src/core/file_sys/card_image.cpp, src/core/file_sys/card_image.h, src/core/loader/xci.cpp
The only reason the getter existed was to check whether or not the program NCA was null. Instead, we can just provide a function to query for the existence of it, instead of exposing it entirely, getting rid of the need to interact with shared_ptr here.
=> XCI: Add function for checking the existence of the program NCA

src/core/core.cpp
`CpuCore()` already does this sort of checking, so we can just call that instead of duplicating the assertions.
=> core: Remove unnecessary assert in ArmInterface()

src/core/file_sys/content_archive.cpp, src/core/file_sys/content_archive.h
This mostly factors out the monster of a constructor into its own constituent functions, which makes each section of behavior a little more readable. Along the way, there were a few other simplifications that were able to be done as well.
=> content_archive: Minor reorganization changes

src/common/alignment.h, src/core/hle/kernel/svc.cpp
The kernel itself checks whether or not the provided addresses are word aligned before continuing, so we should be doing the same.
=> svc: Add missing error checks in svcArbitrateLock/svcArbitrateUnlock

src/core/crypto/partition_data_manager.cpp
Fixes a fatal crash on start when deriving keys.
=> crypto: Use compressed sizes in offset calculation for KIP decompression

src/core/hle/service/aoc/aoc_u.cpp, src/core/hle/service/aoc/aoc_u.h
This event signals the game when new DLC is purchased from the eShop while the game is running. Since, for the forseeable future, yuzu will not have this ability, it seems safe to stub with a dummy event that will never fire. This is needed to boot Sonic Mania Plus (update v1.04).
=> aoc_u: Stub GetAddOnContentListChangedEvent

src/video_core/engines/fermi_2d.cpp, src/video_core/engines/kepler_memory.cpp, src/video_core/engines/kepler_memory.h, src/video_core/engines/maxwell_dma.cpp, src/video_core/engines/maxwell_dma.h, src/video_core/gpu.cpp, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/textures/decoders.cpp, src/video_core/textures/decoders.h
Implements the rest of #1339, using the recently merged flushing code from #1497. Some of this is behind the `use_accurate_gpu_emulation` setting (as otherwise, we avoid flushing in many cases). This is mostly ported over as-is, and needs some testing - I'm not sure what games actually use this
In particular, let me know if there are things that do not work with the `use_accurate_gpu_emulation` setting turned off, and I will try to debug/fix. Also, please let me know if there are any major perf regressions (again, with the setting turned off).
cc @Hexagon12 to assist with testing.
cc @FernandoS27 to improve the swizzle code here, this is based on our old swizzling.
cc @Subv, purely FYI.
=> GPU/DMA: Flush the source region and invalidate the destination region when doing a DMA transfer.

src/core/hle/kernel/svc.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h
Now that the changes clarifying the address spaces has been merged, we can wrap the checks that the kernel performs when mapping shared memory (and other forms of memory) into its own helper function and then use those within MapSharedMemory and UnmapSharedMemory to complete the sanitizing checks that are supposed to be done. This also makes it trivial to add checking to other relevant functions in the future.
=> svc: Add missing sanitizing checks for MapSharedMemory/UnmapSharedMemory

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Initially I didn't want to implement all these instructions at once but it's what the games I tested it with (Xenoblade and L.A.Noire) used. Sadly I didn't see any progression in these titles, probably because of all the other missing features.
I think it deserves an explanation of how this instructions work since they are not handled like `F*` or `I*` instructions.
Most `H*` instructions operate in ~a perverted way~ pairs, that means that they can `ADD`, `MUL` or `FMA` two values at once. These values are packed in registers, immediates... The trick is that when a result is obtained they can do one of four things:
* Set the pair result as-is to the register.
* Set the pair result just to the low part of the register (`Mrg_H0`).
* Set the pair result just to the high part of the register …
=> gl_shader_decompiler: Implement H* instructions

src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_gen.h
The intention of declaring them in gl_shader_decompiler was to be able to use blocks to implement geometry shaders. But that wasn't needed in the end and it caused issues when both vertex stages were being used, resulting in a redeclaration of "position".
=> gl_shader_decompiler: Move position varying declaration back to gl_shader_gen

src/video_core/renderer_opengl/maxwell_to_gl.h
This fixes a TON of game graphical issues.
=> Fixed VAOs Float types only returning GL_FLOAT

src/core/CMakeLists.txt, src/core/hle/service/am/am.cpp, src/core/hle/service/am/applet_ae.cpp, src/core/hle/service/am/applet_oe.cpp, src/core/hle/service/am/idle.cpp, src/core/hle/service/am/tcap.cpp, src/core/hle/service/am/tcap.h, src/core/hle/service/hid/hid.cpp, src/core/hle/service/lbl/lbl.cpp, src/core/hle/service/npns/npns.cpp, src/core/hle/service/npns/npns.h, src/core/hle/service/prepo/prepo.cpp, src/core/hle/service/service.cpp
Keeps the service function table names in sync with the recent updates made to Switchbrew (shoutouts to Hexkyz). Also adds the shells for the npns and tcap services.
=> service: Update service function tables

src/core/hle/kernel/svc.cpp
This should be comparing against the queried process' vma_map, not the current process'. The only reason this hasn't become an issue yet is we currently only handle one process being active at any time.
=> svc: Fix vma boundary check in svcQueryMemory

src/web_service/CMakeLists.txt
Given we link in httplib privately, we can also make the definition enabling OpenSSL support private as well. Prevents leaking a definition into other libraries that link with this one, like the core library.
=> web_service/CMakeLists: Make the CPPHTTPLIB_OPENSSL_SUPPORT constrained to the web_service library only

src/yuzu/CMakeLists.txt
Keeps the definition constrained to the yuzu target and prevents polluting anything else in the same directory (should that ever happen). It also keeps it consistent with how the USE_DISCORD_PRESENCE definition is introduced below it.
=> CMakeLists: Use target_compile_definitions instead of add_definitions to define YUZU_ENABLE_COMPATIBILITY_REPORTING

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp
From my testing this pair behaves just like `SSY` and `SYNC`. From nouveau docs they share the same stack, but calling `SSY` -> `BRK` kills the shader (they are incompatible). This is not emulated because it's very unlikely that a driver/offline compiler would emit an invalid shader.
Renamed the `ssy` stack to `flow` for consistency.
=> gl_shader_decompiler: Implement PBK and BRK

src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_compute.cpp, src/video_core/engines/maxwell_dma.cpp
Silences unused variable and truncation compilation warnings. While we're at it, we can also convert the namespacing over to nested namespace specifiers to keep the source files consistent with the other ones in the same directory.
=> maxwell_dma: Silence compilation warnings

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp
`VSETP`'s behavior similar to `VMAD` but it compares two operands. Thankfully it doesn't do anything weird (like not shifting heights when comparing) so it's pretty straightforward using `VMAD`'s operand unpacking.
This PR also abstracted `VMAD` into a "video" subset (don't blame me for the name, that's how NVidia calls them). The invalid encoding I commented in `VMAD` in fact just killed the shader, I addressed it to emit an `UNREACHABLE()`.
As a side note, this instruction is used to compare `SR_INVOCATION_INFO's third byte <= 0` and then use that predicate to `@PX MOV32I RX, 0x80000000`. RX is then used to determine which `amem` buffer index to write to. Geometry shaders are guarded with `min()` for these high values so it should behave as expected (this was originally added to protect …
=> gl_shader_decompiler: Implement VSETP

src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/hle_ipc.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/process.h, src/core/hle/kernel/server_session.cpp, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/thread.cpp, src/yuzu/debugger/wait_tree.cpp
In the kernel, there isn't a singular handle table that everything gets tossed into or used, rather, each process gets its own handle table that it uses. This currently isn't an issue for us, since we only execute one process at the moment, but we may as well get this out of the way so it's not a headache later on.
Coincidentally, this way makes it much easier to eliminate accessing some of the Core namespace functions directly in kernel code, which is a nice benefit.
=> kernel/process: Make the handle table per-process

CMakeLists.txt, src/web_service/CMakeLists.txt, src/yuzu/CMakeLists.txt
This is more localized to what we want to enforce directory-wise with the project. CMAKE_SOURCE_DIR indicates the root of the source tree, but this would cause the wrong behavior if someone included yuzu as part of a larger buildsystem (for whatever reason). Instead, we want to use the directory where the "project(yuzu)" command was declared as the root path reference.
=> CMakeLists: Use PROJECT_SOURCE_DIR instead of CMAKE_SOURCE_DIR

src/core/hle/kernel/svc.cpp
There seems to be more such as type 1, and 2. Unsure what these currently are but when a game hits them we can investigate and add the rest. Info 1 and Info 2 seems to also provide extra information based on the break. Info 1 usually looks like an address and info 2 looks like a size, however, this also can be zeroed out so the info can be different each type? More research needed but this is a start on better-debugging information.
=> Added break types to svcBreak

src/core/hle/service/acc/acc.cpp, src/core/hle/service/acc/profile_manager.cpp, src/core/hle/service/acc/profile_manager.h, src/core/hle/service/am/am.cpp, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_system.cpp, src/yuzu/configuration/configure_system.h, src/yuzu/configuration/configure_system.ui, src/yuzu/main.cpp, src/yuzu_cmd/config.cpp
tl;dr multiple users and user icons
This adds a UI to manage emulated users along with config support for multiple users and loading of custom icons for users.
For icons, yuzu looks in `%YUZU_DIR%/config/users/<username>.jpg`. It must be a JPEG less than 20kb in size due to switch restrictions. Should no suitable icon be found, a gray background will be used.
The UI allows adding, renaming, and deleting users. When a new user is made, the UUID will be randomly generated. 
Additionally, the right-click open save data menu will let you pick the user.
(NSO NES - icon and name in top left corner)
(Puyo Puyo - custom name in blue box in bottom left corner)
=> qt: Add UI to manage emulated user profiles

src/core/crypto/key_manager.cpp, src/core/file_sys/vfs.cpp
Gets rid of trivial compiler warnings.
=> file_sys: Remove unused variables

src/video_core/engines/maxwell_3d.cpp, src/video_core/textures/decoders.cpp
These are both unused, so we can get rid of them.
=> maxwell_3d/decoders: Remove unused variables

src/core/hle/service/aoc/aoc_u.cpp
We can just call the function instead of duplicating the code here. This also prevents an unused function warning.
We also don't need to take the lambda capture by reference. It's just a u64 value, so by value is fine here.
=> aoc_u: Make use of previously-unused CheckAOCTitleIDMatchesBase() function

src/core/perf_stats.cpp
This hasn't been used since ba8ff096fdc9f7ab101851c4cd06c3244a7d84c3
=> perf_stats: Remove unused variable within DoFrameLimiting()

src/yuzu/bootmanager.cpp
This gets rid of an unnecessary type conversion. We can just use the regular QStringLiteral to already format the string as the type setWindowTitle accepts instead of converting from a std::string instance.
=> bootmanager: Use QStringLiteral instead of std::string to represent the window title.

src/yuzu/game_list.cpp
These are user-facing strings, so they should be marked as translatable
=> game_list: Make game list column headers translatable

src/yuzu/game_list.cpp
We can just use the facilities that Qt provides instead of pulling in stuff from common. While we're at it, we can also simplify the nearby logging statement's argument by just calling .toStdString()
=> game_list: Use QFileInfo instead of common's file functions

src/core/hle/service/hid/controllers/npad.cpp
This also gets rid of variable shadowing related to the lambda parameter a little bit below this code as well.
=> npad: Remove unused controller variable from OnInit()

src/yuzu/debugger/graphics/graphics_breakpoints.cpp, src/yuzu/debugger/graphics/graphics_breakpoints_p.h
`tr()` will not function properly on static/global data like this, as the object is only ever constructed once, so the strings won't translate if the language is changed without restarting the program, which is undesirable. Instead we can just turn the map into a plain old function that maps the values to their equivalent strings. This is also lessens the memory allocated, since it's only allocating memory for the strings themselves, and not an encompassing map as well.
=> graphic_breakpoints: Correct translation of strings in BreakpointModel's data() function

src/audio_core/time_stretch.cpp, src/audio_core/time_stretch.h
This is only stored to, but never read from.
=> time_stretch: Remove unused m_channel_count member variable

src/yuzu/configuration/config.cpp, src/yuzu/configuration/config.h
=>  yuzu/configuration/config: Use a std::unique_ptr for qt_config instead of a raw pointer

src/core/hle/service/acc/profile_manager.cpp, src/core/hle/service/acc/profile_manager.h, src/core/hle/service/am/am.cpp, src/yuzu/configuration/configure_system.cpp, src/yuzu/main.cpp
Now that we can actually use std::optional on macOS, we don't need to continue using boost::optional here.
=> profile_manager: Use std::optional instead of boost::optional

src/yuzu/game_list_worker.cpp
Using fmt here requires unnecessary string conversions back into QString. Instead, we can just use QString's formatting and get the end result of the formatting operation in the proper type.
=> game_list_worker: Use QString's formatting instead of fmt in FormatPatchNameVersions()

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/textures/decoders.cpp
This pull request fixes several issues concerning texture arrays and cubemaps. Before we were reading this types of textures naively without calculating the spacing between them (the mipmaps). With this PR, we correct this issue and add the ability to interpret cubemaps correctly.
As many issues this fixes, it may also bring to light new issues as this textures weren't working correctly and things not shown before will now be shown.
=> rasterizer: Fix Layered Textures Loading and Cubemaps

src/core/hle/ipc.h, src/core/hle/kernel/errors.h, src/core/hle/kernel/server_port.cpp, src/core/hle/kernel/shared_memory.cpp, src/core/hle/kernel/svc.cpp
Amends the holes that we have in our error codes, and gets rid of all the other ones that either aren't used, or don't apply anymore/are holdovers from citra. This knocks out two TODO comments, and keeps the current errors listed to the ones that are actually used within the codebase.
=> kernel/error: Amend error return code values

src/core/file_sys/ips_layer.cpp
Prevents a potential bug when using RLE records in an IPS patch.
=> ips_layer: Use rle_size instead of data_size in RLE patch application

src/core/hle/kernel/process.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h, src/core/hle/service/ldr/ldr.cpp, src/core/loader/nro.cpp, src/core/loader/nro.h
Implements LoadNro function using the existing loader code that we have. This is a really simple and somewhat incomplete implementation, but is enough for basic use cases. With this change and #1556, Super Mario Party now boots.
Partially supersedes #1471
=> Implement the LoadNro functions from the ldr:ro service.

src/core/hle/service/nfp/nfp.cpp, src/core/hle/service/nfp/nfp.h, src/yuzu/main.cpp
We shouldn't silently continue if loading failed, since the general assumption is that no messages showing up implicitly indicates success.
=> yuzu/main: Notify user of loading errors with Amiibo data

src/core/file_sys/card_image.cpp, src/core/file_sys/card_image.h, src/core/file_sys/content_archive.cpp, src/core/file_sys/content_archive.h, src/core/file_sys/partition_filesystem.cpp, src/core/file_sys/partition_filesystem.h, src/core/file_sys/submission_package.cpp, src/core/file_sys/submission_package.h, src/core/file_sys/vfs.h, src/core/file_sys/vfs_layered.cpp, src/core/file_sys/vfs_layered.h, src/core/file_sys/vfs_real.cpp, src/core/file_sys/vfs_real.h, src/core/file_sys/vfs_vector.cpp, src/core/file_sys/vfs_vector.h, src/core/file_sys/xts_archive.cpp, src/core/file_sys/xts_archive.h
When writing VFS, it initally seemed useful to include a function to in-place convert container files into directories in one homogenous directory structure, but re-evaluating it now there have been plenty of chances to use it and there has always been a better way. Removing as it is unused and likely will not be used.
This removes the two overloads of `InterpretAsDirectory` and its backend function `ReplaceFileWithSubdirectory`. Most of these implementations were just stubbed as a sidenote.
=> vfs: Remove InterpretAsDirectory and related functions

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Static cast `size_t` to `GLsizei`
=> gl_rasterizer_cache: Fix compiler warning

src/yuzu/configuration/configure_system.cpp
Tells the user when filesystem operations fail when attempting to set a new icon for a user instead of silently continuing. While we're at it, we can also isolate a few other things about the process to their own functions and use QString where applicable to trim down on conversions from std::string.
=> configure_system: Indicate when filesystem operations fail

src/core/crypto/key_manager.cpp
Crypto revisions are hex numbers and this function only checks if the string is valid for stoul in base 16, so it should be isxdigit.
=> key_manager: Use isxdigit instead of isdigit when reading key file

.travis/macos/build.sh
Enables the usage of further C++ std functions introduced in macOS 10.14.
~~This PR is also required for #1578 for `std::optional::value()`.~~
=> Update MACOSX_DEPLOYMENT_TARGET to 10.14

src/core/hle/kernel/process.h, src/core/hle/kernel/scheduler.cpp, src/core/hle/kernel/scheduler.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/svc.h, src/core/hle/kernel/thread.h
This retrieves:
```cpp
if (curr_thread == handle_thread) {
result = total_thread_ticks + (hardware_tick_count - last_context_switch_ticks);
} else if (curr_thread == handle_thread && sub_id == current_core_index) {
result = hardware_tick_count - last_context_switch_ticks;
}
```
which is fairly trivial to implement, given mostly everything else is in place already, aside from the tick updating itself
=> svc: Implement svcGetInfo command 0xF0000002

.travis/macos/build.sh
Reverts yuzu-emu/yuzu#1581.
The next time, please be more careful when making such changes or approving them.
[**Reason:**](https://github.com/citra-emu/citra/pull/4385#issuecomment-433700338)
> 
> 
> What features?
> 
> AFAIK 10.14 and 10.13 use XCode 10 and thus the same libs so there is 0 benefit and the drawback of supporting only the most recent OSX version which many users still don't use because it has tons of issues. For yuzu this might be ok since you can't run yuzu on osx anyway, but for Citra i don't like that at all
>Also travis currently does not support building with osx 10.14
=> Revert "Update MACOSX_DEPLOYMENT_TARGET to 10.14"

src/video_core/renderer_opengl/gl_rasterizer_cache.h
As requested by @Hexagon12. This fixes Donkey Kong Country: Tropical Freeze.
=> renderer_opengl: Correct bpp value for ASTC_2D_8X5

src/video_core/renderer_opengl/gl_rasterizer_cache.h
apply the same change to the SRGB variant to mimic  FearlessTobi changes
=> renderer_opengl: Correct bpp value for ASTC_2D_8X5_SRGB

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
This fixes textures that showed black for their alphas instead of being see-through.
Before:
After:
=> renderer_opengl: Enable alpha channel for DXT1 texture format

src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/utils.cpp, src/video_core/renderer_opengl/utils.h, src/video_core/utils.h
`video_core/utils.h` had OpenGL-specific code that depended on `glad/glad.h` (which was not included). Instead of adding it, which also poluted the symbols, a new file for those utils was created.
=> video_core: Move OpenGL specific utils to its renderer

src/audio_core/time_stretch.cpp
In the last weeks, many users were complaining about too high latency when using audio stretching.
After bringing this up to @MerryMage, she suggested to switch to the timestretch values/constants of Citra. Doing this cuts back the delay noticeably, while still keeping the audio stretching functionality working without much crackling.
=> time_stretch: Switch to values of Citra

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/renderer_opengl/maxwell_to_gl.h, src/video_core/textures/decoders.h
This is an initial implementation of mipmaps. I've tried to make it as accurate as possible even though there's a innocent workaround: sometimes game will set a mip filter on a texture without mipmaps, instead of forcing out the mip filter, we generate mipmaps on that texture.
=> Implemented Mipmaps

src/core/core.cpp, src/core/core.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/svc.cpp
Many of the Current<Thing> getters (as well as a few others) were missing const qualified variants, which makes it a pain to retrieve certain things from const qualified references to System.
Makes the interface a little more complete for different scenarios
=> core: Add missing const variants of getters for the System class

src/core/hle/ipc_helpers.h, src/core/hle/kernel/hle_ipc.h, src/core/hle/kernel/server_session.cpp
A fairly trivial change. We don't need shared ownership semantics here.
=>  hle_ipc: Make GetDomainMessageHeader return a regular pointer

src/core/hle/service/usb/usb.cpp
Updated based off information on SwitchBrew. Fills out the remaining unknown entries in the table.
=> service/usb: Update IPdSession's function table

src/common/telemetry.h, src/core/telemetry_session.cpp, src/core/telemetry_session.h, src/web_service/telemetry_json.cpp, src/web_service/telemetry_json.h, src/yuzu/compatdb.cpp, src/yuzu/compatdb.h
See citra-emu/citra#4369 for more details.
This PR switches the endpoint for testcases to `api.citra-emu.org/gamedb/testcase` instead of sending them as part of Telemetry. It also adds basic error handling to the compatdb wizard and shows the user a popup in case submission failed.
It also moves the `Report compatibility` button to the emulation tab. This was done to get more users to submit testcase cause it's way more likely a user will visit this tab, than the help tab. If you've got any opinions on this change, don't hesitate to voice them.
=> Port citra-emu/citra#4369: "compatdb: Use a seperate endpoint for testcase submission"

src/core/hle/service/acc/profile_manager.h, src/yuzu/CMakeLists.txt, src/yuzu/configuration/configure_system.cpp, src/yuzu/util/limitable_input_dialog.cpp, src/yuzu/util/limitable_input_dialog.h
Previously, we would let a user enter an unbounded name and then silently truncate away characters that went over the 32-character limit. This is kind of bad from the UX point of view, because we're essentially not doing what the user intended in certain scenarios.
Instead, we clamp it to 32 characters and make that visually apparent in the dialog box to provide a name for a user.
=> configure_system: Contrain profile usernames to 32 characters

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/surface.cpp, src/video_core/surface.h, src/video_core/textures/astc.cpp, src/video_core/textures/astc.h, src/video_core/textures/decoders.cpp, src/video_core/textures/decoders.h, src/yuzu/debugger/graphics/graphics_surface.cpp
This fixes a few possible memory corruptions caused by ASTC formats and adds support for layered ASTC textures.
=> Implement ASTC Textures 5x5 and fix a bunch of ASTC texture problems

src/yuzu/main.cpp, src/yuzu/main.h, src/yuzu/main.ui
Opens a windows explorer/file manager window at the user's yuzu folder (`%APPDATA%/yuzu` on windows).
Meant to make following guide or making configuration changes easier.
=> qt: Add help option to open yuzu folder

src/common/logging/backend.cpp, src/common/logging/backend.h, src/yuzu/main.cpp, src/yuzu_cmd/yuzu.cpp
This shows the log in the Output window in Visual Studio, or whatever other debugger you use on Windows, like it does in Dolphin.
=> logging: Add DebuggerBackend for logging to Visual Studio

src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_resource_manager.cpp, src/video_core/renderer_opengl/gl_resource_manager.h, src/video_core/renderer_opengl/gl_shader_manager.h
Those implementations are quite costly, so there is no need to inline them to the caller.
Ressource deletion is often a performance bug, so in this way, we support to add breakpoints to them.
=> gl_resource_manager: Split implementations in .cpp file.

src/core/hle/kernel/svc.cpp
info1 and info2 seem to sometimes hold an address to a buffer, this is usually 4 bytes or the size of the int and contains an error code. There are other circumstances where it can be something different so we hexdump these to examine them at a later date.
=> svcBreak now dumps information from the debug buffer passed

src/video_core/CMakeLists.txt, src/video_core/rasterizer_cache.cpp, src/video_core/rasterizer_cache.h
Ensures that destruction will always do the right thing in any context.
=> rasterizer_cache: Add missing virtual destructor to RasterizerCacheObject

src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h
This PR starts with the idea to skip some state lookups if the state is clean. This shall reduce the overhead per draw call a tiny bit.
=> gl_rasterizer: Skip VAO binding if the state is clean.

src/video_core/renderer_opengl/gl_rasterizer.cpp
Static cast `s32 `to `GLfloat`
=> gl_rasterizer: Fix compiler warnings

src/yuzu/main.cpp
When @adityaruplaha ported https://github.com/yuzu-emu/yuzu/commit/958c98bdaedc8b496f62967142e5bf4f448260b2 from Citra to yuzu, he forgot a `!`, causing the stuck-in-fullscreen bug to reappear.
=> yuzu: Add a missing "!" to fix the stuck-in-fullscreen bug

src/yuzu/main.cpp
=> yuzu/main: Fix compiler warning

src/core/hle/kernel/svc.cpp, src/core/hle/service/spl/module.cpp, src/core/hle/service/spl/module.h, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_system.cpp, src/yuzu/configuration/configure_system.ui, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h
Two-fold:
- Switch to `std::mt19937` for rng bytes in `csrng` service. This allows determinism given the same seed.
- Add UI options to use a random seed or a set seed. If a seed is not set, `csrng` will use `std::time(nullptr)` to get a seed.
=> csrng: Add config option to set RNG seed

src/core/file_sys/control_metadata.cpp, src/core/file_sys/control_metadata.h, src/core/file_sys/savedata_factory.cpp, src/core/file_sys/savedata_factory.h, src/core/hle/service/filesystem/filesystem.cpp, src/core/hle/service/filesystem/filesystem.h, src/core/hle/service/filesystem/fsp_srv.cpp, src/core/hle/service/filesystem/fsp_srv.h, src/core/hle/service/ns/ns.cpp, src/core/loader/nro.cpp
This includes:
- `fsp_srv` 61: `OpenSaveDataInfoReaderBySaveDataSpaceId` - This returns an object capable of iterating over the currently present saves on the system.
- `fsp_srv` `ISaveDataInfoReader`: The aforementioned iterator object -- I implemented it by iterating over all of the directories in the SaveDataSpace (i.e. /nand/user/save) and filling a vector of SaveDataInfo objects using the directory data.
- `fsp_srv` `ISaveDataInfoReader` 0: `ReadSaveDataInfo` - Reads a game-provided number of entries from the total, resuming where left off between successive calls.
- `ns:am` 400: `GetApplicationControlData` - This returns the raw NACP and icon bytes given the title ID. The data source of this for this implementation is the registration cache (installed titles).
Finally, some basic …
=> [ns|fsp_srv]: Implement various functions to boot Checkpoint

src/core/hle/service/audio/audren_u.cpp
These appear to be a basic getter and setter pair based off RE, so these are fairly trivial to implement and get out of the way.
=> hle/audren_u: Implement Get/SetRenderingTimeLimit

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h
Avoids a breach of responsibilities in the interface and keeps the direct code for memory management within the VMManager class with the rest of the related code. On the upside, this finally allows reporting heap memory usage, since the necessary members for doing so are now accessible.
=>  kernel/process: Migrate heap-related memory management out of the process class and into the vm manager

src/video_core/renderer_base.cpp
Keeps the base class source files implementation-agnostic.
=> video_core/renderer_base: Remove GL include from the renderer base class files

src/yuzu/main.ui
As requested by @wwylele and @B3n30, it makes more sense for it to be in the `File` menu.
=> qt: Move Open yuzu Folder action from Help to File

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
After profiling yuzu I recognized that in some szenarios quite some time is taken by allocating memory in calls of `CopySurface`. ~~So instead of reallocating memory over and over again a reserved_texture_data_memory in form of a std::vector is used.~~ We do not need to do that.
=> gl_rasterizer_cache: CopySurface optimization

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/svc.cpp, src/core/settings.h, src/yuzu/configuration/configure_system.cpp, src/yuzu/configuration/configure_system.ui
Addresses outlying concerns with #1670.
- Use 32-bit random seed to match kernel behavior
- Use random generator to generate per-core values for svcGetInfo RandomEntropy
=> svc: Use proper random entropy generation algorithm

src/core/hle/service/service.cpp
When yuzu is compiled in release mode this function is unused, however, when compiled in debug mode, it's used within a LOG_TRACE statement. This prevents erroneous compilation warnings about an unused function (that isn't actually totally unused).
=> service: Mark MakeFunctionString with the [[maybe_unused]] attribute.

src/core/hle/service/nfp/nfp.cpp
The previous expression would copy sizeof(size_t) amount of bytes (8 on a 64-bit platform) rather than the full 10 bytes comprising the uuid member.
=> nfp: Correct erroneous sizeof expression within GetTagInfo()

src/yuzu/configuration/configure_system.ui
There's no need for translators to concern themselves with the validation mask used by the entry field.
=> yuzu/configure_system: Mark the entropy mask string as nontranslatable

src/core/hle/service/acc/acc.cpp
empty() in this case will always return false, since the returned container is a std::array. Instead, check if all given users are invalid before returning the error code.
=> service/acc: Correct error case within TrySelectUserWithoutInteraction()

src/core/hle/service/audio/audren_u.cpp
Based off RE, they both currently go through the same codepath with no difference in behavior.
=> service/audren_u: Forward RequestUpdateAuto through the same function as RequestUpdate

src/core/file_sys/bis_factory.cpp, src/core/file_sys/bis_factory.h, src/core/file_sys/patch_manager.cpp, src/core/hle/service/filesystem/filesystem.cpp, src/core/hle/service/filesystem/filesystem.h, src/core/loader/nso.cpp, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_debug.cpp, src/yuzu/configuration/configure_debug.ui, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h
As there isn't an accessor for NSOs in AppLoader (and I didn't want to clutter the interface), this takes an approach similar to Dolphin's texture dumper.
This adds a setting to the Debug setting which, when checked, will dump any/all NSOs the emulator attempts to load. 
This is accomplished by adding a check to the `dump_nso` flag in the `PatchNSO` method of `PatchManager`. The AppLoader(s) call this as part of the normal NSO loading routine. The `PatchNSO` function will then dump the NSOs to `yuzu/dump/<title id>/nso/<nso build id>.nso`.
The goal with the `Dump` UI section is to eventually have other game data to dump, and have it all appear in the same place.
=> patch_manager: Add support for dumping uncompressed NSOs

src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h
The code in both places was the same verbatim, so we can extract it to a function to deduplicate the logic.
=> kernel/thread: Deduplicate scheduler switching code

src/core/hle/service/spl/module.cpp
Prevents returning the same value every single call.
=> csrng: Use random integer distribution instead of raw engine

src/core/file_sys/errors.h, src/core/hle/result.h, src/core/hle/service/filesystem/filesystem.cpp, src/core/hle/service/filesystem/fsp_srv.cpp
Makes the error code definitions more succinct that they previously were. We also only keep around the error code values that we actually make use of. While we're at it, we can also move the two random straggling error codes out of result.h and into file_sys/errors with the rest of the filesystem error codes.
=> file_sys/errors: Clean up error code values

src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_state.h
Makes float -> integral conversions explicit via casts and also silences a sign conversion warning.
=> gl_state: Amend compilation warnings

src/core/file_sys/card_image.cpp, src/core/file_sys/card_image.h, src/core/file_sys/content_archive.cpp, src/core/file_sys/content_archive.h, src/core/file_sys/registered_cache.cpp, src/core/file_sys/registered_cache.h, src/core/file_sys/submission_package.cpp, src/core/file_sys/submission_package.h, src/core/hle/service/filesystem/filesystem.cpp, src/core/hle/service/filesystem/filesystem.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_gamelist.cpp, src/yuzu/configuration/configure_gamelist.ui, src/yuzu/game_list.cpp, src/yuzu/game_list_worker.cpp, src/yuzu/ui_settings.h
When using a large game list with yuzu (20+ titles), the refresh takes an upwards of 15 seconds, which is really unreasonable. This PR adds some fixes to mitigate this.
1. Share a `KeyManager` instance between NCAs in an NCA container (e.g. NSP/XCI/RegisteredCache). Since each instance of `KeyManager` needs to read all the keyfiles and parse them, this can cut down on time for users with a large concentration of installed/NSP/XCI titles or who have large key files.
2. Avoid recreating a new `RegisteredCacheUnion` on every request for the installed titles. Now it will only initialize it on first use and then return a `shared_ptr` to that instead of creating a new one and returning a `unique_ptr`. This should save a lot of time for users with large or very populated NAND/SD partitions as it …
=> game_list: Optimize game list refresh

src/core/hle/kernel/svc.cpp, src/core/hle/kernel/svc_wrap.h
~~Rayman Legends: Definitive Edition goes from an instant crash on boot into a fully working menu.~~
~~Rayman Legends: Definitive Edition was crashing on boot before and is now playable.~~
Rayman Legends: Definitive Edition was crashing on boot before and now is playable now without the uniformity check of the memory. To provide these checks some changes to the memory manger may be required (see comment by @lioncash).
Impementation based off suggested code by @lioncash
=> Implement SetMemoryPermission

src/core/hle/kernel/errors.h, src/core/hle/kernel/svc.cpp
Similar to PR #1706, which cleans up the error codes for the filesystem code, but done for the kernel error codes. This removes the ErrCodes namespace and specifies the errors directly. This also fixes up any straggling lines of code that weren't using the named error codes where applicable.
=> kernel/errors: Clean up error codes

src/core/hle/service/audio/hwopus.cpp
hwopus: DecodeInterleavedWithPerformance: Fix ordering of output parameters.
- Fixes audio in Pokemon: Let's Go Pikachu and Let's Go Eevee.
Thank you to @gdkchan for spotting the issue here.
Fixes #1715.
=> hwopus: DecodeInterleavedWithPerformance: Fix ordering of output parameters.

.travis/linux-mingw/docker.sh, appveyor.yml
**Problem:**
Game icons do not show in mingw builds
**Cause:**
Missing libjpeg dll
**Solution:**
This PR (hopefully). I don't currently have a Linux environment set up to fully test this.
=> Include QT imageformat dependencies with releases

src/core/hle/service/vi/vi.cpp
Used by homebrew on exit. According to switchbrew, returns an empty response parcel with one zero in it.
=> vi: Implement TransactParcel for Disconnect and DetachBuffer

src/video_core/renderer_opengl/gl_rasterizer.cpp
Remove an expression carried from Citra. While we have to implement clip distances at some point, having it enabled when it's never set explicitly is wrong.
Fixes a half-black screen issue on Windows' Intel driver.
=> gl_rasterizer: Remove default clip distance

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/textures/decoders.cpp, src/video_core/textures/decoders.h
=> Tegra::Texture::UnswizzleTexture: Eliminated unnessessary memory allocation and copy

.travis/clang-format/build.sh, .travis/clang-format/deps.sh, .travis/clang-format/docker.sh
Based on citra-emu/citra#4129. Requires citra-emu/build-environments#7.
=> travis: Use pre-built image for clang-format target

src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/process.cpp, src/core/hle/kernel/resource_limit.cpp, src/core/hle/kernel/resource_limit.h, src/core/hle/kernel/svc.cpp
Cleans out the citra/3DS-specific implementation details that don't apply to the Switch. Sets the stage for implementing ResourceLimit instances properly. If there's anything that looks like its missing data-structure-wise, this is intentional, I know about the missing members. I've not included those in this PR. They will be included within the follow-up where they're more relevant.
While we're at it, remove the erroneous checks within CreateThread() and SetThreadPriority(). While these are indeed checked in some capacity, they are not checked via a ResourceLimit instance.
In the process of moving out Citra-specifics, this also replaces the system ResourceLimit instance's values with ones from the Switch.
=> kernel/resource_limit: Clean up interface

src/core/hle/service/lm/lm.cpp
This service function was likely intended to be a way to redirect where the output of a log went. e.g. Firing a log over a network, dumping over a tunneling session, etc, rather than kicking it to the default output.
Given we always want to see the log and not change its output destination. It's one of the lucky service functions where the easiest implementation is to just do nothing at all and return success.
=> lm: Implement SetDestination by doing nothing

src/core/file_sys/card_image.h
Fills out the struct according to information provided by SwitchBrew
While not directly used anywhere, it's better than a single ambiguous blob of data
=> file_sys/card_image: Provide named members for the GamecardInfo struct

src/common/assert.h
Previously it was only logging an error message which
1. Isn't what we only want it to do
2. Isn't what UNIMPLEMENTED_MSG does (it properly asserts).
This makes the behavior of the two macros uniform.
This also introduces two other macros that are likely more useful for the graphics and video code, UNIMPLEMENTED_IF and UNIMPLEMENTED_IF_MSG, which allows asserting on a conditional, like a regular assertion.
The rationale behind this is it allows a dev to disable unimplemented feature assertions (which can occur in an unrelated work area), while still enabling regular assertions, which act as behavior guards for conditions or states which must not occur. Previously, the only way a dev could temporarily disable asserts, was to disable the regular assertion macros, which has the downside of …
=> common/assert: Make the UNIMPLEMENTED macro properly assert

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h
<random> isn't necessary directly within the header and can be placed in the cpp file where its needed. Avoids propagating the standard random generation utilities via a header file.
=> kernel/process: Move <random> include to the cpp file

src/core/hle/service/ldr/ldr.cpp
The separate enum isn't particularly necessary here, and the values can just be directly put into the ResultCode instances, given the names are also self-documenting here.
=> ldr: Clean up error codes

src/core/hle/kernel/shared_memory.cpp, src/core/hle/kernel/shared_memory.h, src/core/hle/kernel/svc.cpp
Makes it nicer to reason about the internals of the shared memory instances, by exposing only what is necessary to non-kernel code. In particular, we don't need to directly expose any of the memory-specific data members. Each commit contains rationale to clarify themselves
=> kernel/shared_memory: Make data members private, plus minor interface changes

src/core/hle/service/am/am.cpp
Corrects a build failure that occurred due to commits being merged that utilized previously public shared memory internals before merging the shared memory change itself.
=> am: Correct build failure

src/video_core/engines/maxwell_3d.cpp
- Fixes rendering regression with Sonic Mania.
=> maxwell_3d: Initialize rasterizer color mask registers as enabled.

src/common/math_util.h
Mostly just cleaning out old code. It also allows Rectangle to be constexpr constructible, which allows other data structures containing Rectangle instances to also be constexpr constructible.
=> common/math_util: Minor cleanup

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
The following example sets 1 to `$r20`:
```asm
mov32i 0x0 0xdeadbeef 0xf
mov32i $r20 0x00000001 0xf
iadd $r20 $r20 0x0
```
That implies that writing to `RZ` (0x0 in `envyas` syntax) is a nop (reading from it always returns zero). I didn't test what happens to condition codes in those cases, but that's beyond the scope of `SetRegister`.
=> gl_shader_decompiler: Remove UNREACHABLE when setting RZ

src/core/hle/service/am/am.cpp, src/core/hle/service/am/applets/applets.cpp, src/core/hle/service/am/applets/applets.h, src/core/hle/service/am/applets/software_keyboard.cpp, src/core/hle/service/am/applets/software_keyboard.h
Mostly just cleans up the comment locations to get rid of wonky wrapping, making it nicer to read vertically. It also cleans up the inclusions and moves the broker instance itself into the Applet instance.
=> am/applets: Minor cleanup

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Instead of using `LOG_CRITICAL` + `UNREACHABLE`, this replaces it with `UNIMPLEMENTED` and friends introduced in #1748 when applicable.
=> gl_shader_decompiler: Use UNIMPLEMENTED when applicable

src/video_core/gpu.cpp, src/video_core/renderer_opengl/renderer_opengl.cpp
This fixes Bayonetta 2 and Okami HD crashes.
=> Use default values for unknown framebuffer pixel format

src/core/hle/service/hid/controllers/debug_pad.cpp
Prevents memory exceptions when the debug pad is enabled.
=> debug_pad: Avoid loading input for nonexistent buttons (Home and Screenshot)

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Currently `texture*` calls can generate the following (pseudo-)code:
```glsl
{
vec2 coords = vec2(...);
gpr1 = texture(tex, coords, gpr2).x;
gpr2 = texture(tex, coords, gpr2).y;
gpr3 = texture(tex, coords, gpr2).z;
gpr4 = texture(tex, coords, gpr2).w;
}
```
`gpr2` is overwrited there. This PR attempts to address that using a temporal variable like `coords`.
This may fix some games, but I couldn't find any noticeable issue being fixed.
=> gl_shader_decompiler: Fix register overwriting on texture calls

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Implements predicate comparison 11 (0xB), also known as LessEqualWithNan.
Fixes a crash while trying to go ingame in L.A. Noire.
Fixes trainer battle crashes in Pokemon Let's Go.
=> Added predicate comparison LessEqualWithNan

src/core/CMakeLists.txt, src/core/hle/service/am/am.cpp, src/core/hle/service/am/applets/stub_applet.cpp, src/core/hle/service/am/applets/stub_applet.h
This will log all data it receives, log all calls to its methods and push dummy data into both channels on execution.
This should work for most games that regressed with #1667, but some may still svcBreak. This is simply because they expect real data for the results instead of zeroes.
This is intended to be a temporary solution to the problems exposed by #1667.
=> applets: Add StubApplet and use it as fallback when AppletId is not implemented

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Renamed `control code` to `condition code`.
Also, using `P2R` I found out which internal flags Maxwell has:
* Zero flag (the result is zero).
* Sign flag (the result is negative).
* Carry flag.
* Overflow flag.
Those four are named like that in GLSL instead of using `internalFlag`.
=> gl_shader_decompiler: Rename cc to condition code and name internal flags

src/core/file_sys/patch_manager.cpp, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_debug.cpp, src/yuzu/configuration/configure_debug.ui, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h
As requested by someone in discord, this adds the ability to replace the compressed NSOs in the ExeFS.
The directory structure is:
- mod_dir/
- exefs/
- <ips/ipswitch patches also go here, but are ignored by lfs>
- main
These patches will be listed as LayeredExeFS in the game list to avoid collision/confusion with normal RomFS-based LayeredFS. ex: 
Here is an example I did replacing the Puyo Puyo main NSO with a null file:
(as expected; a null file is not a valid NSO)
Finally, to make modding easier, this adds a checkbox to the UI options to `Dump ExeFS`
When this box is checked, any game booted will have its ExeFS dumped to `yuzu/dump/<title id>/exefs`
=> patch_manager: Add support for applying LayeredFS patches to ExeFS

src/core/hle/service/am/am.cpp, src/core/hle/service/vi/vi.cpp, src/yuzu/configuration/configure_graphics.ui
Specifying an internal resolution in yuzu now will report the scaled changes to vi and am.
=> Report resolution scaling support for vi and am

src/core/hle/service/filesystem/filesystem.cpp, src/core/hle/service/filesystem/filesystem.h
Avoids a crash when the user tries to change the NAND or SDMC directory.
Thanks to @MysticExile for finding this.
=> filesystem: Clear registered union paths on factory creation

src/core/hle/service/sm/sm.cpp, src/core/hle/service/sm/sm.h
These are needed by Edizon to boot. They are used to see if a user is using SX OS, as SX OS registers a custom service called 'tx' and attempting to register a service of the same name lets the application know if it is present.
=> sm: Implement RegisterService and UnregisterService

src/core/hle/kernel/svc.cpp
libnx uses this behavior for firmware version detection: https://github.com/switchbrew/libnx/commit/6ef26bff1a77e2ac0c9d026024a4f010889a67e6
Before, `UNIMPLEMENTED()` would crash the emulator.
=> svc: Return ERR_INVALID_ENUM_VALUE from svcGetInfo

src/video_core/engines/shader_bytecode.h, src/video_core/engines/shader_header.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Clip distances are packed in 2 `vec4`s. Also added header declarations for `ImapSystemValuesC`
* Used in L.A. Noire.
=> gl_shader_decompiler: Implement clip distances

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
After intense RE and some docs on nouveau, I got all the encodings for coordinates, this fixes a bunch of graphical issues. Among them, the famous fish-eye effect on SMO.
=> Fixed Coordinate Encodings in TEX and TEXS instructions

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This instruction sets predicates from a register based on a mask. It can also set condition codes but these are not implemented here.
This instruction is used by Pokémon Let's Go, but I don't have those games to test this implementation. That being said, it is tested against an offline shader.
=> gl_shader_decompiler: Implement R2P_IMM

src/core/hle/service/sm/sm.cpp, src/core/hle/service/sm/sm.h
Avoids the need to create a copy of the std::string instance (potentially allocating).
The only reason RegisterService takes its argument by value is because it's std::moved internally
=> service/sm: Take std::string by const reference in UnregisterService

src/video_core/command_processor.cpp, src/video_core/engines/fermi_2d.cpp, src/video_core/engines/kepler_memory.cpp, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/engines/maxwell_dma.cpp, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_buffer_cache.h, src/video_core/renderer_opengl/gl_rasterizer.cpp
This PR skips reemitting the vertex buffer state if the maxwell registers haven't been touched. But as the vertex buffers obviously depend on the main memory, we need to invalidate this state whenever the main memory may has been touched. This seems to be harder than expected.
=> gl_rasterizer: Skip VB upload if the state is clean.

src/core/hle/kernel/resource_limit.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/svc_wrap.h
Implements the four resource limit API functions that are exposed as part of the service call interface. Specifically:
1. svcCreateResourceLimit
Attempts to create a resource limit instance and allocate a handle for it within the current process' handle table. If this isn't able to occur, then a relevant error is returned where applicable. Currently, error conditions occur if: 
- Allocation of the resource limit instance itself fails.
- If the handle couldn't be allocated for the resource instance.
2. svcGetResourceLimitLimitValue
Attempts to retrieve the limiting value for a particular resource category from a provided resource limit instance (provided as a handle). If this cannot be done, then a relevant error is returned. Currently, error conditions occur if: 
- An invalid resource …
=> svc: Implement svcCreateResourceLimit, svcGetResourceLimitCurrentValue(), svcGetResourceLimitLimitValue(), and svcSetResourceLimitLimitValue()

src/core/gdbstub/gdbstub.cpp
Previously this would cause an implicit truncation warning about assigning a u64 value to a u32 variable without an explicit cast.
=> gdbstub: Silence value truncation warning within FpuWrite()

src/video_core/renderer_opengl/gl_rasterizer.cpp
On invalidating the streaming buffer, we need to reupload all vertex buffers.
But we don't need to reconfigure the vertex format.
This was a (silly) misstake in #1723.
Thanks at Rodrigo for discovering the issue.
Fun fact, as configuring the vertex format also invalidate the vertex buffer,
this misstake had no affect on the behavior.
=> gl_rasterizer: Fixup for #1723.

src/core/file_sys/control_metadata.cpp
While we're at it, organize the array linearly, since clang formats the array elements quite wide length-wise with the addition of the missing 'u'.
Technically also fixes patch lookup and icon lookup with Portuguese, though I doubt anyone has actually run into this issue.
=> control_metadata: Correct typo in language name (Portugese -> Portuguese)

src/core/hle/service/acc/acc.cpp, src/core/hle/service/acc/profile_manager.cpp, src/core/hle/service/acc/profile_manager.h
The ProfileData is a 0x80-sized structure that stores various pieces of miscellaneous data for the account. Previously, it was simply ignored and always 0, which is not hw-accurate. Even though it is still not used by yuzu, only games/applications, we can now avoid neutering the profiles.dat by loading and saving this data.
=> profile_manager: Save and load ProfileData from disk

src/core/file_sys/registered_cache.cpp, src/core/file_sys/registered_cache.h, src/yuzu/main.cpp
These parameters don't need to utilize a shared lifecycle directly in the interface. Instead, the caller should provide a regular reference for the function to use. This also allows the type system to flag attempts to pass nullptr and makes it more generic, since it can now be used in contexts where a shared_ptr isn't being used (in other words, we don't constrain the usage of the interface to a particular mode of memory management).
=> file_sys/registered_cache: Use regular const references instead of std::shared_ptr for InstallEntry()

src/video_core/engines/fermi_2d.cpp, src/video_core/morton.cpp, src/video_core/morton.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/textures/decoders.cpp, src/video_core/textures/decoders.h, src/video_core/textures/texture.h
This fixes textures in Octopath and some indie games.
=> Texture decoder: Implemented Tile Width Spacing

src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_state.h
fast fix for issues caused by the viewport_transform_enabled register and add the missing clipdistance enabled register that are needed for  https://github.com/yuzu-emu/yuzu/pull/1783 to work correctly
=> Fix clip distance and viewport

src/core/hle/service/set/set.cpp, src/core/hle/service/set/set.h
This simply converts a provided index into its respective language code. i.e. making a language code from an index.
=>  service/set: Implement MakeLanguageCode

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Several fixes to how the rasterizer cache does surface copies, particularly with non-2D to 2D copies. Fixes some rendering issues with The Legend of Zelda: Breath of the Wild. This might cause issues or performance regressions in other games, so we'll let it soak in Canary a bit - please report back if you notice these.
* Remove BlitSurface and replace with more accurate copy.
* BlitSurface with different texture targets is inherently broken.
* When target is the same, we can just use FastCopySurface.
* Update AccurateCopySurface to flush complete source surface.
=>  gl_rasterizer_cache: Fix several surface copy issues.

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/yuzu/main.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
This removes unused structs and booleans from the rasterizer and adds the required dependency on `ARB_direct_state_access`, aside from two style changes in `gl_rasterizer_cache`.
=> video_core: Minor style changes

src/video_core/renderer_opengl/gl_shader_manager.h
Instead of calling `glUseProgramStages` every draw call, just call it when the programs have changed.
=> gl_shader_manager: Update pipeline when programs have changed

src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_gen.h
Intel's blob driver crops parts of the screen when clip distances are enabled but not set in a shader. This enables them when they are set in the register and in the shader as a workaround for this issue.
=> gl_rasterizer: Enable clip distances when set in register and in shader

src/core/hle/service/audio/audout_u.cpp
Orders the constructor initializer list the same way the members of the class are declared. Prevents -Wreorder warnings
=> service/audio/audout_u: Amend constructor initialization list order

src/core/file_sys/vfs.cpp, src/core/file_sys/vfs.h, src/core/hle/service/filesystem/filesystem.cpp, src/core/hle/service/filesystem/filesystem.h, src/core/hle/service/filesystem/fsp_srv.cpp
This is the same behavior-wise as DeleteDirectoryRecursively, with the
only difference being that it doesn't delete the top level directory in
the hierarchy, so given:
```
dir/
- some_other_dir/
- File.txt
- OtherFile.txt
```
The end result is just:
```
dir/
```
=> service/fsp_srv: Implement CleanDirectoryRecursively

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This introduces an object to gain scope that will be automatically returned when it's destroyed (similar to `std::scoped_lock`. It also does some clean up in the code in regards to texture instruction generation. It should use a table, but I'll leave that for later.
Reintroduces the usage of multiple `texture` calls since it was being used in some places but not others. `WriteTexsInstruction` no longer takes `coords` as argument because it sometimes requires more arguments. All these values (`coords` included) have to be declared in the calling function and not the callee.
=> gl_shader_decompiler: Introduce a scoped object and style changes

src/core/crypto/key_manager.cpp, src/core/file_sys/patch_manager.cpp, src/core/file_sys/romfs_factory.cpp, src/core/hle/service/aoc/aoc_u.cpp, src/core/hle/service/filesystem/filesystem.cpp, src/core/hle/service/filesystem/filesystem.h, src/yuzu/game_list_worker.cpp, src/yuzu/main.cpp
We can just return a new instance of this when it's requested. This only ever holds pointers to the existing registed caches, so it's not a large object. Plus, this also gets rid of the need to keep around a separate member function just to properly clear out the union.
Gets rid of one of five globals in the filesystem code.
=> filesystem: De-globalize registered_cache_union

src/yuzu/configuration/configure_audio.h, src/yuzu/configuration/configure_debug.h, src/yuzu/configuration/configure_dialog.h, src/yuzu/configuration/configure_gamelist.h, src/yuzu/configuration/configure_general.h, src/yuzu/configuration/configure_graphics.h, src/yuzu/configuration/configure_input.cpp, src/yuzu/configuration/configure_input.h, src/yuzu/configuration/configure_web.h
Narrows the visible scope of functions, remove redundant uses of the private access specifier, and gets rid of a case where a compilation failure could potentially occur.
=> yuzu/configuration: Minor clean-up related changes

src/core/hle/kernel/svc.cpp
Makes the behaviour for implemented info categories more closely match how the kernel itself handles it. This also fixes a minor bug with how the process instance was being retrieved. We weren't going through the handle table when we should have been. See the second commit message for a more in-depth explanation about that.
=> svc: Reorganize svcGetInfo, handle more error cases for existing implemented info categories

src/yuzu/game_list_worker.cpp
Cleans up string usage in FillControlMap() and moves the creation of game list entries to its own function to get rid of code being duplicated twice.
=> yuzu/game_list_worker: Minor cleanup and code deduplication

src/core/CMakeLists.txt, src/core/file_sys/system_archive/ng_word.cpp, src/core/file_sys/system_archive/ng_word.h, src/core/file_sys/system_archive/system_archive.cpp, src/core/file_sys/system_archive/system_archive.h, src/core/file_sys/vfs_vector.cpp, src/core/file_sys/vfs_vector.h, src/core/hle/service/filesystem/fsp_srv.cpp
This adds:
- A framework for synthesizing system archives and returning them to the game, using a table of functions similar to our HLE impl.
- A fallback to this framework if the user doesn't have the correct archive in NAND
- An implementation of NgWord (806) under this.
This works vastly different from citra's impl, which used externally generated romfses packed into cpp files. This stores the actual contents of the files within the archive (i.e. version.dat for NgWord) and then synthesizes the directory structure and romfs on the fly, resulting in cleaner more updatable code.
Tested in Ultra Street Fighter II, which performs exactly the same with or without it.
=> file_sys: Implement open source system archives

src/core/memory.cpp
When Yuzu loads a title, it defaults to assuming a 39-bit address space (before loading title metadata). This causes roughly 1 GB in allocations for VMManager's page-table vectors.
For a 36-bit title (such as BOTW), VMManager does resize the vectors to the lower size (~128MB), but the uCRT at least isn't actually lowering the vectors' capacity - the 800 MB is still committed.
This change just adds std::vector::shrink_to_fit calls after the resizes, which successfully frees the space in my testing. This would invalidate any references to the vector data, but in the event of a Resize I don't think (?) there should be any.
This does lower memory usage in steady-state in BOTW by ~800 MB as seen through task manager. Another approach would be to default to a 36-bit address space (though a …
=> Perf: Call shrink_to_fit after page-table vector resizing to actually reduce vector capacity

src/core/hle/service/ldr/ldr.cpp
We don't need to specify all of the ARM interfaces explicitly.
=> service/ldr: Deduplicate instruction cache clearing code in LoadNro()

src/core/file_sys/system_archive/ng_word.cpp, src/core/file_sys/system_archive/system_archive.cpp
This allows the array to be constexpr. std::function is also allowed to allocate memory, which makes its constructor non-trivial, we definitely don't want to have all of these execute at runtime, taking up time before the application can actually load.
=>  system_archive: Use a regular function pointer instead of std::function for the file-scope system archive array

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Implements `F16` variant for `TEXS`. It was hidden in bit 60 (0 is `F16` and 1 is `F32`), values are returned in packs like the other H* instructions.
* Used by Undertale
(and some other OpenGL ES games)
=> gl_shader_decompiler: Implement TEXS.F16

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h
Instead of reusing the same framebuffer and attaching different images to it, this caches the framebuffer configuration and uses a map-based cache to store and retrieve the framebuffer handles.
I'm not happy with `FramebufferCacheKey`'s layout.
=> gl_rasterizer: Implement a framebuffer cache

src/core/hle/kernel/object.cpp, src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/readable_event.cpp, src/core/hle/kernel/readable_event.h, src/core/hle/kernel/svc.cpp
While partially correct, this service call allows the retrieved event to be null, as it also uses the same handle to check if it was referring to a Process instance.
This also corrects Process' inheritance, given it's actually a synchronizable object that can be waited upon for state changes.
=>  kernel/svc: Correct behavior of svcResetSignal() 

src/core/loader/deconstructed_rom_directory.h, src/core/loader/elf.h, src/core/loader/loader.h, src/core/loader/nax.cpp, src/core/loader/nax.h, src/core/loader/nca.h, src/core/loader/nro.h, src/core/loader/nso.h, src/core/loader/nsp.h, src/core/loader/xci.h, src/yuzu/game_list_worker.cpp
No Loader implementations actually modify instance state via this function (and it would be questionable to do that in the first place given the name), so we can make this a const member function. While we're at it, this also gets rid of trivially removable duplicated calls to the function, given the backing operation for it isn't always trivial, reducing the amount of work done to simply display an entry in the game list
=> loaders: Make GetFileType() a const qualified member function

src/common/logging/backend.cpp
Yay for even needing to do this.
**Original reason:**
As Windows multi-byte character codec is unspecified while we always assume std::string uses UTF-8 in our code base, this can output gibberish when the string contains non-ASCII characters. ::OutputDebugStringW combined with Common::UTF8ToUTF16W is preferred here.
=> Backport review comment from citra-emu/citra#4418

src/core/hle/service/service.cpp, src/core/hle/service/sm/sm.cpp
Tidies up the pre-C++17 code to use structured bindings where applicable and cleans up a few other minor things along the way.
=> hle/service, hle/sm: Minor cleanup

src/core/hle/kernel/shared_memory.cpp, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h, src/core/memory.cpp
This was only ever public so that code could check whether or not a handle was valid. Instead of exposing the object directly and allowing external code to potentially mess with the map contents, we just provide a member function that allows checking whether or not a handle is valid.
This makes all member variables of the VMManager class except for the page table private.
=> vm_manager: Make vma_map private

src/core/file_sys/savedata_factory.cpp
`TemporaryStorage`: Mimics hardware assertions that data is not persisted.
`CacheStorage`: Allows many new games to boot (1-2-Switch, Minecraft, Rocket League, etc). Done at path `/cache/<title_id>`, which is our best guess for how the system actually does it.
=> savedata_factory: Add CacheStorage and delete TemporaryStorage on boot

src/core/hle/kernel/process.cpp
A very trivial change. If metadata is available, the process should use it to retrieve the desired core for the process to run on.
=> kernel/process: Set ideal core from metadata

src/core/file_sys/savedata_factory.h
Amends it with missing values deduced from RE (ProperSystem being from SwitchBrew for naming)
SdCardUser wasn't that difficult to discern given its used alongside SdCardSystem when creating the save data indexer, based off the usage of the string "saveDataIxrDbSd" nearby.
=> file_sys/save_data_factory: Update SaveDataSpaceId enum

src/core/hle/service/filesystem/fsp_srv.cpp
Based off RE, the backing code only ever seems to use 0-2 as the range of values 1 being a generic log enable, with 2 indicating logging should go to the SD card. These are used as a set of flags internally.
Given we only care about receiving the log in general, we can just always signify that we want logging in general. The rest of the values are provided for completeness.
=> service/fsp_srv: Correct returned value in GetGlobalAccessLogMode()

src/core/telemetry_session.cpp
See citra-emu/citra#4476 for more details.
Fixes an issue where Testcases couldn't be sent when Telemetry was disabled, because both things are tied closely together in the backend.
See discussion on (Citra) Discord for more reasoning behind this.
=> Port citra-emu/citra#4476: "web_service: move telemetry condition from TelemetrySession constructor to destructor"

src/core/core.cpp, src/core/core.h, src/core/file_sys/patch_manager.cpp, src/core/file_sys/patch_manager.h, src/core/hle/service/aoc/aoc_u.cpp, src/core/loader/loader.h, src/core/loader/nsp.cpp, src/core/loader/nsp.h, src/core/loader/xci.cpp, src/core/loader/xci.h, src/core/settings.h, src/yuzu/CMakeLists.txt, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_per_general.cpp, src/yuzu/configuration/configure_per_general.h, src/yuzu/configuration/configure_per_general.ui, src/yuzu/game_list.cpp, src/yuzu/game_list.h, src/yuzu/game_list_worker.cpp, src/yuzu/main.cpp, src/yuzu/main.h, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h
This is a temporary workaround to #1816, as well as any other game that fails to work with its update. The workaround is to, with this PR, open the properties and disable the update.
This adds the following properties dialog, which can be displayed from the game list via right-clicking:
This was recycled from #1518, as that PR had other issues, but this is one of the good aspects of it. The UI will display some statistics about the game, its icon, and a list of add-ons and their versions. Unchecking the box will disable the add-on. When disabled, a `[D]` will display in front of the addon in the game list.
=> patch_manager: Add support for disabling patches

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
gl_shader_decompiler: IPA FrontFacing: the right value when is the front face is 0xFFFFFFFF.
That Should fix moustache and red flag colour and other issues related.
Especially thanks to Rodrigo for help in the HW test.
=> gl_shader_decompiler: IPA fix FrontFacing.

src/audio_core/algorithm/interpolate.cpp, src/audio_core/audio_renderer.cpp
Also removes redundant lanczos calculation, which was being calculated twice (surprised the compiler didn't eliminate that).
In BOTW, the vast majority of samples don't need the interpolation, (Interpolation goes from ~4% of CPU time to basically nothing), but if that's an outlier then we should move to a faster sine approximation when interpolation is needed. That's most of the remaining cost.
By code inspection skipping interpolation when sample rates match appears (and sounds) correct, but not very familiar with this logic. At the least a fast-path should be possible for 1.0 ratios.
=> Perf: Avoid (expensive) audio interpolation when sample rates already match

src/video_core/renderer_opengl/gl_shader_cache.cpp
Resolves a trivial warning about implicit truncation
=> gl_shader_cache: Resolve truncation compiler warning 

src/core/hle/service/filesystem/fsp_srv.cpp
Takes no input and returns the size as a u64. Needed by Katamari Damacy Reroll to boot.
With this PR, the game appears to be fully playable, except occasional softlocks.
(Screenshot credit to @Hexagon12)
=> fsp_srv: Implement IStorage::GetSize

src/core/hle/kernel/svc_wrap.h
This would result in `svcSetMemoryAttribute` getting the wrong value for its third parameter. This is currently fine, given the service function is stubbed, however this will be unstubbed in a future change, so this needs to change.
=> svc_wrap: Correct register index for a wrapper specialization

src/yuzu/debugger/wait_tree.cpp, src/yuzu/debugger/wait_tree.h
Just a trivial modernization that potentially avoids copying strings in certain scenarios
=> yuzu/wait_tree: Pass QString by value and std::move in the initializer list for WaitTreeText

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/svc.h, src/core/hle/kernel/svc_wrap.h, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h
Puts the proper memory states in place along with their relevant flags, which will make modifications in the future nicer (particularly, with implementing svcSetMemoryAttribute).
At the same time, this also fixes up svcQueryMemory. Previously, it was possible for memory to get steamrolled, even in error cases where nothing should happen. Since the memory writes were occurring within the SvcWrap handler, this means that those memory writes were happening regardless of the result from the function.
Because of that, it meant that when, say, an invalid process handle is passed to svcQueryProcessMemory, instead of just bailing out, it was bailing out *and* writing 64 bytes into memory (wherever the memory info address is pointing). This means arbitrary stuff in memory can get overwritten, …
=> vm_manager/svc: Modify MemoryState enum, and correct error handling for svcQueryMemory

src/audio_core/audio_out.cpp, src/audio_core/cubeb_sink.cpp, src/audio_core/cubeb_sink.h, src/audio_core/null_sink.h, src/audio_core/sink_details.cpp, src/audio_core/sink_details.h, src/yuzu/configuration/configure_audio.cpp
We can hide the direct array from external view and instead provide functions to retrieve the necessary info. This has the benefit of completely hiding the makeup of the SinkDetails structure from the rest of the code.
Given that this makes the array hidden, we can also make the array constexpr by altering the members slightly. This gets rid of several static constructor calls related to std::vector and std::function.
Now we don't have heap allocations here that need to occur before the program can even enter main(). It also has the benefit of saving a little bit of heap space, but this doesn't matter too much, since the savings in that regard are pretty tiny.
=> audio_core: Make g_sink_details internally linked

src/core/hle/service/service.cpp, src/core/hle/service/service.h
Services created with the ServiceFramework base class install themselves as HleHandlers with an owning shared_ptr in the ServerPort ServiceFrameworkBase::port member variable, creating a cyclic ownership between ServiceFrameworkBase and the ServerPort, preventing deletion of the service objects.
Fix that by removing the ServiceFrameworkBase::port member because it looks like that was only used to detect multiple attempts at installing a port. Instead store a flag if the port was already installed to achieve the same functionality. The service will then live as long as the corresponding ServerPort/ClientPort pair.
This addresses the remaining leaks not fixed by #1890
=> Fix Service object leak on emulation stop

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This PR implements Maxwell's support for 'postfactor' fmul instructions, where the result of multiplication is further multiplied by up to 2^postfactor (or divided by 2^-postfactor if postfactor is negative). Postfactor has a range of [-3, 3], and this occurs before the saturation op if applicable.
This has a marginal impact on BOTW's atmospheric rendering, might have a greater impact elsewhere. Used nouveau as reference and validated against LibNX opengl shaders.
(e: There's a merge conflict with Tinob's in-review CC improvements FYI)
=> Implement postfactor multiplication/division for fmul instructions

src/core/hle/service/am/am.cpp, src/core/hle/service/am/applets/applets.cpp, src/core/hle/service/am/applets/software_keyboard.cpp
This was causing some games (most notably Pokemon Quest) to softlock due to an event being fired when not supposed to. This also removes a hack wherein we were firing the state changed event when the game retrieves it, which is incorrect.
Pokemon Quest now:
(credit to BSoD Gaming for screenshot)
=> applets: Correct usage of SignalStateChanged event

src/video_core/engines/shader_bytecode.h
Fixes half float instructions encoding. It had the same location as the operator A (which is wrong).
Offset was taken from https://github.com/envytools/envytools/blob/3f3155131fcdbed1617bb777959a208a412fcbcb/envydis/gm107.c#L1128-L1134
=> shader_bytecode: Fixup half float's operator B encoding

src/core/hle/kernel/thread.cpp
Somehow I doubt FPCR is 0 on hardware. Unverified.
=> kernel/thread: Set default fpcr

src/core/hle/kernel/svc.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h
Following on the tail of #1900, this implements svcSetMemoryAttribute. This allows setting and unsetting the cached memory attribute from user code. At the sane time, this also lays out all the necessities for properly handling attributes in other contexts as well, however, that can be handled in its own separate PR. This just focuses on the service call.
=> kernel/svc: Implement svcSetMemoryAttribute

src/core/hle/service/sm/sm.cpp
Now it also indicates the name and max session count. This also gives a name to the unknown bool. This indicates if the created port is supposed to be using light handles or regular handles internally. This is passed to the respective svcCreatePort parameter internally.
=> service/sm: Improve debug log for RegisterService

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Previously for arrayed shadow samplers, the array index and depth comparison values were swapped. Fixing this improves shadow rendering pretty decently in BOTW (see attached). There's still some missing shadows that need to be tracked down.
Also fixes invalid logic in GLSL LOD selection (attempting to select LOD with unsupported sampler types, leading to compile errors). Note that the online reference pages are a little inaccurate, the GLSL spec needs to be referenced.
=> Fix arrayed texture LOD selection and depth comparison ordering

src/core/hle/service/nfp/nfp.cpp
Found during hardware testing when working on amiibo spoofing
=> Device handle should not be a random id, instead it's the current npad id

src/core/hle/service/am/am.cpp
This is supposed to return the current process' ID. (0 indicates an invalid ID for both process IDs and ARU IDs).
=> service/am: Unstub GetAppletResourceUserId

src/core/gdbstub/gdbstub.cpp, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/process.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/svc_wrap.h, src/core/hle/kernel/thread.h
Kernel process and thread IDs are internally 64-bit values, not 32-bit, so this amends the relevant interfaces where they're used. In particular, `svcGetThreadId` and `svcGetProcessId` both have 64-bit out parameters.
This also closes a hole in svcGetProcessId, where we weren't handling passed in thread handles properly. The proper behavior is to attempt to read the owning process' ID if a thread handle is passed in instead of a direct process handle. While still technically not covering the whole function's behavior (it also handles debug objects), this is adequate for the time being, given we don't currently implement the debug objects at all, and that games are very unlikely to try and use that in a release.
=> kernel/{process, thread}: Amend behavior related to IDs

src/core/file_sys/savedata_factory.cpp, src/core/hle/kernel/object.cpp, src/core/memory.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/engines/shader_bytecode.h, src/video_core/gpu.cpp, src/video_core/macro_interpreter.cpp, src/video_core/morton.cpp, src/video_core/renderer_opengl/gl_shader_cache.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/surface.cpp, src/video_core/textures/decoders.cpp, src/yuzu/debugger/graphics/graphics_surface.cpp
Functions which are supposed to crash on non-canary builds usually don't return anything which leads to uninitialized memory being used.
This PR is mainly to address the issues with #1340 , with it we should be able to use #1340 instead of #615 
Should also fix some oddity in crashes we might get
=> Fixed uninitialized memory due to missing returns in canary

src/yuzu/CMakeLists.txt, src/yuzu/configuration/config.cpp, src/yuzu/configuration/config.h, src/yuzu/configuration/configure.ui, src/yuzu/configuration/configure_input.cpp, src/yuzu/configuration/configure_input.h, src/yuzu/configuration/configure_input.ui, src/yuzu/configuration/configure_input_player.cpp, src/yuzu/configuration/configure_input_simple.cpp, src/yuzu/configuration/configure_input_simple.h, src/yuzu/configuration/configure_input_simple.ui, src/yuzu/ui_settings.h
Greatly simplifies the current input UI, while still allowing power users to tweak advanced settings. Adds 'input profiles', which are easy autoconfigurations to make getting started easy and fast. Also has a custom option which brings up the current, full UI.
For the profiles, clicking configure will open the button mapping. For custom, it opens the current UI in a dialog.
Currently there are two profiles:
- `Single Player - Handheld - Undocked` (Default)
- `Single Player - Dual Joycons - Docked`
along with `Custom` which will open the current UI when configured.
From my testing, most booting games will work with one or both of these profiles. If a game doesn't work, file an issue report with the game and we can add a new profile.
Examples:
=> configure_input: Add Controller Setup Profiles and simplify input UI

src/core/CMakeLists.txt, src/core/core.cpp, src/core/core.h, src/core/frontend/applets/profile_select.cpp, src/core/frontend/applets/profile_select.h, src/core/hle/service/am/am.cpp, src/core/hle/service/am/applets/applets.cpp, src/core/hle/service/am/applets/profile_select.cpp, src/core/hle/service/am/applets/profile_select.h, src/core/hle/service/am/applets/software_keyboard.cpp, src/yuzu/CMakeLists.txt, src/yuzu/applets/profile_select.cpp, src/yuzu/applets/profile_select.h, src/yuzu/main.cpp, src/yuzu/main.h
This implements a HLE version of the ProfileSelect (0x10) applet on the switch.
When executed, this applet presents a list of users to the player and returns the selection or the cancel error code.
I plan to make a setting to show this on every game boot optionally, similar to how a real switch does it, but I felt that was out-of-scope for this PR.
Used by: Undertale, Arcade Archives
=> am: Implement HLE profile selector applet

src/common/quaternion.h
Previously `xyz` was always being zero initialized due to its constructor, but `w` wasn't. Ensures that we always have a deterministic initial state. Unlikely to matter too much, but prevents potential errors in the future with regards to uninitialized reads.
=> common/quaternion: Ensure that w is always initialized

src/video_core/engines/shader_bytecode.h
The encoding's offset is 59, not 60.
=> shader_bytecode: Fixup TEXS.F16 encoding

src/core/hle/kernel/errors.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h, src/yuzu/debugger/wait_tree.cpp
Implementation of SetThreadActivity.
Adds a new `Paused` thread status, which is essentially `Ready` but with `activity == 1`.
Allows waits to complete before entering `Paused` status.
Permits threads to be paused before started.
Emulator behavior matches console in my test application.
=> svc: Implement SetThreadActivity (thread suspension)

src/yuzu/configuration/configure_input_simple.cpp
Calling tr() from a file-scope array isn't advisable, since it can be executed before the Qt libraries are even fully initialized, which can lead to crashes.
Instead, the translatable strings should be annotated, and the tr() function should be called at the string's usage site. This also just uses regular function pointers instead of std::function. `std::function` is allowed to heap allocate to store any captured data, however, the lambda functions used have no captures. This allows the array to be made constexpr.
=> configure_input_simple: Make input profile array constexpr

src/yuzu/configuration/configure_per_general.cpp
These are user-facing strings, so they should be translatable.
=> configure_per_general: Mark UI strings as translatable in the constructor

src/video_core/renderer_opengl/renderer_opengl.h
This is actually a struct, not a class, which can lead to compilation warnings.
=> renderer_opengl: Correct forward declaration of FramebufferLayout

src/core/file_sys/control_metadata.cpp, src/core/file_sys/control_metadata.h, src/core/file_sys/savedata_factory.cpp, src/core/file_sys/savedata_factory.h, src/core/file_sys/vfs.h, src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h, src/core/hle/service/filesystem/filesystem.cpp, src/core/hle/service/filesystem/filesystem.h, src/core/loader/loader.h, src/core/loader/nsp.cpp, src/core/loader/nsp.h, src/core/loader/xci.cpp, src/core/loader/xci.h, src/yuzu/configuration/configure_per_general.cpp
Since we don't (and have no plans to) support real IVFC-compressed saves, this was the best solution we could come up with.
This will store the normal and journal sizes in a file in the save directory called `.yuzu_save_size`, sequentially as u64s. When the game calls Get or Extend, this file will be read from or written to. Initially, this is populated using the game's control metadata, or if its not available using a default value of 4GB for each (which is large enough to work).
Tested against Minecraft.
Supersedes #1110.
=> am: Implement GetSaveDataSize and ExtendSaveData using files

src/core/hle/kernel/vm_manager.cpp
Like the other members related to memory regions, the attributes need to be reset back to their defaults as well.
=> kernel/vm_manager: Reset region attributes when unmapping a VMA

src/core/hle/service/hid/hid.cpp
With `SetNpadJoyHoldType`, we were popping the applet resource user ID as the hold type. This caused `GetNpadJoyHoldType` to return an invalid value, which broke several games (e.g. Undertale). This worked prior to #1914, as we were always returning an applet resource user iID of 0.
I also took the time here to clean up and improve HID logging, and fixed a few more minor things.
=> hid: Fix SetNpadJoyHoldType and improve logging.

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/svc.cpp, src/core/hle/service/ldr/ldr.cpp
In all cases that these functions are needed, the VMManager can just be retrieved and used instead of providing the same functions in Process' interface.
This also makes it a little nicer dependency-wise, since it gets rid of cases where the VMManager interface was being used, and then switched over to using the interface for a Process instance. Instead, it makes all accesses uniform and uses the VMManager instance for all necessary tasks.
All the basic memory mapping functions did was forward to the Process' VMManager instance anyways. The remaining functions are limited to managing the thread-local-specifics of the process, which is in-line with the kernel itself (it has TLS memory management functions bound to the process as well).
=> kernel/process: Remove most allocation functions from Process' interface

src/core/file_sys/program_metadata.cpp
Provides extra information that makes it easier to tell if an executable being run is using a 36-bit address space or a 39-bit address space, which can potentially help when debugging memory-related issues. While we don't support AArch32 executables yet, this also puts in distinguishing information for the 32-bit address space types as well.
=> file_sys/program_metadata: Print out more descriptive address space descriptions

src/audio_core/audio_out.cpp, src/audio_core/audio_renderer.cpp, src/audio_core/stream.cpp
These two macros being used in tandem were used prior to the introduction of `UNIMPLEMENTED` and `UNIMPLEMENTED_MSG`. This provides equivalent behavior, just with less typing/reading involved.
=> audio_core: Convert LOG_CRITICAL + UNREACHABLE over to UNIMPLEMENTED/UNIMPLEMENTED_MSG

src/core/hle/service/time/time.cpp, src/core/hle/service/time/time.h
Fills in a bit of the data structures a little more based off RE and cleans up GetClockSnapshot to move variables closer to where they're actually used.
=> service/time: Minor cleanup

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h, src/yuzu/debugger/wait_tree.cpp
The main thread for a kernel process should be using the specified ideal core as the core to run on. All main process threads aren't required to start on core zero.
This also cleans up the terminology usage in a few places, and localizes the thread creation for processes to process.cpp.
=> kernel/process: Start the main thread using the specified ideal core

src/core/hle/kernel/process.h, src/core/hle/kernel/svc.cpp
Given #1928 is now merged and we handle the kernel capability descriptors, we can properly sanitize the given core and priority values given to CreateThread by comparing against the masks specified by metadata like how the kernel itself does.
=> kernel/svc: Sanitize core and priority masks within CreateThread

src/core/hle/ipc_helpers.h, src/core/hle/kernel/client_session.cpp, src/core/hle/kernel/client_session.h, src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/hle_ipc.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/server_session.cpp, src/core/hle/kernel/server_session.h, src/core/hle/kernel/wait_object.cpp, src/core/hle/kernel/wait_object.h, src/core/hle/kernel/writable_event.h, src/core/hle/service/am/applets/applets.cpp, src/core/hle/service/am/applets/applets.h, src/core/hle/service/nfp/nfp.cpp, src/core/hle/service/vi/vi.cpp
Gets rid of a few unnecessary header dependencies in some source files, which lessens the likelihood of needing to rebuild those translation units if they were otherwise left in. This also uncovered a few places where we were relying on indirect inclusions of headers (which this also amends).
=> core/kernel: Remove unnecessary inclusions

src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_per_general.cpp
In these scenarios, Qt's API only accepts a 32-bit value, so there's nothing we can do about these except explicitly cast the values.
=> yuzu: Fix truncation warnings within UI code

src/core/hle/service/vi/vi.cpp
In many cases, we didn't bother to log out any of the popped data members. This logs them out to the console within the logging call to provide more contextual information.
=> service/vi: Log more information where applicable

src/core/hle/service/vi/vi.cpp
This IPC command is simply a stub inside the actual service itself, and just returns a successful error code regardless of input. This is likely only retained in the service interface to not break older code that relied upon it succeeding in some way.
=> service/vi: Implement SetDisplayEnabled()

src/core/hle/service/vi/vi.cpp
Internally within the vi services, this is essentially all that OpenDefaultDisplay does, so it's trivial to just do the same, and forward the default display string into the function.
=> service/vi: Implement OpenDefaultDisplay in terms of OpenDisplay

src/core/hle/service/nvflinger/nvflinger.cpp
Upon investigating the issue with #1878, I found that games are the ones who handle the vsync event resetting and not us.
=> Fixed botw deadlock due to incorrect event signal type

src/core/hle/service/vi/vi.cpp
This documents the remaining unknown values, and corrects the initial values for the Default display case. The default display has a max dimension of 1920x1080, not 1280x720
=> service/vi: Minor updates and corrections to the DisplayInfo struct

src/yuzu/CMakeLists.txt, src/yuzu/configuration/configure.ui, src/yuzu/configuration/configure_dialog.cpp, src/yuzu/configuration/configure_profile_manager.cpp, src/yuzu/configuration/configure_profile_manager.h, src/yuzu/configuration/configure_profile_manager.ui, src/yuzu/configuration/configure_system.cpp, src/yuzu/configuration/configure_system.h, src/yuzu/configuration/configure_system.ui
Unclutters the system tab and with the new split UI this also doesn't pollute the tab list.
New System Tab:
New Profiles Tab:
=> qt: Move profile manager to own UI tab

src/core/hle/service/vi/vi.cpp
This also corrects the scaling mode conversions. They do not map 1:1, like comments were indicating. The to-be-converted scaling mode is put into a look-up table of the form:
```
[3, 0, 1, 2, 4]
```
so treating them like equivalent values is just wrong entirely.
=> service/vi: Unstub IApplicationDisplayService's SetLayerScalingMode

src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_cache.h
This PR aims to avoid the cache look up when it's not needed.
=> gl_shader_cache: Use dirty flags for shaders

src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/gl_global_cache.cpp, src/video_core/renderer_opengl/gl_global_cache.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h
Declares the interface for global memory management so other PRs can be canary compatible.
=> gl_global_cache: Add dummy global cache manager

src/core/core.cpp, src/core/hle/service/time/time.cpp, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_system.cpp, src/yuzu/configuration/configure_system.ui, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h
This PR allows the user to set the current time reported to the game manually via settings. On game boot, the system stores a differential between the requested time and the current time (where negative is a time in the past and if this feature isn't enabled it will be 0). This is done so that the clock still increments, just relative to requested time (without this, random crashes will occur in audio-related code). Then, when the game requests the current time via `time:u`, the system will add the differential to the current time in seconds and use that for the service.
Tested against Cave Story, was successfully able to dis/enable the seasonal palette.
UI:
=> settings: Add support for setting the RTC manually

src/core/file_sys/directory.h
This isn't used at all, so we can just get rid of it.
=> file_sys/directory: Remove unused DirectoryBackend class

src/video_core/renderer_opengl/gl_rasterizer.cpp
Use a logical or instead of a bitwise or to test clip distances.
=> gl_rasterizer: Silent unsafe mix warning

src/core/core.cpp, src/core/core.h, src/core/frontend/applets/web_browser.cpp, src/core/frontend/applets/web_browser.h, src/core/hle/service/am/applets/web_browser.cpp, src/yuzu/applets/web_browser.cpp, src/yuzu/applets/web_browser.h
Just does a little cleanup for small details that be done slightly better.
- `std::move`s callbacks where necessary,
- Makes functions private where applicable
- Gets rid of the need to use mutable specifiers for implementations of the web browser applet.
- Adds missing includes
=> yuzu/web_browser: Minor cleanup

src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_resource_manager.cpp, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_state.h, src/video_core/renderer_opengl/gl_stream_buffer.cpp, src/video_core/renderer_opengl/gl_stream_buffer.h, src/video_core/renderer_opengl/renderer_opengl.cpp
Uses DSA (ARB_direct_state_access) for VAOs and buffers except for PBOs due to their bind behaviour it wouldn't make sense to use DSA there.
The plan is to drop as much as `gl_state` as possible to reduce the amount of `Apply()` calls to two or one per draw call. Using DSA also allows a better usage of ARB_multi_bind for textures.
=> gl_rasterizer: Use DSA for VAOs and buffers

src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h
This skips the search of color buffers and the depth buffer if the configuration has not changed (the first two commits). It also skips the framebuffer configuration step if the requested configuration has not changed from the previous call and color and depth buffers are not dirty.
=> gl_rasterizer_cache: Use dirty flags for framebuffers

src/video_core/rasterizer_interface.h, src/yuzu/loading_screen.cpp, src/yuzu/loading_screen.h, src/yuzu/loading_screen.ui, src/yuzu/main.cpp
Part two for #2034, this adds more sparkle to the progress bar to make it more useful. Will rebase this pr after #2034 is merged.
**This image was taken with a loading simulator, and is not representative of actual shader loading times**
There are two problems with the original single progressbar
1. The shader disk loading is actually broken into two parts: loading raw shaders and loading binary shaders.
2. Newly added shaders are appended to the caches, so on the next launch, loading progress goes quickly until it reaches new shaders at which point it'll dramatically slow down.
With these two problems in mind, I designed the progress bar to be minimal but informative. The progressbar is hidden until shader loading is started, and there are two distinct phases with different color …
=> Loading progress bar upgrades

src/yuzu/configuration/configure_debug.cpp, src/yuzu/configuration/configure_input_player.cpp, src/yuzu/configuration/configure_input_player.h, src/yuzu/configuration/configure_per_general.cpp, src/yuzu/configuration/configure_per_general.h, src/yuzu/configuration/configure_system.cpp, src/yuzu/configuration/configure_touchscreen_advanced.h
Removes a bit of unnecessary headers and gets rid of some direct dependencies on other headers. Reduces the amount of rebuilding necessary if certain headers change in the future.
=> yuzu/configuration: Remove unnecessary inclusions where applicable

src/video_core/engines/maxwell_3d.cpp, src/video_core/renderer_opengl/gl_rasterizer.cpp
Commercial games assume that this value is 1 but they never set it. On the other hand nouveau manually sets this register. On `ConfigureFramebuffers` we were asserting for what we are actually implementing (according to envytools).
In case a game wants to explicitly disable separate rendertargets, the new assert should catch it.
=> maxwell_3d: Set rt_separate_frag_data to 1 by default

src/core/settings.cpp, src/core/settings.h, src/yuzu/configuration/configure_dialog.cpp, src/yuzu/main.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
See citra-emu/citra#3928. cc @chris062689 
Fix citra-emu/citra#3918
I chose some of the more diagnostic ones to be logged. Others like custom layout and multiplayer are not logged.
=> Port citra-emu/citra#3928: "citra_qt: Log settings on launch"

src/core/CMakeLists.txt, src/core/frontend/scope_acquire_window_context.cpp, src/core/frontend/scope_acquire_window_context.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h, src/yuzu/main.cpp
This is a prerequisite for #2012 that needs to be merged first to fix canary conflicts.
=> frontend: Refactor ScopeAcquireWindowContext out of renderer_opengl.

src/video_core/video_core.cpp
Also sort the predicate order to have the semantically positive value first.
=> video_core: Silent implicit conversion warning

src/core/hle/kernel/svc.cpp
Looking into the implementation of the C++ exception handling facilities that are within all module binaries. It appears that they use 7 as a break reason to indicate an uncaught C++ exception.
This was primarily found via the third last function called within Horizon's equivalent of libcxxabi's `demangling_terminate_handler()`, which passes the value `0x80000007` to `svcBreak`
=> kernel/svc: Log out uncaught C++ exceptions from svcBreak

src/core/hle/service/vi/vi.cpp
This appears to be a vestigial API function that's only kept around for compatibility's sake, given the function only returns a success error code and exits.
Since that's the case, we can remove the stubbed notification from the log, since doing nothing is technically the correct behavior in this case.
=> service/vi: Remove stubbed notifier from SetLayerVisibility

src/core/hle/service/pm/pm.cpp, src/core/hle/service/pm/pm.h
This is an extremely simple interface function to implement. The service literally just sets the boot mode to maintenance mode like it says it does. No other other checking or anything else is performed, that's all it does.
This completes the pm:bm interface for the time being (until it's added to in subsequent system versions).
=> service/pm: Implement SetMaintenanceBoot

src/video_core/CMakeLists.txt, src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_global_cache.cpp, src/video_core/renderer_opengl/gl_global_cache.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_cache.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.h, src/video_core/shader/decode/memory.cpp, src/video_core/shader/shader_ir.h, src/video_core/shader/track.cpp
This PR uses #1927 as a base implementing #1603 that's itself a continuation of #1323, based on gdkchan's approach for LDG.
About the heuristic itself: it takes the LDG low address register and does a desperate recursive search for any constant buffer that operates on it (returning the first one found), including register proxies.
As difference compared to #1603 and #1323, this one:
* Returns global memory entries through shader entries instead of a global state in Maxwell3D;
* uses SSBOs instead of UBOs; and
* it uses a fixed size for SSBOs.
It has the same graphical issues as #1603, but from what I've seen the heuristic is doing fine (it points to the right constant buffer as base); which means that there's an error elsewhere (some LDG addresses are calculated using XMAD). From some …
=> video_core: Implement LDG through heuristics based on IR

src/video_core/dma_pusher.h
This was previously causing:
> warning C4828: The file contains a character starting at offset 0xa33
that is illegal in the current source character set (codepage 65001).
warnings on Windows when compiling yuzu.
=> video_core/dma_pusher: Silence C4828 warnings

src/core/hle/service/nvflinger/nvflinger.cpp, src/core/hle/service/nvflinger/nvflinger.h, src/core/hle/service/vi/vi.cpp
Converts `Get` functions that don't simply "get" something into `Find`. This also makes FindBufferQueueId() a const qualified member function, since it doesn't modify instance state.
This is just a preliminary cleanup before more changes related to the vi service are made following this.
=> service/nvflinger: Minor renaming changes

src/core/hle/kernel/readable_event.cpp, src/core/hle/kernel/readable_event.h, src/core/hle/kernel/timer.cpp, src/core/hle/kernel/timer.h, src/core/hle/kernel/wait_object.h
None of the current inheritors of the WaitObject class override these functions in any meaningful way. It's also kind of sketchy to allow overriding these, given the kernel itself doesn't really provide for it either.
Given the lack of usage, these can be devirtualized, simplifying the interface that needs to be cared about when inheriting from WaitObject.
=> kernel/wait_object: Devirtualize functions related to manipulating the thread list directly

src/video_core/rasterizer_interface.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/surface.h
Fill surfaces are carried from Citra and unused on yuzu. Remove them and their operations.
=> video_core: Remove unused Fill related code

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h
Some games (like Xenoblade Chronicles 2) clear both depth and stencil buffers while there's a depth-only texture attached (e.g. D16 Unorm). This commit reads the zeta format of the bound surface on `ConfigureFramebuffers` and returns if depth and/or stencil attachments were set. This is ignored on `DrawArrays` but on `Clear` it's used to just clear those attachments, bypassing an OpenGL error.
=> gl_rasterizer: Workaround invalid zeta clears

src/core/hle/service/audio/hwopus.cpp
This functions almost identically to `DecodeInterleavedWithPerfOld`, however this function also has the ability to reset the decoder context's state.
This is documented as a potentially desirable thing in the libopus manual in some circumstances as it says for the OPUS_RESET_STATE ctl:
> This should be called when switching streams in order to prevent the back to back decoding from giving different results from one at a time decoding.
So this is essentially the analogue to that functionality that's being provided.
=> hwopus: Implement DecodeInterleaved (the newest variant)

src/video_core/engines/shader_bytecode.h, src/video_core/shader/decode/memory.cpp
It also renames `BytesN` to `BitsN` since `Bytes32` is a misleading name.
=>  shader_ir/memory: Add LD_L 64 bits loads 

src/video_core/textures/texture.h
Thanks to @ogniK5377 for finding an effect of this bug. If my maths don't fail me this should have a size of 14 instead of 15:
`29 - 16 + 1 = 14`
Sizes taken from: https://github.com/envytools/envytools/blob/c837aa9218b7dd7616a09ef4d5b3ad3cceabfaec/rnndb/graph/gm200_texture.xml#L367
This let's Octopath Traveler get in-game.
=> video_core/texture: Fix BitField size for depth_minus_one

src/yuzu/loading_screen.ui
Was also going to include the console accurate coords for the logo and banner but never got around to it.
=> QT: Fix the loading screen 'H' switch logo to not glitch out

src/yuzu/main.cpp
See citra-emu/citra#4583 for more details.
By default, Qt doesn't add an extension to files if none is explicitly typed by the user.
As such, screenshots would silently fail to save if a user did not type an extension.
This fix creates a full QFileDialog instead of using the getSaveFileName shortcut so a default suffix can be added.
=> Port citra-emu/citra#4583: "citra_qt: Fix saving screenshot when no file extension is provided"

src/yuzu/configuration/configure_graphics.cpp, src/yuzu/configuration/configure_graphics.h
See citra-emu/citra#4586 for more details why this change is made.
=> Port citra-emu/citra#4586: "Use QPixmap/QIcon for background color selection button"

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/renderer_opengl/gl_resource_manager.cpp, src/video_core/renderer_opengl/gl_resource_manager.h, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_state.h, src/video_core/renderer_opengl/renderer_opengl.cpp
This PR uses DSA to handle textures and framebuffers. Due to ARB limitations texture creation had to be moved to immutable storage (which is good since it avoids unwanted lazy allocations by the driver). This revealed a bug in `SurfaceParams::GetRect()` which returns a different value than the `GetMip*(0)` functions. Fixing that is beyond the scope of this PR.
It moves swizzle state tracking from `gl_state` to the texture, this fixes some edge-case issues like:
1. Bind a texture with swizzle RGBA and set a swizzle of RRRR => gl_state updates the swizzling
2. Bind another texture to the same binding as above with swizzle RGBA and set a swizzle of RRRR => gl_state does **not** update it because its swizzle in that binding didn't change.
(OpenGL's texture swizzling is a texture property, not …
=> gl_rasterizer: Use DSA for textures and move swizzling to texture state

src/video_core/dma_pusher.cpp, src/video_core/engines/fermi_2d.cpp, src/video_core/engines/kepler_memory.cpp, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_dma.cpp, src/video_core/memory_manager.cpp, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_primitive_assembler.cpp, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/textures/texture.h
Allowing texture handle a TIC id of zero fixes the "black" texture issue with libnx's nouveau. Allowing these uncovered a crash on Puyo Puyo Tetris (and probably other games) that were using a GPU address of `PageStatus::Reserved`. On the GPU to CPU translation method this state was not being tested, adding this one fixed the Puyo Puyo Tetris crash.
On almost all cases `GpuToCpuAddress` was not being tested for failure, invoking potential undefined behaviour. This adds asserts for these cases.
=> maxwell_3d: Allow texture handles with TIC id zero

src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/shader/decode.cpp, src/video_core/shader/decode/arithmetic.cpp, src/video_core/shader/decode/arithmetic_half.cpp, src/video_core/shader/decode/arithmetic_half_immediate.cpp, src/video_core/shader/decode/arithmetic_immediate.cpp, src/video_core/shader/decode/arithmetic_integer.cpp, src/video_core/shader/decode/arithmetic_integer_immediate.cpp, src/video_core/shader/decode/bfe.cpp, src/video_core/shader/decode/bfi.cpp, src/video_core/shader/decode/conversion.cpp, src/video_core/shader/decode/ffma.cpp, src/video_core/shader/decode/float_set.cpp, src/video_core/shader/decode/float_set_predicate.cpp, src/video_core/shader/decode/half_set.cpp, src/video_core/shader/decode/half_set_predicate.cpp, src/video_core/shader/decode/hfma2.cpp, src/video_core/shader/decode/integer_set.cpp, src/video_core/shader/decode/integer_set_predicate.cpp, src/video_core/shader/decode/memory.cpp, src/video_core/shader/decode/other.cpp, src/video_core/shader/decode/predicate_set_predicate.cpp, src/video_core/shader/decode/predicate_set_register.cpp, src/video_core/shader/decode/register_set_predicate.cpp, src/video_core/shader/decode/shift.cpp, src/video_core/shader/decode/video.cpp, src/video_core/shader/decode/xmad.cpp, src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h, src/video_core/shader/track.cpp
Some games call LDG at the top of a basic block and (on other circumstances) they set the base address if LDG conditionally. This PR lets the heuristic the decoded nodes as a whole instead of per basic blocks and also lets it search inside conditional nodes. This may lead to some false positives but allows the heuristic to track cases it previously couldn't.
Also renames `BasicBlock` to `NodeBlock` since there were some cases where it didn't represent a basic block.
This fixes Xenoblade Chronicles 2 boot sequence.
=> shader/track: Add a more permissive global memory tracking

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
These parameters were declared as constants and passed to glTextureView
but then they were removed on a rabase. This addresses that mistake.
=> gl_rasterizer_cache: Fixup texture view parameters

src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
This is a leftover from the early yuzu days. 
We shouldn't log every time when we are drawing by default, so let's change the log level to Trace.
As suggested by @Hexagon12 on Discord.
=> nvdisp_disp0: change drawing message log level from Warning to Trace

src/video_core/engines/shader_bytecode.h, src/video_core/shader/decode/conversion.cpp
I noticed there was a trunc mode and a none mode which effectively did the same. After some hardware tests, it turns out that None mode was actualy RoundEven mode.
=> Corrected F2I None mode to RoundEven.

src/video_core/renderer_opengl/renderer_opengl.cpp
We already store a reference to the system instance that the renderer is created with, so we don't need to refer to the system instance via Core::System::GetInstance(). Keeps the renderer from directly referring to global variables.
=> renderer_opengl: Remove reference to global system instance

src/video_core/gpu.cpp, src/video_core/gpu.h, src/video_core/surface.cpp
tested on Lego Ninjago and seems to be good.
=> Implement BGRA8 framebuffer format

src/common/threadsafe_queue.h, src/core/core_timing.cpp
The necessity of this parameter is dubious at best (even if enabled, it would still include the size data member as part of the class instead of removing it with template shenanigans), and in 2019 probably offers completely negligible savings as opposed to just leaving this enabled. This removes it and simplifies the overall interface.
=>  threadsafe_queue: Remove NeedSize template parameter

src/core/core_timing.cpp
Given this is only used in one place, it can be moved closest to its usage site.
=> core_timing: Make EmptyTimedCallback a local variable

.gitmodules, CMakeLists.txt, src/common/logging/backend.cpp, src/common/logging/log.h, src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/declarations.h, src/video_core/renderer_vulkan/vk_device.cpp, src/video_core/renderer_vulkan/vk_device.h
Since #1114 is a very old base to work on top of, the intention is to open individual pull requests for Vulkan sections that can be built and reviewed individually. This is (in my opinion) much better than opening a single PR with +7000 lines of code.
This adds [Vulkan-Headers](https://github.com/KhronosGroup/Vulkan-Headers/) as dependency without requiring any external linkage dependencies or SDK, all Vulkan function pointers can be queried at runtime if `vkGetInstanceProcAddr` is provided (something that's exposed in SDL2, GLFW and Qt).
Aside from that, it adds a device abstraction class which is dead-code at the moment. Description in 4d16376.
=> vulkan: Add dependencies and device abstraction

src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/shader/decode/memory.cpp
Fixes a regression introduced in #2068. It also replaces `u32` iterations with `std::size_t`.
=> gl_shader_decompiler: Re-implement TLDS lod

src/video_core/renderer_opengl/gl_rasterizer_cache.h
Avoids shadowing the members of the struct itself, which results in a -Wshadow warning.
=> gl_rasterizer_cache: Get rid of variable shadowing

src/common/logging/backend.cpp, src/common/logging/backend.h, src/common/threadsafe_queue.h
See citra-emu/citra#4197 for more details.
This adds a way to wait until the SPSCQueue / MPSCQueue isn't empty anymore. I didn't add a WaitFor and WaitUntil yet, but this can be easily added if necessary.
For now there is only one instance where this gets used (logging) but scripting (citra-emu/citra#4016) should also use it. This also assures that Wait isn't ended spuriously.
=> Port citra-emu/citra#4197: "threadsafe_queue: Add PopWait and use it where possible "

src/video_core/renderer_opengl/renderer_opengl.cpp
Previously, we were completely ignoring for screenshots whether the game uses RGB or sRGB.
This resulted in screenshot colors that looked off for some titles.
Now everything looks correctly:
=> renderer_opengl: respect the sRGB colorspace for the screenshot feature

src/core/hle/kernel/address_arbiter.cpp, src/core/hle/kernel/address_arbiter.h
A fairly trivial change. Other sections of the codebase use nested namespaces instead of separate namespaces when possible. This one must have just been overlooked.
No functional changes. This is just a simplification.
=> address_arbiter: Use nested namespaces where applicable

src/audio_core/buffer.h, src/audio_core/stream.cpp
This way proper const/non-const selection can occur if needed (as well as, y'know, keeping the interface consistent).
=> audio_core/buffer: Make const and non-const getter for samples consistent

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/vk_resource_manager.cpp, src/video_core/renderer_vulkan/vk_resource_manager.h
`VKResourceManager` is an abstraction layer used to commit fences and command buffers from a pool on Vulkan. This avoids constantly allocating (and deallocating) resources in the hot loop. Details in the individual commits.
=> vk_resource_manager: Implement fence and command buffer allocator

src/core/CMakeLists.txt, src/core/hle/service/nvflinger/nvflinger.cpp, src/core/hle/service/nvflinger/nvflinger.h, src/core/hle/service/vi/display/vi_display.cpp, src/core/hle/service/vi/display/vi_display.h, src/core/hle/service/vi/layer/vi_layer.cpp, src/core/hle/service/vi/layer/vi_layer.h
These are more closely related to the vi service as opposed to the intermediary NVFlinger class.
This also places them in their relevant subfolder, as future changes to these will result in subclassing to represent various displays and services, as they're done within the service itself on hardware.
The reasoning for prefixing the display and layer source files is to avoid potential clashing if two files with the same name are compiled in the same library (e.g. if 'display.cpp/.h' or 'layer.cpp/.h' is added to another service at any point), which MSVC will actually warn against, since it can result in ODR violations. This prevents that case from occurring.
This is a preliminary moving of data structures before expanding on how they function, so I've marked it as "style", even though it's …
=> service/nvflinger: Relocate definitions of Layer and Display to the vi service

src/core/core.cpp, src/video_core/engines/kepler_memory.cpp, src/video_core/engines/kepler_memory.h, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/engines/maxwell_dma.cpp, src/video_core/engines/maxwell_dma.h, src/video_core/gpu.cpp, src/video_core/gpu.h
Avoids the use of the global accessor in favor of explicitly making the system a dependency within the interface.
=> video_core: Remove usages of System::GetInstance() within the engines

src/video_core/renderer_opengl/gl_state.cpp
There are some potential edge cases where gl_state may fail to track the state if a related state changes while the toggle is disabled or it didn't change. This addresses that.
=> gl_state: Synchronize gl_state even when state is disabled

src/video_core/renderer_vulkan/vk_memory_manager.cpp
`VKMemoryCommitImpl` was using as the end of its interval `begin + end`. That ended up wasting memory.
Edit: Now that I look at it, this thing was exponential. No wonder why 8 textures were using 256 MiB of VRAM.
=> vk_memory_manager: Fixup commit interval allocation

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
`MortonSwizzle`'s parameter order is `depth` and then `tile_width_spacing`. This addresses that parameter order bug when swizzling layered textures.
=> gl_rasterizer_cache: Fixup parameter order in layered swizzle

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/vk_scheduler.cpp, src/video_core/renderer_vulkan/vk_scheduler.h
The scheduler abstracts command buffer and fence management with an interface that's able to do OpenGL-like operations on Vulkan command buffers.
It returns by value a command buffer and fence that have to be used for subsequent operations until Flush or Finish is executed, after that the current execution context (the pair of command buffers and fences) gets invalidated a new one must be fetched. Thankfully validation layers will quickly detect if this is skipped throwing an error due to modifications to a sent command buffer.
=> vk_scheduler: Implement a scheduler

src/video_core/dma_pusher.cpp, src/video_core/dma_pusher.h
Fetching every u32 from memory leads to a big overhead. So let's fetch all of them as a block if possible.
This reduces the Memory::* calls by the dma_pusher by a factor of 10.
=> video_core/dma_pusher: The full list of headers at once.

src/core/hle/service/nvflinger/nvflinger.cpp, src/core/hle/service/nvflinger/nvflinger.h, src/core/hle/service/vi/display/vi_display.cpp, src/core/hle/service/vi/display/vi_display.h, src/core/hle/service/vi/layer/vi_layer.cpp, src/core/hle/service/vi/layer/vi_layer.h, src/core/hle/service/vi/vi.cpp
Continuing off of #2142, this converts the Display and Layer structs into classes and puts everything behind interface functions to cleanly isolate behavior for upcoming changes to these structs. #2142 was intended to be the last reorganization PR before functional changes start occurring, but I figured I'd separate this into its own PR beforehand to cut down on the amount of "churn" in later PRs.
This conversion into classes is because future changes will start placing invariants on both classes that need to hold, and so the interface prevents accidentally messing around with those. It also makes it a little more consistent, so we don't have cases where member variables are being directly accessed, and cases where they're not in the future.
=> service/vi: Convert Display and Layer structs into classes

src/common/swap.h
See citra-emu/citra#4655 for more details.
Citra can't be compiled using GCC <7 because of required C++17 support, so these version checks don't need to exist anymore.
=> Port citra-emu/citra#4655: "Remove GCC version checks"

src/video_core/shader/track.cpp
Resolves warnings caused by variables in an inner scope shadowing ones with the same name in an outer scope.
=> shader/track: Resolve variable shadowing warnings

src/audio_core/codec.cpp, src/audio_core/cubeb_sink.cpp
Resolves a few trivial compilation warnings related to truncation, shadowing, and initialization.
=> audio_core: Resolve compilation warnings

src/video_core/renderer_opengl/renderer_opengl.cpp
Framebuffer refreshing is tested against pixel format, but this one was never updated on reconfiguration resulting in a resource deletion + recreation + allocation each frame.
=> renderer_opengl: Update pixel format tracking

src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
This is only necessary in headers. Silences a warning with clang.
=> gl_shader_disk_cache: Remove #pragma once from cpp file

src/common/color.h, src/common/math_util.h, src/common/quaternion.h, src/common/vector_math.h, src/core/frontend/framebuffer_layout.cpp, src/core/frontend/framebuffer_layout.h, src/core/frontend/input.h, src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp, src/core/hle/service/nvdrv/devices/nvdisp_disp0.h, src/core/hle/service/nvflinger/buffer_queue.cpp, src/core/hle/service/nvflinger/buffer_queue.h, src/core/hle/service/vi/vi.cpp, src/input_common/motion_emu.cpp, src/video_core/engines/fermi_2d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/gpu.h, src/video_core/rasterizer_interface.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/renderer_opengl/renderer_opengl.h, src/yuzu/debugger/graphics/graphics_surface.cpp
We have a little bit of a mishmash of math-related namespaces in the common libray (such as Math and MathUtil). For the sake of consistency across the common library, we place all of these into the Common namespace.
=> common: Move Quaternion, Rectangle, Vec2, Vec3, and Vec4 into the Common namespace

src/core/hle/kernel/errors.h, src/core/hle/kernel/handle_table.cpp, src/core/hle/kernel/handle_table.h, src/core/hle/kernel/process.cpp, src/core/hle/kernel/process_capability.cpp, src/core/hle/kernel/process_capability.h
The kernel allows restricting the total size of the handle table through the process capability descriptors. Until now, this functionality wasn't hooked up. With this, the process handle tables become properly restricted.
In the case of metadata-less executables, the handle table will assume the maximum size is requested, preserving the behavior that existed before these changes.
=>  kernel/handle_table: Allow process capabilities to limit the handle table size

src/core/frontend/emu_window.cpp, src/core/frontend/emu_window.h
This member function doesn't modify instance state, so it can have the const specifier applied to it.
=> core/frontend/emu_window: Make ClipToTouchScreen a const member function

src/audio_core/cubeb_sink.cpp, src/audio_core/cubeb_sink.h
cubeb now requires that COM explicitly be initialized on the thread prior to calling cubeb_init for the WASAPI backend. This is documented [here](https://github.com/kinetiknz/cubeb/blob/master/include/cubeb/cubeb.h#L414). However, it wasn't actually enforced by the library until [this commit](https://github.com/kinetiknz/cubeb/commit/6f2420de8f155b10330cf973900ac7bdbfee589d), which added an assertion to check for it.
=> audio_core/cubeb_sink: Ensure COM is initialized on Windows prior to calling cubeb_init

src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Instead of using bitwise operations, let `std::bitset` manage the dirty flags.
=> maxwell_3d: Use std::bitset to manage dirty flags

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_vulkan/vk_memory_manager.cpp
Reorders two constructor initializer lists in terms of the class member variable's declaration order.
The warning mainly stems from:
```cpp
class Thing {
public:
// Despite y being before x here, x will actually be initialized first
// when the constructor runs, not y. Initialization occurs in terms
// how the member variables are ordered.
explicit Thing(int x, int y) : y{y}, x{x} {}
private:
int x;
int y;
};
```
which can be problematic in a scenario where one member variable's initialization depends on another one, and the order is mixed up. e.g. a somewhat minimal example:
```cpp
class OtherThing {
public:
explicit OtherThing(int value) : value{value} {}
private:
int value;
};
class Thing {
public:
// Whoops, uninitialized value passed to ot's constructor.
// Since 'ot' is declared …
```
=> gl_rasterizer/vk_memory_manager: Silence -Wreorder warnings

src/video_core/rasterizer_cache.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h
Some games create complex textures first and then render inside them, sometimes even using that same texture as parameter. This gives the name of this PR "Texception Pass" (texture + inception). This pass consists on detecting such behavior every draw call and copying and correcting the correct used texture.
=> Improve the Accuracy of the Rasterizer Cache through a Texception Pass

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/vk_resource_manager.cpp, src/video_core/renderer_vulkan/vk_resource_manager.h, src/video_core/renderer_vulkan/vk_stream_buffer.cpp, src/video_core/renderer_vulkan/vk_stream_buffer.h
This manages two kinds of streaming buffers: one for unified memory models and one for dedicated GPUs. The first one skips the copy from the staging buffer to the real buffer, since it creates an unified buffer.
This implementation waits for all fences to finish their operation before "invalidating". This is suboptimal since it should allocate another buffer or start searching from the beginning. There is room for improvement here.
This could also handle AMD's "pinned" memory (a heap with 256 MiB) that seems to be designed for buffer streaming.
=>  vk_stream_buffer: Implement a stream buffer

src/core/hle/service/hid/hid.h
The SM namespace is within the Service namespace, so this was forward declaring a type that didn't exist. Silences a compiler warning.
=> service/hid: Amend forward declaration of ServiceManager

src/core/hle/service/audio/audren_u.cpp, src/core/hle/service/audio/audren_u.h
This currently has the same behavior as the regular OpenAudioRenderer API function, so we can just move the code within OpenAudioRenderer to an internal function that both service functions call.
Fills in the remaining function missing from the audren:u function table.
=> service/audio/audren_u: Implement OpenAudioRendererAuto

src/core/hle/service/audio/audren_u.cpp
A somewhat underwhelming API function. This service function appears to do nothing noteworthy on the Switch. All it does at the moment is either return an error code or abort the system. Given we obviously don't want to kill the system, we just opt for always returning the error code.
This fills in the last missing function for the IAudioRenderer class.
=> service/audio: Provide an implementation of ExecuteAudioRendererRendering

src/yuzu/compatdb.cpp
Silences a compiler warning with clang.
=> yuzu/compatdb: Remove unused lambda capture

src/web_service/verify_login.h, src/web_service/web_backend.cpp
Reduces the potential amount of rebuilding necessary if any headers change. In particular, we were including a header from the core library when we don't even link the core library to the web_service library, so this also gets rid of an indirect dependency.
=> web_service: Remove unnecessary inclusions

src/common/logging/backend.cpp, src/common/logging/backend.h
Keeps our logging related state all in one place, as opposed to having a local static within the function.
On weakly ordered systems (e.g. ARM/AArch64), this also gets rid of needing to do a second conditional atomic load within the logging functions, which is also nice as a side benefit to moving it into the class itself.
=>  logging/backend: Move CreateEntry into the Impl class. Relocate local static to a class variable

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_state.cpp
Applying the state to update a framebuffer will also update the state for the textures. Knowing this we can unbind the textures at the end of the draw call without applying it. Also fix a `gl_state` bug were the first index offset was being ignored.
=>  gl_rasterizer: Unbind textures but don't apply the gl_state 

src/core/memory.cpp
See citra-emu/citra#4630 for more details.
The comment already invalidates itself: neither MMIO nor rasterizer cache belongs to HLE kernel state. This mutex has a too large scope if MMIO or cache is included, which is prone to dead lock when multiple thread acquires these resource at the same time. If necessary, each MMIO component or rasterizer should have their own lock.
=> Port citra-emu/citra#4630: "Memory: don't lock hle mutex in memory read/write"

src/core/hle/kernel/thread.cpp, src/video_core/surface.cpp
The TODO in Create() is a TODO carried over from Citra that doesn't apply here. Hexagon also told me that the one in PixelFormatFromRenderTargetFormat() doesn't apply anymore either, so we can get rid of these.
=> {kernel/thread, video_core/surface}: Remove obsolete TODOs

src/video_core/engines/fermi_2d.cpp, src/video_core/engines/fermi_2d.h, src/video_core/engines/kepler_compute.cpp, src/video_core/engines/kepler_compute.h, src/video_core/engines/kepler_memory.h, src/video_core/engines/maxwell_dma.cpp, src/video_core/engines/maxwell_dma.h, src/video_core/engines/shader_bytecode.h, src/video_core/renderer_base.cpp, src/video_core/renderer_vulkan/vk_buffer_cache.cpp
Removes a few unnecessary dependencies on core-related machinery, such as the core.h and memory.h, which reduces the amount of rebuilding necessary if those files change.
This also uncovered some indirect dependencies within other source files. This also fixes those.
=> video_core/engines: Remove unnecessary includes

src/core/CMakeLists.txt, src/core/hle/service/audio/audout_u.cpp, src/core/hle/service/audio/audren_u.cpp, src/core/hle/service/audio/errors.h
Places all error codes in an easily includable header.
This also corrects the unsupported error code (I accidentally used the representation of the hex value when I meant to use the decimal one).
=> hle/service/audio: Extract audio error codes to a header

src/core/hle/kernel/svc.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h
These two functions more appropriately belong to this interface, so we can move them over. While we're at it, also provide similar functions for the other memory ranges.
=> svc: Move memory range checking functions to the VMManager class

src/yuzu/debugger/wait_tree.cpp, src/yuzu/debugger/wait_tree.h
We already have the thread instance that was created under the current process, so we can just pass the handle table of it along to retrieve the owner of the mutex.
=> yuzu/debugger/wait_tree: Remove use of global CurrentProcess accessor

src/core/hle/service/audio/audout_u.cpp
Previously we were overwriting the error case with a success code further down (which is definitely not what we should be doing here).
=> hle/service/audio/audout_u: Correct lack of return in failure case of AppendAudioOutBufferImpl()

src/core/core.cpp, src/core/hle/kernel/address_arbiter.cpp, src/core/hle/kernel/address_arbiter.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/svc.cpp, src/tests/core/arm/arm_test_common.cpp
This will be necessary to do further deglobalizing work when it comes to hoisting the memory subsystem into its own class later on. This also allows getting rid of some usages of the global system accessor, moving them further up the chain into the SVC calls themselves, making them much easier to replace in the future, when globals get addressed there.
=> kernel/address_arbiter: Convert the address arbiter into a class

src/core/core.cpp, src/core/core.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h, src/yuzu/compatdb.cpp, src/yuzu/main.cpp, src/yuzu_cmd/yuzu.cpp
In many cases, the system object reference is nearby, so we can just use that to access the telemetry instance. In the lingering case within compatdb, we can just use the long-form of accessing it.
With all of the usages converted over, we can remove the function that relies on the global variable.
=> core: Remove the global telemetry accessor function

src/core/hle/ipc.h, src/core/hle/kernel/hle_ipc.h, src/core/hle/kernel/svc.cpp, src/core/hle/result.h, src/core/hle/service/am/applets/software_keyboard.cpp, src/core/hle/service/am/applets/software_keyboard.h
Removes a few inclusion dependencies from the headers or replaces existing ones with ones that don't indirectly include the required headers.
This allows removing an inclusion of core/memory.h, meaning that if the memory header is ever changed in the future (it likely will), it won't result in rebuilding the entirety of the HLE services (as the IPC headers are used quite ubiquitously throughout the HLE service implementations).
=> core/hle/ipc: Remove unnecessary includes

src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/textures/astc.cpp, src/video_core/textures/astc.h, src/video_core/textures/convert.cpp, src/video_core/textures/convert.h, src/video_core/textures/decoders.cpp, src/video_core/textures/decoders.h
Pixel conversion functions are used by multiple graphics APIs, this moves them out of `gl_rasterizer_cache`.
Aside from that, pixel format conversion functions now take a C pointer instead of `std::vector<u8>` because map functions in most graphics APIs return a pointer instead of an STL vector. This forced some changes in `astc.cpp`.
=>  gl_rasterizer_cache: Move format conversion functions to their own file 

src/core/core.cpp, src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp, src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp, src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp, src/core/hle/service/nvflinger/nvflinger.cpp, src/core/memory.cpp, src/core/settings.h, src/core/telemetry_session.cpp, src/video_core/CMakeLists.txt, src/video_core/engines/kepler_memory.cpp, src/video_core/engines/maxwell_dma.cpp, src/video_core/gpu.cpp, src/video_core/gpu.h, src/video_core/gpu_asynch.cpp, src/video_core/gpu_asynch.h, src/video_core/gpu_synch.cpp, src/video_core/gpu_synch.h, src/video_core/gpu_thread.cpp, src/video_core/gpu_thread.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/yuzu/bootmanager.cpp, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_graphics.cpp, src/yuzu/configuration/configure_graphics.ui, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h
This PR has as base #2021 (which has LDG, the shader IR, and disk based shader cache) in order to canary merge - hence the diff. 199ffa2 is the first commit
This is a second attempt at asynchronous GPU emulation. This supersedes #2012, and should fix the issues which that change introduced.
This moves GPU command processing to another thread. This works by letting the CPU core (main) thread push "GPU commands", while the GPU thread waits for commands to be available. After a push, the main thread signals that commands are available, and the GPU thread wakes up and continues to process these until the command queue is empty. The current GPU commands are:
* `SubmitList` - Pushes a GPU command list into the DmaPusher interface
* `SwapBuffers` - Swaps the output framebuffers
* `FlushRegion` - …
=> Asynchronous GPU command processing

src/core/hle/service/audio/audout_u.cpp
The service itself only does further actions if the stream is playing. If the stream is already stopped, then it just exits successfully.
=> service/audio/audout_u: Only actually stop the audio stream in StopAudioOut if the stream is playing

src/core/hle/kernel/client_session.cpp, src/core/hle/kernel/client_session.h, src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/server_session.cpp, src/core/hle/kernel/server_session.h, src/core/hle/service/sm/controller.cpp
Following in the same footsteps as most of the other kernel objects, this places all data members behind an interface to make it easier to reason about what kinds of operations may be done to members of the respective classes.
Putting the interface in place will also make it nicer when the light variants of the sessions get implemented.
=> kernel/client_session, kernel/server_session: Make data members private

src/yuzu/applets/web_browser.cpp, src/yuzu/main.cpp
Addresses issues where a user in fullscreen could not exit some web applets without leaving fullscreen. (Specifically #2157)
=> web_browser: Add shortcut to Enter key to exit applet

src/core/hle/kernel/shared_memory.cpp
Given we already pass in a reference to the kernel that the shared memory instance is created under, we can just use that to check the current process, rather than using the global accessor functions.
This allows removing direct dependency on the system instance entirely.
=> kernel/shared_memory: Get rid of the use of global accessor functions within Create()

src/video_core/dma_pusher.cpp
Instead of holding a reference that will get invalidated by `dma_pushbuffer.pop()`, hold it as a copy. This doesn't have any performance cost since CommandListHeader is 8 bytes long.
=> dma_pusher: Store command_list_header by copy

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/maxwell_to_vk.cpp, src/video_core/renderer_vulkan/maxwell_to_vk.h, src/video_core/renderer_vulkan/vk_device.cpp
This has the same purpose as OpenGL's `maxwell_to_gl`, but its definition is in a `cpp` file instead of the header. It's not intended to be a complete implementation, since I like to add the entries as I find them to avoid obscure bugs.
=> maxwell_to_vk: Initial implementation

src/video_core/gpu.h, src/video_core/gpu_asynch.h, src/video_core/gpu_synch.h
Because of the recent separation of GPU functionality into sync/async variants. We need to mark the destructor virtual to provide proper destruction behavior, given we use the base class within the System
class.
Prior to this, it was undefined behavior whether or not the destructor in the derived classes would ever execute.
=> video_core/gpu: Make GPU's destructor virtual

src/video_core/gpu_thread.h
Moves the data members to satisfy the order they're declared as in the constructor initializer list. Silences a -Wreorder warning.
This also removes an unimplemented function prototype as well, to prevent accidental usage of it.
=> video_core/gpu_thread: Silence a -Wreorder warning

.travis.yml, .travis/macos/build.sh, src/common/bit_field.h, src/core/hle/ipc_helpers.h, src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/hle_ipc.h, src/core/hle/kernel/server_session.cpp
There's no real need to use a shared lifetime here, since we don't actually expose them to anything else. This is also kind of an unnecessary use of the heap given the objects themselves are so small; small enough, in fact that changing over to optionals actually reduces the overall size of the HLERequestContext struct (818 bytes to 808 bytes on Windows).
This makes reasoning about the lifetimes of the members a little nicer, since people don't need to actually check whether these members are potentially being shared elsewhere, as well as not needing to care about potentially accidentally causing reference cycles with the shared pointers.
=> kernel/hle_ipc: Convert std::shared_ptr IPC header instances to std::optional

src/yuzu_cmd/config.cpp
Also replaces `(float)` with `static_cast<float>(...)` for consistency.
=>  yuzu_cmd/config: Silent implicit cast warning 

src/core/settings.cpp
This PR makes Yuzu log 2 new specific values (used or not):
* Asynchronous GPU emulation
* Disk Shader Cache
=> core/settings: Log more setting values

src/audio_core/cubeb_sink.cpp, src/audio_core/cubeb_sink.h
This behavior also needs to be visible for MinGW builds as well.
=> audio_core/cubeb_sink: Convert _MSC_VER ifdefs to _WIN32

src/core/hle/service/audio/hwopus.cpp
Moves the non-multistream specific state to its own class. This will be necessary to support the multistream variants of opus decoding, given the overall decoder state parameters differ from the regular non-multistreamed version of the decoder.
=> service/audio/hwopus: Move decoder state to its own class

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/textures/texture.h
Abstract sampler queries into getter methods to avoid repeating logic across APIs.
It also does some renames like `mip_filter` -> `mipmap_filter` because it was easy to mistype `min_filter`.
=> gl_rasterizer: Encapsulate sampler queries into methods

src/core/hle/service/service.cpp
These can just be passed regularly, now that we use fmt instead of our old logging system.
While we're at it, make the parameters to MakeFunctionString std::string_views.
=> service/service: Remove unncessary calls to c_str()

src/core/core.cpp, src/core/hle/kernel/address_arbiter.cpp, src/core/hle/kernel/address_arbiter.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/svc.cpp, src/tests/core/arm/arm_test_common.cpp
Now that we have the address arbiter extracted to its own class, we can fix an innaccuracy with the kernel. Said inaccuracy being that there isn't only one address arbiter. Each process instance contains its own AddressArbiter instance in the actual kernel.
This fixes that and gets rid of another long-standing issue that could arise when attempting to create more than one process.
=> kernel: Make the address arbiter instance per-process 

src/core/hle/ipc_helpers.h, src/core/hle/service/vi/vi.cpp, src/core/hle/service/vi/vi.h, src/core/hle/service/vi/vi_m.cpp, src/core/hle/service/vi/vi_m.h, src/core/hle/service/vi/vi_s.cpp, src/core/hle/service/vi/vi_s.h, src/core/hle/service/vi/vi_u.cpp, src/core/hle/service/vi/vi_u.h
This function is also supposed to check its given policy type with the permission of the service itself. This implements the necessary machinery to unstub these functions.
Policy::User seems to just be basic access (which is probably why vi:u is restricted to that policy), while the other policy seems to be for extended abilities regarding which displays can be managed and queried, so this is assumed to be for a background compositor (which I've named, appropriately, Policy::Compositor).
=> service/vi: Unstub GetDisplayService

src/core/hle/ipc_helpers.h, src/core/hle/result.h, src/core/hle/service/service.cpp
With the recent changes done to BitField, we can remove an unnecessary copy assignment operator. By moving the lone IPC-related error to the IPC utilities, we can then remove an unnecessary constructor.
=> core/hle/result: Tidy up the base error code result header.

src/core/hle/kernel/client_port.cpp, src/core/hle/kernel/server_port.cpp, src/core/hle/kernel/server_port.h, src/core/hle/service/sm/sm.h
With this, all kernel objects finally have all of their data members behind an interface, making it nicer to reason about interactions with other code (as external code no longer has the freedom to totally alter internals and potentially messing up invariants).
=> kernel/server_port: Make data members private

src/video_core/renderer_opengl/gl_global_cache.cpp, src/video_core/renderer_opengl/gl_global_cache.h
Silences compiler warnings. While we're in the area, also convert `ReserveGlobalRegion()` over to using `insert_or_assign()`, since it's a fairly trivial change.
=> renderer_opengl/gl_global_cache: Add missing override specifiers

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h
OpenGL's rasterizer constructor receives a system instance. Store that in the object and use that instead.
=> gl_rasterizer: Use system instance passed from argument

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h
Now that we pass in a reference to the system instance, we can utilize it to eliminate the global accessors in Process-related code.
=> kernel/process: Remove use of global system accessors

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/vk_sampler_cache.cpp, src/video_core/renderer_vulkan/vk_sampler_cache.h, src/video_core/textures/texture.h
Implements a sampler cache that stores Vulkan sampler handles. As future improvement it could receive a fence on sampler queries and destroy samplers that are not being used and have not been used for some time, reducing memory overhead - that being said, samplers should be cheap on most implementations.
=> vk_sampler_cache: Implement a sampler cache

src/yuzu/configuration/config.cpp, src/yuzu/configuration/config.h
See citra-emu/citra#3924.
This is to fix citra-emu/citra#3531.
Design:
1. When a setting does not has a default value, it is stored in the same way as before. (Simple QSettings  entry)
1. When a setting has a default value, it is separated into two entries: `xxxxx\default` and `xxxxx`. If `xxxxx\default` = true, it means that the setting is using its default value, and when the configuration is loaded, the setting will be automatically replaced with the new default value (if any). The `xxxxx` entry stores the setting value, however it is only used when `xxxxx\default` = false. See the `ReadSetting` and `WriteSetting` functions for more detail.
1. In this way the new config file will be compatible with the old file.
1. I did not make any changes to the …
=> Port citra-emu/citra#3924: "citra_qt: Settings (configuration) rework"

src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp, src/core/memory.cpp, src/video_core/engines/kepler_memory.cpp, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_dma.cpp, src/video_core/gpu.h, src/video_core/gpu_asynch.cpp, src/video_core/gpu_asynch.h, src/video_core/gpu_synch.cpp, src/video_core/gpu_synch.h, src/video_core/gpu_thread.cpp, src/video_core/gpu_thread.h, src/video_core/rasterizer_cache.h, src/video_core/rasterizer_interface.h, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_buffer_cache.h, src/video_core/renderer_opengl/gl_global_cache.cpp, src/video_core/renderer_opengl/gl_global_cache.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_cache.h, src/video_core/renderer_vulkan/vk_buffer_cache.cpp, src/video_core/renderer_vulkan/vk_buffer_cache.h
This is the first of several changes that are in the March Patreon build.
With this change, we change our rasterizer caching interface to be based on "CacheAddr", instead of guest CPU address. The latter did not really make a ton of sense (other than being a quick shortcut with our existing CPU memory map...), as the GPU is not aware of this address space.
Ideally, "CacheAddr" would be physical address (the one "true source" of the cached data, which is independent of any emulated virtual address space), but yuzu does not emulate this (...maybe it will in the future). In lieu of this, we use host address - as that is analogous to the "true source" of the data.
This allows us to avoid lots of GPU-to-CPU address lookups (will be more apparent with subsequent changes), which were accounting …
=> gpu: Use host address for caching instead of guest address.

src/core/hle/kernel/scheduler.cpp, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h
These functions both access globals in less than desirable areas (and in the case of `WaitCurrentThread_Sleep`, no globals ever need to be accessed anyway, so it's unnecessary). This moves the sleep logic into its own Sleep() function and just places the ExitCurrentThread code into its only usage spot.
Makes it nicer to reason about the sleeping logic by explicitly making it a part of the thread's interface.
=> kernel/thread: Remove WaitCurrentThread_Sleep() and ExitCurrentThread()

CMakeLists.txt
This issue has since been fixed in newer versions of Boost, so we don't need to worry about this anymore.
=> CMakeLists: Remove now-unnecessary GCC special-casing

src/video_core/dma_pusher.cpp, src/video_core/engines/kepler_memory.cpp, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_dma.cpp, src/video_core/gpu.cpp, src/video_core/memory_manager.cpp, src/video_core/memory_manager.h, src/video_core/morton.cpp, src/video_core/morton.h, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_global_cache.cpp, src/video_core/renderer_opengl/gl_global_cache.h, src/video_core/renderer_opengl/gl_primitive_assembler.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_cache.h, src/video_core/textures/decoders.cpp, src/video_core/textures/decoders.h, src/yuzu/debugger/graphics/graphics_surface.cpp
Precursor to using the GPU memory map instead of the current process memory map.
=> video_core: Refactor to use MemoryManager interface for all memory access.

src/core/hle/kernel/thread.cpp
This was intended to be removed in 51d7f6bffcc0498a47abc7de27bf0906fc523dae, but I guess I forgot to actually save the file like a dingus.
=> kernel/thread: Actually remove the definition of ExitCurrentThread()

src/core/hle/ipc_helpers.h
Certain values that are passed through the IPC buffer are actually floating point values, not solely integral values.
=> ipc_helpers: Allow pushing and popping floating-point values

src/common/CMakeLists.txt, src/common/memory_hook.cpp, src/common/memory_hook.h, src/common/page_table.cpp, src/common/page_table.h, src/core/CMakeLists.txt, src/core/arm/dynarmic/arm_dynarmic.h, src/core/hle/kernel/process.cpp, src/core/hle/kernel/scheduler.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h, src/core/memory.cpp, src/core/memory.h, src/core/memory_setup.h, src/tests/core/arm/arm_test_common.cpp, src/tests/core/arm/arm_test_common.h
We will reuse this for the GPU page table, hence the move to Common.
=> core: Move PageTable struct into Common.

CMakeLists.txt
Required due to bugfix in boost for [changed template resolving rules in GCC 7.3.0 in C++17 mode](https://bugzilla.redhat.com/show_bug.cgi?id=1485641).
Closes #2255.
=> CMakeLists: Raise minimum Boost requirement to 1.66.0

src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h
This condition was checking against the nominal thread priority, whereas the kernel itself checks against the current priority instead. We were also assigning the nominal priority, when we should be assigning
current_priority, which takes priority inheritance into account.
This can lead to the incorrect priority being assigned to a thread.
Given we recursively update the relevant threads, we don't need to go through the whole mutex waiter list. This matches what the kernel does as well (only accessing the first entry within the waiting list) per execution.
=> kernel/thread: Amend conditional test and assignment within UpdatePriority()

src/core/hle/service/filesystem/fsp_srv.cpp, src/core/hle/service/filesystem/fsp_srv.h
This just acts as a basic setter for a given PID value and performs no further checking, so we can just store the passed in value.
=> fsp_srv: Unstub SetCurrentProcess

src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h
These are fairly basic HLE commands, that, for the most part, act as getters and setters. While we don't operate directly on the applets yet, for now, it's sufficient to just store the passed in data.
=> service/am: Supply remaining missing IAudioController functions

src/yuzu/bootmanager.cpp
Please see citra-emu/citra#4684 for the reason why this change is made.
=> Port citra-emu/citra#4684: "frontend: qt: fix a freeze where if you click on entry in the game list too fast, citra will hang"

src/common/CMakeLists.txt, src/common/thread_queue_list.h
We really don't need to pull in several headers of boost related machinery just to perform the erase-remove idiom (particularly with C++20 around the corner, which adds universal container std::erase and std::erase_if, which we can just use instead).
=> common/thread_queue_list: Remove unnecessary dependency on boost

src/common/CMakeLists.txt
When #2247 was created, thread_queue_list.h was the only user of boost-related code, however #2252 moved the page table struct into common, which makes use of Boost.ICL, so we need to add the dependency to it again.
=> common/CMakeLists: Amend boost dependency

src/core/CMakeLists.txt, src/core/hle/kernel/code_set.cpp, src/core/hle/kernel/code_set.h, src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/loader/elf.cpp, src/core/loader/nro.cpp, src/core/loader/nso.cpp
Moves our class that holds the executable data to be mapped into memory into its own source file, to avoid the need to drag in other kernel objects when only its definition is needed. Also adds some basic documentation for the data structure as well.
=> core/kernel: Migrate CodeSet to its own source files

src/common/bit_field.h, src/common/swap.h, src/core/hle/ipc.h, src/core/hle/service/hid/controllers/debug_pad.h, src/core/hle/service/hid/controllers/npad.h, src/core/hle/service/hid/controllers/touchscreen.h, src/core/hle/service/lm/lm.cpp, src/core/hle/service/nvdrv/devices/nvdevice.h, src/tests/CMakeLists.txt, src/tests/common/bit_field.cpp
See citra-emu/citra#4244 and citra-emu/citra#4599 for details.
Even if the enum swap template from 4244 is not used yet, it's good to have it around just in case and also in order to keep parity between Citra and yuzu.
=> Port citra-emu/citra#4244 and citra-emu/citra#4599: Changes to BitField

src/input_common/sdl/sdl.h, src/input_common/sdl/sdl_impl.cpp, src/input_common/sdl/sdl_impl.h
Previously they weren't properly returning the containers at all. While we're at it, introduce a type alias to make relevant function declarations and definitions shorter.
=> input_common/sdl: Correct return values within GetPollers implementations

src/core/hle/service/am/am.cpp
We already have the service related stuff set up for this, however, it's missing the function table.
=> service/am: Add function table for IDebugFunctions

src/core/hle/kernel/process.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h, src/core/hle/service/ldr/ldr.cpp
The CodeData flags were using the CodeFlags flag superset, when it should be using the DataFlags flag superset. Fixes booting Shantae Half-Genie Hero (and probably a few other games). While we're at it, rename CodeStatic/CodeMutable to Code and CodeData where applicable to disambiguate this a little better.
(ROData is technically not mutable, so mutable/static wasn't the best choice of terminology anyways)
=> kernel/vm_manager: Amend flag value for code data

src/core/memory.h
In 93da8e0abfcdcc6e3cb5488a0db12373429f1377, the page table construct was moved to the common library (which utilized these inclusions). Since the move, nothing requires these headers to be included within the memory header.
=> core/memory: Remove unnecessary includes

src/core/hle/kernel/mutex.cpp, src/core/hle/kernel/mutex.h, src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/svc.cpp
Makes it an instantiable class like it is in the kernel. This also allows removing reliance on global accessors in a following change, now that we can encapsulate a reference to the system instance in the class.
=> core/hle/kernel: Make Mutex a per-process class.

src/video_core/rasterizer_cache.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h
- Fixes graphical issues from transitions in Super Mario Odyssey.
=> Revert "Devirtualize Register/Unregister and use a wrapper instead."

src/common/common_types.h, src/common/page_table.cpp, src/common/page_table.h, src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp, src/core/memory.cpp, src/video_core/dma_pusher.h, src/video_core/engines/kepler_memory.cpp, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_dma.cpp, src/video_core/gpu.cpp, src/video_core/gpu.h, src/video_core/memory_manager.cpp, src/video_core/memory_manager.h, src/video_core/rasterizer_interface.h, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_buffer_cache.h, src/video_core/renderer_opengl/gl_global_cache.cpp, src/video_core/renderer_opengl/gl_global_cache.h, src/video_core/renderer_opengl/gl_primitive_assembler.cpp, src/video_core/renderer_opengl/gl_primitive_assembler.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_vulkan/vk_buffer_cache.cpp, src/video_core/renderer_vulkan/vk_buffer_cache.h, src/yuzu/debugger/graphics/graphics_surface.cpp, src/yuzu/debugger/graphics/graphics_surface.h
This rewrites our GPU memory manager to work more like a real page table, rather than just being a wrapper around the CPU memory manager (VMManager class). This is largely based on the VMManager class. This has a few benefits:
* Logically makes more sense, since the GPU has no knowledge of the process CPU address space
* Faster memory access (we do not need to translate GPUAddr to CPU VAddr always)
* Avoids the need to keep track of CPU VAddr in various places of the GPU
* Should make support for non-contiguous regions easier
* Simplifies some things, also allows us to remove a few hacks
Please review commit by commit. This also needs lots of testing.
=> gpu: Rewrite MemoryManager based on the VMManager implementation.

src/core/core.cpp, src/core/file_sys/cheat_engine.cpp, src/core/file_sys/cheat_engine.h, src/core/file_sys/patch_manager.cpp, src/core/file_sys/patch_manager.h, src/core/loader/nso.cpp
Instead, pass in the core timing instance and make the dependency explicit in the interface.
=> file_sys/cheat_engine: Remove use of global system accessors

CMakeLists.txt, src/CMakeLists.txt
Modifying CMAKE_* related flags directly applies those changes to every single CMake target. This includes even the targets we have in the externals directory.
So, if we ever increased our warning levels, or enabled particular ones, or enabled any other compilation setting, then this would apply to externals as well, which is often not desirable.
This makes our compilation flag setup less error prone by only applying our settings to our targets and leaving the externals alone entirely.
This also means we don't end up clobbering any provided flags on the command line either, allowing developers to specifically use the flags they want.
=> Migrate off directly modifying CMAKE_* compilation-related flags directly

src/core/CMakeLists.txt, src/core/file_sys/errors.h, src/core/file_sys/system_archive/system_archive.cpp, src/core/file_sys/system_archive/system_version.cpp, src/core/file_sys/system_archive/system_version.h, src/core/hle/service/set/set_sys.cpp, src/core/hle/service/set/set_sys.h
This adds: 
- A synthesized/open-source version of system archive 0x09 (SystemVersion), which contains a file that describes the current system version. The variant I implemented will return the following information:
- `5.1.0-0.0` on platform `YUZU` with long version `YuzuEmulated Firmware for NX 5.1.0-0.0`
- If using yuzu instead of the official 'NX' platform, becomes an issue, it can easily be changed via string.
- An implementation of GetFirmwareVersion and GetFirmwareVersion2 based on this. On hardware, both read the file aformentioned into state and then copy it into the requested buffer when called (the only difference being that GetFirmwareVersion zeros out two of the fields) -- instead of using the real SystemVersion title if the user has it present, this will always use the …
=> set_sys: Implement GetFirmwareVersion(2) for libnx hosversion

src/core/CMakeLists.txt, src/core/hle/kernel/object.cpp, src/core/hle/kernel/object.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/transfer_memory.cpp, src/core/hle/kernel/transfer_memory.h
Within the kernel, shared memory and transfer memory facilities exist as completely different kernel objects. They also have different validity checking as well. Therefore, we shouldn't be treating the two as the same kind of memory.
They also differ in terms of their behavioral aspect as well. Shared memory is intended for sharing memory between processes, while transfer memory is intended to be for transferring memory to other processes.
This breaks out the handling for transfer memory into its own class and treats it as its own kernel object. This is also important when we consider resource limits as well. Particularly because transfer memory is limited by the resource limit value set for it. While we currently don't handle resource limit testing against objects yet (but we do allow …
=>  core/hle/kernel: Split transfer memory handling out into its own class

src/core/file_sys/cheat_engine.cpp
These don't need to be visible outside of the translation unit, so they can be enclosed within an anonymous namespace.
=> core/cheat_engine: Make MemoryReadImpl and MemoryWriteImpl internally linked

src/core/hle/kernel/kernel.h
This is no longer necessary, as ResultVal isn't used anywhere in the header.
=> kernel/kernel: Remove unnecessary forward declaration

src/audio_core/stream.cpp, src/core/core_timing.cpp, src/core/core_timing.h, src/core/hle/kernel/kernel.cpp, src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h, src/core/hle/service/nvflinger/nvflinger.cpp
In some cases, our callbacks were using s64 as a parameter, and in other cases, they were using an int to represent late cycles, which is inconsistent. To make all callbacks consistent, we can just use an s64 as the type for late cycles, given it gets rid of the need to cast internally.
While we're at it, also resolve some signed/unsigned conversions that were occurring related to the callback registration.
=> core/core_timing: Make callback parameters consistent

src/core/hle/kernel/process.h
Another leftover from Citra that's now no longer necessary.
=> kernel/process: Remove unused AddressMapping struct

src/video_core/gpu.cpp, src/video_core/gpu.h
`smaphore` → `semaphore`
Just trivial renaming.
=> video_core/gpu: Amend typo in GPU member variable name

src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/renderer_vulkan/vk_resource_manager.cpp, src/video_core/renderer_vulkan/vk_resource_manager.h
Ensures that the signatures will always match with the base class.
Also silences a few compilation warnings.
=> video_core: Add missing override specifiers

src/core/hle/kernel/svc.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h
This unifies the heap allocation code into a single function, and cuts out parameters that don't make sense to have anymore, which were mostly holdovers from citra's kernel.
Previously we had both the base address to allocate the heap at and the permissions to set the heap as, however both of these are unnecessary. The base address of the heap will always be the one determined by the VMManager itself, and will always map it as read/write. This makes the function much simpler, the caller only needs to pass in a size, and everything else is taken care of.
We also weren't taking into account the case where a heap is already allocated, and then the function is called again with a size smaller than the current heap. In this case, we need to attempt to shrink the heap and free memory (which we …
=> kernel/vm_manager: Unify heap allocation/freeing functions

src/common/CMakeLists.txt, src/common/bit_util.h, src/common/multi_level_queue.h, src/core/hle/kernel/scheduler.cpp, src/core/hle/kernel/scheduler.h, src/tests/CMakeLists.txt, src/tests/common/bit_utils.cpp, src/tests/common/multi_level_queue.cpp
This replaces the core datatype for managing threads in the Kernel's Scheduler. The new one: should be faster, is iterable, provides more flexibility and is well tested.
=> Replace old Thread Queue for a new Multi Level Queue

src/core/hle/kernel/address_arbiter.cpp, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h, src/yuzu/debugger/wait_tree.cpp
This fixes a few wrongs in our implementation of wait address, cond vars and miscelleneus. It also creates the new Thread State "WaitCondVar" to mark a difference between threads waiting on condvars and threads waiting on mutexes.
=> Kernel: Fixes to Arbitration and SignalProcessWideKey Management

src/core/hle/service/fatal/fatal.cpp
Provides a name for most of the structure members of FatalInfo.
Based off RE, most of these structure members are register values, which makes, sense given this service is used to convey fatal errors. One member indicates the program entry point address, one is a set of bit flags used to determine which registers to print, and one member indicates the architecture type.
=> service/fatal: Name FatalInfo structure members

src/core/hle/kernel/scheduler.cpp, src/core/hle/kernel/scheduler.h, src/core/hle/kernel/thread.cpp
Since C++17, the type of the mutex being locked doesn't need to be specified within the guard itself, it can deduce that on its own. This also removes an unused parameter within AddThread that was made unused within b404fcd
=> kernel/scheduler: Minor tidying up

src/video_core/gpu_thread.cpp, src/video_core/gpu_thread.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/renderer_opengl.cpp
Removes two unused class variables--one in the OpenGL rasterizer, and one in the thread manager.
This also silences two unused private class member warnings with clang.
=> video_core/{gl_rasterizer, gpu_thread}: Remove unused class variables where applicable

src/video_core/rasterizer_cache.h, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_global_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_vulkan/vk_buffer_cache.cpp
Specifies the members in the same order that initialization would actually occur during construction.
This also silences -Wreorder warnings.
=> video_core: Amend constructor initializer list order where applicable

src/common/thread.cpp, src/common/thread.h
Many of these functions are carried over from Dolphin (where they aren't used anymore). Given these have no use (and we really shouldn't be screwing around with OS-specific thread scheduler handling from the emulator, these can be removed.
The function for setting the thread name is left, however, since it can have debugging utility usages.
=> common/thread: Remove unused functions

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/svc.cpp
Previously we weren't totally being accurate with how we were reporting memory usage to svcGetInfo. We were ignoring the main thread stack size and the size of the code being loaded into memory. This corrects that.
Technically we should also be reporting the memory used by map physical memory as well, however we currently don't handle that yet. This will be followed up by making our resource limits behave more properly so that we can properly indicate how much total physical memory is available instead of using a hardcoded constant in VMManager.
=> kernel/process: Report total physical memory used to svcGetInfo slightly better

src/common/detached_tasks.cpp, src/common/logging/backend.cpp, src/common/thread.h, src/common/threadsafe_queue.h, src/core/core_cpu.cpp, src/core/frontend/emu_window.cpp, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/svc.cpp, src/core/hle/service/nfp/nfp.cpp, src/core/perf_stats.cpp, src/input_common/keyboard.cpp, src/input_common/motion_emu.cpp, src/input_common/sdl/sdl_impl.cpp, src/video_core/debug_utils/debug_utils.cpp, src/video_core/debug_utils/debug_utils.h, src/video_core/gpu_thread.h, src/video_core/rasterizer_cache.h, src/web_service/web_backend.cpp, src/yuzu/applets/profile_select.cpp, src/yuzu/applets/software_keyboard.cpp, src/yuzu/applets/web_browser.cpp, src/yuzu/bootmanager.cpp, src/yuzu/bootmanager.h
Since C++17, the introduction of deduction guides for locking facilities means that we no longer need to hardcode the mutex type into the locks and guards themselves, making it easier to switch mutex types, should it ever be necessary in the future (and also makes for less reading).
=> general: Use deducation guides for std::lock_guard and std::unique_lock

src/core/hle/service/nfc/nfc.cpp, src/core/settings.cpp, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_general.cpp, src/yuzu/configuration/configure_general.ui, src/yuzu_cmd/config.cpp
This was initially added to prevent problems from stubbed/not implemented NFC services, but as we never encountered such and as it's only used in a deprecated function anyway, I guess we can just remove it to prevent more clutter of the settings.
=> core/yuzu: Remove enable_nfc setting

src/core/hle/kernel/code_set.h, src/core/hle/kernel/process.cpp, src/core/loader/elf.cpp, src/core/loader/nro.cpp, src/core/loader/nso.cpp
The use of a shared_ptr is an implementation detail of the VMManager itself when mapping memory. Because of that, we shouldn't require all users of the CodeSet to have to allocate the shared_ptr ahead of time. It's intended that CodeSet simply pass in the required direct data, and that the memory manager takes care of it from that point on.
This means we just do the shared pointer allocation in a single place, when loading modules, as opposed to in each loader.
=> kernel/codeset: Make CodeSet's memory data member a regular std::vector

src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/resource_limit.cpp, src/core/hle/kernel/resource_limit.h
This doesn't really provide any benefit to the resource limit interface. There's no way for callers to any of the service functions for resource limits to provide a custom name, so all created instances of resource limits other than the system resource limit would have a name of "Unknown".
The system resource limit itself is already trivially identifiable from its limit values, so there's no real need to take up space in the object to identify one object meaningfully out of N total objects.
=> kernel/resource_limit: Remove the name member from resource limits

src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/svc_wrap.h, src/core/hle/kernel/thread.cpp
Implements two basic info querying supervisor call functions. One retrieves the list of existing processes in general, while the other retrieves the list of threads under the current process. svcGetThreadList also allows passing in a handle to a kernel debug object, but we currently don't implement these events, so I've added an unimplemented assertion for that case.
Fairly simple as far as querying functions go.
=> kernel/svc: Implement svcGetProcessList and svcGetThreadList

src/yuzu/applets/profile_select.cpp, src/yuzu/applets/software_keyboard.cpp
Makes for less reading, and also makes Qt handle the translation of the buttons, rather than us needing to do so.
=> yuzu/applets/{profile_select, software_keyboard}: Use QDialogButtonBox standard buttons instead of custom ones where applicable

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/readable_event.cpp, src/core/hle/kernel/readable_event.h, src/core/hle/kernel/server_port.cpp, src/core/hle/kernel/server_port.h, src/core/hle/kernel/server_session.cpp, src/core/hle/kernel/server_session.h, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h, src/core/hle/kernel/wait_object.h
Just minor tidying to the interface.
1. Makes a parameter const-qualified, as it's not modified,
2. Avoids a sign conversion where avoidable
3. Makes AllWaitObjectsReady() a const-qualified member function, since it doesn't modify the thread instance's state.
=> kernel/thread: Minor interface cleanup

src/core/hle/kernel/shared_memory.cpp, src/core/hle/kernel/shared_memory.h, src/core/hle/kernel/svc.cpp
The kernel makes sure that the given size to unmap is always the same size as the entire region managed by the shared memory instance, otherwise it returns an error code signifying an invalid size.
This is similarly done for transfer memory (which we already have checks in place for).
=> kernel/shared_memory: Sanitize supplied size when unmapping

src/yuzu/debugger/profiler.cpp, src/yuzu/debugger/profiler.h
Moves includes into the cpp file where necessary. This way, microprofile-related stuff isn't dumped into other UI-related code when the dialog header gets included.
=> yuzu/debugger/profiler: Remove unnecessary includes

src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h
These service functions simply increment and decrement an internal 64-bit value. LeaveFatalSection also makes sure that it isn't called when no fatal section has been entered.
=> service/am: Implement EnterFatalSection/LeaveFatalSection

src/core/hle/kernel/object.cpp, src/core/hle/kernel/object.h
The AddressArbiter type isn't actually used, given the arbiter itself isn't a direct kernel object (or object that implements the wait object facilities). The arbiter class itself also doesn't need to make use of this.
Given this, we can remove the enum entry entirely.
=> kernel/object: Remove unused handle type entry

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/gl_shader_manager.h
We can just pass in the Maxwell3D instance instead of going through the system class to get at it, getting rid of a hidden dependency. Particularly given the Maxwell3D instance is always available around current callsites.
This also lets us simplify the interface a little bit. Since we pass in the Maxwell3D context now, we only really need to pass the shader stage index value in.
Also performs some minor related cleanup around the code.
=>  gl_shader_manager: Remove reliance on a global accessor within MaxwellUniformData::SetFromRegs()

src/yuzu/game_list.cpp, src/yuzu/game_list.h, src/yuzu/main.cpp, src/yuzu/main.h
This PR adds option to open the transferable shader cache.
On every OS the transferable shader cache folder opens. On Windows devices the transferable shader cache file for the selected game gets preselected as well.
If no transferable shader cache is present for the selected game, the following warning opens. No file explorer window opens in this case.
=> frontend: Open transferable shader cache for a selected game in the gamelist

src/core/hle/kernel/transfer_memory.cpp, src/core/hle/kernel/transfer_memory.h, src/core/hle/service/am/am.cpp
For whatever reason, shared memory was being used here instead of transfer memory, which (quite clearly) will not work based off the name of the function.
This corrects this wonky usage of shared memory.
=> service/am: Correct behavior of CreateTransferMemoryStorage()

src/common/lz4_compression.cpp
Introduced within 798d76f4c7018174e58702fb06a042dc8c84f0be, this only really has an effect within header files.
Silences a `-Wpragma-once-outside-header` warning with clang.
=> common/lz4_compression: Remove #pragma once directive from the cpp file

src/yuzu/main.cpp
While we're at it, don't use `<QtGui>` and `<QtWidgets>` (these include quite a bit of stuff we don't use), and instead include exactly which headers we actually need.
=> yuzu/main: Remove unnecessary includes

src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_global_cache.cpp, src/video_core/renderer_opengl/gl_primitive_assembler.cpp, src/video_core/renderer_opengl/gl_primitive_assembler.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h, src/video_core/renderer_opengl/gl_shader_cache.h, src/video_core/renderer_opengl/gl_shader_decompiler.h, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_gen.h, src/video_core/renderer_opengl/renderer_opengl.cpp
Quite a few unused includes have built up over time, particularly on core/memory.h. Removing these includes means the source files including those files will no longer need to be rebuilt if they're changed, making compilation slightly faster in this scenario.
=> video_core/renderer_opengl: Remove unnecessary includes

src/yuzu/main.cpp
Just a few minor changes. This also makes the error dialog slightly more unambiguous for those where English may not be their primary language (and disambiguates it in general).
=> yuzu/main: Minor adjustments to OnTransferableShaderCacheOpenFile()

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
TXQ returns integer types. Shaders usually do:
```
R0 = TXQ(); // => int
R0 = static_cast<float>(R0);
```
If we don't treat it as an integer, it will cast a binary float value from a theoretical integer to float - resulting in a corrupted number.
=> gl_shader_decompiler: Fix TXQ types

src/core/hle/service/am/am.cpp, src/core/hle/service/audio/audout_u.cpp, src/core/hle/service/audio/audren_u.cpp, src/core/hle/service/filesystem/fsp_srv.cpp, src/core/hle/service/sockets/sfdnsres.cpp, src/core/hle/service/spl/module.cpp, src/core/hle/service/ssl/ssl.cpp, src/core/hle/service/vi/vi.cpp
In several places, we have request parsers where there's nothing to really parse, simply because the HLE function in question operates on buffers. In these cases we can just remove these instances altogether.
In the other cases, we can retrieve the relevant members from the parser and at least log them out, giving them some use.
=> hle/service: Resolve unused variable warnings

src/video_core/gpu_asynch.cpp, src/video_core/gpu_thread.cpp, src/video_core/gpu_thread.h
This is the last part of the March Patreon changes that have not yet been PR'd yet (sorry for the delay - turns out we had lots of bugs to work through first in order to get here!)
Should fix a lot of issues with asynchronous GPU, although it's not perfect. Games like Super Mario Odyssey and Breath of the Wild work really well with this; other games like Pokemon Let's Go and Sonic Forces work much better with this setting turned off.
As such, asynchronous GPU emulation remains default OFF.
Also incorporates some changes from @degasus
=> gpu_thread: Improve synchronization by using CoreTiming.

src/core/hle/service/filesystem/filesystem.cpp
Rather than make a full copy of the path, we can just use a string view and truncate the viewed portion of the string instead of creating a totally new truncated string.
=> filesystem: Use a std::string_view in OpenFile()

src/video_core/macro_interpreter.cpp
Given we already ensure nothing can set the zeroth register in SetRegister(), we don't need to check if the index is zero and special case it. We can just access the register normally, since it's already going to be zero.
We can also replace the assertion with `.at()` to perform the equivalent behavior inline as part of the API.
=> video_core/macro_interpreter: Simplify GetRegister()

src/yuzu/debugger/graphics/graphics_surface.cpp
Performs a general cleanup to this code, given it hasn't been touched in quite a while.
- Adds the remaining surface formats to the format list.
- Cleans up overload deduction via the use of `qOverload`
- Displays error dialogs to indicate when file I/O errors occur during surface saving.
=> yuzu/debugger/graphics/graphics_surface: General cleanup

src/core/hle/result.h
This is a hold over from the 3DS error codes in Citra.
=> hle/result: Remove unnecessary bitfield entry for ResultCode

src/core/hle/kernel/svc.cpp
Just two overlooked checks that weren't added. We need to be checking whether or not the given address is within the kernel address space or if the given address isn't word-aligned and bail in these scenarios instead of trashing any kernel state.
=> kernel/svc: Properly sanitize mutex address in WaitProcessWideKeyAtomic

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Temporal generally indicates a relation to time, but this is just creating a temporary, so this isn't really an accurate name for what the function is actually doing.
=> gl_shader_decompiler: Rename GenerateTemporal() to GenerateTemporary()

src/core/file_sys/program_metadata.cpp, src/core/file_sys/program_metadata.h
BitField has been trivially copyable since e99a14862841841d74be8d0ea9426c2d23546b5e, so we can eliminate these TODO comments and use ReadObject() directly instead of memcpying the data.
=> file_sys/program_metadata: Remove obsolete TODOs

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This is a workaround for dumps of corrupted memory, it will report a valid message with asserts on and emit broken shaders with asserts off (instead of crashing). That being said, memory shouldn't be corrupted in the first place.
=> gl_shader_decompiler: Return early when an operation is invalid

src/core/file_sys/savedata_factory.cpp, src/core/file_sys/savedata_factory.h, src/core/hle/service/filesystem/filesystem.cpp, src/core/hle/service/filesystem/filesystem.h, src/core/hle/service/filesystem/fsp_srv.cpp
I realized that I updated the documentation on SwitchBrew a while ago, but never actually updated the structs within yuzu.
This also makes some minor cleanup-related changes involving the structs.
=> service/fsp_srv: Update SaveDataInfo and SaveDataDescriptor structs

src/core/file_sys/nca_metadata.cpp, src/core/file_sys/nca_metadata.h
enum class elements from the same enum can already be compared against one another without the need for explicitly defined comparison operators.
=> file_sys/nca_metadata: Remove unnecessary comparison operators for TitleType

src/video_core/gpu_thread.cpp
Since c5d41fd812d7eb1a04f36b76c08fe971cee0868c callback parameters were changed to use an s64 to represent late cycles instead of an int, so this was causing a truncation warning to occur here. Changing it to s64 is sufficient to silence the warning.
=> video_core/gpu_thread: Silence truncation warning in ThreadManager's constructor

src/core/arm/dynarmic/arm_dynarmic.cpp, src/core/arm/dynarmic/arm_dynarmic.h, src/core/arm/unicorn/arm_unicorn.h, src/core/hle/service/audio/audin_u.cpp, src/core/hle/service/audio/audrec_u.cpp, src/core/hle/service/nvdrv/devices/nvdisp_disp0.h, src/core/hle/service/nvdrv/interface.h, src/core/hle/service/nvdrv/nvmemp.h, src/core/hle/service/service.h, src/core/hle/service/set/set_cal.h, src/core/hle/service/ssl/ssl.cpp, src/core/hle/service/vi/vi.cpp, src/core/loader/xci.h
Applies the override specifier where applicable. In the case of destructors that are defaulted in their class definition, they can just simply be removed.
This also removes the unnecessary inclusions being done in audin_u and audrec_u, given their close proximity.
=> core: Add missing override specifiers where applicable

src/core/file_sys/fsmitm_romfsbuild.cpp
The given string instance doesn't need to be copied entirely, we can just use a view instead.
=> file_sys/fsmitm_romfsbuild: Utilize a string_view in romfs_calc_path_hash

src/video_core/memory_manager.cpp, src/video_core/memory_manager.h
A few of these functions only really perform memory reads or searching for memory regions without actually modifying any internal state in the memory manager. This marks those member functions const to signify this (as well as allow their use in const contexts).
=> video_core/memory_manager: Mark a few member functions with the const qualifier

src/core/arm/unicorn/arm_unicorn.cpp, src/core/arm/unicorn/arm_unicorn.h, src/core/gdbstub/gdbstub.cpp
Please see citra-emu/citra#4651 for more details and the unsquashed commits.
=> Port citra-emu/citra#4651: "gdbstub: Fix some bugs in IsMemoryBreak() and ServeBreak. Add workaround to let watchpoints break into GDB."

src/common/bit_util.h, src/common/multi_level_queue.h
Silences some truncation warnings that occur when compiling the scheduler.
=> common/multi_level_queue: Silence truncation warnings

src/core/hle/kernel/server_session.h
Given server sessions can be given a name, we should allow retrieving it instead of using the default implementation of GetName(), which would just return `"[UNKNOWN KERNEL OBJECT]"`.
=> kernel/server_session: Provide a GetName() override

src/core/memory.h
These are holdovers from Citra and can be removed.
=> core/memory: Remove unused enum constants

src/core/hle/ipc_helpers.h, src/core/hle/kernel/client_port.cpp, src/core/hle/kernel/server_port.cpp, src/core/hle/kernel/server_port.h, src/core/hle/kernel/server_session.cpp, src/core/hle/kernel/server_session.h
Keeps the returned type consistent with the function name (and potentially considerably less template work depending on tuple implementations). While we're at it, we can also simplify handling of session pairs with the use of structured bindings.
=> kernel/{server_port, server_session}: Return pairs instead of tuples from pair creation functions

src/video_core/renderer_opengl/gl_shader_manager.h, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_state.h
Implements individual `Apply` methods that change a small subset of the OpenGL state machine. This is the backing functionality of a following commit to remove full `Apply` calls in the places where it's not needed, aswell as de-globalizing `gl_state`.
It also uses generic functions to compare and assign values.
=> gl_state: Rework to enable individual applies

src/core/arm/dynarmic/arm_dynarmic.cpp, src/core/arm/dynarmic/arm_dynarmic.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/process.cpp, src/core/hle/kernel/scheduler.cpp, src/core/memory.cpp, src/core/memory.h, src/tests/core/arm/arm_test_common.cpp
Centralizes the page table changing to one place instead of making all calling code manually handle it. We can also eliminate an unnecessary page table pointer variable within ARM_Dynarmic, since the current page table will always be that of the main running kernel process.
=> core/memory: Minor simplifications to page table management

src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/shader/decode/texture.cpp, src/video_core/shader/shader_ir.h, src/video_core/shader/track.cpp
Implements AOFFI arguments for TEX and TLD4. AOFFI maps to the `Offset` GLSL suffix family - e.g. `textureOffset` will use `TEX.AOFFI` while `texture` just uses `TEX`.
This requires light constant folding because in hardware AOFFI coordinates are passed through a packed register while in GLSL these are required to be constant (although Nvidia's driver allows variable coordinates). In case the constant folding fails - fallback to a variable in-shader implementation that will fail on incompatible hardware (this case has not been found).
Arguments are passed through `gpr20`, the first valid argument for these is the bindless pack, this is not handled in this PR.
=> shader_ir: Implement AOFFI for TEX and TLD4

CMakeLists.txt
See citra-emu/citra#4718 for more details.
should be pretty self-explanatory. i had the citra repo cloned to a path with spaces, so the clang-format target wouldn't work. this pull request fixes that
=> Port citra-emu/citra#4718: "fix clang-format target when using a path with spaces on windows"

src/video_core/engines/maxwell_3d.cpp
All games write this. We know they write it, there's no need to abort execution for it.
=> maxwell_3d: Reduce severity of ProcessSyncPoint

src/common/assert.h, src/video_core/renderer_opengl/gl_shader_cache.cpp
This was the behavior we had before the new GPU VM, all it does is return a nullshader code if the host_ptr given is null just like before. It avoids certain crashes and notifies appropriately.
=> shader_cache: Permit a Null Shader in case of a bad host_ptr.

src/core/hle/kernel/process.cpp
We need to ensure dynarmic gets a valid pointer if the page table is resized (the relevant pointers would be invalidated in this scenario). In this scenario, the page table can be resized depending on what kind of address space is specified within the NPDM metadata (if it's present).
Fixes BotW/ARMS/anything that doesn't specify a 39-bit address space.
While this isn't a preferable approach to the problem, I'd rather refactor our initialization process with everything in working order first, before changing it, potentially causing more regressions. So this will have a follow-up to it.
=> kernel/process: Set page table when page table resizes occur.

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.h
This PR makes sure GL reads on the correct pack size for the respective buffer.
=> gl_backend: Align Pixel Storage

src/yuzu/loading_screen.cpp
In our error console, when loading a game, the strings:
```
QString::arg: Argument missing: "Loading...", 0
QString::arg: Argument missing: "Launching...", 0
```
would occasionally pop up when the loading screen was running. This was due to the strings being assumed to have formatting indicators in them, however only two out of the four strings actually have them. This only applies the arguments to the strings that have formatting specifiers provided, which avoids these warnings from occurring.
Example of the warnings that would occur:
=> yuzu/loading_screen: Resolve runtime Qt string formatting warnings

src/core/core.cpp, src/core/core.h, src/core/crypto/key_manager.cpp, src/core/file_sys/patch_manager.cpp, src/core/file_sys/patch_manager.h, src/core/file_sys/registered_cache.cpp, src/core/file_sys/registered_cache.h, src/core/file_sys/romfs_factory.cpp, src/core/file_sys/submission_package.cpp, src/core/file_sys/submission_package.h, src/core/hle/service/am/applets/web_browser.cpp, src/core/hle/service/aoc/aoc_u.cpp, src/core/hle/service/filesystem/filesystem.cpp, src/core/hle/service/filesystem/filesystem.h, src/core/loader/nso.cpp, src/yuzu/game_list.cpp, src/yuzu/game_list.h, src/yuzu/game_list_worker.cpp, src/yuzu/game_list_worker.h, src/yuzu/main.cpp, src/yuzu/main.h, src/yuzu_cmd/yuzu.cpp
This generifies the current `RegisteredCache` and `RegisteredCacheUnion` into one: `ContentProvider`. This also provides a version of content provider to be used by the frontend and populated with the game list. This allows treating the game list as a full-fledged source of data instead of accessing the current game only through the AppLoader.
Some things that this allows:
- Removing custom code for packed updates
- Displaying the real version numbers instead of `PACKED`, `XCI`, or `NSP` as the version for packed updates
- Storing DLC, Updates, System Archives, and the like in a directory with games without the need to install
- Avoiding a common pattern across FS code where the apploader is queried for info and if it failed the RCache is then queried
- Avoiding another common FS pattern …
=> file_sys: Provide generic interface for accessing game data

src/video_core/dma_pusher.cpp, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_global_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/textures/convert.cpp, src/video_core/textures/convert.h, src/video_core/textures/texture.h
Nothing in this header relies on common_funcs or the memory manager.
This gets rid of reliance on indirect inclusions in the OpenGL caches.
=> video_core/texures/texture: Remove unnecessary includes

src/core/hle/kernel/server_session.cpp
These are holdovers from Citra.
=> kernel/server_session: Remove obsolete TODOs

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/utils.cpp, src/video_core/renderer_opengl/utils.h
This aims to reduce the amount of OpenGL calls with the usage of [ARB_multi_bind](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_multi_bind.txt). It packs binding data into a class, this way uniform and shader storage buffers can be updated across shader stages with a single call (two if you count SSBOs).
No noticeable performance improvements have been found.
=> gl_rasterizer: Use ARB_multi_bind to update buffers with a single call per drawcall

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
A simple fix to fermi copies on linear textures.
=> Correct Fermi Copy on Linear Textures.

src/video_core/CMakeLists.txt, src/video_core/texture_cache.cpp, src/video_core/texture_cache.h
Implements an API agnostic texture view based texture cache. Classes defined here are intended to be inherited by the API implementation and used in API-specific code.
This implementation exposes protected virtual functions to be called from the implementer.
Before executing any surface copies methods (defined in API-specific code) it tries to detect if the overlapping surface is a superset and if it is, it creates a view. Views are references of a subset of a surface, it can be a superset view (the same as referencing the whole texture).
Current code manages 1D, 1D array, 2D, 2D array, cube maps and cube map arrays with layer and mipmap level views. Texture 3D slices views are not implemented.
If the view attempt fails, the fast path is invoked with the overlapping textures (defined in …
=> video_core: Implement API agnostic view based texture cache

src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
This just relaxes some unnecessary restrictions as copies between depth and color formats are allowed in glCopyImageSubData
=> gl_rasterizer_cache: Relax restrictions on FastCopySurface

src/core/hle/kernel/client_port.h, src/core/hle/kernel/client_session.h, src/core/hle/kernel/process.h, src/core/hle/kernel/readable_event.h, src/core/hle/kernel/resource_limit.h, src/core/hle/kernel/server_port.h, src/core/hle/kernel/server_session.h, src/core/hle/kernel/shared_memory.h, src/core/hle/kernel/thread.h, src/core/hle/kernel/writable_event.h
Some objects declare their handle type as const, while others declare it as constexpr. This makes the const ones constexpr for consistency, and prevents unexpected compilation errors if these happen to be attempted to be used within a constexpr context.
=> kernel: Make handle type declarations constexpr

src/core/arm/dynarmic/arm_dynarmic.cpp, src/core/arm/dynarmic/arm_dynarmic.h, src/core/arm/unicorn/arm_unicorn.cpp, src/core/arm/unicorn/arm_unicorn.h, src/core/core_cpu.cpp, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/svc.h, src/core/hle/kernel/svc_wrap.h
Adjusts the interface of the wrappers to take a system reference, which allows accessing a system instance without using the global accessors.
This also allows getting rid of all global accessors within the supervisor call handling code. While this does make the wrappers themselves slightly more noisy, this will be further cleaned up in following changes. This eliminates the global system accessors in the current code while preserving the existing interface, making any replacement changes much less noisy.
This will also make deglobalizing the memory subsystem a little nicer, since the system instance will already be available for utilizing said deglobalized subsystem.
=> kernel/svc: Deglobalize the supervisor call handlers

.gitmodules, externals/CMakeLists.txt, src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.h
Adds a SPIR-V decompiler for Vulkan.
This PR adds [sirit](https://github.com/ReinUsesLisp/sirit) as dependency. This is due to SPIR-V being a bytecode IR instead of a human-readable language like GLSL. It feels weird adding to yuzu a dependency that I wrote (with help from @FernandoS27), but I couldn't find at the time of writing this a proper solution for a SPIR-V decompilation backend.
There were three major approaches:
- Emitting (unstandardised) SPIR-V text and compiling it to bytecode SPIR-V with an external tool.
- Emitting Vulkan compatible GLSL and compiling it down to SPIR-V with an external tool.
- Emitting SPIR-V bytecode directly with an external tool. 
I dropped the first option due to not being standardized. The second option is feasible and it leads to the possibility of …
=> vk_shader_decompiler: Implement a SPIR-V decompiler

src/common/swap.h
Simplifies the preprocessor ifdefs needed to define the integral free functions for performing byte swapping. We can just use the compiler builtins for the range of compilers that we actually support and have CI for rather than special-casing for every single OS variant.
This also improves the codegen of the generic path variants of the byte swapping functions (see the last commit in particular for significantly more info regarding the assembly output).
=> common/swap: Minor cleanup and improvements to byte swapping functions

src/common/scope_exit.h
The template type here is actually a forwarding reference, not an rvalue reference in this case, so it's more appropriate to use std::forward to preserve the value category of the type being moved.
=> common/scope_exit: Replace std::move with std::forward in ScopeExit()

src/core/frontend/emu_window.h, src/yuzu/bootmanager.cpp, src/yuzu/bootmanager.h, src/yuzu/main.cpp, src/yuzu/main.h, src/yuzu_cmd/emu_window/emu_window_sdl2.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2.h
Since QT5, QGLWidget has been deprecated and superseded with QOpenGLWidget and other classes. I replace usages of QGLWidget with the comparable QOpenGLWindow, which gives us the bonus ability to easily create shared contexts.
To support shared contexts, frontends can now implement the GraphicsContext class and the core can attempt to get a shared context from the frontend by calling GetSharedContext. If the rendering backend doesn't need shared contexts, then it just doesn't request a shared context from the frontend. If the backend does request a shared context, it should be ready to handle the case where the frontend returns nullptr (ie: because its not supported on this platform or frontend)
In this PR, I added shared context support to the QT and SDL frontends, but I haven't had a …
=> Frontend: Migrate to QOpenGLWindow and support shared contexts

src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/gl_shader_manager.h
Moves logic from the header file to its source file.
=> gl_shader_manager: Move code to source file and minor clean up

src/core/hle/service/filesystem/fsp_srv.cpp
Logs two unused variables (also getting rid of unused variable warnings). This also gets rid of unnecessary parameter popping in IDirectory's Read() function. This doesn't actually take any input parameters--it only has output parameters.
=> fsp_srv: Minor cleanup related changes

src/core/hle/service/nvflinger/nvflinger.cpp, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_graphics.cpp, src/yuzu/configuration/configure_graphics.ui
Continuing from a conversation on Discord with jroweboy, this PR implements a temporary hack that forces games to run in 30FPS mode.
The hack can be turned on/off using a toggle under the Graphics settings (off by default).
This should allow testers to properly test some 30FPS games, such as PLGP/E or BotW (these have messed up audio/physics when running in 60FPS mode).
Once a proper solution to the framerate limiting issue is implemented, this can be reverted or closed.
This hack can also be expanded to allow for a custom FPS value if needed.
=> Add a toggle to force 30FPS mode

src/core/hle/service/ldr/ldr.cpp
The first two words are actually used to specify a process ID, so we don't need to skip over these. This also removes an erroneous parameter in UnloadNro. This service function only passes in one address, not two.
=> ldr: Minor amendments to IPC-related parameters

src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h
This is a holdover from Citra that currently remains unused, so it can be removed from the Thread interface.
=> kernel/thread: Remove BoostPriority()

src/core/hle/kernel/svc.cpp, src/core/hle/kernel/svc_wrap.h, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h
These are utilized for mapping code modules into memory. Notably, the ldr service would call this in order to map objects into memory. This is what our HLE implementation of said service should actually be calling into to perform the mapping, but our interface isn't currently set up that way to allow for that.
With a few more subsequent modifications to our svc handler following these changes, this will actually be made possible. This'll also have the benefit of allowing HLE'd services to not constantly re-roll their own memory mapping code whenever a service would otherwise invoke an SVC instruction.
=> kernel/svc: Implement svcMapProcessCodeMemory/svcUnmapProcessCodeMemory

src/common/lz4_compression.h, src/common/zstd_compression.h
These two files were missing the #pragma once directive.
=> common/{lz4_compression, zstd_compression}: Add missing header guards

src/yuzu/configuration/configure_dialog.cpp, src/yuzu/configuration/configure_hotkeys.cpp, src/yuzu/configuration/configure_hotkeys.h
Minor clean-up related changes to the hotkey configuration dialog. This also notably prevents the logging window from stealing the initial focus of the hotkey dialog window.
=> yuzu/configure_hotkey: Minor changes

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_global_cache.cpp, src/video_core/renderer_opengl/gl_global_cache.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.h, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode/memory.cpp, src/video_core/shader/shader_ir.h
Also adds support for bigger global memory buffers (now it uses hardware's limit). Flushing to guest memory is dangerous so this add a warning when that action is done.
Some game shaders in their global memory operations are being tracked with a bad constant buffer address, fixing that's beyond the scope of this PR.
=> shader/memory: Implement STG and global memory flushing

src/yuzu/CMakeLists.txt, src/yuzu/game_list_p.h
This is a compile definition introduced in Qt 4.8 for reducing the total potential number of strings created when performing string concatenation. This allows for less memory churn.
This can be read about [here](https://blog.qt.io/blog/2011/06/13/string-concatenation-with-qstringbuilder/)
For a change that isn't source-compatible, we only had one occurrence that actually need to have its type clarified, which is pretty good, as far as transitioning goes.
=> CMakeLists: Define QT_USE_QSTRINGBUILDER for the Qt target

src/video_core/renderer_opengl/gl_rasterizer.cpp
- Avoid resetting OpenGL's state after a `Clear` invocation.
- Just apply the state relevant to the clear.
In theory and from my testing this is safe, but I'm tagging it for canary to make sure.
=> gl_rasterizer: Apply just the needed state on Clear

src/video_core/engines/shader_bytecode.h, src/video_core/shader/decode/memory.cpp
Reduce the severity of some checks from asserts to `LOG_DEBUG`, this is mostly because with the current state of shading languages (or shading representations) we can't manage them without a software implementation. Host shader compilers can choose whatever approach the want and OpenGL (and Vulkan) is fine with that.
[SPV_KHR_float_controls](https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_float_controls.html) might help in this regard, but it just exposes this functionality per-shader module instead of per-operation. SPIR-V is capable of exposing these per-operation but that functionality is reserved for kernels, not shaders.
=> shader_ir/decode: Reduce the severity of common assertions

src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_sampler_cache.cpp, src/video_core/renderer_opengl/gl_sampler_cache.h, src/video_core/renderer_vulkan/vk_sampler_cache.cpp, src/video_core/renderer_vulkan/vk_sampler_cache.h, src/video_core/sampler_cache.cpp, src/video_core/sampler_cache.h
First abstract Vulkan's immutable sampler cache into a templated class and then port it to OpenGL. Now samplers should be immutable on OpenGL.
=> gl_sampler_cache: Port sampler cache to OpenGL

src/core/hle/kernel/process.cpp, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/thread.h
This member variable is entirely unused. It was only set but never actually utilized. Given that, we can remove it to get rid of noise in the thread interface.
=> kernel/thread: Remove unused guest_handle member variable

src/core/hle/kernel/svc.cpp
This call was added to the SVC handlers in the 8.0.0 kernel, so we can finally give it a name (name taken from SwitchBrew).
=> kernel/svc: Name supervisor call 0x36

src/yuzu/bootmanager.cpp, src/yuzu/bootmanager.h
Resolves -Wreorder warnings. These will automatically be initialized to nullptr anyways, so these were redundant.
While we're in the same area, an unused include can be removed as well.
=> yuzu/bootmanager: Resolve constructor initializer list warnings

src/core/hle/kernel/wait_object.cpp, src/core/hle/kernel/wait_object.h
This doesn't actually modify internal state of a wait object, so it can be const qualified.
=> kernel/wait_object: Make GetHighestPriorityReadyThread() a const member function

src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode/arithmetic_half.cpp, src/video_core/shader/decode/arithmetic_half_immediate.cpp, src/video_core/shader/decode/half_set.cpp, src/video_core/shader/decode/half_set_predicate.cpp, src/video_core/shader/decode/hfma2.cpp, src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h
Fixes and adds new functionality to half-float instruction decompilation. Description in individual commits.
Thanks to @FernandoS27 for finding some of these bugs.
=> shader_ir/decode: Miscellaneous fixes to half-float decompilation

src/core/hle/service/audio/audctl.cpp, src/core/hle/service/audio/audctl.h
These two service functions are literally hardcoded to always return these values without any other error checking.
=> service/audctl: Implement GetTargetVolumeMin() and GetTargetVolumeMax()

src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_cache.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.h, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_gen.h
Run a test at boot to determine if the hardware is capable of using variable AOFFI (`textureOffset` and friends). In case it's not, disable it on hardware/drivers that don't support it. This should fix #2363 on AMD devices.
This adds a `gl_device` object similar to `vk_device` to store data related to the OpenGL device.
=> gl_shader_decompiler: Disable variable AOFFI on unsupported devices

src/CMakeLists.txt, src/yuzu_cmd/yuzu.cpp
Previously we were building with MBCS, which is pretty undesirable. We want the application to be Unicode-aware in general.
=> CMakeLists: Ensure we specify Unicode as the codepage on Windows

.travis/macos/upload.sh
See citra-emu/citra#4748 for more details.
This is no longer needed for logging because logs are written to disk.
=> Port citra-emu/citra#4748: "Launch directly in Mac without terminal"

src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/process.cpp, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h, src/core/hle/kernel/wait_object.cpp, src/yuzu/debugger/wait_tree.cpp
Previously we had a two wait synchronization thread status types (we should only have one wait type, but that's a separate issue altogether). This is \**big sigh*\* yet another holdover from Citra. In particular, this was necessary for `svcWaitSynchronization1` and `svcWaitSynchronizationN` supervisor calls. On the Switch, however, we only have one supervisor call–`svcWaitSynchronization`.
This removes the extra type and unifies code to use the one wait type. This also relocates the svcCancelSynchronization behavior to be a part of the thread interface, as future changes will alter this to be more correct (which requires access to thread internals).
=> kernel/svc: Clean up wait synchronization related functionality

src/core/hle/kernel/process.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h
Makes the dependency on the system instance explicit within VMManager's interface.
=> kernel/vm_manager: Remove usages of global system accessors

.travis/linux-mingw/build.sh, .travis/linux-mingw/deps.sh, .travis/linux-mingw/docker.sh, .travis/linux/build.sh, .travis/linux/deps.sh, .travis/linux/docker.sh, CMakeModules/GenerateSCMRev.cmake
See citra-emu/citra#3839 for more details.
The Dockerfiles can be found at [yuzu-emu/build-environments](https://github.com/yuzu-emu/build-environments).
This is a WIP change to the current CI workflow.
In this PR, the builder no longer install packages during the building process, instead, the prebuilt Docker images from hub.docker.com/r/citraemu/build-environments are used.
This can ensure the consistency across the builds and frozen builds are absolutely frozen to the exact version required.
There are several problems in this PR. They will be ironed out very soon. In the mean time, you can stlll comment about your concerns against the change.
MinGW builds will have seperate commits to address the changes. (b/c it's unsure if we will use cross-compile to …
=> Port citra-emu/citra#3839: "travis: use prebuilt image"

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/shader/decode/texture.cpp
Makes use of src, so it's not considered unused. In the other case, the variable can be removed entirely.
=> gl_rasterizer: Silence unused variable warnings

src/common/zstd_compression.cpp
Introduced in 72477731ed20c56a4d6f18a22f43224fab667cef. This is only necessary within header files.
=> common/zstd_compression: Remove #pragma once directive from source file

src/core/frontend/emu_window.cpp, src/core/frontend/emu_window.h
This class is used in a polymorphic context, so destruction of the context will lead to undefined behavior if the destructor isn't virtual.
=> core/frontend/emu_window: Make GraphicsContext's destructor virtual

externals/CMakeLists.txt
Better instruction support has been added since the last update.
the (quite long) changelog:
```
f5233bfc constant_propagation_pass: Fold EOR operations
be3ba545 ir/value: Add member function to check whether or not all bits of a contained value are set
14297804 constant_propagation_pass: Fold AND operations
0d1f9841 constant_propagation_pass: Fold OR operations
7868411d constant_propagation_pass: Fold NOT operations
bcb947eb externals: Update fmt to 5.2.1
49041cb4 Squashed 'externals/fmt/' changes from 135ab5cf..3e75ad98
d3263fd6 ir/value: Add an IsZero() member function to Value's interface
01aa5096 ir/value: Add a GetImmediateAsS64() function
8f262d48 ir/value: Add IsSignedImmediate() and IsUnsignedImmediate() functions to Value's interface
e0eec323 constant_propagation_pass: Combine …
```
=> externals: Update dynarmic to master

src/video_core/CMakeLists.txt, src/video_core/engines/engine_upload.cpp, src/video_core/engines/engine_upload.h, src/video_core/engines/fermi_2d.h, src/video_core/engines/kepler_compute.cpp, src/video_core/engines/kepler_compute.h, src/video_core/engines/kepler_memory.cpp, src/video_core/engines/kepler_memory.h, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/engines/maxwell_dma.cpp, src/video_core/engines/maxwell_dma.h, src/video_core/gpu.cpp
Implement Subengine Upload.
Add documentation references to each engine.
Introduce the Compute Engine.
Fixes and Corrections to DMA Engine:
- Add parameters for swizzling mode.
- Support layered texture copies.
- Use ReadBlock/WriteBlock for obtaining and writting data.
=> Corrections and Implementation on GPU Engines

src/core/memory.h
Recent changes to memory-related code resulted in this being unused, so we can remove it.
=> core/memory: Remove unused FlushMode enum

src/yuzu/configuration/configure_dialog.cpp
Removes the `?` button in the upper right of the dialog. The button is unused entirely, so there's no real reason to expose it in the UI at all.
Before:
After:
=> configure_dialog: Remove the Whats This? button from the dialog

src/yuzu/compatdb.cpp
Keeps the code consistent in regards to how the buttons are referred to.
=> yuzu/compatdb: Remove unnecessary qualifiers

src/yuzu/hotkeys.h
The behavior of the Hotkey constructor is already accomplished via in-class member initializers, so the constructor is superfluous here.
=> yuzu/hotkeys: Remove unnecessary constructor

src/CMakeLists.txt
The C++ standard allows constexpr variables declared with the extern keyword to have external linkage. Previously MSVC wasn't abiding by this. This just makes the compiler more standards compliant during builds. Unfortunately, MSVC doesn't enable this as part of `/permissive-`
More info on this flag can be seen [here](https://docs.microsoft.com/en-us/cpp/build/reference/zc-externconstexpr?view=vs-2019).
=> src/CMakeLists: Add /Zc:externConstexpr to the MSVC build flags

src/core/hle/service/audio/audctl.cpp
The state of these service calls are still the same in version 8.0.0, so we can update the comments to reflect that.
=> service/audctl: Update documentation comments to be relative to 8.0.0

src/CMakeLists.txt
Ensures that -Wall is always active as a compilation flag regardless of build type.
=> CMakeLists: Explicitly specify -Wall for the non-MSVC case

src/CMakeLists.txt
By default, MSVC doesn't use standards-compliant volatile semantics. This makes it behave in a standards-compliant manner, making expectations more uniform across compilers.
This is safe to apply, as we currently don't make direct use of the `volatile` cv-qualifier anywhere in our code, which is nice, because it won't potentially break existing code.
More documentation about the flag can be seen [here](https://docs.microsoft.com/en-us/cpp/build/reference/volatile-volatile-keyword-interpretation?view=vs-2019)
=> CMakeLists: Specify /volatile:iso for MSVC

src/video_core/gpu_thread.cpp, src/video_core/renderer_opengl/gl_rasterizer_cache.cpp, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode/texture.cpp, src/video_core/textures/astc.cpp
Silences a few compilation warnings, and reduces visual noise. Also resolves one instance of the constructor initializer list not matching the declaration order of the variables.
=> video_core: Remove a few unused variables and functions

src/video_core/memory_manager.cpp, src/video_core/memory_manager.h
Just performs a little tidying up of the interface.
- Marks the constructor explicit
- Defaults the destructor in the cpp file.
- Fixes various typos.
- Marks a member function with the const qualifier.
=> video_core/memory_manager: Minor tidying

src/yuzu/configuration/configure_graphics.cpp
Compatibility profile and the disk shader cache settings shouldn't be changed at runtime. This aims to address that shadowing those options.
=> qt/configure_graphics: Shadow options at runtime

src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Without this the SDL2 frontend would always use OpenGL core, ignoring the setting.
=> yuzu_cmd: Use OpenGL compat when asked in the settings

src/yuzu_cmd/yuzu.cpp
The SDL2 frontend never bound the OpenGL context, resulting on a white screen and no-ops all over the backend.
=> yuzu_cmd: Make OpenGL's context current

src/yuzu/about_dialog.cpp, src/yuzu/main.cpp, src/yuzu/main.h
Specifies the conversions explicitly to avoid implicit conversions from const char* to QString. This makes it easier to disable implicit QString conversions in the future.
In this case, the implicit conversion was technically wrong as well. The implicit conversion treats the input strings as ASCII characters. This would result in an incorrect conversion being performed in the rare case a branch name was created with a non-ASCII Unicode character, likely resulting in junk being displayed.
=> yuzu/{about_dialog, main}: Specify string conversions explicitly for SCM-related info

src/yuzu/bootmanager.cpp
Nvidia's proprietary driver creates a real OpenGL compatibility profile without this option, meanwhile Intel (and probably AMD, I haven't tested it) require that QSurfaceFormat::FormatOption::DeprecatedFunctions is explicitly enabled.
This might supersede #2464 since it should also fix mesa drivers.
=> yuzu/bootmanager: Explicitly enable deprecated OpenGL features on compat

src/video_core/renderer_opengl/gl_shader_gen.cpp
Avoids performing copies into the pair being returned. Instead, we can just move the resources into the pair, avoiding the need to make copies of both the std::string and ShaderEntries struct.
=> gl_shader_gen: std::move objects where applicable

src/yuzu/applets/profile_select.cpp
This is a user-facing string, so it should be marked as translatable.
=> yuzu/applets/profile_select: Mark header string as translatable

src/core/hle/kernel/svc.cpp
These are only used from within this translation unit, so they don't need to have external linkage. They were intended to be marked with this anyways to be consistent with the other service functions.
=> kernel/svc: Mark GetThreadList() and UnmapProcessCodeMemory() as internally linked

src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/object.h, src/core/hle/kernel/readable_event.cpp, src/core/hle/kernel/svc.cpp, src/core/hle/service/am/am.cpp, src/core/hle/service/am/applets/applets.cpp, src/core/hle/service/aoc/aoc_u.cpp, src/core/hle/service/audio/audout_u.cpp, src/core/hle/service/audio/audren_u.cpp, src/core/hle/service/btdrv/btdrv.cpp, src/core/hle/service/btm/btm.cpp, src/core/hle/service/hid/controllers/npad.cpp, src/core/hle/service/nfp/nfp.cpp, src/core/hle/service/nifm/nifm.cpp, src/core/hle/service/nim/nim.cpp, src/core/hle/service/nvdrv/interface.cpp, src/core/hle/service/nvflinger/buffer_queue.cpp, src/core/hle/service/vi/display/vi_display.cpp, src/yuzu/debugger/wait_tree.cpp
Renames the members to more accurately indicate what they signify. "OneShot" and "Sticky" are kind of ambiguous identifiers for the reset types, and can be kind of misleading. Automatic and Manual communicate the kind of reset type in a clearer manner. Either the event is automatically reset, or it isn't and must be manually cleared.
The "OneShot" and "Sticky" terminology is just a hold-over from Citra where the kernel had a third type of event reset type known as "Pulse". Given the Switch kernel only has two forms of event reset types, we don't need to keep the old terminology around anymore.
=> core/kernel/object: Rename ResetType enum members for clarity

src/yuzu/debugger/graphics/graphics_breakpoints.cpp, src/yuzu/debugger/profiler.cpp, src/yuzu/debugger/wait_tree.cpp
Another set of changes that brings us slightly closer to disabling implicit string conversions in Qt code. This makes all of the string conversions explicit in the debugger, which is relatively lower traffic in terms of changes compared to the rest of the UI code.
=>  yuzu/debugger: Specify string conversions explicitly 

src/core/hle/ipc_helpers.h
Currently, this overload isn't used, so this wasn't actually hit in any code, only the float overload is used. Which is great, because it means nothing else was affected by this.
Spotted by @wwylele in https://github.com/citra-emu/citra/pull/4702
=> ipc_helpers: Amend floating-point type in Pop<double> specialization

src/video_core/renderer_opengl/maxwell_to_gl.h
nouveau uses these to implement `glClear` with scissor testing enabled.
=> maxwell_to_gl: Add TriangleFan primitive topology

src/video_core/engines/engine_upload.cpp, src/video_core/engines/engine_upload.h
Resolves a -Wreorder compilation warning and makes the class potentially not result in a compilation error with regards to forward declarations. The rest is minor tidying up.
=>  video_core/engines/engine_upload: Minor tidying

src/video_core/renderer_opengl/gl_rasterizer.cpp
nouveau sets the register to zero on some circumstances, this causes OpenGL errors. Bypass this by applying a minimum size for point size. The arbitrary number of one has been chosen since that's what a desktop Nvidia GPU reports as minimum + it doesn't make sense to have points smaller than 1 pixel. It may matter on multi-sampled environments, but Nvidia on OpenGL can't set this value anyways.
=> gl_rasterizer: Limit OpenGL point size to a minimum of 1

src/video_core/renderer_opengl/gl_rasterizer.cpp
`MakeQuadArray` was receiving the converted number of vertices instead of the original size. Thanks @FernandoS27 for finding this out.
=> gl_rasterizer: Pass the right number of array quad vertices count

src/core/hle/service/am/am.cpp
Previously this would fall through and return successfully, despite being an out of bounds read or write.
=> service/am: Add missing return in error case for IStorageAccessor's Read/Write()

src/video_core/engines/maxwell_3d.cpp
Lessens the amount of code that needs to be read, and gets rid of the need to introduce an indexing variable. Instead, we just operate on the objects directly.
While we're in the same area, we can eliminate the use of three magic constants within CallMethod().
=> video_core/engines/maxwell_3d: Simplify for loops into ranged for loops within InitializeRegisterDefaults()

src/video_core/engines/maxwell_3d.h
std::memset is used to clear the entire register structure, which requires that the Regs struct be trivially copyable (otherwise undefined behavior is invoked). This prevents the case where a non-trivial type is potentially added to the struct.
=> video_core/engines/maxwell_3d: Add is_trivially_copyable_v check for Regs

src/video_core/engines/maxwell_3d.cpp
This was reduced due to happening on most games and at such constant
rate that it affected performance heavily for the end user. In general,
we are well aware of the assert and an implementation is already
planned.
=> maxwell_3d: reduce severity of different component formats assert.

src/video_core/gpu_thread.cpp, src/video_core/gpu_thread.h, src/yuzu/applets/error.cpp
With C++17's deduction guides, the type doesn't need to be explicitly specified within locking primitives anymore. Previously the types were removed from locks, but a few stragglers have crept in over time.
=> yuzu: Remove explicit types from locks where applicable

src/video_core/macro_interpreter.cpp
It seems instructions marked with the 'exit' flag will not cause an exit when executed within a delay slot.
This was hwtested by fincs.
=> GPU/MMEInterpreter: Ignore the 'exit' flag when it's executed inside a delay slot.

src/video_core/gpu_thread.h
std::move within a copy constructor (on a data member that isn't mutable) will always result in a copy. Because of that, the behavior of this copy constructor is identical to the one that would be generated automatically by the compiler, so we can remove it.
=> video_core/gpu_thread: Remove redundant copy constructor for CommandDataContainer

src/core/hle/service/audio/audren_u.cpp, src/core/hle/service/audio/audren_u.h
GetAudioRendererWorkBufferSize() was a particularly ugly function from an understanding viewpoint, given it essentially had dumped raw disassembly in there. This is bad, because it fails to document where the actual values come from. It's also even more messy because there's literally no way anyone would actually write an algorithm like that.
I spent some time working out how the values were actually derived and placed everything within its own lambda function to make it more explicit which portions of the size were being derived (working out the command generator's variadic work buffer size was the most "fun").
While I was in the same area, I also added handling for REV5's version 2 of the performance metrics and, as stated above, handling of REV5's variadic command buffer. While there …
=> service/audren_u: Get rid of magic values within GetAudioRendererWorkBufferSize

src/video_core/renderer_opengl/gl_shader_disk_cache.cpp, src/video_core/renderer_opengl/gl_shader_disk_cache.h
Gets rid of the need to use `u8` directly to represent boolean values. Instead, we can just provide overloads that do all the work of converting between the formats for use, allowing the use of the type we actually want to represent (a bool).
This also gets rid of a few unnecessary copies that would otherwise result in heap allocation.
=> gl_shader_disk_cache: Minor cleanup

src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h, src/video_core/shader/track.cpp
Simplifies quite a bit of the template parameter pack shenanigans and makes it obey the standard (std::vector isn't capable of being used in a constexpr context, which OperationNode contains). Aside from that, all behavior for OperationNode is equivalent.
This also marks the tracking member functions as const member functions, since they don't alter internal state.
=> shader/shader_ir: Minor changes

src/video_core/dma_pusher.cpp
This is a measure to avoid crashes on command list reading as an empty 
command_list is considered a NOP.
=> Dma_pusher: ASSERT on empty command_list

src/core/hle/kernel/svc.cpp, src/core/hle/kernel/thread.h
Makes the code much nicer to follow in terms of behavior and control flow. It also fixes a few bugs in the implementation. This initial implementation predated the introduction of the process capability descriptor handling, so these are just a few things that fell through the cracks because of it.
Notably, the thread's owner process shouldn't be accessed in order to retrieve the core mask or ideal core. This should be done through the current running process. The only reason this bug wasn't encountered yet is because we currently only support running one process, and thus every owner process will be the current process.
We also weren't checking against the process' CPU core mask to see if an allowed core is specified or not.
With this out of the way, it'll be less noisy to implement …
=>  kernel/svc: Reorganize and fix up the initial handling of svcSetThreadCoreMask()

src/video_core/engines/maxwell_3d.h, src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode/memory.cpp, src/video_core/shader/decode/other.cpp, src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h
`AL2P` and `ALD.PHYS` is used to access attributes (and varyings) indirectly, code like this:
```glsl
in vec4 my_attributes[2];
uniform int index;
void main() {
gl_Position = my_attributes[index];
}
```
Emits:
```
/*0028*/                   AL2P R1, R0, 0x80;
/* .. */
/*0048*/                   ALD.PHYS R1, a[R1];
```
`AL2P` is used to return a physical address with an offset, for example: `AL2P R1, R0, 0x80` stores in `R1` the address of `R0 + 0x80`. This value can then be used to access the attribute indirectly: `ALD.PHYS R1, a[R1]`.
To implement this I made `AL2P` return a table physical address, for example `AL2P R1, R0, 0x80` will exactly return `R0 + 0x80`. This is a fake address since the memory isn't actually there but we can't do better on GLSL without analysing shader's …
=> shader: Implement AL2P and ALD.PHYS

src/video_core/macro_interpreter.cpp
This reverts a tested behavior on delay slots not exiting if the exit 
flag is set. Currently new tests are required in order to ensure this 
behavior and figure if we are missing something else in our code.
=> Revert #2466

src/yuzu/configuration/configure_audio.cpp, src/yuzu/configuration/configure_gamelist.cpp, src/yuzu/configuration/configure_general.cpp, src/yuzu/configuration/configure_input.cpp, src/yuzu/configuration/configure_input_player.cpp, src/yuzu/configuration/configure_mouse_advanced.cpp, src/yuzu/configuration/configure_per_general.cpp, src/yuzu/configuration/configure_profile_manager.cpp, src/yuzu/configuration/configure_system.cpp, src/yuzu/configuration/configure_web.cpp
Like the previous changes in the same vein, this moves the UI code a step closer to disabling implicit string conversions. This makes the configuration window compatible with disabled implicit QString conversions. After this, all that's left is to deal with some of the top-level source files in the project directory and the conversions can be disabled.
This also uncovered some strings that weren't marked as translatable but should have been. These are also corrected.
=> yuzu/configuration: Specify string conversions explicitly

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
In a lot of places throughout the decompiler, string concatenation via operator+ is used quite heavily. This is usually fine, when not heavily used, but when used extensively, can be a problem. operator+ creates an entirely new heap allocated temporary string and given we perform expressions like:
```cpp
std::string thing = a + b + c + d;
```
this ends up with a lot of unnecessary temporary strings being created and discarded, which kind of thrashes the heap more than we need to. Given we utilize fmt in some AddLine calls, we can make this a part of the ShaderWriter's API. We can make an overload that simply acts as a passthrough to fmt.
This way, whenever things need to be appended to a string, the operation can be done via a single string formatting operation instead of discarding …
=>  gl_shader_decompiler: Add AddLine() overloads with single function that forwards to libfmt

src/yuzu/bootmanager.cpp, src/yuzu/game_list.cpp, src/yuzu/game_list.h, src/yuzu/game_list_p.h, src/yuzu/game_list_worker.cpp, src/yuzu/loading_screen.cpp, src/yuzu/util/util.cpp
Makes all top-level source files compilable with implicit Qt string conversions disabled. Now all that's left is to address main.cpp, which I'll do in a follow-up PR, as it's quite a large file, and would like to have those changes reviewed separately. The follow up change will also finally pass compilation flags that disable implicit Qt string conversions.
=> yuzu/game_list: Specify string conversions explicitly

src/yuzu/configuration/config.cpp, src/yuzu/configuration/config.h
Over time our config values have grown quite numerous in size. Unfortunately it also makes the single functions we have for loading and saving values more error prone.
For example, we were loading the core settings twice when they only should have been loaded once. In another section, a variable was shadowing another variable used to load settings from a completely different section.
Finally, in one other case, there was an extraneous endGroup() call used that didn't need to be done. This was essentially dead code and also a bug waiting to happen.
This separates the section loading code into its own separate functions. This keeps variables only visible to the code that actually needs it, and makes it much easier to visually see the end of each individual configuration group. It also makes …
=> configuration/config: Move config loading and saving to functions based off groups

src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h
This allows for forming comment nodes without making unnecessary copies of the std::string instance.
e.g. previously:
```cpp
Comment(fmt::format("Base address is c[0x{:x}][0x{:x}]",
cbuf->GetIndex(), cbuf_offset));
```
Would result in a copy of the string being created, as CommentNode() takes a std::string by value (a const ref passed to a value parameter results in a copy). Now, only one instance of the string is ever moved around.
=> shader/shader_ir: Make Comment() take a std::string by value

src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/hle_ipc.h, src/core/hle/kernel/server_session.cpp, src/core/hle/service/vi/vi.cpp
See citra-emu/citra#4716 for more details.
This reduces the boilerplate that services have to write out the current thread explicitly. Using current thread instead of client thread is also semantically incorrect, and will be a problem when we implement multicore (at which time there will be multiple current threads)
=> Port citra-emu/citra#4716: "HLE/IPC: HLEContext can memorize the client thread and use it for SleepClientThread"

src/yuzu/configuration/config.cpp, src/yuzu/configuration/config.h
Allows the configuration code to build successfully with implicit string conversions disabled. I got a little ahead of myself in the previous conversion-related PR. The following PR after this one, will be the one that addresses main.cpp and disables implicit conversions.
=>  yuzu/configuration/config: Specify string conversions explicitly

src/video_core/engines/shader_bytecode.h, src/video_core/shader/decode/memory.cpp, src/video_core/shader/shader_ir.h
These instructions have a similar behaviour to STG and LDG, in fact at the moment of writing this I don't know what in particular makes them different since both write to and read to arbitrary memory addresses. Like STG's name suggests it might just allow writes to global memory meanwhile ST can write to local or other types of memory - that is a guess and it's very unlikely someone does that.
nouveau uses these to implement SSBOs.
=> shader/memory: Implement generic memory stores and loads (ST and LD)

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_cache.h, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp, src/video_core/renderer_opengl/gl_shader_disk_cache.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h, src/yuzu/bootmanager.cpp
During disk cache driver side shader compilation use shared contexts to invoke from multiple worker threads. As far as I tested, this works only on Nvidia's proprietary driver. Other vendors will on the other contexts but one at a time, there's not much we can do about drivers building shaders one at a time when being invoked from multiple threads. I even tried removing `glGet*`s to avoid halting execution without luck.
This uses #2017 as base. The last commit is the important one.
=> gl_shader_cache: Use shared contexts to build shaders in parallel at boot

src/yuzu/CMakeLists.txt, src/yuzu/applets/error.cpp, src/yuzu/applets/software_keyboard.cpp, src/yuzu/applets/software_keyboard.h, src/yuzu/main.cpp
The final PR in terms of QString conversions. This resolves all of the implicit string conversions in main.cpp, fixes up any missed locations (applets), and then finally disables implicit string conversions in the CMakeLists--enforcing the behavior at compile-time from this point onwards.
=> yuzu/main: Specify string conversions explicitly

src/yuzu/configuration/configure_dialog.cpp, src/yuzu/configuration/configure_hotkeys.cpp, src/yuzu/configuration/configure_hotkeys.h, src/yuzu/util/sequence_dialog/sequence_dialog.cpp
Cleans up a bit of the code related to managing hotkeys. This is in preparation for making the titles of hotkeys actually translatable, which will be useful in the future once translation support gets merged in.
=> configure_hotkeys: Minor cleanup

src/common/file_util.cpp, src/common/file_util.h, src/yuzu_cmd/config.cpp
Just does a little bit of tidying. Initially meant to just be the first commit, but kind of snowballed into this, as more things were found.
Makes a few more functions more flexible with string types by using std::string_view, and also makes some parameters consistent (`ReadFileToString` and `WriteStringToFile` had swapped argument ordering, between one another which is error-prone).
Also corrects a potential crash case within `GetCurrentDir()`, where nullptr was being returned, despite the return type being `std::string` (which doesn't allow being constructed from a null pointer).
=> common/file_util: Minor cleanup

src/core/hle/service/aoc/aoc_u.cpp
Cleanup a bit of the interface and fills in some parameters (we weren't actually popping the process ID parameter) and logs it out along with the rest of the entries. The rest of the changes are relatively minor, like not allocating when we don't need to, etc.
=> service/aoc_u: Minor cleanup

src/video_core/renderer_opengl/utils.cpp, src/video_core/renderer_opengl/utils.h
Uses a std::string_view instead of a std::string, given the pointed to string isn't modified and is only used in a formatting operation. This is nice because a few usages directly supply a string literal to the function, allowing these usages to otherwise not heap allocate, unlike with std::string*. It's also nice for the early-return case, as no resources will be unnecessarily created and destroyed within the function. 
While we're at it, we can combine the address formatting into a single formatting call. 
\* - Unless the std::string implementation does small-string optimization and the string fits in the string buffer.
=> renderer_opengl/utils: Use a std::string_view with LabelGLObject()

src/core/core_timing_util.cpp, src/core/loader/nso.cpp
Silences a few -Wsign-compare warnings.
=> loader/nso, core/core_timing_util: Silence sign-comparison warning

src/core/frontend/emu_window.h, src/yuzu/bootmanager.cpp, src/yuzu/bootmanager.h, src/yuzu_cmd/CMakeLists.txt, src/yuzu_cmd/emu_window/emu_window_sdl2.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2.h, src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2_gl.h, src/yuzu_cmd/yuzu.cpp
Moves OpenGL specific SDL2 window initialization to its own file.
=>  yuzu_cmd: Split emu_window OpenGL implementation into its own file 

src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_per_general.cpp, src/yuzu/game_list_worker.cpp, src/yuzu/main.cpp, src/yuzu/ui_settings.h
Currently, the game list can drag (for up to 10 seconds) with a large collection of games and/or add-ons. This is because the current algorithm searches the entire list of addons for each game when populating the names for the "Add-Ons" column (which is terribly inefficient and unnecessary). This adds a simple cache that writes the list of addon names and versions to a text file in yuzu_dir/cache/game_list. This will also cache the icons and names of titles, as after add-ons those are the next two biggest time consumers.
I tested this for time difference in two different configurations (one 'light' with about 5 games + 3 updates and one 'heavy' with about 30 games + 20 updates/dlc) In the light the load time went from about 4 seconds to sub 1 second and in the heavy the load time went …
=> yuzu: Implement a caching mechanism for the game list

src/common/CMakeLists.txt, src/common/uuid.cpp, src/common/uuid.h, src/core/CMakeLists.txt, src/core/frontend/applets/profile_select.cpp, src/core/frontend/applets/profile_select.h, src/core/hle/service/acc/acc.cpp, src/core/hle/service/acc/profile_manager.cpp, src/core/hle/service/acc/profile_manager.h, src/core/hle/service/am/applets/profile_select.cpp, src/core/hle/service/am/applets/profile_select.h, src/core/hle/service/mii/mii.cpp, src/core/hle/service/mii/mii_manager.cpp, src/core/hle/service/mii/mii_manager.h, src/yuzu/applets/profile_select.cpp, src/yuzu/applets/profile_select.h, src/yuzu/configuration/configure_profile_manager.cpp, src/yuzu/main.h
**DO NOT MERGE - Awaiting SSBU to become bootable for further testing**
Implements a MiiManager class to serialize/deserialize the Mii database to saves, and perform operations upon it. Provides conversions between MiiInfo (unpacked format -- used by games usually) and MiiStoreData (packed bitfield format -- used for storage).
The format conversion was 'HW tested' by creating 50 miis with one physical difference from default and then comparing the serialized versions. This is also how the default mii was obtained.
This also extracts the Service::Account::UUID class to Common::UUID as other services make use of it to.
=> mii: Implement MiiManager backend and several mii service commands

src/core/frontend/framebuffer_layout.cpp, src/core/frontend/framebuffer_layout.h, src/yuzu/bootmanager.cpp, src/yuzu/bootmanager.h
Tidies up a bit of the bootmanager code and makes it safer. Particularly, we now enforce that the parent of GRenderWindow is GMainWindow, and get rid of the downcast within the constructor, which makes the interface more type-safe.
We also now log out the destination of a screenshot rather than just saying it was saved. We also check if it actually successfully saved to disk before printing said logging message out. If we were unable to save the screenshot to disk, we now display an error message in the log.
The rest of the changes are primarily cosmetic changes made to make reading it nicer.
=> yuzu/bootmanager: Minor interface tidying

src/yuzu/game_list_worker.cpp
This properly handles Unicode file paths, whereas the previous one using streams and our own IOFile would choke on them (particularly the file streams).
I pointed out in the initial PR for the game list cache that the API exposed by Qt should be preferred over the use of the standard library and ourselves, but I guess it got overlooked.
=> game_list_worker: Use QFile over our own IOFile instance or std streams for the game list cache

src/yuzu/applets/profile_select.cpp, src/yuzu/applets/profile_select.h, src/yuzu/applets/software_keyboard.cpp, src/yuzu/applets/software_keyboard.h, src/yuzu/main.cpp
The index value returned by Qt is always going to be signed, so we shouldn't be returning it as an unsigned value; especially when we might be operating with other Qt objects that make use of it. Instead, we can convert it to the unsigned variant for functions that specifically need the index as an unsigned value.
We can also eliminate the GetStatus() function, as this behavior is already provided by the `QDialog::exec` function. We just need to check the return value of it.
=> yuzu/{profile_select, software_keyboard}: Tidy up interface

src/core/CMakeLists.txt, src/core/file_sys/control_metadata.cpp, src/core/file_sys/control_metadata.h, src/core/hle/service/am/am.cpp, src/core/hle/service/ns/errors.h, src/core/hle/service/ns/language.cpp, src/core/hle/service/ns/language.h, src/core/hle/service/ns/ns.cpp, src/core/hle/service/ns/ns.h, src/core/hle/service/ns/ns_language.cpp, src/core/hle/service/ns/ns_language.h
This now respects the application's supported language list from NACP.
This fixes a crash when launching games with unsupported languages (e.g., launching Japanese Puyo Puyo Tetris with language set to English).
=> Implement/Fix IApplicationFunctions::GetDesiredLanguage

src/input_common/sdl/sdl.h, src/input_common/sdl/sdl_impl.cpp, src/input_common/sdl/sdl_impl.h
Performs a little bit of miscellaneous tidying up. Notably, this simplifies deleter handling for joystick instances and prevents a crash in the event a particular failure path is taken within the SDLState constructor.
=> input_common/sdl/sdl_impl: Minor cleanup

src/audio_core/stream.cpp, src/core/core_timing_util.cpp, src/core/core_timing_util.h, src/core/hle/kernel/thread.cpp, src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp, src/core/hle/service/time/time.cpp, src/video_core/gpu_thread.cpp
Simplifies the interface and bases it off of the `std::chrono` time units. This way any other time unit can have their conversions handled by the standard library (either implicitly through regular cross-unit conversions, or explicitly with duration_cast, should it be necessary).
=> core/core_timing_util: Use std::chrono types for specifying time units

src/core/hle/service/ncm/ncm.cpp
- Implements LR service commands 0-2, which simply take no args and returns an object of the appropriate type.
- Rename LocationResolver to LR to prevent confusion with ILocationResolver.
- Add command names for ILocationResolver, IRegisteredLocationResolver, IAddOnContentLocationResolver.
=> lr: Add command handler skeletons for Open*LocationResolver

src/yuzu/CMakeLists.txt
Passes three defines that Qt doesn't enable by default that make it harder to introduce bugs in Qt frontend code. Mainly makes it so written code is required to be more explicit in expressing its intent. e.g. if narrowing is desirable, it should be explicitly handled so it's made evident the writer intended that behavior to happen, etc.
=> yuzu/CMakeLists: Pass compilation flags that make it more difficult to cause bugs in Qt code

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h
Given we don't currently implement the personal heap yet, the existing memory querying functions are essentially doing what the memory querying types introduced in 6.0.0 do.
So, we can build the necessary machinery over the top of those and just use them as part of info types.
=> kernel/svc: Handle TotalPhysicalMemoryAvailableWithoutMmHeap and TotalPhysicalMemoryUsedWithoutMmHeap

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h
Makes the interface more flexible in terms of how Create() may be called, while still allowing the parameter itself to be moved into.
=> kernel/process: Make Create()'s name parameter be taken by value

src/core/hle/kernel/vm_manager.cpp
This is performing more work than would otherwise be necessary during VMManager's destruction. All we actually want to occur in this scenario is for any allocated memory to be freed, which will happen automatically as the VMManager instance goes out of scope. Anything else being done is unnecessary work.
=> kernel/vm_manager: Remove redundant Reset call in destructor

src/core/file_sys/ips_layer.cpp
Given 'replace' is assigned to on the following line, this isn't necessary, as the underlying data is going to be overwritten entirely.
=> file_sys/ips_layer: Remove unnecessary reserve() call

src/common/hex_util.cpp, src/common/hex_util.h, src/core/crypto/key_manager.cpp, src/core/file_sys/ips_layer.cpp, src/core/file_sys/patch_manager.cpp, src/core/file_sys/registered_cache.cpp, src/core/file_sys/submission_package.cpp, src/core/file_sys/xts_archive.cpp, src/core/hle/service/am/applets/general_backend.cpp, src/core/hle/service/ldr/ldr.cpp, src/core/loader/nso.cpp
Given the only difference is the input type, we can make this a little more generic and apply to any contiguous type. While we're at it, we can request the necessary memory ahead of time when building up the string to prevent unnecessary reallocations, given it's as trivial as calling `reserve()`.
=> common/hex_util: Combine HexVectorToString() and HexArrayToString()  

src/video_core/CMakeLists.txt, src/video_core/engines/const_buffer_info.h, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h
This is a requisite to have a single method in `gl_rasterizer` to upload constant buffers when we implement the compute pipeline.
While changing this code I removed unused parameters in related methods.
=>  video_core/engines: Move ConstBufferInfo out of Maxwell3D 

src/yuzu/main.cpp
Added missing whitespace character between two words in the "Warning Missing Derivation Components" warning message box.
=> Added missing space between two words

src/core/hle/service/audio/audren_u.cpp
This is actually an auto-reset event in the audio service itself, not a manual one.
=> service/audio/audren_u: Correct event reset type for the system event

src/core/hle/service/audio/audren_u.cpp
Even though it has been proven that IAudioRenderer:SystemEvent is 
actually an automatic event. The current implementation of such event is 
all thought to be manual. Thus it's implementation needs to be corrected 
when doing such change. As it is right now this PR introduced a series 
of regressions on softlocks on multiple games. Therefore, this pr 
reverts such change until a correct implementation is made.
=> Revert PR 2590.

src/CMakeLists.txt, src/yuzu_tester/CMakeLists.txt, src/yuzu_tester/config.cpp, src/yuzu_tester/config.h, src/yuzu_tester/default_ini.h, src/yuzu_tester/emu_window/emu_window_sdl2_hide.cpp, src/yuzu_tester/emu_window/emu_window_sdl2_hide.h, src/yuzu_tester/resource.h, src/yuzu_tester/service/yuzutest.cpp, src/yuzu_tester/service/yuzutest.h, src/yuzu_tester/yuzu.cpp, src/yuzu_tester/yuzu.rc
This is designed to make unit testing of switch homebrew easier and automatable.
Adds:
- A new frontend (`yuzu_tester`) that will not show a window or emulate input (but otherwise is basically `yuzu_cmd`).
- A service that is only installed for that frontend called `yuzutest` -- this is so the homebrew can communicate with yuzu the results of the test, (NOTE: this is not present in yuzu-qt or yuzu-cmd and can't be used to determine if the app is running on an emulator unless it is running on the test utility.)
When a NRO/NSO that uses the testing service is run on `yuzu-tester`, it will be executed headlessely and when complete the result code from the service will display on screen.
The service also supports passing in a string (for example, to parameterize the test) and string output …
=> yuzu_tester: Add and implement testing utility for homebrew

src/core/CMakeLists.txt, src/core/crypto/partition_data_manager.cpp, src/core/file_sys/kernel_executable.cpp, src/core/file_sys/kernel_executable.h, src/core/file_sys/program_metadata.cpp, src/core/file_sys/program_metadata.h, src/core/loader/kip.cpp, src/core/loader/kip.h, src/core/loader/loader.cpp, src/core/loader/loader.h, src/yuzu/game_list.cpp
KIP files are used by some sysmodules, both homebrew and official. This is intended to be a "first step" towards LLE emulation of services, but all this PR adds is the ability to execute KIPs as if the main application is a KIP. This supports both compressed (with BLZ) and uncompressed KIPs.
This also adds INI file parsing, which is a custom yet simple container Nintendo uses to package up to 0x50 KIPs together. This is used internally with Package 2 (to contain some of the most essential sysmodules, like fsp-srv, sm, ldr, and pm)
I wrote a quick sample homebrew and used `elf2kip` to make a KIP out of it (as an initial PoC):
My KIP if any of you want to try it:
[Hello World KIP File](https://github.com/yuzu-emu/yuzu/files/3255505/hello.zip)
I was also able to launch:
- A homebrew KIP for …
=> loader, file_sys: Add support for parsing and loading KIP (Kernel Internal Process) files

src/core/hle/service/acc/acc.cpp
The sanitizing function ensures that the returned type is always the correct type. This eliminates warnings without extra casts.
=> service/acc: Silence truncation warnings

src/core/reporter.cpp
Fixes a build issue that seems to be caused by renaming `Common::HexVectorToString` to `Common::HexToString`.
=> HexVectorToString -> HexToString

src/core/frontend/applets/general_frontend.cpp, src/core/frontend/applets/general_frontend.h, src/core/frontend/applets/web_browser.cpp, src/core/frontend/applets/web_browser.h, src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h, src/core/hle/service/am/applet_ae.cpp, src/core/hle/service/am/applet_ae.h, src/core/hle/service/am/applet_oe.cpp, src/core/hle/service/am/applet_oe.h, src/core/hle/service/am/applets/applets.cpp, src/core/hle/service/am/applets/applets.h, src/core/hle/service/am/applets/general_backend.cpp, src/core/hle/service/am/applets/general_backend.h, src/core/hle/service/am/applets/web_browser.cpp, src/core/hle/service/am/applets/web_browser.h, src/core/hle/service/service.cpp, src/yuzu/applets/web_browser.cpp, src/yuzu/applets/web_browser.h, src/yuzu/main.cpp
This does:
- Adds the parental control applet backend based on switchbrew and personal RE verification. This also adds the frontend base class with all of the functions and a default impl which will simply log. I plan to eventually add a Qt frontend if I ever get around to doing the `pctl` service legitimately.
- 'Fixes' web applet processing -- based on data from switchbrew we now properly parse the input data for ShimKind and the TLVs. 
- Adds all offline web applet modes to LibAppletOffline -- previously we just assumed it was manual, but this allows applications to call for legal or system data pages as well and also implements the necessary nuances of each. After this PR, I plan on adding some sort of call into Qt so you can view app legal docs from the game list.
- Adds the …
=> applets: Implement backend and default frontend for Parental Controls and EShop (ShopN) applets

src/core/file_sys/nca_metadata.h, src/core/file_sys/registered_cache.cpp, src/core/file_sys/submission_package.cpp, src/core/hle/service/am/applets/web_browser.cpp, src/core/loader/nsp.cpp, src/core/loader/xci.cpp
Fixes the installation error and warnings when installing a patch NSP without DeltaFragments. Many patch NSPs do not include these even if they're listed in the CNMT, since they are not useful outside of Nintendo's official patch installation process on real consoles, and there is no need to install them when they're present.
Also, I only renamed `ContentRecordType::Patch` since it has the most potential to cause confusion, but it may be a good idea to rename the rest of the values to their more common names as well (Manual -> HtmlDocument, Legal -> LegalInformation). I'm not 100% sure but I believe these names are official.
=> file_sys: Ignore DeltaFragment NCAs during installation

src/video_core/rasterizer_cache.h, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_global_cache.cpp
This PR just adds the mutex protection to the highest level as race conditions could still happen.
=> rasterizer_cache: Protect inherited caches from submission level

src/core/CMakeLists.txt, src/core/hle/service/service.cpp, src/core/hle/service/time/interface.cpp, src/core/hle/service/time/interface.h, src/core/hle/service/time/time.cpp, src/core/hle/service/time/time.h, src/core/hle/service/time/time_sharedmemory.cpp, src/core/hle/service/time/time_sharedmemory.h
This PR attempts to implement the shared memory provided by GetSharedMemoryNativeHandle. There is still more work to be done however that requires a rehaul of the current time module to handle clock contexts. This PR is mainly to get the basic functionality of the SharedMemory working and allow the use of addition to it whilst things get improved on.
Things to note:
Memory Barriers are used in the SharedMemory and a better solution would need to be done to implement this. Currently in this PR I’m faking the memory barriers as everything is sync and single threaded. They work by incrementing the counter and just populate the two data slots. On data reading, it will read the last added data.
Specific values in the shared memory would need to be updated periodically. This isn't included in …
=> Implement Time::GetSharedMemoryNativeHandle

src/core/CMakeLists.txt, src/core/hle/service/acc/acc.cpp, src/core/hle/service/acc/acc.h, src/core/hle/service/acc/acc_u0.cpp, src/core/hle/service/acc/errors.h
InitializeApplicationInfoRestricted will need further implementation as it's checking for other user requirements about the game. As we're emulating, we're assuming the user owns the game so we skip these checks currently, implementation will need to be added further on
=> Implemented InitializeApplicationInfo & InitializeApplicationInfoRestricted

src/core/hle/service/set/set.cpp, src/core/hle/service/set/set.h, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_debug.cpp, src/yuzu/configuration/configure_debug.ui, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h
This quite simply returns the current config value to the game to determine if the game is running under 'Retail' or 'Quest' (Kiosk) mode. Kiosk mode is commonly used in stores to display/show games to consumers.
It's unknown how this affects most games, but it's assumed they will show some sort of promotional/advertising material or a tutorial/minigame mode.
Closes #2615
=> set: Implement GetQuestFlag with config option

src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h
Previously each thread instance was holding a block of memory representing a TLS region. An issue with that is:
1. It's not necessary (it's mostly another carry-over from Citra).
2. It over-exposes info that shouldn't really be shared outside of a process instance.
This brings the TLS slot management more in line with how the kernel on the actual system handles it and makes way for handling other aspects related to TLS regions more correctly.
A thread instance is also no longer a requirement for retrieving a TLS region. This is important because a thread isn't the only thing that's assigned a TLS region. Process instances are also assigned one during creation. This will be handled in another PR, as it requires some changes outside of the kernel. This change preserves existing behavior …
=> kernel/process: Decouple TLS handling from threads

src/core/core_cpu.cpp, src/core/settings.cpp, src/core/settings.h, src/core/telemetry_session.cpp, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_general.cpp, src/yuzu/configuration/configure_general.ui, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h, src/yuzu_tester/config.cpp, src/yuzu_tester/default_ini.h
A normal user shouldn't change this, as it will slow down the emulation and can lead to bugs or crashes. So let's move the setting to Debug, like we do for Citra already.
=> yuzu: Move CPU Jit setting to Debug tab

src/core/hle/kernel/svc.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h, src/core/memory.cpp, src/core/memory.h
Handles the placement of the stack a little nicer compared to the previous code. This resolves a few asserts that may have occurred for some games since #2555 
The stack (new map) region, shouldn't be the width of the entire address space if the size of the region calculation ends up being zero. It should be placed at the same location as the TLS IO region and also have the same size.
In the event the TLS IO region contains a size of zero, we should also be doing the same thing. This fixes our memory layout a little bit and also resolves some cases where assertions can trigger due to the memory layout being incorrect.
While we're at it, this also renames usages of "new map" to "stack" to disambiguate between the already existing map region. This will also be followed up with subsequent …
=>  kernel/vm_manager: Handle stack/TLS IO region placement a little better 

src/core/core.cpp, src/core/hle/service/filesystem/filesystem.cpp, src/core/hle/service/filesystem/filesystem.h, src/core/hle/service/filesystem/fsp_srv.cpp, src/core/hle/service/filesystem/fsp_srv.h, src/core/hle/service/service.cpp, src/core/hle/service/service.h, src/core/reporter.cpp, src/core/reporter.h
This:
- `SetGlobalAccessLogMode` -- takes the provided log mode and assigns a member variable to it
- `GetGlobalAccessLogMode` -- returns the same member variable as above, instead of using `LogMode::Log` as default, we now use `LogMode::LogToSdCard` as default
- `OutputAccessLogToSdCard` -- takes a string and sends it to our reporting services to format into a report, also logs to console
- `GetAccessLogVersionInfo` -- returns a format version and program index, used on new (7.0.0+) games to determine if they are running in a development environment. The constants used here are fine.
Closes #2617 (Thats not the real name of the func)
=> fsp-srv: Implement Access Logging Functionality

src/core/CMakeLists.txt, src/core/core.cpp, src/core/core.h, src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h, src/core/hle/service/am/applet_ae.cpp, src/core/hle/service/am/applet_oe.cpp, src/core/hle/service/apm/apm.cpp, src/core/hle/service/apm/apm.h, src/core/hle/service/apm/controller.cpp, src/core/hle/service/apm/controller.h, src/core/hle/service/apm/interface.cpp, src/core/hle/service/apm/interface.h, src/core/hle/service/service.cpp
This implements the getter and setter methods for cpu boost mode in `apm` and `am` services, along with the getters and setters for PerformanceConfig, which is a more granular way of changing speed (and the backend of boost mode).
This also adds the `apm:am` service, which is a rename of `apm` for 8.0.0+, otherwise identical.
For now, this adds the framework to handle setting/getting config and mode and has a function which is called to change CPU speed and for now this simply logs to console.
From my testing, changing emulated clock speed in yuzu will not yield any difference to the user, sometimes even making performance worse.
Closes #2616
=> apm: Initial implementation of performance config and boost mode

src/core/hle/service/pm/pm.cpp, src/core/hle/service/pm/pm.h, src/core/hle/service/service.cpp
This implements various commands in `pm:shell`, `pm:dmnt`, and `pm:info` which map between process and title IDs.
- `pm:info GetTitleId(u64 process_id) -> u64 title_id` 
This takes a process ID and returns the title ID it possesses, if the process ID doesn't correspond to a valid process returns an error code.
- `pm:dmnt GetTitlePid(u64 title_id) -> u64 process_id`
The inverse of the preceding command, this takes a title ID and returns the process ID if there exists a process with that title ID, otherwise error.
- `pm:dmnt GetApplicationPid() -> u64 process_id` & `pm:shell GetApplicationPid() -> u64 process_id`
These both return the process ID of the current application, and if no application is running they return 0, which is an invalid process ID.
=> pm: Implement various pm commands for finding process and title IDs

src/core/hle/service/friend/friend.cpp
We don't have any friends implemented in Yuzu yet so it doesn't make sense to return any friends. For now we'll be returning 0 friends however the information provided will allow a proper implementation of this cmd when needed.
=> IFriendService::GetFriendList

src/video_core/renderer_opengl/gl_rasterizer.h
`must_reconfigure` isn't a parameter for this function any more, so it can be replaced with `current_state`.
While we're at it, we can make the parameters of the declaration match the same name as the ones in the definition.
Resolves a -Wdocumentation warning.
=> gl_rasterizer: Amend documentation comment for ConfigureFramebuffers()

src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h
These are a trivial getter/setter pair within ISelfController. On actual hardware, this would be slightly more involved, however, given we're emulating the console, we don't need to deal with much of the underlying behavior, as it wouldn't apply in an emulated context.
=> service/am: Implement SetAutoSleepDisabled/IsAutoSleepDisabled

src/core/arm/arm_interface.h, src/core/arm/dynarmic/arm_dynarmic.cpp, src/core/arm/dynarmic/arm_dynarmic.h, src/core/arm/unicorn/arm_unicorn.cpp, src/core/arm/unicorn/arm_unicorn.h, src/core/core_cpu.cpp, src/core/hle/kernel/vm_manager.cpp, src/core/settings.cpp, src/core/settings.h, src/core/telemetry_session.cpp, src/yuzu/configuration/config.cpp, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h, src/yuzu_tester/config.cpp, src/yuzu_tester/default_ini.h
This was initially necessary when AArch64 JIT emulation was in its infancy and all memory-related instructions weren't implemented. Given the JIT now has all of these facilities implemented, we can remove these functions from the CPU interface.
Supersedes #2722
=> core/arm: Remove obsolete Unicorn memory mapping

src/core/hle/kernel/svc.cpp, src/core/hle/service/ldr/ldr.cpp
Prior to PR, Yuzu did not restore memory to RW- on unmap of mirrored memory or unloading of NRO.
(In fact, in the NRO case, the memory was unmapped instead of reprotected to --- on Load, so it was actually lost entirely...)
This PR addresses that, and restores memory to RW- as it should.
This fixes a crash in Super Smash Bros when creating a World of Light save for the first time, and possibly other games/circumstances.
=> Restore memory perms on svcUnmapMemory/UnloadNro

CMakeModules/GenerateSCMRev.cmake, src/common/CMakeLists.txt, src/video_core/CMakeLists.txt, src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_gen.h, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/control_flow.cpp, src/video_core/shader/control_flow.h, src/video_core/shader/decode.cpp, src/video_core/shader/decode/other.cpp, src/video_core/shader/node.h, src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h
This PR does an overhaul to our old shader scanner by introducing a new one that it's more accurate, safer and predictable. It also decompiles SYNC/BRK into direct branches when possible. Furthermore, it introduces shader instructions BRX and BRA.CC and decompiles into brute force when they exist as they are indirect branches.
This PR should:
* Improve performance in low-end GPUs
* Produce more readibale code.
* Avoid reading out-of-bounds shaders (aka corrupted shaders).
=> Implement a New Shader Scanner, Decompile Flow Stack and implement BRX BRA.CC

src/core/file_sys/program_metadata.cpp, src/core/file_sys/program_metadata.h, src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/svc_wrap.h, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h, src/video_core/gpu.cpp, src/video_core/memory_manager.cpp, src/video_core/memory_manager.h
This implements svcMapPhysicalMemory/svcUnmapPhysicalMemory for Yuzu, which can be used to map memory at a desired address by games since 3.0.0.
It also properly parses SystemResourceSize from NPDM, and makes information available via svcGetInfo.
This is needed for games like Super Smash Bros. and Diablo 3 -- this PR's implementation does not run into the "ASCII reads" issue mentioned in the comments of #2626, which was caused by the following bugs in Yuzu's memory management that this PR also addresses:
* Yuzu's memory coalescing does not properly merge blocks. This results in a polluted address space/svcQueryMemory results that would be impossible to replicate on hardware, which can lead to game code making the wrong assumptions about memory layout.
* This implements better merging for …
=> Implement MapPhysicalMemory/UnmapPhysicalMemory

src/video_core/macro_interpreter.cpp, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_texture_cache.cpp, src/video_core/texture_cache/surface_base.cpp, src/video_core/texture_cache/surface_base.h, src/video_core/texture_cache/surface_params.cpp, src/video_core/texture_cache/texture_cache.h
This fixes linear textures not being passed to the RebuildSurface case.
Also, I'm adding a few microprofile timers to better benchmark the GPU
=> GPU: Fixes to Texture Cache and Include Microprofiles for GL State/BufferCopy/Macro Interpreter

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.h, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h
This commit implements gl_ViewportIndex and gl_Layer in vertex and geometry shaders. In the case it's used in a vertex shader, it requires ARB_shader_viewport_layer_array. This extension is available on AMD and Nvidia devices (mesa and proprietary drivers), but not available on Intel on any platform. At the moment of writing this description I don't know if this is a hardware limitation or a driver limitation.
In the case that ARB_shader_viewport_layer_array is not available, writes to these registers on a vertex shader are ignored, with the appropriate logging.
=> gl_shader_decompiler: Implement gl_ViewportIndex and gl_Layer in vertex shaders

src/video_core/shader/decode/image.cpp, src/video_core/shader/decode/memory.cpp, src/video_core/shader/decode/texture.cpp, src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h, src/video_core/shader/track.cpp
nouveau uses LDC instead of MOV Rd, c[n][m] to load global memory pointers into a shader. This commit allows the tracking heuristic to find these.
Tracking would previously fail due to LDC being decoded to an operation on the constant buffer address (it's an indirect read). To fix this issue this commit searches inside the operation for the base address.
=> shader/track: Track indirect buffers

src/video_core/shader/decode/other.cpp
This appears to have been a copy/paste error introduced within 8a6fc529a968e007f01464abadd32f9b5eb0a26c
=> shader/decode/other: Correct branch indirect argument within BRA handling

src/core/hle/kernel/svc.cpp
This messages were originally set as warnning since few games used these
svcs and it was needed for debugging. This is no longer the case.
=> Kernel: Downgrade WaitForAddress and SignalToAddress messages to Trace.

src/video_core/shader/decode.cpp, src/video_core/shader/decode/memory.cpp, src/video_core/shader/decode/texture.cpp, src/video_core/shader/decode/xmad.cpp, src/video_core/shader/node_helper.cpp, src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h, src/video_core/shader/track.cpp
Performs a few minor cleanup changes, like removing unused headers, clarity renaming, and getting rid of unnecessary atomic reference count increment and decrements.
=> shader-ir: Minor cleanup-related changes

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode/half_set_predicate.cpp, src/video_core/shader/node.h
Implement `HSETP2_C` and `HSETP2_IMM`. This also addresses a bug in `HSETP2_R` where it was using in Rb the absolute value from Ra.
=> shader/half_set_predicate: Implement missing HSETP2 variants

src/video_core/dma_pusher.cpp, src/video_core/engines/kepler_compute.cpp, src/video_core/engines/kepler_memory.cpp, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/engines/maxwell_dma.cpp, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_state.h, src/video_core/renderer_opengl/gl_texture_cache.cpp, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/texture_cache/texture_cache.h
This PR aims at 3 different things: Redo the dirty system to be standard and easier to setup, optimize CBData uploads and correct clearing Mechanisms.
Reworking the dirty system: the old dirty system was heterogenous and not easy to expand as it heavily relied on a lot of comparisons and check. This rework wastes a little more memory per dirty flag but it's homogenous (everything is a single bool), relies in less comparisons (worse case is only 3 compared to the 20 of before) and can easily be expandable (only serialized dirty flags require comparisons). This is designed for the Vulkan backend, in order to reduce pipeline construction time.
CBData Optimizations: Before we pushed cbdata word by word and called invalidate and dirty flags on every little push. For most games that only send a …
=> Rework Dirty Flags in GPU Pipeline, Optimize CBData and Redo Clearing mechanism

src/video_core/engines/kepler_compute.cpp, src/video_core/gpu.cpp, src/video_core/gpu.h, src/video_core/rasterizer_interface.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_cache.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.h, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp, src/video_core/renderer_opengl/gl_shader_disk_cache.h, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_gen.h, src/video_core/renderer_opengl/gl_shader_util.cpp
Implements compute shaders using OpenGL and [GL_ARB_compute_variable_group_size](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_compute_variable_group_size.txt) which is supported on Nvidia and AMD devices (both proprietary and free drivers). Implementing compute without this extension would require a shader cache invalidation, which can be done later on. For now devices without the extension (Intel) will skip kernel invocations.
There's still work to be done for compute shaders to be working on Nintendo games. That being said, I've seen reports of games like Brawlout properly emulating kernels.
A list of missing features potentially required to get kernels working on Nintendo games **not** implemented by this PR:
* Buffer "views" (buffers being used with a different base, …
=> gl_rasterizer: Implement compute shaders

.ci/templates/build-single.yml, .ci/templates/build-standard.yml, .ci/templates/build-testing.yml, .ci/yuzu-mainline.yml, .ci/yuzu-verify.yml
- Removes caching from PR builds -- in its current form caches count as a build secret, which aren't accessible to forks
- Updates the version of pip used on the merge build agent -- the pip was too old and was having random errors.
=> ci: Fix Azure PR Builds

src/yuzu_tester/yuzu.cpp
Gets rid of a compilation warning.
=> yuzu-tester/yuzu: Remove unused variable

CMakeModules/GenerateSCMRev.cmake, src/common/CMakeLists.txt, src/video_core/CMakeLists.txt, src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode.cpp, src/video_core/shader/decode/warp.cpp, src/video_core/shader/node.h, src/video_core/shader/shader_ir.h
Implement VOTE using Nvidia's intrinsics. Documentation about these can be found [here](https://developer.nvidia.com/reading-between-threads-shader-intrinsics). Instead of using portable ARB instructions I opted to use Nvidia intrinsics because these are the closest we have to how Tegra X1 hardware renders.
To stub VOTE on non-Nvidia drivers (including nouveau) this commit simulates a GPU with a warp size of one, returning what is meaningful for the instruction being emulated:
* `anyThreadNV(value)` -> `value`
* `allThreadsNV(value)` -> `value`
* `allThreadsEqualNV(value)` -> `true`  
`ballotARB`, also known as `uint64_t(activeThreadsNV())`, emits
```asm
VOTE.ANY Rd, PT, PT;
```
on nouveau's compiler. This doesn't match exactly to Nvidia's code
```asm
VOTE.ALL Rd, PT, PT;
```
which is …
=> shader_ir: Implement VOTE on Nvidia drivers

src/video_core/renderer_opengl/gl_buffer_cache.cpp
RasterizerInterface was considered an incomplete object by clang.
=> gl_buffer_cache: Add missing include

src/yuzu/configuration/config.cpp
I missed this in my original PR (https://github.com/yuzu-emu/yuzu/pull/1886).
=> configuration/config: Add missing screenshot path read

src/yuzu/main.cpp, src/yuzu/main.h
See citra-emu/citra#4914 for more details.
Fixes citra-emu/citra#4870 , uses the provided SetThreadExecutionState function to keep display and system awake while a game is being played.
=> Port citra-emu/citra#4914: "Fix to Windows sleep issues"

src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h
This is based on Ryujinx' implementation and it can be found here: https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Graphics/Graphics3d/NvGpuFifo.cs
`macros.entry` (just like the data uploading register) increments on every bind. We weren't emulating this properly.
Thanks to @fincs for pointing out this bug.
=> maxwell_3d: Fix macro binding cursor

src/video_core/engines/shader_bytecode.h, src/video_core/shader/decode/float_set_predicate.cpp
This bit was not listed in envytools. Negate `op_b` when it's required.
=> float_set_predicate: Add missing negation bit for the second operand

.ci/templates/build-testing.yml
Identified a bug in the script which uses the azure image when attempting to upgrade python3-pip.
Package index was out of date because apt-get update was not ran before attempting the upgrade.
=> CI Fix (Azure/Testing) - apt update before upgrade. Use apt-get.

src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp
GLSL decompiler type system was broken. We converted all return values to float except for some cases where returning we couldn't and implicitly broke the rule of returning floats (e.g. for bools or bool pairs).
Instead of doing this introduce class Expression that knows what type a return value has and when a consumer wants to use the string it asks for it with a required type, emitting a runtime error if types are incompatible.
This has the disadvantage that there's more C++ code, but we can emit better GLSL code that's easier to read.
=> gl_shader_decompiler: Rework GLSL decompiler type system

src/core/hle/service/fatal/fatal.cpp, src/core/reporter.cpp
This is required for yuzu to build on Linux. 
Credit to @Cleverking2003
Fixes #2798
=> externals: update fmt to 6.0.0

src/yuzu/configuration/configure_input_player.cpp
See citra-emu/citra#4911 for more details.
When a user clicks the "Set Analog Stick" button, Citra will pop up an information window with instructions for setting it up.
The message reads "After pressing OK, first move your joystick horizontally, and then vertically."
There's a small incongruence between what the message says and the actual behavior, as Citra will try to accept an input even if the user closes the information window by pressing 'Esc' or by clicking the 'x' (not sure how to properly call it).
This PR proposes the addition of a 'Cancel' button and a check for the button clicked by the user.
According to the Qt documentation, this will also assign 'Cancel' as the Escape Button, triggering it when the user presses 'Esc'.
=> Port citra-emu/citra#4911: "Add cancel option to analog stick configuration"

src/yuzu/configuration/configure_general.cpp, src/yuzu/configuration/configure_general.ui, src/yuzu/configuration/configure_graphics.cpp, src/yuzu/configuration/configure_graphics.ui
See citra-emu/citra#4864 for more details.
The speed limiter being a frame limiter is an implmentation detail and can be changed in the future. What user care about is that it limit the emulation speed in genenral (not just graphics but also audio+input).
=> Port citra-emu/citra#4864: "yuzu/configure: move speed limiter to general"

src/yuzu/configuration/configure_dialog.cpp
See citra-emu/citra#4866 for more details.
=> Port citra-emu/citra#4866: "configure_dialog: reverse tab map to avoid logic based on user-facing/translatable text"

src/yuzu/main.cpp
See citra-emu/citra#4877 for more details.
Yes, we don't currently have an OSX build but the plan was to add it back when there's Vulkan support and compatibility layers support all the features we need. 
As we don't have any negative effects from it, it makes sense porting all MacOS features or workaround from Citra.
=> Port citra-emu/citra#4877: "citra_qt: on osx chdir to bundle dir to allow detection of user folder"

src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_cache.h
Now that ProgramVariants holds the primitive topology we no longer need to keep track of individual geometry shaders topologies.
=> gl_shader_cache: Remove special casing for geometry shaders

src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h
Performs some minor cleanup related to the memory manager. Mostly just performs simplifications and very small performance improvements in the slow path of `MergeAdjacentVMA`. One commit fixes a trivial bug within a failure case for `UnmapPhysicalMemory` as well. This case shouldn't be hit within normal (stable) software emulation, so that's likely why it has gone unnoticed until now.
=> kernel/vm_manager: Minor cleanup

src/core/core.cpp, src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h, src/core/hle/service/am/applet_ae.cpp, src/core/hle/service/am/applet_oe.cpp, src/core/hle/service/am/applets/applets.cpp, src/core/hle/service/am/applets/applets.h, src/core/hle/service/am/applets/error.cpp, src/core/hle/service/am/applets/error.h, src/core/hle/service/am/applets/general_backend.cpp, src/core/hle/service/am/applets/general_backend.h, src/core/hle/service/am/applets/profile_select.cpp, src/core/hle/service/am/applets/profile_select.h, src/core/hle/service/am/applets/software_keyboard.cpp, src/core/hle/service/am/applets/software_keyboard.h, src/core/hle/service/am/applets/web_browser.cpp, src/core/hle/service/am/applets/web_browser.h
Avoids the use of global accessors, removing the reliance on global state. This also makes dependencies explicit in the interface, as opposed to being hidden.
With this we're much closer to removing the `Core::CurrentProcess` global accessor.
=> service/am: Remove usages of global system accessors

src/core/loader/nro.cpp, src/core/loader/nro.h
With this, the "Developer" field in the Properties window for homebrew (all `.nro`s) is now populated.
<details>
<summary>Example Screenshots</summary>
</details>
=> nro/ui: Show "Developer" field in Properties

src/video_core/engines/kepler_compute.cpp, src/video_core/engines/kepler_compute.h, src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_state.h, src/video_core/renderer_opengl/gl_texture_cache.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/shader/decode/image.cpp, src/video_core/shader/node.h, src/video_core/shader/shader_ir.h, src/video_core/texture_cache/surface_base.h, src/video_core/texture_cache/surface_params.cpp, src/video_core/texture_cache/surface_params.h, src/video_core/texture_cache/surface_view.cpp, src/video_core/texture_cache/surface_view.h, src/video_core/texture_cache/texture_cache.h
Implements sampler and image bindings to compute invocations. Images are used in instructions like `SUST`, `SULD` and `SUATOM`. There is some code repetition between `maxwell_3d` and `kepler_compute` that I'd like to address afterwards.
While adding an extra entry to OpenGLState, this splits texture and samplers binding to pass them to OpenGL as they are instead of generating a temporary buffer in the stack and abstracts the algorithm into a separate function.
=> gl_rasterizer: Bind images and samplers to compute

src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/macro_interpreter.cpp, src/video_core/macro_interpreter.h
Instead of calling `std::move` on `macro_params` to the callee in `Maxwell3D::CallMethod`, pass a memory reference of it. This avoids constantly having `macro_params` without allocations, making its `std::vector<>::push_back` visible in the profiler (~5% from my testing).
Internally this memory reference is consumed with a `std::vector<u32>`-like `std::unique_ptr<u32[]>` but unlike `std::vector<>::resize` it won't zero newly allocated memory.
This turns constant allocation into a `std::memcpy`.
Thanks to @graphitemaster for pointing this out and suggesting a solution.
=> maxwell_3d: Avoid moving macro_params

src/video_core/engines/shader_bytecode.h, src/video_core/shader/decode/shift.cpp
Nvidia defaults to wrapped shifts, but this is undefined behaviour in GLSL. Explicitly mask/clamp according to what the guest shader requires.
=> shader/shift: Implement SHR wrapped and clamped variants

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode/image.cpp, src/video_core/shader/node.h, src/video_core/shader/shader_ir.h
`SUATOM` is the instruction used for atomic image operations. This implements it and fixes some issues related to image operations in general.
=> shader/image: Implement SUATOM and fix SUST

src/core/hle/service/acc/acc.cpp, src/core/hle/service/acc/acc.h, src/core/hle/service/acc/acc_su.cpp, src/core/hle/service/acc/profile_manager.cpp, src/core/hle/service/acc/profile_manager.h
This is used by homebrew/libnx and allows easy editing of user name, timestamp, data and image.
=> acc: Implement IProfileEditor interface and 'Store'/'StoreWithImage' commands

src/video_core/renderer_vulkan/vk_device.cpp, src/video_core/renderer_vulkan/vk_device.h, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
* Increase minimum Vulkan requirements
* Require `VK_EXT_vertex_attribute_divisor`
* Require `depthClamp`, `samplerAnisotropy` and `largePoints` features
* Search and expose `VK_KHR_uniform_buffer_standard_layout`
* Search and expose `VK_EXT_index_type_uint8`
* Search and expose native float16 arithmetics
* Track current driver with `VK_KHR_driver_properties`
* Query and expose SSBO alignment
* Query more image formats
* Improve logging overall
* Minor style changes
* Minor rephrasing of commentaries
This also updates Vulkan headers.
=> vk_device: Add miscellaneous features and minor style changes

src/video_core/surface.cpp, src/video_core/surface.h
This is required for proper conversion to RGBA8_UNORM or RGBA8_SRGB surfaces when a backend can target both native and converted ASTC.
=> video_core/surface: Add function to detect sRGB surfaces

src/video_core/engines/maxwell_3d.cpp, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_state.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h
Aims to fix #2101. Removes the sRGB hack of tracking if a frame used an sRGB rendertarget to apply at least once to blit the final texture as sRGB. Instead of doing this apply sRGB if the presented image has sRGB.
Also enable sRGB by default on Maxwell3D registers as some games seem to assume this.
Thanks to @FernandoS27 for fixing a regression introduced by this commit.
=> renderer_opengl: Fix sRGB blits

src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/shader/decode/memory.cpp, src/video_core/shader/node.h, src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h
Implement shared memory using SSBOs. Instead of using host shared memory for this, I opted for SSBOs because it let's us alias memory in GLSL to choose between signed and unsigned overloads sets (required for ATOMS).
As a side effect of this approach, we can avoid issues of different hardware having different shared memory size limitations. SSBOs have a much higher size limit compared to shared memory.
=> shader_ir: Implement shared memory

src/video_core/engines/maxwell_3d.cpp
There's no reason to clog logs with DrawArray.
=> Mark DrawArrays as LOG_TRACE

src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
These functions are not stubbed and are called fairly often. Due to the nature of how often they're called, we should keep them marked as LOG_TRACE instead of LOG_DEBUG or LOG_WARNING
=> Mark KickOffPb & SubmitGPFIFO as trace

src/video_core/renderer_opengl/maxwell_to_gl.h
OpenGL texture filters follow `GL_<texture_filter>_MIPMAP_<mipmap_filter>` but we were using them in the opposite way.
=> maxwell_to_gl: Fix mipmap filtering

src/yuzu/configuration/configure_input.cpp
Previously, "Joycons Docked" and "Use Docked Mode" can both be checked. Even though the "Joycons Docked" checkbox is grayed out when "Use Docked Mode is checked, the value of this checkbox is still read and as a result causes unintended behaviors. This PR corrects this by unchecking "Joycons Docked"  when "Use Docked Mode" is checked.
=> configure_input: Uncheck "Joycons Docked" when "Use Docked Mode" is checked

src/core/memory.cpp
This commit avoids Invalidating and Flushing the GPU if the page is notmarked as a RasterizerCache Page.
=> Core/Memory: Only FlushAndInvalidate GPU if the page is marked as RasterizerCachedMemory

src/core/core.cpp, src/core/perf_stats.cpp, src/core/perf_stats.h, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h
See citra-emu/citra#4882 (and https://github.com/citra-emu/citra/pull/4891) for more details.
cc @chris062689
=> Port citra-emu/citra#4882: "Add frametime logging for tracking performance over time"

src/video_core/engines/shader_bytecode.h, src/video_core/shader/decode/arithmetic_integer.cpp
This PR implements ICMP instruction.
=> Shader_IR: Implement ICMP.Instruction

src/yuzu/main.cpp
Spit out a LOG_INFO of the current game name and it's title id in the log. This helps to read log files and figure out which games have which issues.
Log is as follows
`Frontend <Info> yuzu\main.cpp:BootGame:979: Booting game: 010003F003A34000 | Pokémon: Let's Go, Pikachu!`
The only other way we can get a TID in the current log is through the exefs patch notification or if the user is running debug logs, then the program metadata. By marking it as LOG_INFO, we should get this crucial info in all logs
=> Log the current title id and game name which is booting

src/core/hle/service/prepo/prepo.cpp, src/core/hle/service/prepo/prepo.h, src/core/hle/service/service.cpp, src/core/reporter.cpp, src/core/reporter.h
We only had one variant of prepo's reporting functions implemented prior to this, SaveReportWithUserOld, simply because that was the only one we had seen called by games at the time of #2482.
This adds all of the versions of SaveReport*:
- `SaveReportOld` and `SaveReportWithUserOld` -- These were used prior to 6.0.0
- `SaveReport` and `SaveReportWithUser` -- Added in 6.0.0, have the same parameters.
- `SaveSystemReport` and `SaveSystemReportWithUser` -- Unlike the above two, which operate based on process_ids, these use title_ids.
The `WithUser` variants add an additional `u128` parameter at the front of the signature.
Since the framework to store/export this data was added with #2482, this was quite easy. The reports now include an additional JSON field for Old, New or System.
=> prepo: Implement New, System, and Non-User variants of SaveReport

src/video_core/renderer_opengl/gl_framebuffer_cache.cpp, src/video_core/renderer_opengl/gl_framebuffer_cache.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h
`ConfigureFramebuffers` no longer handles clears. Remove unused code from it.
=> gl_rasterizer: Remove unused code paths from ConfigureFramebuffers

src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/macro_interpreter.cpp, src/video_core/rasterizer_interface.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h
This PR aims to accumulate draw calls sent through MME(Macro Interpreter) and flush then once either a sync is required or the program has ended. This heavily increases performance in certain games like SMO, PLGE which use instance drawing heavily. In the pokemon mansion in PLGE performance went from 12fps all the way to 50fps. Some kingdoms in SMO got a significant 5fps boost(changes depending on your computer).
Special thanks to fincs, since he discovered how MME's worked to do instance drawing and suggested this method.
=> Implement a MME Draw commands Inliner and correct host instance drawing

src/audio_core/audio_renderer.cpp, src/audio_core/audio_renderer.h
Added framecount. Need a game to actually read it to confirm that this is the frame count
=> Added frame_count for REV5 audio renderer

src/core/hle/service/hid/controllers/npad.cpp, src/core/hle/service/hid/controllers/npad.h, src/core/hle/service/hid/hid.cpp
We shouldn't return the same event for all npads, this will lead to softlocks/input not working on some games. By setting a separate event for each controller, this should fix a few issues related to style updates.
=> AcquireNpadStyleSetUpdateEventHandle should have a separate event for each controller type

src/core/core.cpp, src/core/core.h, src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h, src/core/hle/service/am/applet_ae.h, src/core/hle/service/am/applet_oe.h, src/yuzu/main.cpp, src/yuzu/main.h
This adds the ExitLock pair of commands, which on HW make the user wait/confirm they want to exit. Apps can use this to allow extra time (up to 15s) for cleanup tasks. In yuzu, this presents as an additional confirmation dialog.
This also adds the `Exit` Command, closing #2664 . This simply closes the current application.
=> am: Implement exit locking and self exit commands
