- CMakeLists.txt
This just renames the old Citra things to yuzu.
> CMakeList.txt: rename CITRA to YUZU 

- src/yuzu/configuration/config.cpp
- src/yuzu/main.cpp
- src/yuzu/main.h
- src/yuzu/main.ui
- src/yuzu/ui_settings.h
Source: https://github.com/citra-emu/citra/pull/3001
> Merge citra-emu PR#3001 by Styleoshin(citra-qt : Adding fullscreen mode)

- .travis/macos/deps.sh
- src/core/arm/arm_interface.h
- src/core/hle/ipc.h
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/memory.cpp
- src/core/hle/kernel/mutex.h
- src/core/hle/kernel/svc.cpp
- src/core/hle/kernel/vm_manager.cpp
- src/core/hle/service/apm/apm.cpp
- src/core/hle/service/nvdrv/nvdrv.h
- src/core/loader/linker.cpp
- src/core/loader/nso.cpp
- src/core/loader/nso.h
- src/video_core/renderer_opengl/renderer_opengl.h
- src/yuzu/about_dialog.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_dialog.cpp
- src/yuzu/configuration/configure_input.cpp
- src/yuzu/configuration/configure_system.cpp
- src/yuzu/debugger/registers.cpp
- src/yuzu/game_list_p.h
- src/yuzu/main.cpp
- src/yuzu/util/spinbox.cpp
- src/yuzu_cmd/yuzu.cpp
(Hopefully) fixes:
* macOS travis build
* clang-format
> Misc build fixes

- src/core/loader/nso.cpp
This allows homebrew built with libnx (at least ones I've built) to get to the point where they start issuing IPC calls.
> nso: Modify .bss size calculation logic

- .travis.yml
https://github.com/citra-emu/citra/pull/3034 for reference.
> Implement Pull #3034 from Citra: Change build order to check clang-format first

- src/yuzu/configuration/configure_debug.ui
https://github.com/citra-emu/citra/pull/3030 for reference
> Implement Pull #3030 from Citra: Rename derivative class name

- src/core/CMakeLists.txt
- src/core/hle/ipc_helpers.h
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/kernel/svc.cpp
- src/core/hle/kernel/svc.h
- src/core/hle/service/am/applet_oe.cpp
- src/core/hle/service/apm/apm.cpp
- src/core/hle/service/apm/apm.h
- src/core/hle/service/nvdrv/devices/nvdevice.h
- src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
- src/core/hle/service/nvdrv/devices/nvdisp_disp0.h
- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
- src/core/hle/service/nvdrv/devices/nvmap.cpp
- src/core/hle/service/nvdrv/devices/nvmap.h
- src/core/hle/service/nvdrv/interface.cpp
- src/core/hle/service/nvdrv/interface.h
- src/core/hle/service/nvdrv/nvdrv.cpp
- src/core/hle/service/nvdrv/nvdrv.h
- src/core/hle/service/nvdrv/nvdrv_a.cpp
- src/core/hle/service/nvdrv/nvdrv_a.h
- src/core/hle/service/service.cpp
- src/core/hle/service/vi/vi.cpp
- src/core/hle/service/vi/vi.h
Most/all of these changes are from @Subv. Just cleaning up to get these merged.
> Improvements to IPC, AppletOE, APM, VI, SVC

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/hle/ipc.h
- src/core/hle/kernel/domain.cpp
- src/core/hle/kernel/hle_ipc.cpp
Fixes several games that currently assert due to not being able to parse this command.
> Implement IPC domain command CloseVirtualHandle

- src/core/loader/nro.cpp
This makes NRO file actually run.
However, most of the homebrew I tried on the NRO format crash due to unimplemented services.
> Fix NRO loading

- src/yuzu/bootmanager.cpp
- src/yuzu/bootmanager.h
Moved over from #3266 in citra.
Addresses one of the checkboxes in #40
> bootmanager: Minor tidiness/correctness changes

- src/common/telemetry.h
Resolves checkbox #3262 in #40
> telemetry: Silence initialization order warnings

- src/yuzu/bootmanager.cpp
- src/yuzu/debugger/profiler.cpp
- src/yuzu/game_list.cpp
- src/yuzu/main.cpp
- src/yuzu/util/spinbox.cpp
> qt: Migrate to Qt 5 signal/slot connection syntax where applicable

- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/core_timing.cpp
- src/core/gdbstub/gdbstub.cpp
- src/core/hle/kernel/condition_variable.cpp
- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/service/vi/vi.cpp
This cleans up some build warnings in visual studio
Partially fixes the issue referenced in: https://github.com/yuzu-emu/yuzu/issues/40
> Fixes some cast warnings, partial port of citra #3064

- src/common/CMakeLists.txt
Minor spelling error of its --> it's
> Fix minor spelling error in CMakeLists

- src/core/gdbstub/gdbstub.cpp
This gets gdbstub working at least to the point where clients can
communicate with it.
What works:
- Reading/writing GPRegs
- Reading/writing memory
- Interrupting the emulated program and continuing
What does NOT work:
- Breakpoints. Sizes have been updated to u64, but support will need to be
added in the interpreter for them to work.
- VRegs. Mostly because my gdb was having issues with 128-bit regs for
some reason. However, the current u128 representation is a bit
awkward to use and should probably be updated first.
> gdbstub: Update registers and sizes for aarch64

- src/core/CMakeLists.txt
- src/core/hle/service/nifm/nifm.cpp
- src/core/hle/service/nifm/nifm.h
- src/core/hle/service/nifm/nifm_a.cpp
- src/core/hle/service/nifm/nifm_a.h
- src/core/hle/service/nifm/nifm_s.cpp
- src/core/hle/service/nifm/nifm_s.h
- src/core/hle/service/nifm/nifm_u.cpp
- src/core/hle/service/nifm/nifm_u.h
- src/core/hle/service/service.cpp
Probably this services not critical for games, but it exist on Switch anyway
> Service/nifm: add nifm:a, nifm:s and nifm:u services

- src/core/hle/service/acc/acc_u0.cpp
fix https://github.com/yuzu-emu/yuzu/issues/158
> acc:u0 : stub GetAccountId

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/hle/service/acc/acc_u0.cpp
- src/core/hle/service/acc/acc_u0.h
- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/applet_ae.cpp
- src/core/hle/service/am/applet_oe.cpp
- src/core/hle/service/apm/apm.cpp
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/lm/lm.cpp
- src/core/hle/service/nifm/nifm.cpp
- src/core/hle/service/nifm/nifm_a.cpp
- src/core/hle/service/nifm/nifm_s.cpp
- src/core/hle/service/nifm/nifm_u.cpp
- src/core/hle/service/nvdrv/devices/nvmap.cpp
- src/core/hle/service/nvdrv/interface.cpp
- src/core/hle/service/nvflinger/buffer_queue.cpp
- src/core/hle/service/pctl/pctl_a.cpp
- src/core/hle/service/set/set.cpp
- src/core/hle/service/time/time.cpp
- src/core/hle/service/vi/vi.cpp
- src/core/hle/service/vi/vi_m.cpp
- src/core/hle/service/vi/vi_s.cpp
- src/core/hle/service/vi/vi_u.cpp
Lots of cleanup and refactoring. Changes include using log subcategories for the services, several new stubs, and several minor fixes. See commit messages for exact details. Recommend reviewing commit by commit.
> Many service improvements

- src/core/CMakeLists.txt
- src/core/hle/service/nvdrv/devices/nvdevice.h
- src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
- src/core/hle/service/nvdrv/devices/nvdisp_disp0.h
- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
- src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
- src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
- src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_gpu.h
- src/core/hle/service/nvdrv/devices/nvmap.cpp
- src/core/hle/service/nvdrv/devices/nvmap.h
- src/core/hle/service/nvdrv/interface.cpp
- src/core/hle/service/nvdrv/interface.h
- src/core/hle/service/nvdrv/nvdrv.cpp
Few more things need to be implemented which I'm working on with @bunnei .The main implementation is /dev/nvhost-gpu, /dev/nvhost-ctrl-gpu, /dev/nvhost-as-gpu
> Extra nvdrv support

- src/core/hle/service/hid/hid.cpp
used in Disgaea 5, Rayman Legends
> Service/hid: stub SetNpadHandheldActivationMode

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/audio/audren_u.h
- src/core/hle/service/filesystem/fsp_srv.cpp
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/time/time.cpp
- src/core/hle/service/vi/vi.cpp
- src/core/hle/service/vi/vi.h
Now most games lead to crash with #167 or after DuplicateSession
> Service: stub some functions in am, audio, time, vi services

- .travis/macos/build.sh
- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/arm/dynarmic/arm_dynarmic.h
Changes ([a6d17e...41ae122](https://github.com/MerryMage/dynarmic/compare/a6d17e6bb0ffd16464b7dae8c1124b0c6a742a15...41ae12263da7c6d1ffafec6a5b9095977b42367d)):
* Primarily implementing more A64 instructions.
> dynarmic: Update to 41ae12263

- src/core/hle/service/acc/acc_u0.cpp
- src/core/hle/service/acc/acc_u0.h
- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
- src/core/hle/service/nvdrv/interface.cpp
- src/core/hle/service/nvdrv/interface.h
- src/core/hle/service/vi/vi.cpp
Some fixes for libnx, which is still not running yet, but soon :)
Couple of other miscellaneous things in here, as well.
> Various fixes for libnx, etc.

- src/core/CMakeLists.txt
- src/core/hle/service/apm/apm.cpp
- src/core/hle/service/apm/interface.cpp
- src/core/hle/service/apm/interface.h
- src/core/hle/service/filesystem/fsp_srv.cpp
- src/core/hle/service/filesystem/fsp_srv.h
- src/core/hle/service/nvflinger/buffer_queue.cpp
- src/core/hle/service/vi/vi.cpp
> More fixes for Libnx

- src/core/CMakeLists.txt
- src/core/core.cpp
- src/core/core.h
- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
- src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_gpu.h
- src/core/hle/service/nvdrv/nvdrv.cpp
- src/video_core/CMakeLists.txt
- src/video_core/command_processor.cpp
- src/video_core/command_processor.h
- src/video_core/engines/fermi_2d.cpp
- src/video_core/engines/fermi_2d.h
- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
- src/video_core/engines/maxwell_compute.cpp
- src/video_core/engines/maxwell_compute.h
- src/video_core/gpu.h
- src/video_core/memory_manager.cpp
- src/video_core/memory_manager.h
The engines don't really do anything yet
> GPU: Added a command processor to decode the GPU pushbuffers and forward the commands to their respective engines

- src/core/hle/service/audio/audren_u.cpp
This stubs some audren methods used by some games.
> Stub RequestUpdateAudioRenderer, StartAudioRenderer and StopAudioRenderer

- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/memory.h
> arm_dynarmic: Support direct page table access

- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/audio/audren_u.h
Schedules a recurring event for audren_u. Fixes a endless wait loop in Puyo Puyo Tetris and BOTW.
> audren_u: Schedule reoccuring event.

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
- src/video_core/gpu.h
Only QueryMode::Write is supported at the moment.
> GPU: Partially implemented the QUERY_* registers in the Maxwell3D engine.

- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/hid/hid.cpp
Stub some function + add `Description()` method to `HLERequestContext`, which shows info about ipc parameters
> Service/hid: stub some functions

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/acc/acc_u0.cpp
- src/core/hle/service/acc/acc_u0.h
- src/core/hle/service/friend/friend.cpp
- src/core/hle/service/friend/friend.h
- src/core/hle/service/friend/friend_a.cpp
- src/core/hle/service/friend/friend_a.h
- src/core/hle/service/service.cpp
Stubs several functions for friend:a and acc:u0 services used by Puyo Puyo Tetris
> Stub several friend:a and acc:u0 service functions

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/hle/service/aoc/aoc_u.cpp
- src/core/hle/service/aoc/aoc_u.h
> Service/AOC: stub ListAddOnContent function

- src/core/core.cpp
When starting up a second guest application, yuzu would crash during the `scheduler = std::make_unique<Kernel::Scheduler>(cpu_core.get());` call, due to execution of `Kernel::Scheduler::~Scheduler`, which depends on `g_current_process`, which was set to `nullptr` by `Kernel::Shutdown`.
Here we add the line `scheduler = nullptr;` before `Kernel::Shutdown();` to fix this. We also reorder the other shutdown tasks to match initialization order.
> core: Fix scheduler-shutdown related crash

- src/core/hle/kernel/svc.cpp
- src/core/hle/kernel/svc_wrap.h
This is my fist time doing actual work on the Emulator without guidelines such as the pretty much now finished Meta-Issue 40. As such, I advise reviewers to be especially critical.
> UnmapSharedMemory

- src/core/hle/service/nvflinger/buffer_queue.cpp
> nvflinger: Remove superfluous buffer format check.

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
Future PRs will refactor the way we handle GPU register writes to support the method-call interface (ie, register 0xE24).
> GPU: Added some shader-related registers.

- src/video_core/engines/maxwell_3d.h
Follow up PRs will start making use of these.
> GPU: Added the vertex array registers.

- src/core/arm/arm_interface.h
- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/arm/dynarmic/arm_dynarmic.h
- src/core/arm/unicorn/arm_unicorn.cpp
- src/core/arm/unicorn/arm_unicorn.h
- src/core/core.cpp
- src/core/core.h
> Implement Pull #3184 from citra: core/arm: Improve timing accuracy before service calls in JIT (Rebased)

- src/video_core/engines/maxwell_3d.h
The TIC stores Texture information and the TSC stores Sampler information.
> GPU: Added TIC and TSC registers to the Maxwell3D register structure.

- src/core/arm/unicorn/arm_unicorn.cpp
- src/core/core.cpp
- src/core/gdbstub/gdbstub.cpp
- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/object_address_table.cpp
- src/core/hle/kernel/server_session.cpp
- src/core/hle/kernel/shared_memory.cpp
- src/core/hle/kernel/svc.cpp
- src/core/hle/service/filesystem/fsp_srv.cpp
- src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
- src/core/hle/service/service.cpp
- src/core/hle/service/time/time.cpp
- src/core/hle/service/vi/vi.cpp
- src/core/loader/linker.cpp
- src/video_core/engines/maxwell_3d.cpp
>  Implement Pull #3064 from citra: Clean all format warnings (Yuzu-specific format warnings cleared too)

- src/yuzu_cmd/yuzu.rc
Changes the name, nothing fancy
> CITRA_ICON -> YUZU_ICON

- src/core/CMakeLists.txt
- src/core/file_sys/directory.h
- src/core/file_sys/disk_filesystem.cpp
- src/core/file_sys/disk_filesystem.h
- src/core/file_sys/filesystem.h
- src/core/file_sys/romfs_filesystem.cpp
- src/core/file_sys/romfs_filesystem.h
- src/core/file_sys/sdmc_factory.cpp
- src/core/file_sys/sdmc_factory.h
- src/core/hle/service/filesystem/filesystem.cpp
- src/core/hle/service/filesystem/filesystem.h
- src/core/hle/service/filesystem/fsp_srv.cpp
This also implements the IDirectory interface.
The code was tested with libtransistor's test_fs_stress program, which now runs correctly.
Closes #247
Closes #219
> FS: Implemented access to the SD card

- src/core/core.h
- src/video_core/CMakeLists.txt
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/debug_utils/debug_utils.h
- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
- src/video_core/gpu.cpp
- src/video_core/gpu.h
- src/video_core/textures/decoders.cpp
- src/video_core/textures/decoders.h
- src/video_core/textures/texture.h
- src/yuzu/CMakeLists.txt
- src/yuzu/debugger/graphics/graphics_breakpoint_observer.cpp
- src/yuzu/debugger/graphics/graphics_breakpoint_observer.h
- src/yuzu/debugger/graphics/graphics_breakpoints.cpp
- src/yuzu/debugger/graphics/graphics_breakpoints.h
- src/yuzu/debugger/graphics/graphics_breakpoints_p.h
- src/yuzu/debugger/graphics/graphics_surface.cpp
- src/yuzu/debugger/graphics/graphics_surface.h
- src/yuzu/main.cpp
- src/yuzu/main.h
> GPU: Added code to unswizzle textures and ported the surface viewer from citra

- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/audio/audren_u.h
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/ns/pl_u.cpp
- src/core/hle/service/ns/pl_u.h
Just some local changes I've had for a while that should get merged, nothing particularly exciting.
> Minor changes to VI, PL, HID, and AUDREN

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/kernel/svc.cpp
- src/core/hle/kernel/svc_wrap.h
- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/nfp/nfp.cpp
- src/core/hle/service/nfp/nfp.h
- src/core/hle/service/nfp/nfp_user.cpp
- src/core/hle/service/nfp/nfp_user.h
- src/core/hle/service/service.cpp
Nothing terribly ground-breaking here - just some minor stuff that gets BOTW booting further.
> NFP, SVC, and AudRen progress

- src/core/hle/service/hid/hid.cpp
Games check that the structs for the touchscreen in HID shared memory are valid, even if they don't use the touch screen. This change updates them, although does not implement actual touch input. With this change and #296, Cave Story+ now runs.
> hid: Write empty touch screen state.

- externals/CMakeLists.txt
- src/common/swap.h
- src/core/hle/service/service.cpp
Applying the changes introduced in [https://github.com/citra-emu/citra/pull/3456](https://github.com/citra-emu/citra/pull/3456).
The commit messages will elaborate on the changes.
> Fix build on OpenBSD

- src/core/CMakeLists.txt
- src/core/hle/kernel/shared_memory.cpp
- src/core/hle/kernel/svc.cpp
- src/core/hle/kernel/svc_wrap.h
- src/core/hle/service/audio/audout_u.cpp
- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/friend/friend.cpp
- src/core/hle/service/friend/friend_u.cpp
- src/core/hle/service/friend/friend_u.h
- src/core/hle/service/nifm/nifm.cpp
- src/core/hle/service/vi/vi.cpp
- src/core/hle/service/vi/vi.h
Another mix bag of minor miscellaneous changes and stubs.
> Implement and stub several SVC/VI/Audio/Friend/etc. funcs

- src/core/core.cpp
- src/core/core.h
- src/core/loader/deconstructed_rom_directory.cpp
- src/core/loader/loader.h
- src/yuzu/main.cpp
Originally thought that someone could test it before i submit the PR, changed my mind though because leaving the issue open like that will cause people to duplicate efforts.
(If it works) Closes #302
> core, main.h: Abort on 32Bit ROMs

- src/yuzu/main.cpp
Direct port of #3611 from Citra.
Original PR link: https://github.com/citra-emu/citra/pull/3611
> Fix the stuck in fullscreen bug

- src/core/hle/kernel/vm_manager.cpp
Gets Binding of Isaac running.
> vm_manager: Increase GetTotalMemoryUsage value.

- src/core/file_sys/disk_filesystem.cpp
- src/core/file_sys/disk_filesystem.h
- src/core/file_sys/filesystem.h
- src/core/file_sys/romfs_filesystem.cpp
- src/core/file_sys/romfs_filesystem.h
- src/core/hle/service/filesystem/fsp_srv.cpp
> fsp_srv: Implement DeleteFile.

- src/core/hle/service/ns/pl_u.cpp
- Makes games work in lieu of shared_font.bin.
> pl_u: Use empty shared font if none is available.

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/maxwell_to_gl.h
This is formally PR'ing part of #339. Note, if you're already using that branch, no need to merge this one as well - there are no functional differences.
> Implement indexed mode rendering

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/gpu.h
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
- src/video_core/textures/texture.h
This is a continuation of getting the various changes in #339 merged into mainline yuzu. In this PR, we bring over some really minor miscellaneous changes that don't fit anywhere else. I've also addressed any related comments on #339.
**As was mentioned in other PRs, if you are already using changes to run games, I do not recommend trying to merge this branch. This does not add anything functionally new that isn't in #339.**
> Misc gpu improvements

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Just a few minor changes to reduce the overall amount of potential allocations that happen. Each commit should have its own accompanying description describing the changes in more detail.
> glsl_shader_decompiler: Minor API changes to ShaderWriter

- src/core/file_sys/disk_filesystem.cpp
- src/core/file_sys/disk_filesystem.h
These were changes that I made for citra, but didn't bring over here yet.
> disk_filesystem: Minor changes

- src/common/common_types.h
> common_types: Minor changes

- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Prevents implicit conversions and scope pollution.
> gl_rasterizer_cache: Make MatchFlags an enum class

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/renderer_opengl.cpp
Most of these are hangovers from citra
> opengl: Remove unnecessary header inclusions

- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.h
- src/yuzu_cmd/yuzu.cpp
Visit citra-emu/citra#3607 for details.
> SDL2: Implement fullscreen. (Original PR: citra-emu/citra#3607)

- src/core/file_sys/disk_filesystem.cpp
- src/core/file_sys/disk_filesystem.h
- src/core/file_sys/filesystem.h
- src/core/file_sys/romfs_filesystem.cpp
- src/core/file_sys/romfs_filesystem.h
- src/core/hle/service/filesystem/fsp_srv.cpp
This PR allow to run PyNX homebrew
> Service/FS: implement IFileSystem::RenameFile

- src/video_core/command_processor.cpp
- src/video_core/engines/maxwell_3d.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/video_core/video_core.cpp
Moves the logging macros over where applicable
> video-core: Move logging macros over to new fmt-capable ones

- src/core/file_sys/disk_filesystem.cpp
- src/core/file_sys/filesystem.cpp
- src/core/file_sys/partition_filesystem.cpp
- src/core/file_sys/program_metadata.cpp
- src/core/file_sys/romfs_factory.cpp
- src/core/file_sys/romfs_filesystem.cpp
- src/core/file_sys/savedata_factory.cpp
- src/core/file_sys/sdmc_factory.cpp
> file-sys: Move logging macros over to the new fmt-capable ones

- src/core/gdbstub/gdbstub.cpp
After this, there's essentially one more PR and all of core will be converted where applicable.
> core/gdbstub: Move logging macros to new fmt-compatible ones

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Not much to see here - just some minimal changes in preparation for implementing integer instructions. No functional changes to shader emulation, yet.
> Shader decompiler prep for integer instructions

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Next part of my changes for supporting integer shader instructions. With this change, we add the `GLSLRegisterManager` class, which is used to track each `GLSLRegister` instance. This class now encapsulates all register `Set*` and `Get*` methods, handling integer/float conversions as needed.
At this point, there are still no functional changes - no new instructions implemented, but should be no regressions with currently supported shaders that use floats.
> gl_shader_decompiler: Add GLSLRegisterManager class to track register state.

- src/common/file_util.cpp
- src/common/file_util.h
Each commit should be fairly self-explanatory
> file_util: Minor changes to IOFile

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
- src/video_core/renderer_opengl/maxwell_to_gl.h
With these changes, we now get the loading graphic on Minecraft
> Shader instructions MOV_C, MOV_R, and several minor GPU things

- src/common/vector_math.h
Ensures that values are always in a well-defined state.
> vector_math: Ensure members are always initialized

- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
- src/core/settings.h
Update all controller timestamps always, update mouse+keyboard states, update unknown section states, add analog stick support.
> hid: Tweaks, Analog Sticks

- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
Removed stubbed 0xcafe value and replaced with more accurate implementation.
> More accurate GetTPCMasks impl

- src/yuzu/debugger/wait_tree.cpp
- src/yuzu/debugger/wait_tree.h
> Qt/WaitTree: Display the callstack for each thread in the wait tree widget

- src/core/hle/service/audio/audin_u.cpp
- src/core/hle/service/audio/audout_u.cpp
- src/core/hle/service/audio/audrec_u.cpp
- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/audio/codecctl.cpp
I've made these changes according to switchbrew website : 
http://switchbrew.org/index.php?title=Audio_services
> Correct audio command numbers & add or rename some functions

- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
- src/core/hle/service/nvdrv/devices/nvmap.cpp
- src/core/hle/service/nvdrv/devices/nvmap.h
- src/video_core/memory_manager.cpp
- src/video_core/memory_manager.h
> Implemented nvhost-as-gpu's UnmapBuffer and nvmap's Free ioctls.

- src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
- src/core/hle/service/nvdrv/devices/nvmap.cpp
- src/core/hle/service/nvdrv/devices/nvmap.h
changes has been made according to : 
http://switchbrew.org/index.php?title=NV_services
> Add ioctl commands with their params and size check

- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
We have no clue on what this actually does yet so stubbing it since it's just input only should be fine for now
> Stubbed NVGPU_GPU_IOCTL_ZBC_SET_TABLE

- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/audio/audren_u.h
Impl of GetAudioRendererWorkBufferSize based on RE, if this can be cleaned up, please contribute!
> GetAudioRendererWorkBufferSize impl

- src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_gpu.h
Used in Nintendo Labo ToyCon 1&2
> Stub NVGPU_IOCTL_CHANNEL_SET_TIMEOUT

- src/core/hle/kernel/svc.h
- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/am/applet_oe.cpp
I've add or correct those things below according to switchbrew : 
- Add some InfoType in svc.h
- Correct OpenApplicationProxy command number
- Add IDisplayController functions
- Add more system languages
> Add & correct miscellaneous things

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/bcat/bcat.cpp
- src/core/hle/service/bcat/bcat.h
- src/core/hle/service/bcat/module.cpp
- src/core/hle/service/bcat/module.h
- src/core/hle/service/service.cpp
> Service/BCAT: add module and services

- src/core/hle/ipc.h
- src/core/hle/service/hid/hid.cpp
all these changes has been made according to switchbrew website.
- Invalid as cmd number 0
- LegacyRequest as cmd number 1
- LegacyControl as cmd number 3
add functions useful for 4.0.0+ and 5.0.0+
> add IPC CommandType & Some HID FunctionInfo

- src/core/hle/service/time/time.cpp
- src/core/hle/service/time/time.h
addittionally, some changes in service/time structures
> Service/time: implement posix time to calendar conversion

- src/core/CMakeLists.txt
- src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
- src/core/hle/service/nvdrv/devices/nvhost_nvdec.h
- src/core/hle/service/nvdrv/nvdrv.cpp
This device used in game Monster Energy Supercross and some other
> Services/nvdrv: add '/dev/nvhost-nvdec' device

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Slightly better than what we had before.
> gl_shader_decompiler: Implement RRO as a register move.

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
Basic RE work done by @ogniK5377 is the basis for this implementation. These were tested with SMO, which now gets to drawing code with these changes.
> am: Implement CreateStorage, PushInData, etc.

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This PR implements a simple version of the `bra` instruction, supporting the same modifiers as the current `kil` instruction implementation.
> GPU: Partially implemented the bra shader instruction

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
1-2 Switch just so happened to work because both were broken, they should be correct now, at least the implemented parts of them.
> GPU: Corrected the FSET and I2F instructions.

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Also fixed the type conversion when reading uniforms in fset and fsetp.
> GPU: Implemented the ISETP_R and ISETP_C instructions

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This should also fix those cases where we ended up with incomplete shaders because the control flow analyzer decided to end processing after finding a predicated exit.
> GPU: Implemented predicated exit instructions in the shader programs.

- src/video_core/engines/shader_bytecode.h
Because for some ungodly reason i thought 20+24-20 = 5
> GPU: Corrected the branch targets for the shader bra instruction.

- src/video_core/renderer_opengl/maxwell_to_gl.h
> maxwell_to_gl: Implement WrapMode Mirror.

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/nifm/nifm.cpp
Adds a few stubs. Used by Splatoon 2.
> Stub SetConnectionConfirmationOption, GetPseudoDeviceId

- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
these changes has been done according to switchbrew : 
http://switchbrew.org/index.php?title=NV_services
> nvdrv/devices/nvidia_ctrl_gpu : add IoctlCommands with their params

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Just some misc local changes I have floating around...
> gl_shader_decompiler: Additional decodings, remove unused stuff from TEX

- src/core/hle/service/nfp/nfp.cpp
> Service/nfp:user : stub some functions.

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/mm/mm_u.cpp
- src/core/hle/service/mm/mm_u.h
- src/core/hle/service/service.cpp
Used in some games, for example, Monster Energy Supercross
> Service/MM: add service and stub some functions

- .travis.yml
- .travis/linux/build.sh
- .travis/linux/docker.sh
- .travis/macos/build.sh
- .travis/macos/deps.sh
This significantly reduces compile times on Travis.
> Enable ccache usage on Travis

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> gl_shader_decompiler: Implement saturate for float instructions.

- src/video_core/CMakeLists.txt
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
- src/video_core/textures/astc.cpp
- src/video_core/textures/astc.h
- src/video_core/textures/decoders.cpp
Fairly self-explanatory, I think. With these changes, and some hand waviness, you can get some gfx output in SMO:
> gl_rasterizer: Implement texture format ASTC_2D_4X4.

- src/core/hle/service/set/set.cpp
> Implement GetAvailableLanguageCodes2

- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/audio/audren_u.h
- Rename some structures
- Rewrite RequestUpdateAudioRenderer to fit output for different audio revisions
> Service/Audio: update audren:u service

- CMakeLists.txt
- CMakeModules/CopyYuzuQt5Deps.cmake
- CMakeModules/CopyYuzuSDLDeps.cmake
- CMakeModules/CopyYuzuUnicornDeps.cmake
- appveyor.yml
- externals/cmake-modules/WindowsCopyFiles.cmake
> Revert "Use Ninja for MSVC AppVeyor builds"

- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/audio/audren_u.h
According to game symbols(SMO), there's references to UpdateDataHeader which seems to be what AudioRendererResponse actually is
> Removed duplicate structs, changed AudioRendererResponse -> UpdateDataHeader

- src/video_core/debug_utils/debug_utils.h
Fixes https://github.com/yuzu-emu/yuzu/issues/582
> Fix crash at exit

- src/core/CMakeLists.txt
- src/core/hle/service/audio/audio.cpp
- src/core/hle/service/audio/hwopus.cpp
- src/core/hle/service/audio/hwopus.h
Used in game BlazBlue and some other
> Service/Audio: add hwopus service, stub GetWorkBufferSize function

- src/video_core/memory_manager.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
This supersedes the last commit in #599
> GPU: Ignore invalid and disabled textures when drawing.

- src/core/hle/service/audio/audren_u.cpp
This makes various games not deadlock anymore whilst waiting for a voice section update.
> Update AudioRenderer Voice Sections

- CMakeModules/CopyYuzuQt5Deps.cmake
- appveyor.yml
See https://github.com/citra-emu/citra/pull/3716 for what happened to the dll
> Add qt windowsvistastyle dll to the build

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
- src/video_core/rasterizer_interface.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
Support clearing both the color and the depth buffer.
Depends on #608
> GPU: Implemented the CLEAR_BUFFERS register.

- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
- src/video_core/textures/decoders.cpp
> GPU: Implemented the 32 bit float depth buffer format.

- src/common/common_paths.h
- src/common/file_util.cpp
- src/yuzu_cmd/default_ini.h
This super big and important PR will make Super Mario Odyssey go ingame at 8k with 120FPS. /s
> Remove some references to Citra

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
It's similar to the FMNMX instruction but it works on integers.
> GPU: Implemented the IMNMX shader instruction.

- src/yuzu/bootmanager.cpp
See https://github.com/citra-emu/citra/pull/3505 for more information.
> Port #3505 from Citra: Fix QGLWidget viewport resize on macOS

- src/common/assert.h
See https://github.com/citra-emu/citra/pull/3474 for more information.
> Port #3474 from Citra: Do not crash on unimplemented code in debug build

- src/common/common_funcs.h
- src/common/memory_util.cpp
- src/common/swap.h
See https://github.com/citra-emu/citra/pull/3579 for more details.
> Port #3579 from Citra: Clean up architecture-specific defines

- src/core/hle/service/hid/hid.cpp
- This fixes user input in SMO.
> hid: Fix timestamps and controller type.

- src/yuzu/debugger/console.cpp
- src/yuzu/main.cpp
- src/yuzu_cmd/yuzu.cpp
* Use log filter from settings in yuzu-cmd
* Fix duplicate log issues https://github.com/yuzu-emu/yuzu/issues/628
> Minor logging fixes

- src/video_core/renderer_opengl/gl_rasterizer.cpp
The GPU ignores that register when clearing, but OpenGL obeys the glDepthMask parameter, so we set the depth mask to GL_TRUE when clearing the depth buffer. It will be restored to the correct value automatically on the next draw call.
This fixes the Minecraft Story Edition title screen.
> GPU: Always enable the depth write when clearing the depth buffer.

- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/service/nvflinger/buffer_queue.cpp
- src/core/hle/service/nvflinger/buffer_queue.h
- src/core/hle/service/nvflinger/nvflinger.cpp
- src/core/hle/service/vi/vi.cpp
Gets SteamWorld Dig 2 booting, probably fixes some other things.
> nvflinger: Fix for BufferQueue event handling.

- src/core/hle/kernel/address_arbiter.cpp
As @lioncash pointed out in his review after my previous PR was merged...I actually forgot to conditionally decrement (and ignored the argument saying whether to do so). This also fixes a signed/unsigned comparison he noted.
> svc:: Fix bug in svcWaitForAddress

- src/video_core/textures/astc.cpp
Minor changes to make the astc code a slight bit better (and not produce some silly warnings), as well as skimmed cleanup.
> astc: Minor changes

- src/common/telemetry.h
Just basic tidying up of the telemetry interface
> Telemetry: Minor changes

- src/yuzu/game_list.cpp
- src/yuzu/game_list.h
This function doesn't modify internal class state, so it can be made a const member function.
>  game_list: Make containsAllWords a const member function 

- src/core/hle/service/hid/hid.cpp
> Touchscreen Support

- src/yuzu/game_list.cpp
- src/yuzu/game_list.h
This function actually depends on no internal class state, so it doesn't even need to be a part of the class interface.
> game_list: Make ContainsAllWords an internally linked non-member function

- src/core/file_sys/content_archive.cpp
- src/core/file_sys/content_archive.h
> content_archive: Minor changes

- src/common/string_util.cpp
- src/common/string_util.h
> string_util: Remove AsciiToHex()

- src/common/swap.h
Just a few modernization changes
> common/swap: Minor changes

- src/core/hle/service/filesystem/filesystem.cpp
Minor individual changes that don't necessarily deserve their own PR
> filesystem: Minor changes

- src/core/hle/service/filesystem/fsp_srv.cpp
This includes a few relatively contained changes that don't really warrant being broken into their own individual PRs.
>  fsp_srv: Misc individual changes

- src/core/loader/nso.cpp
Two minor cleanup and warning related changes
> nso: Minor changes

- src/core/file_sys/vfs.cpp
- src/core/file_sys/vfs.h
- src/core/file_sys/vfs_offset.cpp
- src/core/file_sys/vfs_offset.h
Just a few self-contained minor changes to the interface
> vfs: Minor changes

- src/tests/core/arm/arm_test_common.cpp
- src/tests/core/arm/arm_test_common.h
Minor changes to get rid of a few warnings and file-static state
> tests/arm_test_common: Minor changes

- src/core/file_sys/partition_filesystem.cpp
- src/core/file_sys/vfs_real.cpp
Just a few self-contained minor individual changes
> partition_filesystem, vfs_real: Minor changes

- src/common/file_util.cpp
Should be fairly straightforward.
> file_util: Remove redundant duplicate return in GetPathWithoutTop()

- src/common/file_util.cpp
- src/common/file_util.h
- src/core/file_sys/vfs_real.cpp
- src/core/loader/deconstructed_rom_directory.cpp
- src/yuzu/game_list.cpp
Each commit should be self-explanatory
> file_util: Minor changes to ScanDirectoryTree() and ForeachDirectoryEntry()

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> gl_shader_decompiler: Implement SEL instruction.

- src/core/CMakeLists.txt
- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/arm/dynarmic/arm_dynarmic.h
- src/core/arm/exclusive_monitor.cpp
- src/core/arm/exclusive_monitor.h
- src/core/core.cpp
- src/core/core.h
- src/core/core_cpu.cpp
- src/core/core_cpu.h
Global exclusive monitor across cores.
NOTE: Unicorn support is nonexistent.
> Implement exclusive monitor

- src/video_core/engines/shader_bytecode.h
> shader_bytecode: Implement other TEXS masks.

- src/common/string_util.cpp
- src/common/string_util.h
Minor individual changes to get out of the way before introducing usages of std::string_view to the string utility functions. Each should be fairly self-contained
> string_util: Minor changes

- src/core/CMakeLists.txt
- src/core/file_sys/control_metadata.cpp
- src/core/file_sys/control_metadata.h
- src/core/loader/nro.cpp
- src/core/loader/nro.h
Part of a larger change, but its probably better to split it up.
> NRO Assets and NACP File Format

- src/core/loader/loader.cpp
Each change should be fairly self-contained.
> loader: Minor cleanup

- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/arm/dynarmic/arm_dynarmic.h
This functions doesn't modify instance state, so it can be a made a const member function.
> arm_dynarmic: Make MakeJit() a const member function

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
Just a few minor self-contained changes.
> gl_rasterizer: Minor cleanup

- src/core/CMakeLists.txt
- src/core/core_timing.cpp
- src/core/core_timing.h
- src/core/core_timing_util.cpp
- src/core/core_timing_util.h
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/timer.cpp
- src/core/hle/service/audio/audout_u.cpp
- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/nvflinger/nvflinger.cpp
- src/core/hle/service/time/time.cpp
> core_timing: Split off utility functions into core_timing_util

- src/core/CMakeLists.txt
- src/core/hle/service/es/es.cpp
- src/core/hle/service/es/es.h
- src/core/hle/service/service.cpp
Adds the skeleton for the ETicket service based off the information on Switch Brew
> service: Add the es service

- src/core/CMakeLists.txt
- src/core/hle/service/pm/pm.cpp
- src/core/hle/service/pm/pm.h
- src/core/hle/service/service.cpp
Adds the skeleton for the process management services based off information on Switch Brew.
> service: Add pm services

- src/core/hle/service/nvdrv/nvdrv.cpp
- src/core/hle/service/nvdrv/nvdrv.h
Two minor self-contained changes
> service/nvdrv: Minor changes

- src/core/CMakeLists.txt
- src/core/hle/service/erpt/erpt.cpp
- src/core/hle/service/erpt/erpt.h
- src/core/hle/service/eupld/eupld.cpp
- src/core/hle/service/eupld/eupld.h
- src/core/hle/service/service.cpp
Adds the skeletons for both services based off information on Switch Brew.
> service: Add erpt and eupld services

- src/core/hle/service/lm/lm.cpp
- src/core/hle/service/lm/lm.h
Minor self-contained changes to the logging service.
> service/lm: Minor changes

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/ldn/ldn.cpp
- src/core/hle/service/ldn/ldn.h
- src/core/hle/service/service.cpp
Adds ldn services based off information provided by Switch Brew.
> service: Add ldn services

- src/core/CMakeLists.txt
- src/core/hle/service/nim/nim.cpp
- src/core/hle/service/nim/nim.h
- src/core/hle/service/service.cpp
Adds the skeleton for the nim services based off information from Switch Brew.
> service: Add the nim services

- .gitignore
- src/yuzu_cmd/default_ini.h
See https://github.com/citra-emu/citra/pull/3641 and https://github.com/citra-emu/citra/pull/3702 for more details.
> Port #3641 and #3702 from Citra (Small changes to default_ini and gitignore)

- src/yuzu/main.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
See https://github.com/citra-emu/citra/pull/3665 for more details.
> Port #3665 from Citra: "frontend: Log Citra version"

- src/core/CMakeLists.txt
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/irs.cpp
- src/core/hle/service/hid/irs.h
- src/core/hle/service/hid/xcd.cpp
- src/core/hle/service/hid/xcd.h
Adds the remaining missing services using the information provided by Switch Brew.
> service/hid: Add missing services

- src/core/CMakeLists.txt
- src/core/hle/service/btdrv/btdrv.cpp
- src/core/hle/service/btdrv/btdrv.h
- src/core/hle/service/service.cpp
Added based off the information provided by Switch Brew
> service: Add the btdrv service

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/lbl/lbl.cpp
- src/core/hle/service/lbl/lbl.h
- src/core/hle/service/service.cpp
Adds the lbl service based off the information provided by Switch Brew.
> service: Add the lbl service

- src/yuzu/main.cpp
See https://github.com/citra-emu/citra/pull/3594 for more details.
> Port #3594 from Citra: "citra_qt: Add Continue/Pause & Toggle Speed Limit hotkeys"

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/nfc/nfc.cpp
- src/core/hle/service/nfc/nfc.h
- src/core/hle/service/service.cpp
Adds the skeleton of the nfc service based off the information provided on Switch Brew.
> service: Add nfc services

- src/core/CMakeLists.txt
- src/core/file_sys/content_archive.cpp
- src/core/file_sys/romfs.cpp
- src/core/file_sys/romfs.h
- src/core/file_sys/vfs.cpp
- src/core/file_sys/vfs.h
- src/core/file_sys/vfs_offset.cpp
- src/core/file_sys/vfs_offset.h
- src/core/file_sys/vfs_real.cpp
- src/core/file_sys/vfs_real.h
- src/core/file_sys/vfs_vector.cpp
- src/core/file_sys/vfs_vector.h
Converts a RomFS from a single binary blob to a `VirtualDir`.
Part of an upcoming suprise, figured I'd break it up.
> RomFS Extraction

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/mii/mii.cpp
- src/core/hle/service/mii/mii.h
- src/core/hle/service/service.cpp
Adds the skeleton for the mii services based off information provided by Switch Brew
> service: Add mii services

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/service.cpp
- src/core/hle/service/wlan/wlan.cpp
- src/core/hle/service/wlan/wlan.h
Adds the basic skeleton for the wlan services based off the information on Switch Brew.
> service: Add wlan services

- src/common/common_funcs.h
- src/common/swap.h
See https://github.com/citra-emu/citra/pull/3732 for more details.
Obviously I couldn't test if compilation is actually fixed on ARM now, but this PR should at least be a step towards it.
> Port #3732 from Citra: "common: Fix compilation on ARM"

- src/yuzu/main.cpp
See https://github.com/citra-emu/citra/pull/3913 for more details.
> Port #3913 from Citra: "citra_qt: Remove obsolete application attribute"

- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_general.cpp
- src/yuzu/configuration/configure_graphics.cpp
- src/yuzu/configuration/configure_input.cpp
- src/yuzu/main.cpp
See https://github.com/citra-emu/citra/pull/3911 for more details.
> Port #3911 from Citra: "citra-qt: optimize settings application"

- src/yuzu/about_dialog.cpp
- src/yuzu/aboutdialog.ui
See https://github.com/citra-emu/citra/issues/3837 for more details.
> Port #3837 from Citra: "citra-qt: Add build date in about dialog"

- src/common/timer.cpp
- src/common/timer.h
See https://github.com/citra-emu/citra/pull/3972 for more details.
> Port #3972 from Citra: "common/timer: use std::chrono, avoid platform-dependent code"

- src/common/threadsafe_queue.h
See https://github.com/citra-emu/citra/pull/3973 for more details.
> Port #3973 from Citra: "Remove polymorphism issue"

- src/video_core/gpu.cpp
- src/video_core/gpu.h
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
Used by Games like Go Vacation
> Implement R32_FLOAT RenderTargetFormat

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/caps/caps.cpp
- src/core/hle/service/caps/caps.h
- src/core/hle/service/service.cpp
Adds the basic skeleton for the capture services based off information provided by Switch Brew.
> service: Add capture services

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/psc/psc.cpp
- src/core/hle/service/psc/psc.h
- src/core/hle/service/service.cpp
Adds the basic skeleton for the psc services based off the information provided by Switch Brew.
> service: Add the psc services

- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
- src/video_core/textures/decoders.cpp
Used by games like Go Vacation
> Implement RGB32F PixelFormat

- src/core/file_sys/vfs_vector.cpp
Two minor self-contained changes
> vfs_vector: Minor changes

- src/core/hle/kernel/address_arbiter.cpp
In all cases the vector being supplied is empty, so we can just return by value in these instances.
> address_arbiter: Return by value from GetThreadsWaitingOnAddress()

- src/yuzu/about_dialog.cpp
- src/yuzu/about_dialog.h
- src/yuzu/bootmanager.h
- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_dialog.cpp
- src/yuzu/configuration/configure_general.cpp
- src/yuzu/configuration/configure_graphics.cpp
- src/yuzu/configuration/configure_system.cpp
- src/yuzu/debugger/graphics/graphics_surface.cpp
- src/yuzu/debugger/graphics/graphics_surface.h
- src/yuzu/debugger/wait_tree.cpp
- src/yuzu/debugger/wait_tree.h
- src/yuzu/game_list_p.h
- src/yuzu/main.h
Minor cleanup-related changes to the Qt code.
> qt: Minor cleanup-related changes

- src/yuzu/game_list.cpp
There's no need to keep these separate from one another.
> game_list: Join declarations and assignments in onTextChanged()

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/CMakeLists.txt
- src/core/hle/service/service.cpp
- src/core/hle/service/usb/usb.cpp
- src/core/hle/service/usb/usb.h
Adds basic skeleton for the usb services based off the information provided by Switch Brew.
> service: Add usb services

- src/audio_core/CMakeLists.txt
Implemented https://github.com/yuzu-emu/yuzu/issues/915#issuecomment-410883601
> Make building cubeb optional

- src/core/hle/service/time/time.cpp
Updates the ID of these based off the information on Switch Brew.
> service/time: Amend command IDs of ToPosixTime() and ToPosixTimeWithMyRule()

- src/core/hle/service/hid/hid.cpp
Updated based off the information on Switch Brew.
> services/hid: Add ActivateNpadWithRevision() to the hid function info array

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- Used by Super Mario Odyssey.
> am: Stub SetScreenShotImageOrientation.

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
- Used by Super Mario Odyssey.
> gl_shader_decompiler: Stub input attribute Unknown_63.

- src/common/vector_math.h
> vector_math: Use variable template version of is_signed in Vec classes

- src/common/color.h
Gets rid of undefined behavior within some functions and cleans up some return types.
> common/color: Minor cleanup

- src/video_core/renderer_opengl/maxwell_to_gl.h
- Used by Super Mario Odyssey (in game).
> Implement VertexAttribute::Size::Size_16_16_16_16 and PrimitiveTopology::Points.

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
- Used by Super Mario Odyssey (when going in game).
> gl_shader_decompiler: Declare predicates on use.

- src/video_core/engines/maxwell_3d.cpp
- Used by Super Mario Odyssey (in game).
> maxwell_3d: Ignore macros that have not been uploaded yet.

- src/video_core/renderer_opengl/maxwell_to_gl.h
- Used by Super Mario Odyssey.
> Implements VertexAttributes Size_32_32_32 and Size_8_8.

- src/yuzu/game_list_p.h
Minor self-contained cleanups that should be self-explanatory.
> qt/gamelist: Minor cleanup-related changes

- src/video_core/command_processor.h
- src/video_core/engines/shader_bytecode.h
> video_core: Use variable template variants of type_traits interfaces where applicable

- src/video_core/engines/maxwell_3d.h
- src/video_core/renderer_opengl/maxwell_to_gl.h
These are used by nouveau and some games like SMO.
> GPU/Maxwell3D: Implemented an alternative set of blend factors.

- src/core/core.cpp
- src/core/core.h
- src/core/frontend/emu_window.cpp
- src/core/frontend/emu_window.h
- src/video_core/renderer_base.cpp
- src/video_core/renderer_base.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/video_core/renderer_opengl/renderer_opengl.h
- src/video_core/video_core.cpp
- src/video_core/video_core.h
- src/yuzu/bootmanager.h
- src/yuzu_cmd/emu_window/emu_window_sdl2.h
Gets the class out of the global namespace.
> core: Namespace EmuWindow

- src/core/hle/service/friend/friend.cpp
Needed for Retro City Rampage to go in game
> Stub UpdateUserPresence

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> gl_shader_decompiler: Fix SetOutputAttributeToRegister empty check.

- src/core/hle/service/hid/hid.cpp
This is needed for ARMS to progress further.
>  hid: Stub DisconnectNpad() 

- src/common/misc.cpp
linux-mingw does not really like this.
> common/misc: use windows.h

- src/video_core/renderer_opengl/gl_rasterizer_cache.h
require by Zelda Breath Of The Wild
> Implement Z16 in PixelFormatFromTextureFormat function

- src/core/core_timing.cpp
- src/core/core_timing.h
- src/core/hle/kernel/thread.cpp
> Core::CoreTiming: add UnscheduleEventThreadsafe

- src/common/hex_util.cpp
- src/common/hex_util.h
- src/core/crypto/key_manager.cpp
- src/core/file_sys/registered_cache.cpp
It's in the common code, so it should be under the Common namespace like everything else.
> common: Namespace hex_util.h/.cpp

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
Require by Toki Tori and Toki Tori 2+
> Implement GetDefaultDisplayResolutionChangeEvent

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> Added pred-condition GreaterThanWithNan

- appveyor.yml
See https://github.com/citra-emu/citra/pull/3616 for more details.
> Port #3616 from Citra: "appveyor: set jobs to 4 for mingw"

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
The SSY instruction pushes an address into the stack, and the SYNC instruction pops it. The current stack depth is 20, we should figure out if this is enough or not.
This fixes some infinite loops in some SMO shaders with more complex flow control, where two SSYs were being nested.
> Shaders: Implemented a stack for the SSY/SYNC instructions.

- src/video_core/renderer_opengl/maxwell_to_gl.h
- src/yuzu/main.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
> Added WrapMode MirrorOnceClampToEdge

- src/video_core/engines/shader_bytecode.h
Previously we could end up with a TEXS that didn't write any outputs, this was wrong.
> Shaders/TEXS: Fixed the component mask in the TEXS instruction.

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This was implemented a while ago.
> Shader: Remove an unneeded assert, the negate bit is implemented for conversion instructions.

- src/video_core/gpu.cpp
- src/video_core/gpu.h
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
> Implemented RGBA8_UINT

- src/core/hle/service/pctl/module.cpp
This fixes save files not loading in splatoon 2
> Added CheckFreeCommunicationPermission

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Previously `TEXS` with a mask of `BA` would try to write the both values to the gpr28 and gpr28+1, but they should be written to gpr0 and gpr0+1, using only gpr28 and gpr28+1 for the values that didn't fit into the first two gprs.
> Shaders/TEXS: Write to the correct output register when swizzling.

- src/core/hle/service/ns/pl_u.cpp
> Added missing include for pl:u

- src/video_core/engines/maxwell_3d.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
- src/video_core/renderer_opengl/maxwell_to_gl.h
This will ASSERT if blending is enabled at the same time as logic ops.
I do not currently know of any game that uses this, i'm placing it in canary to see if it fixes anything.
> GPU: Implemented logic ops.

- src/yuzu/main.cpp
- src/yuzu/main.ui
See https://github.com/citra-emu/citra/pull/3902 for more details.
**#1140 must be merged before this PR can be merged!**
> Port #3902 from Citra: "Add restart hotkey & menu option"

- src/yuzu/configuration/configure_input.ui
Major fix /s requested by Hydro
> Swap "Plus" with "Minus" on the controller GUI

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Hi, this is my first PR so I'm not quite sure what to write in here.
This implements the LOP3 instruction, at least partially.
> gl_shader_decompiler: Implement LOP3

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/pm/pm.cpp
- src/core/hle/service/pm/pm.h
> Added GetBootMode

- src/yuzu/main.cpp
See https://github.com/citra-emu/citra/pull/4013 for more details.
> Port #4013 from Citra: "Init logging sooner so we dont miss some logs on startup"

- src/core/core.h
- src/yuzu/main.cpp
Pretty self explanatory.
Example:
> qt: Add filename and title id to window title while running

- src/core/core.h
- src/video_core/debug_utils/debug_utils.cpp
- src/video_core/debug_utils/debug_utils.h
- src/yuzu/debugger/graphics/graphics_breakpoints.cpp
- src/yuzu/debugger/graphics/graphics_surface.cpp
Just a few minor cleanup related changes. Each commit should be fairly explanatory.
> debug_utils: Minor individual interface changes

- src/core/arm/arm_interface.h
- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/arm/dynarmic/arm_dynarmic.h
- src/core/arm/exclusive_monitor.cpp
- src/core/arm/exclusive_monitor.h
- src/core/arm/unicorn/arm_unicorn.cpp
- src/core/arm/unicorn/arm_unicorn.h
- src/core/core.h
- src/core/core_cpu.h
- src/core/hle/kernel/scheduler.cpp
- src/core/hle/kernel/scheduler.h
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
Gets all of these types and interfaces out of the global namespace.
> core: Namespace all code in the arm subdirectory under the Core namespace

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
I don't have many games. Can't really test this. Sorry.
> Shaders: Implemented IADD3

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Thanks @ReinUsesLisp and @gdkchan for the tip. Fixes some rendering issues with SMO.
> gl_shader_decompiler: Improve IPA for Pass mode with Position attribute.

- src/audio_core/stream.cpp
- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/arm/unicorn/arm_unicorn.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
Blame the subsystems which deserve the blame :)
The updated list is not complete, just the ones I've spotted on random sampling the stack trace.
> Update microprofile scopes.

- src/core/core.cpp
- src/core/core.h
- src/video_core/command_processor.cpp
- src/video_core/gpu.h
Two small and trivial 1% optimizations. Please read the commit messages of the patches.
> Optimizations

- src/common/logging/filter.h
- src/common/logging/log.h
- src/common/logging/text_formatter.h
Each change should be fairly self-contained. Mostly just a tiny cleanup and some documentation fixes (syntax-wise with doxygen)
> common/logging: Minor changes

- src/video_core/renderer_opengl/gl_shader_gen.cpp
IMO the old code is fine, but nvidia raises shader compiler warnings.
Trivial fix through...
> gl_shader_gen: Initialize position.

- src/common/CMakeLists.txt
- src/common/scm_rev.cpp.in
- src/common/scm_rev.h
- src/yuzu/about_dialog.cpp
- src/yuzu/main.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
[**REBASED**]
* ~~This PR is blocked by #1196 and also needs a port of Citra's [#3825](https://github.com/citra-emu/citra/pull/3825).~~
see [citra-emu/citra#3804](https://github.com/citra-emu/citra/pull/3804) for more details.
> Port #3804 from Citra - Better Title Bar Display

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> shader_decompiler: Implemented (Partialy) TXQ

- src/video_core/engines/maxwell_dma.cpp
When not set, this tells the GPU to only use the X size when performing a DMA copy.
This is only implemented for linear->linear and tiled->tiled copies. Conversion copies still retain the assert.
This bit is unset by some games for various purposes, and by nouveau when copying the vertex buffers.
> GPU/DMA: Partially implemented the 'enable_2d' bit in the DMA engine.

- src/core/hle/service/hid/hid.cpp
- src/core/settings.h
This fixes being unable to change input keys while the game is running.
> hid: Implement ReloadInputDevices

- src/video_core/engines/maxwell_3d.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
Original impl. from @Subv, with several other changes. Fixes several graphical issues with SMO (and I would guess many other games).
> gl_rasterizer: Implement multiple color attachments.

- src/yuzu/configuration/configure_general.cpp
- src/yuzu/configuration/configure_general.ui
> Remove the multi-core option from the UI

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- Also include several misc. changes to ConfigureFramebuffers in support of this.
> gl_rasterizer: Implement clear for non-zero render targets.

- src/input_common/main.cpp
- src/input_common/main.h
- src/input_common/sdl/sdl.cpp
- src/input_common/sdl/sdl.h
- src/yuzu/bootmanager.cpp
- src/yuzu/configuration/configure_input.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
See citra-emu/citra#4141 for more details.
> Port #4141 from citra: Joystick hotplug support

- src/core/hle/ipc.h
Change DataPayloadRequest to DataPayloadHeader
> ipc: minor fix

- src/video_core/CMakeLists.txt
- src/video_core/command_processor.cpp
- src/video_core/engines/kepler_memory.cpp
- src/video_core/engines/kepler_memory.h
- src/video_core/gpu.cpp
- src/video_core/gpu.h
This engine writes data from a FIFO register into the configured address.
It is used by nouveau.
> GPU: Basic implementation of the Kepler Inline Memory engine (p2mf).

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This seems to be an optimization performed by nouveau.
> Shaders: Implemented multiple-word loads and stores to and from attribute memory.

- src/core/hle/kernel/svc.cpp
Another super important change.
See citra-emu/citra#4192 for more details.
> Port #4192 from Citra: "svc: change unknown to thread in CreateThread"

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> shader_decompiler: Asserts for Texture Instructions

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
> Implemented GetDefaultDisplayResolution

- src/video_core/renderer_opengl/gl_rasterizer.cpp
We uploaded the wrong data before. So the offset on the host GPU pointer may work for the first vertices, the last ones run out bounds.
Let's just offset the upload instead.
> gl_rasterizer: Fix StartAddress handling with indexed draw calls.

- src/core/hle/service/nim/nim.cpp
Needed because of the recent nim fixes. This fixes splatoon 2 not going in game
> Implemented NTC & IEnsureNetworkClockAvailabilityService

- src/core/file_sys/xts_archive.cpp
- src/core/file_sys/xts_archive.h
- src/core/loader/nax.cpp
- src/core/loader/nax.h
Just a few interface changes to be less wasteful with memory and get rid of compiler warnings.
> xts_archive/nax: Minor interface changes

- src/core/hle/service/nifm/nifm.cpp
This fixes updated versions of SMO. Currently unable to test as I don't have an updated version
> Added IRequest::Submit

- src/core/loader/nso.cpp
Unable to use a bitfield for flags since it won't be a trivial copy
> Added support for uncompressed NSOs

- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/utils.h
Special thanks to @ReinUsesLisp for the help
> Added glObjectLabels for renderdoc for textures and shader programs

- src/core/hle/service/ssl/ssl.cpp
> Corrected SSL::SetInterfaceVersion

- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/core/hle/service/hid/irs.cpp
- src/core/hle/service/hid/irs.h
Currently we have no ideal way of implementing IRS. For the time being we should have the functions stubbed until we come up with a way to emulate IRS properly.
> Stubbed IRS

- src/core/core.cpp
- src/core/file_sys/fsmitm_romfsbuild.cpp
- src/core/file_sys/patch_manager.cpp
- src/core/file_sys/registered_cache.cpp
- src/core/file_sys/romfs.cpp
- src/core/file_sys/vfs.cpp
- src/core/file_sys/vfs.h
- src/core/file_sys/vfs_concat.cpp
- src/core/file_sys/vfs_concat.h
- src/core/file_sys/vfs_layered.cpp
- src/core/file_sys/vfs_layered.h
- src/core/file_sys/vfs_static.h
- src/core/file_sys/vfs_vector.cpp
- src/core/file_sys/vfs_vector.h
- src/yuzu/main.cpp
Just a few things that slipped through. Each commit should contain its own description explaining the changes.
> vfs: Minor cleanup related changes to layered VFS code

- CMakeLists.txt
- src/common/file_util.h
- src/common/string_util.cpp
- src/common/string_util.h
See citra-emu/citra#4253 for more details.
> Port citra-emu/citra#4253: "common/string_util cleanup"

- src/common/param_package.cpp
- src/common/param_package.h
- src/yuzu/configuration/configure_input.cpp
- src/yuzu/configuration/configure_input.h
- src/yuzu/configuration/configure_input.ui
See citra-emu/citra#4140 for more details.
> Port citra-emu/citra#4140: "misc input tab improvements"

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
- src/video_core/renderer_opengl/gl_shader_gen.h
- src/video_core/renderer_opengl/maxwell_to_gl.h
- src/video_core/textures/texture.h
With this PR we add depth compare for textures. This fixes some effects in SMO like water, fog and some shadows. Please test and let me know if anything weird appears compared to master.
> Implemented Depth Compare, Shadow Samplers and Texture Processing Modes for TEXS and TLDS

- src/core/file_sys/ips_layer.cpp
- src/core/file_sys/ips_layer.h
Minor miscellaneous clean-up/efficiency changes that don't really deserve their own individual PRs. Each commit's comments should be fairly explanatory.
> ips_layer: Minor miscellaneous changes

- src/core/telemetry_session.cpp
- src/core/telemetry_session.h
Minor changes that don't necessarily deserve their own PRs. Each commit should explain the rationale in their commit messages.
> telemetry_session: Minor miscellaneous changes

- src/yuzu/bootmanager.cpp
- src/yuzu/bootmanager.h
- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.h
See citra-emu/citra#4310 for more details.
> Port citra-emu/citra#4310: "Handle touch input"

- src/video_core/engines/maxwell_3d.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
Added scissor testing, nothing else.
> Implemented Scissor Testing

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Not much to describe. It's a very mad instruction, that's for sure.
> gl_shader_decompiler: Implement VMAD

- src/core/hle/service/audio/hwopus.cpp
> HwOpus, Implemented DecodeInterleavedWithPerformance

- src/core/hle/service/nvdrv/devices/nvmap.cpp
Just to make it a bit more console accurate
> Added error codes for nvmap

- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
Added error for invalid nmap handles
> Passing an invalid nmap handle to Remap should throw an error

- src/core/hle/kernel/svc.cpp
- src/core/hle/kernel/svc_wrap.h
svcBreak reason should be a u32, not a u64.
> Fixed incorrect types for svcBreak

- src/core/hle/kernel/svc.cpp
> svc: Fix typos in sanitizing checks for MapMemory/UnmapMemory

- src/core/crypto/key_manager.cpp
- src/core/crypto/key_manager.h
- src/core/crypto/partition_data_manager.cpp
- src/core/crypto/partition_data_manager.h
Just a few minor changes that don't deserve their own PRs. Each PR should have it's own explanation detailing the changes done.
Mainly reduces the number of allocations and copies in a few areas, and makes the file handling a little better when checking for errors.
> key_manager/partition_data_manager: Minor changes

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Some style inconsistencies I found that don't deserve their own PR. Commits are self-explanatory.
> video_core: Minor style changes

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Fixes shader compilation problems in Zelda BotW.
> Implement Arrays on Tex Instruction

- src/core/hle/service/mm/mm_u.cpp
InitializeWithId needs to return an id which is a u32 which should be a non zero value
> Used better names for mm:u and fixed a bad stub

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
> Home button blocking stub

- src/core/hle/service/hid/controllers/controller_base.cpp
- src/core/hle/service/hid/controllers/controller_base.h
- src/core/hle/service/hid/controllers/debug_pad.cpp
- src/core/hle/service/hid/controllers/debug_pad.h
- src/core/hle/service/hid/controllers/gesture.cpp
- src/core/hle/service/hid/controllers/gesture.h
- src/core/hle/service/hid/controllers/keyboard.cpp
- src/core/hle/service/hid/controllers/keyboard.h
- src/core/hle/service/hid/controllers/mouse.cpp
- src/core/hle/service/hid/controllers/mouse.h
- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
- src/core/hle/service/hid/controllers/stubbed.cpp
- src/core/hle/service/hid/controllers/stubbed.h
- src/core/hle/service/hid/controllers/touchscreen.cpp
- src/core/hle/service/hid/controllers/touchscreen.h
- src/core/hle/service/hid/controllers/xpad.cpp
- src/core/hle/service/hid/controllers/xpad.h
Just a few things that slipped through the HID refactor.
> hid: Minor cleanup-related changes

- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
This is a subset of the better-hid-2 changes, this fixes input in various games which don't support dual joycons. This pr will search for the next best controller which is supported by the current game
> Added auto controller switching to supported controllers and single joycon button rotation

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This fixes mario's nose in SMO and other graphical issues.
> Fixed FSETP and FSET

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Minor clean-up related changes.
> gl_shader_decompiler: Minor changes

- src/yuzu/configuration/configure_system.cpp
- src/yuzu/configuration/configure_system.h
Minor cleanup related changes to get out of the way for a larger change I plan to follow this up with.
> configure_system: Minor cleanup-related changes

- src/video_core/engines/shader_bytecode.h
- src/video_core/engines/shader_header.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This should fix many visual issues in many games that spilled registers to local memory.
> Implemented Shader Local Memory

- src/video_core/renderer_opengl/gl_rasterizer_cache.h
Should fix the stalemate between Mipmaps PR and sRGB PR
> Implement Default Block Height for each format

- src/core/loader/nsp.cpp
Prevents nullptr bug when trying to dump the RomFS of an NSP resulting from `secondary_loader` not being initialized.
> loader/nsp: Move secondary loader initialization to constructor

- src/core/hle/service/filesystem/fsp_srv.cpp
Implements DeleteDirectory & DeleteDirectoryRecursive Commands into the Service.
With this change, Lego Worlds gets ingame.
> service/filesystem: Implemented DeleteDirectory & DeleteDirectoryRecursive

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
- src/video_core/renderer_opengl/gl_shader_gen.cpp
This improves the shader precision of some shader instructions used. Sadly because of some driver/implementation bug, Fragment shaders couldn't be improved. This fixes a ton of issues.
> Improved Shader accuracy on Vertex and Geometry Shaders.

- src/core/file_sys/fsmitm_romfsbuild.h
- src/core/hle/kernel/mutex.cpp
- src/yuzu/debugger/wait_tree.h
Cleans up unused includes and trims off some dependencies on externals.
> general: Remove unused boost inclusions where applicable

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This PR just adds asserts to Flow Instructions, making sure they don't use Control Codes. (if they do, hell)
> Assert Control Flow Instructions using Control Codes

- src/core/hle/service/nvflinger/buffer_queue.h
Fix typo in BufferTransformFlags.
> Fix typo in BufferTransformFlags

- src/yuzu/main.cpp
> Fix quickstart link

- src/audio_core/stream.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_resource_manager.cpp
- src/video_core/renderer_opengl/gl_stream_buffer.cpp
This PR introduce new microprofile scopes for hot code and delete one unused one.
> gl_rasterizer: Update microprofile scopes.

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
Add support for multiple viewports and independent blending, testing is welcome.
> Implement multi-target viewports and blending

- src/core/hle/service/acc/acc.cpp
- src/core/hle/service/acc/acc.h
- src/core/hle/service/acc/acc_su.cpp
- src/core/hle/service/acc/acc_u0.cpp
- src/core/hle/service/acc/acc_u1.cpp
Needed for Shantae - Half-Genie Hero - Ultimate Edition!
> Implement acc:TrySelectUserWithoutInteraction

- src/core/hle/service/hid/controllers/npad.cpp
> Updated npad styles on holdtype switches

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> Implement 3 coordinate array in TEXS instruction

- src/core/settings.h
- src/yuzu/configuration/configure_system.cpp
> configure_system: Fix compiler warning

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
- src/video_core/renderer_opengl/maxwell_to_gl.h
- src/video_core/textures/texture.h
Add support for anisotropic filtering, lod settings, some fixes to stencil test and some tweaks to reduce state handling redundancy.
> Map more missing opengl states

- src/core/hle/service/time/interface.cpp
- src/core/hle/service/time/time.cpp
- src/core/hle/service/time/time.h
Needed by megaman 11.
ToPosixTime & ToPosixTimeWithMyRule  is mainly used by unity games
> Implement GetClockSnapshot, ToPosixTime & ToPosixTimeWithMyRule

- src/video_core/engines/maxwell_3d.cpp
Minor code cleanup from unaddressed feedback in #1654
> engines/maxwell_3d: Minor cleanup

- src/common/string_util.cpp
- src/common/string_util.h
Removes some unnecessary/unused functions. Each commit contains the rationale for doing so.
> common/string_util: Minor cleanup

- src/core/hle/service/acc/profile_manager.cpp
- src/core/hle/service/acc/profile_manager.h
Just minor tidying changes that I noticed could be done when doing #1696
> acc/profile_manager: Minor cleanup-related changes

- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
We accidently used controller index instead of npad id
> Fixed priority switching edge case for handheld

- src/video_core/textures/decoders.cpp
> textures/decoders: Minor cleanup

- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
> gl_rasterizer_chache: Minor cleanup

- src/common/bit_field.h
See citra-emu/citra#4426 for more details.
Storing signed type causes the following behaviour: `ExtractValue` can do overflow/negative left shift. Now it only relies on two implementation-defined behaviours (which are almost always defined as we want): unsigned->signed conversion (as two's complement equivalence), and signed right shift (arithmetic shift).
> Port citra-emu/citra#4426: "Common/Bitfield: store value as unsigned type"

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
This is needed for Youtube to progress, does not yet boot though. Youtube among some other games needs CacheStorage implemented.
> am: Stub EnableApplicationCrashReport

- src/core/hle/kernel/svc.cpp
> svc: ResetSignal is not stubbed

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_manager.h
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
- src/video_core/renderer_opengl/maxwell_to_gl.h
- src/video_core/textures/texture.h
Add support for more missing functionality in glstate
> Missing ogl states

- src/video_core/textures/decoders.cpp
> textures/decoders: Replace magic numbers

- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer_cache.h
This fixes performance regressions in ARMS and Splatoon and improves loading performance in Many Games.
> Implemented Fast Layered Copy

- src/video_core/macro_interpreter.cpp
- src/video_core/macro_interpreter.h
> macro_interpreter: Implement AddWithCarry and SubtractWithBorrow.

- src/core/hle/service/audio/audout_u.cpp
- src/core/hle/service/audio/audout_u.h
> audout_u: Add support for multiple IAudioOut streams.

- src/video_core/engines/maxwell_3d.h
- src/video_core/renderer_opengl/maxwell_to_gl.h
> maxwell_3d: Implement alternate blend equations.

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Fixes Strips in Zelda and ARMS
> Properly Implemented TXQ Instruction

- src/common/thread.cpp
- src/common/thread.h
Gets rid of obsolete functions and tidies up the rest of the interface.
> common/thread: Minor cleanup

- src/yuzu/applets/software_keyboard.cpp
- src/yuzu/applets/software_keyboard.h
Minor tidying changes and also fixes a bug within the reject() function, where accept was being called when it shouldn't be.
> software_keyboard: Minor changes

- CMakeLists.txt
- src/core/gdbstub/gdbstub.cpp
GDBStub Improvements:
- Add FPU support
- Fix access to TLS
Fix clang-format.
> GDBStub Improvements

- src/video_core/engines/maxwell_3d.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
this register controls what states ( viewport, scissor ) affects the clear command
> Add support for clear_flags register

- src/yuzu/configuration/configure_input.cpp
- src/yuzu/configuration/configure_input.h
- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/configuration/configure_input_player.h
- src/yuzu/configuration/configure_mouse_advanced.cpp
- src/yuzu/configuration/configure_mouse_advanced.h
Minor cleanup and organizational changes. It also silences compiler warnings.
> yuzu/input: Minor changes

- src/core/hle/service/erpt/erpt.cpp
- src/core/hle/service/usb/usb.cpp
Keeps the function tables up to date.
> hle/service: Update function tables for erpt:c and usb's IClientEpSession

- src/core/hle/service/hid/controllers/npad.cpp
> Fixed crash with SetNpadMode

- src/core/file_sys/registered_cache.cpp
Also inverts if statements where applicable to allow unindenting code a little bit.
> file_sys/registered_cache: Eliminate variable shadowing

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
TLD4S: (textureGather) https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/textureGather.xhtml
Fix DC cases, actually is using vec3 and returning a float but should be use vec2 and return vec4
Fix DC cases refZ should be use float gr20 and not component integer from immediate
TLD4 (textureGather) 
Fix DC cases, actually is using vec3 and returning a float but should be use vec2 and return vec4
Fix DC cases refZ should be use float gr20 and not component integer from immediate
Implement all texture types reflecting teh source registers
TLDS (texelFetch) https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/texelFetch.xhtml
Fix LL cases, Lod is always in gr20 and not in gr20 + offset
FIX Coord Y when Lod is used is in gr8 + 1 and not in gr20 
Implement all texture types reflecting …
> gl_shader_decompiler: TLDS/TLD4/TLD4S Reworked reflecting the source registers, bugs fixed and modularize.

- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_opengl/gl_shader_cache.h
- src/video_core/renderer_opengl/gl_shader_gen.cpp
- src/video_core/renderer_opengl/gl_shader_gen.h
This PR does not add much functionality in its own but is vital for implementing the Disk Shader Cache and Mods that inject shaders.
> Implemented Shader Unique Identifiers

- src/core/arm/dynarmic/arm_dynarmic.cpp
References:
* [Exophere bootup](https://github.com/Atmosphere-NX/Atmosphere/blob/e0f1e637f79a6eae88178a6576a3a74a953d1929/exosphere/src/bootup.c#L328)
* [fusee hwinit](https://github.com/Atmosphere-NX/Atmosphere/blob/6e7eb47d33704b3c2fe4056d7a867eb8979b6f4f/fusee/fusee-primary/src/hwinit.c#L37)
> arm_dynarmic: Set CNTFRQ value

- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
This fixes two small issues that currently cause a large amount of GL debug spew.
The first flags RGBA16UI as a GL_RGBA_INTEGER format (as RGBA32UI already is). This was causing..
`GL_INVALID_OPERATION error generated. Texture type and format combination is not valid."`
.. during copy operations.
The second causes R16U surfaces to be created as Z16 surfaces when the depth_compare_enabled register is set. BOTW at the least was (attempting to) sample from it with a shadow sampler. This was causing
`
Program undefined behavior warning: The current GL state uses a sampler (1) that has depth comparisons enabled, with a texture object (Texture2DArray@0x000000028e286200) with a non-depth format, by a shader that samples it with a shadow sampler. This will result in undefined behavior.`
No …
> Texture format fixes for RGBA16UI for copies and R16U when used as depth

- src/core/frontend/framebuffer_layout.cpp
- src/core/frontend/framebuffer_layout.h
- src/video_core/renderer_base.cpp
- src/video_core/renderer_base.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/video_core/renderer_opengl/renderer_opengl.h
- src/video_core/video_core.cpp
- src/video_core/video_core.h
- src/yuzu/bootmanager.cpp
- src/yuzu/bootmanager.h
- src/yuzu/configuration/config.cpp
- src/yuzu/main.cpp
- src/yuzu/main.h
- src/yuzu/main.ui
- src/yuzu/ui_settings.h
See citra-emu/citra#4164 for more details.
Because some stuff is different in yuzu, I needed to make some changes to the PR in order for it to work here. So please pay close attention while reviewing.
> Port citra-emu/citra#4164: "citra_qt, video_core: Screenshot functionality"

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> Fixed shader linking error due to TLDS

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Originally intended this pull to add support for the rest of the Control flags but I will keep every flag on a separate pull.
This pull improve and centralize the set process of the zero flag
> Improve Zero flag implementation

- src/core/arm/arm_interface.cpp
- src/core/arm/arm_interface.h
Minor cleanup to arm_interface. Also gets rid of a -Wextra-semi warning.
> arm_interface: Minor cleanup

- src/core/hle/kernel/object.h
- src/core/hle/kernel/readable_event.cpp
- src/core/hle/kernel/timer.cpp
- src/yuzu/debugger/wait_tree.cpp
Pulse is considered a hack and nothing should be using it. We should completely remove it
> Removed pulse event type

- src/core/hle/service/am/am.cpp
When we have no messages, we should be returning an error code.
> Proper no message handling for AM::PopMessage

- src/core/hle/service/nfp/nfp.cpp
This will prompt CreateApplicationArea
> Return no application area when games try to open an application area

- src/audio_core/time_stretch.cpp
> audio_core: remove unnecessary spaces on comments

- .github/ISSUE_TEMPLATE.md
I made this PR in order to get more people to use the forum for their (end-user) problems and to make more clear what's required for a proper issue report.
This is almost a 100% port of Citras template, except for the log part.
~~Let the bikeshedding begin!~~
> ISSUE_TEMPLATE: changes to make it more expressive and prevent low-quality issues

- src/video_core/shader/decode.cpp
- src/video_core/shader/shader_ir.h
Just a few minor changes that resolve some compilation warnings (-Wpessimizing-move and -Wreorder) and fixes three comment typos. Fairly trivial stuff.
> video_core/shader: Minor changes

- src/video_core/gpu.cpp
- src/video_core/gpu.h
Implemented some of the GPU methods that execute directly on the PFIFO puller.  
Methods implemented are:
- 0x0010 | SEMAPHORE_ADDRESS_HIGH | New-style semaphore address high part
- 0x0014 | SEMAPHORE_ADDRESS_LOW | New-style semaphore address low part
- 0x0018 | SEMAPHORE_SEQUENCE        | New-style semaphore payload
- 0x001c | SEMAPHORE_TRIGGER            | New-style semaphore trigger
- 0x0050 | REF_CNT                                  | Writes the ref counter
Feedback and comments are appreciative since this my first PR with YUZU.
> video_core/GPU   Implemented the GPU PFIFO puller semaphore operations.

- src/video_core/engines/shader_bytecode.h
- src/video_core/shader/decode/memory.cpp
> Fix TXQ not using the component mask.

- src/core/gdbstub/gdbstub.cpp
See citra-emu/citra#4603 for more details and reasoning.
> Port citra-emu/citra#4603: "gdbstub: only let Execute breakpoints write/restore BKPT opcodes into target memory"

- src/core/hle/service/vi/vi.cpp
Amends it to add the 7.0.0+ CreateStrayLayer function entry.
> service/vi: Update IManagerDisplayService's function table

- src/video_core/CMakeLists.txt
- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
- src/video_core/renderer_vulkan/vk_buffer_cache.h
This buffer cache is just like OpenGL's with some minor style changes. It uses VKStreamBuffer.
> vk_buffer_cache: Implement a buffer cache

- README.md
Yuzu can now render 3D graphics to some degree.
> Yuzu can render 3D.

- src/yuzu/main.cpp
See citra-emu/citra#4647 for all the reasoning and discussion on this.
> Port citra-emu/citra#4647: "citra_qt/main: make SPEED_LIMIT_STEP static constexpr"

- src/yuzu/main.cpp
not much to explain here. Key is F10.
> yuzu: add a hotkey to switch between undocked and docked mode

- src/video_core/renderer_opengl/gl_rasterizer.cpp
Reduces the severity of some logs/assertions.
> gl_rasterizer: Minor logger changes

- src/video_core/textures/texture.h
Fix regression introduced in #2215.
> video_core/texture: Fix up sampler lod bias

- src/input_common/sdl/sdl_impl.cpp
Just a tiny bit of tidying up.
> input_common/sdl_impl: Minor cleanup in SDLState constructor

- src/yuzu_cmd/yuzu.cpp
See citra-emu/citra#4697 for more details.
> Port citra-emu/citra#4697: "Fix getopt on systems where char is unsigned by default"

- src/core/hle/service/audio/hwopus.cpp
After doing a little more reading up on the Opus codec, it turns out that the multistream API that is part of libopus can handle regular packets. Regular packets are just a degenerate case of multistream Opus packets, and all that's necessary is to pass the number of streams as 1 and provide a basic channel mapping, then everything works fine for that case.
This allows us to get rid of the need to use both APIs in the future when implementing multistream variants in a follow-up PR, greatly simplifying the code that needs to be written.
> hwopus: Leverage multistream API for decoding regular Opus packets

- src/core/hle/kernel/thread.cpp
Fixes the crash caused by #2238
> Fix crash caused by #2238.

- src/core/file_sys/content_archive.h
- src/core/file_sys/registered_cache.cpp
Gives it a better name. While we're at it, give each entry some documentation.
> file_sys/content_archive: Amend name of Data_Unknown5 enum entry

- src/core/file_sys/patch_manager.cpp
- src/core/loader/nso.cpp
- src/core/loader/nso.h
Minor refactoring/relocating of NSO-related code to get the busywork out of the way. I plan to make further changes to the loading code in a follow-up PR to be more correct, however I figured I'd PR all of the unimportant changes first to get them out of the way.
> loader/nso: Minor refactoring

- src/video_core/CMakeLists.txt
- src/video_core/renderer_vulkan/vk_swapchain.cpp
- src/video_core/renderer_vulkan/vk_swapchain.h
Abstracts swapchain management into a class. It can handle both SDL2 windows and Qt `QWindow`s.
> vk_swapchain: Implement a swapchain manager

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
This just implements the register, we still need to implement the appropriate services.
> Implement SyncPoint Register in the GPU.

- src/video_core/gpu.cpp
- src/video_core/memory_manager.cpp
- src/video_core/memory_manager.h
- Fixes graphical issues with Chocobo's Mystery Dungeon EVERY BUDDY!
- Fixes a crash with Mario Tennis Aces
> memory_manager: Improved implementation of read/write/copy block.

- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_general.cpp
- src/yuzu/game_list.cpp
- src/yuzu/main.cpp
- src/yuzu/ui_settings.h
Just a trivial renaming for better legibility
> ui_settings: Rename game directory variables

- src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
This corrects textures in Undertale.
> Correct Pitch in Fermi2D

- src/video_core/shader/decode/texture.cpp
- src/video_core/shader/shader_ir.h
Miscellaneous fixes that don't deserve their own PR. Description in the commit title.
> shader_ir: Miscellaneous fixes

- .travis.yml
Keeps the CI toolchain updated. This is also necessary for updating dynarmic.
> travis: Update to using Xcode 10.2

- src/core/telemetry_session.cpp
- src/core/telemetry_session.h
See citra-emu/citra#4749 for more details.
> Port citra-emu/citra#4749: "web_service: Misc fixes"

- src/core/hle/service/set/set.cpp
This corrects cases where it was possible to write more entries into the write buffer than were requested. Now, we check the size of the buffer before actually writing into them.
We were also returning the wrong value for GetAvailableLanguageCodeCount2(). This was previously returning 64, but only 17 should have been returned. 64 entries is the size of the static array used in MakeLanguageCode() within the service binary itself, but isn't the actual total number of language codes present.
> service/set: Correct and simplify behavior related to copying language codes

- src/video_core/renderer_opengl/gl_device.cpp
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_opengl/gl_shader_gen.cpp
> gl_shader_gen: Always declare extensions after the version declaration 

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
- src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
- src/video_core/shader/decode/other.cpp
- src/video_core/shader/shader_ir.h
These map to `gl_LocalInvocationID` and `gl_WorkGroupID` respectively.
>  shader: Implement S2R Tid{XYZ} and CtaId{XYZ} 

- src/yuzu/configuration/configure_system.cpp
- src/yuzu/configuration/configure_system.h
- src/yuzu/configuration/configure_system.ui
> yuzu: Remove unused birthday setting

- src/yuzu/configuration/configure_audio.ui
- src/yuzu/configuration/configure_debug.ui
- src/yuzu/configuration/configure_input.ui
Commit title is self explanatory.
> qt: Silence name collision warnings

- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_opengl/gl_shader_cache.h
Commit titles explain the individual changes.
> gl_shader_cache: Minor style changes

- src/core/file_sys/nca_metadata.h
Names a few more entries in relevant structures. Information based off SwitchBrew and my own RE.
> file_sys/nca_metadata: Update CNMT structures

- src/core/file_sys/card_image.cpp
Just performs a minor readability/deduplication cleanup
> file_sys/card_image: Minor cleanup

- .travis/linux-mingw/build.sh
- CMakeLists.txt
Reverts yuzu-emu/yuzu#2474.
As no one has shown interest in fixing https://github.com/yuzu-emu/yuzu/issues/2610, and it was caused by this PR, I think reverting is the best option for now. 
cc @FreddyFunk
> Revert "CMake: Get Git submodule dependencies via CMake"

- src/core/CMakeLists.txt
- src/core/hle/service/friend/errors.h
- src/core/hle/service/friend/friend.cpp
- src/core/hle/service/friend/friend.h
- src/core/hle/service/friend/interface.cpp
Pseudocode from RE below
```cpp
ResultCode GetEvent(INotificationService *this, unsigned int *event) {
if(this->is_event_created) {
*event = this->event;
} else {
if(CreateSystemEvent(&this->event, MANUAL_CLEAR)) {
Abort();
return;
}
*event = this->event;
}
return 0;
}
```
```cpp
ResultCode Clear(INotificationService *this) {
// Queue handled internally
this->notification_count = 0;
this->has_friend_request_sent = 0;
return 0;
}
```
```cpp
ResultCode Pop(INotificationService *this, SizedNotificationInfo *out_info) {
if(!this->notification_count) {
return 0x1E79;
}
auto notification = this->notification_queue->front();
this->notification_queue->pop();
*out_info = noitifcation;
if(out_info->type == 0x65) {
this->has_friends_list_updated = 0;
} else if(out_info->type == 0x1) { …
```
> Implemented INotificationService

- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_opengl/gl_shader_cache.h
This unifies `CachedShader` constructors into a single method. The two previous constructors had different meanings depending on the arguments that were being passed, this commit addresses that using static public initializers with descriptive names instead.
Shader arguments are now packed into a structure.
> gl_shader_cache: Use static constructors for CachedShader initialization 

- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_opengl/gl_shader_cache.h
Adds missing review comments introduced by my merge of #2563
> gl_shader_cache: Make CachedShader constructor private

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
Tick increment on unsuspension at am.text + 92508 in 8.1.0.
> am: Implement GetAccumulatedSuspendedTickValue

- src/core/reporter.cpp
- src/core/reporter.h
Performs minor clean-up/correctness-related changes, some preventing potential compilation issues in the future.
> core/reporter: Minor changes

- .ci/templates/build-single.yml
- .ci/templates/build-testing.yml
- README.md
> Fix README change mistake

- src/video_core/shader/control_flow.cpp
- src/video_core/shader/control_flow.h
- src/video_core/shader/decode.cpp
- src/video_core/texture_cache/surface_base.cpp
Provides a few minor cleanup-related changes that reduce the amount of work done in some scenarios. They also resolve some compilation warnings that would occur. Each commit should be fairly separated, making reviewing them in isolation possible.
> video_core/control_flow: Minor changes/warning cleanup

- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_input.cpp
- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/configuration/configure_input_simple.cpp
- src/yuzu/configuration/configure_mouse_advanced.cpp
- src/yuzu/configuration/configure_profile_manager.cpp
- src/yuzu/configuration/configure_touchscreen_advanced.cpp
Please see citra-emu/citra#4849 for more details.
> Port citra-emu/citra#4849: "Qt: Fixed behaviour of buttons by connecting functors to correct signals"

- src/yuzu/discord_impl.cpp
When renaming all ui_settings -> uisettings, it seems we missed this one
> Fixup! #2772 missed this one file

- src/video_core/engines/shader_bytecode.h
- src/video_core/shader/decode/conversion.cpp
Implements F2I's selector and changes asserts to work with float conversion variants too.
> shader_ir/conversion: Implement F2I and F2F F16 selector

- src/core/hle/service/audio/audren_u.cpp
> service/audio/audren_u: Stub IAudioDevice::GetAudioDeviceOutputVolume

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
This function used in new games, line **Wolfenstein Youngblood**
> AM: Stub IApplicationFunctions::GetGpuErrorDetectedSystemEvent

- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
> hid: Implement PermitVibration and IsVibrationPermitted

- src/video_core/shader/decode/half_set_predicate.cpp
Predicate assignments were wrong (again).
> half_set_predicate: Fix HSETP2 predicate assignments

- src/video_core/renderer_opengl/gl_rasterizer.cpp
* Fix stencil dirty flags tracking when stencil is disabled
* Attach stencil on clears (previously it only attached depth)
* Attach stencil on drawing regardless of stencil testing being enabled
This fixes Puyo Puyo Tetris and Cadence of Hyrule
> gl_rasterizer: Fix stencil testing

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
- src/video_core/macro_interpreter.cpp
> Revert "Revert #2466" and stub FirmwareCall 4

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Avoids emitting invalid GLSL when something an output attribute is unimplemented.
> gl_shader_decompiler: Avoid writing output attribute when unimplemented

- src/yuzu/main.cpp
Check https://github.com/citra-emu/citra/pull/4944 and https://github.com/citra-emu/citra/pull/4931 for more details on the original implementation.
> Port citra-emu/citra#4944: "Added Host CPU and OS to log"

- src/core/hle/service/acc/acc.cpp
According to @ogniK5377, this should have always been Debug and not Info.
> service/acc: Lower log severity from INFO to DEBUG

- src/yuzu/configuration/configure_general.cpp
Adds a missing include in configure_general.cpp.
> Add missing include

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This commit tries to address #2863
> gl_shader_decompiler: Fix clang build issues

- src/core/arm/dynarmic/arm_dynarmic.cpp
> Revert "arm_dynarmic: Check if jit is nullptr when preparing reschedule"

- .ci/scripts/merge/apply-patches-by-label-private.py
- .ci/scripts/merge/apply-patches-by-label.py
- .ci/templates/mergebot-private.yml
At request of @bunnei , this makes the mergebot search for patreon PRs on both Azure and GitHub, allowing us to add PRs to patreon without requiring the person to be a core contributor.
> ci: Merge patreon tagged PRs from public repository during merge step.

- src/core/hle/service/hid/controllers/npad.cpp
We should signal when a net controller is added and our event should be manual, not automatic. This is a minor fix for pokemon lets go, however more work still needs to be done
> Signal styleset changes at a better time

- .ci/scripts/merge/apply-patches-by-label-private.py
- .ci/scripts/merge/apply-patches-by-label.py
This fixes a bug where mainline PRs on the 2nd page won't get merged.
> ci: Iterate through GitHub pages for pull requests

- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
This fixes linux and mingw builds.
> SDL: Fix missing header

- src/core/hle/service/es/es.cpp
Some minor compiler warning fixed
> Services::ES fix casting warnings

- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_general.cpp
- src/yuzu/configuration/configure_general.ui
- src/yuzu/main.cpp
- src/yuzu/main.h
- src/yuzu/uisettings.h
See citra-emu/citra#4930 for more details.
> Port citra-emu/citra#4930: "Pause when in background"

- src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
These parameters aren't actually modified in any way, so they can be made const references. Keeps the Vulkan decompilers in sync with the signatures of the OpenGL analogues.
> vk_shader_decompiler: Mark operator() function parameters as const references

- src/core/core.cpp
Add null pointer check to fix crash described here #2996.
> Fix null pointer dereference.

- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
Tidies up the code a little bit and also fixes a bug within `ConnectAllDisconnectedControllers()` where it wouldn't actually signify the controllers as connected.
> hid/npad: Minor cleanup

- src/video_core/shader/decode/arithmetic_integer.cpp
- src/video_core/shader/decode/image.cpp
- src/video_core/shader/decode/other.cpp
- src/video_core/shader/decode/shift.cpp
- src/video_core/shader/decode/video.cpp
- src/video_core/shader/decode/warp.cpp
Silences a few -Wshadow warnings.
> video_core/shader: Resolve instances of variable shadowing

- src/core/file_sys/savedata_factory.cpp
After further hardware investigation, it appears that some games, perhaps those more lazily coded, will not call EnsureSaveData, meaning that they expect the normal (current) save to be automatically made. Additionally, some games do not create a cache or temporary save before use.
In these 3 specific instances, the save is created automatically for the game if it doesn't exist.
> savedata_factory: Automatically create certain savedata

- src/core/hle/kernel/scheduler.cpp
- src/core/hle/kernel/scheduler.h
Mostly resolves warnings and tidies up documentation comments.
> kernel/scheduler: Minor changes

- src/yuzu/main.cpp
- src/yuzu/main.h
See citra-emu/citra#4948 for more details.
> Port citra-emu/citra#4948: "citra_qt: add amiibo drag and drop support"

- .ci/scripts/linux/docker.sh
- .gitmodules
- externals/CMakeLists.txt
- externals/libzip/CMakeLists.txt
- externals/zlib/CMakeLists.txt
We can supply our own CMakeLists.txt file like with Opus to avoid needing to special-case the tests in CTest execution. This also requires that we track upstream libzip instead of a fork (what we should have been doing in the first place), since it was hardcoding pathing information within the source tree, which we should avoid doing.
Now, libzip can also be easily updated without us needing to manually update files within a fork, since none of them are directly touched now.
Note that the handling of zlib is still less than ideal, however I'd like to actually get CMake configurations all centralized in the repository first before making further changes to it.
> externals: Remove special casing of zlib's tests.

- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/object.h
- src/core/hle/kernel/readable_event.cpp
- src/core/hle/kernel/readable_event.h
- src/core/hle/kernel/svc.cpp
- src/core/hle/kernel/writable_event.cpp
- src/core/hle/kernel/writable_event.h
- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/applets/applets.cpp
- src/core/hle/service/aoc/aoc_u.cpp
- src/core/hle/service/audio/audout_u.cpp
- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/bcat/backend/backend.cpp
- src/core/hle/service/btdrv/btdrv.cpp
- src/core/hle/service/btm/btm.cpp
- src/core/hle/service/friend/friend.cpp
- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/nfp/nfp.cpp
- src/core/hle/service/nifm/nifm.cpp
- src/core/hle/service/nim/nim.cpp
- src/core/hle/service/nvdrv/nvdrv.cpp
- src/core/hle/service/nvflinger/buffer_queue.cpp
- src/core/hle/service/vi/display/vi_display.cpp
- src/yuzu/debugger/wait_tree.cpp
- src/yuzu/debugger/wait_tree.h
* Initialize members
* Only signal if not signaled
* Remove ResetType::Automatic -- this appears to be an SDK construct, not kernel behavior
> kernel: Improve events

- .ci/scripts/common/post-upload.sh
- .ci/scripts/linux/upload.sh
- .ci/scripts/windows/upload.ps1
- .ci/scripts/windows/upload.sh
- .ci/templates/build-msvc.yml
> Revert "ci: Rename build folder only on non-mainline builds"

- src/video_core/shader/control_flow.cpp
Remove copied and pasted for cycles into a common templated function and minor style changes.
> shader/control_flow: Abstract repeated code chunks in BRX tracking

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
Needed to boot some newer games (SDK >= ~7.x).
> Implement stub for IApplicationFunctions::QueryApplicationPlayStatisticsByUid

- src/core/hle/kernel/client_session.cpp
- src/core/hle/kernel/server_session.cpp
- src/core/hle/kernel/session.h
- Fixes shutdown crash and crash in Pokemon SwSh.
> kernel: Fix reference management for client/server session.

- .ci/scripts/windows/upload.ps1
> Add missing CMakeLists.txt from root folder to source upload

- src/video_core/renderer_vulkan/declarations.h
- src/video_core/renderer_vulkan/vk_device.cpp
Updates Vulkan-Headers but not to the latest version, since that one introduces regressions I haven't debugged yet.
> externals: Update Vulkan-Headers

- src/video_core/engines/maxwell_3d.h
Adds tessellation state properties to Maxwell 3D registers.
> maxwell_3d: Add tessellation state entries

- src/video_core/renderer_vulkan/vk_device.cpp
- src/video_core/renderer_vulkan/vk_device.h
- Setup more features and requirements.
- Improve logging for missing features.
- Collect telemetry parameters.
- Add queries for more image formats.
- Query push constants limits.
- Optionally enable some extensions.
> vk_device: Misc changes

- src/video_core/engines/maxwell_3d.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_state.cpp
- src/video_core/renderer_opengl/gl_state.h
This commit finishes adding depth mode that was reverted before due to other unresolved issues.
> Maxwell3D: Implement Depth Mode.

- src/video_core/renderer_vulkan/maxwell_to_vk.cpp
- src/video_core/renderer_vulkan/maxwell_to_vk.h
- src/video_core/renderer_vulkan/vk_sampler_cache.cpp
Updates `maxwell_to_vk`. Description about the changes is in individual commits.
> maxwell_to_vk: Use VK_EXT_index_type_uint8 and misc changes

- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/video_core/renderer_opengl/renderer_opengl.h
Miscellaneous changes, description in individual commit titles. As a major change, it now takes advantage of GLSL 4.3 features.
> renderer_opengl: Miscellaneous clean ups

- src/video_core/shader/decode/conversion.cpp
I2F's byte selector is used to choose what bytes to convert to float.
e.g. If the input is `0xaabbccdd` and the selector is ".B3" it will convert 0xaa. The default (when it's not shown in `nvdisasm`) is ".B0", in that example the default would convert 0xdd to float.
> shader/conversion: Implement byte selector in I2F

- src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
- src/video_core/renderer_vulkan/vk_shader_decompiler.h
Description about the changes in the individual commits.
> vk_shader_decompiler: Misc changes

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
- src/video_core/shader/decode/texture.cpp
- src/video_core/shader/node.h
- src/video_core/shader/shader_ir.h
Implements for GLSL textureGatherOffset and textureGatherOffsets backend instructions.
>  shader/texture: Implement AOFFI and PTP for TLD4 and TLD4S

- src/core/hle/service/nvflinger/nvflinger.cpp
- src/core/hle/service/nvflinger/nvflinger.h
- src/core/hle/service/vi/display/vi_display.cpp
- src/core/hle/service/vi/display/vi_display.h
- src/core/hle/service/vi/vi.cpp
- Needed for Undertale.
Fixes #3272
> service: vi: Implement CloseLayer.

- src/video_core/shader/decode/texture.cpp
Avoid abusing lambdas for no valid reason.
> shader_ir/texture: Simplify AOFFI code

- CMakeModules/GenerateSCMRev.cmake
- src/common/CMakeLists.txt
Should fix `GIT-NOTFOUND` for people that have that in the title bar
> Fix git version in scm_rev.cpp

- src/yuzu/main.ui
Fixes https://github.com/yuzu-emu/yuzu/issues/1898.
> Add headbar icon on Linux

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Use Visit instead of reimplementing it. Fixes unimplemented negations for condition codes.
> gl_shader_decompiler: Fix decompilation of condition codes

- src/core/hle/service/time/time_zone_manager.cpp
- src/core/hle/service/time/time_zone_manager.h
- src/core/hle/service/time/time_zone_service.cpp
- src/core/hle/service/time/time_zone_service.h
- Used by Pokemon Mystery Dungeon.
> service: time: Implement ToPosixTimeWithMyRule.

- src/video_core/renderer_opengl/gl_texture_cache.cpp
This addresses the long standing issue of compatibility vs. core
profiles on OpenGL, properly implementing depth vs. stencil sampling
depending on the texture swizzle.
> gl_texture_cache: Properly implement depth/stencil sampling

- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/configuration/configure_input_player.h
- src/yuzu/configuration/configure_input_player.ui
> GUI: Deadzone controls for sdl engine at configuration input

- dist/qt_themes/colorful/style.qrc
- dist/qt_themes/colorful/style.qss
- dist/qt_themes/default/default.qrc
- dist/qt_themes/default/style.qss
- dist/qt_themes/qdarkstyle/style.qss
- src/yuzu/main.cpp
- src/yuzu/main.h
See https://github.com/yuzu-emu/yuzu/pull/3251 for reference.
> GUI: Togglable graphics settings buttons in status bar

- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/service/prepo/prepo.cpp
Fixes a crash in SMO (and other games) which was only hit in debug mode. This was due to a bad IPC interface. Adds better error checking to hopefully prevent this kind of thing in the future.
> hle: services: Fix prepo IPC, and add better error checking.

- src/video_core/renderer_opengl/maxwell_to_gl.h
Fixes grass in The Legend of Zelda: Breath of the Wild.
> maxwell_to_gl: Implement R8G8_USCALED

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
- src/video_core/gpu.cpp
- src/video_core/gpu.h
This PR is based on a series of findings by fincs on his project to build an NVN-like API for homebrew. Special thanks to him.
This PR aims to more accurately address queries and time in the GPU.
> GPU: Refactor queries implementation and correct GPU Clock.

- src/core/hle/service/audio/hwopus.cpp
trivial change,
see https://switchbrew.org/wiki/Audio_services#IHardwareOpusDecoder
> update hwopus DecodeInterleaved for FW 7.0.0+

- src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_gpu.h
Used by Pokemon Sword.
Issue: #3118
> nvhost_gpu: implement ChannelSetTimeslice

- src/video_core/shader/decode/conversion.cpp
Used for Kirby Star Allies
Issue: #3289. This is last piece to get this game work with Vulkan.
Thanks @ReinUsesLisp for help.
> shader_conversion: add conversion I2F for Short

- src/video_core/renderer_opengl/gl_rasterizer.cpp
This may help some OpenGL implementations.
> gl_rasterizer: Use the least generic OpenGL draw function possible

- src/video_core/memory_manager.cpp
`Invalidate` (on memory write) and `FlushAndInvalidate` (on unmap memory) can be asynchronous.
This replaces #3386, which needed to be reverted due to a regression with Dead Cells (because the `Flush` still needs to be synchronous).
Results in a minor performance improvement, as measured by @Morph1984 .
> video_core: memory_manager: Flush/invalidate asynchronously when possible.

- src/video_core/renderer_vulkan/maxwell_to_vk.cpp
- src/video_core/renderer_vulkan/vk_device.cpp
Used by Kirby Star Allies
Issue: #3289
> vulkan: add DXT23_SRGB

- src/video_core/renderer_vulkan/vk_device.cpp
- src/video_core/renderer_vulkan/vk_device.h
- src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
Used by Kirby Star Allies.
Issue: #3289 
Thanks @ReinUsesLisp for helping me out.
> vk_shader: Implement ImageLoad

- src/video_core/renderer_vulkan/vk_sampler_cache.cpp
Follow this implement on RPCS3: https://github.com/RPCS3/rpcs3/blob/90f4023cb8682ed6d5ca2feab4c91c5024697f0c/rpcs3/Emu/RSX/VK/VKFormats.cpp#L101
> renderer_vulkan: Add the rest of case for TryConvertBorderColor

- src/video_core/engines/shader_bytecode.h
- src/video_core/shader/decode/arithmetic.cpp
> shader: FMUL switch to using LUT

- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/video_core/renderer_opengl/renderer_opengl.h
- Fixes SRGB in Super Smash Bros. Ultimate.
> renderer_opengl: Fix SRGB presentation frame tracking.

- src/input_common/udp/client.cpp
- src/input_common/udp/protocol.cpp
- src/yuzu_cmd/default_ini.h
Check each commit for more details.
> Minor fixes for udp input

- src/audio_core/cubeb_sink.cpp
Previously, when performing downmixing, we would discard all channels except the left and right one.
This implementation respects them when mixing down to Stereo.
It is taken from this document: http://www.atsc.org/wp-content/uploads/2015/03/A52-201212-17.pdf.
Fixes Luigis Mansion 3 cutscene and Bayonetta audio + Sonic Forces audio.
[**Before**](https://streamable.com/o5a3k) and [**After**](https://streamable.com/uf5f6) (thanks to @slashiee).
> cubeb_sink: Don't discard other channels when performing downmixing

- externals/microprofile/microprofile.h
- src/core/hle/service/nvflinger/nvflinger.cpp
This adds the ability to access tokens directly and makes flipping microprofile after a fence instead of before.
> Small corrections and features to microprofile

- src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
> vk_shader_decompiler: fix linux build

- src/video_core/renderer_vulkan/maxwell_to_vk.cpp
> maxwell_to_vk: add vertex format eA2B10G10R10UnormPack32

- src/input_common/udp/udp.cpp
- src/video_core/textures/astc.cpp
Fixes build issues signaled by clang.
> astc/input_common: Fix clang build issues

- externals/microprofile/microprofile.h
- src/video_core/engines/kepler_compute.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
- src/video_core/renderer_vulkan/maxwell_to_vk.cpp
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
Silence warnings signaled by gcc that don't deserve their own pull request.
> video_core: Silence misc warnings

- src/video_core/shader/decode/xmad.cpp
Follow this:
```c++
if (p_a==0 || p_b==0) break;
//v & 0x80000000 -> as_twos_complement(v) < 0
if (p_a & 0x80000000) c -= 65536;
if (p_b & 0x80000000) c -= 65536;
```
ref: [link](https://envytools.readthedocs.io/en/latest/hw/graph/maxwell/cuda/int.html)
> shader_decode: implement XMAD mode CSfu

- src/core/hle/service/set/set.cpp
- src/core/hle/service/set/set.h
- src/core/settings.cpp
- src/core/settings.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_system.cpp
- src/yuzu/configuration/configure_system.h
- src/yuzu/configuration/configure_system.ui
following https://switchbrew.org/wiki/Settings_services#RegionCode
> set: implement GetRegionCode

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
- src/video_core/macro_interpreter.cpp
This implemented based on #3529. I hope it working ok
Thank @fincs to explain it to me again.
Screenshot from @BSoDGamingYT
> Implement MME shadow RAM

- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
- src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
- src/video_core/shader/decode/memory.cpp
- src/video_core/shader/node.h
- src/video_core/shader/node_helper.cpp
This PR implements all operations for ATOM/ATOMS but `Increment `and `Decrement`.
for now, it only supports S32 and U32 type.
Note: still have some issue with OpenGL
> shader_decode: Implement partial ATOM/ATOMS instr

- src/video_core/shader/decode/arithmetic_integer.cpp
`op_b` and `op_c` had their meanings flipped. Fix that and simplify the generated code.
>  shader/lea: Fix LEA implementation

- src/video_core/renderer_vulkan/wrapper.cpp
- src/video_core/renderer_vulkan/wrapper.h
Continues #3566.
Nothing special to highlight, it adds the missing wrappers.
> renderer_vulkan/wrapper: Add a Vulkan wrapper (part 2 of 2)

- src/yuzu/configuration/configure_input_player.ui
Previous:
New:
Also reorder them in the code to look a bit nicer.
> configuration: Reorder shoulder buttons

- src/common/file_util.cpp
- src/common/thread.cpp
See citra-emu/citra#5127 for more details and the list of commits.
Ports parts of dolphin-emu/dolphin#5572, dolphin-emu/dolphin#4611 and dolphin-emu/dolphin#5632
Mostly fixes a few warnings.
> Port citra-emu/citra#5127: "common: Port some changes from dolphin"

- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/configuration/configure_input_simple.cpp
- src/yuzu/configuration/configure_mouse_advanced.cpp
I'm fucking done with my life after debugging this for way too long.
Change explanation is in the commits.
> yuzu/configuration: Fix input profiles and a wrong assert

- src/video_core/engines/shader_bytecode.h
- src/video_core/shader/decode/arithmetic.cpp
> shader/arithmetic: Add FCMP_CR variant

- src/video_core/renderer_vulkan/vk_memory_manager.h
- src/video_core/texture_cache/texture_cache.h
Fixes broken documentation references.
> video_core: Amend doxygen comment references

- src/video_core/renderer_opengl/maxwell_to_gl.h
Since yesterday, this breaks the build on linux.
So let's fix it.
> video_code: Fix implicit switch fallthrough.

- src/core/hle/service/time/standard_network_system_clock_core.h
- src/core/hle/service/time/steady_clock_core.h
- src/core/hle/service/time/system_clock_context_update_callback.h
- src/core/hle/service/time/system_clock_core.cpp
- src/core/hle/service/time/system_clock_core.h
Makes a few minor changes to the time service, which is mostly just aimed at resolving warnings/etc. Each commit should be self-explanatory.
> service/time: Minor changes

- src/video_core/renderer_vulkan/renderer_vulkan.cpp
> Unbreak Vulkan on FreeBSD

- src/core/arm/unicorn/arm_unicorn.cpp
Turns out, Unicorn fallbacks have been broken for a very long time due to https://github.com/yuzu-emu/yuzu/commit/70624e1c1d16c2ff3b786ec56ec550f699065741. This is because even if an instruction is not a load/store, we still need to map the code memory for Unicorn to execute the instruction.
As a workaround, we now will temporarily map the code page (and then unmap it) on Unicorn fallback. This is SLOW. But useful for debugging. Fortunately, since Dynarmic is quite complete, this should basically never be hit for end users.
> core: arm_unicorn: Fix interpret fallback by temporarily mapping instruction page.

- src/core/hle/service/time/time.cpp
Eliminates usages of the global system accessor and instead passes the existing system instance into the interfaces.
Only five usages of the global system instance remain within the HLE code after this.
> service/time: Remove reliance on the global system accessor

- src/core/hle/kernel/memory/memory_block.h
- src/core/hle/kernel/memory/memory_block_manager.cpp
- src/core/hle/kernel/memory/memory_block_manager.h
- src/core/hle/kernel/memory/page_table.cpp
- src/core/hle/kernel/memory/page_table.h
- src/video_core/memory_manager.cpp
Addresses some TODOs that were added with #3666. For a proper fix, we need device_use_count to be implemented.
> kernel: memory: Improve implementation of device shared memory.

- src/yuzu/configuration/configure_filesystem.cpp
> frontend/filesystem: Add a trailing separator to the string path

- src/common/bit_field.h
- src/video_core/engines/shader_bytecode.h
- src/video_core/renderer_vulkan/fixed_pipeline_state.h
> Fix -Werror=conversion and -Wdeprecated-copy issues

- src/yuzu/game_list_p.h
> Fix "Port citra-emu/citra#4956: "Fixes to game list sorting" #3611"

- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
- Used by The Legend of Zelda: Breath of the Wild v1.6.0
> services: hid: Stub StopSevenSixAxisSensor.

- src/core/hle/service/nim/nim.cpp
> nim: CreateServerInterface, CreateAccessorInterface, CreateAsyncInterface

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
> am: GetFriendInvitationStorageChannelEvent

- src/core/hle/service/acc/acc.cpp
- src/core/hle/service/acc/acc.h
- src/core/hle/service/acc/acc_su.cpp
- src/core/hle/service/acc/acc_u0.cpp
- src/core/hle/service/acc/acc_u1.cpp
Closes #2844
supersedes #3549 as it doesn't have all the interfaces
> account: ListQualifiedUsers

- src/core/hle/service/caps/caps_su.cpp
- src/core/hle/service/caps/caps_su.h
This includes ogniK5377's commit in #3831 (properly merged - yay git).
> Add stub for caps:su SetShimLibraryVersion

- src/video_core/fence_manager.h
Regressed by #3677. See [error log](https://github.com/yuzu-emu/yuzu/files/4566616/yuzu-qt5-s20200501.log).
> Unbreak build with Clang < 10

- src/core/hle/kernel/handle_table.cpp
- src/core/hle/kernel/mutex.cpp
- src/core/hle/kernel/process_capability.cpp
- src/core/hle/kernel/readable_event.cpp
- src/core/hle/kernel/resource_limit.cpp
- src/core/hle/kernel/svc.cpp
- src/core/hle/kernel/thread.cpp
> kernel: Don't fail silently

- src/core/hle/service/audio/audin_u.cpp
- src/core/hle/service/audio/audin_u.h
> audin:u: ListAudioIns, OpenAudioIn, ListAudioInsAuto, OpenAudioInAuto, ListAudioInsAutoFiltered, OpenAudioInProtocolSpecified

- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
Needed for Puchikon 4 SmileBASIC 1.0.0
> Stub hid:SendKeyboardLockKeyEvent

- src/yuzu/bootmanager.cpp
We can't track the current state of the underlying context in this wrapper class because
Qt may make the underlying context not current for one reason or another. In particular,
the WebBrowser uses GL, so it seems to conflict if we aren't careful.
Instead of always just making the context current (which does not have any caching to
check if the underlying context is already current) we can check for the current context
in the thread local data by calling `currentContext()` and checking if its ours.
Fixes issue where closing web applets breaks the presentation.
> Frontend: Remove tracking for context wrapper

- src/core/file_sys/system_archive/system_version.cpp
Was last updated for version 5.1.0
> file_sys: Update SystemVersion archive to version 10.0.2

- src/yuzu/discord_impl.cpp
We lost access to the old application on Discord and therefore had to make a new one.
Please let me verify this works in early-access before merging.
> yuzu/discord_impl: Update the applicationID

- src/video_core/engines/maxwell_3d.cpp
Silence errors/asserts about invalid registers. Default them to what NVN expects.
> maxwell_3d: Initialize more registers to their expected value

- src/core/settings.h
- src/video_core/CMakeLists.txt
- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
- src/video_core/macro/macro.cpp
- src/video_core/macro/macro.h
- src/video_core/macro/macro_interpreter.cpp
- src/video_core/macro/macro_interpreter.h
- src/video_core/macro/macro_jit_x64.cpp
- src/video_core/macro/macro_jit_x64.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_debug.ui
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
This PR implements a macro JIT to help with larger macros and help with performance in games that spend a lot of time in the macro interpreter. 
Huge thanks to @jroweboy for their initial work on the JIT!
> video_core: Implement Macro JIT

- src/video_core/renderer_opengl/gl_device.cpp
Skip fast buffer uploads on Nvidia 443.24 Vulkan beta driver on OpenGL.
This driver throws the following error when calling BufferSubData or
BufferData on buffers that are candidates for fast constant buffer
uploads. This is the equivalent to push constants on Vulkan, except that
they can access the full buffer. The error:
Unknown internal debug message. The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
If this error persists on future drivers, we might have to look deeper
into this issue. For now, we can black list it and log it as a temporary
solution.
> gl_device: Black list NVIDIA 443.24 for fast buffer uploads

- CMakeModules/GenerateSCMRev.cmake
- src/common/CMakeLists.txt
- src/video_core/CMakeLists.txt
- src/video_core/renderer_opengl/gl_arb_decompiler.cpp
- src/video_core/renderer_opengl/gl_arb_decompiler.h
- src/video_core/renderer_opengl/gl_device.cpp
- src/video_core/renderer_opengl/gl_device.h
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/yuzu/configuration/configure_graphics_advanced.cpp
Emit code compatible with NV_gpu_program5.
This should emit code compatible with Fermi, but it wasn't tested on
that architecture. Pascal has some issues not present on Turing GPUs.
> gl_arb_decompiler: Implement an assembly shader decompiler

- src/common/x64/xbyak_abi.h
- src/video_core/macro/macro_jit_x64.cpp
Minor changes not affecting behaviour. (With the exception of the first commit, which is a bugfix.)
> xbyak_abi: Cleanup

- src/video_core/renderer_opengl/gl_device.cpp
Due to the limitation of GL_MAX_IMAGE_UNITS being low (8) on Intel's and Nvidia's proprietary drivers, we have to reserve an appropriate amount of image bindings for each of the stages.
So far games have been observed to use 4 image bindings in the fragment stage (Kirby Star Allies) and 1 in the vertex stage (TWD series).
No games thus far in my limited testing used more than 4 images concurrently and across all currently active programs.
This fixes shader compilation errors on Kirby Star Allies on OpenGL (Both GLSL and GLASM, although these errors don't translate to graphical issues on GLASM that are seen on GLSL, oddly enough)
Thanks to @ToxaGaming, @Its-Rei and gidoly for helping me test this out.
**GLSL:**
Before:
After:
(Thanks gidoly for the images below)
Before:
After:
> gl_device: Reserve 4 image bindings for fragment stage

- src/core/file_sys/system_archive/mii_model.cpp
- src/input_common/keyboard.cpp
- src/input_common/motion_emu.cpp
Named return value optimization automatically applies in these cases.
> Remove redundant moves

- src/core/file_sys/system_archive/shared_font.cpp
- src/core/hle/kernel/memory/memory_manager.cpp
- src/video_core/query_cache.h
- src/video_core/renderer_vulkan/renderer_vulkan.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/shader/memory_util.cpp
- src/video_core/shader_cache.h
- src/yuzu/CMakeLists.txt
- src/yuzu/bootmanager.cpp
Please note: This does not enable yuzu to be playable on macOS.
> Fix compilation on macOS

- src/video_core/renderer_opengl/gl_arb_decompiler.cpp
Variables that are marked as const cannot have the move constructor invoked when returning from a function (the move constructor requires a non-const variable so it can "steal" the resources from it.
@ReinUsesLisp Is the transformation made at 1159 (moving the string into the conditional) safe, or does it need to purposely be outside of the if statement?.
> gl_arb_decompiler: Avoid several string copies

- src/core/hle/service/acc/acc.cpp
- src/core/hle/service/acc/acc_aa.cpp
- src/core/hle/service/acc/acc_su.cpp
- src/core/hle/service/acc/acc_u0.cpp
- src/core/hle/service/acc/acc_u1.cpp
This was based on Switchbrew page: switchbrew.org/wiki/Account_services
This does *not* allow you to play online.
> account: Update function tables and add missing classes

- src/core/hle/service/lm/manager.cpp
- src/yuzu_tester/service/yuzutest.cpp
Silence miscellaneous warnings reported by MSVC
> Silence miscellaneous warnings

- src/yuzu/main.cpp
- src/yuzu/main.h
- src/yuzu/main.ui
It simply opens [the Mods page](https://github.com/yuzu-emu/yuzu/wiki/Switch-Mods) when clicked
> Add a "Open Mods Page" button to the GUI

- src/core/hle/service/eupld/eupld.cpp
This was based on Switchbrew page: https://switchbrew.org/wiki/Error_Upload_services
> eupld: Update function table

- src/core/hle/service/aoc/aoc_u.cpp
This was based on Switchbrew page: https://switchbrew.org/wiki/NS_Services#aoc:u
> aoc: Update function table

- src/core/hle/service/bcat/bcat.cpp
- src/core/hle/service/bcat/module.cpp
This was based on Switchbrew page: https://switchbrew.org/wiki/BCAT_services
> bcat: Update function tables and add missing classes

- src/core/hle/service/bpc/bpc.cpp
This was based on Switchbrew page: https://switchbrew.org/wiki/PCV_services
> bpc: Update function tables

- src/core/hle/service/btdrv/btdrv.cpp
This was based on Switchbrew page: https://switchbrew.org/wiki/Bluetooth_Driver_services
> btdrv: Update function table

- src/common/CMakeLists.txt
- src/common/fiber.cpp
- src/common/fiber.h
- src/common/spin_lock.cpp
- src/common/spin_lock.h
- src/common/thread.h
- src/common/uint128.cpp
- src/common/uint128.h
- src/common/wall_clock.cpp
- src/common/wall_clock.h
- src/common/x64/cpu_detect.cpp
- src/common/x64/cpu_detect.h
- src/common/x64/native_clock.cpp
- src/common/x64/native_clock.h
- src/core/CMakeLists.txt
- src/core/core_timing_util.cpp
- src/core/core_timing_util.h
- src/core/host_timing.cpp
- src/core/host_timing.h
- src/tests/CMakeLists.txt
- src/tests/common/fibers.cpp
- src/tests/core/host_timing.cpp
All this new utilities will be used in special development project **Prometheus**
This include tests and setups. We are also updating boost with this.
Special Thanks to Exzap, from CEMU. For feedback and providing example code to estimate x64's native clock frequency.
> Implement SpinLocks, Fibers and a Host Timer

- src/core/hle/service/friend/friend.cpp
This was based on Switchbrew page: https://switchbrew.org/wiki/Friend_services
> friend: Update function table

- src/core/hle/service/nfc/nfc.cpp
This was based on Switchbrew page: https://switchbrew.org/wiki/NFC_services
> nfc: Update function table

- src/core/hle/service/mm/mm_u.cpp
This was based on Switchbrew page: https://switchbrew.org/wiki/Display_services
> mm: Update function table

- src/core/hle/service/mig/mig.cpp
This was based on Switchbrew page: https://switchbrew.org/wiki/Migration_services
> mig: Update function table

- src/core/hle/service/ldn/ldn.cpp
This was based on Switchbrew page: https://switchbrew.org/wiki/LDN_services
> ldn: Update function table

- src/core/hle/service/grc/grc.cpp
This was based on Switchbrew page: https://switchbrew.org/wiki/GRC_services
> grc: Update function table

- src/core/hle/service/ldr/ldr.cpp
This was based on Switchbrew pages:
https://switchbrew.org/wiki/NRR
https://switchbrew.org/wiki/NRO
> ldr: Update NRR/NRO structs

- src/yuzu/main.cpp
- src/yuzu/main.h
Based on suggestion in Feature Request #3997 
Superseds #4059 
Before:
After:
> Add game version to window title

- src/common/CMakeLists.txt
> Revert "cmake: fix fmt linking"

- src/core/hle/service/set/set.cpp
- src/core/hle/service/set/set.h
> Implement GetKeyCodeMap & GetKeyCodeMap2

- src/yuzu/configuration/config.cpp
- src/yuzu/main.cpp
Also fixed a crash when emu_thread is nullptr and attempting to screenshot
> configuration: Fix hotkeys that open file dialog in windowed mode

- src/core/arm/cpu_interrupt_handler.cpp
> cpu_interrupt_handler: Remove #pragma once from .cpp file

- src/core/hle/service/am/am.cpp
> AM: fix GetDisplayVersion

- src/input_common/gcadapter/gc_adapter.cpp
Some yuz-ers have reported crashes relating to libusb. This PR adds more error checking on libusb calls, logging errors as encountered and halting executions earlier when errors are encountered.
> input_common: Add more libusb error checks for GC Adapter

- src/audio_core/stream.cpp
- src/audio_core/stream.h
Fixes the issue with needing the timestretcher for multicore.
> audio: Improving audio timing for multicore/single core

- src/common/alignment.h
> Revert "Port citra-emu/citra#5441: "Common: remove a mod from AlignUp""

- README.md
> Fix Discord invite link

- src/common/alignment.h
Please wait for CI to pass before merging this.
> common/alignment: Fix compilation errors

- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_64.cpp
- src/core/settings.h
- src/yuzu/CMakeLists.txt
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/config.h
- src/yuzu/configuration/configure.ui
- src/yuzu/configuration/configure_cpu.cpp
- src/yuzu/configuration/configure_cpu.h
- src/yuzu/configuration/configure_cpu.ui
- src/yuzu/configuration/configure_cpu_debug.cpp
- src/yuzu/configuration/configure_cpu_debug.h
- src/yuzu/configuration/configure_cpu_debug.ui
- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_debug.ui
- src/yuzu/configuration/configure_dialog.cpp
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
- src/yuzu_tester/default_ini.h
Expose fine-grained CPU optimization flags for debugging purposes only.
> configuration: Add settings to enable/disable specific CPU optimizations

- src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Avoids redundant variable name repetitions.
> vk_graphics_pipeline: Make use of designated initializers where applicable

- src/core/constants.h
Eliminates reliance on an indirect include.
> constants: Add missing <array> include

- src/core/hle/kernel/address_arbiter.cpp
- src/core/hle/kernel/svc.cpp
- src/core/hle/kernel/synchronization.cpp
Silences a few warnings in the Linux build.
> kernel: Remove unused variables

- src/input_common/gcadapter/gc_adapter.cpp
- src/input_common/gcadapter/gc_adapter.h
I wanted to take some time to clean up the code, removing unnecessary functions and variables and hopefully improving readability at the very least.
I would appreciate suggestions for gc_adapter and gc_poller code.
> gc_adapter: Refactor code

- src/core/hle/service/am/applets/software_keyboard.cpp
- src/core/hle/service/am/applets/software_keyboard.h
Fixes random swkbd popups in monster hunter. Future PR will implement inlined swkbd when more research is done
> swkbd: Return result for Calc request for inlined swkbd

- src/input_common/gcadapter/gc_adapter.cpp
- src/input_common/gcadapter/gc_poller.cpp
Resolves some compiler warnings on Clang/GCC
> gc_adapter/gc_poller: Resolve compiler warnings

- src/core/hle/service/am/am.cpp
> AM: GetDesiredLanguage: remove unused variable

- src/video_core/texture_cache/surface_params.cpp
These are bugs waiting to happen. While we're in the area, we can also do a little bit of other tidying up.
> surface_params: Replace questionable usages of the comma operator with semicolons

- src/core/file_sys/mode.h
- src/core/file_sys/vfs_real.cpp
Same behavior, minus a hand-rolled operator.
> file_sys/mode: Make use of DECLARE_ENUM_FLAG_OPERATORS with Mode

- src/core/file_sys/savedata_factory.cpp
- src/core/file_sys/savedata_factory.h
- src/core/hle/service/am/am.cpp
- src/core/hle/service/filesystem/filesystem.cpp
- src/core/hle/service/filesystem/filesystem.h
- src/core/hle/service/filesystem/fsp_srv.cpp
- src/core/hle/service/filesystem/fsp_srv.h
Stub these 2 service commands required for Animal Crossing: New Horizons Update 1.4.0
Fixes https://github.com/yuzu-emu/yuzu/issues/4454.
> fsp-srv: Stub Read/WriteSaveDataFileSystemExtraDataWithMaskBySaveDataAttribute

- src/core/hle/service/acc/profile_manager.cpp
Simplifies some code and eliminates variable name repetition.
> profile_manager: Make use of designated initializers 

- src/video_core/renderer_vulkan/vk_blit_screen.cpp
- src/video_core/renderer_vulkan/vk_device.cpp
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_sampler_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
We simply need to provide two initializers.
> vk_texture_cache: Silence -Wmissing-field-initializer warnings

- CMakeLists.txt
Updates our tracked libraries to use their latest releases, keeping them up to date.
> CMakeLists: Update several libraries

- src/core/file_sys/system_archive/time_zone_binary.cpp
Simplifies the initialization of some objects and eliminates now-unnecessary zero-initializations.
> time_zone_binary: Make use of designated initializers

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_device.cpp
- src/video_core/renderer_vulkan/vk_device.h
- src/video_core/renderer_vulkan/vk_fence_manager.cpp
- src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
- src/video_core/renderer_vulkan/vk_graphics_pipeline.h
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/renderer_vulkan/vk_pipeline_cache.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.h
- src/video_core/renderer_vulkan/wrapper.cpp
- src/video_core/renderer_vulkan/wrapper.h
- src/video_core/shader/async_shaders.cpp
- src/video_core/shader/async_shaders.h
- src/yuzu/configuration/configure_graphics_advanced.ui
This PR is an attempt to defer Vulkan graphics pipeline compilation to asynchronous threads, in an effort to reduce stutter while building the graphics pipelines during gameplay. Based heavily on the previous work for async OpenGL shaders by ogniK (#4273)
Huge thanks to both ogniK and Rodrigo for their guidance, and @lat9nq for testing on Linux.
> vulkan_renderer: Async shader/graphics pipeline compilation

- src/common/time_zone.cpp
> Revert "common/time_zone: Simplify GetOsTimeZoneOffset()"

- src/core/arm/cpu_interrupt_handler.cpp
- src/core/arm/cpu_interrupt_handler.h
Fixes a data race detected with tsan
> cpu_interrupt_handler: Make is_interrupted an atomic

- src/input_common/sdl/sdl_impl.cpp
Performs some minor tidying up that reduces copies and unnecessary constructions where able to do so.
Each commit contains an elaboration on the changes made.
> sdl_impl: Minor cleanup

- .gitmodules
- externals/libusb/CMakeLists.txt
- externals/libusb/config.h.in
Allows us to directly track and manage how we integrate libusb into yuzu without needing to use a fork as an intermediary to bridge the gap.
> externals: Track upstream libusb directly

- src/core/file_sys/patch_manager.h
> file_sys/patch_manager: Add missing include

- src/yuzu/game_list_p.h
Consistency change with how we mark constants in the rest of the codebase.
> game_list_p: Mark some constants as constexpr

- src/core/core.cpp
- src/core/core.h
- src/core/file_sys/bis_factory.cpp
- src/core/file_sys/bis_factory.h
- src/core/file_sys/romfs_factory.cpp
- src/core/file_sys/romfs_factory.h
- src/core/hle/service/filesystem/filesystem.cpp
- src/core/loader/deconstructed_rom_directory.cpp
- src/core/loader/nca.cpp
- src/core/loader/nro.cpp
- src/core/loader/nso.cpp
Continues the removal of dependencies on the global system instance. This gets rid of five more instances.
> bis_factory/romfs_factory: Eliminate dependencies on the global system instance

- src/core/hle/service/service.cpp
This is now completely unused, so it can be removed.
> service: Remove unused funcation

- src/yuzu/configuration/configure_input_player.cpp
> configure_input_player: Fixes motion mapping using ConfigureButtonClick
