.ci/templates/build-mock.yml, .ci/templates/build-single.yml, .ci/templates/release-download.yml, .ci/templates/release-github.yml, .ci/templates/release-universal.yml, .ci/yuzu-mainline-step1.yml, .ci/yuzu-mainline-step2.yml
Adds:
- Caching for all builds
- Mock build for faster testing
- Templates for universal and github releases
- Split mainline pipeline to two parts, one for main and sub repos
=> ci: Split mainline pipeline and add support for GitHub releases

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.h, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode/image.cpp, src/video_core/shader/node.h, src/video_core/shader/shader_ir.h
Implements SULD (`imageLoad`) using `GL_EXT_shader_image_load_formatted` when available. While we are at it, fix SUATOM related GLSL build issues.
This removes the image format guessing and always uses `r32ui` when atomic operations are present. Operations that will require signed/unsigned distinction (e.g. `MIN`) will have to use a compare-and-swap loop. The implementation for these has been removed until we find a game using it.
=> shader/image: Implement SULD and fix SUATOM

README.md
Removes the AppVeyor status indicator from the readme.md as we have moved pull request checks to Azure
=> Remove AppVeyor status from the readme.md

.ci/scripts/windows/upload.ps1, .ci/templates/build-msvc.yml, .ci/templates/build-single.yml, .ci/templates/mergebot.yml, .ci/templates/release-download.yml, .ci/yuzu-mainline-step2.yml, .ci/yuzu-patreon-step2.yml
This:
- Adds the MSVC windows build template
- Fixes a mainline title bar bug
- Uses MSVC over MinGW in mainline and patreon
=> ci: Add windows MSVC builds to patreon and mainline pipelines

license.txt, src/yuzu/uisettings.cpp, src/yuzu/uisettings.h
See citra-emu/citra#4004 for more details and screenshots of how it looks.
This is a follow-up to https://github.com/yuzu-emu/yuzu/pull/2444, this is why the diff is so small.
=> Port citra-emu/citra#4004: "qt_themes: add two colorful themes"

.ci/scripts/linux/docker.sh, .gitmodules, externals/CMakeLists.txt
We don't need to depend on a custom fork for this. We can add the library as is, and then make it excluded from the ALL target, so we only link in the libraries that we actually make use of.
=> externals: Track mainline zlib as a submodule

src/core/crypto/key_manager.cpp
Removes std::array contructor call.
=> [crypto] Use IsAllZeroArray helper function

src/yuzu_cmd/emu_window/emu_window_sdl2.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2.h, src/yuzu_cmd/yuzu.cpp
Port citra-emu/citra#4950: "Add FPS to SDL title bar"
Also fix a small issue with incorrect shutdown ordering in SDL.
Previously the system would still be running so the telemetry task
didn't launch and detached_tasks would assert(count == 0)
I'm adding this so that we can visually have people test to see if theres a performance difference between SDL and Qt. We techincally could have them turn on frametime logging, but thats still slightly unreliable since we learned about how SwapBuffers() isn't included in frametime calculations.
=> Port citra-emu/citra#4950: "Add FPS to SDL title bar"

src/video_core/texture_cache/texture_cache.h
This PR adds another HLE mechanism to the texture cache. It turns out that Fermi2D blits depth formats as color formats, forcing us to do an expensive depth -> color conversion through buffer copies. With this PR, the texture cache will try to deduce if the textures are both depth (or 1 is depth & the other is not known) and will try to correct the formatting, in order to avoid expensive copies.
This work great on ZLA and DKCTF.
=> TextureCache: Add the ability to deduce if two textures are depth on blit.

src/video_core/shader/ast.cpp, src/video_core/shader/ast.h, src/video_core/shader/control_flow.cpp, src/video_core/shader/expr.cpp, src/video_core/shader/expr.h
Makes a few minor amendments to the changes introduced within #2888. Notably, it also fixes a bug within the move constructor of ASTManager where all member variables wouldn't be transferred over to the new instance.
This also gets rid of a few instances where unnecessary atomic reference count increments and decrements were being performed due to std::shared_ptr copies.
=> video_core/shader: Minor changes

src/yuzu/main.cpp
Fixes a small error where title bars would not contain the game name
=> qt: Fix game name format error

src/video_core/renderer_opengl/gl_shader_disk_cache.cpp, src/video_core/renderer_opengl/gl_shader_disk_cache.h
Previously old entries where appended to the file even if the shader cache was ignored at boot. Address that issue.
=> gl_shader_disk_cache: Properly ignore existing cache

src/common/alignment.h
This was related to the source allocator being passed into the constructor potentially having a different type than allocator being constructed.
We simply need to provide a constructor to handle this case.
=> alignment: Resolve allocator construction issues on debug

src/core/hle/service/bcat/backend/backend.cpp, src/core/hle/service/bcat/backend/backend.h, src/core/hle/service/bcat/backend/boxcat.cpp, src/core/hle/service/bcat/module.cpp
Silences unused variable warnings and type truncation warnings. While we're in the same area, we can also make minor improvements to the interfaces.
=> bcat: Silence various warnings

src/core/core.cpp, src/core/core.h, src/core/file_sys/romfs_factory.cpp, src/core/file_sys/romfs_factory.h, src/core/file_sys/savedata_factory.cpp, src/core/gdbstub/gdbstub.cpp, src/core/hle/kernel/handle_table.cpp, src/core/hle/service/am/am.cpp, src/core/hle/service/bcat/bcat.cpp, src/core/hle/service/bcat/bcat.h, src/core/hle/service/bcat/module.cpp, src/core/hle/service/bcat/module.h, src/core/hle/service/fatal/fatal.cpp, src/core/hle/service/filesystem/filesystem.cpp, src/core/hle/service/filesystem/filesystem.h, src/core/hle/service/ldr/ldr.cpp, src/core/hle/service/ns/pl_u.cpp, src/core/memory.cpp
Migrates the HLE service code off the use of directly accessing the global system instance where trivially able to do so. This removes all usages of Core::CurrentProcess from the service code, only 8 occurrences of this function exist elsewhere. There's still quite a bit of "System::GetInstance()" being used, however this was able to replace a few instances.
Keeping around `Core::CurrentProcess` only encourages the use of the global system instance (which will be phased out long-term). Instead, we use the direct system function call directly to remove the appealing but discouraged short-hand.
=> core: Remove Core::CurrentProcess()

src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h
Makes use of the already existing `DeactivateController` function.
Resolves #2663
=> hid: Implement DeactivateNpad

.ci/scripts/windows/upload.ps1
This makes the builds smaller in a low-dependency format.
=> ci: Add TAR-XZ compression to MSVC builds

.ci/templates/build-mock.yml, .ci/templates/merge-private.yml, .ci/templates/merge.yml, .ci/templates/release-github.yml, .ci/templates/release-private-tag.yml, .ci/yuzu-mainline-step2.yml, .ci/yuzu-patreon-step2.yml
Releases and tags now use the DisplayVersion instead of BuildId
=> ci: Correct azure tag and release names

src/core/CMakeLists.txt, src/core/core.cpp, src/core/core.h, src/core/hle/service/lm/lm.cpp, src/core/hle/service/lm/lm.h, src/core/hle/service/lm/manager.cpp, src/core/hle/service/lm/manager.h, src/core/hle/service/service.cpp, src/core/reporter.cpp, src/core/reporter.h
Firstly, this renames command 0 on `ILogger` to `Log`, as opposed to `Initialize`, which was an early unofficial name.
This also now outputs log data to the reporter instead of just outputting them to console. The way LM log packets are structured, there is a head log and tail log which signal the start and end of a stream of messages. All messages in a stream will output to one report, as an array of packets. Additionally, the core will automatically flush any non-tailed log packets on shutdown in case of an unexpected failure.
=> lm: Rewrite logger to use core reporting services

src/video_core/renderer_opengl/gl_rasterizer.cpp
For some reason hardware divides polygon offset units by two. This is visible since drivers multiply the application requested polygon offset by two.
=> gl_rasterizer: Fix polygon offset units

src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h
This is useful in Vulkan where we want to update depth bounds without caring if it's enabled or disabled through `vkCmdSetDepthBounds`.
=> maxwell_3d: Add dirty flags for depth bounds values

CONTRIBUTING.md
The original Contributing.md had differences, such as some links, so I created a page on yuzu's wiki based on the original file.
=> Link to Yuzu's wiki instead of Citra's

src/core/file_sys/card_image.cpp, src/core/file_sys/card_image.h, src/core/file_sys/partition_filesystem.cpp, src/core/file_sys/partition_filesystem.h
This adds:
- Optimization that lazily loads parts of the gamecard
- Bug fix that allows the update part to be loaded -- this is the reason for the previous bullet point.
- Accessors for the raw part0/1 of the gamecard
- Missing implementations for gamecard certificate and IDs
- Accessors for sizes/offset maps in PFS
=> file_sys: Add code to access raw gamecard partitions and lazily load them

src/yuzu/configuration/configure_input_player.cpp
Analog triggers (from controllers like the XBOX controller) would not work due to a different range of their signals (from 0 to 255 on analog triggers instead of -32768 to 32768 on analog joysticks).
The SDL driver misinterprets analog triggers as analog joysticks.
Fixes:
#1659
=> yuzu/configure_input_player: Fix input handling for ZL and ZR from controllers with analog triggers

src/common/CMakeLists.txt, src/common/algorithm.h, src/video_core/texture_cache/surface_base.cpp, src/video_core/texture_cache/surface_base.h
Makes the header a little bit more general-purpose and open for other iterator-based additions in the future. Having a single header for solely one 8 line algorithm is a little unnecessary.
=> common: Rename binary_find.h to algorithm.h

src/core/hle/service/am/am.cpp, src/core/hle/service/bcat/backend/backend.cpp, src/core/hle/service/bcat/backend/backend.h, src/core/hle/service/bcat/backend/boxcat.cpp, src/core/hle/service/bcat/backend/boxcat.h, src/core/hle/service/bcat/module.cpp, src/core/hle/service/nvflinger/buffer_queue.cpp, src/core/hle/service/nvflinger/buffer_queue.h, src/core/hle/service/nvflinger/nvflinger.cpp, src/video_core/gpu.cpp
Eliminates the reliance on global state in a few areas. These are relatively trivial usages that are able to be replaced via passing along the system instance as part of function interfaces. In some cases, it's as simple as just using a member variable instead of the accessor.
Brings us a little close to dropping the global singleton.
=> {bcat, gpu, nvflinger}: Remove trivial usages of the global system accessor

src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/shader/node.h
Just applies a few minor changes that avoid redundant copies and heap allocations. Each commit itself should have extra context in its description to help clarify the changes.
=> gl_shader_decompiler: Minor cleanup-related changes

src/video_core/surface.cpp
Prevents fallthrough into the following case.
=> video_core/surface: Add missing break in PixelFormatFromTextureFormat()

src/video_core/texture_cache/texture_cache.h
We can take these by const reference and avoid making unnecessary copies, preventing some atomic reference count increments and decrements.
=> texture_cache: Avoid unnecessary surface copies within PickStrategy() and TryReconstructSurface()

src/video_core/texture_cache/texture_cache.h
Amends the doxygen comments so that they properly resolve (a comma at the end of an identifier name causes them to fail to resolve). While we're at it, we can correct some typos and fix up some of the comments' formatting in order to make them slightly nicer to read.
=> video_core/texture_cache: Amend Doxygen references

src/video_core/engines/maxwell_3d.cpp, src/video_core/shader/control_flow.cpp, src/video_core/shader/control_flow.h
A trivial warning caused by not using size_t as the argument types instead of u32.
=> maxwell_3d: Silence truncation warnings

src/core/core.cpp, src/core/memory/cheat_engine.cpp
Orders the members in constructor initializer lists to be formatted the same way as their declaration in the class itself.
=> core: Resolve -Wreorder warnings

src/core/hle/service/apm/controller.cpp, src/core/hle/service/apm/controller.h
Makes a member function a const-qualified and eliminates the use of a static lifetime map (using an array instead, given the small size of the elements), reducing the heap memory usage of the function.
=> service/apm/controller: Minor interface changes

src/video_core/macro_interpreter.cpp, src/video_core/macro_interpreter.h
This allows the implementation of these types to change without requiring a rebuild of everything that includes the macro interpreter header.
=> video_core/macro_interpreter: Make definitions of most private enums/unions hidden

src/core/memory/dmnt_cheat_vm.cpp
Previously these were performing the same behavior as the Save and ClearSaved opcode types. I've also filed a PR upstream with Atmosphere [here](https://github.com/Atmosphere-NX/Atmosphere/pull/683) given it's derived from the same code.
=> dmnt_cheat_vm: Correct register Restore and ClearRegs behavior

src/video_core/shader/ast.cpp, src/video_core/shader/ast.h
- Makes use of fmt where applicable in order to make strings easier to read, as well as cut down on string churn.
- Makes Indent() non-allocating, given it only ever substrings a string_view that's always guaranteed to exist.
=> video_core/shader/ast: Minor changes to ASTPrinter

src/video_core/engines/maxwell_3d.cpp
Otherwise this spams faster than what conhost can show.
The count entry is wrong, but that's beyond the scope of these changes.
=> maxwell_3d: Reduce FlushMMEInlineDraw logging to Trace

src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
The `NeverExecute` and `UnusedIndex` entries were currently having their target overwritten and replaced with the default case. This amends that.
=> gl_shader_decompiler/vk_shader_decompiler: Resolve implicit fallthrough cases

src/video_core/shader/decode/memory.cpp, src/video_core/shader/shader_ir.h
Ignore global memory operations instead of invoking undefined behaviour when constant buffer tracking fails and we are blasting through asserts, ignore the operation.
In the case of LDG this means filling the destination registers with zeroes; for STG this means ignore the instruction as a whole.
The default behaviour is still to abort execution on failure.
While we are at it, remove the usage of unnecessary temporaries for STG.
=> shader_ir/memory: Ignore global memory when tracking fails

.ci/scripts/common/post-upload.sh, .ci/scripts/linux/upload.sh, .ci/scripts/windows/upload.ps1, .ci/scripts/windows/upload.sh, .ci/templates/build-msvc.yml
Fixes a bug in the installer with multiple variants on the same platform.
=> ci: Add build name to archive root folder

src/video_core/engines/shader_bytecode.h
Greatly shrinks the amount of generated code for GetDecodeTable().
Collapses an assembly [output](https://godbolt.org/z/taz6kA) of 9000+ lines down to ~3621 with Clang, and 6513 down to ~2616 with GCC, given they're now allowed to construct all the would-be entries as a sequence of constant data.
=> shader_bytecode: Make Matcher constexpr capable

.ci/scripts/common/post-upload.sh, .ci/scripts/linux/upload.sh, .ci/scripts/windows/upload.ps1, .ci/scripts/windows/upload.sh, .ci/templates/build-msvc.yml
This reverts commit 5e553a6c267f4ab96a89833f1006ea27fd78b30a.
This commit introduced a regression (unintentional) by changing the folder that the build is deployed to (intentional). The installer creates a shortcut at install time which reads from the config at install time to point the shortcut to the folder path, so when this change went out, it caused the shortcut to point to the wrong launch path. Users would need to reinstall with a patched config to fix the issue, but for reasons we haven't figured out at the moment, the config update doesn't seem to be pushed out properly to some individuals, so we will just revert and hope for the best.
=> Revert "ci: Add build name to archive root folder"

src/video_core/shader/decode/texture.cpp, src/video_core/shader/shader_ir.h
TLD4S always outputs 4 values, the previous code checked a component mask and omitted those values that weren't part of it. This commit corrects that and makes sure all 4 values are set.
=> Shader_Ir: Fix TLD4S from using a component mask.

src/video_core/shader/shader_ir.cpp
Given the overall size of the maps are very small, we can use arrays of pairs here instead of always heap allocating a new map every time the functions are called. Given the small size of the maps, the difference in container lookups are negligible, especially given the entries are already sorted.
=> shader_ir: Use std::array with std::pair instead of std::unordered_map

src/video_core/textures/astc.cpp
Self explanatory. Removes some of the few remaining `-Wconversion` or `/w4244` errors in `video_core`.
=> astc: Silence implicit conversion warnings

src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h
With #3032 and #3033 it becomes trivial to start treating implicit conversions as errors.
=> maxwell_3d: Silence implicit conversion warnings

src/common/multi_level_queue.h, src/core/core.cpp, src/core/core.h, src/core/core_cpu.cpp, src/core/core_cpu.h, src/core/cpu_core_manager.cpp, src/core/gdbstub/gdbstub.cpp, src/core/hle/kernel/address_arbiter.cpp, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/mutex.cpp, src/core/hle/kernel/process.cpp, src/core/hle/kernel/scheduler.cpp, src/core/hle/kernel/scheduler.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h, src/core/hle/kernel/wait_object.cpp, src/yuzu/debugger/wait_tree.cpp
This PR is a continuation of the new scheduler (#2364) with significantly more fixes. The new scheduler is meant to be closer to the RE info we have and does a few things in a more appropriate manner. Core differences:
- The new scheduler does not automatically assign threads without an assigned cpu core. Instead it moves them to a suggested queue and resolves them when no scheduled thread can be assigned to the current core.
- All yield types are now implemented and can now be redundant accordingly (before the yielding thread went to sleep, leaving the possibility for a lower priority thread to be scheduled instead).
- Prepare reschedule has been revised and should now be triggered whenever a thread wakes up.
- Some corrections have been made to thread switching and picking threads on …
=> Kernel: Implement a New Thread Scheduler V2

.gitmodules, externals/opus/CMakeLists.txt
Tracks upstream opus, allowing the library to be easily updated. While we're at it, we incorporate the CMakeLists.txt from the fork in a way that we have easy control over the requirements of the build within the actual source tree separate from the submodule itself.
=> externals: Track upstream opus

src/video_core/engines/kepler_compute.cpp, src/video_core/engines/kepler_compute.h, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/textures/texture.h
This removes unused parts of the API in maxwell_3d and kepler_compute, simplifying the code overall. There are other changes to be done but I'll wait for related changes to be merged first.
=> maxwell_3d: Remove unused entries

src/video_core/CMakeLists.txt, src/video_core/rasterizer_accelerated.cpp, src/video_core/rasterizer_accelerated.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h
Add an intermediary class that implements common functions across GPU accelerated rasterizers. This avoids future code repetition.
=> rasterizer_accelerated: Add intermediary for GPU rasterizers

src/video_core/engines/shader_bytecode.h, src/video_core/shader/decode/texture.cpp, src/video_core/shader/shader_ir.h
This commit fixes an issue where not all 4 results of tld4 were being written, the color component was defaulted to red, among other things. It also implements the bindless variant.
=> Shader_IR: Fix TLD4 and add Bindless Variant.

src/video_core/shader/decode/texture.cpp, src/video_core/shader/shader_ir.h
Originally on the last commit I thought TLD4 acted the same as TLD4S and didn't have a mask. It actually does have a component mask. This commit corrects that.
=> Shader_IR: Fix regression on TLD4

src/common/common_funcs.h
- Zero initialization here is useful for determinism.
=> common_func: Use std::array for INSERT_PADDING_* macros.

src/common/common_funcs.h
=> Revert "common_func: Use std::array for INSERT_PADDING_* macros."

src/common/bit_field.h
See bunneis comment [here](https://github.com/citra-emu/citra/pull/4629#discussion_r258533167).
They were supposed to be removed by him, but he missed them.
=> common/bit_field: Remove FORCE_INLINE calls

src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h
These commands require Screenshots to be implemented anyway, so they are safe to stub for now.
=> core/am: Stub InitializeApplicationCopyrightFrameBuffer, SetApplicationCopyrightImage and SetApplicationCopyrightVisibility

src/video_core/engines/fermi_2d.cpp
Normaly OpenGL does not care if the areas exceed the texture regions but other backends such as Vulkan do care about the limits of this areas. This PR crops the areas of the blit in order that they don't surpass the limits of the textures. This should help Vulkan and faulty OpenGL drivers.
=> Fermi2D: limit blit area to only available area

src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h
Here, we are leaving both `SetNpadJoyAssignmentModeSingleByDefault` and `SetNpadJoyAssignmentModeSingle` stubbed because we do not currently know fully the differences in implementation between both commands.
This PR also stubs `GetNpadHandheldActivationMode` and reorganizes some of the hid service commands based on the command ID.
This resolves #2671, **however this will not allow you to proceed past the controller selection screen when docked mode is enabled upon launching the game** (see #2865). Also, Pokemon Let's Go reports a `npad_id` of 32 when `SetNpadJoyAssignmentModeSingle` is called which ~~according to @Hexagon12 is incorrect~~ is the npad_id for "Handheld Docked Joycons."
It seems that the cause of Pokemon Let's Go not booting in the canary versions is due to the Joycons …
=> hid: Stub SetNpadJoyAssignmentModeSingle and GetNpadHandheldActivationMode

.ci/scripts/common/post-upload.sh, .ci/scripts/linux/upload.sh, .ci/scripts/windows/upload.ps1, .ci/scripts/windows/upload.sh, .ci/templates/build-msvc.yml
Adds a build name suffix to the archive folder name when the build name is *not* `mainline`.
=> ci: Rename build folder only on non-mainline builds

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.h, src/video_core/shader/decode/image.cpp, src/video_core/shader/decode/texture.cpp, src/video_core/shader/node.h, src/video_core/shader/shader_ir.h, src/video_core/textures/texture.h
Bindless textures were using u64 to pack the buffer and offset from where they come from. Drop this in favour of separated entries in the struct.
Remove the usage of `std::set` and `std::map` in favor of `std::list` (it's not `std::vector` to avoid reference invalidations) for samplers and images. Now these entries can be easily modified after they are returned.
=> shader/node: Unpack bindless texture encoding

src/video_core/buffer_cache/buffer_cache.h, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_buffer_cache.h, src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/gl_rasterizer.cpp
Nvidia's OpenGL driver maps `gl(Named)BufferSubData` with some requirements to a fast. This path has an extra `memcpy` but updates the buffer without orphaning or waiting for previous calls. It can be seen as a better model for "push constants" that can upload a whole UBO instead of 256 bytes.
This path has some requirements established [here](http://on-demand.gputechconf.com/gtc/2014/presentations/S4379-opengl-44-scene-rendering-techniques.pdf#page=24).
Instead of using the stream buffer, this commits moves constant buffers uploads to calls of `glNamedBufferSubData` and from my testing it brings a performance improvement. This is disabled when the vendor is not Nvidia since it brings performance regressions.
Thanks to @graphitemaster for telling me about …
=> gl_rasterizer: Upload constant buffers with glNamedBufferSubData

src/video_core/shader/decode/arithmetic.cpp, src/video_core/shader/decode/arithmetic_half.cpp, src/video_core/shader/decode/arithmetic_half_immediate.cpp, src/video_core/shader/decode/ffma.cpp, src/video_core/shader/decode/half_set.cpp, src/video_core/shader/decode/half_set_predicate.cpp, src/video_core/shader/decode/texture.cpp
Many of these warnings don't offer valuable information in logs, these commits reduces their severity.
While we are at it, change some of these logs to show up in cases where the unexpected variant is used (e.g. no FTZ in a instruction).
=> shader_ir: Reduce severity of warnings

src/video_core/buffer_cache/buffer_cache.h
`boost::make_iterator_range` is available when `boost/range/iterator_range.hpp` is included
Also, include `boost/icl/interval_map.hpp` and `boost/icl/interval_set.hpp`
`boost/range.hpp` is **not** present in the trimmed down version of boost yuzu uses.
Supersedes #3049 by using the correct include(s). Also, fixes #2821
=> buffer_cache: Add missing include

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This commit corrects the argument ordering in textureGatherOffset.
=> GLSLDecompiler: Correct Texture Gather Offset.

src/video_core/renderer_opengl/gl_shader_cache.cpp
Properly pass engine when a shader is being constructed from memory.
=> gl_shader_cache: Fix locker constructors

src/web_service/web_backend.cpp, src/web_service/web_backend.h, src/yuzu/configuration/configure_web.cpp, src/yuzu/configuration/configure_web.ui
yuzu: configure_web: Use Base64 encoded token for simplifying user experience.
This is a change we are making for both citra and yuzu across all clients. It's purely a user-facing/UI change, to make the experience of adding your credential simpler - it's just a simply copy+paste of one string.
See https://github.com/citra-emu/citra/pull/4993 for more details.
=> yuzu: configure_web: Use Base64 encoded token

.ci/scripts/common/post-upload.sh, .ci/scripts/windows/upload.ps1
This copies the sources of the build into the final binary archive to comply with the GPL in an easier way.
=> ci: Package source with builds

.ci/scripts/windows/upload.ps1
This should prevent path length issues when extracting the build from the installer
This might also cause a new "source" artifact to be uploaded, but that shouldn't matter for github releases at least. We should check that it doesn't break azure releases later.
=> Move source in windows uploads into its own internal zip

src/common/common_funcs.h
We can trivially resolve these by casting the characters to unsigned values and then shifting the bits.
=> common_funcs: silence sign-conversion warnings in MakeMagic()

src/core/file_sys/xts_archive.cpp
We can just call the .data() member of path instead of constructing a completely new string.
=> xts_archive: Remove redundant std::string constructor

src/common/hash.h
This is unused, so it can be removed. There's better ways of ensuring zeroed out padding bits, like using zero-initialization, anyhow.
=> common/hash: Remove unused HashableStruct

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode/warp.cpp, src/video_core/shader/node.h
Thanks to gdkchan and [Ryujinx](https://github.com/Ryujinx/Ryujinx) for this vendor-agnostic approach. The commit used as base to implement this can be found [here](https://github.com/Ryujinx/Ryujinx/commit/a4f0dbb99aad4cc6baa887af156c3bad349e3773).
This reimplements `SHFL` and `FSWZADD` using [GL_ARB_shader_ballot](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_shader_ballot.txt). This "low-level" approach allows us to emulate shader derivatives without pattern matching (building `dFd*` out of the guest instructions).
One pitfall in this approach is that it requires that the host warp size is greater or equal to 32. This is not a problem on Vulkan where we can force the warp size on compatible devices to 32 with [VK_EXT_subgroup_size_control](https://www.khronos.org/registry/v …
=> shader: Implement FSWZADD and reimplement SHFL

src/core/crypto/key_manager.cpp, src/core/crypto/partition_data_manager.cpp, src/core/file_sys/registered_cache.cpp, src/core/file_sys/xts_archive.cpp, src/core/hle/service/bcat/backend/boxcat.cpp, src/core/hle/service/bcat/module.cpp, src/core/hle/service/ldr/ldr.cpp
These functions are marked for [deprecation](https://tls.mbed.org/api/sha256_8h.html#a25c94940f4217c4dd7ad6a4e7da61b47) and it's recommended that the `mbedtls_*_ret` variants be used instead.
=> core: Migrate off deprecated mbedtls functions

src/video_core/surface.cpp
Complete the RGBA16UI which has those 2 important lines missing and for information RGBA16UI is required by pokemon sword and shield
=> Complete the implementation of RGBA16UI

src/common/common_funcs.h
Makes code that uses the macros consistent by requiring the lines to be terminated with a semicolon.
=> common_funcs: Remove semicolons from INSERT_PADDING_* macros

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_gen.cpp, src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/gl_shader_manager.h, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_state.h, src/yuzu/main.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
Emulates negative y viewports with [ARB_clip_control](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_clip_control.txt). This allows us to more easily emulate pipelines with tessellation and/or geometry shader stages while also avoiding corrupt feedbacks on games with transform feedbacks and negative viewports (since gl_Position.y was being modified).
While we are at it, use `std::string_view` in `yuzu-cmd` for collecting unsupported extension strings.
=> gl_rasterizer: Emulate viewport flipping with ARB_clip_control

src/common/bit_field.h
We can just use numeric_limits instead of relying on wraparound behavior here.
=> common/bit_field: Silence sign-conversion warnings

src/common/bit_field.h
#3106 caused expressions like `instr.gpr8.Value() != Register::ZeroIndex` to always evaluate as true even if `gpr8` is `RZ`. We use this to determine if we should write or not to the output register, resulting in all register stores being no-ops (nothing is rendered).
Until it's properly fixed I'm tagging this for mainline to avoid regressions.
=> Revert "common/bit_field: Silence sign-conversion warnings"

src/video_core/shader/decode/other.cpp
While DEPBAR is stubbed it doesn't change anything from our end. Shading languages handle what this instruction does implicitly. We are not getting anything out of this log except noise.
=> shader/other: Reduce DEPBAR log severity

src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h
Maintains implementation parity between QueryApplicationPlayStatistics and QueryApplicationPlayStatisticsByUid. If we have one of the two stubbed, then they should both be stubbed, since they function the same behaviorally underneath the hood, with the only difference being that one allows specifying a UID.
=> am: Stub QueryApplicationPlayStatistics

src/core/hle/service/am/am.cpp
We can simplify these by wrapping the necessary members in structs and then simply reading out the whole struct to make it look a little neater.
=> service/am: Remove unnecessary Skip calls

src/yuzu/main.ui
See citra-emu/citra#4953 for more details.
=> Port citra-emu/citra#4953: "citra_qt/main.ui: remove unused actions "Load Symbol Map..." and "Select Game Directory...""

src/video_core/renderer_opengl/gl_shader_gen.cpp
Nvidia has sane default output values for varyings, but the other vendors don't apply these. To properly emulate this we would have to analyse the shader header. For the time being, apply the same default Nvidia applies to `gl_Position` so we get the same behaviour on non-Nvidia drivers.
Fixes https://github.com/yuzu-emu/yuzu/issues/3125.
=> gl_shader_gen: Apply default value to gl_Position

src/video_core/buffer_cache/buffer_cache.h
Objects with a default constructor don't require curly braces. While we are at it, normalize the other initializers to use `=` instead of `{}`.
=> buffer_cache: Remove brace initialized for objects with default constructor

src/common/assert.h
See citra-emu/citra#4964 for more details.
We rely on UNREACHABLE's noreturn attribute to eliminate parent's "no return value" warning. However, this was wrapped in a `if(!false)` block, which compilers may not unfold to recognize the noreturn nature.
=> Port citra-emu/citra#4964: "Unfold UNREACHABLE implementation for dumb compilers"

src/core/hle/kernel/svc.cpp
See https://switchbrew.org/wiki/SVC#svcGetSystemTick for details
=> svc: GetSystemTick should return cntpct_el0, not core ticks.

src/video_core/renderer_opengl/gl_texture_cache.cpp
`glBlitFramebuffer` keeps in mind `GL_FRAMEBUFFER_SRGB`'s state. Enable this depending on the target surface pixel format.
=> gl_texture_cache: Apply sRGB on blits

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Casts from f32 to f16 zeroes the higher half of the target register.
=> gl_shader_decompiler: Fix casts from fp32 to fp16

src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h
The heuristic to detect AMD's driver was not working properly since it also included Intel. Instead of using heuristics to detect it, compare the GL_VENDOR string.
=> gl_device: Deduce indexing bug from device instead of heuristic

src/video_core/shader/const_buffer_locker.cpp, src/video_core/shader/const_buffer_locker.h
Silences a compiler warning.
While we're in the same area we can do a little bit of tidying up.
=> video_core/const_buffer_locker: Remove #pragma once from cpp file

src/video_core/gpu_thread.cpp
We can just use std::nullopt and std::make_optional to make this a little bit less noisy.
=> video_core/gpu_thread: Tidy up SwapBuffers()

src/core/file_sys/directory.h, src/core/hle/service/filesystem/fsp_srv.cpp
This can trivially be an enum class rather than a regular enum, making it more strongly typed.
=> file_sys/directory: Make EntryType an enum class

src/core/file_sys/patch_manager.cpp
A check for disabled cheats was missing from patch_manager, this PR adds the check.
Fixes #3176
=> patch_manager: Adds check for disabled cheats to prevent them from being enabled

src/core/file_sys/romfs.cpp, src/core/file_sys/romfs.h
These functions aren't used outside of this file, so we can place them within an anonymous namespace. While we're at it, we can also remove some unused header inclusions.
=> filesys/romfs: Make ProcessFile and ProcessDirectory internally linked

src/video_core/texture_cache/surface_base.h
Some texture views were being created out of bounds (with more layers or mipmaps than what the original texture has). This is because of a miscalculation in mipmap bounding. end_layer and end_mipmap are out of bounds (e.g. layer 6 in a cubemap), there's no need to add one more there.
Fixes OpenGL errors and Vulkan crashes on Splatoon 2.
=> texture_cache/surface_base: Fix out of bounds texture views

src/video_core/renderer_opengl/gl_framebuffer_cache.cpp, src/video_core/renderer_opengl/gl_framebuffer_cache.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h
First, reintroduce the framebuffer cache for clears.
After that, optimize framebuffer cache's key to use fewer bytes and to be more easily hashed. It is reduced to the color and zeta attachments and the color attachments map (`glDrawBuffers`) is reduced to a single u32.
After this is merged we can safely remove the render target count check in the texture cache found [here](https://github.com/yuzu-emu/yuzu/blob/e3ee017e91ef4d713f1af8cb60c5157e40d43f18/src/video_core/texture_cache/texture_cache.h#L170).
From my testing, Super Mario Maker 2 doesn't have regressions with these changes.
=> gl_framebuffer_cache: Optimize framebuffer cache management

src/core/CMakeLists.txt, src/core/hle/ipc_helpers.h, src/core/hle/kernel/client_port.cpp, src/core/hle/kernel/client_session.cpp, src/core/hle/kernel/client_session.h, src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/hle_ipc.h, src/core/hle/kernel/object.cpp, src/core/hle/kernel/object.h, src/core/hle/kernel/server_session.cpp, src/core/hle/kernel/server_session.h, src/core/hle/kernel/session.cpp, src/core/hle/kernel/session.h, src/core/hle/kernel/svc.cpp, src/core/hle/service/nfp/nfp.cpp, src/core/hle/service/service.cpp, src/core/hle/service/sm/controller.cpp, src/core/hle/service/sm/sm.cpp, src/core/hle/service/sm/sm.h
* Properly puts threads to sleep on SendSyncRequest, and wakes them in the future.
* Uses a threadsafe queue for IPC requests, which will be helpful for multicore impl.
* More accurate representation of Session, ClientSession, and ServerSession kernel objects.
* ClientPort() should only be used for named ports.
=> kernel: Implement a more accurate IPC dispatch.

src/core/telemetry_session.cpp
First add a constexpr temporary to avoid passing always the same field type.
Hardcode OpenGL as the renderer backend for telemetry.
=> telemetry_session: Report renderer backend

CMakeLists.txt
This fixes the builds from early-access source drops on Windows (tested on EA 58). CMake was previously looking for git-related files that were stripped out of the early access builds and failing; check if those exist before reading them.
=> [EA source]: Ignore git-related files in cmake for early access tarballs

src/core/core_cpu.cpp, src/core/hle/kernel/scheduler.cpp
This commit corrects an error in which a Core could remain with an exclusive state after running, leaving space for possible race conditions between changing cores.
This finally fixes the Mutex Corruption problem worked around in: #2365
=> CpuCore: Clear exclusive state after doing a run in dynarmic.

src/video_core/renderer_vulkan/vk_swapchain.cpp, src/video_core/renderer_vulkan/vk_swapchain.h
We don't know until the game is running if it's using an sRGB color space or not. Add support for hot-swapping swapchain surface formats.
=> vk_swapchain: Add support for swapping sRGB

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.h, src/video_core/shader/decode/memory.cpp, src/video_core/shader/decode/other.cpp, src/video_core/shader/decode/warp.cpp, src/video_core/shader/node.h, src/video_core/shader/shader_ir.h, src/video_core/shader/track.cpp
Update Sirit and its usage in `vk_shader_decompiler`. Highlights:
- Implement tessellation shaders for Vulkan.
- Implement geometry shaders.
- Implement some missing features.
- Use native half float instructions when available.
=> vk_shader_decompiler: Add tessellation and misc changes

src/core/hle/kernel/svc.cpp, src/core/hle/kernel/svc_wrap.h
These are fairly trivial to implement, we can just do nothing. This also provides a spot for us to potentially dump out any relevant info in the future (e.g. for debugging purposes with homebrew, etc).
=> kernel/svc: Provide implementations for svcDumpInfo/svcDumpInfoNew

src/core/hle/kernel/address_arbiter.cpp, src/core/hle/kernel/address_arbiter.h, src/core/hle/kernel/kernel.cpp
This corrects arbitration threads to behave just like in Horizon OS. They are added into a container and released according to what priority they had when added. Horizon OS does not reorder them if their priority changes.
=> Kernel: Correct behavior of Address Arbiter threads.

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode/other.cpp, src/video_core/shader/node.h
Implement using `memoryBarrier` on GLSL and `OpMemoryBarrier` on SPIR-V.
- Fixes some crashes on Nvidia on Fire Emblem: Three Houses.
=> shader: Implement MEMBAR.GL

src/video_core/renderer_opengl/gl_rasterizer.cpp
This commit ensures the OGL backend does not execute tesselation shader stages as they are currently unimplemented.
=> Gl_Rasterizer: Skip Tesselation Control and Eval stages as they are unimplemented

src/core/hle/kernel/svc.cpp, src/core/hle/kernel/svc_wrap.h
SignalProcessWideKey doesn't actually return a result code, so we can amend our implementation of it to reflect this.
=> kernel/svc: Amend function signature of SignalProcessWideKey

src/video_core/renderer_opengl/gl_shader_cache.cpp
Add missing new-line. This caused shaders using local memory and shared memory to inject a preprocessor GLSL line after an expression (resulting in invalid code).
It looked like this:
```glsl
shared uint smem[8];#define LOCAL_MEMORY_SIZE 16
```
It should look like this (addressed by this commit):
```glsl
shared uint smem[8];
#define LOCAL_MEMORY_SIZE 16
```
=> gl_shader_cache: Add missing new-line on emitted GLSL

src/video_core/renderer_opengl/gl_device.cpp
Previously we naively checked for "Intel" in GL_VENDOR, but this includes both Intel's proprietary driver and the mesa driver. Re-enable compute shaders for mesa.
=> gl_device: Enable compute shaders for Intel Mesa drivers

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/shader/decode/texture.cpp, src/video_core/shader/shader_ir.h
This PR corrects a series of bugs in TLD4S, TextureGather in glsl as well as make sure failed bindless samplers default to 0.
=> Corrections and fixes to TLD4S & Bindless samplers failing

src/video_core/engines/shader_bytecode.h
Fixes TLD4S's encoding to match nouveau's [documentation](https://github.com/envytools/envytools/blob/305c1dddf579da68a58b211ac80687b4fd67b476/envydis/gm107.c#L1951).
=> shader_bytecode: Fix TLD4S encoding

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
`gl_shader_decompiler` was missing a `DeclareImages`. Images were not being declared.
=> gl_shader_decompiler: Add missing DeclareImages

src/video_core/shader/decode/texture.cpp
When a image format mismatches we were inserting zeroes to the texture itself. This was not handling cases were the mismatch uses less coordinates than the guest shader code. Address that by resizing the vector.
=> shader/texture: Properly shrink unused entries in size mismatches

src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
`ExprCondCode` visit implements the generic `Visit`. Use this instead one instead.
As an intended side effect this fixes unwritten memory usages in cases when a negation of a condition code is used.
- Fixes one of the crashes in Vulkan in Fire Emblem: Three Houses (the other crash is a device loss).
=> vk_shader_decompiler: Use Visit instead of reimplementing it

src/video_core/texture_cache/surface_params.cpp, src/video_core/texture_cache/surface_params.h, src/video_core/texture_cache/texture_cache.h, src/video_core/textures/decoders.h
This commit adds a series of HLE methods for handling 3D textures in general. This helps games that generate 3D textures on every frame and may reduce loading times for certain games.
=> Texture Cache: Add HLE methods for building 3D textures

src/video_core/renderer_vulkan/vk_device.cpp, src/video_core/renderer_vulkan/vk_device.h, src/video_core/renderer_vulkan/vk_resource_manager.cpp, src/video_core/renderer_vulkan/vk_resource_manager.h
Description about the changes in their individual commits.
Add some missing command queries, catches device losses with `VK_NV_device_diagnostic_checkpoints` and implement move constructor and move assignment for `VKFenceWatch`.
=> vk_resource_manager: Catch device losses and other changes

src/video_core/renderer_opengl/gl_shader_cache.cpp
Removes unused return values and invalid commentaries. Not dividing by 4 the size of shared memory is
not a hack; it describes the number of integers, not bytes. While we are at it sort the generated code to put preprocessor lines on the top.
=> gl_shader_cache: Style changes

src/video_core/CMakeLists.txt, src/video_core/engines/maxwell_3d.h, src/video_core/renderer_vulkan/fixed_pipeline_state.cpp, src/video_core/renderer_vulkan/fixed_pipeline_state.h
The intention behind this hashable structure is to describe the state
of fixed function pipeline state that gets compiled to a single graphics
pipeline state object. This is all dynamic state in OpenGL but Vulkan
wants it in an immutable state, even if hardware can edit it freely.
In this commit the structure is defined in an optimized state (it uses
booleans, has paddings and many data entries that can be packed to
single integers). This is intentional as an initial implementation that
is easier to debug, implement and review. It will be optimized in later
stages, or it might change if Vulkan gets more dynamic states.
=> fixed_pipeline_state: Define structure and loaders

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_shader_manager.h
Rendering without a fragment shader is usually used in depth-only passes.
Fixes shadows artifacts in some instances on PLGE:
And removes some of the artifacts in LM3 (this previously something like a button drawn in the floor):
=> gl_rasterizer: Allow rendering without fragment shader

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp, src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
The job of this abstraction is to provide staging buffers for temporary
operations. Think of image uploads or buffer uploads to device memory.
It automatically deletes unused buffers.
=> vk_staging_buffer_pool: Add a staging pool for temporary operations

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/vk_image.cpp, src/video_core/renderer_vulkan/vk_image.h
This object's job is to contain an image and manage its transitions.
Since Nvidia hardware doesn't know what a transition is but Vulkan
requires them anyway, we have to state track image subresources
individually.
To avoid the overhead of tracking each subresource in images with many
subresources (think of cubemap arrays with several mipmaps), this commit
tracks when subresources have diverged. As long as this doesn't happen
we can check the state of the first subresource (that will be shared
with all subresources) and update accordingly.
Image transitions are deferred to the scheduler command buffer.
=> vk_image: Add an image object abstraction

src/video_core/engines/shader_bytecode.h, src/video_core/shader/decode/register_set_predicate.cpp
P2R dumps predicate or condition codes state to a register. This is useful for unit testing.
It's not known to be used in retail games or homebrew.
=> shader/p2r: Implement P2R Pr

src/video_core/renderer_opengl/maxwell_to_gl.h
Many of these topologies are exclusively available in OpenGL.
=> maxwell_to_gl: Implement missing primitive topologies

src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp, src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
This commit corrects a padding value in Ioctl Remap that was actually an offset to the mapping address.
**Thanks to Gdkchan for finding the issue.**
=> NvServices: Correct Ioctl Remap.

src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/node.h, src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h
This commit introduces a mechanism by which shader IR code can be amended and extended. This useful for track algorithms where certain information can derived from before the track such as indexes to array samplers.
=> Shader_IR: add the ability to amend code in the shader ir.

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/vk_descriptor_pool.cpp, src/video_core/renderer_vulkan/vk_descriptor_pool.h
Create a large descriptor pool where we allocate all our descriptors
from. It has to be wide enough to support any pipeline, hence its large
numbers.
If the descritor pool is filled, we allocate more memory at that moment.
This way we can take advantage of permissive drivers like Nvidia's that
allocate more descriptors than what the spec requires.
=> vk_descriptor_pool: Initial implementation

src/core/hle/service/nvflinger/nvflinger.cpp, src/video_core/gpu.cpp, src/video_core/gpu.h
This function is called rarely and blocks quite often for a long time.
So don't waste power and let the CPU sleep.
This might also increase the performance as the other cores might be allowed to clock higher.
=> video_core: Block in WaitFence.

src/core/arm/dynarmic/arm_dynarmic.cpp, src/core/memory.cpp
This saves us two x64 instructions per load/store instruction.
TODO: Clean up our memory code. We can use this optimization here as well.
=> core/memory + arm/dynarmic: Use a global offset within our arm page table.

src/yuzu/bootmanager.cpp
MakeCurrent is a costly call (according to Nsight's profiler it takes a tenth of a millisecond to complete), and we don't have a reason to call it because:
- Qt no longer signals a warning if it's not called
- yuzu no longer supports macOS
=> yuzu/bootmanager: Remove {glx,wgl}MakeCurrent on SwapBuffers

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/vk_renderpass_cache.cpp, src/video_core/renderer_vulkan/vk_renderpass_cache.h, src/video_core/renderer_vulkan/vk_update_descriptor.cpp, src/video_core/renderer_vulkan/vk_update_descriptor.h
This PR adds two new abstractions required to add the pipeline cache in a future PR. Description in individual commits.
=> vk_update_descriptor/vk_renderpass_cache: Add pipeline cache dependencies

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/fixed_pipeline_state.cpp, src/video_core/renderer_vulkan/fixed_pipeline_state.h, src/video_core/renderer_vulkan/vk_compute_pipeline.cpp, src/video_core/renderer_vulkan/vk_compute_pipeline.h, src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp, src/video_core/renderer_vulkan/vk_graphics_pipeline.h, src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.h, src/video_core/renderer_vulkan/vk_rasterizer.h
This PR adds Vulkan's pipeline cache (not to be confused with a disk pipeline cache). Detailed description about it in the respective commit.
There are chunks of code we can share between OpenGL's shader cache and Vulkan's pipeline cache that are duplicated here. These should be moved to a common helper file in a future contribution.
=> vk_pipeline_cache: Initial implementation

src/core/hle/kernel/process.cpp
module._memory was already moved over to a new shared_ptr.
So code_memory_size was not increased at all.
This lowers the heap space and so saves a bit of memory, usually between 50 to 100 MB.
This fixes a regression of c0a01f3adc466d07fc27020048e82cca60988970
=> core/kernel: Fix GetTotalPhysicalMemoryUsed.

src/video_core/shader/decode/memory.cpp, src/video_core/shader/shader_ir.h
Using the same technique we used for u8 on LDG, implement u16.
In the case of STG, load memory and insert the value we want to set
into it with bitfieldInsert. Then set that value.
=> shader_ir/memory: Implement u16 and u8 for STG and LDG

src/yuzu/configuration/configure_hotkeys.cpp
Just a simple UX tweak. Resize hotkeys `Action` column to fit text after populate to avoid ellipsis trim.
Screenshot shows Configuration window with initial width.
=> GUI/configure: resize hotkeys action column to fit content

src/video_core/renderer_opengl/gl_shader_cache.cpp
Removes two unused variables, one of which was previously unable to be removed by compiler optimizations, since it contained `std::vector` instances which have non-trivial destructors.
While we're at it, we can also `std::move` the `entries` parameter of CachedShader to prevent unnecessary copies from occurring in almost all cases.
=> gl_shader_cache: Remove unused variables

src/video_core/shader/control_flow.cpp
Organizes the initializer list in the same order that the variables would actually be initialized in.
=> control_flow: Silence -Wreorder warning for CFGRebuildState

src/video_core/renderer_opengl/utils.cpp, src/video_core/renderer_opengl/utils.h
Keeps the definitions hidden and allows changes to the structs without needing to recompile all users of classes containing said structs. While we're in the same area we can also remove unnecessary inclusions.
=> renderer_opengl/utils: Forward declare private structs 

src/video_core/engines/maxwell_3d.h
This isn't used outside of the class itself, so we can make it private for the time being.
=> maxwell_3d: Make dirty_pointers private

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/vk_staging_buffer_pool.h, src/video_core/renderer_vulkan/vk_texture_cache.cpp, src/video_core/renderer_vulkan/vk_texture_cache.h, src/video_core/texture_cache/surface_params.h
It currently ignores PBO linearisations since these should be dropped as soon as possible on OpenGL.
=> vk_texture_cache: Implement generic texture cache on Vulkan

src/video_core/texture_cache/format_lookup_table.cpp
Component types for ZF32_X24S8 were using UNORM. Drivers will set FLOAT, UINT, UNORM, UNORM; causing a format mismatch. This commit addresses that.
- Used by Atelier Ryza
=> format_lookup_table: Fix ZF32_X24S8 component types

src/video_core/renderer_opengl/gl_texture_cache.cpp
Fixes some internal formats and formats in the table that were wrong. No known visible changes were found.
=> gl_texture_cache: Minor fixes and style changes

src/common/telemetry.cpp, src/common/x64/cpu_detect.cpp, src/common/x64/cpu_detect.h
The information is duplicated in the brand string and the telemetry field is unused.
Already worked with flame sage to make this field optional as well.
=> Remove unused CPU Vendor string and telemtry field

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode/memory.cpp, src/video_core/shader/node.h
Add ATOMS encoding and implement the ADD U32 variant. We can add the other variants as we find them, although I'm planning on writing unit tests for these.
With our current approach, S32 variants will have to spin to be implemented. Luckily these are not common.
* Used by Atelier Ryza.
=> shader/memory: Implement ATOMS.ADD.U32

src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_state.cpp, src/video_core/renderer_opengl/gl_state.h
For gl_PointSize to have effect we have to activate GL_PROGRAM_POINT_SIZE.
This is one of the reasons why SMO's fog doesn't work on OpenGL. The other reason remains unknown for now.
=> gl_state: Implement PROGRAM_POINT_SIZE

src/core/hle/kernel/physical_memory.h, src/core/hle/kernel/vm_manager.cpp, src/core/loader/elf.cpp, src/core/loader/kip.cpp, src/core/loader/nso.cpp, src/core/memory.cpp, src/core/memory.h
This pull requests tries to simplify the interface of PhysicalMemory. PhysicalMemory is currently a std::vector, but it shall be replaced with a custom allocator with mirrored mapping support. So it shall be able to be used for fastmem.
=> core/hle/kernel: Simplify PhysicalMemory usages.

src/yuzu/main.cpp, src/yuzu/main.ui
Currently hotkeys listed below are not displayed with corresponding entries in yuzu main menu:
* File -> Load Amiibo
* Emulation -> Restart 
* Tools -> Capture Screenshot
This PR adds those missing shortcuts and a separator between `Show status bar` and `Debugging` group in `View` menu.
=> GUI: add few missing hotkeys to main menu

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_state.h
This fixes template resolution considering GLboolean an integer instead
of a bool.
=> gl_state: Use bool instead of GLboolean

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/renderer_vulkan.h, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_rasterizer.h
This abstraction is Vulkan's equivalent to OpenGL's rasterizer. It takes care of joining all parts of the backend and rendering accordingly on demand. I am aware of the large diff.
After this, we are only missing `renderer_vulkan`, `vk_blit_screen` and the Qt and SDL2 frontends.
=>  vk_rasterizer: Implement Vulkan's rasterizer 

src/video_core/engines/maxwell_3d.cpp, src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Front face was being forced to a certain value when cull face is
disabled. Set a default value on initialization and drop the forcefully
set front facing value with culling disabled.
=> vk_graphics_pipeline: Set front facing properly

src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
Also updates sirit to include atomic instructions.
=> vk_shader_decompiler: Implement UAtomicAdd (ATOMS) on SPIR-V

src/yuzu/configuration/configure_gamelist.cpp, src/yuzu/configuration/configure_gamelist.h, src/yuzu/game_list_p.h
Currently user can achieve single row entries on the game list by selecting same option twice in configuration panel. Inspired by Citra I have implemented a bit user friendlier game list row configuration:
* second row has now "None" option
* duplicate options are dynamically removed on initial render and on user interaction
I'm not a QT nor C++ expert, I'm sure this could be written better so I'm awaiting reviews and comments ;) 
I have tried few simplifications  (using `curentIndex()` instead of  `currentData()`, avoiding "caching" current selection etc.) but I failed miserably due to some UI glitches or even crashes. Currently committed code, at least for me, working stable and as intended. 
I have left `row1 == row2` condition in `game_list_p.h` for the backward compatibility with …
=> GUI/gamelist: add "None" as an option for second row and remove dynamically duplicate row options

src/yuzu/configuration/configure_dialog.cpp
- We have some important audio settings, makes them more discoverable.
=> yuzu_qt: config: Move audio to its own tab.

src/core/hle/service/time/time_zone_manager.cpp
Fixes timestamp in ZLA and Astral Chain saves.
Thanks CrazyMax for pointing this out.
=> time: Fix month off-by-one error.

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/vk_blit_screen.cpp, src/video_core/renderer_vulkan/vk_blit_screen.h, src/video_core/renderer_vulkan/vk_swapchain.cpp, src/video_core/renderer_vulkan/vk_swapchain.h
This abstraction takes care of presenting accelerated and non-accelerated or "framebuffer" images to the Vulkan swapchain.
The date (2018) is not a typo, that's when it was written.
=> vk_blit_screen: Initial implementation

dist/qt_themes/qdarkstyle/style.qss, src/yuzu/uisettings.cpp
This PR fixes few minor UI issues with dark themes also trying to mimic more "Default" ("Light") mode styling and component sizes to avoid resize on theme change. The following changes has been made:
- mimic "Default" theme list headers styling - use list background color, border omission, no extra padding - **_Screenshot 1_**
- decrease contrast of even rows on the lists to mimic "Default"  theme styling and differentiate those rows more from Status Bar or Filter Bar - **_Screenshot 1_**
- update tabs minimal size and padding to roughly match "Default" theme styling - **_Screenshot 2_**
- fix Main Menu and Context Menu (ex. game row) checkbox position and items padding - **_Screenshot 3_**
- fix ComboBox currently selected value being repositioned on options list open (only "Dark" themes …
=> GUI: fix minor issues with dark themes + rename and reorder themes

src/CMakeLists.txt
See citra-emu/citra#5037 for more details. As I don't have a Linux machine with a toolchain installed, I'm just gonna wait for CI to finish.
This significantly reduces unnecessary disk writes and space usage
when building Citra.
libcore.a is now only ~1MB rather than several hundred megabytes.
=> Port citra-emu/citra#5037: "CMake: Create thin archives on Linux"

src/video_core/renderer_opengl/gl_shader_cache.cpp
This pragma stops Nvidia's driver from over optimizing math (probably using fp16 operations) on places where we don't want to.
Thanks to Ryujinx for finding this workaround.
=> gl_shader_cache: Disable fastmath on Nvidia

CMakeLists.txt, src/common/thread.h, src/core/settings.h, src/input_common/CMakeLists.txt, src/input_common/main.cpp, src/input_common/udp/client.cpp, src/input_common/udp/client.h, src/input_common/udp/protocol.cpp, src/input_common/udp/protocol.h, src/input_common/udp/udp.cpp, src/input_common/udp/udp.h, src/yuzu/configuration/config.cpp, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h
**Requires https://github.com/yuzu-emu/ext-boost/pull/2**.
See https://github.com/citra-emu/citra/pull/4049 for more details.
Even though yuzu doesn't have motion support yet, this PR is still useful for us as it already adds support for the underlying protocol and it also adds the possibility to make touch inputs with a DS4 controller.
=> Port citra-emu/citra#4049: "Input: UDP Client to provide motion and touch controls"

src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.h
Some games like The Legend of Zelda: Breath of the Wild assign
render targets without writing them from the fragment shader. This
generates Vulkan validation errors, so silence these I previously
introduced a commit to set "vec4(0, 0, 0, 1)" for these attachments. The
problem is that this is not what games expect. This commit reverts that
change.
=> vk_shader_decompiler: Disable default values on unwritten render targets

src/common/logging/backend.cpp, src/common/logging/backend.h, src/common/logging/log.h, src/common/string_util.cpp
See citra-emu/citra#5039 for more details.
The title of this PR is slightly misleading as we already weren't using a regex anymore for yuzu. 
Either way, this unifies and simplifies the implementation of this feature.
The regex here is run on the emulation thread, and can cause slowdowns when there is excessive logging. Now the source file path trimming should be done at compile time.
godbolt.org/z/3vqPvB
=> Port citra-emu/citra#5039: "common/logging: don't use regex for path trimming"

src/yuzu/CMakeLists.txt, src/yuzu/configuration/configure.ui, src/yuzu/configuration/configure_dialog.cpp, src/yuzu/configuration/configure_general.cpp, src/yuzu/configuration/configure_general.ui, src/yuzu/configuration/configure_ui.cpp, src/yuzu/configuration/configure_ui.h, src/yuzu/configuration/configure_ui.ui
Taken from https://github.com/yuzu-emu/yuzu/pull/1974.
Unifies the UI with Citra and makes it easier to port translation support.
=> yuzu/configuration: create UI tab and move gamelist settings there

src/core/hle/service/sockets/bsd.cpp, src/core/hle/service/sockets/bsd.h
Required for Little Town Hero to boot further. These stubs should be OK, as BSD issues are fairly easy to track down. Furthermore, we are not planning on properly implementing BSD in the near term.
=> bsd: Stub several more functions.

dist/qt_themes/qdarkstyle/style.qss
This PR introduce a lot of small changes and improvements for dark themes and supplement changes introduced in #3339. Most important things that has been updated:
* user control/interaction elements design has been standardized and proper disabled state for all of them has been added 
* tabs design has been based more on light theme and simplified
* Main Menu and Context Menu has been refined to mimic native menu better and disabled styling has been updated
* game list now dimms instead of being lighten up while loading
Other than that a lot of small tweaks and changes has been applied across whole dark themes stylesheet.
=> GUI: dark themes refinements and QSS cleanup

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This was implemented by #3305 and it's no longer required.
=> gl_shader_decompiler: Remove UNIMPLEMENTED for gl_PointSize

src/video_core/shader/decode/memory.cpp
`.S16` sign extends on loads, but it seems to be the same as `.U16` on stores. Since our IR doesn't support primitives for integers smaller than 32 bits, implement the logic manually. In the future we might want to handle 16 and 8 bit operations at its respective level on the IR and use 32 bits operations on the decompilation step when the target API doesn't support smaller integers.
While we are at it, abstract the code to avoid repeating logic.
- Used by PC Builder Simulator
- Used by Doom 2016
=>  shader/memory: Implement LDL.S16, LDS.S16, STL.S16 and STS.S16

src/core/cpu_manager.cpp, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/physical_core.cpp, src/core/hle/kernel/physical_core.h
shared_ptr was used in 2d1984c due to a misunderstanding of how the language generates move constructors and move assignment operators.
If a destructor is user-provided, then the compiler won't generate the move constructor and move assignment operators by default--they must be explicitly opted into.
The reason for the compilation errors is due to the fact that the language will fall back to attempting to use the copy constructor/copy assignment operators if the respective move constructor or move assignment operator is unavailable.
Given that we explicitly opt into them now, the the move constructor and move assignment operators will be generated as expected.
While we're at it, we can do a little bit of tidying up.
=> kernel/physical_core: Make use of std::unique_ptr instead of std::shared_ptr

src/core/arm/dynarmic/arm_dynarmic.cpp, src/core/arm/unicorn/arm_unicorn.cpp
Now both CPU backends go through their referenced system instance to obtain the current thread. Gets rid of two trivial cases of relying on global state.
=> core/arm: Remove usage of global GetCurrentThread()

src/video_core/CMakeLists.txt, src/video_core/engines/const_buffer_engine_interface.h, src/video_core/engines/kepler_compute.cpp, src/video_core/engines/kepler_compute.h, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/guest_driver.cpp, src/video_core/guest_driver.h, src/video_core/rasterizer_interface.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp, src/video_core/renderer_opengl/gl_shader_disk_cache.h, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/const_buffer_locker.cpp, src/video_core/shader/const_buffer_locker.h, src/video_core/shader/decode.cpp, src/video_core/shader/decode/texture.cpp, src/video_core/shader/node.h, src/video_core/shader/node_helper.h, src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h, src/video_core/shader/track.cpp
This PR Implements the tracking algorithm and deduction of indexed samplers. So far they can only be correctly deduced under the next conditions:
- [Non NVN/Nouveau only] Atleast one shader has been executed with atleast 2 normal bound samplers. (This is used to calculate the sizing of bound texture handlers, it uses default values that are compatible with nouveau and NVN, thus only required for other graphic apis).
- The indexed sampler is bound between two normal samplers.
It still does not work properly on the next case:
- The indexed sampler is the last bound sampler in the shader. In this case, we default to a size of only 1 as it's the only guarantee. A method that works on every driver is being tested and will be adressed in a future PR.
=> Partially implement Indexed samplers in general and specific code in GLSL

src/video_core/shader/ast.h, src/video_core/shader/decode/arithmetic_integer.cpp, src/video_core/shader/decode/texture.cpp, src/video_core/shader/node.h, src/video_core/shader/track.cpp
These objects are `shared_ptr`s and don't require an explicit initializer.
=> shader: Remove curly braces initializers on shared pointers

src/input_common/main.cpp, src/input_common/udp/client.cpp, src/input_common/udp/client.h, src/input_common/udp/protocol.h, src/input_common/udp/udp.cpp, src/input_common/udp/udp.h
Individual minor changes to the UDP backend that don't really warrant their own PRs by themselves.
Each commit should be fairly self-contained, so they can be reviewed individually. Notably, this corrects the fact that the UDP backend would never actually get shutdown whenever Shutdown() was called.
=> input_common/udp: Minor changes

src/video_core/renderer_vulkan/vk_rasterizer.cpp
Removes bounds checking from "texceptions" instances.
=> vk_rasterizer: Use noexcept methods of std::bitset

src/core/hle/kernel/svc.cpp, src/core/hle/kernel/transfer_memory.cpp, src/core/hle/kernel/transfer_memory.h, src/core/hle/kernel/vm_manager.cpp, src/core/hle/kernel/vm_manager.h, src/core/hle/kernel/wait_object.cpp, src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h, src/core/hle/service/am/applets/applets.cpp, src/core/hle/service/am/applets/error.cpp, src/core/hle/service/am/applets/general_backend.cpp, src/core/hle/service/am/applets/profile_select.cpp, src/core/hle/service/am/applets/software_keyboard.cpp, src/core/hle/service/am/applets/web_browser.cpp
Supersedes #2710. Fixes:
* Properly reserve and reset TransferMemory region -- this would lead to a hard crash when trying to read the transfer memory.
* Clear events on PopOutData and PopInteractiveOutData.
* Correct a miscounted IPC header in am.
* Add a missing state changed event signal in interactive applet -- fixes a softlock for some games.
* Make wait object wake on any signalled thread, not all -- fixes softlock with applet as sdk code waits on two events that are mutually exculsive. This fixes a bug introduced by #2416.
* Various cleanup.
Thanks to @DarkLordZach for some of the fixes here.
Will tag this one as mainline, to not regress Pokemon in the main release channel.
Fixes pre-entered text in software keyboard:
=> applets: Fixes for software keyboard and transfer memory.

src/video_core/engines/shader_bytecode.h, src/video_core/shader/decode/shift.cpp
Implement left and right variants. This implementation avoids undefined behaviour between (shifting values larger than 32) and using 64 bit integers.
In pseudo-code this instruction does:
```c
u32 low = ...;
u32 high = ...;
u64 value = (u64)low | (u64)high << 32;
if (.L)
return (u32)((value << shift) >> 32);
else
return (u32)(value >> shift);
=> shader/shift: Implement SHF

src/video_core/gpu_thread.h
- Necessary for multiple service threads.
=> gpu_thread: Use MPSCQueue for GPU commands.

src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_ui.cpp, src/yuzu/configuration/configure_ui.ui, src/yuzu/game_list_worker.cpp, src/yuzu/uisettings.h
Removes the option "Show files with type 'Unknown'" as this option serves no functional purpose other than clutter the games list and providing a bad UX.
=> Remove option "Show files with type 'Unknown'"

src/video_core/engines/maxwell_3d.h
Back face stencil mask and stencil function mask were flipped.
Thanks to gdkchan from [Ryujinx](https://github.com/Ryujinx/Ryujinx) to help me confirm this fix.
* Fixes `ONINAKI`
=> maxwell_3d: Fix stencil back mask

src/core/hle/kernel/thread.cpp
We can just use the kernel member variable directly instead of going through the system to obtain the same thing.
=> kernel/thread: Remove trivial usages of the global system accessor

src/core/hle/service/bcat/backend/backend.cpp
A formatting specifier within Clear wasn't being used, which will cause fmt to throw an exception. This fixes that.
=> bcat/backend: Prevent fmt exception in debug log within NullBackend::Clear()

src/core/hle/kernel/address_arbiter.cpp, src/core/hle/kernel/address_arbiter.h
We can just leverage `std::find_if` in `InsertThread()` and `RemoveThread()` to collapse the manual looping. `GetThreadsWaitingOnAddress()` can also be simplified and turned into a const member function.
=> address_arbiter: Minor cleanup to list querying

src/video_core/gpu.cpp, src/video_core/memory_manager.cpp, src/video_core/memory_manager.h
Reverts yuzu-emu/yuzu#3386
For KeplerMemory, we need flushing to be synchronous.
=> Revert "video_core: memory_manager: Use GPU interface for cache functions."

src/core/hle/service/ldn/ldn.cpp
Rename incorrect function `SetOperationMode` to `Initialize2` follow https://switchbrew.org/wiki/LDN_services#IUserLocalCommunicationService
Fix issue #3119 by stubbed Initialize2 function. Help Pokemon sword pass this crash.
=> IUserLocalCommunicationService: stub function Initialize2

CMakeLists.txt
Previous commit led to a regression for Arch Linux users. This patch should fix that issue. See [here](https://discourse.libsdl.org/t/arch-linux-cmake-find-package-sdl2-required-passes-but-doesnt-find-anything/24226/2) and [here](https://github.com/tsoding/nothing/issues/923#issuecomment-506370650) for more information. Fixes #3426.
=> Fix CMake build errors for certain SDL2 installations

src/core/frontend/framebuffer_layout.cpp, src/core/frontend/framebuffer_layout.h, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_graphics.cpp, src/yuzu/configuration/configure_graphics.ui, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h, src/yuzu_tester/config.cpp, src/yuzu_tester/default_ini.h
Supersedes #3404 and closes #2427, credit to @Margen67 for discovering the relevant line modification. Special thanks to @raven02 for the initial PR(s).
16:9 (Default)
21:9
Stretch to Window
=> GUI: Add aspect ratio dropdown

src/video_core/CMakeLists.txt, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/query_cache.h, src/video_core/rasterizer_interface.h, src/video_core/renderer_opengl/gl_query_cache.cpp, src/video_core/renderer_opengl/gl_query_cache.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_resource_manager.cpp, src/video_core/renderer_opengl/gl_resource_manager.h, src/video_core/renderer_vulkan/vk_device.cpp, src/video_core/renderer_vulkan/vk_query_cache.cpp, src/video_core/renderer_vulkan/vk_query_cache.h, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_rasterizer.h, src/video_core/renderer_vulkan/vk_scheduler.cpp, src/video_core/renderer_vulkan/vk_scheduler.h
Queries are a method to write information from the GPU to GPU and CPU visible memory. The most common types of queries are counters, timestamps and fences.
Khronos' APIs (OpenGL and Vulkan) use ranged queries with the following model:
```
BeginQuery();
Draw();
EndQuery();
value = AskValue();
```
Meanwhile NVN and hardware "queries" do this:
```
ResetCounter();
Draw();
value = AskValue();
```
To emulate this behaviour we add up previous queries to the current ones on request.
Asking for a query value is a costly operation, not because of the action of reading the value itself but because they are a blocking call. It doesn't have to wait for all GPU operations, only until the ranged query was ended. To minimize this cost this PR delays the query up it's read by the CPU.
This is done through …
=> query_cache: Implement a query cache and query 21 (samples passed)

src/video_core/engines/maxwell_3d.cpp, src/video_core/rasterizer_interface.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_rasterizer.h
Pass instanced state of a draw invocation as an argument instead of
having two separate virtual methods.
=> maxwell_3d: Unify draw methods

externals/httplib/README.md, externals/httplib/httplib.h, src/core/hle/service/bcat/backend/boxcat.cpp, src/web_service/web_backend.cpp
Some linux users (#3048) report segfaults using the mainline builds that seem to trace back to older versions of httplib being [incompatible with OpenSSL 1.1](https://github.com/yhirose/cpp-httplib/pull/243). For me, this only occurred on the provided binaries and not on built images, so without a DevOps build, I can't confirm that this fixes the issue.
It's worth noting the latest version of cpp-httplib is 0.5.5, however v0.5 introduces breaking changes that prevented yuzu from building. Anyone more familiar is obviously welcome to rectify the code that uses httplib to work with they latest version if they want.
=> Update httplib to 0.5.5

src/video_core/shader/decode/texture.cpp
Fix typo in the illegal 3D texture assert logic. We care about catching
arrayed 3D textures or 3D shadow textures, not regular 3D textures.
=> shader/texture: Fix illegal 3D texture assert

src/core/CMakeLists.txt, src/core/core.cpp, src/core/core.h, src/core/hardware_properties.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/scheduler.cpp, src/core/hle/kernel/scheduler.h, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h, src/core/hle/kernel/time_manager.cpp, src/core/hle/kernel/time_manager.h
This PR introduces TimeManager and SchedulerLocks to the kernel, also known as Critical Sections (This are private within the global scheduler)
=> Kernel: Refactors and Implement a TimeManager and SchedulerLocks

src/video_core/gpu.h, src/video_core/surface.cpp
Thanks to @neico from pointing this out in #3417
- Used by Fire Emblem: Three Houses
=> video_core/surface: Add R32_SINT render target format

src/video_core/shader/decode/arithmetic_integer.cpp
Fix black texture on Kirby Star Allies
Before: 
After:
Thanks @ReinUsesLisp for pointing me what is wrong :D
Link ref: https://devtalk.nvidia.com/default/topic/1070081/cuda-programming-and-performance/reverse-lut-for-lop3-lut/
=> shader: implement LOP3 fast replace for old function

src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h
Closes #2719 
This command was mistakenly called SwitchLcdBacklight, according to sdk symbols and switchbrew it is actually called SetLcdBacklighOffEnabled. Note: The service command name is not a typo, it is missing the 't' in "Backlight".
This command sets whether the LCD backlight is turned on or off, however, this is stubbed for now since backlight services needs to be implemented #2542.
If the bool is true, the backlight turns off
If the bool is false, the backlight turns on
=> AM/ICommonStateGetter: Stub SetLcdBacklighOffEnabled

README.md
See citra-emu/citra#5097 for more details.
- Discord is generally the preferred method for developer communication now
- fixed a typo in contributor info
- 3D output is working, but not very popular. if we want to keep that part, VR headsets would probably be more relevant.
- neobrain is no longer active in the project and probably shouldn't be contacted for donations
- firmware version is no longer relevant for homebrew purposes
pinging @bunnei because I'm not sure whether he is still the one to contact for console donations (not that we ever get any)
=> Port citra-emu/citra#5097: "Update README.md"

src/video_core/renderer_opengl/maxwell_to_gl.h, src/video_core/renderer_vulkan/maxwell_to_vk.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
While changing this, fix an assert in vk_shader_decompiler. We now know scaled formats are expected to be float in shaders attributes.
=> video_core: Implement more scaled attribute formats

src/core/CMakeLists.txt, src/core/arm/arm_interface.h, src/core/arm/dynarmic/arm_dynarmic_32.cpp, src/core/arm/dynarmic/arm_dynarmic_32.h, src/core/arm/dynarmic/arm_dynarmic_64.cpp, src/core/arm/dynarmic/arm_dynarmic_64.h, src/core/arm/dynarmic/arm_dynarmic_cp15.cpp, src/core/arm/dynarmic/arm_dynarmic_cp15.h, src/core/arm/exclusive_monitor.cpp, src/core/arm/unicorn/arm_unicorn.cpp, src/core/arm/unicorn/arm_unicorn.h, src/core/core_manager.cpp, src/core/gdbstub/gdbstub.cpp, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/physical_core.cpp, src/core/hle/kernel/physical_core.h, src/core/hle/kernel/process.cpp, src/core/hle/kernel/scheduler.cpp, src/core/hle/kernel/scheduler.h, src/core/hle/kernel/svc.cpp, src/core/hle/kernel/svc_wrap.h, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h, src/core/loader/deconstructed_rom_directory.cpp, src/core/reporter.cpp, src/yuzu/debugger/wait_tree.cpp
**NOTE: No 32-bit games will run with these changes alone!**
These are the very initial changes to boot A32 games. With these changes we:
* Remove error checks on loading 32-bit games
* Refactor ARM interface to support 32-bit and 64-bit JIT backends
* Implement a 32-bit ARM interface, based on Citra's armv6 Dynarmic backend
* Implement several 32-bit SVCs
With these changes, Mario Kart 8 Deluxe will load, boot, and initialize a few services. We quickly get blocked on unimplemented CPU instructions.
With regards to missing ARM functionality -- you'll need to implement the following instructions in Dynarmic for these changes to work: `LDAB`, `LDAEX`, `STLB`, `STLEX`. After this, armv7 VFP needs to be implemented -- the first instruction we are blocked on is `VMOV`.
Credit to @FearlessTobi …
=> Refactoring to boot A32 games

src/video_core/shader/track.cpp
It fixed opcode LD, LDG on Pokemon Sword that can't find the constant buffer. Not sure if it helps any on visual.
=> shader_decode: Fix LD, LDG when track constant buffer

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_vulkan/vk_compute_pipeline.cpp, src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.h, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/node.h
Implement accessing textures through an index. It uses the same
interface as OpenGL, the main difference is that Vulkan bindings are
forced to be arrayed (the binding index doesn't change for stacked
textures in SPIR-V).
This doesn't fix LM3 reflections on Vulkan. There might be a bug some where else.
=> vk_shader_decompiler: Implement indexed textures

src/video_core/renderer_vulkan/maxwell_to_vk.cpp
A1B5G5R5U formats on Vulkan can't do storage operations (GLSL's imageStore/imageLoad), remove the requirement for this capability.
=> maxwell_to_vk: Remove Storage capability for A1B5G5R5U

src/core/settings.h, src/video_core/renderer_opengl/gl_sampler_cache.cpp, src/video_core/textures/texture.h, src/yuzu/CMakeLists.txt, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure.ui, src/yuzu/configuration/configure_dialog.cpp, src/yuzu/configuration/configure_graphics.cpp, src/yuzu/configuration/configure_graphics.ui, src/yuzu/configuration/configure_graphics_advanced.cpp, src/yuzu/configuration/configure_graphics_advanced.h, src/yuzu/configuration/configure_graphics_advanced.ui, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h, src/yuzu_tester/config.cpp, src/yuzu_tester/default_ini.h
Closes #3447, credit to @Margen67 for finding out the appropriate value.
1. This PR adds a new `Advanced` tab in the `Graphics` section of the `Configure` menu
This moves both the `Use Accurate GPU emulation` and `Force 30 FPS mode` options to the advanced tab.
2. This PR adds an experimental `Anisotropic Filtering` dropdown under the `Advanced Graphics Settings` allowing you to select between the Default, 2x, 4x, 8x, and 16x options. However, this setting cannot be changed when in game. (The dropdown will be grayed out when a game is running)
Please note that this setting **may break rendering in some games**, so it is recommended to leave it at the default setting.
Comparisons courtesy of @BSoDGamingYT
Fire Emblem Three Houses
https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.h …
=> frontend/Graphics: Add "Advanced" graphics tab and experimental Anisotropic Filtering support

src/video_core/textures/texture.h
Previous code could generate an anisotropy value way higher than x16.
=> textures: Fix anisotropy hack

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/gl_shader_manager.h, src/video_core/renderer_opengl/renderer_opengl.cpp
After a compute shader was set to the pipeline, no graphics shader was
invoked again. To address this use glUseProgram to bind compute shaders
(without state tracking) and call glUseProgram(0) when transitioning out
of it back to the graphics pipeline.
- Fixes ZLA on OpenGL.
=> gl_shader_manager: Fix interaction between graphics and compute

src/core/frontend/framebuffer_layout.cpp, src/core/frontend/framebuffer_layout.h
There's no reason to use enum here.
May address #3493.
=> framebuffer_layout.h: drop the use of enum for screen dimensions

src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
Adds support for "disabled" uniform buffers on Vulkan. This matches our current OpenGL behaviour of returning zeroes when these are read from a shader.
=> vk_rasterizer: Support disabled uniform buffers

src/video_core/renderer_vulkan/vk_rasterizer.cpp
This should use Maxwell3D engine. Fixed some GPU error on Kirby and maybe other games.
=> vk_rasterizer: fix mistype on SetupGraphicsImages

src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_state_tracker.cpp, src/video_core/renderer_opengl/gl_state_tracker.h, src/video_core/renderer_opengl/maxwell_to_gl.h, src/video_core/renderer_opengl/renderer_opengl.cpp
This uses `GL_NV_fill_rectangle` to implement fill rectangles. Emulating this on other vendors is not trivial and it's not implemented here.
=> gl_rasterizer: Implement polygon modes and fill rectangles

CMakeModules/GenerateSCMRev.cmake, src/common/CMakeLists.txt, src/video_core/CMakeLists.txt, src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_device.cpp, src/video_core/renderer_vulkan/vk_device.h, src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.h, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_rasterizer.h, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.h, src/video_core/shader/transform_feedback.cpp, src/video_core/shader/transform_feedback.h
This PR implements transform feedbacks for its most common usage. This won't work if games do anything of the following:
- Feedback more than one draw.
- Draw feedbacks (`glDrawTransformFeedback`).
- Use transform feedback queries in a meaningful way.
- Stream to multiple buffers in a geometry shader.
- Output a different topology than what `glDraw*` emits.
- Use a non-zero output buffer on Vulkan.
This implementation works for POKKEN, Donkey Kong Tropical Freeze and Xenoblade Chronicles to some extent.
This PR includes #3473, the first commit is 59c1475.
=> video_core: Initial implementation of transform feedbacks

src/common/page_table.cpp, src/common/page_table.h, src/video_core/memory_manager.h
This PR aims to reduce the memory usage in the CPU page table by moving GPU specific parameters into a child class. This saves 1Gb of Memory for most games.
=> PageTable: move backing addresses to a children class as the CPU page table does not need them.

src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/renderer_opengl.cpp
This change adds a GPU debug mode where output frames are kept synchronized with the GPU thread. This is needed to fix GPU debuggers such as RenderDoc, which was broken due to how #3430 works. This mode is automatically activated by checking `GL_EXT_debug_tool`.
=> renderer_opengl: Keep frames synchronized when using a GPU debugger.

src/video_core/engines/shader_bytecode.h, src/video_core/shader/decode/bfe.cpp, src/video_core/shader/node_helper.cpp
This PR reimplement BFE instruction set. Still missing ~~BREV and~~ Rd.CC tho.
As always thank to @ReinUsesLisp
=> shader_decode: Reimplement BFE instructions

src/video_core/renderer_vulkan/vk_rasterizer.cpp
End can be equal to start in CalculateVertexArraysSize. This is quite
common when the vertex size is zero.
=> vk_rasterizer: Fix vertex range assert

src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/renderer_opengl.cpp
Use getenv to detect Nsight.
While we are at it, move the logic to detect debugging tools outside of `Device`. This way we avoid initializing two instances.
=> renderer_opengl: Detect Nvidia Nsight as a debugging tool

src/video_core/renderer_vulkan/maxwell_to_vk.cpp
=> maxwell_to_vk: Implement RG32 and RGB32 integer vertex formats

src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.h, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_rasterizer.h
Reimplements rasterizer's `Clear` using `vkCmdClearAttachments`. This allows us to implement "scissored" clears and layered clears.
By calling `vkCmdClearAttachments` just after a renderpass has began, validation layers complain about performance concerns of not using CLEAR_OP. This is not addressed by this PR.
=> vk_rasterizer: Implement scissor clears and layered clears

src/video_core/textures/astc.cpp
The major optimization introduced by this PR is to generate a table at compile time for encoders. Generating these at runtime wasted ~55% of the whole process on a 4096x4096 ASTC level.
It's recommended to review this commit by commit (having in mind the last one that fixed some search & replace typos).
=> astc: General changes and optimizations

src/core/hle/service/time/time_zone_content_manager.cpp
There were cases where raw_data didn't contain enough space to hold the zero terminator.
This was caught with -fsanitize=address.
=> time_zone_content_manager: Fix out of bounds read

src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_system.cpp
This was requested bei Rei and BsoD Gaming on Discord. 
Previously, the setting would always go back to Mono after reopening the configuration tab. This is fixed with this PR and the default value is set to Stereo.
This setting still has no use so I'm not really against removing it altogether either.
For now I've chosen to keep it as it exists on the real Switch as well and can be hooked up to our backends sometime in the future.
=> yuzu: Save sound output mode and set it to Stereo by default

src/yuzu/configuration/config.cpp, src/yuzu_cmd/config.cpp
This commit disables the Boxcat backend by default for new users of yuzu.
There's several reasons as to why this is done:
1. Boxcat currently only actually has an impact on 3 games and doesn't influence any core mechanics of them
2. It causes a plethora of issues when enabled such as games like Crash Team Racing, Diablo 3 and Tales of Vesperia not booting at all or hanging
3. It causes https://github.com/yuzu-emu/yuzu/issues/2957 to happen. This makes the configuration menu totally unusable for many Linux users of yuzu
I think those points show that currently the negative impact of Boxcat outweighs its benefits and should therefore be disabled by default.
For users who are eager to use the extra features provided by it, they can still just turn it on in the settings.
=> bcat: Disable Boxcat backend by default

src/input_common/udp/client.cpp
Should fix https://github.com/yuzu-emu/yuzu/issues/3487.
error_code::failed is a function which has been introduced in Boost 1.69.
This version of boost hasn't landed in most major distros yet.
=> input_common/udp: Fix Linux build by using a backwards compatible way of error checking

src/core/hle/service/am/applets/web_browser.cpp
Currently, yuzu just freezes when an error occurs while Initializing the WebApplet.
From a user perspective, this obviously isn't great as the game just softlocks.
With this change, yuzu will call the Finalize method, so to the game it seems like as the user just exited the WebApplet normally.
This works around https://github.com/yuzu-emu/yuzu/issues/2852.
=> core/web_browser: Allow WebApplet to exit gracefully when an error occurs

src/core/hle/service/sm/controller.cpp
This increases the PointerBufferSize as a lager one is required by some services.
This change is still not hw-accurate, but it is proven to work in Ryujinx.
Instead of using a hardcoded size, we should figure out the specific values for each service in the future. Some of them can be taken from [Atmosphere](https://github.com/Atmosphere-NX/Atmosphere/search?q=PointerBufferSize). 
Thanks to @jduncanator for finding this issue in the first place.
=> sm/controller: Increase PointerBufferSize

src/video_core/renderer_opengl/gl_rasterizer.cpp
Implement depth ranges using the transformed viewport instead of the
generic one. This matches the current Vulkan implementation but doesn't
support negative depth ranges. An update to glad is required for this.
Partially fixes a regression caused by #3529 and #3542 on OpenGL. The other fix required to address the regressions on Super Mario Odyssey are described in #3542.
=> gl_rasterizer: Use transformed viewport for depth ranges

src/core/core.cpp, src/core/gdbstub/gdbstub.cpp, src/core/gdbstub/gdbstub.h
See citra-emu/citra#5106 for more details.
This fixes https://github.com/yuzu-emu/yuzu/issues/1850, a common issue between citra and yuzu's gdbstub implementation.
Under the citra-qt codebase, during the VideoCore shader initialization, the EmuThread->RunLoop logic, used to emulate the game and, among other things, handle gdbstub packets, is frozen. This ends up making gdb send back its packet a second time and eventually sending the next packet in the list, in our case qSupported followed by vMustReplyEmpty. By this time gdb is expecting a reply to vMustReplyEmpty, qSupported having been dropped but citra just decided to unfreeze the gdbstub thread and process the packets, replying to the answer of qSupported.
To fix that, I introduced a way to defer the …
=> Port citra-emu/citra#5106: "gdbstub: Ensure gdbstub doesn't drop packets crucial to initialization"

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/shader/shader_ir.cpp, src/video_core/shader/shader_ir.h
Legacy varyings are special attributes carried over in hardware from
the OpenGL 1 and OpenGL 2 days. These were generally used instead of the
generic attributes we use today. They are deprecated or removed from
most APIs, but Nvidia still ships them in hardware.
To implement these, this commit maps them 1:1 to OpenGL compatibility.
- Used by Xash3D.
=> gl_shader_decompiler: Implement legacy varyings

src/video_core/shader/decode/xmad.cpp
This should fix the following build error:
```
/yuzu/src/video_core/shader/decode/xmad.cpp:102:63: error: reference to local binding 'op_b' declared in
enclosing function 'VideoCommon::Shader::ShaderIR::DecodeXmad'
op_b, Immediate(0));
^
/yuzu/src/video_core/shader/decode/xmad.cpp:34:46: note: 'op_b' declared here
auto [is_merge, is_psl, is_high_b, mode, op_b,
^
```
=> xmad: fix clang build error

CMakeModules/CopyYuzuQt5Deps.cmake
Qt does weird things when its missing a qt.conf file, causing me endless headaches when building locally. The "proper" fix is to add a qt.conf file (it can be blank) which sets that directory as the qt root folder for plugin loading, and from there, Qt will check the `plugins` folder for all the plugins. This means that we also need to move the rest of the plugin folders into that new folder.
Please test this before merging. If theres an issue with the build bots, it will cause the UI to fail to load entirely, so its important to test builds from the build bot before merging.
=> Use the correct directory for Qt Plugins

src/yuzu/main.cpp
This removes the "exit lock" popup from yuzu when *pausing* a game.
**Motivation**
The exit lock feature is broken in many ways and doesn't work properly in a lot of games, causing it to appear every time you want to pause the game or stop it, even in places where it wouldn't on Switch.
Additionally, the feature of pausing a game doesn't exist like this on Switch and yuzu should be guaranteed to be deterministic anyway, so pausing the emulation shouldn't be able to interrupt any critical processes in any way.
=> yuzu: Remove exit lock for game pausing

src/video_core/renderer_vulkan/maxwell_to_vk.cpp
One is used in _Call of Juarez: Gunslinger_.
Error log was
```
Debug <Critical> video_core\renderer_vulkan\maxwell_to_vk.cpp:VertexFormat:429: Assertion Failed! Unimplemented vertex format of type=6 and size=15
```
=> maxwell_to_vk: implement signedscaled vertex formats

src/video_core/engines/const_buffer_engine_interface.h
This information is required to properly implement SULD.B. It might also
be handy for all image operations, since it would allow us to implement
them on devices that require the image format to be specified (on
desktop, this would be AMD on OpenGL and Intel on OpenGL and Vulkan).
This is designed to avoid invalidating shader caches, although new commits reading this information may behave improperly if an old cache exists.
=> engines/const_buffer_engine_interface: Store image format and types

src/yuzu/main.cpp
See citra-emu/citra#4906 for more details.
The stuck in fullscreen mode bug happens if the emulated program exits, is fixed by adding [this](https://github.com/citra-emu/citra/compare/master...vvanelslande:hotkey-and-fullscreen-fixes?expand=1#diff-5e8bf22f5c3b3579c402308dd96b7563R888-R894), steps to reproduce:
- Start [FBI](https://github.com/Steveice10/FBI)
- Press START
=> Port citra-emu/citra#4906: "citra_qt: fix the stuck in fullscreen mode"

src/yuzu/main.cpp
See citra-emu/citra#5089 for more details.
From my testing, possibly closes citra-emu/citra#5040. If it does, I'm not sure of the _exact_ reason for it. (Maybe the deprecated widget ignored the focus policy? Or some other bug? Or maybe something to do with how returning focus to the window works?)
I'm not happy with the lack of explanation for the change, but it's somewhat backed by [Qt docs](https://doc.qt.io/archives/qt-5.10/focus.html)
> Since pressing Tab is so common, most widgets that can have focus should support tab focus.
=> Port citra-emu/citra#5089: "Set render window's focus policy to Qt::StrongFocus"

src/video_core/renderer_opengl/gl_rasterizer.cpp
This fixes a regression on Puyo Puyo Tetris. Unlike what I was expecting, it doesn't break Smash Ultimate.
=> gl_rasterizer: Synchronize stencil testing on clears

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/wrapper.cpp, src/video_core/renderer_vulkan/wrapper.h
The intention behind a Vulkan wrapper is to drop Vulkan-Hpp.
The issues with Vulkan-Hpp are:
- Regular breaks of the API.
- Copy constructors that do the same as the aggregates (fixed recently)
- External dynamic dispatch that is hard to remove
- Alias KHR handles with non-KHR handles making it impossible to use
smart handles on Vulkan 1.0 instances with extensions that were included
on Vulkan 1.1.
- Dynamic dispatchers silently change size depending on preprocessor
definitions. Different files will have different dispatch definitions,
generating all kinds of hard to debug memory issues.
In other words, Vulkan-Hpp is not "production ready" for our needs and
this wrapper aims to replace it without losing RAII and exception
safety. Not being able to update our Vulkan headers due to …
=> renderer_vulkan/wrapper: Add a Vulkan wrapper (part 1 of 2)

src/core/CMakeLists.txt, src/core/hle/service/caps/caps.cpp, src/core/hle/service/caps/caps.h, src/core/hle/service/caps/caps_a.cpp, src/core/hle/service/caps/caps_a.h, src/core/hle/service/caps/caps_c.cpp, src/core/hle/service/caps/caps_c.h, src/core/hle/service/caps/caps_sc.cpp, src/core/hle/service/caps/caps_sc.h, src/core/hle/service/caps/caps_ss.cpp, src/core/hle/service/caps/caps_ss.h, src/core/hle/service/caps/caps_su.cpp, src/core/hle/service/caps/caps_su.h, src/core/hle/service/caps/caps_u.cpp, src/core/hle/service/caps/caps_u.h
Splits caps into caps_a, caps_c, caps_u, caps_sc, caps_ss, and caps_su.
Stubs GetAlbumContentsFileListForApplication (#2720) as it is used in Super Smash Bros. Ultimate World of Light. The crash following this is unrelated. This command is also used when taking a snapshot. However, it calls SaveScreenShotEx0 in caps:su next and crashes due to it also being unimplemented.
=> capsrv: Split Capture services into individual files and stub GetAlbumContentsFileListForApplication

src/video_core/shader/decode/memory.cpp
Silences a warning about not all control paths returning a value.
=> shader/memory: Silence no return value warning

src/core/file_sys/romfs.cpp
Some Unity game, such like Pokemon Mystery Dungeon:DX,  using "Data" as the top directory.
Also see this issue more details -> https://github.com/yuzu-emu/yuzu/issues/3482
=> file_sys: fix LayeredFS error when loading some games made with the Unity

CMakeModules/GenerateSCMRev.cmake, src/yuzu/about_dialog.cpp, src/yuzu/main.cpp
I noticed some time ago that the "human-readable" yuzu version was missing from the log and about section. This PR aims to fix that by "hacking together" the required parameter directly into GenerateSCMRev.cmake instead of modifying every single CI to pass the correct argument to cmake.
I tested this against Mainline, i hope it works in the Patreon repo too, as i couldn't test it being that it isn't public.
=> Log version and about section version fix

src/yuzu/configuration/configure_input_player.ui
Thanks to @Morph1984 for pointing this out!
When I made #3579 I messed up the placement of SL and SR when you select a single joycon.
Current:
New:
=> configuration: Fix placement of SL and SR

src/common/CMakeLists.txt, src/common/dynamic_library.cpp, src/common/dynamic_library.h, src/core/frontend/emu_window.h, src/video_core/renderer_vulkan/declarations.h, src/video_core/renderer_vulkan/renderer_vulkan.cpp, src/video_core/renderer_vulkan/renderer_vulkan.h, src/video_core/renderer_vulkan/vk_device.cpp, src/video_core/renderer_vulkan/vk_device.h, src/yuzu/CMakeLists.txt, src/yuzu/bootmanager.cpp, src/yuzu/bootmanager.h, src/yuzu/configuration/configure_graphics.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2_gl.h, src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2_vk.h, src/yuzu_tester/emu_window/emu_window_sdl2_hide.cpp, src/yuzu_tester/emu_window/emu_window_sdl2_hide.h
This PR takes Dolphin's DynamicLibrary. The implementation is from Stenzek.
It's slightly modified to properly support move semantics.
Create Vulkan instances and surfaces from the Vulkan backend instead of the frontend. This removes the requirement for QVulkanWindow on Qt, allowing CI to build Linux executables with Vulkan support.
It also simplifies the frontend code, simplifying port efforts.
Thanks to @jroweboy for the initial implementation, this is based on that.
=> yuzu: Drop SDL2 and Qt frontend Vulkan requirements

src/yuzu/game_list.cpp, src/yuzu/game_list_p.h
See citra-emu/citra#4956 for more details.
Should fix citra-emu/citra#4593.
As the issue might not be entirely clear, I'll offer a short explanation from what I understood from it and found from experimentation.
Currently Citra offers the user the option to change the text that's displayed in the "Name" column in the game list. Generally, it is expected that the items are sorted based on the displayed text, but Citra would sort them by title instead.
Made it so that an access to SortRole returns the same as DisplayRole.
There shouldn't be any UI changes, only change in behaviour.
Also fixes a bug with directory sorting, where having the directories out of order would enable you to try to "move up" to the addDirectory button, which would crash the emulator.
=> Port citra-emu/citra#4956: "Fixes to game list sorting"

src/core/hle/service/nvflinger/buffer_queue.cpp, src/core/hle/service/nvflinger/buffer_queue.h
This corrects the behavior of free buffer after witnessing it in an unrelated hardware test. I haven't found any games affected by it but in name of better accuracy we'll correct such behavior.
=> Buffer queue: Correct behavior of free buffer.

src/video_core/engines/maxwell_3d.h, src/video_core/textures/texture.h
This adds the registers used for multisampling. It doesn't implement
anything for now.
=> video_core: Add MSAA registers in 3D engine and TIC

src/video_core/engines/shader_bytecode.h, src/video_core/shader/decode/video.cpp, src/video_core/shader/shader_ir.h
Implements the common usages for VMNMX. Inputs with a different size
than 32 bits are not supported and sign mismatches aren't supported
either.
VMNMX works as follows:
It grabs Ra and Rb and applies a maximum/minimum on them (this is
defined by .MX), having in mind the input sign. This result can then be
saturated. After the intermediate result is calculated, it applies
another operation on it using Rc. These operations are merges,
accumulations or another min/max pass.
This instruction is useful for implementing with a more flexible approach GCN's
min3 and max3 instructions (for instance).
- Used by ACNH. Thanks to Ryujinx for pointing out this game uses VMNMX.
=> shader/video: Partially implement VMNMX

src/core/hle/service/nvflinger/buffer_queue.cpp, src/core/hle/service/nvflinger/buffer_queue.h, src/core/hle/service/vi/vi.cpp
Thanks to fincs for guiding me in this.
This is not based on reverse engineering. It's purely based on making [deko_examples](https://github.com/switchbrew/switch-examples/tree/master/graphics/deko3d/deko_examples). I'm open for feedback on this, as I don't have experience doing HLE.
`Disconnect` and `DetachBuffer` were no-ops. This commit implements `Disconnect`.
While we are at it, change the code to use a `switch` case.
=> service/vi: Partially implement BufferQueue disconnect

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Avoiding bitwise expressions, this fixes Turing issues in shaders using
half float merges that affected several games.
=> gl_shader_decompiler: Improve generated code in HMergeH*

src/video_core/renderer_opengl/gl_texture_cache.cpp
This way we are not ignoring the base layer of the current texture view.
- Tries to fix Astral Chain regression. Thanks to Rei for helping me bisect this.
=> gl_texture_cache: Attach view instead of base texture for layered attchments

src/video_core/engines/shader_bytecode.h, src/video_core/shader/decode/conversion.cpp
Reimplements I2I adding sign extension, saturation (clamp source value
to the destination), selection and destination sizes that are not 32
bits wide.
It doesn't implement CC yet.
=> shader/conversion: Implement I2I sign extension, saturation and selection

src/video_core/textures/astc.cpp
This moves more ASTC decoding code from runtime to compile time, reducing a 39% time consumption on a 8192x4096. It uses a look up tables on known ranges and falls back to the slow runtime alternative when the range is not pre-generated.
This avoids all heaps allocations while decoding using `boost::container::static_vector` (aside from the return vector).
=> texture/astc: More small ASTC optimizations

src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_state_tracker.cpp, src/video_core/renderer_opengl/gl_state_tracker.h
Implements "legacy" features from OpenGL present on hardware such as
smooth lines and line width.
- Used by [deko3d-examples](https://github.com/switchbrew/switch-examples/blob/master/graphics/deko3d/deko_examples/source/Example09_SimpleCompute.cpp#L254).
=> gl_rasterizer: Implement line widths and smooth lines

src/core/file_sys/patch_manager.cpp
When there are no layers to apply, return early as there is no need to rebuild the RomFS
=> file_sys: patch_manager: Return early when there are no layers to apply.

src/core/hle/service/friend/friend.cpp
- This is safe to stub, as there should be no adverse consequences from reporting no blocked users.
=> service: friend: Stub IFriendService::GetBlockedUserListIds.

src/video_core/texture_cache/texture_cache.h
This is a simple optimization as Buffer Copies are mostly used for texture recycling. They are, however, useful when games abuse undefined behavior but most 3D APIs forbid it.
=> Texture Cache: Only do buffer copies on accurate GPU.

src/video_core/renderer_vulkan/vk_rasterizer.cpp
Silence validation layer errors.
=> vk_rasterizer: Default to 1 viewports with a size of 0

src/video_core/renderer_vulkan/vk_blit_screen.cpp
When the dynamic state is specified, pViewports and pScissors are
ignored, quoting the specification:
pViewports is a pointer to an array of VkViewport structures, defining
the viewport transforms. If the viewport state is dynamic, this member
is ignored.
That said, AMD's proprietary driver itself seem to read it regardless of
what the specification says.
=> vk_blit_screen: Initialize all members in VkPipelineViewportStateCreateInfo

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
This reverts commit 05cf27083608bebd3ee4c38f2f948c8f2030f881.
Apparently the first approach using floats instead of bitfieldInsert
worked better for Fire Emblem: Three Houses. Reverting to get that
behavior back.
=> Revert "gl_shader_decompiler: Implement merges with bitfieldInsert"

src/video_core/renderer_opengl/gl_texture_cache.cpp
The base level is already included in the texture view. If we specify
the base level in the texture again, this will end up in the incorrect
level and potentially out of bounds.
=> gl_texture_cache: Fix layered texture attachment base level

src/video_core/renderer_opengl/gl_shader_cache.cpp
From my testing on a Splatoon 2 shader that takes 3800ms on average to
compile changing to FullDecompile reduces it to 900ms on average.
The shader decoder will automatically fallback to a more naive method if
it can't use full decompile.
=> gl_shader_cache: Use CompileDepth::FullDecompile on GLSL

src/video_core/renderer_vulkan/maxwell_to_vk.cpp
=> maxwell_to_vk: Add uint16 vertex formats

src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp
Credits go to gdkchan from Ryujinx for finding constant attributes are
used in retail games.
This commit does not implement them on Vulkan.
=> gl_rasterizer: Implement constant vertex attributes

src/CMakeLists.txt, src/core/hle/kernel/kernel.cpp, src/video_core/gpu_asynch.cpp, src/video_core/renderer_opengl/renderer_opengl.cpp
This can result in silent logic bugs within code, and given the amount of times these kind of warnings are caused, they should be flagged at compile-time so no new code is submitted with them.
=> CMakeLists: Make -Wreorder a compile-time error

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode/memory.cpp, src/video_core/shader/node.h
Implements a reduction operation. It's an atomic operation that doesn't
return a value.
This commit introduces another primitive because some shading languages
might have a primitive for reduction operations.
=> shader/memory: Implement RED.E.ADD and minor changes to ATOM

src/video_core/shader/control_flow.cpp
Eliminates redundant atomic reference count increments and decrements.
=> control_flow: Make use of std::move in TryInspectAddress()

src/video_core/texture_cache/surface_base.h
This doesn't modify internal state, so this can be made const.
=> surface_base: Make IsInside() a const member function

src/video_core/renderer_opengl/gl_device.cpp
Previously this was mutable even though it shouldn't be.
=> gl_device: Mark stage_swizzle as constexpr

src/video_core/texture_cache/surface_view.cpp, src/video_core/texture_cache/surface_view.h
Provides logical symmetry to the interface.
=> surface_view: Add missing operator!= to ViewParams

src/video_core/shader/decode/shift.cpp
Removes a redundant variable that is already satisfied by the IsFull() utility function.
=> decode/shift: Remove unused variable within Shift()

externals/CMakeLists.txt, src/core/CMakeLists.txt, src/input_common/CMakeLists.txt, src/web_service/CMakeLists.txt
This is mostly done by pkgconfig.
I've focused on the larger and more stable libraries.
Also the OpenSSL dependency is moved to httplib.
=> externals: Use shared libraries if possible

src/CMakeLists.txt, src/core/arm/arm_interface.cpp, src/core/file_sys/patch_manager.cpp, src/core/file_sys/registered_cache.cpp, src/core/file_sys/vfs_libzip.cpp, src/core/frontend/framebuffer_layout.cpp, src/core/hle/kernel/hle_ipc.cpp, src/core/hle/service/audio/audren_u.cpp, src/core/hle/service/filesystem/filesystem.cpp, src/core/hle/service/filesystem/fsp_srv.cpp, src/core/hle/service/time/time_zone_manager.cpp, src/core/hle/service/vi/vi.cpp, src/core/memory/dmnt_cheat_vm.cpp, src/core/telemetry_session.cpp, src/input_common/sdl/sdl_impl.cpp, src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/shader/decode/image.cpp, src/video_core/shader/shader_ir.cpp, src/video_core/shader/track.cpp, src/video_core/texture_cache/surface_params.cpp, src/video_core/texture_cache/texture_cache.h, src/web_service/web_backend.cpp, src/yuzu/debugger/profiler.cpp, src/yuzu/game_list_worker.cpp, src/yuzu/main.cpp
Allows reporting more cases where logic errors may exist, such as implicit fallthrough cases, redundant or pessimizing moves, etc.
=> CMakeLists: Specify -Wextra on linux builds

src/video_core/renderer_opengl/gl_query_cache.cpp
Avoids potential invalid junk data from being read.
=> gl_query_cache: Resolve use-after-move in CachedQuery move assignment operator

src/common/file_util.cpp, src/common/file_util.h
It's undefined behavior to pass a null pointer to `std::fread` and `std::fwrite`, even if the length passed in is zero, so we must perform the precondition checking ourselves.
A common case where this can occur is when passing in the data of an empty `std::vector` and size, as an empty `std::vector` will typically have a null internal buffer.
While we're at it, we can move the implementation out of line and add debug checks against passing in nullptr to `std::fread` and `std::fwrite`.
=> file_util: Early-exit in WriteArray and ReadArray if specified lengths are zero

src/video_core/renderer_opengl/gl_shader_cache.cpp
Reverts yuzu-emu/yuzu#3656
That change increases memory consumption on Nvidia's driver. Tagging this until we find a fix.
=> Revert "gl_shader_cache: Use CompileDepth::FullDecompile on GLSL"

externals/CMakeLists.txt
Keeps the library up to date.
See the [changelog](https://github.com/fmtlib/fmt/releases) for the list of improvements.
=> externals: Update fmt to 6.2.0

src/core/hle/kernel/memory/slab_heap.h
Casting from void* with static_cast is permitted by the standard, so we can just make use of that instead.
=> memory/slab_heap: Make use of static_cast over reinterpret_cast

src/core/loader/nso.cpp
Given the std::vector was const, an automatic move out of the function could not occur. We can allow automatic return value optimizations to occur by making the buffer non-const.
=> loader/nso: Resolve moves not occurring in DecompressSegment

CMakeLists.txt
Regressed by 1c340c6efad9. See [error log](https://github.com/yuzu-emu/yuzu/files/4498032/yuzu-qt5-s20200417.log).
=> Unbreak -Werror=implicit-fallthrough with Clang

src/video_core/shader/track.cpp
Two variables can be references, while two others can be std::moved. Makes for 4 less atomic reference count increments and decrements.
=> track: Eliminate redundant copies

src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/hle_ipc.h
These were added in the change that enabled -Wextra on linux builds so as not to introduce interface changes in the same change as a build-system flag addition.
Now that the flags are enabled, we can freely change the interface to make these unnecessary.
=> hle_ipc: Remove std::size_t casts where applicable

src/video_core/texture_cache/format_lookup_table.cpp
Previously these were all using the red component to derive the indices, which is definitely not intentional.
=> texture_cache/format_lookup_table: Fix incorrect green, blue, and alpha indices

src/core/hle/service/audio/audren_u.cpp, src/core/hle/service/hid/controllers/npad.cpp
This is annoying me so much now, that I'm just gonna throw it out here.
VibrateController isn't really stubbed as only the functionality on the frontend side is missing, and for audio we are well aware that it's not 100% complete.
As those two warnings get printed pretty much every frame, I think it's good for readibility to just lower their log level.
=> Try to reduce log spam a bit by lowering log levels to Debug

src/core/arm/dynarmic/arm_dynarmic_64.cpp, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_debug.cpp, src/yuzu/configuration/configure_debug.ui, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h
To ease future CPU debugging: Disable the less-testable parts of dynarmic.
=> dynarmic: Add option to disable CPU JIT optimizations

src/audio_core/CMakeLists.txt, src/audio_core/audio_renderer.cpp, src/audio_core/audio_renderer.h, src/audio_core/behavior_info.cpp, src/audio_core/behavior_info.h, src/audio_core/common.h, src/core/hle/service/audio/audren_u.cpp
Start implementation of behavior manager for future support of error throwing and feature set detection for audio renderer.
Note, many functions now used now are placeholders for a future implementation
=> audio_renderer: Preliminary BehaviorInfo

src/video_core/engines/maxwell_3d.h, src/video_core/renderer_vulkan/fixed_pipeline_state.cpp, src/video_core/renderer_vulkan/fixed_pipeline_state.h, src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_rasterizer.cpp
Compare the whole struct with std::memcmp and hash with CityHash. Using CityHash instead of a naive hash should reduce the number of collisions. Improve used type traits to ensure this operation is safe.
With these changes the improvements to the hashable pipeline state are:
Optimized structure
```
Hash:            89 ns
Equal:          103 ns
Construction*:  164 ns
Struct size:    384 bytes
```
Original structure
```
Hash:           148 ns
Equal:          174 ns
Construction*:  281 ns
Size:          1384 bytes
```
* Attribute state initialization is not measured
These measures are averages taken with `std::chrono::high_resolution_clock` on MSVC shipped on Visual Studio 16.6.0 Preview 2.1.
=> fixed_pipeline_state: Pack structure, use memcmp and CityHash on it

src/core/file_sys/program_metadata.cpp, src/core/file_sys/program_metadata.h, src/core/loader/elf.cpp, src/core/loader/nro.cpp, src/core/loader/nro.h
With the old VMM, we relied on the memory layout being initialized at ctor time. Homebrew apps relied on this behavior. This change restores similar functionality.
=> Fix process memory initialization for ELF and NRO

src/core/gdbstub/gdbstub.cpp
See citra-emu/citra#5185 for more details.
1. Ensure that register information available to gdbstub is most up-to-date.
2. There's no reason to check for `current_thread == thread` when emitting a trap packet.
Doing this results in random hangs whenever a step happens upon a thread switch.
Not sure whether (1) is actually necessary. I'm planning on a refactoring of the JIT which will eventually make it a moot point anyway (using contexts directly instead of needing to Load/Store them).
=> Port citra-emu/citra#5185: "gdbstub: Fix some gdbstub jankiness"

src/video_core/CMakeLists.txt, src/video_core/renderer_vulkan/nsight_aftermath_tracker.cpp, src/video_core/renderer_vulkan/nsight_aftermath_tracker.h, src/video_core/renderer_vulkan/vk_compute_pipeline.cpp, src/video_core/renderer_vulkan/vk_device.cpp, src/video_core/renderer_vulkan/vk_device.h, src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp, src/video_core/renderer_vulkan/vk_query_cache.cpp, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_scheduler.cpp, src/video_core/renderer_vulkan/wrapper.cpp, src/video_core/renderer_vulkan/wrapper.h
Adds optional support for Nsight Aftermath. It is enabled through
ENABLE_NSIGHT_AFTERMATH in cmake. A path to the SDK has to be provided
by the environment variable NSIGHT_AFTERMATH_SDK.
Nsight Aftermath allows an application to generate "minidumps" of the
GPU state when a device loss happens. By analysing these on Nsight we
can know what a game was doing and why it triggered a device loss.
The dump is generated inside %APPDATA%\yuzu\log\gpucrash and this
directory is deleted every time a new instance is initialized with
Nsight enabled.
To enable it on yuzu there has a to be a driver and device capable of
running Nsight Aftermath on Vulkan. That means only Turing based GPUs
on the latest stable driver, beta drivers won't work for now.
It is manually enabled in Configuration>Debug>Enable …
=>  renderer_vulkan: Integrate Nvidia Nsight Aftermath on Windows

src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2_vk.h
This PR resolves https://github.com/yuzu-emu/yuzu/issues/3752 and adds the dummy context as used in `src/yuzu/bootmanager.cpp` to provide functioning VK support to yuzu-cmd.
=> Introduce dummy context for yuzu-cmd VK support

src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp
Missing semicolon. Pointed out by https://github.com/yuzu-emu/yuzu/commit/c883cd103e1d6145e135e5e65ef66b8028ee99cb#r38678697.
=> Add missing ;

externals/opus/CMakeLists.txt
`_FORTIFY_SOURCE=0` must be set if building with `mingw-w64`, as described [here ](https://sourceforge.net/p/mingw-w64/mailman/message/36764708/). Resolves https://github.com/yuzu-emu/yuzu/issues/3726.
=> Set _FORTIFY_SOURCE=0 if building Opus with mingw-w64

src/core/hle/kernel/thread.cpp
Technical Summary:
bunnei narrowed down certain game issues to a rounding issue. This was hack-fixed by stepping back to unicorn for these instructions. Unicorn however, was broken, and did not pick up the fpcr set by the rest of the system, so ran with fpcr = 0. This turns out to fix things.
**Edit:** [fpcr value confirmed in Atmosphere](https://github.com/Atmosphere-NX/Atmosphere/blob/fa4a96d021a7b5b8b18d76490e598264da81e682/libraries/libmesosphere/source/arch/arm64/kern_k_thread_context.cpp#L134).
=> thread: FPCR.FZ is likely not 1 (and FPCR.RMode = TieAway and FPCR.DN = 0)

src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
The intention behind this was to assign a float to from an uint32_t, but
it was unintentionally being copied directly into the std::optional.
Copy to a temporary and assign that temporary to std::optional. This can
be replaced with std::bit_cast<float> once we are in C++20.
- Silences a validation issue and bug (dynamic state point size not being set) on Super Mario Odyssey.
=> vk_pipeline_cache: Fix unintentional memcpy into optional

externals/microprofile/microprofile.h, externals/microprofile/microprofileui.h, src/CMakeLists.txt, src/core/crypto/partition_data_manager.cpp, src/core/hle/service/bcat/backend/boxcat.cpp, src/core/hle/service/es/es.cpp, src/tests/core/core_timing.cpp, src/video_core/engines/fermi_2d.cpp, src/video_core/shader/control_flow.cpp, src/video_core/textures/decoders.cpp, src/video_core/textures/decoders.h, src/yuzu/applets/profile_select.cpp
Allows catching cases where internal linkage isn't specified for helper functions when they should be marked as such.
Opening this with minimal changes first to see if anything is caught by the buildbot that can be rectified along with this change.
=> CMakeLists: Enable -Wmissing-declarations on Linux builds

src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Resubmission: this fixes a format error (that otherwise causes `yuzu-cmd` to fail) to allow the reporting of emulation speed statistic in the window title of `yuzu-cmd`. Resolves https://github.com/yuzu-emu/yuzu/issues/3746.
=> Fix format error in performance statistics

src/core/hle/kernel/shared_memory.cpp, src/core/hle/kernel/shared_memory.h
Amends the parameter to match the documentation reference.
Resolves a -Wdocumentation warning with clang.
=> shared_memory: Amend doxygen reference

src/core/hle/kernel/svc.cpp
Since the VMM refactor, this is no longer used or needed.
=> svc: Remove unused variable

src/core/hle/kernel/memory/page_table.cpp
Any time the lambda function is called, the permission being used in the capture would be passed in as an argument to the lambda, so the capture is unnecessary.
Fixes: #3773
=> page_table: Remove unused captures

src/core/hle/kernel/svc.cpp
These were lost in the re-implementation of the virtual memory manager.
=> svc: Re-add MapProcessCodeMemory/UnmapProcessCodeMemory

src/yuzu/configuration/configure_input_player.cpp, src/yuzu/configuration/configure_input_player.h, src/yuzu/configuration/configure_input_player.ui
Use the existing deadzone slider to edit the modifier scale when keyboard is being used for stick controls. The slider is now always shown.
I also changed the shown value to show percent instead of decimals. I think that makes more sense to a regular user.
The setText at line 543 and 552 are needed because QSlider::valueChanged isn't called when the sliders are set to 0 and the configure window is opened.
=> configure_input_player: Use slider to edit modifier scale

src/yuzu/configuration/config.cpp, src/yuzu/configuration/config.h, src/yuzu/configuration/configure_hotkeys.cpp, src/yuzu/configuration/configure_hotkeys.h, src/yuzu/configuration/configure_hotkeys.ui
* This adds Clear and Restore Default for each and all hotkeys:
* Shows which action the key sequence is already assigned to, both if you're trying to set a new one or restore one to default:
* Reorders the hotkeys in config.cpp to actually be in alphabetical order. 
I'm not sure if it's correct to make the key sequence empty, but it works like intended and I'm not getting any errors. It seems Qt deals with that on it's own.
=> configuration: Add Restore Default and Clear options to hotkeys

src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_rasterizer.h, src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
On NVN buffers can be enabled but have no size. According to deko3d and
the behavior we see in Animal Crossing: New Horizons these buffers get
the address of 0x1000 and limit themselves to 0xfff.
Implement buffers without a size by binding a null buffer to OpenGL
without a side.
Introduce a default buffer getter that lazily constructs an empty
buffer. This is intended to match OpenGL's buffer 0.
Use this for disabled vertex and uniform buffers.
While we are at it, include vertex buffer usages for staging buffers to
silence validation errors.
- Fixes asserts on Animal Crossing: New Horizons
- Fixes high memory consumption on Animal Crossing: New Horizons.
=> {gl,vk}_rasterizer: Add lazy default buffer maker and use it for empty buffers

src/core/settings.h, src/video_core/dma_pusher.cpp, src/video_core/dma_pusher.h, src/video_core/engines/fermi_2d.cpp, src/video_core/engines/fermi_2d.h, src/video_core/engines/kepler_compute.cpp, src/video_core/engines/kepler_compute.h, src/video_core/engines/kepler_memory.cpp, src/video_core/engines/kepler_memory.h, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/engines/maxwell_dma.cpp, src/video_core/engines/maxwell_dma.h, src/video_core/gpu.cpp, src/video_core/gpu.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_graphics_advanced.cpp, src/yuzu/configuration/configure_graphics_advanced.ui, src/yuzu_cmd/config.cpp, src/yuzu_tester/config.cpp
This PR optimizes Command list methods with multiple arguments such as Const Buffer Data Upload. This helps considerably a few games like Diablo 3 which abuse buffer inlines. It also ports a hack from Ryujinx called Fast GPU Time: https://github.com/Ryujinx/Ryujinx/pull/1139 by gdkchan credits to him for this hack as it avoids activating game's dynamic resolution. The hack is enabled/disabled through a separate option in Graphics Advance. It is, however, still recommended to use dynamic resolution disabling mods.
=> Optimize GPU Command Lists and Introduce Fast GPU Time Option

src/video_core/renderer_vulkan/vk_device.h, src/video_core/renderer_vulkan/vk_memory_manager.cpp, src/video_core/renderer_vulkan/vk_memory_manager.h, src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp, src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
All drivers (even Intel) seem to have a device local memory type that is
not host visible. Remove this flag so all devices follow the same path.
This fixes a crash when trying to map to host device local memory on
integrated devices.
=> vk_memory_manager: Remove unified memory model flag

src/video_core/renderer_vulkan/fixed_pipeline_state.cpp, src/video_core/renderer_vulkan/fixed_pipeline_state.h, src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.h, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_renderpass_cache.cpp, src/video_core/renderer_vulkan/vk_renderpass_cache.h
Continues what #3718 started for renderpasses. This allows us to call Common::CityHash and std::memcmp only once for GraphicsPipelineCacheKey.
Framebuffer creation was ignoring the number of color attachments, this caused validation errors. No known issues were caused by this.
=> vk_renderpass_cache: Pack renderpass cache key and unify keys

src/core/hle/service/am/am.cpp, src/core/hle/service/glue/errors.h
Consistency for the rest of the error codes in the codebase
=> style: Change AMs & Glues error codes to be dec instead of hex

src/core/hle/kernel/svc.cpp
As we currently match hardware and don't return a successful result, these should be marked as errors instead of warnings and as stubs.
=> kernel: Bad GetInfo ids should not be marked as stubs

src/video_core/CMakeLists.txt, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.h, src/video_core/shader/control_flow.cpp, src/video_core/shader/decode.cpp, src/video_core/shader/memory_util.cpp, src/video_core/shader/memory_util.h, src/video_core/shader/shader_ir.h
Deduplicate code shared between vk_pipeline_cache and gl_shader_cache as
well as shader decoder code.
While we are at it, fix a bug in gl_shader_cache where compute shaders
had an start offset of a stage shader.
=> shader/memory_util: Deduplicate code

src/core/arm/dynarmic/arm_dynarmic_64.cpp, src/core/arm/unicorn/arm_unicorn.cpp, src/core/arm/unicorn/arm_unicorn.h, src/core/hle/kernel/physical_core.cpp
Allows this code to compile successfully on non x86-64 architectures.
Fixes issue #3782
=> physical_core: Make use of std::make_unique instead of std::make_shared in ctor

src/core/hle/service/ns/ns.cpp, src/core/hle/service/set/set.cpp, src/core/hle/service/sm/sm.cpp, src/core/hle/service/vi/vi.cpp
Retail games rarely throw error codes. Actually logging when calls fail helps with debugging/locating more issues in a users logs.
=> Don't fail silently for vi, sm, set and ns services

src/yuzu/main.cpp
Patch the RomFS with the selected updates before dumping. Previously the resulting RomFS only contained data from the original title.
To dump the RomFS without updates the user can disable the update under Properties before choosing Dump RomFS.
=> Dump RomFS command to include Updates

src/video_core/shader/track.cpp
This reverses this PR as it was causing invalid Buffers to be tracked and used which lead to big Memory leaks on Vulkan on BotW.
=> Revert: shader_decode: Fix LD, LDG when track constant buffer.

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode/arithmetic_integer.cpp, src/video_core/shader/decode/register_set_predicate.cpp, src/video_core/shader/node.h
Description in the individual commits.
This is a first step on removing the buggy and improperly named `SetInternalFlagsFrom*`. Internal flags should be called "Condition Codes" as described in [NV_gpu_program4](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_gpu_program4.txt), Section 2.X.3.7
=> shader: Implement P2R CC, IADD Rd.CC and IADD.X

src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_vulkan/fixed_pipeline_state.cpp, src/video_core/renderer_vulkan/fixed_pipeline_state.h, src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Using deko3d as reference:
https://github.com/devkitPro/deko3d/blob/4e47ba0013552e592a86ab7a2510d1e7dadf236a/source/maxwell/gpu_3d_state.cpp#L42
We were using bits 3 and 4 to determine depth clamping, but these are
the same both enabled and disabled:
```
state->depthClampEnable ? 0x101A : 0x181D
```
The same happens on Nvidia's OpenGL driver, where they do something like
this (default capabilities, GL 4.5 compatibility):
```
(state & DEPTH_CLAMP) != 0 ? 0x201a : 0x281c
```
There's always a difference between the first bits in this register, but
bit 11 is consistently disabled on both deko3d/NVN and OpenGL. This
commit changes yuzu's behaviour to use bit 11 to determine depth
clamping.
Once I finish the graphics test framework we'll be able to test each individual bit.
- Fixes depth issues …
=> maxwell_3d: Fix depth clamping register

src/core/hle/service/ptm/psm.cpp
No point to emulate battery life. However, options are broken out if we ever want to add a setting for it
=> psm: Mark as debug instead of warning

src/core/hle/service/caps/caps_su.cpp
SetShimLibraryVersion, SaveScreenShotEx1 & SaveScreenShotEx2 were missing
=> caps: Add missing service names to caps:su

src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h
Return the proper state of vr mode for IsVrModeEnabled
We should not return an error for SetVrModeEnabled. When VR Mode is turned on, it signals to lbl to turn vr mode on, not return an error code
=> am: IsVrModeEnabled & SetVrModeEnabled fixes

src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
IoctlGetGpuTime should be 16 bytes, not 8.
=> nvdrv: Fix GetGpuTime stack corruption

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.h, src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode.cpp, src/video_core/shader/decode/image.cpp, src/video_core/shader/decode/texture.cpp, src/video_core/shader/node.h, src/video_core/shader/shader_ir.h, src/video_core/texture_cache/surface_params.cpp, src/video_core/texture_cache/texture_cache.h
This allows deducing some properties from the texture instruction before
asking the runtime. By doing this we can handle type mismatches in some
instructions from the renderer instead of the shader decoder.
Fixes texelFetch issues with games using 2D texture instructions on a 1D
sampler.
=> shader/texture: Support multiple unknown sampler properties

src/video_core/renderer_vulkan/vk_rasterizer.cpp
Xenoblade 2 invokes a draw call with zero vertices.
This is likely due to indirect drawing (glDrawArraysIndirect)
being used to implement conditional rendering.
This causes a crash in the staging buffer pool when trying to create a
buffer with a size of zero. To workaround this, skip index buffer setup
entirely when the number of indices is zero.
=> vk_rasterizer: Skip index buffer setup when vertices are zero

.ci/scripts/windows/docker.sh
On some systems like arch, qt path is a bit different and it breaks packaging.
So I've made a fallback to `/usr/x86_64-w64-mingw32/lib/qt/`.
=> Fixed packaging on some systems with different QT5 path

src/core/hle/kernel/readable_event.cpp
Resolves a -Wextra-semi warning (there's no need for a semicolon on a closing brace of the conditional.
While we're at it, we can invert the branch to form a guard clause, unindenting all of the contained code.
=> readable_event: Remove unnecessary semicolon in Signal()

src/input_common/main.cpp
Just making the changes of https://github.com/yuzu-emu/yuzu/pull/3792, after it got mysteriously closed.
=> input_common: fix build when SDL2 is disabled

CMakeModules/MinGWCross.cmake
The Docker image was just updated to use Arch Linux instead of Ubuntu. This PR sets the compiler names to reflect how they are installed on the Arch Linux Docker image. Fixes `x86_64-w64-mingw32-g++-posix is not a full path and was not found in the PATH.` error and the likewise gcc error in CMake.
=> CMake: Update compiler paths for the current MinGW Docker image

src/core/settings.cpp
```
Default = 0,
2x = 1,
4x = 2,
8x = 3,
16x = 4,
```
=> settings: Add anisotropic filtering level to the yuzu configuration log

src/common/uuid.h, src/core/hle/service/acc/acc.cpp
Currently we return 1 for a users Nintendo ID. By returning just the lower part of the users UUID, we can have a unique account for each user
=> acc: Return a unique value per account for GetAccountId

src/yuzu/bootmanager.cpp, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_general.cpp, src/yuzu/configuration/configure_general.ui, src/yuzu/main.cpp, src/yuzu/main.h, src/yuzu/uisettings.h
See citra-emu/citra#5094 for more details.
Add the option to hide the mouse cursor when a defined amount of time (currently ~~3s~~ 2.5s)
Adresses/closes citra-emu/citra#4687.
Mouse clicks now count as activity and the setting can be changed while emulation is running.
After reading the comments and some deliberation, I decided to not implement in this PR neither hotkeys nor changing the mouse timeout. Both are rather niche features and could be easily implemented by someone passionate about it, if they decide the current amount of control over the mouse hiding is not enough.
UI change:
=> Port citra-emu/citra#5094: "yuzu: Option to hide mouse on inactivity"

src/core/hle/kernel/memory/address_space_info.cpp, src/core/hle/kernel/memory/address_space_info.h, src/core/hle/kernel/memory/memory_block_manager.cpp, src/core/hle/kernel/memory/memory_block_manager.h, src/core/hle/kernel/memory/memory_manager.cpp, src/core/hle/kernel/memory/memory_manager.h, src/core/hle/kernel/memory/page_linked_list.h, src/core/hle/kernel/memory/page_table.cpp, src/core/hle/kernel/memory/page_table.h, src/core/hle/kernel/memory/slab_heap.h, src/core/hle/kernel/memory/system_control.cpp
Resolves a few compiler warnings like unused variables, variable shadowing, #pragma once within a cpp file, etc.
Each commit should be self-contained.
=> kernel/memory: Resolve several compiler warnings

src/video_core/CMakeLists.txt, src/video_core/dma_pusher.cpp, src/video_core/dma_pusher.h, src/video_core/engines/engine_interface.h, src/video_core/engines/fermi_2d.cpp, src/video_core/engines/fermi_2d.h, src/video_core/engines/kepler_compute.cpp, src/video_core/engines/kepler_compute.h, src/video_core/engines/kepler_memory.cpp, src/video_core/engines/kepler_memory.h, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/engines/maxwell_dma.cpp, src/video_core/engines/maxwell_dma.h, src/video_core/gpu.cpp, src/video_core/macro_interpreter.cpp, src/video_core/textures/decoders.cpp, src/video_core/textures/decoders.h
This PR aims to delegate engine calling to the DMA pusher, thus reducing spaghetti code. At the same time we are adding an optimized path for small DMA copies that avoid reading the whole texture but just tiny bits of it.
This optimizations greatly benefit Pokemon Sword & Shield on Cities and some routes.
=> GPU: More optimizations to GPU Command List Processing and DMA Copy Optimizations

src/yuzu/main.cpp
See citra-emu/citra#5280 for more details.
Follow up to citra-emu/citra#5094.
Fixes a bug reported on discord by Dragois, and backports review comments from yuzu-emu/yuzu#3637.
The reported bug was that the menubar would lose sensitivity to the hover interactions. This happens because Qt menubars have mouse tracking true as default, therefore I had operated on false assumptions. 
There are no changes in behaviour besides the bug fix.
=> Port citra-emu/citra#5280: "Small fixes to "Option to hide mouse on inactivity""

src/video_core/renderer_vulkan/vk_device.cpp, src/video_core/renderer_vulkan/vk_device.h, src/video_core/renderer_vulkan/vk_sampler_cache.cpp
This should fix grass interactions on Breath of the Wild on Vulkan.
It is currently untested against validation layers.
Nvidia's Windows 443.09 beta driver or Linux 440.66.12 is required for
now.
=> vk_sampler_cache: Use VK_EXT_custom_border_color when available

src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/maxwell_to_gl.h, src/video_core/renderer_vulkan/fixed_pipeline_state.cpp, src/video_core/renderer_vulkan/fixed_pipeline_state.h, src/video_core/renderer_vulkan/maxwell_to_vk.cpp, src/video_core/renderer_vulkan/maxwell_to_vk.h, src/video_core/renderer_vulkan/vk_device.cpp, src/video_core/renderer_vulkan/vk_device.h, src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
It is currently implemented only on devices with GL_NV_viewport_swizzle or VK_NV_viewport_swizzle.
- Fixes flipping issues in several games (#2703).
=> video_core: Implement viewport swizzles with NV_viewport_swizzle

src/video_core/renderer_vulkan/maxwell_to_vk.cpp
One is used by _Dark Souls: Remastered_.
Log message:
```
Debug <Critical> video_core\renderer_vulkan\maxwell_to_vk.cpp:VertexFormat:462: Assertion Failed! Unimplemented vertex format of type=3 and size=15
```
=> maxwell_to_vk: implement missing signed int formats

CMakeLists.txt, externals/find-modules/FindCatch2.cmake, externals/find-modules/FindLibzip.cmake, externals/find-modules/Findfmt.cmake, externals/find-modules/Findnlohmann_json.cmake, externals/find-modules/Findzstd.cmake
This pull requests implements propper version checking for all modules (but opus). This will ensure that older versions of the system libraries will be rejected and conan will be used instead.
Fixes #3790
=> externals: Cmake version checks

.ci/yuzu-patreon-step2.yml
Apparently the core checks for errors before uploading new builds, and so if clang format fails, the website won't update the latest build.
=> CI: Don't check clang format on early access builds

src/video_core/engines/shader_bytecode.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/shader/decode.cpp, src/video_core/shader/decode/xmad.cpp, src/video_core/shader/node.h, src/video_core/shader/shader_ir.cpp
This allows us to use native SPIR-V instructions without having to manually check for NAN.
"Not equal" operators on GLSL seem to behave as unordered when we expect an ordered comparison. Manually emulate this checking for LGE values (numbers, "not-NaNs").
For example, this would have returned true instead of false:
```glsl
float a = NAN;
float b = 5;
return a != b;
```
These are the unit tests used for this pull request: [nxgputests.zip](https://github.com/yuzu-emu/yuzu/files/4602975/nxgputests.zip)
Current master would crash or generate invalid GLSL, but the relevant part is that these kind of tests were failing:
```
MOV R0, c[0x0][0x140];
MOV R1, c[0x0][0x144];
MOV32I R2, 0xffffffff;
MOV32I R3, 0x3f800000;
FSETP.NE.FTZ.AND P0, PT, R2, R3, PT;
@!P0    MOV32I R2, 0xdead;
@P0    MOV32I R2, …
```
=> shader_ir: Add separate instructions for ordered and unordered comparisons and fix NE on GLSL

src/common/CMakeLists.txt, src/common/time_zone.cpp, src/common/time_zone.h, src/core/hle/service/time/time_manager.cpp, src/core/hle/service/time/time_zone_content_manager.cpp, src/core/settings.cpp, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_system.cpp, src/yuzu/configuration/configure_system.h, src/yuzu/configuration/configure_system.ui, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h
Various improvements to time zone support. Tested against ACNH. 
* Tries to detect current time zone and use that. Windows only for now, and fairly incomplete.
* Adds a setting to manually change the time zone.
=> Improve time zone support

src/audio_core/audio_renderer.cpp, src/audio_core/audio_renderer.h, src/audio_core/common.h
Supersedes #3738 and #3321
Expands on the initial work done by tobi to fix issues in other games for the voice mixer. This is still preliminary mixing as we don't have dedicated mix buffers yet. 6 channel downmixing was merged into this PR since it needed to be changed either way for voice mixing.
=> audio_renderer: Better voice mixing and 6 channel downmixing

src/core/frontend/emu_window.cpp, src/core/frontend/framebuffer_layout.h, src/yuzu/loading_screen.cpp, src/yuzu/main.cpp, src/yuzu/main.h, src/yuzu/main.ui
Previously the minimum window size was 1280x720, causing some users with monitors/screens with a height of less than 800 pixels (taskbar hidden) or 840 pixels (taskbar visible) have the status bar cut off **and not be able to resize the window below 720p**. This amends the issue by reducing the minimum window size to 640x360.
To those who are confused what this does, and does not do:
1. It **does not** cause the window to run at 360p by default
2. This is just allows users to resize the window below 720p to a minimum of 360p where previously you were not able to,
Before (1280x720):
After (640x360):
=> frontend: Set minimum window size to 640x360 instead of 1280x720

src/video_core/renderer_vulkan/vk_rasterizer.cpp
Match OpenGL's behavior. This can fix or simplify bisecting issues on Vulkan.
=> vk_rasterizer: Match OpenGL's FlushAndInvalidate behavior

src/core/file_sys/control_metadata.cpp, src/core/file_sys/control_metadata.h, src/core/file_sys/savedata_factory.cpp, src/core/hle/service/filesystem/fsp_srv.cpp, src/core/hle/service/filesystem/fsp_srv.h, src/yuzu/game_list.cpp, src/yuzu/game_list.h, src/yuzu/main.cpp, src/yuzu/main.h
This is some minor improvements for emulation of device saves. This:
- Fixes Animal Crossing: New Horizons saving.
- Makes it so "Open Save Data Location" option goes to the device save folder where appropriate.
- Stubs the FileSystem MultiCommitManager. Since this is not strictly necessary for the only game we've seen use this (ACNH), we should implement this with the ongoing VFS rewrite. @DarkLordZach as FYI.
=> FS: Improve emulation of device saves

src/core/hle/service/hid/controllers/keyboard.cpp
Previously we never cleared the states of the entries and the key would stay held down, also looping over the key bytes for each key lead to setting every bit for the key state instead of the key we wanted
=> hid: Clear keyboard states & fix logic issue

src/core/hle/service/nifm/nifm.cpp
This has been "wrong" since https://github.com/yuzu-emu/yuzu/commit/0432af5ad1ec34f02071f6fdc5fc78149b059f18
I haven't found a game that called this function (and I haven't tried this on a real Switch), and because of this I haven't been able to check if the number in assert OR the string in the assert is wrong, but one of the two is wrong:
NetworkProfileData is 0x18E, while SfNetworkProfileData is 0x17C, according to Switchbrew
Switchbrew doesn't officially say that NetworkProfileData's size is 0x18E but it's possible to calculate its size since Switchbrew provides the size and the offset of all the components of NetworkProfileData (which isn't currently implemented in yuzu, alongside SfNetworkProfileData)
NetworkProfileData documentation: …
=> nifm: correct assert string in CreateTemporaryNetworkProfile

src/video_core/CMakeLists.txt, src/video_core/buffer_cache/buffer_cache.h, src/video_core/buffer_cache/map_interval.cpp, src/video_core/buffer_cache/map_interval.h, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_fence_manager.cpp, src/video_core/renderer_vulkan/vk_buffer_cache.cpp, src/video_core/renderer_vulkan/vk_fence_manager.h
Instead of using boost::icl::interval_map for caching, use
boost::intrusive::set. interval_map is intended as a container where the
keys can overlap with one another; we don't need this for caching
buffers and a std::set-like data structure that allows us to search with
lower_bound is enough.
This aims to keep mapped addresses close to one another in memory.
=> buffer_cache: Replace boost::icl::interval_map with boost::intrusive::set

src/core/settings.cpp, src/core/settings.h, src/core/telemetry_session.cpp, src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_resource_manager.cpp, src/video_core/renderer_opengl/gl_resource_manager.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_cache.h, src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/gl_shader_manager.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_graphics_advanced.cpp, src/yuzu/configuration/configure_graphics_advanced.ui, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h
Add code required to use OpenGL assembly programs based on
[NV_gpu_program5](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_gpu_program5.txt). Decompilation for ARB programs is intended to be added
in a follow up commit. This does **not** include ARB decompilation and
it's not in an usable state.
The intention behind assembly programs is to reduce shader stutter
significantly on drivers supporting [NV_gpu_program5](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_gpu_program5.txt) (and other required
extensions). Currently only Nvidia's proprietary driver supports these
extensions.
Add a UI option hidden for now to avoid people enabling this option
accidentally.
This code path has some limitations that OpenGL compatibility doesn't
have:
- …
=> renderer_opengl: Add assembly program code paths

src/video_core/rasterizer_cache.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_rasterizer.cpp
This PR takes care of correcting a series of crashes and incorrections on Async GPU & Vulkan.
Resume of changes:
- Remove CPU Query Cache Invalidation on Async GPU, as Async GPU always flushes and invalidates them.
- On Async GPU, Shader & Pipeline Invalidations from the CPU will no longer be instant and instead use the sync interface.
- Corrected an issue in Vulkan's Pipeline Cache where if a shader had an invalid address, it wouldn't use a null shader instead of trying to decompile it.
=> Correct a series of crashes and intructions on Async GPU and Vulkan Pipeline

src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
Some operations like atomicMin were ignored because they returned were
being stored to RZ. This operations have a side effect and it was being
ignored.
Part of #3938
=> shader_decompiler: Visit source nodes even when they assign to RZ

src/video_core/renderer_vulkan/maxwell_to_vk.cpp, src/video_core/renderer_vulkan/vk_device.cpp
=> maxwell_to_vk: Add format B8G8R8A8_SRGB and add Attachable capability for B8G8R8A8_UNORM

src/core/file_sys/patch_manager.cpp, src/core/file_sys/patch_manager.h
Some patch developers distribute their patches with odd-cased subdirectories. On Windows systems, this is fine: file names do not have case, so 'exefs' and 'exeFS' refer to the same directory. On most Linux systems however, case matters when naming files and directories. Thus, the current patch manager implementation in Linux does not recognize mods that use alternate-cases when naming specifically the `exefs`, `romfs`, `romfs_ext`, and `cheats` directories.
This changes patch_manager functions to use a case-insensitive variant of `GetSubdirectory`. With this change, patches now work on *nix systems even when patch directories are named with odd cases.
I am obviously open to changes, especially moving `FindSubdirectoryCaseless` to a different file. It is in patch_manager because I was …
=> patch_manager: Add support for case-sensitivity on Linux

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_texture_cache.cpp, src/video_core/renderer_opengl/gl_texture_cache.h, src/video_core/renderer_vulkan/vk_texture_cache.cpp, src/video_core/texture_cache/texture_cache.h
Stop ignoring image swizzles on depth and stencil images.
This doesn't fix a known issue on Xenoblade Chronicles 2 where an OpenGL
texture changes swizzles twice before being used. A proper fix would be
having a small texture view cache for this like we do on Vulkan.
=> texture_cache: Implement depth stencil texture swizzles

src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/gl_rasterizer.cpp
Previously we were disabling compute shaders on Intel's proprietary driver due to broken compute. This has been fixed in the latest Intel drivers. Re-enable compute for Intel proprietary drivers and remove the check for broken compute.
=> gl_device: Enable compute shaders for Intel proprietary drivers

src/video_core/texture_cache/texture_cache.h
Avoid unnecessary work on GetSurfacesInRegion using `std::unordered_map::find` instead of `operator[]` and avoid heap allocations using `boost::container::small_vector` with a size of one.
While we are at it, use standard algorithms when possible.
=> texture_cache: Optimize GetSurfacesInRegion

src/video_core/renderer_opengl/renderer_opengl.cpp, src/yuzu/bootmanager.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
This commit aims to help easing debugging of driver crashes without having to modify existing code.
=> OpenGL: Enable Debug Context and Synchronous debugging when graphics debugging is enabled

src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.h
Constant attributes (in OpenGL known as disabled attributes) are not
supported on Vulkan, even with extensions. To emulate this behavior we
return zero on reads from disabled vertex attributes in shader code.
This has no caching cost because attribute formats are not dynamic state
on Vulkan and we have to store it in the pipeline cache anyway.
- Fixes Animal Crossing: New Horizons terrain borders on Vulkan
=> vk_rasterizer: Implement constant attributes 

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
These fixes are based on gdkchan's explanation of the problem, found in [this](https://github.com/Ryujinx/Ryujinx/pull/1277) pull request from Ryujinx.
The implementation is different. On Vulkan I removed a leftover from OpenGL and everything works fine, on OpenGL I ported an the old Vulkan code back. As described in 606a62d, this is not a complete implementation because we only check for the first viewport.
The reason I didn't port gdkchan's solution is because I don't want to use viewport swizzles on games not using viewport swizzles and injecting shader code to flip `gl_Position` can introduce issues on transform feedbacks.
This fixes front face issues on Xenoblade Chronicles 2 and any other game doing bad things on NVN queues.
Credits to gdkchan from [Ryujinx](ryujinx.org/) for …
=> fixed_pipeline_state,gl_rasterizer: Swap negative viewport checks for front faces

src/video_core/texture_cache/format_lookup_table.cpp
Implement G24S8 as S8Z24, this is deduced from the component type. If sampling individual components has to be implemented has not been tested.
=> format_lookup_table: Implement G24S8 format as S8Z24

src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.h
Avoids compilation errors at the cost of shader build times and runtime
performance when a game hits the limit of uniform buffers we can use.
=> glsl: Squash constant buffers into a single SSBO when we hit the limit

src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h
Allows Minecraft: Nintendo Switch Edition (a.k.a. old Minecraft) to boot and go ingame
=> hid: Stub GetXpadIDs

src/yuzu/configuration/configure_input_player.cpp
See citra-emu/citra#5376 for more details.
Previously I would have to reset the input to default every single time I opened Citra if I just wanted the default keyboard binds.
=> Port citra-emu/citra#5376: "Actually save the input when clearing/resetting to default"

src/video_core/renderer_opengl/gl_shader_decompiler.cpp
On Intel's proprietary drivers, gl_Layer and gl_ViewportIndex are not allowed members of gl_PerVertex block, causing the shader to fail to compile. Fix this by declaring these variables outside of gl_PerVertex.
=> gl_shader_decompiler: Fix geometry shader outputs on Intel drivers

src/video_core/renderer_vulkan/vk_compute_pipeline.cpp, src/video_core/renderer_vulkan/vk_descriptor_pool.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_rasterizer.h, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/renderer_vulkan/vk_shader_decompiler.h, src/video_core/renderer_vulkan/vk_texture_cache.cpp
Storage texels are the equivalent of an image buffer on OpenGL.
Implement atomic operations on images.
On GLSL these are imageAtomic* functions (e.g. imageAtomicAdd).
=> vk_rasterizer: Implement storage texels and atomic image operations

src/video_core/renderer_opengl/renderer_opengl.cpp
Avoids logging when it's not relevant. This can potentially reduce
driver's internal thread overhead.
Supersedes #3914
=> renderer_opengl: Only enable DEBUG_OUTPUT when graphics debugging is enabled

src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_texture_cache.cpp, src/video_core/renderer_opengl/gl_texture_cache.h, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_texture_cache.cpp, src/video_core/renderer_vulkan/vk_texture_cache.h, src/video_core/texture_cache/surface_base.cpp, src/video_core/texture_cache/surface_base.h, src/video_core/texture_cache/surface_params.cpp, src/video_core/texture_cache/texture_cache.h
This allows rendering to 3D textures with more than one slice.
Applications are allowed to render to more than one slice of a texture
using gl_Layer from a VTG shader.
This also requires reworking how 3D texture collisions are handled, for
now, this commit allows rendering to slices but not to miplevels. When a
render target attempts to write to a mipmap, we fallback to the previous
implementation (copying or flushing as needed).
- Fixes color correction 3D textures on UE4 games (rainbow effects). #4016 is required.
- Allows Xenoblade games to render to 3D textures directly (no copies required).
=> texture_cache: Implement rendering to 3D textures

src/video_core/engines/const_buffer_engine_interface.h, src/video_core/engines/kepler_compute.cpp, src/video_core/engines/kepler_compute.h, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp, src/video_core/renderer_opengl/gl_shader_disk_cache.h, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/shader/decode/texture.cpp, src/video_core/shader/node.h, src/video_core/shader/node_helper.h, src/video_core/shader/registry.cpp, src/video_core/shader/registry.h, src/video_core/shader/shader_ir.h, src/video_core/shader/track.cpp
Games using D3D idioms can join images and samplers when a shader
executes, instead of baking them into a combined sampler image. This is
also possible on Vulkan.
One approach to this solution would be to use separate samplers on
Vulkan and leave this unimplemented on OpenGL, but we can't do this
because there's no consistent way of determining which constant buffer
holds a sampler and which one an image. We could in theory find the
first bit and if it's in the TIC area, it's an image; but this falls
apart when an image or sampler handle use an index of zero.
The used approach is to track for a LOP.OR operation (this is done at an
IR level, not at an ISA level), track again the constant buffers used as
source and store this pair. Then, outside of shader execution, join
the sample and …
=> shader/texture: Join separate image and sampler pairs offline

src/video_core/buffer_cache/buffer_cache.h, src/video_core/renderer_opengl/gl_rasterizer.cpp
Vertex buffers bindings become invalid after the stream buffer is
invalidated. We were originally doing this, but it got lost at some
point.
- Fixes Animal Crossing: New Horizons black blinking glitches, but it affects everything.
=> gl_rasterizer: Mark vertex buffers as dirty after buffer cache invalidation

src/video_core/macro/macro_jit_x64.h
Fix build time issues on gcc. Confirmed through asan that avoiding this
initialization is safe (this was not intentional, as I was debugging something else).
Closes #4051.
=> video_core/macro_jit_x64: Remove initializer in member variable

src/video_core/buffer_cache/buffer_block.h, src/video_core/buffer_cache/buffer_cache.h, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_buffer_cache.h, src/video_core/renderer_opengl/gl_stream_buffer.cpp, src/video_core/renderer_opengl/gl_stream_buffer.h, src/video_core/renderer_vulkan/vk_buffer_cache.cpp, src/video_core/renderer_vulkan/vk_buffer_cache.h, src/video_core/renderer_vulkan/vk_stream_buffer.h
Instead of using as template argument a shared pointer, use the
underlying type and manage shared pointers explicitly. This can make
removing shared pointers from the cache more easy.
While we are at it, make some misc style changes and general
improvements (like using insert_or_assign instead of operator[] + operator=).
=> buffer_cache: Avoid passing references of shared pointers and misc style changes

externals/CMakeLists.txt
Ensure yuzu is using the version of xbyak yuzu wants and isn't importing dynarmic's.
=> CMakeLists: xbyak comes before dynarmic

src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_graphics.cpp, src/yuzu/configuration/configure_graphics.ui, src/yuzu/main.cpp, src/yuzu_cmd/config.cpp, src/yuzu_cmd/default_ini.h, src/yuzu_tester/config.cpp, src/yuzu_tester/default_ini.h
Removes the internal resolution combobox to minimize user confusion as this setting is currently non-functional.
=> yuzu/frontend: Remove internal resolution option

src/video_core/macro/macro_jit_x64.cpp, src/video_core/macro/macro_jit_x64.h
Primarily removal of unused code, removal of unnecessary registers, and allocation of the remaining used registers to slightly better choices.
Justification for each commit in each commit's description.
=> macro_jit_x64: Cleanup

src/core/arm/dynarmic/arm_dynarmic_32.cpp, src/core/arm/dynarmic/arm_dynarmic_32.h, src/core/arm/dynarmic/arm_dynarmic_cp15.cpp, src/core/arm/dynarmic/arm_dynarmic_cp15.h
* Log unknown coprocessor 15 instructions
* Change implementation of existing cp15 instructions to only require two variables
* Hook this up appropriately to GetTlsAddress/SetTlsAddress/SetTPIDR_EL0/GetTPIDR_EL0.
* Implement CNTPCT for coprocessor 15.
=> arm_dynarmic: CP15 changes

src/core/arm/dynarmic/arm_dynarmic_32.cpp
On MSVC builds we treat conversion warnings as errors.
=> arm_dynarmic_32: Fix implicit conversion error in SetTPIDR_EL0

src/video_core/renderer_opengl/maxwell_to_gl.h, src/video_core/renderer_vulkan/maxwell_to_vk.cpp, src/video_core/renderer_vulkan/vk_sampler_cache.cpp
The changes are explained in the individual commits.
The only functional changes are:
- Returns GL_NEAREST instead of GL_LINEAR on an unknown texture filter mode
- Returns VK_SAMPLER_MIPMAP_MODE_NEAREST instead of VK_SAMPLER_MIPMAP_MODE_LINEAR when mipmap_filter is None
- Emulates GL_LINEAR/NEAREST minification filters based on the [description](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSamplerCreateInfo.html#_description) in VkSamplerCreateInfo(3)
- Any unimplemented features will be logged under UNIMPLEMENTED_MSG instead of LOG_ERROR to bring into parity with the logging found in maxwell_to_vk
=> maxwell_to_gl/vk: Miscellaneous changes

src/video_core/macro/macro_jit_x64.cpp
Two correctness issues with existing optimizations.
* `zero_reg_skip` should not skip zero generation for adc and sbb: Generated code depends on src_a and src_b being valid registers.
* `optimize_for_method_move` assumes adjacent instructions write to same dst.
Conflicts with #4089, will correct depending on whichever is merged first.
=> macro_jit_x64: Optimization correctness

src/video_core/macro/macro_jit_x64.cpp, src/video_core/macro/macro_jit_x64.h
Unnecessary function call overhead. (Yes, this conflicts with #4086, I know.)
=> macro_jit_x64: Inline Engines::Maxwell3D::GetRegisterValue

src/video_core/macro/macro_jit_x64.cpp
Removes a completely unused label and marks another variable as unused, given it seems like it has potential uses in the future.
=> macro_jit_x64: Remove unused variable

src/video_core/macro/macro_jit_x64.cpp
Previously the dst variables weren't being used, but the code managed to function normally anyways, since the register being used directly, is the same register as the one being loaded (only it's the 8-bit view of it being used in the shifts).
We can make use of the destination directly to prevent compiler warnings.
=> macro_jit_x64: Amend readability of Compile_ExtractShiftLeftRegister()

src/video_core/macro/macro_jit_x64.cpp
[SHL/SHR only accepts CL as their second argument](https://www.felixcloutier.com/x86/sal:sar:shl:shr).
Xbyak would detect this case, raise an assert, and crash at runtime.
=> macro_jit_x64: Use ecx for shift register

src/yuzu/yuzu.rc, src/yuzu_cmd/yuzu.rc, src/yuzu_tester/yuzu.rc
See citra-emu/citra#5322 for more details.
Occurs when doing a local compile in MSVC build. The compiler I'm using is as below:
*Microsoft Visual Studio Community 2019 Preview*
*Version 16.6.0 Preview 5.0*
Fixes this error:
CVTRES : fatal error CVT1100: duplicate resource.  type:MANIFEST, name:1, language:0x0409
LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt
I have put `0` since previous name was `1`. If have other names in mind, please let me know.
=> Port citra-emu/citra#5322: "Fix: fatal error CVT1100 when compiling manifest file"

src/video_core/renderer_vulkan/wrapper.cpp, src/video_core/renderer_vulkan/wrapper.h
Check() can throw an exception if the Vulkan result isn't successful.
We remove the check so that std::terminate isn't outright called and allows for better debugging (should it ever actually fail).
=> vulkan/wrapper: Remove noexcept from GetSurfaceCapabilitiesKHR()

src/video_core/buffer_cache/buffer_cache.h, src/video_core/macro/macro_jit_x64.cpp, src/video_core/memory_manager.cpp, src/video_core/memory_manager.h
Eliminates some cases of variable shadowing to prevent potential bugs from being hit in the future.
=> video_core: Eliminate some variable shadowing

src/core/arm/dynarmic/arm_dynarmic_32.cpp, src/core/arm/dynarmic/arm_dynarmic_64.cpp
arm_dynarmic_32: Log under Core_ARM instead of HW_GPU
arm_dynarmic_64: Log the instruction when an exception is raised
=> arm_dynarmic: Minor logging changes

src/common/telemetry.cpp, src/common/x64/cpu_detect.cpp, src/common/x64/cpu_detect.h, src/yuzu/main.cpp
Before:
```
Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
```
After:
```
Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz | AVX2 | FMA
```
Before:
```
Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
```
After:
```
Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz | AVX512 | FMA
```
AVX512 detection is done through checking the AVX512F, AVX512CD, AVX512VL, AVX512DQ, AVX512BW CPUID bits as these are the minimum supported sets in current mainstream AVX512 processors (SKL-X/SP and newer)
=> main/common: Log/append AVX/FMA to the Host CPU string if available and add AVX512 detection

src/video_core/texture_cache/texture_cache.h
Previously the source was being deduced twice in a row.
=> texture_cache: Fix incorrect address used in a DeduceSurface() call

dist/yuzu.manifest
See citra-emu/citra#5324 for more details.
Adds two new manifest element:
`dpiAwareness`: overrides the `dpiAware` element for Windows 10 version 1607 and later versions
`gdiScaling`: The GDI (graphics device interface) framework can apply DPI scaling to primitives and text on a per-monitor basis without updates to the application itself. (Introduce from Windows 10 version 1703).
Also formatted text for better readability. Added comments where appropriate.
=> Port citra-emu/citra#5324: "Update manifest file to include new elements that are introduced with Windows 10 later versions"

src/core/hle/service/am/applets/software_keyboard.cpp
We can just make use of moves here to get rid of two redundant copies
=> software_keyboard: Eliminate trivial redundant copies

src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Fixes #3969 
Enable `GL_EXT_texture_shadow_lod` if exposed by the gpu driver.
Utilizes the workaround described [here](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_glsl.cpp#L5872) and [here](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_glsl.cpp#L5949) if `GL_EXT_texture_shadow_lod` isn't available, allowing the compute shaders in The Legend of Zelda: Breath of the Wild to compile on Intel/AMD's proprietary drivers.
In my short testing I have not noticed any visual changes.
=> gl_shader_decompiler: Workaround textureLod when GL_EXT_texture_shadow_lod is not available

src/video_core/CMakeLists.txt, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/macro/macro.cpp, src/video_core/macro/macro.h, src/video_core/macro/macro_hle.cpp, src/video_core/macro/macro_hle.h, src/video_core/macro/macro_interpreter.cpp, src/video_core/macro/macro_jit_x64.cpp
This PR allows us to HLE macros to allow instanced drawing without executing and stepping through the macro. Originally we would heuristically try to work out if the macro is doing instanced drawing or not. With this PR we can just initiate an instanced draw without actually executing the macro. This leads to near-zero overhead due to macros.
The current HLE'd macros are: `0x771BB18C62444DA0`, `0x0D61FC9FAAC9FCAD`, `0x0217920100488FF7` which is used by most switch games. This list can be expanded as we find more macros.
=> Add support for HLEing Macros

src/video_core/buffer_cache/buffer_cache.h, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_buffer_cache.h, src/video_core/renderer_opengl/gl_device.cpp, src/video_core/renderer_opengl/gl_device.h, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_stream_buffer.cpp, src/video_core/renderer_opengl/gl_stream_buffer.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h, src/video_core/renderer_vulkan/vk_buffer_cache.cpp, src/video_core/renderer_vulkan/vk_buffer_cache.h, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_stream_buffer.h
Switch games are allowed to bind less data than what they use in a vertex buffer, the expected behavior here is that these values are read as zero. At the moment of writing this only D3D12, OpenGL through [NV_vertex_buffer_unified_memory](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_vertex_buffer_unified_memory.txt) and NVN support vertex buffer with a size limit.
In theory this could be emulated on Vulkan creating a new [VkBuffer](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkBufferCreateInfo.html) for each [handle, offset, length] tuple and binding the expected data to it. This is likely going to be slow and memory expensive when used on the vertex buffer and we have to do it on all draws because we can't know
without analysing indices when a game …
=> gl_rasterizer: Use NV_vertex_buffer_unified_memory for vertex buffer robustness

src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h
- Used by Captain Toad: Treasure Tracker Update 1.3.0
Stubs the following commands:
Command 302, StopConsoleSixAxisSensor
Command 303, ActivateSevenSixAxisSensor
Command 304, StartSevenSixAxisSensor
Command 307, FinalizeSevenSixAxisSensor
Command 310, ResetSevenSixAxisSensorTimestamp
While we're at it, fix the input parameters for SetIsPalmaAllConnectable and SetPalmaBoostMode
=> hid: Stub a series of "SevenSixAxisSensor" service commands

src/video_core/renderer_opengl/gl_device.cpp
Other targets were never actually checked despite being in a loop
=> gl_device: Fix IsASTCSupported to scan all targets instead of just GL_TEXTURE_2D

src/core/hle/service/caps/caps.cpp, src/core/hle/service/caps/caps.h, src/core/hle/service/caps/caps_a.cpp, src/core/hle/service/caps/caps_a.h, src/core/hle/service/caps/caps_c.cpp, src/core/hle/service/caps/caps_c.h, src/core/hle/service/caps/caps_sc.cpp, src/core/hle/service/caps/caps_sc.h, src/core/hle/service/caps/caps_ss.cpp, src/core/hle/service/caps/caps_ss.h, src/core/hle/service/caps/caps_su.cpp, src/core/hle/service/caps/caps_su.h, src/core/hle/service/caps/caps_u.cpp, src/core/hle/service/caps/caps_u.h
Use enum classes and check struct sizes on compile time.
While we're at it, update the copyright headers to "yuzu Emulator Project" on all the caps cpp/h files and fix the GetAlbumContentsFileListForApplication stub
=> caps: Use enum classes and check struct sizes on compile time

src/audio_core/stream.cpp, src/core/settings.cpp, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/config.h, src/yuzu/main.cpp
Mutes the audio by returning 0 to VolumeAdjustSamples() when toggled. The already existing volume setting won't be affected.
I decided to not make it save to the config file as muting audio may be a temporary thing for the current play session, but I'll change it if requested.
=> hotkeys: Add a "Mute Audio" hotkey

src/yuzu/bootmanager.cpp
Fix OpenGL renderer framebuffer size on fractional scaling display by using devicePixelRatioF()
Before:
After:
=> Fix framebuffer size on fractional scaling display

src/core/hle/service/lbl/lbl.cpp
This was based on Switchbrew page: https://switchbrew.org/wiki/Backlight_services
=> lbl: Update function table

src/yuzu/main.cpp
Currently when changing the fullscreen hotkey the old hotkey still works for entering fullscreen, while the new hotkey can toggle between. The context menu will also show the old hotkey until yuzu is restarted. And if you switch back to the first hotkey you'll have to press it twice to enter the fullscreen.
This fixes that.
At first I tried with 
`ui.action_Fullscreen->setShortcut(hotkey_registry.GetKeySequence(main_window, fullscreen));`
to keep it in the same style as the others above, but that caused the double press issue.
I also added 
`ui.action_Fullscreen->setShortcutContext(hotkey_registry.GetShortcutContext(main_window, fullscreen));`
for the same reason (I don't know what it does) but this fix works without it, so I don't know if it should be removed.
=> hotkeys: Fix issues caused when changing the fullscreen hotkey

src/video_core/macro/macro.cpp
Macro code is just uploaded sequentially from a starting address, however that does not mean the entry point for the macro is at that address. This PR adds preliminary support for executing macros in the middle of our cached code.
=> macro: Add support for "middle methods" on the code cache

src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/maxwell_to_gl.h, src/video_core/renderer_vulkan/maxwell_to_vk.cpp
maxwell_to_gl: Add 32 bit component sizes to (un)signed scaled formats and group (un)signed normalized, scaled, and integer formats together.
maxwell_to_vk: Reorder vertex formats and add A2B10G10R10 for all types except float
(Un)signed scaled formats with 32 bit component sizes have been confirmed to work on OpenGL using [these tests](https://github.com/yuzu-emu/yuzu/files/4842318/nxgputests.zip).
(And yes, I'm aware the diff looks like a mess)
=> maxwell_to_gl/vk: Reorder vertex formats

src/video_core/CMakeLists.txt, src/video_core/compatible_formats.cpp, src/video_core/compatible_formats.h, src/video_core/texture_cache/texture_cache.h
Supersedes #4156
Introducing a compatibility table to avoid illegal copies. This intercepts the last step of a copy to avoid generating validation errors or corrupting the driver on some instances.
We can create views and emit copies accordingly in future commits and remove this last-step validation.
This creates the compatibility table at runtime. I tried doing this constexpr but `returntype(std::bitset::operator[])::operator=` is not constexpr.
=> texture_cache: Check format compatibility before copying

src/common/memory_detect.cpp
Regressed by #3954. From [error log](https://github.com/yuzu-emu/yuzu/files/4848484/yuzu-s20200629.log):
```c++
src/common/memory_detect.cpp:15:10: fatal error: 'sys/sysinfo.h' file not found
#include <sys/sysinfo.h>
^~~~~~~~~~~~~~~
```
[sysinfo(2)](http://man7.org/linux/man-pages/man2/sysinfo.2.html) doesn't exist on any of BSDs. [libsysinfo](https://github.com/bsdimp/libsysinfo) relies on [kvm_getswapinfo(3)](https://man.freebsd.org/kvm_getswapinfo/3) which doesn't exist on NetBSD and OpenBSD. Also, installing libsysinfo [is dangerous](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=242236).
=> common: unbreak build on BSDs

src/video_core/renderer_opengl/maxwell_to_gl.h
Like MirrorOnceBorder, this requires the `GL_EXT_texture_mirror_clamp` extension. This extension is unfortunately not available on Intel's drivers (both Windows proprietary and Linux Mesa). Use `GL_MIRROR_CLAMP_TO_EDGE` as a fallback if the extension is unavailable.
A Vulkan equivalent is not available so it will be left unimplemented.
Used in Kirby Star Allies. Thanks to gidoly from the yuzu discord for the log.
=> maxwell_to_gl: Implement MirrorOnceClampOGL wrap mode using GL_MIRROR_CLAMP_EXT

src/common/CMakeLists.txt
On gcc/ld, and clang/lld, fmt::v6 symbols are excluded, so linking
fails. This fixes the issue.
Note: This was included in the FindBoost changes I shared with
BlinkHawk, however only they were merged. I'm not sure if it was missed,
or if there was an issue with this part of the change.
=> cmake: fix fmt linking

src/video_core/buffer_cache/buffer_cache.h, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_buffer_cache.h, src/video_core/renderer_vulkan/vk_buffer_cache.cpp, src/video_core/renderer_vulkan/vk_buffer_cache.h
After marking buffers as resident, Nvidia's driver seems to take a
slow path. To workaround this issue, copy to a STREAM_READ buffer and
then call GetNamedBufferSubData on it.
This is a temporary solution until we have asynchronous flushing.
=> gl_buffer_cache: Copy to buffers created as STREAM_READ before downloading

src/video_core/renderer_vulkan/fixed_pipeline_state.cpp, src/video_core/renderer_vulkan/fixed_pipeline_state.h, src/video_core/renderer_vulkan/vk_device.cpp, src/video_core/renderer_vulkan/vk_device.h, src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.h, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_rasterizer.h, src/video_core/renderer_vulkan/vk_state_tracker.cpp, src/video_core/renderer_vulkan/vk_state_tracker.h, src/video_core/renderer_vulkan/wrapper.cpp, src/video_core/renderer_vulkan/wrapper.h
Supersedes #4139.
Same as the linked PR, this time implementing the usage of [VK_EXT_extended_dynamic_state](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_EXT_extended_dynamic_state).
The graphics pipeline key has been rearranged to support hashing and `memcmp`ing with a variable size, this way we ignore state that can be changed dynamically.
As Miksel12 has pointed [here](https://github.com/yuzu-emu/yuzu/pull/4139#issuecomment-648377016), beta drivers for Nvidia are available, and there's also a merge request on mesa for ANV. This implementation has only been tested against Nvidia's driver without validation layers (as these don't exist/are not public yet).
=> vulkan: Use VK_EXT_extended_dynamic_state when available

.github/ISSUE_TEMPLATE/bug-report-feature-request.md, .github/ISSUE_TEMPLATE/config.yml
See citra-emu/citra#5364 for more details.
Hopefully this will decrease the number of users using GitHub issues for tech support requests.
Adds links to the discord, forums, and android repo for users reporting android bugs. There is a hyperlink at the bottom of the template page for those who want to create an actual issue.
=> Port citra-emu/citra#5364: ".github: add a new issue template"

src/core/memory.cpp
Users have been reporting the `Mapped memory page without a pointer` assertion being triggered, which should never happen.
The most likely way this is triggered is due to a race condition while modifying page tables. i.e.: An entry is accessed with an out-of-date attribute.
This PR attempts to 1. set `pointers` before `attribute = Memory`, and 2. set `attribute` before `pointers = nullptr` to avoid this race. Please not however that this is not a guaranteed fix because the compiler may reorder this operation during optimization.
Ideally one would audit the codebase for race-conditions and use appropriate synchronisation primitives as required.
=> memory: Race-condition in pagetables.

src/yuzu/configuration/configure_graphics.cpp
Unlikely to affect performance much at all, but it's essentially a free transformation, so why not?
While we're in the same area, we can tidy up two function pointer casts by making use of `qOverload`.
=>  configure_graphics: Prevent unnecessary string copies in UpdateDeviceComboBox()

CMakeLists.txt, externals/find-modules/FindLibUSB.cmake, src/input_common/gcadapter/gc_adapter.h
Regressed by #4137
- FreeBSD, OpenBSD, macOS use libc++ by default
- DragonFly, FreeBSD ship non-reference libusb
- 121af3646dad added `find_package(LibUSB)` but forgot to copy FindLibUSB.cmake from Dolphin
=> gcadapter: unbreak build on FreeBSD

src/video_core/renderer_vulkan/vk_stream_buffer.cpp
Fixes #3794 
This prevents the crash on Linux systems running the current Linux Long Lived branch NVIDIA driver (450.57). Sets allocable_size to 9 MiB, an experimentally determined value such that anything less than 9 MiB reproduces the crash. Many thanks to @ReinUsesLisp who helped me debug the error.
=> vk_stream_buffer: Prevent Vulkan crash in Linux on recent NVIDIA driver

CMakeLists.txt
Fixes the `Unknown CMake command "pkg_check_modules".` error when building on windows
=> cmake: Fix libusb builds breaking

CMakeLists.txt
Our convention uses lower-case command names, so this is just a consistency change.
=> CMakeLists: Use lower-case command names

CMakeLists.txt
Keeps the package up to date with the latest major release of fmt.
This version brings in quite a bit of improvements, such as code size reduction, etc. For a more detailed changelog, see fmt's [release](https://github.com/fmtlib/fmt/releases/tag/7.0.0) page.
=> CMakeLists: Update fmt to 7.0.1

src/core/crypto/key_manager.cpp
If the keys are zero, don't write them to the autogenerated file.
=> KeyManager: Prevent writing of invalid keys

src/common/alignment.h
See citra-emu/citra#5441 for more details.
In cases where the size is not a known constant when inlining, `AlignUp<std::size_t>` currently generates two 64-bit div instructions.
This generates one div and a cmov which is significantly cheaper.
https://godbolt.org/z/S848QG
=> Port citra-emu/citra#5441: "Common: remove a mod from AlignUp"

CMakeLists.txt
Do not search for system libusb on macOS. This allows yuzu is build on macOS. I note dolphin has the [same check](https://github.com/dolphin-emu/dolphin/blob/master/CMakeLists.txt#L696).
=> CMakeLists: Do not search for system libusb on macOS

src/video_core/renderer_vulkan/vk_rasterizer.cpp
This has been fixed in Nvidia's public beta driver 451.74. The previous
beta driver will be broken, people using this will have to update.
=> vk_rasterizer: Pass <pSizes> to CmdBindVertexBuffers2EXT

src/yuzu/CMakeLists.txt, src/yuzu/install_dialog.cpp, src/yuzu/install_dialog.h, src/yuzu/main.cpp, src/yuzu/main.h, src/yuzu/main.ui
Closes #3383
This extends the implementation of the `Install File to NAND` option to accept and install multiple files in a directory. Furthermore, a confirmation dialog has been added to confirm the installation of said files. This implementation is inspired by RPCS3's recent support for batch PKG install https://github.com/RPCS3/rpcs3/pull/7187.
A new option `Overwrite Existing Files` has been added to this confirmation dialog, allowing the user to choose whether or not to overwrite these files if they exist in the NAND. By default, this option is unticked, which means that already existing files will not be overwritten, and the user will not be prompted about overwriting files. If this option is ticked, it will overwrite all files in the selection.
At the end of installation a "Install …
=> frontend: Add support to batch install files to NAND

CMakeLists.txt, src/yuzu/game_list.cpp
Provides the buildbot with one builder that is always tracking the latest version of the C++ standard, allowing us to progressively rectify our code and amend any differences between standards over time instead of waiting for a complete standard change, potentially breaking a lot of code all at once.
For example, we already had some non-conformant code. `u8` prefixed on a string makes the string an array of `char8_t`, which is a distinct type in C++20.
GCC and clang have no concept of a "latest" switch unfortunately, so the same changes cannot be applied to them there.
=> CMakeLists: Make use of /std:c++latest on MSVC

CMakeLists.txt
Testing to see if this resolves the recent issues with yuzu's early access pipeline
=> CMakeLists: Disable concepts in boost asio

CMakeLists.txt
Previously the name of the define was missing the BOOST_ prefix.
=> CMakeLists: Correct boost asio disabling define name

CMakeLists.txt
This also fixes building on Linux with C++20, so we can enable it across the board for all OSes that we officially support.
Thanks to @ReinUsesLisp for testing it on Linux.
=> CMakeLists: Enable usage of C++20 on Linux

CMakeLists.txt, src/input_common/CMakeLists.txt, src/input_common/gcadapter/gc_adapter.cpp, src/input_common/gcadapter/gc_adapter.h, src/input_common/main.cpp
Regressed by #4266 
Fixes #4279
Reference libusb (unlike FreeBSD implementation) has `libusb-1.0/` directory prefix, so include directory from `pkg-config --cflags libusb-1.0` needs to be passed properly.
=> cmake: pass libusb include directory

src/yuzu/configuration/configure_general.cpp
This is likely an oversight during a rebase. This guards use_multi_core to only be set when the global value is in use. It should not make a difference given the current code base, but makes the code sensible and makes less assumptions.
=> configure_general: Explicitly guard use_multi_core when applying setting

src/input_common/udp/client.cpp
C++20 deprecates using the = lambda capture to implicitly capture the this pointer. Instead, we must specify it explicitly.
=> udp: Silence a C++20 deprecation warning

src/input_common/gcadapter/gc_adapter.cpp, src/input_common/gcadapter/gc_adapter.h, src/input_common/gcadapter/gc_poller.cpp, src/input_common/gcadapter/gc_poller.h
Tidies up some compiler warnings and also removes some deprecated usages of lambda captures in C++20.
=> gcadapter: Tidy up compiler warnings

src/input_common/gcadapter/gc_adapter.h, src/input_common/gcadapter/gc_poller.cpp
Previously, a crash would occur if the user has one of their inputs configured to be a GC adapter, but then attempts to launch a game if the adapter is unplugged. The state of the adapter would be queried, but there is no state, throwing an exception.
This checks first that a device is connected at the port, which is updated only if the adapter in properly plugged in and instantiated, before attempting to query its actual state.
=> gcadapter: Fix crash if gc configured but adapter not connected

src/video_core/engines/maxwell_dma.cpp, src/video_core/engines/maxwell_dma.h, src/video_core/texture_cache/surface_params.cpp, src/video_core/texture_cache/surface_params.h, src/video_core/textures/decoders.cpp, src/video_core/textures/decoders.h
Thanks to gdkchan from [Ryujinx](https://ryujinx.org/) for finding that some games copy pitch arrays to block linear 3D textures. The pull request can be found [here](https://github.com/Ryujinx/Ryujinx/pull/1354).
This PR renames registers in the `MaxwellDMA` class to match the [Nvidia's official documentation](https://github.com/NVIDIA/open-gpu-doc/blob/master/classes/dma-copy/clb0b5.h). Some names are unusual (like `offset_out` being `dest_gpu_addr`), but IMO it's better to stick to whatever names Nvidia uses.
Aside from some style changes, this adds support for copying 2D arrays of pixels into 3D voxels with a new function.
Thanks to @FernandoS27 for helping me understand how swizzle works.
Screenshot provided by BSoD gaming for Lego Super Heroes 2 running on Vulkan (to avoid having …
=> maxwell_dma: Match official doc and support pitch->voxel copies

src/common/swap.h
Allows removing a bunch of defines in favor of a two liner.
=> common/swap: Make use of std::endian

src/core/file_sys/registered_cache.cpp, src/core/file_sys/registered_cache.h, src/yuzu/main.cpp
- This checks for and removes old updates or dlc based on title id. If a content meta nca exists within the registered cache, it will attempt to remove all the ncas associated with the content meta before installing a new update/dlc
- Now updates and DLC can be properly overwritten
Note: If there are more than 1 update versions installed, this will not remove the extras properly.
=> registered_cache: Remove previous update/dlc if it exists on install

src/core/hle/kernel/handle_table.cpp, src/core/hle/kernel/handle_table.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/process.cpp, src/core/hle/kernel/process.h, src/core/hle/kernel/thread.cpp, src/core/hle/kernel/thread.h
Removes even more usages of the global system instance, trimming away more dependencies on global variables and making them explicit in the interface.
With this, the kernel has only one more remaining place that depends on the global system instance.
=> kernel/handle_table: Remove usages of the global system instance

src/yuzu/main.cpp
This exists as an option on the real Switch as well and saves some hassle for the users.
=> main/profile_select: Don't prompt for profile selection when only one is available

src/core/settings.cpp, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/main.cpp
Another error that got pass me and only noticed when I was doing the per-game settings UI rework. This prevents asynchronous GPU emulation from being disabled while multi core is enabled as a result of a poorly put together per-game config.
=> main: Set async gpu properly after loading per-game setting

src/core/cpu_manager.h, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/kernel.h, src/core/hle/kernel/scheduler.cpp, src/core/hle/kernel/thread.cpp
Previously the header for cpu_manager was relying upon indirect includes. This PR makes them explicit, so include orderings being changed in other files don't break the compilation of things in the header.
While we're at it, we can also tidy up some unused variables and getters.
=> cpu_manager: Minor tidying up/header inclusions

src/core/hle/kernel/memory/address_space_info.cpp, src/core/hle/kernel/memory/address_space_info.h
We can alter the structure so that we can use designated initializers in the array, eliminating the comments that indicate their field names. Also has the benefit of preventing bugs from reordering in the future, though this is unlikely to happen.
=> address_space_info: Make use of designated initializers

src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
For whatever reason, VK_TRUE and VK_FALSE aren't defined as having a VkBool32 type, so we need to cast to it explicitly.
=> vk_graphics_pipeline: Resolve narrowing warnings

src/video_core/renderer_vulkan/vk_texture_cache.cpp
Discovered while converting relevant parts of the codebase over to designated initializers.
=> vk_texture_cache: Amend mismatched access masks and indices in UploadBuffer

src/video_core/macro/macro_hle.cpp
Given the expression involves a 32-bit value, this simplifies down to just: 0x3ffffff. This is likely a remnant from testing that was never cleaned up.
Resolves a -Wshift-overflow warning.
=> macro_hle: Simplify shift expression in HLE_771BB18C62444DA0()

src/video_core/macro/macro.h
Resolves a -Wdocumentation warning.
=> macro: Resolve missing parameter in doxygen comment

src/core/CMakeLists.txt
Allows this header file to show up in IDE CMake generators.
=> core/CMakeLists: Add missing physical_memory.h header file

src/core/settings.cpp
In all usages of `LogSetting()`, string literals are provided. `std::string_view` is better suited here, as we won't churn a bunch of
string allocations every time the settings are logged out.
While we're at it, we can fold `LogSetting()` into `LogSettings()`, given it's only ever used there.
=> settings: Make use of std::string_view over std::string for logging

src/video_core/shader_cache.h
Now that we use C++20, we can also make use of std::erase_if instead of needing to do the erase-remove idiom.
=> shader_cache: Make use of std::erase_if

src/video_core/renderer_vulkan/vk_state_tracker.cpp
Fixes a regression on any game using stencil on devices with VK_EXT_extended_dynamic_state.
=> vk_state_tracker: Fix dirty flags for stencil_enable on VK_EXT_extended_dynamic_state

src/core/memory/dmnt_cheat_vm.cpp, src/core/memory/dmnt_cheat_vm.h
This was based on Atmosphére's DMNT Cheat VM:
- https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/dmnt/source/cheat/impl/dmnt_cheat_vm.hpp
- https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/dmnt/source/cheat/impl/dmnt_cheat_vm.cpp
From Atmosphére's documentation: "Code type 0xC3 reads or writes a static register with a given register"
There are now only two remaining opcodes to implement (PauseProcess and ResumeProcess)
This is untested because I don't have any experience in testing cheats on yuzu
=> dmnt_cheat_vm: Implement opcode 0xC3 (ReadWriteStaticRegister)

src/video_core/renderer_vulkan/vk_device.cpp
Designated initializers on old MSVC versions fail to build when they
take the address of a constant.
=> vk_device: Fix build error on old MSVC versions

src/video_core/renderer_vulkan/vk_buffer_cache.cpp, src/video_core/renderer_vulkan/vk_compute_pass.cpp, src/video_core/renderer_vulkan/vk_compute_pipeline.cpp, src/video_core/renderer_vulkan/vk_descriptor_pool.cpp, src/video_core/renderer_vulkan/vk_image.cpp, src/video_core/renderer_vulkan/vk_memory_manager.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_query_cache.cpp, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_renderpass_cache.cpp, src/video_core/renderer_vulkan/vk_resource_manager.cpp, src/video_core/renderer_vulkan/vk_sampler_cache.cpp, src/video_core/renderer_vulkan/vk_scheduler.cpp, src/video_core/renderer_vulkan/vk_shader_util.cpp, src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp, src/video_core/renderer_vulkan/vk_stream_buffer.cpp, src/video_core/renderer_vulkan/vk_swapchain.cpp, src/video_core/renderer_vulkan/vk_texture_cache.cpp, src/video_core/renderer_vulkan/wrapper.cpp
Makes use of designated initializers where applicable (and also don't ICE MSVC) across the board, normalizing all of the structs.
=> vulkan: Make use of designated initializers where applicable

src/core/hle/service/filesystem/filesystem.cpp
If subdirectories exist in the given path parameter and don't exist in the real filesystem create them prior to creating the files within.
This fixes the softlocks upon save creation in The Legend of Zelda: Breath of the Wild
=> filesystem: Create subdirectories prior to creating a file

src/common/alignment.h
With C++20, much of the allocator interface has been simplified, so we can make the same adjustments.
=> alignment: Simplify AlignmentAllocator implementation

src/audio_core/stream.cpp, src/audio_core/stream.h, src/core/core_timing.cpp, src/core/core_timing.h, src/core/hardware_interrupt_manager.cpp, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/server_session.cpp, src/core/hle/kernel/time_manager.cpp, src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h, src/core/hle/service/nvflinger/nvflinger.cpp, src/core/memory/cheat_engine.cpp, src/core/memory/cheat_engine.h, src/core/tools/freezer.cpp, src/core/tools/freezer.h, src/tests/core/core_timing.cpp
In a bunch of places we were using std::chrono types and in a bunch of other places, we were using raw primitive types. This aims to make it more consistent by using std::chrono::nanoseconds across the board, which makes for more consistent expectations when using the interface.
=> core_timing: Make usage of nanoseconds more consistent in the interface

src/common/alignment.h
Regressed by #4373. `std::align_val_t` is defined in `<new>` (previously, bootlegged via `<new>`) but GCC 10 can use `std::align_val_t` without any headers.
https://en.cppreference.com/w/cpp/memory/new/align_val_t
=> alignment: unbreak build with Clang

src/yuzu/debugger/wait_tree.cpp
=> frontend: Improve wait tree readability for dark themes

src/video_core/renderer_opengl/gl_arb_decompiler.cpp, src/video_core/renderer_opengl/gl_buffer_cache.cpp, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h, src/video_core/renderer_opengl/gl_shader_manager.cpp, src/video_core/renderer_opengl/gl_shader_manager.h, src/video_core/renderer_opengl/gl_stream_buffer.cpp
This shouldn't be tagged or merged until #4156 and #4157 are merged.
NV_shader_buffer_{[load](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_shader_buffer_load.txt),[store](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_shader_buffer_store.txt)} is a 2010 extension that allows GL applications
to use what in Vulkan is known as physical pointers, this is basically C
pointers. On GLASM these is exposed through the LOAD/STORE/ATOM
instructions.
Up until now, assembly shaders were using [NV_shader_storage_buffer_object](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_shader_storage_buffer_object.txt).
These work fine, but have a (probably unintended) limitation that forces
us to have the limit of a single stage for all shader stages. In contrast,
with …
=> gl_arb_decompiler: Use NV_shader_buffer_{load,store} on assembly shaders

src/core/CMakeLists.txt, src/core/core.cpp, src/core/network/network.cpp, src/core/network/network.h, src/core/network/sockets.h
This commit adds a network abstraction designed to implement bsd:s and nifm services but at the same time work as a generic abstraction to implement any networking code we have to use from core.
This is implemented on top of BSD sockets on Unix systems and winsock on Windows. The code is designed around winsocks having compatibility definitions to support both BSD and Windows sockets.
It is preferred to use this instead of `boost::asio` because the later is too high level for our needs. When implementing bsd:s procedures like `socket` we can't know ahead of time if this is going to be a client socket or an acceptor, but `boost::asio` wants to know this ahead of time.
The Linux code hasn't been tested at runtime because compilation is broken there and when attempting to remove the commits …
=> core/network: Add network abstraction

src/core/network/network.cpp
Regressed by #4306. From [error log](https://github.com/yuzu-emu/yuzu/files/4962915/yuzu-qt5-s20200721.log):
```c++
src/core/network/network.cpp:112:28: error: use of undeclared identifier 'SHUT_RD'
constexpr int SD_RECEIVE = SHUT_RD;
^
src/core/network/network.cpp:120:37: error: unknown type name 'in_addr'; did you mean 'in_addr_t'?
constexpr IPv4Address TranslateIPv4(in_addr addr) {
^~~~~~~
in_addr_t
```
=> network: unbreak build on FreeBSD

src/video_core/renderer_opengl/gl_arb_decompiler.cpp, src/video_core/renderer_opengl/gl_shader_cache.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/shader/decode/arithmetic_integer.cpp, src/video_core/shader/decode/video.cpp, src/video_core/shader/decode/xmad.cpp, src/video_core/shader/shader_ir.cpp
Removes const from some variables that are returned from functions, as this allows the move assignment/constructors to execute for them.
=> video_core: Allow copy elision to take place where applicable

src/video_core/buffer_cache/buffer_cache.h
A fairly trivial change. We can make use of emplace()'s return value to determine whether or not we need to perform an increment. emplace() performs no insertion if an element already exist, so this can eliminate a find() call.
=> buffer_cache: Eliminate redundant map lookup in MarkRegionAsWritten()

src/yuzu/configuration/configuration_shared.cpp, src/yuzu/configuration/configuration_shared.h, src/yuzu/configuration/configure_audio.cpp, src/yuzu/configuration/configure_audio.h, src/yuzu/configuration/configure_audio.ui, src/yuzu/configuration/configure_general.cpp, src/yuzu/configuration/configure_general.h, src/yuzu/configuration/configure_graphics.cpp, src/yuzu/configuration/configure_graphics.h, src/yuzu/configuration/configure_graphics.ui, src/yuzu/configuration/configure_graphics_advanced.cpp, src/yuzu/configuration/configure_graphics_advanced.h, src/yuzu/configuration/configure_graphics_advanced.ui, src/yuzu/configuration/configure_system.cpp, src/yuzu/configuration/configure_system.h, src/yuzu/configuration/configure_system.ui
In the original implementation of per-game configurations, the partially checked state of tristate check boxes were used to signal that a given setting would inherit its global configuration. In addition, many combo boxes stated "Use global configuration" to indicate the same behavior. Unfortunately it is not immediately clear to new users how tristate check boxes are supposed to work, and, assuming it is anyways, it is not convenient to go back-and-forth between the global config and the per-game config when the user forgets the global setting and wants to override it.
This PR aims to solve both of those problems. Check boxes still have three states, but they follow a different pattern:
1. they initially inherit the global state (can be on or off),
2. the first click negates the …
=> configure_per_game: Clearer per-game settings

src/video_core/renderer_vulkan/vk_rasterizer.cpp
The relevant values are already assigned further down in the lambda, so this can be removed entirely.
=> vk_rasterizer: Remove unused variable in Clear()

src/common/string_util.h
This function was relocated to log.h as a constexpr function, so this can be removed.
=> common/string_util: Remove unimplemented function prototype

src/yuzu/configuration/configure_debug.ui
Those are already found in the Filesystem tab.
They were added back to the Debug tab by mistake in the Vulkan PR.
Fixes https://github.com/yuzu-emu/yuzu/issues/4427.
=> yuzu/configure_debug: Remove duplicated checkboxes

src/input_common/udp/client.cpp
Also silences a deprecation warning from boost on Clang/GCC.
=> udp/client: Remove unused boost include

src/core/hle/service/nvflinger/nvflinger.cpp, src/core/hle/service/nvflinger/nvflinger.h, src/core/hle/service/vi/vi.cpp
comex reported in #4424 that we were incorrectly discarding the return value of Lock() which is correct.
While we're at it, we can make it more unlikely for issues like this to happen in the future by marking parts of the interface with the [[[nodiscard]]](https://en.cppreference.com/w/cpp/language/attributes/nodiscard) attribute.
=> nvflinger: Use return value of Lock()

src/input_common/gcadapter/gc_adapter.cpp
Without this, yuzu crashes with:
```
terminate called after throwing an instance of 'std::system_error'
what():  Invalid argument
Aborted
```
=> GCAdapter: only join worker thread if running & joinable

src/video_core/gpu.h
The puller register array is made up of u32s however the `NUM_REGS` value is the size in bytes, so switch it to avoid making the struct unnecessary large. Also fix a small typo in a comment.
=> video_core/gpu: Correct the size of the puller registers

dist/qt_themes/qdarkstyle/style.qss, dist/qt_themes/qdarkstyle_midnight_blue/style.qss
Fixes certain override highlights in per-game settings from looking broken when viewed on the Dark or Midnight Blue themes by setting QLabels to have transparent backgrounds by default.
Also apparently adds a newline to the end of the Dark theme's qss file.
=> qt_themes: Set QLabel background color to transparent for Dark and Midnight Blue themes

src/audio_core/stream.cpp, src/core/core_timing.cpp, src/core/core_timing.h, src/core/hardware_interrupt_manager.cpp, src/core/hle/kernel/kernel.cpp, src/core/hle/kernel/server_session.cpp, src/core/hle/kernel/time_manager.cpp, src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h, src/core/hle/service/nvflinger/nvflinger.cpp, src/core/memory/cheat_engine.cpp, src/core/memory/cheat_engine.h, src/core/tools/freezer.cpp, src/core/tools/freezer.h, src/tests/core/core_timing.cpp
This way, we have a type in place that is always guaranteed to be able to represent a pointer exactly, no matter the platform being compiled for. No behavioral changes. All this does is insert a more proper descriptive type in place. On x86-64, this is the same as using a `u64`.
=> core_timing: Make use of uintptr_t to represent user_data

src/core/settings.cpp, src/core/settings.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/configure_graphics_advanced.cpp, src/yuzu/configuration/configure_graphics_advanced.h, src/yuzu/configuration/configure_graphics_advanced.ui
The introduction of multicore rendered this setting non-functional as timing code was changed.
This removes the setting entirely.
=> configure_graphics: Remove Force 30 FPS mode

src/core/core.cpp, src/core/device_memory.cpp, src/core/device_memory.h
This isn't used by anything in particular, so it can be removed.
=> device_memory: Remove unused system member

src/core/file_sys/registered_cache.cpp, src/core/file_sys/registered_cache.h, src/core/file_sys/xts_archive.cpp, src/yuzu/game_list.cpp, src/yuzu/game_list.h, src/yuzu/main.cpp, src/yuzu/main.h
Adds the following actions to the context menu upon right clicking on a game entry.
- Remove Installed Update
- Remove All Installed DLC
- Remove Shader Cache
- Remove Custom Configuration
- Remove All Installed Contents
https://imgur.com/a/PctG5k7
https://imgur.com/a/G1VcuSE
https://imgur.com/a/NNZvHmt
https://imgur.com/a/1bopB5a
Closes #2633 
Update: Now supports removing SDMC installed titles as well as NAND installed titles.
=> game_list: Add "Remove" context menu

src/common/common_paths.h, src/common/file_util.cpp, src/common/file_util.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/config.h, src/yuzu/configuration/configure_ui.cpp, src/yuzu/configuration/configure_ui.ui, src/yuzu/main.cpp, src/yuzu/uisettings.h
Currently, to save a screenshot, there is no option but to choose a path and filename each time the user wanted to take a screenshot. In Linux, the Capture Screenshot QFileDialog is blank **if** it is visible, thus it is completely unusable.
This PR allows the user to save a screenshot immediately, shortcutting the process in Windows, and provides a workaround for the dialog issue in Linux until an actual solution is found. To control this behavior, in Emulation -> Configure... -> General -> UI there are two new options. The first lets the user choose whether yuzu prompts where to store the screenshot (marked as Windows only). The second is a text box that allows the user to specify a default path to save screenshots. Beside that is a button that opens a QFileDialog letting the user …
=> screenshots: Option to save screenshots immediately in a specified directory + Linux workaround

src/CMakeLists.txt, src/common/CMakeLists.txt, src/common/concepts.h, src/core/hle/kernel/hle_ipc.h, src/core/hle/service/acc/acc.cpp, src/core/hle/service/audio/hwopus.cpp, src/core/hle/service/bcat/module.cpp, src/core/hle/service/es/es.cpp, src/core/hle/service/nfp/nfp.cpp, src/core/hle/service/set/set.cpp, src/core/hle/service/time/time.cpp, src/core/hle/service/time/time_zone_service.cpp
With the support of C++20, we can use concepts to deduce if a type is an STL container or not.
=> ipc: Allow all trivially copyable objects to be passed directly into WriteBuffer

src/core/hle/service/ldr/ldr.cpp
We were performing an `int < size_t` comparison. We can just correct the type of the loop induction variable.
=> service/ldr: Resolve sign mismatch warnings

src/tests/core/core_timing.cpp
I made a review comment about this in the PR that this was introduced in (#3955, commit 71c4779211dc081a3b2dd4af52edad5748e7a7f5), but it seems to have been missed.
We shouldn't be using this pragma here because it's MSVC specific. This causes warnings on other compilers.
The test it's surrounding is *extremely* dubious, but for the sake of silencing warnings on other compilers, we can mark "placebo" as volatile and be on with it.
=> tests/core_timing: Remove pragma optimize(off)

src/core/hle/service/audio/audout_u.cpp, src/core/hle/service/nvdrv/interface.cpp, src/core/hle/service/vi/vi.cpp, src/video_core/gpu.cpp, src/yuzu/bootmanager.cpp, src/yuzu/configuration/configure_input_player.cpp, src/yuzu/configuration/configure_mouse_advanced.cpp, src/yuzu/configuration/configure_ui.cpp, src/yuzu/main.cpp
C++20 deprecates capturing the this pointer via the '=' capture. Instead, we replace it or extend the capture specification.
=> yuzu: Resolve C++20 deprecation warnings related to lambda captures

src/core/perf_stats.cpp, src/core/perf_stats.h
The general pattern is to mark mutexes as mutable when it comes to matters of constness, given the mutex acts as a transient member of a data structure: it's not a direct invariant of the data structure.
While we're at it, we can make use of designated initializers to directly initialize structs instead of zeroing them out beforehand.
=> perf_stats: Mark GetMeanFrametime() as const 

src/video_core/renderer_opengl/gl_rasterizer.cpp
This bumps up the maximum threads for asynchronous shader compilation to 4 threads, and ensures that no more than 25% of all threads are used.
The number of shader threads spawned are as follows:
```
CPU Threads  Shader Threads
<= 7               1
8-11               2
12-15               3
>= 16               4
```
=> renderer_opengl: Use 1/4 of all threads for async shader compilation

src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp, src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h, src/core/hle/service/nvdrv/devices/nvmap.cpp, src/core/hle/service/nvdrv/devices/nvmap.h, src/video_core/memory_manager.cpp, src/video_core/memory_manager.h
Rewrites our GPU Virtual Memory Manager. This greatly simplifies things, should reduce committed memory by the process, fixes many bugs, and allows us to implement a few new features. Among these, we implement the "remap" flag of the MapBufferEx ioctl. This fixes many of the graphical bugs with Mario Kart 8 Deluxe, as well as some of the softlock issues with Dragon Quest XI.
=> hle: nvdrv: Rewrite of GPU memory management.

src/core/loader/loader.cpp
Relies on #4465 for concept.h Common::IsBaseOf
Thanks to std::is_base_of_v we can ensure that everything passed is actually derived from "AppLoader" and not rely on preprocessor macros now.
=> loader: Make IdentifyFile typesafe

src/CMakeLists.txt
This switch is enabled by default in all recent versions of GCC and Clang.
Removing the flag just so I can see what the compiler error is if our GCC variant is too old. Otherwise it's basic enough to just check if clang is being used and not pass -fconcepts.
Fixes #4478
=> CMakeLists: Resolve #4478

src/core/hle/service/nvflinger/buffer_queue.cpp
Makes for less reading in the case of designated initializers.
In the case of std::nullopt, this allows compilers to eliminate unnecessary zeroing out of the optional's buffer.
=> buffer_queue: Make use of designated initializers/std::nullopt where applicable

src/core/crypto/aes_util.cpp, src/core/crypto/aes_util.h, src/core/crypto/ctr_encryption_layer.cpp, src/core/crypto/ctr_encryption_layer.h, src/core/crypto/partition_data_manager.cpp, src/core/file_sys/content_archive.cpp, src/core/file_sys/nca_patch.cpp
In a few places, the data to be set as the IV is already within an array. We shouldn't require this data to be heap-allocated if it doesn't need to be.
=> aes_util: Allow SetIV() to be non-allocating

src/core/hle/ipc_helpers.h
It's undefined behavior to use non-trivially copyable objects with std::memcpy, so we can add asserts to catch usages of these at compile-time.
=> ipc_helpers: Only allow trivially copyable objects with PushRaw() and PopRaw()

src/core/hle/kernel/address_arbiter.cpp, src/core/hle/kernel/scheduler.cpp
Makes the type conversion explicit.
=> address_arbiter/scheduler: Resolve sign conversion warnings

src/common/concepts.h, src/core/hle/service/sm/sm.h, src/core/loader/loader.cpp
This makes it more inline with its currently unavailable standardized analogue [std::derived_from](https://en.cppreference.com/w/cpp/concepts/derived_from). While we're at it, we can also make the template match the requirements of the standardized variant as well.
=> common/concepts: Rename IsBaseOf to DerivedFrom

.ci/scripts/format/script.sh, .travis/clang-format/script.sh
10.0 plays nicer with C++ attributes compared to clang-format 6.0.
Depends on https://github.com/yuzu-emu/build-environments/pull/15
=> ci: Make use of clang-format 10.0

.ci/scripts/format/script.sh, CMakeLists.txt, src/common/bit_field.h
Now that we updates to clang-format 10. This PR serves to catch anything that is now unconforming to the updated clang-format.
This just changes a piece of code in order to run the pass.
=> General: Tidy up clang-format warnings

src/common/virtual_buffer.cpp
Regressed by #3666. Similar to #4208. From [DragonFly build log](https://sting.dragonflybsd.org/dports/logs/emulators___yuzu-qt5.log):
```
src/common/virtual_buffer.cpp
src/common/virtual_buffer.cpp:16:10: fatal error: sys/sysinfo.h: No such file or directory
#include <sys/sysinfo.h>
^~~~~~~~~~~~~~~
```
=> common/virtual_buffer: drop unused includes

src/core/tools/freezer.cpp, src/core/tools/freezer.h
With C++20 we can simplify the erasing idiom.
While we're at it, we can coalesce the repeated entry finding code into their own functions to make for nicer reading.
=> freezer: Make use of std::erase_if

.ci/scripts/format/script.sh, src/audio_core/cubeb_sink.cpp, src/common/bit_field.h, src/common/detached_tasks.cpp, src/common/math_util.h, src/core/file_sys/registered_cache.h, src/core/hle/kernel/hle_ipc.cpp, src/core/hle/kernel/memory/page_table.cpp, src/core/hle/service/am/applets/web_browser.cpp, src/core/hle/service/audio/audout_u.cpp, src/core/hle/service/bcat/backend/boxcat.cpp, src/core/hle/service/nvflinger/nvflinger.h, src/input_common/udp/client.cpp, src/video_core/renderer_vulkan/wrapper.h, src/video_core/shader/control_flow.cpp, src/video_core/shader/decode/memory.cpp, src/yuzu/configuration/configure_input_player.cpp, src/yuzu/configuration/configure_mouse_advanced.cpp
General catch all for the clang-format migration changes. This shouldn't be merged until clang-format 10 issues are sorted out.
#4502 wasn't intended to be merged yet, but I forgot to mark the PR as a do not merge PR.
=> General: Tidy up clang-format warnings part 2

src/video_core/renderer_opengl/gl_shader_cache.cpp
Does not allocate more threads than available in the host system for boot-time shader compilation and always allocates at least 1 thread if `std::thread::hardware_concurrency()` returns 0.
=> gl_shader_cache: Use std::max() for determining num_workers

src/core/hle/service/time/time_zone_content_manager.cpp
Prevents a useless self-assignment from occurring.
=> time_zone_content_manager: Collapse auto and default case

src/video_core/engines/maxwell_dma.cpp, src/video_core/textures/decoders.cpp, src/video_core/textures/decoders.h
There were two issues with block linear copies. First the swizzling was wrong and this commit reimplements it.
The other issue was that these copies are generally used to download render targets from the GPU and yuzu was not downloading them from host GPU memory unless the extreme GPU accuracy setting was selected. This commit enables cached memory reads for all accuracy levels.
- Fixes level thumbnails in Super Mario Maker 2.
=> textures/decoders: Fix block linear to pitch copies

CMakeLists.txt
Keeps the library up to date and fixes a few bugs
See changelogs for:
- [7.0.2](https://github.com/fmtlib/fmt/releases/tag/7.0.2)
- [7.0.3](https://github.com/fmtlib/fmt/releases/tag/7.0.3)
respectively to see addressed issues.
=> CMakeLists: Update fmt to 7.0.3

src/common/lz4_compression.cpp, src/common/lz4_compression.h, src/common/zstd_compression.cpp, src/common/zstd_compression.h, src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
Allows condensing the data and data size parameters into a single argument.
=> lz4_compression/zstd_compression: Make use of std::span in interfaces

src/core/frontend/emu_window.h, src/core/hle/kernel/scheduler.h
Allows the compiler to warn about cases where the constructor is used but then immediately discarded, which is a potential cause of locking/unlocking bugs. Similar to thread locks, where the following is accidentally done:
```cpp
std::lock_guard{mutex}
```
instead of
```cpp
std::lock_guard guard{mutex};
```
=> kernel/scheduler: Mark SchedulerLock constructor as nodiscard 

src/core/hle/service/am/applets/software_keyboard.cpp
A std::vector created in place like this is already an rvalue and doesn't need to be moved.
=> software_keyboard: Resolve a pessimizing move warning

src/core/hle/result.h, src/core/hle/service/hid/controllers/npad.cpp, src/core/hle/service/nvdrv/devices/nvdevice.h
We can amend one of the cascade macros to require semicolons in order to compile. In other cases, we can just remove the superfluous semicolons. Silences around 30+ warnings.
=> core: Resolve several -Wextra-semi warnings

src/yuzu/game_list.cpp, src/yuzu/game_list_worker.cpp, src/yuzu/uisettings.h
While we're in the same area, we can ensure GameDir member variables are always initialized to consistent values.
=> yuzu: Resolve -Wextra-semi warnings

src/yuzu/main.cpp, src/yuzu/main.h, src/yuzu/main.ui
Creates a new entry in the Emulation menu labelled "Configure Current Game..." that is only enabled if a game is currently being run in yuzu. When selected, it opens the game properties dialog for the current game.
Thanks to BSoD for reminding me to do this.
=> main: Add an option to modify the currrent game's configuration

src/core/crypto/aes_util.cpp, src/core/crypto/partition_data_manager.cpp
Same behavior, but minus a template instantiation. The input parameters are already typed correct to be able to be used with the non-template variant. While we're at it, we can get rid of a magic constant.
=> aes_util: Make use of non-template variant of Transcode

src/yuzu/configuration/configure_hotkeys.cpp
There's no need to translate an empty string. This just gives translators unnecessary work.
=> configure_hotkeys: Don't translate empty strings

src/common/time_zone.cpp
We can simplify this function down into a single line with the use of fmt. A benefit with the fmt approach is that the fmt variant of localtime is thread-safe, making GetOsTimeZoneOffset() thread-safe as well.
=> common/time_zone: Simplify GetOsTimeZoneOffset()

src/yuzu/configuration/configuration_shared.cpp, src/yuzu/configuration/configuration_shared.h, src/yuzu/configuration/configure_audio.cpp, src/yuzu/configuration/configure_general.cpp, src/yuzu/configuration/configure_graphics.cpp, src/yuzu/configuration/configure_graphics_advanced.cpp, src/yuzu/configuration/configure_system.cpp
We can query the given object name directly from the widget itself. This removes any potential for forgetting to change the name if the widget gets renamed and makes the API much simpler (just pass in the widget, and not worry about its name).
=> configuration_shared: Simplify name lookup in highlighting functions

src/yuzu/game_list.cpp, src/yuzu/game_list.h, src/yuzu/main.cpp, src/yuzu/main.h
Previously NAND/SDMC installed titles would open device saves when they are supposed to be user saves. This is due to the control nca not being read and thus returns 0 for both GetDefaultNormalSaveSize() and GetDeviceSaveDataSize(). Fix this by utilizing the patch manager to read the control nca.
=> main: Fix Open Save/Mod Locations for installed titles

src/video_core/renderer_vulkan/wrapper.cpp
Given this is implicitly creating a std::optional, we can move the vector into it.
=> vulkan/wrapper: Avoid unnecessary copy in EnumerateInstanceExtensionProperties()

src/common/dynamic_library.cpp, src/common/file_util.cpp
These are intentionally discarded internally, since the rest of the public API allows querying success. We want all non-internal uses of
these functions to be explicitly checked, so we can signify that we intentionally want to discard the return values here.
=> common: Silence two discarded result warnings

src/common/concepts.h
This is a compiler/linker error waiting to happen.
=> common/concepts: Move <type_traits> include out of the Common namespace

src/common/telemetry.cpp, src/common/telemetry.h, src/core/core.cpp, src/core/telemetry_session.cpp, src/core/telemetry_session.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_vulkan/renderer_vulkan.cpp, src/web_service/telemetry_json.cpp, src/web_service/telemetry_json.h, src/yuzu/compatdb.cpp, src/yuzu/main.cpp, src/yuzu_cmd/yuzu.cpp, src/yuzu_tester/yuzu.cpp
Migrates the Telemetry namespace into the Common namespace to make the code consistent with the rest of our common code.
=> common/telemetry: Migrate namespace into the Common namespace

src/common/CMakeLists.txt, src/web_service/CMakeLists.txt, src/web_service/telemetry_json.cpp, src/web_service/verify_login.cpp, src/web_service/web_backend.cpp, src/web_service/web_backend.h, src/web_service/web_result.h
This is the only place it's actively used. It's also more appropriate for web-related structures to be within the web service target. Especially given this one doesn't rely on anything in the common library.
=> web_service: Move web_result.h into web_service

src/core/file_sys/vfs_real.cpp
Avoids some trivially avoidable map lookups by keeping the result of find operations around and querying them. Reduces overhead a tiny bit.
=> vfs_real: Avoid redundant map lookups

src/core/crypto/key_manager.cpp, src/core/crypto/key_manager.h
We can convert these maps into constexpr arrays to eliminate some runtime static constructors.
=> key_manager: Make data arrays constexpr

src/video_core/fence_manager.h, src/video_core/renderer_opengl/gl_fence_manager.cpp, src/video_core/renderer_opengl/gl_fence_manager.h
Avoids pulling in unnecessary things that can cause rebuilds when they aren't required.
=> video_core/fence_manager: Remove unnecessary includes

src/video_core/renderer_opengl/gl_texture_cache.cpp, src/video_core/renderer_opengl/gl_texture_cache.h
LabelGLObject takes a string_view, so we don't need to make copies of the std::string.
=> gl_texture_cache: Take std::string by reference in DecorateViewName()

src/core/cpu_manager.cpp
We can simplify a few loops by making use of ranged for.
=> cpu_manager: Make use of ranged for where applicable

src/video_core/engines/fermi_2d.cpp, src/video_core/engines/fermi_2d.h, src/video_core/engines/kepler_compute.cpp, src/video_core/engines/kepler_compute.h, src/video_core/engines/maxwell_3d.cpp, src/video_core/engines/maxwell_3d.h, src/video_core/gpu.cpp, src/video_core/gpu.h, src/video_core/gpu_asynch.cpp, src/video_core/gpu_asynch.h, src/video_core/gpu_synch.cpp, src/video_core/gpu_synch.h, src/video_core/macro/macro_hle.cpp, src/video_core/memory_manager.cpp, src/video_core/memory_manager.h, src/video_core/renderer_base.cpp, src/video_core/renderer_base.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h, src/video_core/renderer_vulkan/renderer_vulkan.cpp, src/video_core/renderer_vulkan/renderer_vulkan.h, src/video_core/video_core.cpp
Add an extra step in GPU initialization to be able to initialize render backends with a valid GPU instance.
This will allow us to avoid having `Core::System` instances in a follow up commit.
=> video_core: Initialize renderer with a GPU

src/common/color.h
No external code makes use of this header, so we can freely change the namespace.
=> common/color: Migrate code over to the Common namespace

src/core/file_sys/registered_cache.cpp
Removes the need for comments to indicate the fields being assigned.
=> registered_cache: Make use of designated initializers

src/video_core/memory_manager.cpp, src/video_core/memory_manager.h
This doesn't modify internal member state, so it can be marked as const.
=> memory_manager: Mark IsGranularRange() as a const member function

src/video_core/memory_manager.h
This doesn't modify member state, so it can be marked as const.
While we're at it, we can mark several member functions as nodiscard.
=> memory_manager: Make operator+ const qualified

src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_state_tracker.cpp, src/video_core/renderer_vulkan/vk_state_tracker.h
State track the current primitive topology with a regular comparison instead of using dirty flags.
This fixes a bug in dirty flags for this particular state and it also avoids unnecessary state changes as this property is stored in a frequently changed bit field.
- Fixes a regression on drivers with `VK_EXT_extended_dynamic_state` on Smash Ultimate.
=> vk_state_tracker: Fix primitive topology

src/video_core/shader/decode/memory.cpp
Given a message isn't provided, we should be using this variant of the macro.
=> shader/memory: Amend UNIMPLEMENTED_IF_MSG without a message

src/common/assert.h
Normalizes the syntax used for attributes
=> common/assert: Make use of C++ attribute syntax

src/input_common/main.cpp, src/input_common/main.h, src/yuzu/bootmanager.cpp, src/yuzu/bootmanager.h, src/yuzu/configuration/configure_debug_controller.cpp, src/yuzu/configuration/configure_debug_controller.h, src/yuzu/configuration/configure_dialog.cpp, src/yuzu/configuration/configure_dialog.h, src/yuzu/configuration/configure_input.cpp, src/yuzu/configuration/configure_input.h, src/yuzu/configuration/configure_input_player.cpp, src/yuzu/configuration/configure_input_player.h, src/yuzu/configuration/configure_mouse_advanced.cpp, src/yuzu/configuration/configure_mouse_advanced.h, src/yuzu/main.cpp, src/yuzu/main.h, src/yuzu_cmd/emu_window/emu_window_sdl2.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2.h, src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2_gl.h, src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2_vk.h, src/yuzu_cmd/yuzu.cpp, src/yuzu_tester/emu_window/emu_window_sdl2_hide.cpp, src/yuzu_tester/emu_window/emu_window_sdl2_hide.h
Abstracts most of the input mechanisms under an InputSubsystem class that is managed by the frontends, eliminating any static constructors and destructors. This gets rid of global accessor functions and also allows the frontends to have a more fine-grained control over the lifecycle of the input subsystem.
This also makes it explicit which interfaces rely on the input subsystem instead of making it opaque in the interface functions. All that remains to migrate over is the factories, which can be done in a separate change.
=> input_common: Eliminate most global state

src/video_core/renderer_vulkan/vk_device.cpp
Vertex binding's <stride> is bugged on AMD's proprietary drivers when
using VK_EXT_extended_dynamic_state. Blacklist it for now while we
investigate how to report this issue to AMD.
It might be possible the driver is interpreting `<stride>` as in OpenGL's `VertexAttribPointer` instead of `BindVertexBuffer`.
- Fixes [SMO corruption](https://user-images.githubusercontent.com/26564870/91619271-0699d380-e963-11ea-8315-ff87ff107846.png) on the latest AMD proprietary drivers.
=> vk_device: Blacklist AMD proprietary from VK_EXT_extended_dynamic_state

src/input_common/main.h, src/input_common/sdl/sdl_impl.cpp, src/input_common/settings.h
I forgot to remove this in the rebase when removing most of the global variables within the input common codebase.
=> input_common/main: Remove unimplemented prototype

src/yuzu/bootmanager.cpp, src/yuzu/bootmanager.h, src/yuzu/main.cpp, src/yuzu/main.h
Due to the way Qt performs destruction of parent/child widgets, we need to make the lifetime of the input subsystem shared across the main window and the render window.
=> yuzu/main: Amend lifetime issues with InputSubsystem

src/yuzu/bootmanager.cpp
The list of points is returned by const reference, so we don't need to make a copy of every element in the list.
=> bootmanager: Prevent unnecessary copies in TouchUpdateEvent()

src/video_core/renderer_vulkan/vk_device.cpp
'driver_id' can only be known on Vulkan 1.1 after creating a logical
device. Move the driver id check to disable
VK_EXT_extended_dynamic_state after the logical device is successfully
initialized.
The Vulkan device will have the extension enabled but it will not be
used.
=> vk_device: Fix driver id check on AMD for VK_EXT_extended_dynamic_state

src/common/thread.cpp, src/core/cpu_manager.cpp
- In `SetCurrentThreadName`, when on Linux, truncate to 15 bytes, as (at least on glibc) `pthread_set_name_np` will otherwise return `ERANGE` and do nothing.
- Also, add logging in case `pthread_set_name_np` returns an error anyway.  This is Linux-specific, as the Apple and BSD versions of `pthread_set_name_np` return `void`.
- To make things slightly more succinct, change `SetCurrentThreadName` to take `const std::string&` rather than `const char *`.
- Change the name for CPU threads in multi-core mode from "yuzu:CoreCPUThread_N" (19 bytes) to "yuzu:CPUCore_N" (14 bytes) so it fits into the Linux limit.  Some other thread names are also cut off, but I didn't bother addressing them as you can guess them from the truncated versions.  For a CPU thread, truncation means you can't see which …
=> Fix thread naming on Linux, which limits names to 15 bytes.

dist/qt_themes/qdarkstyle/style.qss, src/core/frontend/framebuffer_layout.h, src/core/hle/service/hid/controllers/touchscreen.cpp, src/core/hle/service/hid/controllers/touchscreen.h, src/core/settings.h, src/input_common/CMakeLists.txt, src/input_common/main.cpp, src/input_common/main.h, src/input_common/touch_from_button.cpp, src/input_common/touch_from_button.h, src/yuzu/CMakeLists.txt, src/yuzu/configuration/config.cpp, src/yuzu/configuration/config.h, src/yuzu/configuration/configure_input.cpp, src/yuzu/configuration/configure_input_advanced.cpp, src/yuzu/configuration/configure_input_advanced.h, src/yuzu/configuration/configure_motion_touch.cpp, src/yuzu/configuration/configure_motion_touch.h, src/yuzu/configuration/configure_motion_touch.ui, src/yuzu/configuration/configure_touch_from_button.cpp, src/yuzu/configuration/configure_touch_from_button.h, src/yuzu/configuration/configure_touch_from_button.ui, src/yuzu/configuration/configure_touch_widget.h
This ports several PRs from Citra, adding a motion and touch configuration UI to yuzu.
See https://github.com/citra-emu/citra/pull/5163 and https://github.com/citra-emu/citra/pull/4059 for the two main PRs this code comes from.
Thanks to @z87 and @zhaowenlan1779 for doing most of the original work.
**THIS DOES NOT ADD MOTION CONTROLS TO YUZU**.
=> yuzu: Add motion and touch configuration from Citra

src/common/quaternion.h, src/input_common/CMakeLists.txt, src/input_common/motion_input.cpp, src/input_common/motion_input.h
This class does all the calculations needed to add full motion control to all devices.
The transformation from quaternion to rotation matrix is based on this PR [Add Motion controls #1363](https://github.com/Ryujinx/Ryujinx/pull/1363)
The quaternion algorithm is based on this repository [Open-Source-AHRS-With-x-IMU](https://github.com/xioTechnologies/Open-Source-AHRS-With-x-IMU/blob/master/x-IMU%20IMU%20and%20AHRS%20Algorithms/x-IMU%20IMU%20and%20AHRS%20Algorithms/AHRS/MahonyAHRS.cs)
=> input_common: Add a basic class for motion devices

src/common/math_util.h, src/input_common/motion_input.cpp, src/input_common/motion_input.h
Also amend the copyright notice to yuzu's instead of Dolphin's, which was mistakenly copy-pasted from another file.
=> input_common/motion_input: Make use of Common::PI constant

src/yuzu/main.ui
Fixes a typo in the UI file for "Configure Current Game...". An ellipsis has 3 dots.
=> main: Use three dots to complete the ellipsis

externals/libusb/CMakeLists.txt
Given we have two libraries that seem to use the same identifier, we can alter one of them so that the variable is used in place, effectively changing the used identifier, but without altering the source of libusb.
=> externals: Work around libusb duplicate GUID errors

src/core/crypto/partition_data_manager.cpp, src/core/file_sys/bis_factory.cpp, src/core/file_sys/bis_factory.h, src/core/file_sys/card_image.cpp, src/core/file_sys/card_image.h, src/core/file_sys/content_archive.cpp, src/core/file_sys/content_archive.h, src/core/file_sys/control_metadata.cpp, src/core/file_sys/control_metadata.h, src/core/file_sys/kernel_executable.cpp, src/core/file_sys/kernel_executable.h, src/core/file_sys/nca_metadata.cpp, src/core/file_sys/nca_metadata.h, src/core/file_sys/partition_filesystem.cpp, src/core/file_sys/partition_filesystem.h, src/core/file_sys/patch_manager.cpp, src/core/file_sys/patch_manager.h, src/core/file_sys/program_metadata.cpp, src/core/file_sys/program_metadata.h, src/core/file_sys/romfs.h, src/core/file_sys/sdmc_factory.cpp, src/core/file_sys/sdmc_factory.h, src/core/file_sys/submission_package.cpp, src/core/file_sys/submission_package.h, src/core/file_sys/xts_archive.cpp, src/core/file_sys/xts_archive.h, src/core/hle/service/ns/ns.cpp
Same behavior, minus unnecessary inclusions where not necessary.
=> file_sys: Replace inclusions with forward declarations where applicable

src/core/hle/service/filesystem/fsp_srv.cpp
We can initialize `id` to a deterministic value and also mark the unreachable cases in the switch with `UNREACHABLE()`.
=> fsp_srv: Resolve -Wmaybe_uninitialized warning in OpenSaveDataFileSystem()

.lgtm.yml
See citra-emu/citra#5495 for more details.
Refer to citra-emu/citra#5494 for some example issues found. LGTM analysis for this repo can be viewed [here](https://lgtm.com/projects/g/citra-emu/citra/alerts/?mode=tree). Note: this doesn't affect existing CI routines in any way.
Added config file makes static analysis results much easier to read and also speeds up analysis process by preinstalling used packages.
Potential addition:
```YAML
queries:
include: "*"
```
This enables all warning types as opposed to default only. It might be a good idea to enable later on once default ones are addressed.
Additionally, it's worth taking a look at https://lgtm.com/projects/g/citra-emu/citra/ci/. Automatic check for new alerts introduced by PRs and alerts count/code quality …
=> Port citra-emu/citra#5495: "Add LGTM static analyzer config file"

src/core/hle/service/hid/controllers/npad.cpp, src/core/hle/service/hid/controllers/npad.h, src/core/hle/service/hid/hid.cpp
This implementation was split from #4597
- Fully implement the MergeSingleJoyAsDualJoy HID service command. This merges a pair of left and right joycons into a Dual Joycon. Used in Super Mario Odyssey when going into 1 Player mode from 2 Player mode.
=> hid: Implement MergeSingleJoyasDualJoy

src/core/CMakeLists.txt, src/core/hle/service/nifm/nifm.cpp, src/core/hle/service/service.cpp, src/core/hle/service/sockets/blocking_worker.h, src/core/hle/service/sockets/bsd.cpp, src/core/hle/service/sockets/bsd.h, src/core/hle/service/sockets/sockets.cpp, src/core/hle/service/sockets/sockets.h, src/core/hle/service/sockets/sockets_translate.cpp, src/core/hle/service/sockets/sockets_translate.h
This implements from `bsd:s`: `Socket`, `Poll`, `Accept`, `Bind`, `Connect`, `GetPeerName`, `GetSockName`, `Listen`, `Fcntl`, `SetSockOpt`, `Shutdown`, `Recv`, `RecvFrom`, `Send`, `SendTo`, `Write`, and `Close`. From `nifm`, `GetCurrentIpAddress` is implemented.
The implementation was done referencing: SwIPC, switchbrew, testing with libnx and inspecting its code, general information about bsd sockets online, and analysing official software.
Not everything from these service calls is implemented, but everything that is not implemented will be logged in some way.
Thanks to ogniK and Blinkhawk for helping me understand the overall structure of our IPC abstraction and guest thread/event management related to services.
With this, [ftpd](https://github.com/mtheall/ftpd) works locally:
=>  services: Implement most of bsd:s and GetCurrentIpAddress from nifm

src/input_common/gcadapter/gc_adapter.cpp, src/input_common/gcadapter/gc_adapter.h, src/input_common/gcadapter/gc_poller.cpp
This doesn't modify instance state, so it can be made const.
This allows several pointers to be made const, making their read-only nature explicit in our interfaces.
=> gc_adapter: Make DeviceConnected() a const member function

src/yuzu/configuration/configure_input_player.cpp
Prevents sign mismatch warnings in the loop conditionals.
=> configure_input_player: Resolve sign conversion warnings in UpdateMappingWithDefaults()

src/audio_core/CMakeLists.txt, src/audio_core/algorithm/interpolate.cpp, src/audio_core/algorithm/interpolate.h, src/audio_core/audio_renderer.cpp, src/audio_core/audio_renderer.h, src/audio_core/behavior_info.cpp, src/audio_core/behavior_info.h, src/audio_core/command_generator.cpp, src/audio_core/command_generator.h, src/audio_core/common.h, src/audio_core/cubeb_sink.cpp, src/audio_core/effect_context.cpp, src/audio_core/effect_context.h, src/audio_core/info_updater.cpp, src/audio_core/info_updater.h, src/audio_core/memory_pool.cpp, src/audio_core/memory_pool.h, src/audio_core/mix_context.cpp, src/audio_core/mix_context.h, src/audio_core/sink_context.cpp, src/audio_core/sink_context.h, src/audio_core/splitter_context.cpp, src/audio_core/splitter_context.h, src/audio_core/stream.cpp, src/audio_core/voice_context.cpp, src/audio_core/voice_context.h, src/core/hle/service/audio/audren_u.cpp
This is part one of a multipart reimplementation of the Nintendo switch audio renderer system module. The nintendo switch audio renderer is much like a giant state machine with many moving parts to it.
The behavior info aspect of audio is mainly in charge of providing the information for backward compatibility and tracking various non-critical errors. It handles all version checks for what features can/can't be used as well as bugs that have and haven't been fixed. This means if there were bugs in a previous version of audio renderer(such as incorrect splitter sizes), this bug will need to remain to provide backward compatibility to games that target older system versions.
Memory pools are responsible for sharing data to and from the DSP. They can either be attached or detatched. As we …
=> audio_core: Apollo Part 1, AudioRenderer refactor

src/core/hle/service/sockets/blocking_worker.h, src/core/hle/service/sockets/bsd.cpp, src/core/hle/service/sockets/sockets_translate.cpp
Resolves a few warnings in our BSD code on Windows and Clang.
This also includes a bugfix for SendToImpl where the address would never be propagated down to SendTo.
=> bsd: Resolve a few warnings

.lgtm.yml
Follow-up to #4596, which was originally authored by me. Currently, build fails when searching for `clang-format-10` as it is missing for whatever reason.
Even with this patch analysis still fails due to CMake version being 3.13.4 and Yuzu needing at least 3.15, but at least we are not ones to blame now. Once they upgrade their distro used for build, it will likely start working.
P.S.: when it does, I'm going to look into this once more and specify all packages it will pull into this file to speed build up.
=> Remove bad and useless packages from LGTM build

src/core/hle/service/service.cpp, src/core/hle/service/service.h, src/core/hle/service/sm/sm.cpp
Removes more instances of reliance on global state.
=> service: Remove two usages of the global system accessor

src/core/hle/kernel/client_session.cpp, src/core/hle/kernel/client_session.h, src/core/hle/kernel/server_session.cpp, src/core/hle/kernel/server_session.h, src/core/hle/kernel/svc.cpp
With this, the kernel finally doesn't depend directly on the global system instance anymore.
All that remains to have their dependency on the global instance removed is:
- 18 instances in the file_sys code
- 14 instances in the GDB stub (this is broken anyways, so this can be tossed if it really comes down to it)
- 6 instances in the loader code.
- 4 instances in the services
- 2 instances in the settings code
- 1 instance in the crypto code
After all these are removed in the future, our frontends will be able to have full control over the lifecycle of the entire emulated system (and will likely make start up a little faster, given less static constructors).
=> kernel: Remove all dependencies on the global system instance

src/core/crypto/key_manager.cpp, src/core/crypto/key_manager.h, src/yuzu/main.cpp
We can supply the content provider as an argument instead of hardcoding a global accessor in the implementation.
Now the crypto code no longer has any dependencies on the global system instance.
=> crypto/key_manager: Remove dependency on the global system accessor

src/core/file_sys/patch_manager.cpp, src/core/file_sys/patch_manager.h
Tidies up the external interface of the patch manager a little bit. Figured I may as well get this out of the way before eliminating reliance on the global system instance.
Each commit should be fairly straightforward.
=> patch_manager: Minor cleanup

src/core/file_sys/patch_manager.cpp, src/core/memory/cheat_engine.cpp, src/core/memory/cheat_engine.h
This isn't used within the function at all in any implementations, so we can remove it entirely.
=> cheat_engine: Remove unnecessary system argument to CheatParser's Parse function

src/core/file_sys/nca_patch.cpp, src/core/file_sys/nca_patch.h
Previously, this function was using around ~16.5KB (16528 bytes) on the stack, since the arguments passed in were taken by value.
Given this function doesn't modify the passed in values, we can take these arguments by const reference and get rid of a lot of unnecessary copying.
=>  nca_patch: Reduce stack usage size within SearchBucketEntry()

src/core/core.cpp, src/core/loader/deconstructed_rom_directory.cpp, src/core/loader/deconstructed_rom_directory.h, src/core/loader/elf.cpp, src/core/loader/elf.h, src/core/loader/kip.cpp, src/core/loader/kip.h, src/core/loader/loader.h, src/core/loader/nax.cpp, src/core/loader/nax.h, src/core/loader/nca.cpp, src/core/loader/nca.h, src/core/loader/nro.cpp, src/core/loader/nro.h, src/core/loader/nso.cpp, src/core/loader/nso.h, src/core/loader/nsp.cpp, src/core/loader/nsp.h, src/core/loader/xci.cpp, src/core/loader/xci.h
Now all that remains is:
- 18 instances in file_sys code
- 14 instances in GDB stub code (this can be tossed wholesale)
- 4 instances in HLE code
- 2 instances in settings code.
=> core/loader: Remove dependencies on the global system instance

src/input_common/gcadapter/gc_adapter.cpp
Pragma disable zero-sized array nonstandard extension warning on MSVC.
=> gc_adapter: Disable MSVC nonstandard extension warning on libusb.h

src/core/file_sys/control_metadata.h
This isn't used anywhere, so this is a trivial fix.
=> control_metadata: Resolve typo in Portuguese language name

src/core/frontend/input.h, src/core/hle/service/hid/controllers/npad.cpp, src/core/hle/service/hid/controllers/npad.h, src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h, src/core/settings.h, src/input_common/main.cpp, src/input_common/main.h, src/input_common/motion_emu.cpp, src/input_common/settings.cpp, src/input_common/settings.h, src/input_common/udp/client.cpp, src/input_common/udp/client.h, src/input_common/udp/udp.cpp, src/input_common/udp/udp.h, src/yuzu/configuration/config.cpp, src/yuzu/configuration/config.h, src/yuzu/configuration/configure_input.cpp, src/yuzu/configuration/configure_input_player.cpp, src/yuzu/configuration/configure_input_player.h, src/yuzu/configuration/configure_input_player.ui, src/yuzu_cmd/config.cpp, src/yuzu_tester/config.cpp
This is a follow up of this PR #3890. It includes shared memory for motion controls and the configuration needed to map motion devices. This PR does not include any kind of motion input devices.
With the PR #4570 and #4411. Most games that use motion work properly. Thanks to theboy181 for helping with testing motion controls.
=> hid/configuration: Implement motion controls to HID

src/video_core/shader/decode/image.cpp
Fortunately this didn't result in any issues, given the block that code was falling through to would immediately break.
=> decode/image: Eliminate switch fallthrough in DecodeImage()

src/video_core/shader/decode/texture.cpp
The assignment was previously truncating a u64 value to a bool, which can cause a build error on the latest version of MSVC.
=> decoder/texture: Eliminate narrowing conversion in GetTldCode()

src/audio_core/command_generator.cpp, src/core/hle/service/nfp/nfp.cpp
GetAmiiboBuffer() returns by const reference, so we can use a reference instead of taking the returned buffer by value.
=> command_generator/nfp: Eliminate unnecessary copies

src/core/core.cpp, src/core/hle/service/sm/sm.cpp, src/core/hle/service/sm/sm.h
Removes a dependency on the global system instance in the service manager code.
After this, the service manager no longer has a dependency on the global system accessor at all.
=> service/sm: Eliminate dependency on the global system instance

src/core/arm/dynarmic/arm_dynarmic_cp15.h
Ensures that the member variables are always initialized to a deterministic value on creation.
=> arm_dynarmic_cp15: Initialize member variables

src/core/hle/service/am/am.cpp, src/core/hle/service/am/am.h
- Used in Super Mario 3D All-Stars
Also allows it to boot to the launcher with #4675
=> am: Stub GetPreviousProgramIndex

src/yuzu/configuration/configure_input_player.cpp, src/yuzu/configuration/configure_input_player.h
The context menu was removed in Mjölnir Part 1 as part of the input rewrite as we were unaware of it's usage statistics.
However, as this was the only way to clear the inputs of individual buttons, this PR will re-add it back in.
Closes #4646
=> configure_input_player: Re-add "Clear" context menu option

src/video_core/engines/fermi_2d.cpp, src/video_core/engines/fermi_2d.h
Same behavior, less repetition. We can also ensure all members of Config are initialized.
=> fermi_2d: Make use of designated initializers

src/core/hle/service/hid/hid.cpp
There have been reports of quite heavy input lag in the past.
Compared to Citra for example, our pad_update_ns value is very high.
So let's decrease it and see if it helps with this problem.
=> Test: Decrease pad_update_ns

src/video_core/renderer_base.h, src/video_core/renderer_opengl/renderer_opengl.cpp, src/video_core/renderer_opengl/renderer_opengl.h, src/video_core/renderer_vulkan/renderer_vulkan.cpp, src/video_core/renderer_vulkan/renderer_vulkan.h, src/yuzu/bootmanager.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2.h, src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2_gl.h, src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp, src/yuzu_cmd/emu_window/emu_window_sdl2_vk.h, src/yuzu_cmd/yuzu.cpp
Emulated mailbox presentation was causing performance issues on Nvidia's OpenGL driver. This PR removes it.
I tried to fix it, but it seems like Qt is not invoking `paintEvent` as often as it should. Calling SwapBuffers from the emulation thread fixes it.
Superseedes #4688. Fixes #4687.
=> renderer_opengl: Remove emulated mailbox presentation

src/core/file_sys/ips_layer.cpp
Prevents unnecessary copying of the line being parsed.
=> ips_layer: Eliminate a redundant copy in Parse()

src/core/arm/dynarmic/arm_dynarmic_cp15.cpp, src/core/file_sys/content_archive.cpp, src/core/file_sys/vfs.cpp, src/core/file_sys/vfs_offset.cpp, src/core/file_sys/vfs_static.h, src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp, src/core/hle/service/nvdrv/nvdrv.h, src/core/hle/service/nvflinger/nvflinger.cpp, src/core/hle/service/sockets/bsd.cpp, src/core/loader/nso.cpp, src/video_core/engines/maxwell_3d.cpp, src/video_core/macro/macro.cpp, src/video_core/memory_manager.cpp, src/video_core/renderer_opengl/gl_shader_decompiler.cpp, src/video_core/shader/ast.h, src/video_core/shader/track.cpp, src/video_core/texture_cache/surface_base.cpp
Allows some implementations to avoid completely zeroing out the internal buffer of the optional, and instead only set the validity byte within the structure.
This also makes it consistent how we return empty optionals.
=> General: Make use of std::nullopt where applicable

src/video_core/shader/control_flow.cpp
Avoids unnecessary atomic reference count increments and decrements. Also while we're at it, we can emplace some data structures instead of creating them and then moving them into place.
=> control_flow: Make use of std::move in InsertBranch()

src/yuzu/install_dialog.h
This function doesn't have an implementation, so it can be removed to prevent others from unintentionally using it.
=> install_dialog: Remove unused function prototype

src/core/memory.cpp
memory doesn't exist as a parameter any more.
=> memory: Resolve a -Wdocumentation warning

src/core/hle/service/acc/acc.cpp, src/core/hle/service/acc/acc.h, src/core/hle/service/acc/acc_u0.cpp
This is used in multiple games such as:
- Clubhouse Games: 51 Worldwide Classics
- Grandia HD Collection
- XCOM 2 Collection
- Baldur's Gate 1/2
- Dr Kawashima's Brain Training
- Super Mario 3D All-Stars
=> acc: Partially implement LoadOpenContext

src/video_core/shader/decode/arithmetic_integer_immediate.cpp
Same behavior, minus any redundant atomic reference count increments and decrements.
=> arithmetic_integer_immediate: Make use of std::move where applicable

src/core/hle/service/service.cpp
Turns out this function is actually used, but within a trace log.
=> service: Restore "unused" function

src/audio_core/audio_renderer.cpp, src/audio_core/audio_renderer.h, src/audio_core/command_generator.h, src/audio_core/common.h, src/audio_core/stream.cpp
Same behavior, but removes header dependencies where they don't need to be.
=> audio_core: Remove unnecessary inclusions

src/video_core/shader/registry.cpp, src/video_core/shader/registry.h
Same behavior, less repetition.
=> shader/registry: Make use of designated initializers where applicable 

src/video_core/renderer_vulkan/vk_stream_buffer.cpp
The previous fix (#4283) only partially solved the issue, as only certain GPUs that needed 9 or less MiB subtracted would work (i.e. GTX 980 Ti, GT 730). This takes from DXVK's example to divide `heap_size` by 2 to determine `allocable_size`. Additionally tested on my Quadro K4200, which previously required setting it to 12 to boot. Requires more testing from different NVIDIA video cards.
=> vk_stream_buffer: Fix initializing Vulkan with NVIDIA on Linux

src/audio_core/CMakeLists.txt, src/audio_core/command_generator.cpp, src/audio_core/effect_context.cpp, src/audio_core/effect_context.h, src/audio_core/info_updater.cpp, src/audio_core/mix_context.cpp, src/audio_core/splitter_context.cpp, src/audio_core/voice_context.cpp
While were at it, we can also enable sign conversion warnings and other common warnings as errors to prevent these from creeping back into the codebase.
=> audio_core: Resolve sign conversion warnings 

src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp, src/core/hle/service/nvdrv/devices/nvhost_nvdec.h, src/core/hle/service/nvdrv/devices/nvhost_vic.cpp, src/core/hle/service/nvdrv/devices/nvhost_vic.h
Allows games to continue past a NVDEC movie by decoding to black and returning success for the necessary Ioctls. This does not skip a movie, so the game will appear to softlock and display only black while the movie is playing, but should continue afterwards.
=> nvdrv: Stub nvdec/vic ioctls to bypass nvdec movies

src/audio_core/cubeb_sink.cpp
Conversions from void* to the proper data type are well-defined and supported by static_cast. We don't need to use reinterpret_cast here.
=> cubeb_sink: Use static_cast instead of reinterpret_cast in DataCallback()

src/audio_core/codec.cpp, src/audio_core/codec.h, src/audio_core/command_generator.cpp
Allows compilers to elide needing to push these values on the stack every time the function is called.
=> codec: Make lookup table static constexpr

src/core/hle/service/hid/controllers/controller_base.h, src/core/hle/service/hid/controllers/npad.cpp, src/core/hle/service/hid/controllers/npad.h, src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h
Separates motion state updates from pad state updates to have correct timing for motion Input. 
This fixes motion in Mario Tennis Aces.
=> HID: Use different timing for motion

src/video_core/renderer_vulkan/vk_device.cpp
Latest AMD 20.9.2 driver fixed this, there's no reason to keep it blocked, as the previous stable signed driver release doesn't include the extension.
=> Remove ext_extended_dynamic_state blacklist

src/common/wall_clock.cpp, src/common/wall_clock.h, src/common/x64/native_clock.h
From -fsanitize=address, this code wasn't calling the proper destructor.
Adding virtual destructors for each inherited class and the base class
fixes this bug.
While we are at it, mark the classes as final.
=> common/wall_clock: Add virtual destructors

src/yuzu/game_list.cpp, src/yuzu/game_list_p.h
This fixes a memory leak as KeyReleaseEater's destructor was never
called.
=> qt/game_list: Give GameListSearchField::KeyReleaseEater a parent

src/core/core.h, src/core/frontend/applets/controller.cpp, src/core/frontend/applets/controller.h, src/core/hle/service/am/applets/applets.cpp
While we're at it, we can mark the global system instance function as deprecated.
=> frontend/controller: Eliminate dependency on the global system instance

src/core/frontend/input.h, src/core/hle/service/hid/controllers/npad.cpp, src/core/hle/service/hid/controllers/npad.h, src/core/hle/service/hid/hid.cpp, src/input_common/sdl/sdl_impl.cpp
This is an approach to implement a basic controller rumble. It enables vibrations on Pro Controllers that can use sdl_haptics. 
The first button of player settings is used as a reference to know which controller corresponds to which player.
From testing and debugging I found that controller_ids should be splitted into 4 bytes. The second rightmost byte always contains the player number.
Most of the code added should be changed with a better method. I'm looking to fix it until everyone it's happy with the code.
Closes #3894
=> input_common: First implementation of controller rumble

src/core/hle/service/hid/controllers/npad.cpp
This prevents using buttons that aren't supposed to exist in the controller.
Example:
You map all buttons xbox controller as a pro controller then change the controller type to left joycon. 
On SSBU you can still use A,X,Y,Z and right stick of the xbox controller.
=> HID: Only use inputs corresponding to controller type

src/input_common/udp/client.cpp
Currently the Steam Controller can't be configured for motion as the "shake" requirements exceed the possible values for the said controller.
The maximum values that the SC produces are: `2.f` for accel and `~5.5f` for gyro. The old ranges will never be exceeded and the controller won't be usable :disappointed:. Therefore I propose to reduce the values a little (technically the `>=` and `<=` changes are enough for accel, but for me it this way seems to be a little bit nicer).
=> Reduce the "shake" requirements when configuring UDP.

src/core/hle/service/caps/caps_c.cpp, src/core/hle/service/caps/caps_c.h, src/core/hle/service/caps/caps_su.cpp, src/core/hle/service/caps/caps_u.cpp, src/core/hle/service/caps/caps_u.h
caps_su/u's SetShimLibraryVersion - Used in Super Smash Bros. Ultimate
caps_c's SetShimLibraryVersion - Used by caps_su's SetShimLibraryVersion (according to switchbrew)
=> capsrv: Stub 3 variants of SetShimLibraryVersion

src/core/file_sys/submission_package.cpp
Fixes #4693
The previous PR #4675 had a flaw which did not account for updates integrated into cartridge images (XCIs). This PR aims to solve this by adding explicit checks for multi-content / multi-program data.
=> submission_package: Fix updates integrated into cartridge images.

src/core/hle/service/hid/controllers/npad.cpp, src/core/hle/service/hid/controllers/npad.h, src/core/hle/service/hid/hid.cpp, src/core/hle/service/hid/hid.h
- Used in 1-2 Switch. Given that we do not emulate the functionality of the home button yet, we can stub this for now.
=> hid: Stub HomeButtonInputProtection service commands

src/input_common/CMakeLists.txt, src/input_common/main.cpp, src/input_common/motion_from_button.cpp, src/input_common/motion_from_button.h, src/input_common/motion_input.cpp, src/input_common/motion_input.h, src/input_common/sdl/sdl_impl.cpp, src/input_common/sdl/sdl_impl.h, src/input_common/udp/client.cpp
This allows to assign other types of inputs as a random motion input. This effectively triggers shake actions in multiple games like SMO.
=> InputCommon: Add random motion input for buttons

src/input_common/motion_input.cpp, src/input_common/motion_input.h
This would allow to have fast motion with devices that only have accelerometer and make them be able to trigger shake events. Gyro is needed for true motion tracking having only accelerometer will not detect movements on the perpendicular plane to the gravity.
Also slowly auto calibrate for drift if the device is still. Improving accuracy on the long run.
As an extra, estimate the correct orientation of the controller if an orientation reset occurs. This will remove slow drifts when a orientation reset happens.
=> InputCommon: Add compatibility with only accelerometer and auto calibrate for drift

src/video_core/CMakeLists.txt, src/video_core/engines/shader_header.h
This avoids calling `memcpy` and other type punning functions on non-trivial types.
=> video_core: Enforce -Wclass-memaccess

src/audio_core/CMakeLists.txt, src/audio_core/algorithm/filter.cpp, src/audio_core/algorithm/interpolate.cpp, src/audio_core/command_generator.cpp, src/audio_core/cubeb_sink.cpp, src/audio_core/voice_context.cpp
Normalizes the warnings shared between audio_core and core.
=> audio_core/CMakeLists: Make warnings consistent with core

src/core/hle/service/acc/acc.cpp
This is used by Super Mario 3D All-Stars, and should be safe to stub for now.
=> service: acc: Stub IManagerForApplication::StoreOpenContext.

src/input_common/udp/client.cpp, src/input_common/udp/client.h
Avoids redundant copies. While we're in the same area, we can make use of designated initializers to make the callback list nicer to read.
=> udp/client: Take std::function by const reference with TestCommunication()

src/core/hle/service/bcat/backend/boxcat.cpp
- Fixes a crash when BCAT service is offline.
=> service: bcat: Check client connection before interacting with socket.

src/video_core/renderer_vulkan/fixed_pipeline_state.cpp, src/video_core/renderer_vulkan/fixed_pipeline_state.h, src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp, src/video_core/renderer_vulkan/vk_pipeline_cache.cpp, src/video_core/renderer_vulkan/vk_rasterizer.cpp, src/video_core/renderer_vulkan/vk_rasterizer.h
Vulkan has requirements for primitive topologies that don't play nicely
with yuzu's. Since it's only 4 bits, we can move it to fixed state
without changing the size of the pipeline key.
- Fixes a regression on recent Nvidia drivers on Fire Emblem: Three Houses.
=> vk_graphics_pipeline: Manage primitive topology as fixed state

src/core/hle/service/mii/manager.cpp
Previously, the lower bound wasn't being used and zero was being used as the lower bound every time this function was called.
This affects the outcome of some of the randomized entries a little bit, for example, the lower-bound for beard and mustache flags was supposed to be 1, not 0.
Aside from these cases, the bug didn't affect anything else.
This was found while addressing cases in #4796
=> mii/manager: Make use of unused lower bound in GetRandomValue()

src/core/CMakeLists.txt
Same behavior, minus a script variable.
=> core: Add boxcat sources with target_sources

src/video_core/renderer_vulkan/renderer_vulkan.cpp, src/video_core/renderer_vulkan/renderer_vulkan.h, src/video_core/renderer_vulkan/vk_device.cpp, src/video_core/renderer_vulkan/vk_device.h, src/video_core/renderer_vulkan/vk_shader_decompiler.cpp, src/video_core/renderer_vulkan/wrapper.cpp, src/video_core/renderer_vulkan/wrapper.h
Enable the required capabilities to use Vulkan 1.0 without validation errors and disable those that are not compatible with it.
=> renderer_vulkan: Create and properly use Vulkan 1.0 instances when 1.1 is not available

src/video_core/renderer_opengl/gl_arb_decompiler.cpp, src/video_core/renderer_opengl/gl_rasterizer.cpp, src/video_core/renderer_opengl/gl_rasterizer.h
This emulates the behavior we get on GLSL with regular SSBOs with a
pointer + length pair. It aims to be consistent with the crashes we
might get.
Out of bounds stores are ignored. Atomics are ignored and return zero.
Reads return zero.
=> gl_arb_decompiler: Implement robust buffer operations

src/video_core/CMakeLists.txt
These compiler flags aren't shared with Clang, so specifying these flags unconditionally when building with it can lead to a bit of warning spam. So we can wrap these to only activate when compiling with GCC.
While we're in the area, we can also enable -Wunused-but-set-parameter given this is almost always a bug.
=> video_core: Conditially activate relevant compiler warnings

src/core/core.cpp, src/core/core.h, src/core/hle/service/time/time.cpp, src/core/hle/service/time/time.h, src/core/hle/service/time/time_manager.cpp, src/core/hle/service/time/time_manager.h, src/core/hle/service/time/time_zone_content_manager.cpp, src/core/hle/service/time/time_zone_content_manager.h, src/yuzu/configuration/configure_system.cpp
This refreshes the time service with changes to the RTC set in the UI. This can be used to advance time, e.g. for Pokemon Sword/Shield pokejobs.
=> service: time: Update current time with changes to RTC setting.

src/video_core/host_shaders/CMakeLists.txt, src/video_core/host_shaders/StringShaderHeader.cmake
When HEADER_GENERATOR was included in the DEPENDS section of custom
commands, msbuild assumed this was always modified. Changing this file
is not common so we can remove it from there.
=> video_core: Fix instances where msbuild always regenerated host shaders

src/yuzu/applets/profile_select.cpp, src/yuzu/applets/profile_select.h, src/yuzu/main.cpp
~Based on #4297.~
Reverts #4297 and moves the profile selection skip to QtProfileSelectionDialog. Now it skips in both 
`GMainWindow::ProfileSelectorSelectProfile` and `GMainWindow::OnGameListOpenFolder` when there's only one profile.
=> main/profile_select: Don't ask for profile when there's only one.
