yuzu-emu/yuzu

src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/npad.h
src/core/hle/service/hid/hid.cpp

- Used in Clubhouse Games: 51 Worldwide Classics

hid: Implement Get/SetNpadHandheldActivationMode

---

src/yuzu/game_list.cpp
src/yuzu/game_list.h
src/yuzu/main.cpp

Several functions can have their arguments taken by const reference to avoid copies. While we're in the area we can also touch up the casing of several functions.

game_list: Eliminate redundant argument copies 

---

src/input_common/gcadapter/gc_adapter.cpp
src/input_common/gcadapter/gc_adapter.h
src/input_common/main.cpp

Adds the GameCube controller to the device list and auto maps the corresponding keys

Add automap feature for GC adapter

---

src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h

Makes boom ball:boost edition boot. It's 100% playable.

HID: Add Stub for EnableSixAxisSensorFusion

---

src/video_core/renderer_vulkan/wrapper.cpp

The old code had a sort function that was invalid and it didn't work as
expected when the base vector had a different order (e.g. renderdoc was
attached).
This sorts devices as expected and fixes a debug assert on MSVC.

renderer_vulkan/wrapper: Fix physical device sorting

---

src/video_core/CMakeLists.txt
src/video_core/engines/maxwell_dma.cpp
src/video_core/renderer_opengl/gl_device.cpp

This helps to catch bugs early.

video_core: Enforce -Wunused-variable and -Wunused-but-set-variable

---

src/video_core/shader/decode/texture.cpp

TMML takes an array argument that has no known meaning, this one appears
as the first component in gpr8 followed by s, t and r. Skip this
component when arrays are being used. Also implement CUBE texture types.
- Used by Pikmin 3: Deluxe Demo.

shader/texture: Implement CUBE texture type for TMML and fix arrays

---

src/video_core/renderer_vulkan/vk_device.cpp

RDNA devices seem to crash when using VK_EXT_extended_dynamic_state in
the latest 20.9.2 proprietary Windows drivers. As a workaround, for now
we block device names corresponding to current RDNA released products.

vk_device: Block VK_EXT_extended_dynamic_state for RDNA devices

---

src/core/hle/service/nvflinger/buffer_queue.cpp
src/core/hle/service/nvflinger/buffer_queue.h
src/core/hle/service/vi/vi.cpp

- This is used by Super Mario 3D All-Stars.

hle: service: vi: Implement BufferQueue::CancelBuffer.

---

src/common/math_util.h
src/common/vector_math.h
src/input_common/CMakeLists.txt
src/input_common/analog_from_button.cpp
src/input_common/gcadapter/gc_adapter.cpp
src/input_common/gcadapter/gc_adapter.h
src/input_common/gcadapter/gc_poller.cpp
src/input_common/keyboard.cpp
src/input_common/main.cpp
src/input_common/motion_emu.cpp
src/input_common/motion_from_button.cpp
src/input_common/motion_input.cpp
src/input_common/motion_input.h
src/input_common/sdl/sdl_impl.cpp
src/input_common/touch_from_button.cpp
src/input_common/udp/client.cpp
src/input_common/udp/client.h
src/input_common/udp/udp.cpp
src/yuzu/configuration/configure_motion_touch.cpp

Makes the input_common code warning errors more consistent with the rest of the codebase.

input_common/CMakeLists: Make some warnings errors

---

src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h

- This is used by Super Mario 3D All-Stars.

hle: service: nvdrv: Implement nvhost_as_gpu::FreeSpace.

---

src/core/hle/service/filesystem/filesystem.cpp

Fixes #4708 
Add a check if dir is nullptr (does not exist)
Fixes save game creation in Hades

filesystem: Fix CreateDirectory and DeleteFile

---

src/core/hle/kernel/kernel.cpp

Locks on GetCurrentHostThreadID were causing performance issues
according to Visual Studio's profiler. It was consuming twice the time
as arm_interface.Run(). The cost was not in the function itself but in
the locking it required.
Reimplement these functions using atomics and flat storage instead of
an unordered_map. This is a side effect to avoid locking and using linked
lists for reads.
Replace unordered_map with a linear search.

kernel: Implement host thread register methods without locking

---

src/input_common/sdl/sdl_impl.cpp

Previously, disconnecting a controller still leaves a null SDLJoystick entry within the vector of SDLJoysticks mapped by GUID.
When a DirectInput device of the same GUID is reconnected, it adds that device to a new port causing non-detectable input.
Furthermore, opening the "Configure" menu would cause yuzu to crash since it first tries to resolve the name of a null SDLJoystick entry that was not removed.
Resolve this by properly erasing the SDLJoystick entry from the vector, this resolves #4268.

sdl_impl: Erase the SDLJoystick entry after removing a controller

---

src/input_common/settings.h
src/yuzu/configuration/configure_input_player.cpp
src/yuzu/configuration/configure_input_player.h

Fix them for real this time, now they finally work.
This is part of Mjolnir Part 3, which will be PR'd once it is ready

configure_input_player: Fix modifier buttons

---

src/core/hle/service/nifm/nifm.cpp

Fixes crash for Catherine Full Body

nifm: GetAppletInfo stub

---

src/input_common/sdl/sdl_impl.cpp

It turns out that after a controller is disconnected, there is a chance that events from the previous controller are sent/processed after it has been disconnected.
This causes the previously disconnected controller to reappear as connected due to GetSDLJoystickBySDLID() emplacing this controller back to the vector/map.
Fix this by only returning an SDLJoystick if and only if it exists in the map.
This also reverts the changes from #4627 as they are unnecessary after this change.
Fixes #4815 and properly fixes #4268

sdl_impl: Fix controller reconnection issues

---

src/core/hle/service/bcat/backend/backend.cpp
src/yuzu/applets/controller.cpp

general: Use template deduction guides for lock_guard

---

src/core/hle/service/time/time_zone_content_manager.h

Missed the code review feedback from #4792 
@lioncash as FYI

hle: services: TimeZoneContentManager: This can be made explicit.

---

src/tests/common/fibers.cpp

This should fix CI randomly failing on Linux.
Previous to this commit, the tests were using operator[] from
unordered_map to query elements but this silently inserts empty elements
when they don't exist. If all threads were executed without concurrency,
this wouldn't be an issue, but the same unordered_map could be written
from two threads at the same time. This is a data race and makes some
previously inserted elements invisible for a short period of time,
causing them to insert and return an empty element. This default
constructed element (a zero) was used to index an array of fibers that
asserted when one of them was nullptr, shutting the test session off.
To address this issue, lock on thread id reads and writes. This could be
a shared mutex to allow concurrent reads, but the …

tests: Fix data race in fibers test

---

src/core/hle/service/am/am.cpp
src/core/hle/service/hid/hid.cpp
src/core/hle/service/mii/mii.cpp
src/core/hle/service/set/set.cpp
src/core/hle/service/set/set_sys.cpp

Updates function tables according to info on SwitchBrew.

service: Update function tables

---

externals/httplib/README.md
externals/httplib/httplib.h
src/web_service/web_backend.cpp

* The web_service HTTP request is now fixed on Windows (R) platform.
* The issue is due to a complicated race-condition in `httplib`, a detailed explanation is available at https://github.com/yhirose/cpp-httplib/pull/701.
* A pending Pull Request on `httplib` has been applied to remedy the said race-condition.
* The socket availability check is removed due to a behavioral choice of `httplib` that a socket will not be created before any actual request is sent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yuzu-emu/yuzu/4857)

web_service: follow-up fix to #4842

---

src/common/fiber.h
src/common/spin_lock.h
src/video_core/dma_pusher.h
src/video_core/gpu.h

Allows building on clang to work again.
Fixes #4890

General: Fix clang build

---

src/common/logging/backend.cpp
src/common/logging/log.h
src/core/CMakeLists.txt
src/core/hle/service/olsc/olsc.cpp
src/core/hle/service/olsc/olsc.h
src/core/hle/service/service.cpp

- Used by Animal Cross: New Horizons v1.6.0 update, minimal stub gets this update working.

hle: service: Stub OLSC Initialize and SetSaveDataBackupSettingEnabled functions.

---

src/core/core.cpp
src/core/core.h
src/yuzu_cmd/yuzu.cpp
src/yuzu_tester/yuzu.cpp

Given this is a central class, we should flag cases where the return value of some functions not being used is likely a bug.

core: Make use of [[nodiscard]] with the System class

---

src/core/cpu_manager.cpp

- This crash would happen when shutting down yuzu while shaders were compiling.

core: cpu_manager: Fix shutdown crash when closing before emulation starts.

---

src/core/core.cpp

Eliminates some minor string churn where applicable. Also eliminates an unnecessary vector copy when calling `MakeConcatenatedFile`

core: Reduce string copies in GetGameFileFromPath()

---

src/core/hle/service/hid/hid.cpp

hid: Check if applet_resource exists in InitializeVibrationDevice

---

src/input_common/mouse/mouse_input.cpp

InputCommon: Fix implicit conversion in mouse input

---

src/core/settings.h
src/input_common/main.cpp
src/input_common/udp/client.cpp
src/input_common/udp/client.h
src/input_common/udp/udp.cpp
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_motion_touch.cpp
src/yuzu/configuration/configure_motion_touch.h
src/yuzu/configuration/configure_motion_touch.ui
src/yuzu_cmd/config.cpp

Modifies the ui and adds the necessary code to permit multiple udp clients to connect up to 8 different udp servers
Thanks to @Its-Rei for modifying the UI

InputCommon: Add multiple udp server support

---

src/input_common/mouse/mouse_input.cpp
src/input_common/mouse/mouse_input.h
src/input_common/mouse/mouse_poller.cpp

Resolves a -Wdocumentation warning, removes some casts, and removes some unused includes among other things.

mouse_input/mouse_poller: Minor cleanup

---

src/core/file_sys/vfs_real.cpp

Fixes a regression introduced by #5173 
Requires #5174

vfs_real: Fix CreateFile for files without a file extension

---

src/common/file_util.cpp

Addresses the review comments of #5174

common/file_util: Address review comments of #5174

---

src/core/CMakeLists.txt
src/core/file_sys/common_funcs.h
src/core/file_sys/patch_manager.cpp
src/core/file_sys/romfs_factory.cpp
src/core/file_sys/romfs_factory.h
src/core/hle/service/aoc/aoc_u.cpp
src/core/hle/service/filesystem/filesystem.cpp
src/core/hle/service/filesystem/filesystem.h
src/core/hle/service/filesystem/fsp_srv.cpp
src/core/hle/service/filesystem/fsp_srv.h
src/yuzu/main.cpp

- Used by RollerCoaster Tycoon 3: Complete Edition
- Used by Immortals Fenyx Rising
Fixes #4763 
Supersedes #4764

fsp_srv: Implement OpenDataStorageWithProgramIndex

---

src/input_common/gcadapter/gc_poller.cpp
src/input_common/mouse/mouse_poller.cpp
src/input_common/sdl/sdl_impl.cpp
src/yuzu/configuration/configure_input_player.cpp

Now you can invert the direction of the analog axis with right click.

InputCommon: Allow to invert analog axis with right click

---

src/video_core/texture_cache/texture_cache.h

PAGE_SHIFT is a #define in system headers that leaks into user code on some systems

texture_cache: Replace PAGE_SHIFT with PAGE_BITS

---

src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
src/core/hle/service/nvdrv/devices/nvhost_nvdec.h
src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
src/core/hle/service/nvdrv/devices/nvhost_vic.h
src/core/hle/service/nvdrv/nvdrv.cpp
src/video_core/cdma_pusher.cpp
src/video_core/cdma_pusher.h
src/video_core/command_classes/host1x.cpp
src/video_core/command_classes/host1x.h
src/video_core/command_classes/sync_manager.cpp

This PR includes the incorporation of the syncpoint manager to more accurately emulate nvdec. 
However, this does not implement proper async gpu support, that still remains as a TODO.

nvdec: Incorporate syncpoint manager

---

src/core/hle/service/apm/interface.cpp
src/core/hle/service/apm/interface.h

Stub IsCpuOverclockEnabled. Used by MONSTER HUNTER RISE DEMO

apm: Stub IsCpuOverclockEnabled

---

src/video_core/vulkan_common/vulkan_device.cpp
src/video_core/vulkan_common/vulkan_device.h

Fix Vulkan initialization on ANV.

vulkan_device: Enable shaderStorageImageMultisample conditionally

---

src/video_core/vulkan_common/vulkan_debug_callback.h

Prevents inclusion issues from occurring.

vulkan_debug_callback: Add missing header guard

---

src/core/frontend/emu_window.cpp
src/core/frontend/emu_window.h
src/core/frontend/input.h
src/core/hle/service/hid/controllers/touchscreen.cpp
src/core/hle/service/hid/controllers/touchscreen.h
src/input_common/touch_from_button.cpp
src/input_common/udp/client.cpp
src/input_common/udp/client.h
src/input_common/udp/protocol.h
src/input_common/udp/udp.cpp
src/yuzu/bootmanager.cpp
src/yuzu/bootmanager.h
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_motion_touch.cpp
src/yuzu/configuration/configure_motion_touch.ui
src/yuzu/configuration/configure_touchscreen_advanced.cpp
src/yuzu/configuration/configure_touchscreen_advanced.ui
src/yuzu_cmd/config.cpp
src/yuzu_cmd/emu_window/emu_window_sdl2.cpp

Adds multi touch support to yuzu. Making Voez playable.
Todo:

HID: Add multitouch support

---

src/core/hle/service/acc/acc.cpp
src/core/hle/service/acc/acc.h
src/core/hle/service/acc/acc_su.cpp
src/core/hle/service/acc/acc_u0.cpp
src/core/hle/service/acc/acc_u1.cpp

Fixes ACA NEOGEO METAL SLUG hanging on boot.

acc: Stub StoreSaveDataThumbnail

---

src/core/hle/service/lbl/lbl.cpp

Pretty basic service, only thing left to do is handle setting applying once set:sys is implemented

lbl: Implement most of lbl

---

src/video_core/shader/shader_ir.cpp

Thanks @adityaruplaha for catching this.

Shader_ir: Fix comment typo

---

src/core/hle/service/ptm/psm.cpp

psm: IPsmSession

---

src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/npad.h
src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h

Stubs SetSixaxisSensorFusionParameters, GetSixaxisSensorFusionParameters and ResetSixaxisSensorFusionParameters. Makes The World Ends with You boot.

HID: Stub Set/Get/Reset SixaxisSensorFusionParameters

---

src/video_core/renderer_vulkan/vk_scheduler.h

We were accidentaly creating an object in an unaligned memory address.
Fix this by manually aligning the offset.

vk_scheduler: Fix unaligned placement new expressions

---

src/core/hle/service/prepo/prepo.cpp

Stub GetSystemSessionId. Allows Jump the rope to get in game.

prepo: Stub GetSystemSessionId

---

src/core/hle/service/sockets/bsd.cpp
src/core/hle/service/sockets/bsd.h

bsd: Stub EventFd

---

src/core/hle/service/am/am.cpp
src/core/hle/service/am/am.h

am: Stub TryPopFromFriendInvitationStorageChannel

---

src/core/hle/service/sockets/bsd.cpp

bsd: Fix EventFd stub

---

src/core/hle/service/prepo/prepo.cpp

RequestImmediateTransmission
- Used by Animal Crossing: New Horizons

prepo: Stub RequestImmediateTransmission and GetTransmissionStatus

---

src/core/hle/service/am/am.cpp
src/core/hle/service/am/am.h

am/IApplicationFunctions: Stub IsGamePlayRecordingSupported

---

src/core/settings.cpp

These are useful for troubleshooting/support purposes

settings: Log the cache, config and mod load directories

---

src/core/hle/service/am/am.cpp
src/core/hle/service/am/am.h

- Used in the Chinese version of Mario Kart 8 Deluxe (马力欧卡丁车8 豪华版)

IApplicationFunctions: Implement GetHealthWarningDisappearedSystemEvent

---

src/core/hle/kernel/k_address_arbiter.cpp

Removes some dead code and simplifies other code. While we're in the area, we can introduce a few specific logging calls.

k_address_arbiter: Minor cleanup

---

src/core/hle/kernel/svc.cpp

Allows SVC calls to have much more informative information during error cases. This also doesn't hide control flow returns from the reader.

svc: Provide more detailed error logs for svc functions

---

src/core/hle/service/olsc/olsc.cpp

Stub GetSaveDataBackupSetting used in Animal Crossing 1.7.0

olsc: Stub GetSaveDataBackupSetting

---

src/yuzu/configuration/configure_input_player_widget.cpp
src/yuzu/configuration/configure_input_player_widget.h

Lifts some portions of expressions out to locals so it's a little bit nicer to parse. Also prevents some expensive copies from occurring.

configure_input_player_widget: Minor cleanup

---

src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/maxwell_to_gl.h

Removes unused declarations in maxwell_to_gl.h

maxwell_to_gl: Remove unused code

---

src/video_core/renderer_vulkan/vk_resource_pool.cpp
src/video_core/renderer_vulkan/vk_resource_pool.h

Other minor style improvements. Rename free_iterator to hint_iterator, to describe better what it does.

vk_resource_pool: Load GPU tick once and compare with it

---

src/audio_core/CMakeLists.txt
src/audio_core/command_generator.cpp
src/audio_core/command_generator.h
src/audio_core/common.h
src/audio_core/delay_line.cpp
src/audio_core/delay_line.h
src/audio_core/effect_context.cpp
src/audio_core/effect_context.h

Most notable fix is the voices in Fire Emblem Three Houses

audren: Implement I3dl2Reverb

---

src/core/frontend/applets/controller.h
src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/npad.h
src/input_common/settings.h
src/yuzu/applets/controller.cpp
src/yuzu/configuration/configure_input_player.cpp
src/yuzu/configuration/configure_input_player.h
src/yuzu/configuration/configure_input_player_widget.cpp

Implements the necessary changes for the GC controller to be detected in-game as a GC controller. Analog triggers are going to be implemented in a future PR

HID: Implement GC controller in game

---

src/input_common/mouse/mouse_input.cpp

Improves mouse panning in different aspects. 
- Smoother movement.
- The pointer reset less frequently to center with slow movements.
- The mouse has a dead zone boost. This increase the responsiveness.
- The mouse slowly drifts to center. Less hard stops. 
- Added a max range limit. This allows faster changes in direction.

Improve mouse panning

---

src/video_core/renderer_vulkan/vk_buffer_cache.cpp
src/video_core/renderer_vulkan/vk_buffer_cache.h
src/video_core/renderer_vulkan/vk_update_descriptor.cpp
src/video_core/renderer_vulkan/vk_update_descriptor.h

Allow compilers with our current settings to inline hot code.

vk_update_descriptor: Inline and improve code for binding buffers

---

src/core/hle/service/hid/controllers/gesture.cpp
src/core/hle/service/hid/controllers/gesture.h

Implements touch, pan, pinch and rotation gestures. No known game uses this feature. I used a NRO to verify that it was working like real HW. This was the result in an attempt to fix touch in voez.

HID: Implement gestures

---

src/core/hle/service/vi/vi.cpp

Used by games invoking the inline software keyboard such as GNOSIA

IApplicationDisplayService: Stub GetIndirectLayerImageMap

---

src/video_core/renderer_opengl/gl_device.cpp

Currently, the Windows version of the Intel OpenGL driver and the AMD proprietary OpenGL driver do not properly support (or in fact degrade in performance) when asynchronous shader compilation is enabled. This blocks specifically those drivers from using this feature. This affects AMDGPU-PRO on Linux, and AMD's and Intel's OpenGL drivers on Windows.
This will log when it is enabled in settings but not compatible with the driver, much the same way assembly shaders are disabled at a guest boot time.
The only case that hasn't been tested at the time of writing is Intel on Linux.

gl_device: Block async shaders on AMD and Intel

---

src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_64.cpp

I feel this could be a configuration option given the memory usage requirements.

arm_dynarmic: Increase size of code cache

---

src/video_core/command_classes/codecs/vp9.cpp

Avoid sending null pointer to memcpy as reported by Undefined Behaviour Sanitizer.

vp9: Avoid memcpy with null pointers

---

src/core/hle/service/audio/hwopus.cpp

Update hwopus function table to 12,x

service: audio: Update service function tables

---

src/core/hle/service/acc/acc.cpp
src/core/hle/service/acc/acc_su.cpp
src/core/hle/service/acc/acc_u1.cpp

Updates various service functions to 12.x

service: acc: Update service function tables

---

src/core/hle/service/filesystem/fsp_srv.cpp
src/core/hle/service/filesystem/fsp_srv.h

Updates various service functions to 12.x

service: fs: Update service function tables

---

src/core/hle/kernel/kernel.cpp

12.x increased the number of available sessions and event resource counts

kernel: Increase event and session counts

---

src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/npad.h
src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h

- Used by eBASEBALLパワフルプロ野球2020

service: hid: Stub SetAnalogStickUseCenterClamp

---

src/core/hle/service/friend/friend.cpp

Stubs GetPlayHistoryRegistrationKey used by BLAZBLUE CROSS TAG BATTLE

Friend: Stub GetPlayHistoryRegistrationKey

---

src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/process.cpp

This PR addresses the inaccurate behavior of kernel processes creating their own resource limit, rather than utilizing the kernel's system-wide resource limit instance.
With this change, `Process::GetTotalPhysicalMemoryAvailable` can accurately return the expected resource limit values, without the use of a local resource limit instance.

kernel/process: Replace process resource limit instance with the kernel's resource limit

---

src/yuzu/applets/controller.cpp
src/yuzu/applets/controller.h

I forgot to hook this up during the development of the controller applet, this PR amends that.
Fixes #6194

applets/controller: Hook up the "Motion" button functionality

---

src/core/hle/service/lm/lm.cpp

Resolves a trivial warning with clang.
While we're in the area, we can improve the Log() member function a little bit.

lm: Resolve -Wextra-semi warning

---

src/core/hle/service/am/am.cpp
src/core/hle/service/am/am.h

- Used by Pixel Game Maker Series Werewolf Princess Kaguya

ICommonStateGetter: Stub SetRequestExitToLibraryAppletAtExecuteNextProgramEnabled

---

src/video_core/renderer_vulkan/vk_texture_cache.cpp

Swizzles the Red and Blue channels of the A1B5G5R5_UNORM texture format, which was being incorrectly rendered.
Before:
After:

vk_texture_cache: Swap R and B channels of color flipped format

---

src/core/hle/service/hid/controllers/gesture.cpp
src/core/hle/service/hid/controllers/touchscreen.cpp

Currently this setting is not used anywhere. Let's use it

hid: Disable touch if setting is not enabled

---

src/yuzu/game_list.cpp
src/yuzu/game_list_p.h

Also move that `setFilterResults` in `OnTextChanged()` after the for loop.

game_list: Update filter results when removing directories

---

src/core/file_sys/card_image.cpp
src/core/file_sys/content_archive.cpp
src/core/file_sys/fsmitm_romfsbuild.cpp
src/core/file_sys/fsmitm_romfsbuild.h
src/core/file_sys/nca_patch.cpp
src/core/file_sys/registered_cache.cpp
src/core/file_sys/registered_cache.h
src/core/file_sys/romfs_factory.cpp
src/core/file_sys/romfs_factory.h
src/core/file_sys/savedata_factory.cpp
src/core/file_sys/submission_package.cpp
src/core/file_sys/vfs_concat.cpp
src/core/file_sys/vfs_concat.h
src/core/file_sys/vfs_layered.cpp
src/core/file_sys/vfs_layered.h
src/core/file_sys/vfs_offset.cpp
src/core/file_sys/vfs_offset.h
src/core/file_sys/vfs_real.cpp
src/core/file_sys/vfs_real.h
src/core/file_sys/vfs_vector.cpp
src/core/file_sys/vfs_vector.h

Brings us closer to enabling -Wshadow as an error in core code.

file_sys: Resolve cases of variable shadowing

---

src/core/hle/service/hid/controllers/gesture.cpp
src/core/hle/service/hid/controllers/gesture.h

Touch in Pokemon Snap was broken. This PR rewrites gestures in order to make them more accurate against hardware by implementing all gesture types. Removes any input errors that it previously had.

hid: Improve hardware accuracy of gestures

---

src/core/hle/service/ssl/ssl.cpp

- Used in JUMP FORCE Deluxe Edition

ssl: Stub Import(Client/Server)Pki

---

src/CMakeLists.txt

This is similar to -Werror=return-type

CMakeLists: Enforce C4715 on MSVC

---

src/yuzu/applets/software_keyboard.cpp

Previously the text string for the inline software keyboard was being sent instead of the normal software keyboard, leading to empty text being sent all the time.
Fixes #6332

applets/swkbd: Send the correct text string on TextCheck::Confirm

---

src/yuzu/configuration/configure_cpu.ui

Set unique names for each label

settings: Suppress duplicate label name warning

---

src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_32.h
src/core/arm/dynarmic/arm_dynarmic_64.cpp
src/core/arm/dynarmic/arm_dynarmic_64.h
src/core/arm/dynarmic/arm_dynarmic_cp15.h
src/core/arm/dynarmic/arm_exclusive_monitor.h

The new version supports fastmem on a64.

externals: Update dynarmic.

---

src/core/file_sys/savedata_factory.cpp
src/core/file_sys/savedata_factory.h
src/core/hle/service/filesystem/filesystem.cpp
src/core/hle/service/filesystem/filesystem.h
src/core/hle/service/filesystem/fsp_srv.cpp
src/core/hle/service/filesystem/fsp_srv.h

fsp-srv: Implement DisableAutoSaveDataCreation

---

src/core/hle/service/filesystem/fsp_srv.cpp

This slipped through due to #6355 being merged

fsp-srv: Replace one last instance of RESULT_SUCCESS

---

src/core/hle/kernel/k_light_condition_variable.h
src/core/hle/kernel/k_light_lock.cpp
src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/k_resource_limit.cpp

Updates the implementation of KLightConditionVariable to FW 12.x

kernel: KLightConditionVariable: Update implementation to 12.x

---

src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h

hid: Stub IsFirmwareUpdateAvailableForSixAxisSensor

---

src/audio_core/stream.cpp
src/audio_core/stream.h
src/core/hle/service/audio/audout_u.cpp

[audout] Implement GetAudioOutPlayedSampleCount

---

src/audio_core/sink_context.h
src/core/hle/service/mii/manager.h
src/input_common/mouse/mouse_poller.cpp
src/input_common/touch_from_button.cpp

Add missing includes to fix any compile errors

Add missing includes

---

src/video_core/vulkan_common/vulkan_device.cpp
src/video_core/vulkan_common/vulkan_device.h

vulkan_device: Make device memory match the rest of the file

---

src/video_core/CMakeLists.txt
src/video_core/buffer_cache/buffer_cache.h
src/video_core/command_classes/codecs/codec.h
src/video_core/command_classes/vic.cpp
src/video_core/renderer_vulkan/vk_buffer_cache.cpp
src/video_core/texture_cache/texture_cache.h

Fixes a regression in the Marvel game by Koei Tecmo.

buffer_cache,texture_cache: Misc fixups from the memory reaper

---

src/yuzu/debugger/profiler.cpp

Address some simple warnings on the compiler

Resolve some compiler warnings

---

src/common/fs/file.cpp
src/common/fs/file.h
src/common/logging/backend.cpp

The changes are described in their individual commits.

common: fs: More misc. changes

---

src/core/hle/service/bcat/backend/boxcat.cpp
src/web_service/web_backend.cpp

Fixes build errors on gcc when building on debug mode.

boxcat,web_service: Silence -Wmaybe-uninitialized when including httplib.h

---

src/input_common/main.cpp

Allows to compile without errors

input_common: Fix build with SDL disabled

---

src/video_core/texture_cache/util.cpp

On the texture cache we handle multisampled images by keeping their real
size in samples (e.g. 1920x1080 with 4 samples is 3840x2160).
This works nicely with size matches and other comparisons, but the
calculation for guest sizes was not having this in mind, and the size
was being multiplied (again) by the number of samples per dimension.
For example a 3840x2160 texture cache image had its width and height
multiplied by 2, resulting in a much larger texture.
Fix this issue.
- Fixes performance regression on cooking related titles when an
unrelated bug was fixed.

texture_cache/util: Fix size calculations of multisampled images

---

src/core/core.cpp
src/core/core.h
src/core/file_sys/card_image.cpp
src/core/file_sys/card_image.h
src/core/file_sys/submission_package.cpp
src/core/file_sys/submission_package.h
src/core/loader/loader.cpp
src/core/loader/loader.h
src/core/loader/nsp.cpp
src/core/loader/nsp.h
src/core/loader/xci.cpp
src/core/loader/xci.h
src/yuzu/game_list.cpp
src/yuzu/game_list.h
src/yuzu/game_list_worker.cpp
src/yuzu/main.cpp
src/yuzu/main.h

The previous implementation can only load the default first game. This PR aims to able to load all games in the xci or nsp file.

Support load game collection

---

src/input_common/sdl/sdl_impl.cpp
src/yuzu/configuration/configure_input_player.cpp

It was requested to add toggle support for sdl controllers

input_common: Support SDL toggle buttons

---

src/video_core/renderer_vulkan/vk_texture_cache.cpp

Silences performance warnings generated from validation layers on each frame.

vk_texture_cache: Use VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL when possible

---

src/video_core/buffer_cache/buffer_cache.h
src/video_core/renderer_opengl/gl_buffer_cache.cpp

buffer_cache: Misc fixups related to buffer clears

---

README.md

As agreed with all this contributors.

Grant a partial license exception to Skyline Emulator.

---

src/shader_recompiler/backend/glasm/emit_glasm.cpp

This should be LINES_ADJACENCY

emit_glasm: Fix LINESS_ADJACENCY typo in InputPrimitive()

---

src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp

The Yuzu Vulkan renderer refused to start at some point and the logs had the following error:
```
[   4.066235] Render.Vulkan <Error> video_core/renderer_vulkan/renderer_vulkan.cpp:RendererVulkan:121: Vulkan initialization failed with error: VK_ERROR_OUT_OF_DEVICE_MEMORY
[   4.066441] HW.GPU <Error> video_core/video_core.cpp:CreateGPU:50: Failed to initialize GPU: Vulkan initialization error VK_ERROR_OUT_OF_DEVICE_MEMORY
```
I unfortunately don't know how to reproduce the problem since it was working at first, but I think Yuzu should handle those cases regardless.
The crash is caused by the fact that Yuzu tries to allocate staging buffers in host visible VRAM. On my system (which doesn't support resizable BAR) that's just 256 MB.
This PR makes Yuzu fall back to regular system memory if …

Handle allocation failure in Staging buffer

---

src/video_core/renderer_base.cpp
src/video_core/renderer_base.h
src/video_core/renderer_opengl/renderer_opengl.cpp
src/video_core/renderer_vulkan/renderer_vulkan.cpp
src/video_core/renderer_vulkan/renderer_vulkan.h
src/video_core/renderer_vulkan/vk_blit_screen.cpp
src/video_core/renderer_vulkan/vk_blit_screen.h
src/yuzu/bootmanager.cpp

Implements screenshots for the Vulkan API.
Supersedes #6718

 renderer_vulkan: Implement screenshots

---

CMakeLists.txt

* Added SDL_GameControllerSendEffect() and SDL_JoystickSendEffect() to allow sending custom trigger effects to the DualSense controller
* Added SDL_GameControllerGetSensorDataRate() to get the sensor data rate for PlayStation and Nintendo Switch controllers
* Added support for the Amazon Luna game controller
* Added rumble support for the Google Stadia controller using the HIDAPI driver
* Added SDL_GameControllerType constants for the Amazon Luna and Google Stadia controllers
* Added analog rumble for Nintendo Switch Pro controllers using the HIDAPI driver

externals: Update sdl2 to 2.0.16

---

src/video_core/textures/decoders.cpp

Applies the speed doubling in #6790 to the rest of the functions in that file.
Thanks to @ameerj for telling me that the problem is here.
ZLA plays at 60 FPS instead of 50 FPS!

decoders: Optimize memcpy for the other functions

---

src/yuzu/applets/qt_software_keyboard.cpp

Nothing interesting here, move along.

qt_software_keyboard: fix copy-paste error

---

src/core/hle/service/am/applets/applet_error.cpp

Thanks to @v1993 for pointing this out!

applet_error: Fix 64-bit error code conversion

---

src/common/logging/filter.cpp
src/common/logging/types.h
src/core/CMakeLists.txt
src/core/hle/service/ngct/ngct.cpp
src/core/hle/service/ngct/ngct.h
src/core/hle/service/service.cpp

Stub the "No Good Content for Terra" service and IService::Filter, we don't need to implement word censoring. Needed in Boyfriend Dungeon 
Closes #6925

ngct: Stub NGCT:U service

---

src/common/lru_cache.h
src/common/settings.cpp
src/common/settings.h
src/video_core/buffer_cache/buffer_base.h
src/video_core/buffer_cache/buffer_cache.h
src/video_core/texture_cache/image_base.h
src/video_core/texture_cache/texture_cache.h
src/video_core/texture_cache/texture_cache_base.h
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_graphics_advanced.cpp
src/yuzu/configuration/configure_graphics_advanced.h
src/yuzu/configuration/configure_graphics_advanced.ui
src/yuzu_cmd/config.cpp

This PR recreates the garbage collector using an LRU cache instead. It's not as aggressive as the older one but it gets the job done. It should be bugless.

Project <tentative title>: Rework Garbage Collection.

---

src/core/hle/service/nvflinger/nvflinger.cpp
src/core/hle/service/nvflinger/nvflinger.h
src/core/hle/service/vi/display/vi_display.cpp
src/core/hle/service/vi/display/vi_display.h

core: hle: service: nvflinger/vi: Improve management of KEvent.

---

src/core/cpu_manager.cpp
src/core/cpu_manager.h

Breaking up https://github.com/yuzu-emu/yuzu/pull/6964

core: cpu_manager: Use jthread.

---

src/yuzu/configuration/configure_graphics.ui
src/yuzu/configuration/configure_graphics_advanced.ui

Renames "Use disk shader cache" to "Use disk pipeline cache" and renames "hack" to "Hack" for a cleaner, and less OCD-triggering experience 😆

Second part of Golden's PR #6976

---

src/core/hle/service/nvflinger/buffer_queue.cpp
src/core/hle/service/nvflinger/buffer_queue.h
src/core/hle/service/nvflinger/nvflinger.cpp

core: hle: service: buffer_queue: Improve management of KEvent.

---

src/core/CMakeLists.txt
src/core/hle/service/acc/acc.cpp
src/core/hle/service/acc/async_context.cpp
src/core/hle/service/acc/async_context.h

Closes #2547, #6946, #4239 
Death Coming now boots:

account: EnsureTokenIdCacheAsync

---

src/shader_recompiler/backend/glsl/emit_glsl_warp.cpp
src/shader_recompiler/backend/spirv/emit_spirv_warp.cpp

AMD devices dispatch 64-thread warps, making emulating the Tegra warp instructions a bit of a challenge due the guest device using a 32-thread warp size. This requires us to divide a 64-thread warp to behave as two 32-thread warps, and forbids us from using the standard warp intrinsics in the high level API's which operate on the entire warp group.
Prior to #6585, most warp instructions simply ignored the upper 32 threads in a 64-thread warp. This obviously posed some accuracy issues. The shader decompiler rewrite aimed to better support these kinds of devices, but fell short. 
This PR aims to fix the warp instructions on 64-thread warp devices. Using the thread's invocation ID, it becomes clear if they are part of the lower or upper 32-thread group, and change the warp instruction to …

shaders: Fix warp instructions on 64-thread warp devices

---

src/core/core.cpp

The main_process was never being cleaned up, causing a noticeable memory leak on subsequent launches. 
This change cleans up the memory during Core Shutdown, mitigating the leak.
For reference, here's the memory usage after 4 launches of a relatively light homebrew:
Before:
After:

core: Destroy main_process during shutdown

---

src/core/file_sys/vfs.cpp
src/core/file_sys/vfs.h
src/core/file_sys/vfs_real.cpp
src/core/file_sys/vfs_real.h
src/core/file_sys/vfs_types.h
src/core/hle/service/filesystem/filesystem.cpp
src/core/hle/service/filesystem/filesystem.h
src/core/hle/service/filesystem/fsp_srv.cpp

Gets rid of homebrew warnings using this func

vfs: Partially implement GetFileTimeStampRaw

---

src/core/hle/service/ngct/ngct.cpp

ngct: Stub Match

---

src/yuzu/configuration/configure_debug.ui

Getting rid of some more squished text. Moving things around to tidy up as well.
Before | After
-------- | -----

Debug Config Ui: Clean-up and nits

---

src/core/hle/service/sockets/bsd.cpp
src/core/hle/service/sockets/bsd.h

- Used by Diablo II: Resurrected

service: bsd: Implement Read

---

src/core/network/network.cpp

Logging this may be a privacy concern for some users.

network: Do not log IP address

---

src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp

Fixes a crash on some drivers when tessellation is used but the IA topology is not patch list.
Closes #7094

vk_graphics_pipeline: Force patch list topology when tessellation is used

---

src/shader_recompiler/backend/spirv/emit_spirv_image.cpp

Implicit LOD sampling in non-fragment shaders behave on hardware as if sampling from LOD 0. Some drivers don't necessarily behave this way, so this change ensures all drivers match the behavior of HW in this instance.
This was confirmed to fix the behavior on the AMD windows Vulkan driver in unit tests. 
I am not aware of any specific bugs this may have fixed, but it does ensure more accurate behavior across drivers.

emit_spirv_image: Fix depth image implicit lod sample in non-fragment stages

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2021-11-01)

---

src/core/hle/kernel/svc.cpp
src/core/hle/kernel/svc_wrap.h

num_handles is a s32
Supersedes #7274

svc: Correct WaitSynchronization num_handles param type

---

src/core/hle/service/acc/acc.cpp
src/core/hle/service/acc/acc.h
src/core/hle/service/acc/acc_u0.cpp

Addresses the comments of #7283

service/acc: Rename Unknown160 to InitializeApplicationInfoV2

---

src/core/hle/service/pctl/pctl_module.cpp

service/pctl: Stub EndFreeCommunication

---

src/shader_recompiler/backend/spirv/emit_context.cpp
src/shader_recompiler/backend/spirv/emit_context.h
src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp

Reimplemented spirv legacy attribute support

shader: Spirv support legacy attribute v2

---

src/yuzu/configuration/configure_graphics.ui
src/yuzu/main.cpp

AMD'S FIDELITYFX SR -> AMD FSR

main: Shorten AMD FSR status bar text

---

src/core/hle/service/pm/pm.cpp

- Used by Skyline modding framework
See #7392 for progress on the support of this modding framework

service: pm: Implement AtmosphereGetProcessId 

---

src/video_core/renderer_vulkan/blit_image.cpp
src/video_core/renderer_vulkan/blit_image.h
src/video_core/renderer_vulkan/vk_texture_cache.cpp

Resolves some of the comments in PR #7368

general: Resolve comments in PR #7368

---

src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/svc.cpp
src/core/hle/service/ldr/ldr.cpp

- Used by Skyline modding framework
See #7392 for progress on the support of this modding framework

kernel: svc: Implement SetProcessMemoryPermission 

---

src/video_core/command_classes/codecs/codec.cpp

This Pull Request addresses the issues in the following scenarios:
- When someone installed Intel video drivers on an AMD system, the decoder will select the Intel VA-API decoding driver and yuzu will crash due to incorrect driver selection; the fix will check if the currently about-to-use driver is loaded in the kernel.
- When using NVIDIA driver on Linux with a ffmpeg that does not have CUDA capability enabled, the decoder will crash; the fix simply makes the decoder prefers the VDPAU driver over CUDA on Linux.
- When you are using Flatpak.
Related issues:
- https://github.com/flathub/org.yuzu_emu.yuzu/issues/218
- https://github.com/flathub/org.yuzu_emu.yuzu/issues/200

video_core/codecs: fix multiple decoding issues on Linux

---

src/video_core/texture_cache/format_lookup_table.cpp

Add missing pixel format mapping

---

src/core/hid/emulated_console.h
src/core/hid/emulated_controller.h
src/core/hid/emulated_devices.h
src/core/hid/hid_core.cpp
src/core/hid/hid_core.h
src/core/hid/hid_types.h
src/core/hid/input_converter.h
src/core/hid/input_interpreter.cpp
src/core/hid/input_interpreter.h
src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/npad.h
src/core/memory/cheat_engine.cpp
src/yuzu/applets/qt_controller.cpp
src/yuzu/configuration/configure_input_player.cpp

Described in the individual commits

core: hid: Post kraken cleanup

---

src/core/hle/service/friend/friend.cpp

- Used by Super Bomberman R Online
Closes #7479

service: friend: Implement GetCompletionEvent

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2021-12-01)

---

src/core/hle/service/am/am.cpp
src/core/hle/service/am/am.h
src/core/hle/service/caps/caps.h

- Used by Disney Magical World 2: Enchanted Edition

service: am: ISelfController: Stub SaveCurrentScreenshot

---

src/common/x64/native_clock.cpp

In my testing, waiting for 200ms provided the same level of precision as the previous implementation when estimating the RDTSC frequency.
This significantly improves the yuzu executable launch times since we reduced the wait time from 3 seconds to 200 milliseconds.

native_clock: Wait for less time in EstimateRDTSCFrequency

---

src/core/hid/emulated_controller.cpp

I forgot to add handheld support

core/hid: Add missing controller type

---

src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h

Used by ring fit adventure 1.2.0

service/hid: Stub SetNpadCaptureButtonAssignment and ClearNpadCaptureButtonAssignment

---

src/common/logging/filter.cpp
src/common/logging/types.h
src/core/CMakeLists.txt
src/core/hle/service/glue/glue.cpp
src/core/hle/service/glue/notif.cpp
src/core/hle/service/glue/notif.h

Used by ring fit adventure 1.2.0

service/notif: Add notif:a and stub ListAlarmSettings, Initialize

---

src/video_core/renderer_vulkan/maxwell_to_vk.cpp
src/video_core/vulkan_common/vulkan_device.cpp

- Used by Immortals Fenyx Rising
Closes #7540

renderer_vulkan: Add R16G16_UINT

---

src/input_common/drivers/tas_input.cpp
src/input_common/drivers/tas_input.h

Resolves a tiny bit of accumulated cruft and gets rid of some unnecessary header dependencies

tas_input: Minor cleanup

---

src/core/hid/emulated_controller.cpp

Fixes analog triggers not moving correctly.

core/hid: Fix faulty analog triggers

---

src/video_core/renderer_vulkan/maxwell_to_vk.cpp

- Used by Lego City Undercover
Closes #7548

maxwell_to_vk: Add ASTC_2D_8X5_UNORM

---

src/yuzu/main.cpp

Old version had formatting issues, and I want to provide an answer to the most common reason this pops up in the first place, outdated drivers.

Update video core popup

---

src/core/loader/kip.cpp

- Allows us to boot KIP (kernal apps), useful for testing the kernel.

core: loader: kip: Minimal changes to fix KIP loading.

---

dist/yuzu.desktop
dist/yuzu.xml

Add NSP and XCI associations and MIME info for XDG.

dist/XDG: add more file associations

---

src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/svc.cpp
src/core/hle/kernel/svc_wrap.h

- Not seen in any games yet, but validated with kernel tests.

core: hle: kernel: Implement SetMemoryPermission.

---

CMakeLists.txt
src/shader_recompiler/backend/spirv/emit_spirv.cpp

Liu's finding, this allows to build yuzu on VS 2022.
Ignore at will.

Increase boost requirement to 1.78.0

---

src/core/hle/kernel/k_memory_block.h
src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/svc.cpp
src/core/hle/kernel/svc_common.h

- Updates our svcSetHeapSize with latest HOS, furthermore allowing heap size to properly be extended/shrunk.
- Validated with tests https://github.com/Atmosphere-NX/Atmosphere/blob/master/tests/TestSvc/source/test_set_heap_size.cpp.

core: hle: kernel: Updated implementation of svcSetHeapSize.

---

src/core/CMakeLists.txt
src/core/hle/kernel/global_scheduler_context.cpp
src/core/hle/kernel/k_interrupt_manager.cpp
src/core/hle/kernel/k_interrupt_manager.h
src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/k_process.h
src/core/hle/kernel/k_scheduler.cpp
src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/k_thread.h
src/core/hle/kernel/svc.cpp

- We largely had the mechanics in place for thread pinning, this change hooks these up.
- Validated with tests https://github.com/Atmosphere-NX/Atmosphere/blob/master/tests/TestSvc/source/test_thread_pinning.cpp.

core: hle: kernel: Implement thread pinning.

---

src/core/hle/service/nvflinger/buffer_queue.cpp
src/core/hle/service/nvflinger/buffer_queue.h
src/core/hle/service/nvflinger/nvflinger.cpp
src/video_core/gpu.cpp

core:hle:service:nvflinger Implement few type in bufferqueue query method

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2022-01-05)

---

src/core/hid/motion_input.cpp
src/input_common/input_engine.cpp

Allow to map motion devices that only have accelerometer data

input_common: Allow to only have acceleration motion data

---

src/input_common/drivers/tas_input.cpp

It's posible to crash the emulator with misshaped TAS scripts.  This PR adds some error handling to prevent crashing from string to int/float conversions.
fixes: #7686

input_common: Handle errors on TAS scripts

---

CMakeLists.txt
externals/CMakeLists.txt
src/CMakeLists.txt
src/tests/CMakeLists.txt

Also remove remanent of phantom external.

cmake: make tests optional

---

src/core/hle/kernel/kernel.cpp

- CreateServiceThread and ReleaseServiceThread can be accessed by different threads, uses a lock to make this thread safe.
- Fixes a rare crash in Pokemon Sword/Shield that can occur when a new service thread is being created while an old one is being destroyed.

hle: kernel: Fix service_threads access to be thread safe.

---

src/input_common/drivers/sdl_driver.cpp

Minor nitpick
Code is from narr

Change default name for playstation controllers

---

src/yuzu/configuration/config.cpp
src/yuzu/uisettings.h

We did patreon poll about what theme should be new default theme instead white theme and dark colorful theme won

Change default theme to Dark colorful

---

src/core/hid/emulated_controller.cpp

Found by static analysis with PVS-Studio.

hid: fix std::transform call

---

src/input_common/drivers/mouse.cpp

Found by static analysis with PVS-Studio.

input_common: fix copy-paste error

---

src/video_core/vulkan_common/vulkan_device.cpp

https://gitlab.freedesktop.org/mesa/mesa/-/issues/5895
Fixes #7116 
Fixes #7709

vulkan_device: Fix sType for VkPhysicalDeviceShaderAtomicInt64Features

---

src/input_common/drivers/udp_client.cpp
src/input_common/drivers/udp_client.h

Display the battery level for UDP controllers

input_common: Report battery for UDP controllers

---

src/yuzu/configuration/configure_input_player.cpp

Somehow this wasn't added on kraken. Add the button modifiers to invert and toggle the input on keyboard
Closes #7759

yuzu: Add modifiers for keyboard

---

src/shader_recompiler/frontend/maxwell/translate/impl/video_minimum_maximum.cpp

Validated with unit tests. 
- Used by Pokemon Legends: Arceus.

video_minimum_maximum: Implement src operand selectors

---

src/core/hle/kernel/svc.cpp

svc: Add 32 bit SynchronizePreemptionState

---

dist/languages/ca.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/es.ts
dist/languages/fi.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2022-02-01)

---

src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h

- More accurately reflects real kernel behavior by using guest locks.

hle: kernel: KPageTable: Migrate locks to KScopedLightLock.

---

src/input_common/helpers/stick_from_buttons.cpp

This is a follow up of #7760 basically keyboard joystick don't use the input converter to get the button value. Instead we read the values directly. For this reason we need to apply the modifiers here.

input_common: Use attributes for analog range modifiers

---

src/yuzu/applets/qt_controller.cpp
src/yuzu/configuration/configure_input.cpp
src/yuzu/configuration/configure_vibration.cpp
src/yuzu/configuration/configure_vibration.h
src/yuzu/configuration/configure_vibration.ui

If a controller button is pressed the controller vibrates

yuzu: config: Vibrate the controller while configuring vibration strength

---

src/common/logging/filter.cpp
src/common/logging/types.h
src/core/CMakeLists.txt
src/core/hle/service/mnpp/mnpp_app.cpp
src/core/hle/service/mnpp/mnpp_app.h
src/core/hle/service/service.cpp

Used in Super Nintendo Entertainment System™ - Nintendo Switch Online
Data about this service seems lacking. For now stubbing seems to avoid some crashes.

service/mnpp: Stub mnpp_app

---

src/common/page_table.cpp
src/common/page_table.h
src/core/hle/kernel/k_page_table.cpp

- Improves the implementations of MapPhysicalMemory and UnmapPhysicalMemory to more closely reflect latest HOS.

core: hle: kernel: KPageTable: Improve Un/MapPhysicalMemory.

---

src/core/hle/service/am/am.cpp
src/core/hle/service/am/am.h
src/core/hle/service/apm/apm_controller.cpp
src/core/hle/service/apm/apm_controller.h

service: am: Update enum names to match documentation

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/es.ts
dist/languages/fi.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts

Update translations (2022-03-01)

---

src/common/logging/backend.cpp

Was getting an unhandled `invalid_argument` [exception](https://en.cppreference.com/w/cpp/thread/thread/join) during shutdown on my linux
machine. This function is called by the deconstructor and
may be called before `StartBackendThread` gets a chance to run, causing it to try and join a null thread.

logging: Convert `backend_thread` into an `std::jthread`

---

CMakeLists.txt

Revert "build(cmake): fix missing Qt5::DBus target on linux"

---

src/yuzu/configuration/config.cpp

Ensures the configs are written and saved between boots

config: Write dynarmic exclusive memory configs

---

src/shader_recompiler/ir_opt/rescaling_pass.cpp

ImageFetch offsets for 2D array coordinates have a different composite size than the coordinates. The rescaling pass was not taking this into account.
Fixes broken shaders when scaling is enabled in Astral Chain, and likely other titles.

rescaling_pass: Fix rescaling Color2DArray ImageFetch offsets

---

src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_64.cpp

Reverts yuzu-emu/yuzu#8016
@merryhime several other users narrowed down SSBU stutter to this 😪

Revert "dynarmic: Reduce size of code caches"

---

src/yuzu/applets/qt_web_browser.h

Adds include which was removed in #8048, to permit compiling.

Add include to fix compiling

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fi.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2022-04-01)

---

src/video_core/renderer_opengl/gl_device.cpp
src/video_core/texture_cache/texture_cache.h

Fixes [HW: AoC Regression](https://github.com/yuzu-emu/yuzu/issues/8121)

GPU Garbage Collection: Fix regressions.

---

src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_64.cpp

dynarmic: Print stack trace on unrecognised instruction or other exception

---

src/core/hle/service/nvflinger/buffer_queue_consumer.cpp
src/core/hle/service/nvflinger/buffer_queue_consumer.h
src/core/hle/service/nvflinger/buffer_queue_core.cpp
src/core/hle/service/nvflinger/buffer_queue_core.h
src/core/hle/service/nvflinger/buffer_queue_producer.cpp
src/core/hle/service/nvflinger/buffer_queue_producer.h
src/core/hle/service/nvflinger/consumer_base.cpp
src/core/hle/service/nvflinger/consumer_base.h
src/core/hle/service/nvflinger/nvflinger.cpp

Follow-up to #8088 & #8050. Several more fixes & cleanup to NVFlinger code.

Follow-up fixes for NVFlinger rewrite (Part 2)

---

src/CMakeLists.txt

These are similar to Wunused-function on gcc/clang

CMakeLists: Enforce C4505 and C5245

---

src/core/hid/emulated_console.cpp
src/core/hid/emulated_console.h
src/core/hid/emulated_controller.cpp
src/core/hid/emulated_controller.h
src/core/hid/emulated_devices.cpp
src/core/hid/emulated_devices.h

Toast found a bunch of data races on the HID side. This addresses some of them.

core: hid: Reduce the amount of data races

---

src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_64.cpp

Regression introduced in a5d040df3d. Closes #8201.

dynarmic: Fix single core mode

---

src/core/hle/service/jit/jit.cpp
src/core/hle/service/jit/jit_context.cpp
src/core/hle/service/jit/jit_context.h

Documents the HLE JIT plugin interface, makes it a little bit more robust against potentially misbehaving plugins, and removes the need for bare ARM implementations of helper functions.

service: jit: document and clean up

---

src/yuzu/configuration/configure_ui.cpp

I don't know why, but the development tools embed the language files in the following order
ca da cs de el es fi fr id it nb nl pl sv vi ko_KR ja_JP tr_TR pt_BR pt_PT ru_RU zh_CN zh_TW vi_VN
Sorted alphabetically
ca cs da de el es fi fr id it ja_JP ko_KR nb nl pl pt_BR pt_PT ru_RU sv tr_TR vi vi_VN zh_CN zh_TW
Current order
For the Yuzu User Interface Language, I believe the options should be in native language. 
Note: Not touching the System Language, those have a nice enumeration order provided by "N"
Basically with this Draft PR, I'm asking about two things
1. Can we sort the list alphabetically by the language code?
2. Should this list be in native strings, or left as the English names of the languages?

Changes to language order in General -> UI -> Interface Language

---

src/core/hle/result.h

A ResultRange defines an inclusive range of error descriptions within an error module.
This can be used to check whether the description of a given ResultCode falls within the range.
The conversion function returns a ResultCode with its description set to description_start.
An example of how it could be used:
```cpp
constexpr ResultRange ResultCommonError{ErrorModule::Common, 0, 9999};
ResultCode Example(int value) {
const ResultCode result = OtherExample(value);
// This will only evaluate to true if result.module is ErrorModule::Common and
// result.description is in between 0 and 9999 inclusive.
if (ResultCommonError.Includes(result)) {
// This returns ResultCode{ErrorModule::Common, 0};
return ResultCommonError;
}
return ResultSuccess;
}
```

hle/result: Implement ResultRange

---

src/video_core/macro/macro_jit_x64.cpp

This would crash in a difficult-to-identify location otherwise, if the macro tried to access a parameter that was too far outside the bounds of what it was supposed to be accessing. (The interpreter already does this.)

video_core/macro_jit_x64: warn on invalid parameter access

---

src/common/settings.h
src/video_core/macro/macro.cpp
src/yuzu/configuration/configure_debug.cpp
src/yuzu/configuration/configure_debug.ui

I thought we already had this implemented but I couldn't find it. Code is basically just lifted from shader_environment.cpp.

video_core/macro: Add option to dump macros

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2022-05-09)

---

dist/org.yuzu_emu.yuzu.metainfo.xml

For reference see the [specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-relations-control)

Add control to metainfo

---

src/core/hid/hid_types.h
src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/npad.h
src/core/hle/service/hid/errors.h
src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h

Things started to stack up on my side so I decided to add all in one PR to avoid merge conflicts, hopefully everything is separated by the commit name. All of these changes are relatively safe as is mostly just improving our current code.
Thanks to ReSwitched members for some help and insight on RE.
Changes:
- Adds error handling to several HID functions
- Improve some implementations to match more closely to HW
- Implement functions needed by Nintendo Switch Sports EnableSixAxisSensorUnalteredPassthrough, IsSixAxisSensorUnalteredPassthroughEnabled, LoadSixAxisSensorCalibrationParameter, GetSixAxisSensorIcInformation, ResetIsSixAxisSensorDeviceNewlyAssigned.

Service: hid: Several improvements and implementations

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2022-06-01)

---

src/core/debugger/gdbstub.cpp

This is reported as being implemented in the qSupported packet, so it should be present.

gdbstub: add missing library list query

---

src/yuzu/main.cpp

Qt5 and Qt6 don't really do a good job of reporting Windows versions past the 2004 version.
Current: Windows 10 Version 2009
This Patch: Windows 10 Version 21H1 (Build 19043.1706)
Also: Windows 11 Version 21H2 (Build 22000.675)
Fixes: #8362
------
Just `Windows 11 Version 21H2` might be sufficient, but its easier to quickly delete some code than quickly add some code.

Logging: Report Post Windows 10 2004 versions, like Windows 11

---

src/core/core.cpp
src/core/core.h
src/core/debugger/debugger.cpp
src/core/debugger/debugger.h
src/core/debugger/debugger_interface.h
src/core/debugger/gdbstub.cpp
src/core/debugger/gdbstub.h
src/yuzu/main.cpp
src/yuzu_cmd/config.cpp
src/yuzu_cmd/default_ini.h
src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
src/yuzu_cmd/yuzu.cpp

core/debugger: support operation in yuzu-cmd

---

src/video_core/renderer_vulkan/vk_compute_pass.cpp

According to the standard, a narrowing conversion is an implicit conversion from an integer or unscoped enumeration type to an integer type that cannot represent all the values of the original type, except when the value is a literal or constant expression.
MSVC, unlike GCC or Clang, determines this to be a narrowing conversion despite the enumeration exclusively containing values that fit within the range of a 32 bit integer, emitting a warning since designated initializers prohibit narrowing conversions.
To solve this, explicitly cast to the type we are initializing.
The diff is due to clang-format deciding to reformat the whole lambda. The actual change is just the addition of the cast.

vk_compute_pass: Explicitly cast to VkAccessFlags

---

src/common/thread.cpp
src/common/thread.h
src/common/uint128.h
src/common/x64/native_clock.cpp
src/common/x64/native_clock.h
src/core/core_timing.cpp
src/core/core_timing.h
src/tests/core/core_timing.cpp

This remakes core timing making it use more threads to improve it's accuracy while sacrificing ordering.

Core: Remake Core Timing

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2022-07-01)

---

.github/workflows/ci.yml
.github/workflows/verify.yml

Updates checkout and cache to v3

ci: Update various actions from v2 to v3

---

src/common/bit_field.h

This works around a GCC/Clang-specific issue in some conditions where the game would spam the controller applet due to believing the wrong controllers were connected. Aliasing of the bitfield members would cause the compiler to mark the wrong bits in the pad state struct (e.g., only right joycon when dual joycons were connected).
Original code snippet:
https://github.com/yuzu-emu/yuzu/blob/313f047f974249c0fa004056ced3f18a8c61eae4/src/core/hle/service/hid/controllers/npad.cpp#L472-L487
Unintended code generation causes the bitfield to be clobbered:

common: fix bitfield aliasing on GCC/Clang

---

src/common/logging/filter.cpp
src/common/logging/types.h
src/core/CMakeLists.txt
src/core/hle/service/nifm/nifm.cpp
src/core/hle/service/ptm/psm.cpp
src/core/hle/service/ptm/psm.h
src/core/hle/service/ptm/ptm.cpp
src/core/hle/service/ptm/ptm.h
src/core/hle/service/ptm/ts.cpp
src/core/hle/service/ptm/ts.h
src/core/hle/service/service.cpp

The Homebrew menu still fails to boot. But at least those 2 services are implemented. This PR also changes PSM to a subservice of PTM.

service: ptm: Add TS, nifm: Stub GetInternetConnectionStatus

---

src/core/arm/arm_interface.cpp
src/core/arm/arm_interface.h
src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_64.cpp

Abort watchpoints as soon as possible.
Ref: https://github.com/merryhime/dynarmic/commit/f7b42b924ebaa5acd225d6629c2dab6f16a9cd39

dynarmic: Abort watchpoints ASAP

---

src/core/hle/service/sockets/bsd.cpp

Currently, when the MSG_DONTWAIT flag is passed to the Recv socket function, Yuzu ignores this flag, and continues with a blocking call to the Recv equivalent on the host OS.  Calls to RecvFrom, however, correctly handle this flag. This PR adds the non-block functionality of RecvFrom to Recv. In the code, this looks like an oversight from when this functionality was initially added to RecvFrom.
This PR was prompted by attempting to improve compatibility with the Super Mario Odyssey Online mod.

Enable the use of MSG_DONTWAIT flag on RecvImpl

---

src/video_core/renderer_vulkan/vk_blit_screen.cpp

This aims to address the recent string of Vulkan-related crashes coming from the Flathub builds, which enable libstdc++ assertions and thus catch this subspan operation overflowing.

video_core: use correct byte size for framebuffer

---

src/core/CMakeLists.txt
src/core/hle/service/hid/irs.cpp
src/core/hle/service/hid/irs_ring_lifo.h
src/core/hle/service/hid/irsensor/clustering_processor.cpp
src/core/hle/service/hid/irsensor/clustering_processor.h
src/yuzu/bootmanager.cpp

This infrared image processor is used by `Game Builder Garage` and `Nintendo Labo Toy-Con 01: Variety Kit`. Seems to be fully functional as long there's good contrast with the objects.

service: irs: Implement clustering processor

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2022-08-01)

---

src/video_core/renderer_vulkan/vk_blit_screen.cpp

Redo of #8611. Should still fix the crash reported from Flatpak users, but avoid a very slow path for the framebuffer blit in Pokemon: Let's Go, Pikachu! when attempting to play with your Pokemon.

video_core: differentiate between tiled and untiled framebuffer sizes for unaccelerated blits

---

src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_64.cpp

#8637 had a conflict with #8240

core/arm: fix build error

---

src/video_core/renderer_opengl/renderer_opengl.cpp
src/video_core/renderer_vulkan/vk_blit_screen.cpp

video_core: support framebuffer crop rect top not zero

---

CMakeLists.txt

Better than deleting `.gitmodules` manually :p

cmake: add option to check submodules

---

src/yuzu/bootmanager.cpp
src/yuzu/configuration/configure_camera.cpp

Our current camera implementation have a horrible bug. It saves every single frame into a file. This results in millions of images over a long period of play time often breaking file explorer.
This PR forces the output to be saved in a buffer. This comes at a cost. If camera doesn't support this we no longer support that camera.
Sorry for everyone with this issue. If you are on windows and the file explorer doesn't work please open cmd on that folder and type "del IMG_00*.jpg" after a couple of minutes it will delete all images generated by this feature.

yuzu: Force camera output to be saved on a buffer

---

src/core/hle/service/audio/audren_u.cpp

[Audio] Implement AudRenU:RequestUpdateAuto

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2022-09-01)

---

src/core/CMakeLists.txt
src/core/file_sys/system_archive/shared_font.cpp
src/core/hle/service/am/applets/applet_web_browser.cpp
src/core/hle/service/ns/iplatform_service_manager.cpp
src/core/hle/service/ns/iplatform_service_manager.h
src/core/hle/service/ns/ns.cpp

Used in homebrew Ship of Harkinian. This is the same as pl:u but with system access

core: ns: Implement pl:s service

---

src/common/input.h
src/core/hid/input_converter.cpp
src/input_common/input_poller.cpp
src/yuzu/configuration/configure_input_player.cpp

Allows to toggle buttons that have analog inputs.

input_common: Add support for analog toggle

---

src/video_core/textures/astc.cpp

Given the issues with GPU accelerated ASTC decoding with NVIDIA's latest drivers, parallelize astc decoding on the CPU.
Uses half the available threads in the system for astc decoding.

astc: Enable parallel CPU astc decoding

---

src/core/hle/service/nfp/nfp.cpp
src/core/hle/service/sockets/bsd.cpp
src/network/network.cpp
src/shader_recompiler/backend/glasm/emit_glasm.cpp
src/shader_recompiler/backend/glsl/emit_glsl.cpp

Fix some typos reported by Lintian

chore: fix some typos

---

src/audio_core/sink/sink_stream.cpp

Do not try to pause core timing from the audio thread when using single-core

---

src/core/hle/service/hid/irs.cpp
src/yuzu/applets/qt_controller.cpp
src/yuzu/configuration/configure_input.cpp
src/yuzu/main.cpp

Nothing special just removes some warnings from the log

yuzu: Silence some clang warnings

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2022-10-01)

---

src/video_core/macro/macro_jit_x64.cpp

Fixes the bug mentioned in #6598, so it can be merged now.

macro_jit_x64: fix miscompilation of bit extraction operations

---

src/shader_recompiler/backend/glasm/emit_glasm_context_get_set.cpp

Same as #8024, #8133 for GLASM users
|Before|After|
|-|-|
|![noldc](https://user-images.githubusercontent.com/9658600/193477413-6749ad65-23f3-4f70-b9ea-54bda5193bd8.png)|![ldc](https://user-images.githubusercontent.com/9658600/193477420-399e3bcd-a150-4f19-a7cd-301b83f38d36.png)|
Note that there is a way to do this natively in the shader language:
```
CBUFFER buf0[][] = { program.buffer[0..3] };
LDC.F32X4 result.position, buf0[R0.x][0];
```
but as far as I know, we can't use it here because we bind buffers sparsely. (Same is true for GLSL and SPIR-V backends.)

shader_recompiler: add extended LDC to GLASM backend

---

src/core/hid/emulated_controller.cpp
src/core/hle/service/nfp/amiibo_crypto.cpp
src/core/hle/service/nfp/nfp_device.cpp
src/core/hle/service/nfp/nfp_result.h
src/core/hle/service/nfp/nfp_types.h
src/core/hle/service/nfp/nfp_user.cpp

I ran this service through an unit testing homebrew to ensure we are mostly 1:1 with real hardware. Hopefully removing any remaining bug that I'm not aware of.  This should be the final PR related to the amiibo service.

service: nfp: Fix errors to pass unit testing

---

src/core/hle/service/nfp/nfp_types.h

nfp_types: silence -Wtype-limits

---

src/video_core/renderer_vulkan/vk_scheduler.cpp

This makes homebrew launching work consistently in Vulkan. Previously WaitWorker would return after the queue was popped but before processing completed, causing the backend try to wait for a semaphore before signaling it due to a race condition.

vk_scheduler: wait for command processing to complete

---

src/core/hle/service/filesystem/fsp_srv.cpp
src/core/hle/service/filesystem/fsp_srv.h

Official sdk aborts if this request fails

fsp_srv: stub GetCacheStorageSize

---

src/video_core/host1x/syncpoint_manager.cpp

This restores the mistakenly deleted logic from Skyline. This was causing crashes when frames rendered too slowly.
https://github.com/skyline-emu/skyline/blob/86f6fc510e4c482b53cb8ae32cb20f0af401b888/app/src/main/cpp/skyline/soc/host1x/syncpoint.cpp#L30

syncpoint_manager: ensure handle is removable before removing

---

src/video_core/renderer_base.cpp

video_core: don't block rendering on screenshots

---

src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
src/video_core/renderer_vulkan/vk_staging_buffer_pool.h

Reverts yuzu-emu/yuzu#8987
See #9022 for details. I'll be leaving this up until we figure out what's going on.

Revert "vulkan: automatically use larger staging buffer sizes when possible"

---

src/core/hle/result.h

This ports all of the new R_ macros from libvapours except the ranged return check macros.

kernel: add expanded result macros

---

src/common/settings.h

Since 16:10 was added, the maximum value is now 4.

settings: Update aspect_ratio range

---

src/yuzu/main.cpp

Kreato pointed this out over on discord.
-------
This is the perfect PR to verify that the transifex push step works properly. Please merge **after** #9058

fix a tiny spelling mistake

---

src/core/hle/kernel/k_slab_heap.h

See [this comment](https://github.com/Atmosphere-NX/Atmosphere/blob/master/libraries/libmesosphere/include/mesosphere/arch/arm64/kern_k_slab_heap_impl.hpp#L28). An ABA can occur when `ret` and `ret->next` are evaluated in the `compare_exchange_weak` loop.
The x86 architecture does not have an exclusive monitor so this type of loop probably cannot be correctly implemented without using a lock, in the general case (for slabs 16 bytes or larger, it may be possible with 16-byte atomic compares and a counter value).

kernel: fix slab heap ABA

---

src/tests/video_core/buffer_base.cpp

tests: fix for -Wall

---

src/core/file_sys/control_metadata.cpp
src/core/file_sys/control_metadata.h

file_sys: Priority display of game titles in the current language

---

src/core/hle/service/nvdrv/core/nvmap.cpp
src/core/hle/service/nvdrv/core/nvmap.h
src/core/hle/service/nvdrv/devices/nvmap.cpp
src/core/hle/service/nvflinger/buffer_queue_producer.cpp
src/core/hle/service/nvflinger/nvflinger.cpp
src/core/hle/service/nvflinger/nvflinger.h
src/core/hle/service/vi/display/vi_display.h
src/core/hle/service/vi/vi.cpp

Allows hbmenu to be almost fully functional, with some only weird flickering issue in Vulkan regarding console homebrew.

Improved support for nx-hbmenu

---

src/core/hle/service/am/am.cpp
src/core/hle/service/am/am.h

Allows bayonetta 3 to proceed without crashing

service: am: Stub SetRecordVolumeMuted

---

src/core/hle/kernel/k_thread.cpp

k_thread: fix single core

---

src/yuzu/main.ui

This pr removes an unnecessary sepator in file menu (main.ui)

remove unnecessary sepator in file menu (main.ui)

---

dist/languages/uk.ts

I'm not sure if GillianMC and I can claim that yuzu is first emulator translated to Ukrainian until the language files are used in builds.
-------
Please consider merging this if Zhaobot doesn't get kicked in a day or so.

Manually import Ukrainian language file

---

src/core/internal_network/socket_proxy.cpp

network: unbreak on BSDs due to missing include

---

src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp

video_core: Fix scaling graphical regressions for multiple games

---

src/video_core/engines/maxwell_3d.cpp

Fix #9147
Fix Instance model instance_count error.

video_core: Fix drawing trigger mechanism regression

---

src/shader_recompiler/backend/glasm/emit_glasm_context_get_set.cpp
src/shader_recompiler/backend/glasm/emit_glasm_instructions.h
src/shader_recompiler/backend/glasm/glasm_emit_context.cpp
src/shader_recompiler/backend/glsl/emit_glsl_context_get_set.cpp
src/shader_recompiler/backend/glsl/emit_glsl_instructions.h
src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
src/shader_recompiler/backend/spirv/emit_spirv_instructions.h
src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
src/shader_recompiler/backend/spirv/spirv_emit_context.h
src/shader_recompiler/frontend/ir/ir_emitter.cpp
src/shader_recompiler/frontend/ir/ir_emitter.h
src/shader_recompiler/frontend/ir/opcodes.inc
src/shader_recompiler/frontend/ir/patch.h
src/shader_recompiler/frontend/maxwell/translate/impl/move_special_register.cpp
src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
src/shader_recompiler/shader_info.h
src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp

Fix The Legend of Heroes Trails from Zero main menu background black screen.

video_core: Fix few issues in Tess stage

---

src/core/hle/kernel/k_event.cpp
src/core/hle/kernel/service_thread.cpp

Some games use a _lot_ of simultaneous sessions. Since we were assigning a new KProcess for services with their own dedicated threads, the process slab heap could run out -- this was reported to happen in Monster Hunter Rise. This works around the issue temporarily by getting rid of the process until I finish reworking the service architecture.

service_thread: remove explicit KProcess

---

src/common/settings.cpp
src/common/settings.h
src/video_core/renderer_vulkan/vk_fsr.cpp
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_graphics.cpp
src/yuzu/configuration/configure_graphics.h
src/yuzu/configuration/configure_graphics.ui
src/yuzu_cmd/config.cpp

Simply a sharpening slider for FSR.
Lacks support for per-game settings, Qt is scary.

FSR Sharpening Slider

---

src/yuzu_cmd/default_ini.h

While working with yuzu-cmd I noticed the config was misleading. I updated the description a bit to be more clear.

yuzu-cmd: Update configuration file description

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/uk.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2022-12-01)

---

src/core/hle/service/audio/audin_u.cpp
src/core/hle/service/audio/audout_u.cpp
src/core/hle/service/audio/audren_u.cpp

- This was arbitrarily added by me, and does not appear to be helpful.

hle: service: audio: Use default service thread.

---

src/core/hle/kernel/service_thread.cpp

service_thread: fix uninitialized memory usage

---

src/video_core/engines/maxwell_3d.cpp

Noticed that macros interact with this reg, may as well use it.

Respect render mode override

---

src/common/settings.h
src/core/arm/arm_interface.cpp
src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_64.cpp
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_cpu_debug.cpp
src/yuzu/configuration/configure_cpu_debug.ui
src/yuzu_cmd/config.cpp
src/yuzu_cmd/default_ini.h

Fixes #8776 (sorry for the delay)

core: add option to break on unmapped access

---

src/video_core/engines/draw_manager.cpp
src/video_core/engines/draw_manager.h
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_vulkan/vk_rasterizer.cpp

More accurate topology update logic.

video_core: Adjust topology update logic and Adjust Clear Manage

---

src/common/thread.h
src/core/core.cpp
src/core/cpu_manager.cpp
src/core/cpu_manager.h
src/core/hle/kernel/kernel.cpp

Mainly intended to prevent deadlocks/crashes on GPU initialization failure

general: improve handling of system startup failure

---

src/core/hle/service/audio/audin_u.cpp
src/core/hle/service/audio/audout_u.cpp
src/core/hle/service/audio/audren_u.cpp

Revert "hle: service: audio: Use default service thread."

---

src/core/frontend/emu_window.h
src/video_core/gpu.cpp
src/video_core/renderer_opengl/gl_device.cpp
src/video_core/renderer_opengl/gl_device.h
src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_opengl/gl_shader_cache.h
src/video_core/renderer_opengl/renderer_opengl.cpp
src/video_core/renderer_vulkan/renderer_vulkan.cpp
src/video_core/renderer_vulkan/vk_swapchain.cpp
src/video_core/renderer_vulkan/vk_swapchain.h
src/yuzu/bootmanager.cpp
src/yuzu/main.cpp
src/yuzu/main.h
src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp

Based on: https://github.com/yuzu-emu/yuzu/pull/9427

Wayland fixes

---

src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/k_process.h
src/core/hle/kernel/svc.cpp

Implemented according to atmosphere. Needed by Just Dance® 2023 Edition.

kernel: process: Implement GetFreeThreadCount

---

src/yuzu/bootmanager.cpp
src/yuzu/main.cpp

qt: handle wayland-egl platform name

---

src/core/core.cpp
src/core/core.h
src/yuzu/bootmanager.cpp
src/yuzu/bootmanager.h
src/yuzu/main.cpp
src/yuzu/main.h

This gets rid of some spaghetti surrounding starting and stopping emulation.

EmuThread: refactor

---

src/yuzu/configuration/configure_input_player.cpp
src/yuzu/configuration/configure_input_player.h
src/yuzu/configuration/configure_input_player.ui

We don't need a refresh button if we always keep the list updated.

yuzu: Automatically refresh device list

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/uk.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2023-01-01)

---

src/core/hid/emulated_controller.cpp

To avoid quickly switching between different input methods whenever one of them receives an output, Yuzu has a system to keep the old input device until the other one input surpasses a certain threshold (`0.5f` by default). However, this should not apply to TASes, as those can also have much less extreme inputs that do not pass that threshold, which should still be played back either way. 
To account for that, this "anti-flapping-system" should be ignored if the new playback device is a TAS input. In that case, immediately change the input device and accept the new stick value, but only change back to non-TAS-inputs if TAS enters a value of 0;0 or the non-TAS-input surpasses the threshold.

TAS: Immediately switch stick to TAS on input

---

src/common/settings.h

Too many hardware support issues.

renderer_vulkan: disable turbo by default

---

src/yuzu/configuration/configure_graphics_advanced.cpp

It isn't supposed to be PartiallyChecked when using the global setting

qt: fix configuration weirdness on turbo

---

src/video_core/vulkan_common/vulkan_device.h
src/video_core/vulkan_common/vulkan_wrapper.cpp
src/video_core/vulkan_common/vulkan_wrapper.h

vulkan_common: fix indirect draw with count

---

src/video_core/vulkan_common/vulkan_device.cpp

There is a bug in MoltenVK where if you try to actually use all 31 of the reported vertex attributes and bindings, it will think there are no bindings and invoke undefined behavior in the shader:
> It chooses vertex buffer indices with the equation metal_max_buffers - 1 - vulkan_index, which goes negative for buffer 32
> And then it has a second check of whether a buffer should be considered used by a pipeline, and that one uses what I'm guessing is the number of buffers declared in the descriptor layout
> And that one also [goes negative], which makes it think no buffers are used by the pipeline, which is why it doesn't bind any
|Before|After|
|-|-|
|<img width="1072" alt="Screenshot 2023-01-09 at 7 05 49 PM" src="https://user-images.githubusercontent.com/9658600/211432587-ed689818-bacb-4 …

MoltenVK: restrict number of vertex attributes/bindings to 16

---

src/input_common/drivers/sdl_driver.cpp

Turns out things like the web applet disable motion.  SDL is never aware of this and starts to push null data. This PR fixes the issue by restarting the sensors if they send invalid data after a few seconds.

input_common: reset sdl motion if data is invalid

---

src/core/debugger/gdbstub.cpp

Prints out the fastmem region. Helpful for simplifying external debugging workflows as guest pointers can simply be calculated as fastmem base address +  guest address.

debugger: add host fastmem pointer fetch command

---

src/yuzu/configuration/config.cpp
src/yuzu/hotkeys.cpp
src/yuzu/hotkeys.h
src/yuzu/uisettings.h

pressing and holding volume up/down hotkeys will now increase/decrease repeatedly.

allow volume up/down hotkeys to be repeated

---

src/yuzu/configuration/configure_dialog.cpp
src/yuzu/configuration/configure_motion_touch.cpp
src/yuzu/configuration/configure_per_game.cpp
src/yuzu/configuration/configure_tas.cpp
src/yuzu/debugger/controller.cpp
src/yuzu/debugger/profiler.cpp
src/yuzu/install_dialog.cpp
src/yuzu/main.cpp
src/yuzu/util/limitable_input_dialog.cpp
src/yuzu/util/sequence_dialog/sequence_dialog.cpp

Sets the AA_DisableWindowContextHelpButton attribute to disable this useless button globally.

main: Globally disable the "?" button on dialogs

---

src/core/hle/kernel/k_code_memory.cpp
src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/k_shared_memory.cpp
src/core/hle/kernel/svc.cpp

Trying again for #9516. Will do some internal testing first to verify.

kernel: KPageTable: update

---

src/shader_recompiler/backend/glasm/emit_glasm.cpp
src/shader_recompiler/backend/glasm/emit_glasm_image.cpp
src/shader_recompiler/backend/glsl/emit_glsl_image.cpp
src/shader_recompiler/backend/glsl/glsl_emit_context.cpp

Fixes character portraits in Fire Emblem Engage when using GLSL/GLASM shader backends

glasm, glsl: Implement multisampled Image Fetch

---

src/common/polyfill_thread.h

- If the callback function is being invoked concurrently on another thread, the destructor does not complete until the callback function invocation is complete.
- If the callback function is being invoked on the same thread the destructor is being invoked on, then the destructor returns without waiting for callback invocation to complete (see Notes).
[(cppreference)](https://en.cppreference.com/w/cpp/thread/stop_callback/%7Estop_callback)
Also avoids some iterator invalidation nastiness by using unique IDs for callbacks in a map instead of actual iterators to them

polyfill_thread: satisfy execution ordering requirements of stop_callback

---

src/shader_recompiler/ir_opt/texture_pass.cpp

texture_pass: Refactor texture handle retrieval

---

.ci/scripts/format/script.sh
src/common/address_space.h
src/common/alignment.h
src/common/atomic_helpers.h
src/common/bit_util.h
src/common/concepts.h
src/common/div_ceil.h
src/common/expected.h
src/common/intrusive_red_black_tree.h
src/common/make_unique_for_overwrite.h
src/common/polyfill_ranges.h
src/common/polyfill_thread.h
src/common/settings.h
src/common/tree.h
src/common/vector_math.h
src/core/hle/kernel/k_auto_object.h
src/core/hle/kernel/k_priority_queue.h
src/core/hle/kernel/k_scoped_lock.h
src/core/hle/kernel/k_thread.h
src/core/hle/kernel/k_thread_local_page.h
src/input_common/helpers/joycon_protocol/common_protocol.h
src/shader_recompiler/frontend/ir/ir_emitter.h
src/shader_recompiler/frontend/ir/value.h
src/shader_recompiler/object_pool.h
src/video_core/texture_cache/descriptor_table.h
src/video_core/texture_cache/slot_vector.h

Depends on https://github.com/yuzu-emu/build-environments/pull/69

Move to Clang Format 15

---

CMakeLists.txt

cmake: Download clang format 15

---

src/core/CMakeLists.txt
src/core/hardware_properties.h
src/core/hle/kernel/k_capabilities.cpp
src/core/hle/kernel/k_capabilities.h
src/core/hle/kernel/svc_types.h
src/core/hle/kernel/svc_version.h

Does nothing right now, will be used for KProcess later.

kernel: add KCapabilities

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/uk.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2023-02-01)

---

src/common/input.h
src/core/hid/emulated_controller.cpp
src/core/hid/emulated_controller.h
src/core/hle/service/hid/controllers/npad.cpp
src/input_common/input_poller.cpp
src/yuzu/configuration/configure_input_player.cpp
src/yuzu/configuration/configure_input_player_widget.cpp
src/yuzu/configuration/configure_input_player_widget.h

Three request in a single day granted this PR. For everyone who likes cheating this PR implements turbo buttons. Now you can press buttons as fast as a switch game can register.

input_common: Implement turbo buttons

---

src/core/CMakeLists.txt
src/core/hle/kernel/init/init_slab_setup.cpp
src/core/hle/kernel/k_device_address_space.cpp
src/core/hle/kernel/k_device_address_space.h
src/core/hle/kernel/kernel.h
src/core/hle/kernel/svc_types.h

kernel: add KDeviceAddressSpace

---

src/input_common/helpers/stick_from_buttons.cpp

Last time I had a bit of a harsh time remembering how this code worked. So this PR simplifies the code by using the same logic for both analog and digital sticks.

input_common: Simplify stick from button

---

src/yuzu_cmd/yuzu.cpp

Having different arguments for each yuzu version is annoying. So this PR adds the -u and -g argument to yuzu cmd.

yuzu_cmd: Order arguments alphabetically and port arguments from Qt

---

src/yuzu/CMakeLists.txt
src/yuzu/discord_impl.cpp

This PR has been opened due to https://github.com/yuzu-emu/yuzu/pull/9051 being stale.
I decided to use the Yuzu combability wiki to grab images.

Game Image with Discord RPC

---

src/yuzu_cmd/default_ini.h

Rename FSR, add missing resolution multipliers, and SMAA

Update yuzu_cmd's default_ini.h

---

src/yuzu/main.cpp
src/yuzu/main.h

adding a volume display to the main window which allows for easy display of volume/mute status.
clicking it will display a slider to change the volume
https://user-images.githubusercontent.com/6887590/213465007-1158e9f1-1dc3-41cd-9e3f-da961cd6b33d.mp4

add volume quicksetting with volume slider

---

src/core/hle/kernel/k_capabilities.cpp
src/core/hle/kernel/physical_core.h

kernel: fix compilation with older gcc

---

src/audio_core/sink/cubeb_sink.cpp

Fixes a yuzu crash when another thread tries to initialize cubeb.

audio: cubeb: Fix yuzu crashing when it test for latency

---

src/core/CMakeLists.txt
src/core/hle/kernel/init/init_slab_setup.cpp
src/core/hle/kernel/k_object_name.cpp
src/core/hle/kernel/k_object_name.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/kernel.h
src/core/hle/kernel/svc/svc_port.cpp

kernel: add KObjectName

---

src/core/hle/kernel/kernel.cpp

On MSVC at least, there seems to be a non-trivial overhead to calling `GetHostThreadId()`.
This slightly reworks the host_thread_id variable to reduce some of the complexity around its usage, along with some small refactors around dummy threads/current_thread.
I saw measurable improvements to the overhead of calling `GetHostThreadId()` with these changes in place. But there still are times where the call can take 0.1ms to 0.5ms. This is rather odd, maybe some thread_local implementation quirk on MSVC's part.

kernel: Refactor thread_local variable usage

---

src/core/hle/kernel/svc.cpp
src/core/hle/kernel/svc.h
src/core/hle/kernel/svc/svc_address_translation.cpp
src/core/hle/kernel/svc/svc_cache.cpp
src/core/hle/kernel/svc/svc_code_memory.cpp
src/core/hle/kernel/svc/svc_debug.cpp
src/core/hle/kernel/svc/svc_device_address_space.cpp
src/core/hle/kernel/svc/svc_insecure_memory.cpp
src/core/hle/kernel/svc/svc_io_pool.cpp
src/core/hle/kernel/svc/svc_physical_memory.cpp
src/core/hle/kernel/svc/svc_port.cpp
src/core/hle/kernel/svc/svc_process_memory.cpp
src/core/hle/kernel/svc_generator.py
src/video_core/buffer_cache/buffer_base.h

svc: Fix type consistency (exposed on macOS)

---

src/core/hle/service/hid/hidbus.cpp
src/core/hle/service/hid/hidbus.h

Minor change from a mistake I made. Shouldn't affect anything.

core: hidbus: Fix BusType size

---

src/common/settings.h
src/core/hid/emulated_controller.cpp
src/core/hid/emulated_controller.h
src/core/hid/hid_types.h
src/yuzu/applets/qt_controller.cpp
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_input_per_game.cpp
src/yuzu/configuration/configure_input_player.cpp

Reverts #9824. Input config is very broken after this change. I need to come up with a better solution.

Revert "yuzu: config: Remove player 8 and 9 from config file"

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/uk.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2023-03-01)

---

src/common/settings.h

fix typo in settings.h

---

src/core/hle/service/psc/psc.cpp
src/core/hle/service/ssl/ssl.cpp
src/core/hle/service/usb/usb.cpp

Updates and completes info about these services. Doesn't introduce anything new.

Service: USB, SSL, PSC: Update

---

src/core/hle/kernel/svc/svc_synchronization.cpp

1. Invalid use of GetPointer for address with no alignment requirements
2. Missing conversion of ResultSessionClosed to ResultSuccess

kernel: fix WaitSynchronization

---

src/video_core/engines/draw_manager.cpp
src/video_core/renderer_opengl/blit_image.cpp
src/video_core/renderer_opengl/gl_rasterizer.cpp

video_core: Fix inline_index and draw_texture error

---

src/video_core/renderer_vulkan/vk_scheduler.cpp

vulkan: fix scheduler chunk reserve

---

src/core/hle/kernel/k_address_arbiter.cpp
src/core/hle/kernel/k_condition_variable.cpp

This isn't a tail call in any of the cases and there's no apparent reason to use recursion here.

kernel: fix unbounded stack usage in atomics

---

src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/npad.h
src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h

Used by Let's Get Fit. I already had this implemented but I haven't really done any test at the moment. Tomorrow I will confirm if it works as intended.

service: hid: Implement SetNpadJoyAssignmentModeSingleWithDestination

---

src/core/frontend/applets/profile_select.cpp
src/core/frontend/applets/profile_select.h
src/core/hle/service/am/applets/applet_profile_select.cpp
src/core/hle/service/am/applets/applet_profile_select.h
src/yuzu/applets/qt_profile_select.cpp
src/yuzu/applets/qt_profile_select.h
src/yuzu/main.cpp
src/yuzu/main.h

In an attempt to fix a game issue I ended up taking a look to this applet. This applet does much more than just selecting a user, while this PR doesn't implement new functionality it passes the correct arguments to the frontend so they can be implemented later.

service: am: Improve profile select applet

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/uk.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2023-04-04)

---

src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
src/yuzu/configuration/configure_general.ui
src/yuzu_cmd/default_ini.h

kernel: switch extended memory setting to 8GB arrangement

---

src/video_core/renderer_vulkan/vk_master_semaphore.cpp
src/video_core/renderer_vulkan/vk_master_semaphore.h
src/video_core/renderer_vulkan/vk_scheduler.cpp
src/video_core/vulkan_common/vulkan_device.h

vulkan: use plain fences when timeline semaphores are not available

---

src/core/hid/emulated_controller.cpp

Similar to TAS we don't want any deadzone here.

core: hid: Remove deadzone of virtual controller

---

src/video_core/engines/fermi_2d.cpp

Blit is being passed out-of-bounds ranges when using corner sampling, due to a pre-added offset. Pokemon Scarlet throws a lot of validation errors with invalid ranges, like (2, 1922) rather than the expected (0, 1920).

Account for a pre-added offset when using Corner sample mode for 2D blits

---

src/core/hle/service/audio/audout_u.cpp

IGS Classic Arcade Collection [0100BA001821A000] is now accessible to play.

core: audio: return result when audio_out initialize failed

---

src/common/intrusive_list.h
src/core/hle/kernel/k_event_info.h
src/core/hle/kernel/k_object_name.h
src/core/hle/kernel/k_server_port.h
src/core/hle/kernel/k_server_session.h
src/core/hle/kernel/k_session_request.h
src/core/hle/kernel/k_shared_memory_info.h
src/core/hle/kernel/k_thread.h

This switches the kernel lists to a simplified implementation in common.

kernel: remove boost intrusive lists

---

src/video_core/buffer_cache/buffer_cache.h
src/video_core/buffer_cache/memory_tracker_base.h
src/video_core/texture_cache/texture_cache.h

Makes the build work on my least favorite compiler again.
Fixes #10136

video_core: fix build on Apple Clang

---

src/core/core.cpp
src/core/hle/kernel/k_auto_object.h
src/core/hle/kernel/kernel.cpp
src/core/hle/service/ipc_helpers.h
src/core/hle/service/kernel_helpers.cpp
src/core/hle/service/mutex.cpp
src/core/hle/service/server_manager.cpp
src/core/hle/service/sm/sm.cpp
src/core/hle/service/sm/sm_controller.cpp

Perfectly balanced, as all things should be.

kernel: match calls to Register and Unregister

---

src/common/settings.cpp
src/common/settings.h
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_graphics_advanced.cpp
src/yuzu/configuration/configure_graphics_advanced.h
src/yuzu/configuration/configure_graphics_advanced.ui
src/yuzu_cmd/config.cpp
src/yuzu_cmd/default_ini.h

This is no longer used by anything.

settings: remove pessimistic flushing

---

src/video_core/memory_manager.cpp

This fixes a possible race condition between cpu, nvservices and texture cache.

Memory manager: Fix possible softlock

---

src/input_common/input_engine.cpp

This wasn't supposed to be here, I must have forgotten to force push.

input_common: Revert debugging changes

---

src/core/hid/emulated_controller.cpp
src/core/hid/emulated_controller.h
src/core/hid/input_converter.cpp
src/core/hle/service/hid/controllers/npad.cpp
src/input_common/input_poller.cpp

Another regresión from previous commits. We shouldn't be requesting updates when fetching controller data. Instead do it on the function that updates every npad update.

core: hid: Update motion on a better place

---

src/video_core/renderer_opengl/gl_texture_cache.cpp
src/video_core/renderer_vulkan/vk_texture_cache.cpp
src/video_core/texture_cache/util.cpp

This fixes Donkey kong country's Sand world:

Texture Cache: Fix 3D ASTC textures

---

src/input_common/drivers/sdl_driver.cpp

I use a game controller that is technically comatible with HD Rumble (a DualSense), but Yuzu totally ignore the fact, and doesn’t emulate it other than using standard rumble (I may try to add proper support for it, but I’ll need to learn more about SDL and likely CPP, hoping I don’t have to having to generate the wave myself, like I did in a python prototype).
This change the amplitude of the rumble based upon the frequency. This allow to have some sort of feel for the frequency. It first have no change for frequency from 0 to 100 Hz, then lower linearly from 100 Hz to 600 Hz (Mario Odyssey in practice doesn’t go over 420).
Those parameter might be changed, but this still seems to provide better rumble.
I also increased the max duration of Rumble. There is an effect on the SMO scooter …

Attempt at improving HD Rumble emulation

---

src/video_core/buffer_cache/buffer_cache.h

We should check the regions marked as one type before marking them as modified of another type.

Swap order of checking/setting region modifications in the buffer_cache

---

src/video_core/renderer_vulkan/vk_master_semaphore.cpp
src/video_core/renderer_vulkan/vk_master_semaphore.h

As discussed in #10057 which originally implemented the fence fallback, waiting on the fence immediately might be slow. This PR moves the fence wait on a separate thread which mitigates the aforementioned performance loss.
Timeline
Old Fence
New Fence

vk_master_semaphore: Move fence wait on separate thread

---

src/video_core/vulkan_common/vulkan_device.cpp

[Fixed in newer mesa.](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/23156)

vulkan_device: Enable VK_KHR_push_descriptor on newer ANV

---

src/input_common/helpers/joycon_protocol/nfc.cpp

See also: https://github.com/yuzu-emu/yuzu/issues/8779

input_common: rename PAGE_SIZE to avoid conflict

---

src/input_common/drivers/virtual_amiibo.cpp

Minor mistake that breaks virtual amiibos

input_common: Fix virtual amiibos

---

src/video_core/renderer_vulkan/vk_master_semaphore.cpp

Should improve performance by a little bit

Remove timeline semaphore wait

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/uk.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2023-06-01)

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/overlay/InputOverlay.kt
src/android/app/src/main/res/layout/card_game.xml

Allows the buttons to reposition themselves if the window is resized.

Store button's position in the overlay as a percentage 

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/Settings.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/overlay/InputOverlay.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/overlay/InputOverlayDrawableButton.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/overlay/InputOverlayDrawableDpad.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/overlay/InputOverlayDrawableJoystick.kt
src/android/app/src/main/res/layout/dialog_overlay_adjust.xml
src/android/app/src/main/res/menu/menu_overlay_options.xml
src/android/app/src/main/res/values/strings.xml

Just had to enable the scaling logic and implement the required logic for opacity adjustment.

android: Enable overlay scale/opacity dialog

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/ImportExportSavesFragment.kt

@PabloG02 Pointed this out in the android support chat

android: Fix crash on importing invalid save

---

.github/ISSUE_TEMPLATE/bug_report.yml

Closes https://github.com/yuzu-emu/yuzu/issues/10546

issue_template: Add link to website, Getting Log Files

---

README.md

This adds Android to the sequence telling about the actively maintained builds.

Update README.md (Add Android at builds description)

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
src/android/app/src/main/res/layout/fragment_emulation.xml

A couple random `;` left behind and replacements for code that was deprecated in API 30 (the minimum of the app)

android: Replace deprecated and Java code

---

src/common/host_memory.cpp

Track the private anonymous placeholder mappings created by Unmap() and wherever possible, replace existing placeholders with larger ones instead of creating many small ones.
This helps with the buildup of mappings in /proc/YUZU_PID/maps after a longer gaming session, improving stability without having to increase vm.max_map_count to a ridiculous value. The amount of placeholder mappings will no longer outgrow the amount of actual memfd mappings in cases of high memory fragmentation.
In particular, I have observed the placeholder mappings getting out of control while playing ToTK – at some point, there were around 30k memfd mappings and 38k placeholders. With this patch, the placeholder amount is under control and ends up around 6-8k after a few hours.
This could be relevant to #10245 and …

host_memory: merge adjacent placeholder mappings on Linux

---

src/android/app/build.gradle.kts

Forgot to include these with the other deprecation stuff.

android: Resolve a couple Gradle warnings

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/applets/keyboard/ui/KeyboardDialogFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/Settings.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/view/SubmenuSetting.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsFragmentPresenter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
src/android/app/src/main/res/values/arrays.xml
src/android/app/src/main/res/values/strings.xml

Went over all of the in-app strings with @Schplee and made them follow sentence-case where applicable.
Additionally, settings for graphics API, and graphics debugging have been moved to the debug menu.

android: String and settings organization changes

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/LicenseAdapter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AboutFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/LicenseBottomSheetDialogFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/LicensesFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/License.kt
src/android/app/src/main/res/layout/dialog_license.xml
src/android/app/src/main/res/layout/fragment_about.xml
src/android/app/src/main/res/layout/fragment_licenses.xml
src/android/app/src/main/res/navigation/home_navigation.xml
src/android/app/src/main/res/values/strings.xml

Please let me know if I should add any more licenses now or in the future.

android: Add licenses page

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/views/FixedRatioSurfaceView.kt
src/android/app/src/main/res/layout/fragment_emulation.xml

Credit to the Skyline team for the `FixedRatioSurfaceView`.
Should help #10567

android: Use a custom view for changing emulation aspect ratio

---

src/android/app/build.gradle.kts

CI complained about this missing setting. Just checking if this makes android compile in CI

android: Set version code

---

.github/workflows/verify.yml
.gitmodules

Removes the release workflow for PR CI and fixes the libadrenotools submodule name

github/gitmodules: Misc fixes

---

src/audio_core/audio_core.cpp
src/audio_core/audio_core.h
src/common/settings.cpp
src/common/settings.h
src/core/core.cpp
src/core/core.h
src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
src/core/hle/service/nvnflinger/nvnflinger.cpp
src/yuzu/configuration/configure_graphics_advanced.cpp
src/yuzu/configuration/configure_graphics_advanced.h
src/yuzu/configuration/configure_graphics_advanced.ui

nvnflinger: allow locking framerate during video playback

---

src/yuzu/configuration/config.cpp

qt: persist framerate sync option

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
src/android/app/src/main/jni/native.cpp
src/video_core/renderer_vulkan/vk_blit_screen.cpp
src/video_core/renderer_vulkan/vk_swapchain.cpp

android: Fix screen orientation & blurriness.

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
src/android/app/src/main/jni/native.cpp
src/android/app/src/main/res/drawable/ic_system_update_alt.xml
src/android/app/src/main/res/values/strings.xml
src/core/file_sys/submission_package.h

Allows installing game updates and DLC on Android. There's no way to check if the game has an update other than by checking in-game. Hopefully, once the per-game info is completed, you will be able to confirm which updates you have installed.

android: Add update and DLC support

---

.codespellrc
src/android/app/src/main/res/values-de/strings.xml
src/android/app/src/main/res/values-es/strings.xml
src/android/app/src/main/res/values-fr/strings.xml
src/android/app/src/main/res/values-it/strings.xml
src/android/app/src/main/res/values-ja/strings.xml
src/android/app/src/main/res/values-ko/strings.xml
src/android/app/src/main/res/values-nb/strings.xml
src/android/app/src/main/res/values-pl/strings.xml
src/android/app/src/main/res/values-pt-rBR/strings.xml
src/android/app/src/main/res/values-pt-rPT/strings.xml
src/android/app/src/main/res/values-ru/strings.xml
src/android/app/src/main/res/values-uk/strings.xml
src/android/app/src/main/res/values-zh-rCN/strings.xml
src/android/app/src/main/res/values-zh-rTW/strings.xml

I tested German on my device and it worked fine.
We really need to set up an automatic process for this in the future though.

android: Add translation files manually

---

src/video_core/texture_cache/image_info.cpp

Helps resolution mods to work correctly in Tears of the Kingdom when using the scaler. Needs testing to ensure it hasn't caused any issues in other games.

image_info: adjust rescale thresholds and refactor constant use

---

src/android/app/build.gradle.kts
src/android/app/src/main/AndroidManifest.xml
src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/GameAdapter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
src/android/app/src/main/res/layout/activity_emulation.xml
src/android/app/src/main/res/navigation/emulation_navigation.xml
src/android/app/src/main/res/navigation/home_navigation.xml
src/android/build.gradle.kts

Some work I forgot to merge since I got caught up with the launch

android: Adapt EmulationActivity to navigation component

---

src/video_core/renderer_vulkan/vk_pipeline_cache.cpp

renderer_vulkan: propagate conditional barrier support

---

src/video_core/vulkan_common/vulkan_device.cpp

ARM briefly added support for this in their driver and then removed it shortly after. The support in drivers that report it is broken (and probably why they removed it), so we shouldn't use it.

vulkan_device: disable extended_dynamic_state2 on ARM drivers

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/BooleanSetting.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/StringSetting.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/view/HeaderSetting.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/view/StringSingleChoiceSetting.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsAdapter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsFragmentPresenter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/viewholder/SingleChoiceViewHolder.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/utils/SettingsFile.kt
src/android/app/src/main/res/layout/list_item_setting_switch.xml
src/android/app/src/main/res/layout/list_item_settings_header.xml
src/android/app/src/main/res/values/arrays.xml
src/android/app/src/main/res/values/strings.xml

Exposes settings for CPU debugging, a combined fastmem toggle, and an audio engine switcher

android: Expose settings

---

src/video_core/buffer_cache/buffer_cache.h
src/video_core/renderer_vulkan/vk_buffer_cache.cpp

Synchronize vertex buffer even when it doesn't require binding

---

src/video_core/engines/draw_manager.cpp

video_core: drawtexture support upscale

---

vcpkg.json

Fixes for qt5 CVE-2023-33285 / CVE-2023-34410

externals: Update vcpkg to 2023.06.17

---

src/video_core/texture_cache/texture_cache.h
src/video_core/texture_cache/texture_cache_base.h

Close #9709
1. Fix Fire Emblem Engage  vulkan device loss in handle mode.
2. Fix SPONGEBOB SQUAREPANTS THE COSMIC SHAKE Abnormal color and shadow.

video_core: add samples check when find render target

---

externals/nx_tzdb/CMakeLists.txt

Includes a fix for the Apple date utility.
Closes #10848

externals: Update tzdb_to_nx

---

src/android/app/src/main/jni/native.cpp

Makes the applied settings show up in the log file

android: Log settings

---

src/core/file_sys/vfs_real.cpp
src/core/file_sys/vfs_real.h

Fixes regression caused by #10729

vfs_real: lock concurrent accesses

---

src/common/thread.h
src/core/hle/service/nvnflinger/nvnflinger.cpp
src/core/hle/service/nvnflinger/nvnflinger.h
src/core/hle/service/server_manager.cpp
src/core/hle/service/server_manager.h
src/video_core/renderer_vulkan/vk_master_semaphore.cpp
src/video_core/renderer_vulkan/vk_master_semaphore.h
src/yuzu/bootmanager.cpp
src/yuzu/bootmanager.h

general: remove atomic signal and wait

---

src/yuzu/configuration/configure_general.cpp
src/yuzu/main.cpp

Seems like clang format didn't catch these on #9663

yuzu: Fix clang format

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/uk.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2023-07-01)

---

src/common/ring_buffer.h
src/common/scratch_buffer.h
src/core/hle/service/audio/audin_u.cpp
src/core/hle/service/audio/audout_u.cpp
src/core/hle/service/audio/audren_u.cpp
src/core/hle/service/audio/hwopus.cpp
src/core/hle/service/nvdrv/nvdrv_interface.cpp
src/core/hle/service/nvdrv/nvdrv_interface.h
src/core/hle/service/nvnflinger/parcel.h
src/video_core/engines/maxwell_dma.cpp
src/video_core/host1x/codecs/codec.cpp
src/video_core/host1x/codecs/h264.cpp
src/video_core/host1x/codecs/h264.h
src/video_core/host1x/codecs/vp8.cpp
src/video_core/host1x/codecs/vp8.h
src/video_core/host1x/codecs/vp9.cpp
src/video_core/host1x/codecs/vp9.h
src/video_core/host1x/codecs/vp9_types.h

See commits, these were changes I made while working on #10966

general: Misc changes that did not deserve their own PRs

---

src/video_core/texture_cache/texture_cache.h

This reverts commit 1fc47361a12afd91d8ea0b76378e0b3d4feb93a6. This is known to cause device losses in many games.

Revert "texture_cache: Fix incorrect logic for AccelerateDMA"

---

src/core/file_sys/fsmitm_romfsbuild.cpp

Cuts romfs build time in half again. (based on findings from #10692)

fsmitm_romfsbuild: avoid full path lookups

---

src/core/hle/kernel/k_thread.h
src/core/hle/kernel/svc/svc_ipc.cpp
src/core/hle/kernel/svc/svc_synchronization.cpp

Synchronize implementations of svcReplyAndReceive and svcWaitSynchronization

kernel: Synchronize

---

src/core/file_sys/vfs_real.cpp

vfs_real: use open file size for getting size

---

CMakeLists.txt

externals: Update sdl2 to 2.28.1

---

src/yuzu/main.cpp

The increased buffer size means that that progress bar size has to be adjusted
Fixes #10997

main: Fix install progress calculation

---

src/core/arm/arm_interface.cpp

arm_interface: correct breakpoint rewind condition

---

src/core/hle/service/am/am.cpp

Mark SetIdleTimeDetectionExtension logging as debug

---

src/core/hle/service/sockets/nsd.cpp
src/core/hle/service/sockets/nsd.h

Fixes #11108
Note: there are still rendering issues, but they are unrelated to this PR

nsd: add GetApplicationServerEnvironmentType

---

src/core/hle/service/acc/acc.cpp
src/core/hle/service/glue/ectx.cpp
src/core/hle/service/glue/ectx.h
src/core/hle/service/sockets/bsd.cpp
src/core/hle/service/sockets/nsd.cpp
src/core/hle/service/sockets/nsd.h
src/core/hle/service/sockets/sfdnsres.cpp
src/core/hle/service/sockets/sfdnsres.h
src/core/hle/service/sockets/sockets_translate.cpp
src/core/hle/service/sockets/sockets_translate.h

core: implement GetGaiStringErrorRequest, IContextRegistrar

---

src/core/memory.cpp

memory: check page against address space size

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/uk.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2023-08-01)

---

src/core/hle/service/olsc/olsc.cpp

I couldn't find the names for functions of ITransferTaskListController. For now it simply creates the interfaces needed.

service: olsc: Implement IOlscServiceForSystemService ITransferTaskListController interfaces for QLaunch

---

src/core/hle/service/pctl/pctl_module.cpp

I made a wrong assumption. Correct this data.

service: pctl: Partially revert 11221

---

src/yuzu/game_list.cpp

Now I can just type `0001000` and easily find qlaunch.

Allow searching by a substring of the title ID

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/SetupAdapter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/SetupFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/HomeViewModel.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/SetupPage.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/ViewUtils.kt
src/android/app/src/main/res/layout-w600dp/fragment_setup.xml
src/android/app/src/main/res/layout-w600dp/page_setup.xml
src/android/app/src/main/res/layout/fragment_setup.xml
src/android/app/src/main/res/layout/page_setup.xml
src/android/app/src/main/res/values/strings.xml

+ Completion indicator for each step
+ Adjusted step fragment layout padding so that the viewpager can reach into system insets
+ Auto page forward on step completion

android: Setup additions

---

src/core/debugger/gdbstub.cpp

Applies solution for instruction bytes from https://github.com/yuzu-emu/yuzu/issues/11154#issuecomment-1650216473

gdbstub: fixup replaced instruction bytes in memory reads

---

CMakeLists.txt
CMakeModules/DownloadExternals.cmake
src/video_core/vulkan_common/vulkan_instance.cpp
src/video_core/vulkan_common/vulkan_library.cpp
src/yuzu/CMakeLists.txt

The main addition in this PR  is an automated copy script for MoltenVK. It allows for the launch of some simple games on my Mac Pro. However, there are still quite a few issues that need to be resolved.

Add macos moltenvk bundle, Add copy moltevk dylib script

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/GameHelper.kt

Searches 3 subfolders deep. Seems like a reasonable default but it's not configurable at the moment.

android: Search game directory recursively

---

src/yuzu/game_list_worker.cpp

This was a regression from https://github.com/yuzu-emu/yuzu/pull/1837.
Fixes https://github.com/yuzu-emu/yuzu/issues/1938.

game_list_worker: Display correct size for NAX games

---

src/android/app/src/main/jni/native.cpp

android: jni: ensure NCAs from loaded filepath are registered in manual content provider

---

src/core/file_sys/registered_cache.cpp

The current VFS code has no realistic mechanism for supporting mapping these to the base CNMT, so we'll just support creating and removing fake entries inside yuzu_meta with the raw NCA install method. Fixes #8217

registered_cache: create fake CNMT entries for program updates of multiprogram applications

---

src/core/hle/service/filesystem/filesystem.cpp

Allows Grid Autosport to boot.
Fixes https://github.com/yuzu-emu/yuzu/issues/8287.

filesystem: Return correct error for RenameFile when dest_path already exists

---

src/yuzu/configuration/shared_widget.cpp

ui: Fixed inverted controls on ReverseSlider widgets

---

src/audio_core/sink/cubeb_sink.cpp
src/audio_core/sink/sink_details.cpp

audio: allow more latency in cubeb initialization

---

src/core/hle/service/sockets/nsd.cpp
src/core/hle/service/sockets/sfdnsres.cpp

sfdnsres: ensure lp1 is not resolved

---

src/shader_recompiler/backend/glsl/emit_glsl_image.cpp
src/shader_recompiler/backend/spirv/emit_spirv_image.cpp

shader_recompiler: fix emulation of 3D textureGrad

---

src/CMakeLists.txt

This wasn't taking effect for arm64.

general: make -fwrapv generic to all architectures

---

src/video_core/engines/maxwell_3d.cpp

This considerably improves the performance of Bayonetta 3.

Maxwell3D: Improve Index buffer size estimation.

---

dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/uk.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2023-09-01)

---

src/yuzu/main.cpp

This improves the responsiveness of the dialog when dumping for games like SSBU which only have a single file in their romfs.

qt: measure romfs dump completion by bytes read

---

src/CMakeLists.txt
src/audio_core/audio_event.cpp
src/common/CMakeLists.txt
src/core/hle/kernel/k_capabilities.cpp
src/core/hle/service/nvdrv/core/nvmap.cpp
src/core/hle/service/ssl/ssl_backend_schannel.cpp
src/dedicated_room/yuzu_room.cpp
src/input_common/CMakeLists.txt
src/network/room.cpp
src/shader_recompiler/CMakeLists.txt
src/tests/common/ring_buffer.cpp
src/yuzu/configuration/shared_widget.cpp
src/yuzu_cmd/yuzu.cpp

msvc: set warning level to /W4 globally

---

src/android/app/src/main/jni/native.cpp
src/core/core.cpp
src/core/core.h
src/core/hle/service/am/am.cpp
src/core/hle/service/am/am.h
src/yuzu/game_list.cpp
src/yuzu/game_list.h
src/yuzu/main.cpp
src/yuzu/main.h
src/yuzu_cmd/yuzu.cpp

Fixes language selection in Super Mario 3D All-Stars
Fixes https://github.com/yuzu-emu/yuzu/issues/8210.
Fixes https://github.com/yuzu-emu/yuzu/issues/8850.
Should fix https://github.com/yuzu-emu/yuzu/issues/10385.

am: Implement UserChannel parameters

---

src/core/file_sys/nca_metadata.cpp
src/core/file_sys/nca_metadata.h
src/core/file_sys/registered_cache.cpp
src/core/file_sys/registered_cache.h
src/yuzu/main.cpp
src/yuzu/main.h
src/yuzu/main.ui

Also fixes a dumb issue with how updates for multi-program applications were being installed that caused hash verification failure.

qt: add verification for installed contents

---

src/video_core/texture_cache/texture_cache.h

AIR creates 2 different render targets at the same address, a 720p and a 1080p one. The 1080p one is created first, but never used beyond the first frame, only the 720p one is. When we look for the present framebuffer image, we just take the very first one that matches. This is likely fine in 99.9% of situations where there will only be a single valid framebuffer image for a given CPU address, but in AIR's case it has 2. 
Since the 1080p image is created first, when iterating through the map looking for framebuffers, that always gets checked first and is returned early. Since it's never updated though, only ever a black image, leading to the horrible flickering between one correctly rendering image, and a black image in AIR.
I'm sure there's a better way to do this, but for now this stops …

Look for the most recently modified image for present

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/HomeSettingAdapter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/Settings.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/view/SubmenuSetting.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsActivity.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsFragmentPresenter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/IndeterminateProgressDialogFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/SearchFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/SettingsSearchFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/SetupFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/EmulationViewModel.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/GamesViewModel.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/HomeSetting.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/HomeViewModel.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/SettingsViewModel.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/TaskViewModel.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/GamesFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
src/android/app/src/main/res/navigation/home_navigation.xml
src/android/app/src/main/res/navigation/settings_navigation.xml

StateFlows are the Kotlin standard way of updating UI state and have extra features that we could take advantage of in the future.

android: Use StateFlow instead of LiveData

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/GameAdapter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/GameIconUtils.kt
src/android/app/src/main/res/drawable/shortcut.xml
src/android/app/src/main/res/values/dimens.xml

Fixes issue where the shortcut icon would appear cropped on certain devices

android: Use resource as shortcut intermediary

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/IndeterminateProgressDialogFragment.kt

Before the viewLifecycleOwner wasn't ready and would cause a crash

android: Collect task state once view is created

---

src/core/file_sys/registered_cache.cpp

registered_cache: correct file deletion case

---

src/core/hle/service/aoc/aoc_u.cpp

aoc: stub purchase info calls

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/ImportExportSavesFragment.kt
src/android/app/src/main/res/values-de/strings.xml
src/android/app/src/main/res/values-es/strings.xml
src/android/app/src/main/res/values-fr/strings.xml
src/android/app/src/main/res/values-it/strings.xml
src/android/app/src/main/res/values-ja/strings.xml
src/android/app/src/main/res/values-ko/strings.xml
src/android/app/src/main/res/values-nb/strings.xml
src/android/app/src/main/res/values-pl/strings.xml
src/android/app/src/main/res/values-pt-rBR/strings.xml
src/android/app/src/main/res/values-pt-rPT/strings.xml
src/android/app/src/main/res/values-ru/strings.xml
src/android/app/src/main/res/values-uk/strings.xml
src/android/app/src/main/res/values-zh-rCN/strings.xml
src/android/app/src/main/res/values-zh-rTW/strings.xml
src/android/app/src/main/res/values/strings.xml

Exporting still won't be allowed on an empty save directory.

android: Allow save imports always

---

src/android/app/build.gradle.kts

Fixes an issue with the input overlay on certain devices where the controls would appear offscreen.
Credits to @ronaldgameking for testing
Closes #11391

android: Update androidx window library to 1.2.0-beta03

---

src/video_core/renderer_vulkan/vk_texture_cache.cpp

This was originally introduced in https://github.com/yuzu-emu/yuzu/pull/5363. The problem was that UNORM views of SRGB formats could not be attached as storage images in shaders, with the solution being creating the image as UNORM ~~and having the view be SRGB.~~
However this doesn't always work as intended. When the image is used directly without the aid of the view, for example when image is target of vkCmdResolveImage, the colors end up wrong since the colorspace has changed. To fix this, we can do a partial revert of that part and limit the srgb block only when transcoding compressed formats in the GPU.
Fixes https://github.com/yuzu-emu/yuzu/issues/11010

vk_texture_cache: Limit srgb block to transcoding only

---

src/core/hle/service/filesystem/fsp_srv.cpp

fsp-srv: add GetFileSystemAttribute

---

src/core/hle/service/am/applets/applet_mii_edit.cpp
src/core/hle/service/mii/mii_database_manager.cpp
src/core/hle/service/mii/types/char_info.cpp
src/core/hle/service/mii/types/core_data.cpp
src/core/hle/service/nfc/common/device.cpp

This PR fixes a couple of remaining bugs from the mii implementation.
- Creating more than one mii from Mario Kart
- Incomplete mii name from amiibo
- Eyebrows too high

service: mii: Fix reported bugs

---

src/core/core_timing.cpp
src/core/core_timing.h
vcpkg.json

Also attempt to reduce sifting.
Thanks to @gidoly for performance testing.

core_timing: Replace queue with a fibonacci heap

---

src/video_core/query_cache/bank_base.h
src/video_core/renderer_vulkan/vk_query_cache.cpp

Fixes the memory leaks caused by the new query cache

Query Cache: Fix memory leak.

---

dist/languages/ar.ts
dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/hu.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2023-10-01)

---

src/yuzu/main.cpp

Fixes #11654 by adding an additional menu item to dump the HTML document storages.

qt: add additional romfs dump targets

---

src/core/hle/kernel/k_page_table.cpp

Current KPageTable destroys the container of page table entries at the end of Finalize. Therefore, there is no need to remove each page table entry on a one-by-one basis--an operation that can take over a second even on a fast desktop processor. We only have to remove mappings from the fastmem arena and then destroy the container.
This makes game shutdown super fast and nearly instant again.

k_page_table: skip page table clearing on finalization

---

src/video_core/vulkan_common/vulkan_device.cpp

I encountered a bug in Bravely Default 2 around its water rendering, where it flickers in and out every few frames. After some debugging I found it to be *indirectly* caused by push descriptor. If the number of bindings for a draw exceeds the device's push descriptor maximum, we fallback to using regular descriptor binding, otherwise push descriptor is used. There seems to be either a hardware bug or a long-standing driver bug (no driver I've tested seems to fix it, and newer architectures are fine), where switching between descriptor binding and push descriptor will break the descriptors, and causes the flickering.
Confirmed via Bravely Default 2 to affect Pascal and Maxwell, so this PR disables push descriptor for architectures <= Pascal. This PR also re-works the architecture detection …

Disable push descriptor for Pascal and older nVidia architectures

---

src/core/file_sys/program_metadata.cpp
src/core/file_sys/program_metadata.h
src/core/loader/deconstructed_rom_directory.cpp

loader: don't reassign program ID on npdm reparse

---

src/android/app/src/main/jni/native.cpp
src/video_core/renderer_base.h
src/video_core/renderer_vulkan/renderer_vulkan.h
src/video_core/renderer_vulkan/vk_present_manager.cpp
src/video_core/renderer_vulkan/vk_present_manager.h
src/video_core/vulkan_common/vulkan_wrapper.h

This should help control crashing related to surface recreation  on Android.

vk_present_manager: recreate surface on any surface loss

---

src/video_core/texture_cache/format_lookup_table.cpp

add Z32, FLOAT, UINT, UINT, UINT, LINEAR to format lookup table

---

src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/k_transfer_memory.cpp
src/core/hle/kernel/k_transfer_memory.h
src/core/hle/kernel/svc/svc_transfer_memory.cpp

Somehow this was not added yet.

kernel: implement transfer memory

---

src/yuzu/util/util.cpp

Previous implementation will only save an icon file with the highest resolution possible. This PR will write 7 different layers each one with a different resolution. This improves quite a bit the shortcut quality on windows.

yuzu: Save multiple resolutions per icon

---

src/core/hle/service/caps/caps_a.cpp

service: caps: Remove ambiguous call

---

src/common/elf.h
src/core/hle/service/jit/jit_context.cpp

jit: add support for relr-type relocations

---

src/core/hle/kernel/k_page_table.cpp

k_page_table: add missing page group open when locking memory

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/DriverManagerFragment.kt

The driver was assumed to be installed at this point before I made a refactor. Now we just check if the copy operation was successful and delete the file if it fails.

android: Fix incorrect assumption for driver installation validation

---

src/common/polyfill_thread.h

Based on warnings from build log of #11761 (needs other changes to fully fix). Qualify std::move calls in accordance with clang warning (system headers have this diagnostic disabled); also replace `std::move` with `std::forward` where appropriate.

common/polyfill_thread: use std::forward where appropriate, qualify std::move calls

---

src/video_core/engines/draw_manager.cpp
src/video_core/engines/draw_manager.h

Needed by Super Meat Boy for rendering to its present frame. Fixes the game rendering a black screen.

Implement vertex array first and subsequent draws

---

src/core/hle/service/mii/types/core_data.cpp

I wish sometimes users reported to devs instead of a random reddit. Fixes "Find Mii" stage on SSBU if you have no custom mii.

service: mii: Create random mii with name

---

.codespellrc
src/core/debugger/gdbstub.cpp
src/core/hle/kernel/init/init_slab_setup.cpp
src/core/hle/kernel/initial_process.h
src/core/hle/kernel/k_memory_block.h
src/core/hle/kernel/k_memory_block_manager.cpp
src/core/hle/kernel/k_memory_block_manager.h
src/core/hle/kernel/k_memory_layout.h
src/core/hle/kernel/k_memory_manager.cpp
src/core/hle/kernel/k_memory_region_type.h
src/core/hle/kernel/k_page_group.h
src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/svc/svc_memory.cpp
src/core/hle/kernel/svc_types.h
src/core/hle/service/nvnflinger/fb_share_buffer_manager.cpp

Most notably, implements support for the new PermissionLocked attribute used for RELRO relocations.

kernel: update for 17.0.0

---

src/core/memory/cheat_engine.cpp

Currently any cheat with a name longer than 64 characters will fail. We should be clamping the name instead of failing.

cheats: Clamp cheat names without failing

---

externals/CMakeLists.txt
externals/stb/stb_image_write.cpp
externals/stb/stb_image_write.h
src/core/hle/service/caps/caps.cpp
src/core/hle/service/caps/caps_manager.cpp
src/core/hle/service/caps/caps_manager.h
src/core/hle/service/caps/caps_ss.cpp
src/core/hle/service/caps/caps_ss.h
src/core/hle/service/caps/caps_su.cpp
src/core/hle/service/caps/caps_su.h
src/core/hle/service/caps/caps_types.h

Used by SSBU and probably more games. Allows to save screenshot captures from within games. Album screenshot editing is still not working.

service: caps: Implement SaveScreenShotEx0 and variants

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
src/android/app/src/main/res/layout/card_home_option.xml

Below 600dp - unchanged
Above 600dp -

android: Break home settings into grid with large screens

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/model/GamesViewModel.kt

Deserializing games from the cache in shared preferences was done on the main thread and could cause a stutter on startup.

android: Move game deserialization to another thread

---

src/core/hle/service/am/am.cpp
src/core/hle/service/am/am.h

service: am: Add support for LLE Software Keyboard Applet

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/AppletAdapter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/CabinetLauncherDialogAdapter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AppletLauncherFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/CabinetLauncherDialogFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/MessageDialogFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/Applet.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/Game.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/DirectoryInitialization.kt
src/android/app/src/main/jni/native.cpp
src/android/app/src/main/jni/native.h
src/android/app/src/main/res/drawable/ic_album.xml
src/android/app/src/main/res/drawable/ic_applet.xml
src/android/app/src/main/res/drawable/ic_edit.xml
src/android/app/src/main/res/drawable/ic_mii.xml
src/android/app/src/main/res/drawable/ic_refresh.xml
src/android/app/src/main/res/drawable/ic_restore.xml
src/android/app/src/main/res/layout/card_applet_option.xml
src/android/app/src/main/res/layout/dialog_list.xml
src/android/app/src/main/res/layout/dialog_list_item.xml
src/android/app/src/main/res/layout/fragment_applet_launcher.xml
src/android/app/src/main/res/navigation/home_navigation.xml
src/android/app/src/main/res/values/strings.xml

Allows you run any of our supported system applets so long as you have firmware and keys installed
List item - 
Launcher page - 
Cabinet options -

android: Applet launcher UI

---

dist/languages/ar.ts
dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/hu.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/uk.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2023-11-01)

---

.ci/scripts/android/build.sh
.ci/scripts/android/upload.sh

Credits to the Citra team for the CI code

ci: android: Use signing key if available

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
src/android/app/src/main/res/values/strings.xml

Reorganize each option so that the most used items and highlighted features are on top
Advanced Settings
GPU driver manager
Applet launcher
Manage yuzu data
Select games folder
Share debug logs
Open yuzu folder
Theme and color
About

android: Reorganize settings tab

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/YuzuApplication.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/Log.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/MemoryUtil.kt

Logs more system information and includes a fix for the low memory warning appearing when it shouldn't

android: Log more system information

---

src/core/hle/service/hid/hid.cpp

Spammed by wario ware. Makes logs impossible to read.

service: hid: Silence EnableUnintendedHomeButtonInputProtection

---

src/audio_core/adsp/apps/opus/opus_decoder.cpp
src/audio_core/opus/decoder_manager.cpp

Authored by @Kelebek1, not me.
Fixes #11945

opus: Allow 0 stereo count

---

src/core/hle/service/am/applets/applets.h
src/yuzu/main.cpp

Keep the recently played list clear of applets since these have their dedicated button.
Closes: #11949

yuzu: Only store games in the recently played list

---

src/core/hle/service/nvdrv/devices/ioctl_serialization.h
src/core/hle/service/nvdrv/devices/nvdevice.h
src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
src/core/hle/service/nvdrv/devices/nvhost_gpu.h
src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
src/core/hle/service/nvdrv/devices/nvhost_nvjpg.cpp
src/core/hle/service/nvdrv/devices/nvhost_nvjpg.h
src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
src/core/hle/service/nvdrv/devices/nvmap.cpp
src/core/hle/service/nvdrv/devices/nvmap.h
src/core/hle/service/nvnflinger/fb_share_buffer_manager.cpp

Fixes buffer usage issues described in https://github.com/yuzu-emu/yuzu/issues/11871#issuecomment-1777323027

nvdrv: add ioctl command serialization wrapper

---

src/core/hle/service/nvnflinger/buffer_transform_flags.h
src/video_core/renderer_vulkan/vk_blit_screen.cpp
src/video_core/renderer_vulkan/vk_fsr.cpp
src/video_core/renderer_vulkan/vk_fsr.h

When combined with #11894, fixes #7382
TODO:

renderer_vulkan: fix cropping for presentation

---

src/core/debugger/gdbstub.cpp

This fixes a regression from #11326 where the load address would not be set correctly for homebrew.

gdbstub: read module information from memory layout

---

src/core/hle/kernel/k_capabilities.cpp

Fixes booting hbl after #11914

k_capabilities: ignore map region when KTrace is disabled

---

src/android/app/src/main/res/layout/fragment_emulation.xml

Also let the style control the text size

android: Add drop shadow to FPS counter

---

src/core/memory.cpp
src/video_core/fence_manager.h
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_vulkan/renderer_vulkan.cpp
src/video_core/renderer_vulkan/vk_rasterizer.cpp
src/video_core/renderer_vulkan/vk_rasterizer.h

This avoids the constant need to lock the scheduler everywhere.

Revert PR #11806 and do a proper fix to the memory handling.

---

src/core/hle/service/friend/friend.cpp

Stub used by Super Bomberman R 2

Stub CheckBlockedUserListAvailability for Super Bomberman R 2

---

src/video_core/renderer_vulkan/vk_texture_cache.cpp
src/video_core/renderer_vulkan/vk_texture_cache.h

vk_texture_cache: add workaround for nullDescriptor on Mali

---

src/video_core/renderer_opengl/gl_device.cpp
src/video_core/vulkan_common/vulkan_device.cpp

Also sets OpenGL driver names to a non-capitalized version.

vulkan_device: add names for more driverID enumeration values

---

src/core/hle/service/hid/controllers/touchscreen.cpp
src/core/hle/service/hid/controllers/touchscreen.h
src/core/hle/service/hid/hid_server.cpp
src/core/hle/service/hid/hid_server.h

Fixed this by implementing `SetTouchscreenDimensions`

Fixed controller applet crashing when on FW17+

---

src/core/hle/service/set/set_sys.cpp

Fixes https://github.com/yuzu-emu/yuzu/pull/12194#issuecomment-1828500089

set: don't load version nca with null romfs

---

externals/CMakeLists.txt
src/common/CMakeLists.txt
src/common/linux/gamemode.cpp

general: conditionally compile gamemode on linux only

---

dist/languages/ar.ts
dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/hu.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/uk.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2023-12-01)

---

src/common/host_memory.cpp

host_memory: unbreak build on FreeBSD x86_64

---

src/video_core/renderer_vulkan/vk_texture_cache.cpp
src/video_core/renderer_vulkan/vk_texture_cache.h
src/video_core/texture_cache/texture_cache.h

texture_cache: use pedantic type names

---

src/video_core/host1x/ffmpeg/ffmpeg.cpp

Resolves Clang -Wdeprecated-declarations warning from interlaced_frame

codec: Update to use av frame flags

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AddGameFolderDialogFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/SetupFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/GamesViewModel.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/HomeViewModel.kt

Fixes broken game directory selection setup flow

android: Listen for directory selection in viewmodel

---

src/core/CMakeLists.txt
src/core/hle/kernel/k_client_port.cpp
src/core/hle/kernel/k_client_port.h
src/core/hle/kernel/k_light_client_session.cpp
src/core/hle/kernel/k_light_client_session.h
src/core/hle/kernel/k_light_server_session.cpp
src/core/hle/kernel/k_light_server_session.h
src/core/hle/kernel/k_light_session.cpp
src/core/hle/kernel/k_light_session.h
src/core/hle/kernel/k_port.cpp
src/core/hle/kernel/k_port.h
src/core/hle/kernel/k_server_port.cpp
src/core/hle/kernel/k_server_port.h
src/core/hle/kernel/k_thread.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/svc/svc_light_ipc.cpp
src/core/hle/kernel/svc/svc_port.cpp
src/core/hle/kernel/svc/svc_session.cpp

kernel: implement light IPC

---

src/core/hle/kernel/k_client_session.cpp
src/core/hle/kernel/k_client_session.h
src/core/hle/kernel/k_server_session.cpp
src/core/hle/kernel/k_session.h
src/core/hle/kernel/svc/svc_ipc.cpp
src/core/hle/service/sm/sm.cpp

Adds support for:
- SendSyncRequestWithUserBuffer
- SendAsyncRequestWithUserBuffer
- ReplyAndReceiveWithUserBuffer

kernel: implement remaining IPC syscalls

---

src/core/hle/kernel/physical_core.cpp

kernel: fix single core

---

src/core/hle/service/sm/sm.cpp
src/core/hle/service/sm/sm.h

Arguments no longer stable sorted by alignment.

sm:: fix tipc deserialization

---

src/yuzu/configuration/configure_debug.ui

configure_debug: Fix small typo

---

src/core/hle/service/ssl/ssl.cpp

Incredibly silly issue.
Regressed by #11093
Fixes #12371

ssl: fix output byte buffer size issue

---

src/android/app/build.gradle.kts
src/core/CMakeLists.txt
src/core/arm/nce/arm_nce.cpp
src/core/arm/nce/arm_nce.h
src/core/arm/nce/arm_nce.s
src/core/arm/nce/arm_nce_asm_definitions.h
src/core/arm/nce/interpreter_visitor.cpp
src/core/arm/nce/interpreter_visitor.h
src/core/arm/nce/visitor_base.h

This allows Paper Mario: The Origami King to go in game with NCE. This is the most outsized effort I think I have ever made to fix a single game, with an almost 4000 line delta. The game doesn't even render correctly anyway, so it almost feels not worth the effort.
Marked as draft due to conflicts with #12236, which should be merged first.

nce: implement instruction emulation for misaligned memory accesses

---

src/video_core/renderer_opengl/gl_buffer_cache.cpp

gl_buffer_cache: Fix tfb binding typo

---

src/tests/video_core/memory_tracker.cpp
src/video_core/buffer_cache/word_manager.h
src/video_core/rasterizer_accelerated.cpp
src/video_core/rasterizer_accelerated.h
src/video_core/rasterizer_interface.h
src/video_core/shader_cache.cpp
src/video_core/texture_cache/texture_cache.h

Reverts yuzu-emu/yuzu#12344
Fixes #12379, based on https://github.com/yuzu-emu/yuzu/issues/12379#issuecomment-1859320954

Revert "video_core: use interval map for page count tracking"

---

src/core/arm/nce/arm_nce.cpp
src/core/arm/nce/interpreter_visitor.cpp

nce: fix read size in simd immediate emulation

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/GamesFragment.kt

android: Fix "No games found" text appearing on load

---

src/shader_recompiler/ir_opt/constant_propagation_pass.cpp

These are fetched using GetThroughCast, where the cast is a BitCastU32F32. If the fetch finds that the value is an immediate, then it just returns the immediate - which is u32, not f32, but the op requires f32. Convert these to f32 before processing to avoid a shader validation error.
Fixes #11875 
Fixes #11906

shader_recompiler: ensure derivatives for textureGrad are f32

---

src/common/ring_buffer.h
src/yuzu/main.h

See citra-emu/citra#7239 for more details.
Small commits here and there that dont deserve their own PR

Port citra-emu/citra#7239: "common: Miscellaneous cleanups"

---

src/core/hle/kernel/k_handle_table.h
src/core/hle/kernel/k_process.h
src/core/hle/kernel/k_server_session.cpp
src/core/hle/service/am/am.cpp
src/core/hle/service/audio/audren_u.cpp
src/core/hle/service/audio/hwopus.cpp
src/core/hle/service/hid/hid_server.cpp
src/core/hle/service/hid/hidbus.cpp
src/core/hle/service/hid/irs.cpp
src/core/hle/service/hle_ipc.cpp
src/core/hle/service/hle_ipc.h
src/core/hle/service/jit/jit.cpp
src/core/hle/service/ro/ro.cpp
src/core/hle/service/service.cpp

 service: fetch objects from the client handle table 

---

src/shader_recompiler/backend/spirv/spirv_emit_context.cpp

Fixes #12462
Fixes #12483
Fixes #7390
RDR has a shader which has clip distance stores indicated in the omap, but only uses indexed stores to clip distances, causing us to declare a clip distance array of size zero. This was regressed by #12403 and is illegal SPIR-V, which causes some drivers to crash on compilation. Instead, we should create an array of as many clip distances as the driver will support, up to a maximum of 8. On Mali the number of clip distances is 0, on all other drivers I know of it is 8.
This reintroduces the original problem that #12403 was trying to fix. To deal with that, I now declare a default value for the clip distances array containing constant 0 values. This solves the problem of having undefined values on the output, so radv doesn't have problems with it any …

shader_recompiler: use default value for clip distances array

---

dist/languages/ar.ts
dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/hu.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/uk.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2024-01-01)

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/overlay/InputOverlay.kt

Was using the wrong key previously

android: Fix dpad position saving

---

src/core/hle/service/hid/hid_system_server.cpp
src/core/hle/service/hid/hid_system_server.h

Since I will be doing a lot of hid changes in the next couple of weeks I want to avoid creating more merge conflicts. So I put here the remaining stubs needed by QLaunch.

service: hid: Add functions needed by QLaunch

---

src/core/hle/service/hid/hid_server.cpp
src/core/hle/service/hid/hid_system_server.cpp
src/core/hle/service/hid/hid_system_server.h
src/hid_core/resources/npad/npad.cpp
src/hid_core/resources/npad/npad.h

We already emulate these functions. Adding the interface is practically free at this point.

service: hid: Hook interface implementations

---

.ci/scripts/format/script.sh

Fixes mainline CI and https://github.com/yuzu-emu/yuzu/pull/12622#issuecomment-1885053028 (git grep doesn't recurse into submodules)

ci: fix format task

---

.ci/yuzu-mainline-step2.yml

ci: remove format dep from mainline step2

---

src/core/hle/service/nvnflinger/nvnflinger.cpp
src/core/hle/service/nvnflinger/nvnflinger.h
src/core/hle/service/vi/display/vi_display.cpp
src/core/hle/service/vi/display/vi_display.h
src/core/hle/service/vi/layer/vi_layer.h
src/core/hle/service/vi/vi.cpp

Fixes #12697 (both issues mentioned)

 vi: check layer state before opening or closing

---

src/core/hle/service/hid/hid_system_server.cpp
src/hid_core/resources/npad/npad.cpp
src/hid_core/resources/npad/npad.h

Allows to disable input while keeping npad enabled.

service: hid: Implement EnableAppletForInput

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GameInfoFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/MessageDialogFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/GameVerificationResult.kt
src/android/app/src/main/jni/native.cpp
src/android/app/src/main/res/layout/fragment_game_info.xml
src/android/app/src/main/res/values/strings.xml
src/frontend_common/content_manager.h
src/yuzu/main.cpp

Allows you to verify your game dumps and all installed content

android: Add verify contents buttons

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/IntSetting.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
src/android/app/src/main/jni/android_settings.h
src/android/app/src/main/res/drawable/ic_lock.xml
src/android/app/src/main/res/menu/menu_in_game.xml
src/android/app/src/main/res/values/strings.xml

android: Port "Lock drawer" feature from Citra

---

src/core/loader/nsp.cpp

Broke hbl again with #12612, whoops

loader: also register fs process for raw exefs partition

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/DriverViewModel.kt
src/android/app/src/main/jni/native.cpp

This additionally fixes an issue where custom drivers could load inconsistently
Closes #12766

android: Show driver vendor in FPS overlay

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/AbstractDiffAdapter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/GameAdapter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/Game.kt

Fixes an issue where the list scroll state would be reset after a refresh

android: Only compare game contents for GameAdapter

---

src/core/hle/kernel/k_page_table_base.cpp
src/core/hle/service/nvdrv/core/container.cpp
src/core/hle/service/nvdrv/core/nvmap.cpp
src/core/hle/service/nvdrv/core/nvmap.h

Fixes a couple of resource management issues that were found while testing #12756.

core: miscellaneous fixes

---

CMakeModules/FindSimpleIni.cmake

supersede https://github.com/yuzu-emu/yuzu/pull/12793
fix https://github.com/yuzu-emu/yuzu/issues/12791

cmake: support simpleini config and pc file

---

src/core/hle/service/cmif_serialization.h
src/core/hle/service/cmif_types.h
src/core/hle/service/jit/jit.cpp
src/core/hle/service/ro/ro.cpp

Make in/out handle types more useful and ensure domain sessions work correctly

cmif_serialization: fixes

---

src/hid_core/frontend/emulated_controller.cpp
src/hid_core/frontend/emulated_controller.h
src/hid_core/hid_types.h

User reported having issues with his controller. I think this is due requesting stuff a bit more than necessary. This PR reduces the controller calls to a bare minimum without loosing any data.
closes #12750

core: hid: Reduce controller requests

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/model/EmulationViewModel.kt
src/android/app/src/main/jni/id_cache.cpp
src/android/app/src/main/jni/id_cache.h
src/android/app/src/main/jni/native.cpp
src/android/app/src/main/jni/native.h

Allows games like Klonoa: Phantasy Reverie Series to be playable
https://github.com/yuzu-emu/yuzu/assets/14132249/cc6b756b-5885-4b2f-b9fd-2138d3a0254d

android: Multi-program app switching

---

src/core/hle/service/am/applets/applet_mii_edit.cpp
src/core/hle/service/mii/mii.cpp
src/core/hle/service/mii/mii.h
src/core/hle/service/set/system_settings_server.cpp

Migrates service to the new interface style.

service: mii: Migrate service to new interface

---

src/core/hle/service/audio/audctl.cpp
src/core/hle/service/audio/audctl.h
src/core/hle/service/set/setting_formats/system_settings.cpp
src/core/hle/service/set/setting_formats/system_settings.h
src/core/hle/service/set/settings_types.h
src/core/hle/service/set/system_settings_server.cpp
src/core/hle/service/set/system_settings_server.h
src/hid_core/resource_manager.cpp
src/hid_core/resources/hid_firmware_settings.cpp

More system settings. This one is focused on audio.  I need to bump the version file since we need vibration to be enabled for everyone.

service: set: Implement more Qlaunch Settings

---

src/core/hle/kernel/k_thread.cpp

kernel: clear pinned waiter list on unpin

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/model/DriverViewModel.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/GpuDriverHelper.kt
src/android/app/src/main/jni/CMakeLists.txt
src/android/app/src/main/jni/native.cpp

android: Show system driver information

---

.gitmodules
CMakeLists.txt
externals/CMakeLists.txt
src/video_core/CMakeLists.txt
src/video_core/renderer_vulkan/vk_swapchain.cpp
src/video_core/vulkan_common/vk_enum_string_helper.h
src/video_core/vulkan_common/vulkan_wrapper.cpp
src/video_core/vulkan_common/vulkan_wrapper.h

How would you feel about using vk_enum_string_helper.h from https://github.com/KhronosGroup/Vulkan-Utility-Libraries rather than keeping vulkan_wrapper in sync yourself?
If you like the idea it would need to be added to externals I think

Simplify VkResult lookup

---

src/hid_core/CMakeLists.txt
src/hid_core/hid_types.h
src/hid_core/resources/shared_memory_format.h
src/hid_core/resources/system_buttons/capture_button.cpp
src/hid_core/resources/system_buttons/capture_button.h
src/hid_core/resources/system_buttons/home_button.cpp
src/hid_core/resources/system_buttons/home_button.h
src/hid_core/resources/system_buttons/sleep_button.cpp
src/hid_core/resources/system_buttons/sleep_button.h
src/hid_core/resources/system_buttons/system_button_types.h
src/hid_core/resources/unique_pad/unique_pad.cpp

I implemented those buttons to see if they were detected by applets. Sadly applets don't detect anything. Seems like all is handled by AM.

service: hid: Implement home, capture and sleep buttons

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/DriverAdapter.kt

android: Don't show delete button for system driver

---

CMakeLists.txt
externals/CMakeLists.txt

cmake: prefer system oaknut library

---

src/core/hle/service/hid/hid_server.cpp
src/core/hle/service/hid/hid_server.h
src/hid_core/hid_types.h
src/hid_core/resources/npad/npad.cpp
src/hid_core/resources/npad/npad.h

This function doesn't access npad.

service: hid: Implement GetPlayerLedPattern accurately

---

src/core/hle/service/aoc/aoc_u.cpp

Fixes Assassin's Creed Rogue boot

aoc: fix DLC listing

---

src/video_core/engines/sw_blitter/blitter.cpp

This fixes the rendering issues in guest Web Applet.

SwBlitter: Fix Pitch linear reading/writting

---

dist/languages/ar.ts
dist/languages/ca.ts
dist/languages/cs.ts
dist/languages/da.ts
dist/languages/de.ts
dist/languages/el.ts
dist/languages/es.ts
dist/languages/fr.ts
dist/languages/hu.ts
dist/languages/id.ts
dist/languages/it.ts
dist/languages/ja_JP.ts
dist/languages/ko_KR.ts
dist/languages/nb.ts
dist/languages/nl.ts
dist/languages/pl.ts
dist/languages/pt_BR.ts
dist/languages/pt_PT.ts
dist/languages/ru_RU.ts
dist/languages/sv.ts
dist/languages/tr_TR.ts
dist/languages/uk.ts
dist/languages/vi.ts
dist/languages/vi_VN.ts
dist/languages/zh_CN.ts
dist/languages/zh_TW.ts

Update translations (2024-02-01)

---

.ci/scripts/android/eabuild.sh
.ci/scripts/android/mainlinebuild.sh
.github/workflows/android-ea-play-release.yml
.github/workflows/android-mainline-play-release.yml
.github/workflows/android-merge.js
.github/workflows/android-publish.yml
src/android/app/build.gradle.kts

Changes the android CI so that mainline / EA play store builds can be triggered manually via a workflow dispatch trigger.

ci: android: Play store publishing setup

---

src/web_service/web_backend.cpp
src/yuzu/configuration/configure_ui.cpp

Ports https://github.com/citra-emu/citra/pull/7347 and https://github.com/citra-emu/citra/pull/7379.
Please look at the commit descriptions for additional information.

Port some small changes from Citra (web_backend and translations)

---

src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hidbus.cpp
src/core/hle/service/hid/hidbus.h
src/hid_core/hidbus/hidbus_base.h
src/hid_core/hidbus/ringcon.cpp
src/hid_core/hidbus/ringcon.h
src/hid_core/hidbus/starlink.cpp
src/hid_core/hidbus/starlink.h
src/hid_core/hidbus/stubbed.cpp
src/hid_core/hidbus/stubbed.h

This interface had a couple of mistakes.

service: hid: Migrate hidbus to new interface

---

src/core/hle/service/hid/hid_system_server.cpp
src/hid_core/resource_manager.cpp
src/hid_core/resources/npad/npad.cpp
src/hid_core/resources/npad/npad.h
src/hid_core/resources/npad/npad_resource.cpp
src/hid_core/resources/npad/npad_resource.h

Fixes launching homebrew from hbmenu.

service: hid: Free npad applet resource

---

src/core/memory/cheat_engine.cpp
src/core/memory/cheat_engine.h
src/core/memory/dmnt_cheat_vm.cpp
src/core/memory/dmnt_cheat_vm.h

Not sure if this works as intended. I need to find a cheat script that needs this. But this should add support for those opcodes.

dmnt: cheat: Add pause and resume support

---

src/core/hle/service/bcat/news/newly_arrived_event_holder.cpp
src/core/hle/service/bcat/news/news_database_service.cpp
src/core/hle/service/bcat/news/news_database_service.h
src/core/hle/service/bcat/news/news_service.cpp
src/core/hle/service/bcat/news/news_service.h
src/core/hle/service/bcat/news/overwrite_event_holder.cpp
src/core/hle/service/bcat/news/service_creator.cpp

News service is domain. I also somehow forgot to implement some Qlaunch functions.

service: news: Stub remaining functions

---

src/video_core/texture_cache/image_info.cpp
src/video_core/texture_cache/image_info.h
src/video_core/texture_cache/texture_cache.h

This fixes some 0 fps bugs in NCE Unreal games and likely some other engines.

Texture Cache: Fix untracking on GPU remap

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/GamePropertiesAdapter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/HomeSettingAdapter.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/InputProfileDialogFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsActivity.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsDialogFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsSearchFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AddonsFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/DriverManagerFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/DriversLoadingDialogFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GameFoldersFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GamePropertiesFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/InstallableFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/ProgressDialogFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/SearchFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/SetupFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/GamesFragment.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/LifecycleUtils.kt

Now lint won't yell at me for collecting state correctly -_-

android: Create lifecycle utility to simplify common StateFlow operations

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt

android: Show cancel button for the content install notice

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt

android: Show done button when configuring input overlay

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/overlay/InputOverlay.kt

android: Fix overlay visibility reset

---

src/core/CMakeLists.txt
src/core/hle/service/btm/btm.cpp
src/core/hle/service/btm/btm.h
src/core/hle/service/btm/btm_debug.cpp
src/core/hle/service/btm/btm_debug.h
src/core/hle/service/btm/btm_system.cpp
src/core/hle/service/btm/btm_system.h
src/core/hle/service/btm/btm_system_core.cpp
src/core/hle/service/btm/btm_system_core.h
src/core/hle/service/btm/btm_user.cpp
src/core/hle/service/btm/btm_user.h
src/core/hle/service/btm/btm_user_core.cpp
src/core/hle/service/btm/btm_user_core.h

Migrates the interface and adds a few functions needed by Qlaunch

service: btm: Migrate service to new IPC

---

src/android/app/src/main/java/org/yuzu/yuzu_emu/overlay/InputOverlay.kt

android: Have input overlay follow player 1 style index

---

src/yuzu/main.cpp
src/yuzu/main.h
src/yuzu/main.ui

Import keys, re-initialize KeyManager, re-scan vfs, re-populate game list.

Import keys from filesystem.

---

src/core/hle/service/nvnflinger/display.h
src/core/hle/service/nvnflinger/hardware_composer.cpp
src/core/hle/service/nvnflinger/surface_flinger.cpp
src/core/hle/service/nvnflinger/surface_flinger.h
src/core/hle/service/vi/container.cpp
src/core/hle/service/vi/container.h
src/core/hle/service/vi/layer.h
src/core/hle/service/vi/layer_list.h
src/core/hle/service/vi/shared_buffer_manager.cpp

Fixes a couple things from the previous refactor:
- Fixes #13077
- Fixes shutdown deadlocks in applets

vi: misc fixes

---

src/yuzu/main.cpp

Fixes error message to something more informative.

yuzu: Fix shortcut error message

---

src/android/app/src/main/jni/native.cpp
src/core/CMakeLists.txt
src/core/file_sys/fs_save_data_types.h
src/core/file_sys/savedata_factory.cpp
src/core/file_sys/savedata_factory.h
src/core/hle/service/am/service/application_functions.cpp
src/core/hle/service/filesystem/fsp/fs_i_filesystem.h
src/core/hle/service/filesystem/fsp/fs_i_multi_commit_manager.cpp
src/core/hle/service/filesystem/fsp/fs_i_multi_commit_manager.h
src/core/hle/service/filesystem/fsp/fs_i_save_data_info_reader.cpp
src/core/hle/service/filesystem/fsp/fs_i_save_data_info_reader.h
src/core/hle/service/filesystem/fsp/fs_i_storage.cpp
src/core/hle/service/filesystem/fsp/fs_i_storage.h
src/core/hle/service/filesystem/fsp/fsp_srv.cpp
src/core/hle/service/filesystem/fsp/fsp_srv.h
src/core/hle/service/filesystem/fsp/fsp_types.h
src/yuzu/main.cpp

After https://github.com/yuzu-emu/yuzu/pull/12982 is merged, all of fs will use the new IPC system.

fsp: Migrate remaining interfaces to cmif serialization

---

src/core/hle/service/filesystem/fsp/fsp_srv.cpp
src/core/hle/service/filesystem/fsp/fsp_srv.h

Fixes applets failing on new profiles due to missing system save data

fs: fix argument order

---

src/core/hle/service/glue/time/worker.cpp
src/core/hle/service/set/system_settings_server.cpp
src/core/hle/service/set/system_settings_server.h

service: set: Fix GetSettingsItemValue

---

tools/reset-submodules.sh

tools: Add reset submodules script

---

src/video_core/renderer_opengl/gl_shader_cache.cpp

https://github.com/yuzu-emu/yuzu/pull/13075#issuecomment-1964466998

renderer_opengl: declare geometry stream support in profile

---

src/core/CMakeLists.txt
src/core/hle/service/hid/active_vibration_device_list.cpp
src/core/hle/service/hid/active_vibration_device_list.h
src/core/hle/service/hid/applet_resource.cpp
src/core/hle/service/hid/applet_resource.h
src/core/hle/service/hid/hid_server.cpp
src/core/hle/service/hid/hid_server.h
src/hid_core/hid_types.h
src/hid_core/resource_manager.cpp
src/hid_core/resource_manager.h
src/hid_core/resources/palma/palma.cpp
src/hid_core/resources/palma/palma.h

Is a miracle that I'm still alive after migrating this interface.

service: hid: Migrate HidServer to new IPC
