yuzu-emu/yuzu

- src/yuzu/applets/profile_select.cpp
Resolves a warning where not all control paths return a value.
> applets/profile_select: Resolve a warning in exec()

- src/yuzu/applets/controller.cpp
'bool' isn't always guaranteed to be the same size as an int, so this can technically cause truncation warnings if we support other platforms (e.g. AArch64) in the future.
> controller: Convert led_patterns integer literals to bool literals

- src/core/frontend/applets/controller.cpp
- src/core/frontend/applets/controller.h
- src/yuzu/applets/controller.cpp
- src/yuzu/applets/controller.h
Prevents unnecessary copies and heap reallocations from occurring.
> controller: Pass ControllerParameters by reference in ReconfigureControllers()

- src/core/cpu_manager.cpp
- Fixes an occasional crash when trying to launch subsequent games.
> core: cpu_manager: Add missing call to MicroProfileOnThreadExit().

- src/yuzu/configuration/config.cpp
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
- In general, this is now the preferred settings for most games.
> yuzu: settings: Enable multicore, asynch GPU, and assembly shaders by default.

- src/video_core/CMakeLists.txt
- src/video_core/command_classes/codecs/vp9.cpp
- src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
- src/video_core/renderer_vulkan/wrapper.cpp
Silence three warnings and make them errors to avoid introducing more in the future.
> video_core: Enforce -Wredundant-move and -Wpessimizing-move

- src/video_core/CMakeLists.txt
- src/video_core/command_classes/codecs/vp9.cpp
Silences one warning and avoids introducing more in the future.
`base_stream.GetPosition()` returns an unsigned type, so it will always be greater than or equal to zero.
> video_core: Enforce -Werror=type-limits

- src/common/fiber.cpp
- src/common/fiber.h
I've found this while debugging #4849. This might randomly fail as the linked pull request is not merged.
YieldTo does not intend to modify the passed shared_ptrs.
Pass it by copy to keep a reference count while this function executes.
> common/fiber: Take shared_ptr<Fiber> by copy in YieldTo

- src/core/hle/kernel/kernel.cpp
This member was only used on asserts and it triggered data races.
Remove it to fix them.
> hle/kernel: Remove unused registered_core_threads to fix data races

- .gitmodules
Tracks the upstream inih project and updates to the latest release.
Previously, we were tracking the svn2github release of the project back when google code was closing. However, the author of the library continued development on the library on Github, so we can change the URL to track that one.
See the [changelogs](https://github.com/benhoyt/inih/releases) for fixed issues (some of which are memory safety issues).
> externals: Track upstream inih

- src/video_core/cdma_pusher.cpp
Fixes a crash when debug log is enabled :)
> video_core: cdma_pusher: Add missing LOG_DEBUG field in ExecuteCommand.

- src/web_service/web_backend.cpp
- Fixes a shutdown crash when we try to submit telemetry if there is a service issue.
Similar fix to #4797
> web_service: web_backend: Handle socket errors with GenericRequest.

- src/video_core/command_classes/sync_manager.cpp
- src/video_core/command_classes/sync_manager.h
Corrects some cases where the arguments would be incorrectly swapped.
> sync_manager: Amend parameter order of calls to SyncptIncr constructor

- src/core/hle/kernel/process.cpp
Use the current time, not zero, as the default RNG seed.
Fixes the Homebrew function `randomGet()` being predictable when no RNG seed is set in configuration.
> kernel: Use the current time as the default RNG seed

- src/core/hle/kernel/process.cpp
> kernel/process: Add missing <ctime> include

- src/input_common/gcadapter/gc_adapter.cpp
- src/input_common/gcadapter/gc_adapter.h
- src/input_common/gcadapter/gc_poller.cpp
This PR has the changes from #4755, #4739.
- Adds hotplug for GC adapters. No need to restart or connect the adapter before opening yuzu anymore. It's tolerant to communication errors and restarts the adapter automatically if the connection is lost.
- Adds a rather basic output form of vibration for GC controllers
- Allows offbrand GC adapters to work
- Fixes error where yuzu will not boot (run in background only) if a 3rd party controller is connected like [titan one](https://www.consoletuner.com/products/titan-one/)
> Add hotplug, rumble and fix 3rd party adapters for the GC adapter

- CMakeLists.txt
Keeps the used version of the library up to date.
Includes improvements with formatting floating point values alongside other improvements ([Changelog](https://github.com/fmtlib/fmt/releases/tag/7.1.0))
> externals: Update fmt to 7.1.0

- src/common/stream.h
- src/video_core/command_classes/codecs/vp9.cpp
- src/video_core/command_classes/codecs/vp9.h
Eliminates a potential vector for an uninitialized read.
Also makes some non-stateful functions internally linked. While we're at it, we can also be explicit about our copy and move semantics to the reader.
`[[nodiscard]]` is also added to some parts of the interface to ensure values aren't accidentally discarded through refactoring.
> VP9: Minor interface changes and safety improvements

- src/CMakeLists.txt
- src/common/file_util.h
- src/common/misc.cpp
Allows our CI to catch more potential bugs.
This also removes the [[nodiscard]] attribute of `IOFile`'s `Open()` member function. There are cases where a file may want to be opened, but have the status of it checked at a later time. This was something I missed when initially adding all of the [[nodiscard]] specifiers to the common library.
It is still possible to ignore discarded return values, however they must now be explicit. e.g.
```cpp
[[nodiscard]] Fart* MakeFarts();
// ...
void fn() {
// Lotta hot air here.
// Necessary to work around [insert extremely esoteric reason here]
static_cast<void>(MakeFarts(10));
}
```
> General: Make ignoring a discarded return value an error

- src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
Regressed by #4729. From [error log](https://github.com/yuzu-emu/yuzu/files/5466456/yuzu-qt5-s20201030.log):
```c++
src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp:41:15: error: unused variable 'OutOfMemory' [-Werror,-Wunused-const-variable]
constexpr u32 OutOfMemory{static_cast<u32>(-12)};
^
```
> video_core: unbreak -Werror in NVDEC with Clang

- src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
- src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
I renamed it to be the same as [switchbrews nvhost-ctrl](https://switchbrew.org/wiki/NV_services#NVHOST_IOCTL_CTRL_SYNCPT_CLEAR_EVENT_WAIT), and removed the gpu check as switchbrew says this function is exclusive to the switch, so it seamed unnecessary.
> Rename to align with switchbrew and remove gpu function

- src/video_core/shader/async_shaders.cpp
Adds 1 async worker thread for every 2 available threads above 8. The breakdown is as follows:
| CPU Threads | Async Workers |
| ------------- | ------------- |
| <= 7 | 1 |
| 8 | 2 |
| 12 | 4 |
| 16 | 6 |
| ... | ... |
For every additional 2 threads, add 1 thread for async compile.
> async_shaders: Increase Async worker thread count for >8 thread cpus

- src/core/hle/service/ldr/ldr.cpp
- Used by Final Fantasy X/X-2 HD Remaster.
Fixes #4808
> hle: service: ldr: Implement UnloadNrr.

- externals/microprofile/microprofile.h
- src/common/CMakeLists.txt
- src/common/fiber.cpp
- src/common/fiber.h
- src/common/file_util.cpp
- src/common/logging/backend.cpp
- src/common/string_util.cpp
- src/common/timer.cpp
- src/common/wall_clock.cpp
- src/common/x64/native_clock.h
Cleans up the common library so that we can enable warnings as errors for all the warnings that we currently have enabled.
Also performs some minor changes to microprofile to allow for this, which we control
> common: Enable warnings as errors

- externals/microprofile/microprofile.h
Silences a truncation warning by making the truncation explicit and documenting the reason for it.
> microprofile: Silence warning in headers

- src/video_core/command_classes/codecs/codec.h
- src/video_core/command_classes/codecs/h264.cpp
- src/video_core/command_classes/codecs/h264.h
- src/video_core/command_classes/codecs/vp9.cpp
- src/video_core/command_classes/codecs/vp9.h
- src/video_core/command_classes/codecs/vp9_types.h
- src/video_core/command_classes/nvdec.h
Prevents bugs from occurring where the results of a function are accidentally discarded.
> nvdec: Make use of [[nodiscard]] where applicable

- src/core/CMakeLists.txt
- src/core/core.cpp
- src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
- src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
- src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_gpu.h
- src/core/hle/service/nvdrv/nvdrv.cpp
- src/core/hle/service/nvdrv/nvdrv.h
- src/core/hle/service/nvdrv/syncpoint_manager.cpp
- src/core/hle/service/nvdrv/syncpoint_manager.h
- src/core/hle/service/nvflinger/nvflinger.cpp
- src/video_core/dma_pusher.cpp
- src/video_core/dma_pusher.h
- src/video_core/gpu.cpp
- src/video_core/gpu.h
Implements prefetched buffers in the GPU DMA pusher. We then use this to implement some missing GPU synchronization mechanisms, such as the SubmitGPFIFO flags for adding a wait and incrementing syncpoints. This also adds various other improvements, and refactoring to remove code duplication. Lastly, we still see cases where GPU synchronization is bad and command lists can be corrupted. This previously would result in the emulator crashing on an out-of-bounds access in GPU code. To mitigate this, I have added integrity checks and log these errors.
Off the top of my head, this fixes Super Mario Sunshine and Super Mario Galaxy (they do not render yet, due to other issues, but the games seem to be submitting valid data now with asynch GPU/multicore enabled). This should also fix some issues …
> Improvements to GPU synchronization & various refactoring

- src/core/settings.cpp
- src/core/settings.h
- src/yuzu/configuration/configure_audio.cpp
- src/yuzu/configuration/configure_dialog.cpp
- src/yuzu/configuration/configure_general.cpp
- src/yuzu/configuration/configure_graphics.cpp
- src/yuzu/configuration/configure_graphics_advanced.cpp
- src/yuzu/configuration/configure_per_game.cpp
- src/yuzu/configuration/configure_system.cpp
Rather than have directly modified global state here, we can make it an implementation detail and have an interface that changes are queried through.
> core/settings: Move configuring_global behind an API

- src/core/settings.h
This can use a braced initializer to accomplish the same thing with less code.
> settings: Simplify initializer of resolution factor

- src/common/fiber.cpp
- src/common/fiber.h
Hides all of the implementation details for users of the class. This has the benefit of reducing includes and also making the fiber classes movable again.
> common/fiber: Move all member variables into impl class

- CMakeLists.txt
Updates to the latest bugfix release of fmt.
All the fixes can be seen [here](https://github.com/fmtlib/fmt/releases)
> externals: Update fmt to 7.1.2

- src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
- src/video_core/dma_pusher.cpp
- src/video_core/dma_pusher.h
- This seems to cause softlocks in Breath of the Wild.
> video_core: dma_pusher: Remove integrity check on command lists.

- src/core/hle/ipc_helpers.h
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/service/acc/acc.cpp
- src/core/hle/service/am/applet_ae.cpp
- src/core/hle/service/aoc/aoc_u.cpp
- src/core/hle/service/apm/apm.cpp
- src/core/hle/service/bcat/module.cpp
- src/core/hle/service/btdrv/btdrv.cpp
- src/core/hle/service/btm/btm.cpp
- src/core/hle/service/friend/friend.cpp
- src/core/hle/service/glue/arp.cpp
- src/core/hle/service/ldr/ldr.cpp
- src/core/hle/service/lm/lm.cpp
- src/core/hle/service/nvdrv/nvdrv.cpp
- src/core/hle/service/pm/pm.cpp
- src/core/hle/service/prepo/prepo.cpp
Resolves numerous deprecation warnings throughout the codebase due to inclusion of this header. Now building core should be significantly less noisy (and also relying on less global state).
This also uncovered quite a few modules that were relying on indirect includes, which have also been fixed.
> ipc_helpers: Remove usage of the global system instance

- src/core/arm/cpu_interrupt_handler.h
The interrupt handler contains a std::atomic_bool, which isn't copyable or movable, so the special move member functions will always be deleted, despite being defaulted.
This resolves warnings on Clang and GCC.
> cpu_interrupt_handler: Mark move contructor/assignment as deleted

- src/core/hle/service/caps/caps_u.cpp
- src/core/hle/service/caps/caps_u.h
- This works similiar to GetAlbumContentsFileListForApplication.
- Since we do not implement the album, this should be safe to stub for now.
- Used by Super Smash Bros. Ultimate (newer updates) in World of Light.
> hle: service: caps_u: Stub GetAlbumFileList3AaeAruid.

- src/core/hle/service/am/applets/controller.cpp
- src/core/hle/service/am/applets/controller.h
Some games like Cave Story+ set invalid values in the ControllerPrivateArg's mode and caller fields.
Use other fields to determine the appropriate mode and caller should either or both fields be invalid.
Fixes the issue reported by @german77 in https://github.com/yuzu-emu/yuzu/pull/4866#issuecomment-719059839
> applets/controller: Introduce additional checks for mode and caller

- src/yuzu/bootmanager.cpp
Changes the first message to not include the OpenGL version, as the error is caused by OpenGL failing to load and nothing to do with the version.
Adds a new check for OpenGL version 4.3. This will display a message with a similar error as well as the GL_RENDERER string. Adds a ERROR log message when triggered. This prevents a crash with yuzu trying to use older OpenGL versions.
Modifies the unsupported extension message to output the GL_RENDERER string in the message, as well as logging the string.
> bootmanager: Log and show GL_RENDERER string when GPU is insufficient

- src/input_common/motion_input.h
Given most of the public interface returns by value, we should mark these as nodiscard to prevent any arithmetic bugs from arising where we accidentally don't use the result of a function,
> motion_input: Mark member functions as [[nodiscard]] where applicable 

- src/video_core/gpu.h
- src/video_core/rasterizer_interface.h
- src/video_core/renderer_base.h
Makes use of `[[nodiscard]]` to allow the compiler to catch scenarios where not using the return value of a function is undeniably a bug.
> [gpu, render_base, rasterizer_interface]: Make use of [[nodiscard]] where applicable

- src/common/page_table.cpp
- src/common/page_table.h
- src/common/virtual_buffer.cpp
- src/common/virtual_buffer.h
Makes the API a little more flexible by allowing them to be moved if they ever need to be. Previously, with the destructor specified, but no move assignment or move constructor specified, they wouldn't be implicitly generated.
While we're at it, we can also make VirtualBuffer a little more type-safe at compile-time so we don't ever unintentionally hit undefined behavior.
> page_table: Allow page tables to be moved

- src/common/virtual_buffer.h
Prevents us from potentially churning memory by freeing and reallocating a memory block that would have already been adequate as is.
> virtual_buffer: Do nothing on resize() calls with same sizes

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_3d.h
Deduplicate some code and put it in separate functions so it's easier to understand and profile.
Use insert instead of loop push_back to accumulate macro parameters. This reduces the overhead of bounds checking on each element. It won't reduce the cost of allocation because usually this vector's capacity is usually large enough to hold whatever we push to it.
> maxwell_3d: Move code to separate functions and insert instead of push_back

- src/common/CMakeLists.txt
- src/common/bit_cast.h
Add a std::bit_cast-like function archiving the same runtime results as
the standard function, without compile time support.
This allows us to use bit_cast while we wait for compiler support, it
can be trivially replaced in the future.
Thanks to Lioncache for the SFINAE implementation.
> common/bit_cast: Add function matching std::bit_cast without constexpr

- src/input_common/gcadapter/gc_poller.cpp
- src/input_common/sdl/sdl_impl.cpp
Changes the current amplification method for a more linear and less aggressive one. Since vibration strength can be fine tuned now.
This should amend problems where 1% of rumble strength still was too strong
> Modify rumble amplification

- src/yuzu/configuration/configure_input_player.cpp
This is a static member function, so we don't need use an existing instance to call this function.
> configure_input_player: Use static qualifier for IsProfileNameValid()

- src/video_core/engines/shader_bytecode.h
Eliminates variable shadowing in shader_bytecode, bringing us a little closer to enabling -Wshadow as an error.
While we're at it we can also apply nodiscard where applicable to the helper functions to prevent bugs from slipping through.
> shader_bytecode: Eliminate variable shadowing

- src/video_core/renderer_opengl/gl_rasterizer.cpp
Alpha test has been proven to only affect the first render target.
> gl_rasterizer: Remove warning of untested alpha test

- src/core/hle/service/nvdrv/devices/nvdevice.h
- src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
- src/core/hle/service/nvdrv/devices/nvdisp_disp0.h
- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
- src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
- src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
- src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_gpu.h
- src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
- src/core/hle/service/nvdrv/devices/nvhost_nvdec.h
- src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
- src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
- src/core/hle/service/nvdrv/devices/nvhost_nvjpg.cpp
- src/core/hle/service/nvdrv/devices/nvhost_nvjpg.h
- src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
- src/core/hle/service/nvdrv/devices/nvhost_vic.h
- src/core/hle/service/nvdrv/devices/nvmap.cpp
- src/core/hle/service/nvdrv/devices/nvmap.h
- src/core/hle/service/nvdrv/interface.cpp
- src/core/hle/service/nvdrv/interface.h
- src/core/hle/service/nvdrv/nvdata.h
- src/core/hle/service/nvdrv/nvdrv.cpp
- src/core/hle/service/nvdrv/nvdrv.h
The most notable changes are as follows;
* Ioctl1, Ioctl2 & Ioctl3 are completely separated now. This allows us to track unimplemented Ioctls across versions easier.
* Delayed Ioctls are removed. They're not accurate and are not needed.
* All Ioctls share the same result codes now instead of redefining results all the time.
* Ioctls are now set up to use their groups & cmd numbers. This cuts down the code for nvdec & is closer to what the service does on the switch.
* GetVARegions for Ioctl3 is now implemented(this was not implemented before)
* All structs have their members initialized now
> core: Make nvservices more standardized

- .ci/templates/build-msvc.yml
This PR will add an installation step for Vulkan SDK to the MSVC build.
> ci: install Vulkan SDK in MSVC build

- src/video_core/shader/async_shaders.cpp
Same behavior, but avoids redundant copies.
While we're at it, we can simplify the pushing of the parameters into the pending queue.
> async_shaders: std::move data within QueueVulkanShader()

- .ci/templates/build-msvc.yml
Then cmake can find the Vulkan SDK binaries.
It seems like Azure Pipelines resets environment variables each step. By reordering the `refreshenv` instruction, the modified `PATH` variable will be passed to `CMake` correctly.
> CI: move refreshenv to the configure step

- src/common/logging/backend.cpp
- src/core/settings.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_debug.ui
This PR increases the maximum size the log can go up to from 50 MB to 100 MB.
The extended logging option is automatically disabled on boot but can be enabled afterwards, allowing the log file to go up to 1 GB during that session.
This PR also fixes a few errors that are present in the general debug menu, such as tool tips not appearing.
> logging/settings: Increase maximum log size to 100 MB and add extended logging option

- src/core/frontend/input.h
- src/input_common/CMakeLists.txt
- src/input_common/gcadapter/gc_poller.cpp
- src/input_common/sdl/sdl.h
- src/input_common/sdl/sdl_impl.cpp
- src/input_common/touch_from_button.cpp
- src/input_common/udp/client.cpp
- src/input_common/udp/protocol.h
Migrates over warnings as errors for input common to match how the common library treats warnings as errors.
> input_common: Treat warnings as errors

- src/core/hle/kernel/svc.cpp
The parameter is used in this function, so this suppression isn't necessary.
> svc: Remove unnecessary [[maybe_unused]] tag

- src/video_core/shader/decode/image.cpp
The components' sizes were mismatched. This corrects that.
> decoder/image: Fix incorrect G24R8 component sizes in GetComponentSize()

- src/core/core.cpp
- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/am/applet_ae.cpp
- src/core/hle/service/am/applet_ae.h
- src/core/hle/service/am/applet_oe.cpp
- src/core/hle/service/am/applet_oe.h
- src/core/hle/service/service.cpp
- src/core/hle/service/service.h
- src/core/hle/service/vi/vi.cpp
- src/core/hle/service/vi/vi.h
- src/core/hle/service/vi/vi_m.cpp
- src/core/hle/service/vi/vi_m.h
- src/core/hle/service/vi/vi_s.cpp
- src/core/hle/service/vi/vi_s.h
- src/core/hle/service/vi/vi_u.cpp
- src/core/hle/service/vi/vi_u.h
- This crash would happen when attempting to shutdown yuzu early on in boot.
> hle: services: Fix a crash with improper NVFlinger lifetime management.

- src/core/core.cpp
- src/core/core.h
- src/core/file_sys/card_image.cpp
- src/core/file_sys/card_image.h
- src/core/file_sys/submission_package.cpp
- src/core/file_sys/submission_package.h
- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/loader/loader.cpp
- src/core/loader/loader.h
- src/core/loader/nsp.cpp
- src/core/loader/nsp.h
- src/core/loader/xci.cpp
- src/core/loader/xci.h
- src/yuzu/bootmanager.cpp
- src/yuzu/bootmanager.h
- src/yuzu/main.cpp
- src/yuzu/main.h
This change refactors loader code to support booting an indexed program within the application container. For now, this supports booting a program NCA (by index) within an NSP or XCI file.
With this refactoring, we can implement IApplicationFunctions::ExecuteProgram within the AM service, which is used to boot another process. This is used by Super Mario 3D All-Stars to launch sub-titles (Super Mario 64, Super Mario Sunshine, etc.).
Since yuzu does not support multiple processes, we accomplish this by simply stopping the current process and launching the new process at the specified program index.
This allows Super Mario 3D All-Stars to mostly function (with the exception that the Mario games do not render, but that is unrelated to this change). Once we fix rendering, this should work.
> core: Refactor loader and implement ExecuteProgram

- src/input_common/analog_from_button.cpp
Instead of returning only the cardinal angles with digital buttons allow the input to output any angle by drifting the angle slowly to the desired direction. Solving #4580, #2845. A solution with mouse will also be implemented in a future PR.
The speed of the drift can be adjusted in the config.ini. If necessary I can add the setting to the UI but as far my testing with the game I have needs no adjustment.
> Allow to dial any angle with digital joystick

- src/yuzu/applets/controller.cpp
- src/yuzu/applets/controller.h
- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/configuration/configure_input_player.h
Example:
Pokemon Let's Go, supports Handheld, Left and Right Joycons
Invalid emulated controllers would show up as empty in the dropdown and utilize the Pro Controller image as a fallback
> configure_input_player: Use the NpadStyleSet to limit the available controllers shown

- src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
- src/video_core/renderer_vulkan/fixed_pipeline_state.h
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
- src/video_core/renderer_vulkan/vk_shader_decompiler.h
This PR aims to implement the alpha test culling for the Vulkan renderer, culling the render if its `alpha` value does not satisfy a comparison operation against a particular reference alpha value, both of which are provided by Maxwell 3D. 
This is used on different textures in various titles. One of the most noticeable being SSBU's menus:
Before
After
> vulkan_renderer: Alpha Test Culling Implementation

- src/core/frontend/emu_window.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/video_core/renderer_vulkan/renderer_vulkan.cpp
- src/yuzu/bootmanager.cpp
- src/yuzu/bootmanager.h
- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.h
- src/yuzu_cmd/yuzu.cpp
- src/yuzu_tester/emu_window/emu_window_sdl2_hide.cpp
- src/yuzu_tester/emu_window/emu_window_sdl2_hide.h
EmuWindow::PollEvents was called from the GPU thread (or the CPU thread
in sync-GPU mode) when swapping buffers.  It had three implementations:
- In GRenderWindow, it didn't actually poll events, just set a flag and
emit a signal to indicate that a frame was displayed.
- In EmuWindow_SDL2_Hide, it did nothing.
- In EmuWindow_SDL2, it did call SDL_PollEvents, but this is wrong
because SDL_PollEvents is supposed to be called on the thread that set
up video - in this case, the main thread, which was sleeping in a
busyloop (regardless of whether sync-GPU was enabled).  On macOS this
causes a crash.
To fix this:
- Rename EmuWindow::PollEvents to OnFrameDisplayed, and give it a
default implementation that does nothing.
- In EmuWindow_SDL2, do not override OnFrameDisplayed, but instead have
the …
> Overhaul EmuWindow::PollEvents to fix yuzu-cmd calling SDL_PollEvents off main thread

- src/input_common/CMakeLists.txt
Regressed by #4927. From [error log](https://github.com/yuzu-emu/yuzu/files/5599711/yuzu-qt5-s20201125.log):
```c++
error: unknown warning option '-Werror=unused-but-set-parameter'; did you mean '-Werror=unused-parameter'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Werror=unused-but-set-variable'; did you mean '-Werror=unused-const-variable'? [-Werror,-Wunknown-warning-option]
```
> input_common: unbreak -Werror with Clang

- src/core/hle/service/nvdrv/syncpoint_manager.h
- src/video_core/gpu.cpp
- Use .at() instead of raw indexing when dealing with untrusted indices.
- For the special case of WaitFence with syncpoint id -1, instead of crashing, log an error and ignore.  This is what I get when running Super Mario Maker 2.
> nvdrv, video_core: Don't index out of bounds when given invalid syncpoint ID

- src/core/file_sys/savedata_factory.cpp
- src/core/file_sys/savedata_factory.h
- src/core/hle/service/filesystem/filesystem.cpp
- src/yuzu/main.cpp
Now there's only two meaningful instances left in core.
> savedata_factory: Eliminate usage of the global system instance

- src/CMakeLists.txt
This Clang warning complains when offsetof is used on a
non-standard-layout type (i.e. any class using various C++ features),
even though it works fine (and is not undefined behavior as of C++17).
> CMakeLists: disable -Winvalid-offsetof

- src/audio_core/audio_renderer.cpp
- src/audio_core/audio_renderer.h
It's unused and doesn't need to be initialized
> audio_core: Remove temp_mix_buffer

- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
Those functions are used by these games #4048. Making them playable. The enum posible values are unknown.
> HID: Stub set and get NpadCommunicationMode

- src/core/hle/service/hid/controllers/npad.h
In latest research I found NpadCommunicationMode actually has 4 different types
> Add missing types to NpadCommunicationMode

- src/common/CMakeLists.txt
- src/common/div_ceil.h
Add an equivalent to 'Common::AlignUp(n, d) / d' and a log2 alternative.
Required by #4967
> common: Add Common::DivCeil and Common::DivCeilLog2

- src/video_core/command_classes/codecs/codec.cpp
- src/video_core/command_classes/codecs/codec.h
- src/video_core/command_classes/codecs/h264.cpp
- src/video_core/command_classes/codecs/h264.h
- src/video_core/command_classes/codecs/vp9.cpp
- src/video_core/command_classes/codecs/vp9.h
- src/video_core/command_classes/codecs/vp9_types.h
- src/video_core/command_classes/nvdec.cpp
- src/video_core/command_classes/nvdec.h
- src/video_core/command_classes/vic.cpp
This PR aims to reduce noticeable frame skipping by queuing all FFmpeg decoded frames and display the frames in order, rather than simply displaying the most recently decoded frame. This noticeably fixes frame skipping in VP9 streams in particular, as they seem to decode frames at a different rate to displaying them.
This PR also cleans up much of the vp9 code to trim unneeded values and opt for `std::move` more often.
closes #4839
> nvdec: Queue and display all decoded frames, cleanup decoders

- src/audio_core/CMakeLists.txt
- src/audio_core/algorithm/filter.cpp
- src/audio_core/algorithm/filter.h
- src/audio_core/audio_renderer.cpp
- src/audio_core/audio_renderer.h
- src/audio_core/buffer.h
- src/audio_core/command_generator.cpp
- src/audio_core/command_generator.h
- src/audio_core/cubeb_sink.cpp
- src/audio_core/effect_context.cpp
- src/audio_core/effect_context.h
- src/audio_core/info_updater.cpp
- src/audio_core/info_updater.h
- src/audio_core/memory_pool.cpp
- src/audio_core/memory_pool.h
- src/audio_core/sink_context.cpp
- src/audio_core/sink_context.h
- src/audio_core/splitter_context.cpp
- src/audio_core/splitter_context.h
- src/audio_core/stream.cpp
- src/audio_core/stream.h
- src/audio_core/voice_context.cpp
- src/audio_core/voice_context.h
- src/common/wall_clock.cpp
- src/common/wall_clock.h
- src/common/x64/native_clock.cpp
- src/common/x64/native_clock.h
- src/core/core_timing.h
- src/core/hle/result.h
Moves the audio code closer to enabling warnings as errors in general.
Here's to another 5K PRs ✌️.
> audio_core: Make shadowing and unused parameters errors

- src/common/fiber.cpp
- src/common/fiber.h
- src/core/arm/arm_interface.h
- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_32.h
- src/core/arm/dynarmic/arm_dynarmic_64.cpp
- src/core/arm/dynarmic/arm_dynarmic_64.h
- src/core/core.cpp
- src/core/core.h
- src/core/cpu_manager.cpp
- src/core/hle/kernel/address_arbiter.cpp
- src/core/hle/kernel/address_arbiter.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/memory/page_table.cpp
- src/core/hle/kernel/physical_core.cpp
- src/core/hle/kernel/physical_core.h
- src/core/hle/kernel/scheduler.cpp
- src/core/hle/kernel/scheduler.h
- src/core/hle/kernel/svc.cpp
- src/core/hle/kernel/synchronization_object.h
- src/core/hle/kernel/thread.cpp
- src/core/hle/kernel/thread.h
- src/core/hle/kernel/time_manager.cpp
- src/core/hle/kernel/time_manager.h
- src/core/hle/service/ldr/ldr.cpp
- src/yuzu/debugger/wait_tree.cpp
The primary purpose of this PR is to change how our implementation of allocating an instance of Dynarmic per guest thread to one where we allocate an instance per physical core (4 total). This has the benefit of greatly reducing memory usage, since Dynarmic does not share block allocations across instances. This part was mostly done by @FernandoS27.
This should fix many issues related to yuzu crashing for users who do not have a large enough page file or enough RAM. It also improves performance in various places.
Additionally, this change includes a few more cleanups, and some minor changes around the scheduler code, as well as changes necessary for the 4-JITs implementation to work with NROs.
This change does surface an issue that we may need to live with for now -- There seems to be a …
> Kernel: Refactor to use 4-instances of Dynarmic & various cleanups and improvements

- src/video_core/command_classes/codecs/vp9.cpp
- src/video_core/command_classes/vic.cpp
Removes the usage of moves that don't result in behavior different from a copy, or otherwise would prevent copy elision from occurring.
> vp9/vic: Resolve pessimizing moves

- src/video_core/shader/node.h
Migrates the video core code slightly towards enabling variable shadowing as a compilation error.
While we're in the same area, we can make a few functions as `[[nodiscard]]` to prevent logic bugs from slipping through.
> node: Eliminate variable shadowing

- src/video_core/command_classes/codecs/codec.cpp
This was only necessary for use with the `avcodec_decode_video2`/`avcoded_decode_audio4` APIs which are also deprecated.
Given we use `avcodec_send_packet`/`avcodec_receive_frame`, this isn't necessary, this is even indicated directly within the FFmpeg API changes document [here](https://github.com/FFmpeg/FFmpeg/blob/master/doc/APIchanges#L410) on 2017-09-26.
This prevents our code from breaking whenever we update to a newer version of FFmpeg in the future if they ever decide to fully remove this API member.
> codec: Remove deprecated usage of AVCodecContext::refcounted_frames

- src/video_core/renderer_opengl/renderer_opengl.cpp
See citra-emu/citra#5617 for more details.
AddField is implemented using std::move.
However, the memory backing these three const char* fields are local in scope to this function. When Citra (SDL2 at least) attempts to use these fields on exit, the memory may already be unmapped/invalid. To fix this, just convert them to a string.
I couldn't find a good way to discriminate between const char[] and const char* in the AddField templating system, so for now we just need to be careful and keep this in mind. I did check and as far as I can tell, all of the other const char*-like fields passed to AddField are globals that won't be freed.
> Port citra-emu/citra#5617: "Fix telemetry-related exit crash from use-after-free"

- src/yuzu/game_list_p.h
This is designated as obsolete in Qt's docs (see: https://doc.qt.io/qt-5/qvariant-obsolete.html#operator-lt), so we directly compare against the data instead of delegating the work to QVariant.
Prevents our code from breaking in the future when we update Qt versions.
> game_list_p: Resolve deprecated usage of QVariant operator<

- src/common/x64/xbyak_abi.h
Avoids an implicit sign conversion in `RegToIndex()`
> xbyak_abi: Avoid implicit sign conversions

- src/audio_core/cubeb_sink.cpp
See citra-emu/citra#5577 for more details.
When using cubeb, the volume level assigned via windows wouldn't be remembered, annoying some users who controlled volume levels solely using the mixer volumes, instead of changing the master volume or the citra provided internal volume.
The issue happens on Citra as well as Yuzu (see yuzu-emu/yuzu#2935)
A recent cubeb change (kinetiknz/cubeb#599) introduced the CUBEB_STREAM_PREF_PERSIST flag which should fix the issue.
Fixes yuzu-emu/yuzu#2935.
> Port citra-emu/citra#5577: "Update cubeb and request a persistent stream session"

- src/video_core/engines/maxwell_dma.h
On Apple platforms, `FALSE` and `TRUE` are defined as macros by <mach/boolean.h>, which is included by various system headers.
Note that there appear to be no actual users of the names to fix up.
> maxwell_dma: Rename RenderEnable::Mode::FALSE and TRUE to avoid name conflict

- src/yuzu_cmd/config.cpp
Specifically:
const auto size = sdl2_config->GetInteger("System", "users_size", 0);
The variable is never used, producing a warning.  I wondered if this
ought to be assigning something to in `Settings`, but nothing else in
the codebase ever mentions a setting called "users_size", so I guess
it's safe to remove...
> yuzu_cmd: Remove 'users_size'

- src/video_core/dirty_flags.cpp
- src/video_core/renderer_opengl/gl_state_tracker.cpp
- src/video_core/renderer_vulkan/vk_state_tracker.cpp
The previous definition was:
#define NUM(field_name) (sizeof(Maxwell3D::Regs::field_name) / sizeof(u32))
In cases where `field_name` happens to refer to an array, Clang thinks
`sizeof(an array value) / sizeof(a type)` is an instance of the idiom
where `sizeof` is used to compute an array length.  So it thinks the
type in the denominator ought to be the array element type, and warns if
it isn't, assuming this is a mistake.
In reality, `NUM` is not used to get array lengths at all, so there is no
mistake.  Silence the warning by applying Clang's suggested workaround
of parenthesizing the denominator.
> video_core: Adjust `NUM` macro to avoid Clang warning

- src/core/hle/kernel/physical_core.h
`PhysicalCore`'s move assignment operator was declared as `= default`,
but was implicitly deleted because `PhysicalCore` has fields
of reference type.  Switch to explicitly deleting it to avoid a Clang
warning.
The move *constructor* is still defaulted, and is required to exist due
to the use of `std::vector<PhysicalCore>`.
> Fix "explicitly defaulted but implicitly deleted" warning

- src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
> nvdrv: Remove useless re-declaration of pure virtual methods that were already declared in the superclass

- src/core/hle/ipc_helpers.h
- src/core/hle/service/vi/vi.cpp
- Add a type check so that calling Push with an invalid type produces a compile error rather than a linker error.
- vi.cpp was calling Push with a variable of type `std::size_t`.  There's no explicit overload for `size_t`, but there is one for `u64`, which on most platforms is the same type as `size_t`.  On macOS, however, it isn't: both types are 64 bits, but `size_t` is `unsigned long` and `u64` is `unsigned long long`.  Regardless, it makes more sense to explicitly use `u64` here instead of `size_t`.
> hle: Type check ResponseBuilder::Push arguments, and fix use in vi.cpp

- src/core/hle/kernel/memory/memory_block_manager.h
- src/core/hle/service/ncm/ncm.cpp
These fields look like they might be useful in the future (especially in ncm where the methods are all unimplemented), so I didn't remove them entirely.
> core: Mark unused fields as [[maybe_unused]]

- src/video_core/buffer_cache/buffer_block.h
Reduces the amount of dependencies the header pulls in. While we're at it, we can mark the interface as nodiscard where applicable.
> buffer_block: Remove unnecessary includes

- src/video_core/shader/shader_ir.cpp
Same behavior, but elides an unnecessary atomic reference count increment and decrement.
> shader_ir: std::move node within DeclareAmend()

- src/video_core/buffer_cache/map_interval.h
Clang complains about `new_chunk`'s constructor using the then-uninitialized `first_chunk` (even though it's just to get a pointer into it).
> map_interval: Change field order to address uninitialized field warning

- CMakeLists.txt
- src/core/network/network.cpp
- src/core/network/sockets.h
`__unix__` is not predefined on Apple platforms even though they are Unix.
> CMakeLists,network: Create YUZU_UNIX macro to replace __unix__

- src/video_core/shader/ast.cpp
Provides an in-place format string to make it more pleasant to read.
> ast: Improve string concat readability in operator()

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/renderer_opengl/gl_arb_decompiler.cpp
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
- src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
- src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
- src/video_core/shader/control_flow.cpp
- src/video_core/shader/decode.cpp
With C++20, we can use the more concise `contains()` member function instead of comparing the result of the `find()` call with the end iterator.
> video_core: Make use of ordered container contains() where applicable

- src/core/settings.h
- src/input_common/analog_from_button.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_input_advanced.cpp
- src/yuzu/configuration/configure_input_advanced.ui
Since this setting adds delay to the input, some games like SSBU don't work as intended. This will disable the setting by default and add a checkbox under advanced settings to enable it.
> Disable analog joystick from buttons by default

- src/core/hle/service/am/applets/controller.cpp
Avoids unnecessary 1072 byte copies when querying info about controllers. While we're in the area, we can also use std::move where applicable.
> controller: Avoid unnecessary copies in ConfigurationComplete()

- src/core/memory.cpp
Write() doesn't return anything, so the `@returns` tag shouldn't be present.
> memory: Resolve -Wdocumentation warning for Write()

- src/core/core.cpp
- src/core/file_sys/content_archive.cpp
- src/core/frontend/applets/error.cpp
- src/core/hle/kernel/process_capability.cpp
- src/core/hle/kernel/resource_limit.cpp
- src/core/hle/kernel/server_session.cpp
- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/applets/error.cpp
- src/core/hle/service/am/applets/general_backend.cpp
- src/core/hle/service/apm/controller.cpp
- src/core/hle/service/apm/interface.cpp
- src/core/hle/service/fatal/fatal.cpp
- src/core/hle/service/filesystem/filesystem.cpp
- src/core/hle/service/filesystem/fsp_srv.cpp
- src/core/hle/service/friend/friend.cpp
- src/core/hle/service/lm/lm.cpp
- src/core/hle/service/ns/pl_u.cpp
- src/core/hle/service/nvflinger/buffer_queue.cpp
- src/core/hle/service/prepo/prepo.cpp
- src/core/hle/service/service.cpp
- src/core/hle/service/set/set_sys.cpp
- src/core/hle/service/sockets/bsd.cpp
- src/core/hle/service/sockets/sockets_translate.cpp
- src/core/hle/service/vi/vi.cpp
- src/core/network/network.cpp
Follows the video core PR. fmt doesn't require casts for enum classes anymore, so we can remove quite a few casts.
> core: Remove unnecessary enum casts in log calls

- src/common/file_util.cpp
- src/common/file_util.h
Migrates a bunch of our file handling code over to std::filesystem to simplify a bunch of our code and make it easier to maintain.
Notably with this, `CopyDir` will now function on Windows.
> common/file_util: Make use of std::filesystem

- src/core/hle/service/sockets/bsd.cpp
- src/core/hle/service/sockets/sockets.h
- src/core/hle/service/sockets/sockets_translate.cpp
- src/core/hle/service/sockets/sockets_translate.h
- src/core/network/network.cpp
- src/core/network/network.h
Actually, two enum classes, since for some reason there are two separate
yet identical `PollFD` types used in the codebase.  I get that one is
ABI-compatible with the Switch while the other is an abstract type used
for the host, but why not use `WSAPOLLFD` directly for the latter?
Anyway, why make this change?  Because on Apple platforms, `POLL_IN`,
`POLL_OUT`, etc. (with an underscore) are defined as macros in
<sys/signal.h>.  (This is inherited from FreeBSD.)  So defining
a variable with the same name causes a compile error.
I could just rename the variables, but while I was at it I thought I
might as well switch to an enum for stronger typing.
Also, change the type used for values copied directly to/from the
`events` and `revents` fields of the host *native*
`pollfd`/`WSASPOLLFD`, from …
> network, sockets: Replace `POLL_IN`, `POLL_OUT`, etc. constants with an `enum class PollEvents`

- src/common/file_util.cpp
- src/common/file_util.h
Fix CreateFullPath to have its intended previous behavior (whatever that was), and deprecate it in favor of the new CreateDirs function.
Unlike CreateDir, CreateDirs is marked as [[nodiscard]] to avoid new code ignoring its result value.
Thanks to Morph and ogniK for helping me debug and fix this.
> common/file_util: Fix and deprecate CreateFullPath, add CreateDirs

- src/common/file_util.cpp
Fix invalid encoding paths when iterating over a directory on Windows.
> common/file_util: Let std::filesystem cast from UTF16 to std::string

- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Resolves a `-Wrange-loop-analysis` warning.
> gl_shader_decompiler: Elide unnecessary copies within DeclareConstantBuffers()

- .travis/linux/build.sh
Changes the bound ccache directory to `/home/yuzu/.ccache` instead of `/root/.ccache`, since the `/root` directory is not accessible by the `yuzu` user in the guest container and is not the default ccache directory for this user.
> travis/linux: Use correct ccache directory

- src/common/file_util.cpp
- src/common/file_util.h
- src/core/file_sys/vfs_real.cpp
This reverts all the changes for std::filesystem as it causes an application crash when narrow multibyte (UTF-8) encoded characters are converted to and from UTF-16 on Windows.
Reverts #5173, #5174, #5176, #5179 and #5181
> fs: Revert all std::filesystem changes

- src/core/file_sys/content_archive.cpp
- src/core/file_sys/content_archive.h
- src/core/file_sys/nca_patch.cpp
- src/core/file_sys/nca_patch.h
- src/core/file_sys/vfs.cpp
- src/core/file_sys/vfs.h
- src/core/file_sys/vfs_concat.cpp
- src/core/file_sys/vfs_concat.h
- src/core/file_sys/vfs_layered.cpp
- src/core/file_sys/vfs_layered.h
- src/core/file_sys/vfs_offset.cpp
- src/core/file_sys/vfs_offset.h
- src/core/file_sys/vfs_real.cpp
- src/core/file_sys/vfs_real.h
- src/core/file_sys/vfs_static.h
- src/core/file_sys/vfs_vector.cpp
- src/core/file_sys/vfs_vector.h
- src/core/file_sys/xts_archive.cpp
- src/core/file_sys/xts_archive.h
- src/core/loader/deconstructed_rom_directory.h
- src/core/loader/elf.h
- src/core/loader/kip.h
- src/core/loader/nax.h
- src/core/loader/nca.h
- src/core/loader/nro.h
- src/core/loader/nso.h
- src/core/loader/nsp.h
- src/core/loader/xci.h
Makes use of the VirtualDir and VirtualFile aliases across the board instead of having a few isolated places that don't use it.
> vfs: Use existing type aliases consistently

- CMakeLists.txt
- src/common/CMakeLists.txt
Fixes a regression by 761206cf81b271f7f4dd6a167a120325b760dbf3, causing yuzu to not build on at least Linux with any version of Boost except a cached 1.73 Conan version from before about a day ago.
Moves the Boost requirement out of the `REQUIRED_LIBS` pseudo-2D-array for Conan to instead be manually configured, using Conan as a fallback solution if the system does not meet our requirements.
~~Requires rebuilding the `linux-fresh` container in order to build/pass CI. As of writing, that container uses the mentioned cached version of Boost and is incompatible with these changes.~~ Partially compatible now.
**DO NOT MERGE** until someone with the MSVC toolchain can verify this works there, too.
> cmake: Fix generating CMake configs and linking with Boost

- src/core/hle/service/aoc/aoc_u.cpp
- src/core/hle/service/aoc/aoc_u.h
Stubs the following commands:
**aoc:u**
CreateEcPurchasedEventManager
CreatePermanentEcPurchasedEventManager
**IPurchaseEventManager**
SetDefaultDeliveryTarget
SetDeliveryTarget
Implements
**IPurchaseEventManager**
GetPurchasedEventReadableHandle
- Used by Pokémon Café Mix
- Used by DOOM: Eternal
> aoc_u: Stub IPurchaseEventManager and its service commands

- src/video_core/engines/maxwell_3d.h
This is unused and removing it shrinks the structure by 3584 bytes. While we're at it we can resolve a nearby -Wdocumentation warning.
> maxwell_3d: Remove unused dirty_pointer array

- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
Some games such as NEKOPARA Vol. 3 send invalid device handles when calling InitializeVibrationDevice. Introduce a check to validate the device handle before use.
Fixes #5188
> controllers/npad: Validate device handles before use

- CMakeLists.txt
Addresses an issue with the two competing versions of Conan's Boost package that are currently floating around, in this case the newer one.
Adds the Boost::context target only if it's recognized by CMake as a target.
> cmake/conan: Conditionally add target Boost::context

- src/core/settings.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_debug.ui
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
- src/yuzu_cmd/yuzu.cpp
- src/yuzu_tester/config.cpp
- src/yuzu_tester/yuzu.cpp
The gdbstub itself was removed with https://github.com/yuzu-emu/yuzu/pull/5028.
This PR just removes the remaining gdb configuration code from the emulator and the UI.
> yuzu: Remove gdbstub configuration

- src/core/hle/service/nvflinger/buffer_queue.cpp
- src/core/hle/service/nvflinger/buffer_queue.h
- src/core/hle/service/vi/vi.cpp
The PR fixes a few inaccuracies in the buffer queue management, and uses a `std::array` for the fixed number of buffer slots.
Fixes freeze/crash on boot for: `Katana Zero`, `Yoshi's Crafted World`, `Deltarune`, `Dragon Ball FighterZ`, `Wonderboy` (And possibly other games).
Closes #3787 and closes #4987
> vi/buffer_queue: Buffer queue management refactor

- src/yuzu/main.cpp
- src/yuzu/main.h
- src/yuzu/main.ui
Allows to resize between 720p and 1080p depending if undocked or docked mode is selected.
Fixes #5175
>  Add option to reset window size to 1080p

- src/yuzu/debugger/profiler.cpp
- src/yuzu/debugger/wait_tree.cpp
- src/yuzu/main.cpp
- src/yuzu/main.ui
Adds a unique access key to each action within each menu. A few actions already had their own access key, so those were untouched.
> yuzu/main: Improve menubar access keys

- src/yuzu/main.cpp
- src/yuzu/main.h
Saves UISettings and Settings when booting a guest. Moves updating UISettings::values from GMainWindow::closeEvent into its own function, then reuses it in GMainWindow::BootGame.
> yuzu/main: Save settings when starting guest

- src/core/memory.cpp
There is a race between memory pages being accessed and the GPU marking them as cached by the rasterizer. This change adds a lock to alleviate this issue. I also addressed this in #5199, however that change added a bit of unnecessary overhead,
Thanks to @ReinUsesLisp for bringing this to my attention.
Supersedes #5199
> core: memory: Ensure thread safe access when pages are rasterizer cached

- CMakeLists.txt
- externals/CMakeLists.txt
- src/video_core/CMakeLists.txt
- src/video_core/video_core.cpp
- src/yuzu/CMakeLists.txt
- src/yuzu/bootmanager.cpp
- src/yuzu/configuration/configure_graphics.cpp
- src/yuzu/main.cpp
- src/yuzu_cmd/CMakeLists.txt
- src/yuzu_cmd/yuzu.cpp
Removes the unnecessary burden of maintaining separate #ifdef paths and allows us sharing generic Vulkan code across APIs.
~~This is missing CI changes, bear with me until it's happy.~~ Fixed.
> cmake: Always enable Vulkan

- src/video_core/CMakeLists.txt
- src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
Most of the time people write code that always returns a value,
terminates execution, throws an exception, or uses an unconventional
jump primitive.
This is not always true when we build without asserts on mainline builds.
To avoid introducing undefined behavior on our most used builds, enforce
this warning signalling an error and stopping the build from shipping.
> video_core: Enforce C4715 (not all control paths return a value)

- src/input_common/udp/client.cpp
Currently, each of the four pads in a single socket process all new data packets, regardless of whether the packet is actually relevant to them. This works fine when only one pad is used in a single socket (though redundant, as each packet is processed four times, and the same motion input is reported as four different devices), but with additional pads that would result in corrupted motion input, as motion inputs from different devices are processed together.
This PR fixes this issue, by checking the pad index of the incoming packet before processing it.
> input_common: process udp packets only for the correct pad

- src/core/hle/kernel/svc.cpp
This log is called often, and introduces a lot of noise when debug logging is enabled, making it difficult to see other debug logs.
> svc: demote SleepThread log to LOG_TRACE

- src/core/hle/kernel/k_scheduler_lock.h
This is needed as the header invokes methods on KernelCore.
> Add missing include of "core/hle/kernel/kernel.h"

- src/common/concepts.h
- src/core/hle/kernel/k_priority_queue.h
- For `std::same_as`, add missing include of `<concepts>`.
- For `std::convertible_to`, create a replacement in `common/concepts.h`
and use that instead.
This would also be found in `<concepts>`, but unlike `std::same_as`,
`std::convertible_to` is not yet implemented in libc++, LLVM's STL
implementation - not even in master.  (In fact, `std::same_as` is the
*only* concept currently implemented.  For some reason.)
> k_priority_queue: Fix concepts use

- src/CMakeLists.txt
- src/core/hle/service/pcie/pcie.cpp
Enforce `-Wuninitialized` treating it as an error on the whole project.
> cmake: Enforce -Wuninitialized

- src/video_core/renderer_vulkan/maxwell_to_vk.cpp
Silences a -Wmaybe-uninitialized warning
Fixes #5259
> maxwell_to_vk: Initialize usage variable in SurfaceFormat()

- src/input_common/sdl/sdl_impl.cpp
See citra-emu/citra#5509 for more details.
When mapping an analog trigger to a button, take two samples of an axis to determine the direction it's being moved, and override the event value to be saturated in that direction if it's been moved enough to count as an event.
> Port citra-emu/citra#5509 "Look at direction of analog axis travel instead of instantaneous sample"

- src/audio_core/algorithm/interpolate.cpp
lut_index had 0 added when nothing was supposed to be added
despite this, index was not added to 0 when nothing was supposed to be added...
> Make the coding conventions more consistant

- .ci/templates/build-msvc.yml
Previously this flag was missing, causing translation files not to be shipped with CI builds of yuzu.
> .ci/templates: Enable QT translation for MSVC CI

- src/common/page_table.cpp
- src/common/page_table.h
- src/common/virtual_buffer.h
- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_64.cpp
- src/core/hle/kernel/memory/page_table.cpp
- src/core/memory.cpp
Squash attributes into the pointer's integer, making them an uintptr_t
pair containing 2 bits at the bottom and then the pointer. These bits
are currently unused thanks to alignment requirements. By doing this
we no longer have to use a mutex to write and read the page table.
Configure Dynarmic to mask out these bits on pointer reads.
While we are at it, remove some unused attributes carried over from
Citra.
Read/Write and other hot functions use a two step unpacking process that
is less readable to stop MSVC from emitting an extra AND instruction in
the hot path:
```diff
mov         rdi,rcx
shr         rdx,0Ch
mov         r8,qword ptr [rax+8]
mov         rax,qword ptr [r8+rdx*8]
mov         rdx,rax
-and         al,3
and         rdx,0FFFFFFFFFFFFFFFCh
je …
```
> core/memory: Read and write page table atomically

- src/yuzu/applets/controller.cpp
- src/yuzu/configuration/configure_input.cpp
- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/configuration/configure_input_player.h
Increases the controller connection delay to 60ms and refactors it to attempt to disconnect all controllers prior to connecting all controllers in HID.
This change is necessary due to #5208
Also, this should be merged **after** #5208
> configure_input: Modify controller connection delay

- src/yuzu/main.cpp
Allows the dialog text to be fully translated, as opposed to only the title. While we're at it, we can add annotation comments to explain what the contents of the formatting specifiers are for translators.
> main: Make the loader error dialog fully translatable 

- CMakeLists.txt
See citra-emu/citra#5668 for more details.
Silences a warning on newer CMake versions about CMake < 2.8.12 support.
The update may also result in a 5% increase in decompression performance, according to https://github.com/facebook/zstd/releases/tag/v1.4.5
> Port citra-emu/citra#5668: "Update zstd to v1.4.8"

- src/core/hle/service/nvflinger/buffer_queue.cpp
- This behavior is a mistake, fixes Katana Zero.
> hle: service: nvflinger: buffer_queue: Do not reset id/layer_id on Connect.

- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_64.cpp
- src/core/settings.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_cpu.cpp
- src/yuzu/configuration/configure_cpu.ui
Here are less accurate versions of some things that aren't numbers.
---
In this commit we introduce a new unsafe "optimization", we add an option to remove NaN checks from JITted code. Do note that this means that the NaNs produced will not be bit-perfect with hardware.
Also **please note that this removes some checks for certain special values**, thus this produce incorrect finite results. Here are the two cases where incorect values are wrongly produced when this unsafe option is enabled:
* FRSQRTS will produce a NaN for certain large inputs (where previously it would have produced a value >10^38).
* FMA will sometimes produce a negative zero where previously a positive zero was produced.
I chose to keep NaN checks in FMULX/FMINNM/FMAXNM and related instructions that special case NaN …
> dynarmic: Add Unsafe_InaccurateNaN optimization

- src/core/loader/loader.cpp
- src/core/loader/loader.h
- src/yuzu/main.cpp
During the transition to make the error dialog translatable, I accidentally got rid of the conversion to ResultStatus, which prevented operator<< from being invoked during formatting.
This adds a function to directly retrieve the result status string instead so that it displays again.
> main: Resolve error string not displaying

- src/core/hle/service/nvflinger/buffer_queue.cpp
- src/core/hle/service/nvflinger/buffer_queue.h
Fixes a data race introduced by #5208 where `queue_sequence` was accessed and manipulated by multiple threads, but was not protected.
Thanks to @ReinUsesLisp for a reproducible test scenario confirming the data race and its fix.
> buffer_queue: Fix data race by protecting queue_sequence access

- src/yuzu/bootmanager.cpp
- src/yuzu/bootmanager.h
- src/yuzu/main.cpp
- src/yuzu/main.h
The mouseMoveEvent never gets triggered for some reason, causing the mouse to never reappear, unless pressed or moved to the menu bar. Using eventFilter instead solves this issue.
I don't have a lot of experience with Qt, so any suggestions/alternative solutions are welcome.
> yuzu/main: Fix 'Hide mouse on inactivity' and port citra-emu/citra#5476

- src/video_core/renderer_vulkan/vk_rasterizer.cpp
Fixes unit tests where compute shaders had no descriptors in the set, making Vulkan drivers crash when binding an empty set.
> vk_rasterizer: Skip binding empty descriptor sets on compute

- src/core/CMakeLists.txt
- src/core/crypto/key_manager.cpp
- src/core/file_sys/nca_patch.cpp
- src/core/file_sys/registered_cache.cpp
- src/core/hle/kernel/memory/address_space_info.cpp
- src/core/hle/service/sockets/sockets_translate.cpp
Same as #5226 but for `core`.
On some instances a reference was being returned, so I replaced `UNREACHABLE` with an exception.
> core: Enforce C4715 (not all control paths return a value)

- .ci/scripts/common/post-upload.sh
- .ci/scripts/common/pre-upload.sh
- .ci/scripts/linux/docker.sh
- .ci/scripts/linux/upload.sh
This builds yuzu in an [AppImage](https://appimage.org/) alongside the other archives during release. Required to allow distributing yuzu in the future with upgraded dependencies, such as Qt. As a result of using an AppImage, we remove the need for users to install dependencies before running yuzu on wild Linux distros. Since the build system recently switched to Ubuntu 18.04, this change also brings yuzu back to Ubuntu 18.04, Debian Buster, CentOS 8, and similar.
There are a few changes of note to make this possible:
- Puts the `artifacts/` directory into a variable. The variable is used to directly copy the AppImage to `artifacts/` from within the Linux-specific scripts.
- Reverts to using GNU Make in order to install yuzu to a custom directory.
- Downloads needed tools at build time to …
> ci/linux: Build an AppImage

- src/video_core/compatible_formats.cpp
- src/video_core/compatible_formats.h
- src/video_core/renderer_opengl/gl_device.cpp
- src/video_core/renderer_opengl/gl_device.h
- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_opengl/gl_texture_cache.h
- src/video_core/renderer_vulkan/vk_texture_cache.h
- src/video_core/texture_cache/image_base.cpp
- src/video_core/texture_cache/image_view_base.cpp
- src/video_core/texture_cache/texture_cache.h
- src/video_core/texture_cache/util.cpp
- src/video_core/texture_cache/util.h
Workaround for broken drivers. Description in the commits.
> gl_texture_cache: Avoid format views on Intel and AMD

- src/video_core/vulkan_common/vulkan_library.cpp
Ignore the return value on \_\_APPLE\_\_ systems as well (same as the non-\_\_APPLE\_\_ case).
Just want yuzu to build on my local systems thanks.
> vulkan_library: Common::DynamicLibrary::Open is [[nodiscard]]

- CMakeLists.txt
Boxcat is a web service but is still enabled despite ENABLE_WEB_SERVICE's state during CMake generation, causing compilation issues with either missing headers or missing libraries.
If ENABLE_WEB_SERVICE is disabled, this disables YUZU_ENABLE_BOXCAT.
...Apparently, this also strips trailing spaces in the main CMakeLists.txt.
Closes #3269
(The root of that issue from long ago has been otherwise fixed or disappeared. This just fixes a newer issue using the same parameters.)
> CMakeLists: Disable YUZU_ENABLE_BOXCAT if ENABLE_WEB_SERVICE is disabled

- README.md
The MacOS build link was removed in the README.md because it no longer exist.
> Removed MacOS build link

- src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
- src/video_core/renderer_vulkan/fixed_pipeline_state.h
- src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Without using VK_EXT_robustness2, we can't consider the 'enabled' (not null) vertex buffers as dynamic state, as this leads to invalid Vulkan state. Move this to static state that is always hashed and compared in the pipeline key.
The bits used for enabled vertex buffers are moved into the attribute state bitfield. This is not 'correct' as it's not an attribute state, but that struct has bits to spare, and it's used in an array of 32 elements (the exact same number of vertex buffer bindings).
> renderer_vulkan/fixed_pipeline_state: Move enabled bindings to static state

- src/CMakeLists.txt
- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/file_sys/registered_cache.h
- src/core/hle/service/nvflinger/buffer_queue.cpp
- src/tests/common/ring_buffer.cpp
This should match some warnings we treat as errors on gcc and clang (-Wswitch and -Wreorder), catching bugs early and reducing the number of instances where we have to edit commits to make CI happy when developing from Windows.
> cmake: Enforce C4062, C4265, C4388, and C5038

- src/common/div_ceil.h
Fixes instances where DivCeil(u32, u64) would surprisingly return u64, instead of the more natural u32.
> common/div_ceil: Return numerator type

- src/CMakeLists.txt
- src/yuzu_cmd/yuzu.cpp
This matches GCC's -Wunused-variable
> cmake: Enforce C4101

- src/yuzu/configuration/config.cpp
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
- src/yuzu_tester/config.cpp
- src/yuzu_tester/default_ini.h
Enables the docked mode by default.
This has 2 advantages:
1. Makes games run at their best quality/resolution.
2. A workaround for the SMO flickering issue when GLASM (OpenGL Assembly Shaders) is enabled with a NVIDIA GPU in undocked mode.
> config: Enable docked mode by default

- src/common/intrusive_red_black_tree.h
- src/common/parent_of_member.h
Provides the same construct, but makes it obey namespacing.
This also reduces the likelihood of clashing with other libraries, given `TYPED_STORAGE` is quite generic for a preprocessor define
> common/parent_of_member: Replace TYPED_STORAGE define with template alias

- src/common/logging/backend.cpp
See citra-emu/citra#5666 for more details.
Particularly useful for Android as Android will immediately restart the app/Activity if it crashes, immediately overwriting the old log file before it can be read. Also could be useful for the common case of users restarting Citra and overwriting their log on Desktop.
> Port citra-emu/citra#5666: "Rotate previous log file to "citra_log.txt.old""

- src/CMakeLists.txt
switch is equivalent to MSVC's C4062
unused-variable is equivalent to MSVC's C4101
> cmake: Enforce -Werror=switch and -Werror=unused-variable

- src/video_core/vulkan_common/vulkan_device.cpp
yuzu doesn't currently emulate MS image stores. Requiring this makes no
sense for now. Fixes ANV not booting any games on Vulkan.
Closes #5338.
> vulkan_device: Remove requirement on shaderStorageImageMultisample

- src/yuzu/bootmanager.cpp
- src/yuzu/game_list.cpp
`setMargin()` has been deprecated since Qt 5, and replaced with `setContentsMargins()`. We can move to `setContentsMargins()` to stay forward compatible with Qt 6.0 whenever we update to it.
> yuzu: Migrate off of setMargin() to setContentsMargins()

- src/yuzu/configuration/configure_motion_touch.cpp
Fixes error introduced in #5156. Where the last octet produced an error if the value was higher than 199. For example 192.168.1.200 
This is caused by the break line in the string. Putting the string in a single line fixes the issue.
> Fix IP validator error

- src/yuzu/configuration/configure_motion_touch.cpp
`touch_engine` was being compared against after being moved into the setter for the engine, so this comparison wouldn't behave properly.
> configure_motion_touch: Prevent use after move in ApplyConfiguration()

- src/yuzu/configuration/configure_motion_touch.cpp
`QRegularExpression` was introduced in Qt 5 as a better replacement for `QRegExp`. In Qt 6.0 `QRegExp` is removed entirely.
To remain forward compatible with Qt 6.0, we can transition over to using `QRegularExpression`.
> configure_motion_touch: Migrate off QRegExp to QRegularExpression

- src/yuzu/configuration/configure_dialog.cpp
- src/yuzu/configuration/configure_motion_touch.cpp
Removes two unused variables in out Qt code. In this case the removal of these two results in less allocations, given std::map allocates on the heap.
> yuzu: Remove unused variables in Qt code

- .ci/scripts/linux/docker.sh
- .ci/scripts/linux/upload.sh
Moves the final step for building the AppImage to the upload script. Instructs appimagetool to embed update information into the AppImage if the release target is Mainline. Also tells it to create a zsync file to enable partial-downloads when updating the AppImage.
Renames the AppImage from `yuzu-{version info}-x86_64.AppImage` to `yuzu-{version info}.AppImage` to avoid a bug in the downloads page at https://yuzu-emu.org/downloads.
This needed to be a followup to #5250 in order to allow local testing with update files after a Mainline release was made live.
Requires yuzu-emu/build-environments#25 before merging
> ci/linux: Make Mainline AppImages updateable

- src/video_core/textures/astc.cpp
Games can bind invalid textures that make us read or write out of bounds, to avoid exploding on these illegal textures; handle them gracefully with regular robustness techniques.
- Fixes ASTC address sanitizer errors on Astral Chain, and regular crashes when on regular gcc builds.
> astc: Make the decoder more robust to invalid data

- src/CMakeLists.txt
- src/video_core/CMakeLists.txt
- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
Stops us from merging code with unused functions in the future.
If something is invoked behind conditionally evaluated code in
a way that the language can't see it (e.g. preprocessor macros), the
potentially unused function should use [[maybe_unused]].
> cmake: Enforce -Wunused-function code-base wise

- src/core/CMakeLists.txt
- src/video_core/CMakeLists.txt
These flags are already defined in src/cmake.
> {video_,}core/cmake: Remove Werror flags already defined code-base wide 

- src/common/alignment.h
- src/video_core/texture_cache/accelerated_swizzle.cpp
- src/video_core/texture_cache/util.cpp
- src/video_core/textures/decoders.cpp
AlignUpLog2 describes what the function does better than AlignBits.
`clang-format` changes the formatting of this between versions, adding a space before `[[nodiscard]]`. CI formatting should validate if I got this right.
> common/alignment: Rename AlignBits to AlignUpLog2 and use constraints

- src/audio_core/sink_context.h
- src/common/common_funcs.h
- src/core/file_sys/content_archive.cpp
- src/core/hle/ipc.h
- src/core/hle/service/am/applets/error.cpp
- src/video_core/engines/fermi_2d.h
- src/video_core/engines/kepler_compute.h
- src/video_core/engines/kepler_memory.h
- src/video_core/engines/maxwell_3d.h
- src/video_core/engines/shader_header.h
- src/video_core/gpu.h
`INSERT_PADDING_BYTES_NOINIT` is more descriptive of the underlying behavior.
> common/common_funcs: Rename INSERT_UNION_PADDING_{BYTES,WORDS} to _NOINIT

- src/core/frontend/input_interpreter.cpp
- src/core/frontend/input_interpreter.h
This allows to check for continuous input for the duration of a button press/hold
> input_interpreter: Add method to check for a button press state

- src/tests/CMakeLists.txt
- src/tests/video_core/buffer_base.cpp
- src/video_core/CMakeLists.txt
- src/video_core/buffer_cache/buffer_base.h
This keeps track of the modified CPU and GPU ranges on a CPU page granularity, notifying the given rasterizer about state changes in the tracking behavior of the buffer.
The buffer takes advantage of C++20's `<bit>` operations when possible to check for modified pages on a 256 KiB range as fast as possible. On MSVC this will use CPU extensions when available branching at runtime.
Due to how error prone the container design is, I've added unit tests for it. Some tests are based on bugs found using this buffer in games, so if we ever break it in the future in a way that might harm commercial games, the tests should fail.
This is part of the buffer cache rewrite, it doesn't currently change yuzu's behavior aside from the tests.
> buffer_cache/buffer_base: Add a range tracking buffer container and tests

- src/core/frontend/input_interpreter.h
These aren't stateful functions, so we can make use of const.
While we're at, we can resolve some -Wdocumentation warnings.
> input_interpreter: Mark two member functions as const

- src/video_core/buffer_cache/buffer_base.h
- src/video_core/vulkan_common/vulkan_memory_allocator.h
Silences some -Wdocumentation warnings on Clang.
Also fixes a minor typo, given we're in the same area.
> video_core: Resolve -Wdocumentation warnings

- src/core/hle/service/hid/controllers/npad.cpp
Ensures the handheld controller is only connected if the correct npad_index is sent
> npad: Add check for HANDHELD_INDEX in UpdateControllerAt()

- src/yuzu/configuration/configure_service.cpp
The function is unused if YUZU_ENABLE_BOXCAT is disabled, causing a `-Wunused-function` error when compiled using GCC.
I am wrapping it with `#ifdef YUZU_ENABLE_BOXCAT` to prevent compiling the function when the variable is disabled. I am opting to not use `[[maybe unused]]` in case the function is totally unused in the future.
> configure_service: Only compile FormatEventStatusString when YUZU_ENABLE_BOXCAT is enabled

- src/video_core/texture_cache/util.cpp
Resolves a -Wsign-compare warning on Clang.
> texture_cache/util: Resolve -Wsign-compare warning

- src/yuzu/game_list.cpp
- src/yuzu/game_list_p.h
See citra-emu/citra#5344 for more details.
The bug(s) happened because we swapped the contents on values.game_dirs, but the pointer each item had to their respective game_dir wasn't updated. This made it so that the item had the wrong game_dir associated with it after a "move up" or "move down" operation. It can be observed by choosing "open directory location" after such operation.
Changed from raw pointer to an index because it's equivalent but a bit clearer, but the change is not essential.
> Port citra-emu/citra#5344: "game_list: Fix folder reordering"

- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_input_player.cpp
The default connected value when loading the player 1 is true and the default connected value when saving the player 1 was false. Because of this the player 1 was always on, regardless of the config. 
Handheld configuration is a copy of the configuration of player 1 but the configuration only was updated when handheld was turned on for the first time.
This PR addresses both issues. By fixing the default value for player 1 and always updating the configuration for handheld when it's turned on.
> Fix player 1 turning on handheld and not updating handheld settings

- src/common/bit_util.h
We can use the standardized CLZ facilities to perform this in a platform-agnostic manner. This also allows us to make utilizing functions constexpr and eliminate the inclusion of an intrinsics header.
Should we also unify the 32 and 64 variants together?
> bit_util: Unify implementations of MostSignificantBit32/MostSignificantBit64

- CMakeLists.txt
Update conan package version used for building.
A couple of new joystick-related functions might pose interest to yuzu's input system. Some sort of LED management have been added, but it doesn't seem to support leds used for player number indication JoyCons/ProCons use.
> Bump conan SDL2 version to 2.0.14

- src/input_common/sdl/sdl_impl.cpp
Some games do not send a 0 amplitude vibration to stop residual vibrations. This sets the maximum duration for any vibration to 1 second.
Fixes #5026
> sdl_impl: Set the maximum vibration duration to 1 second

- src/core/hle/service/am/am.cpp
This one should be OK to stub for now. Used by Monster Hunter Rise demo.
> hle: service: am: Stub ILibraryAppletAccessor::PresetLibraryAppletGpuTimeSliceZero.

- src/video_core/host_shaders/CMakeLists.txt
Silence noisy builds on toolchains.
> host_shaders/cmake: Pass --quiet to glslang to keep it quiet

- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
The VertexA stage is not yet implemented, but Vulkan is adding its
descriptors, causing a discrepancy in the pushed descriptors and the
template. This generally ends up in a driver side crash.
Bypass the VertexA stage for now.
- Fixes a crash on World of Final Fantasy Maxima.
> vk_pipeline_cache: Properly bypass VertexA shaders

- src/video_core/vulkan_common/vulkan_device.cpp
It seems to be safe to use this on new drivers.
> vulkan_device: Lift VK_EXT_extended_dynamic_state blacklist on RDNA

- src/core/file_sys/vfs_real.cpp
Found this via a warning, but it's a substantive fix.
Since this is only for a cache, it should be safe to silently drop the entry if opening fails.  I think.
> vfs_real: When moving files or directories, don't assume file opening will succeed

- src/video_core/renderer_vulkan/maxwell_to_vk.cpp
- src/video_core/renderer_vulkan/maxwell_to_vk.h
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
Vulkan 1.0 didn't support creating sRGB image views on an ABGR8 VkImage
with storage usage bits. VK_KHR_maintenance2 addressed this allowing to
reduce the usage bits on a VkImageView.
To allow image store on non-sRGB image views when the VkImage is created
with sRGB, always create VkImages without sRGB and add the sRGB format
on the view.
> vk_texture_cache: Support image store on sRGB images with VkImageViewUsageCreateInfo

- src/video_core/shader/node.h
- src/video_core/shader/shader_ir.cpp
- src/video_core/shader/shader_ir.h
This reverts #4713. The implementation in that PR is not accurate.
It does not reflect the behavior seen in hardware.
Closes #5817
> Revert "Start of Integer flags implementation"

- src/video_core/memory_manager.cpp
- src/video_core/memory_manager.h
When we copy into a buffer, it might contain data modified from the GPU
on the same pages. Because of this, we have to flush the contents before
writing new data.
An alternative approach would be to write the data in place, but games
can also write data in other ways, invalidating our contents.
- Fixes geometry in Zombie Panic in Wonderland DX.
> video_core/memory_manager: Flush destination buffer on CopyBlock

- src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
Fixes softlocks in pokemon lets go caused by Nvdec.
Fixed softlock caused by leon in sword and shield
> nvdrv: Unregister already registered events

- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
- src/core/hle/service/hid/hid.cpp
Inserts padding in `Parameters` struct where applicable and removes unused device handle function parameters
> hid: Cleanup SixAxisFusionParameters

- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/service/prepo/prepo.cpp
Fixes #4050
The second input buffer could be optional when prepo/srepo is called, test for the availability of the second buffer prior to reading from it.
> prepo: Fix BufferDescriptorX invalid buffer index errors and add New variants of SaveReport

- src/core/hle/service/sockets/bsd.cpp
- src/core/hle/service/sockets/bsd.h
Stubs GetSocktOpt by returning not connected error, needed for Scott Pilgrim vs The World. Allows to proceed in game.
> sockets: Stub GetSockOpt

- src/yuzu/configuration/configure_input.cpp
- src/yuzu/configuration/configure_input_player.cpp
Increases delay before and after connecting the controllers to reduce the chance of missing the event. Adds more rules to prevent sending invalid events like disconnecting a controller that it's already disconnected or the other way around. Rewrites handheld event handling to apply the same rules as the other controllers.
This fixes Pokemon let's go controller selection.
> Fix connect and disconnect controller events

- src/video_core/memory_manager.cpp
- src/video_core/memory_manager.h
Track map address sizes in a flat ordered map and add a method to query the number of bytes until the end of a map in a given address. This is required for binding extra bytes in guest SSBOs.
I'm open to suggestions for the name "BytesToMapEnd".
I'll push these changes to #5741, so this PR shouldn't be tagged for EA. I'll rebase that PR when this is merged.
> video_core/memory_manager: Add BytesToMapEnd

- src/core/hle/service/sockets/bsd.cpp
GetSockOpt writes an output buffer of optval and u32 optlen
> bsd: Fix GetSockOpt stub

- src/input_common/analog_from_button.cpp
This PR aims to address an exception that sometimes occurs when trying to join the Analog object's `update_thread` when launching a title.
By using an atomic bool for the status of the update thread, we ensure its value is consistent across the threads accessing it, and avoid trying to join a thread that was never running.
> analog_from_button: Fix update_thread.join exception

- src/core/hle/service/nifm/nifm.cpp
Stub GetCurrentNetworkProfile
- Used by Minecraft Bedrock Edition
- Used by Bloons TD 5
Stub GetCurrentIpConfigInfo
- Used by Lets Sing 12
> nifm: Stub GetCurrentNetworkProfile and GetCurrentIpConfigInfo

- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_32.h
Eases debugging if we know the processor is in thumb mode.
> arm_dynarmic_32: Print out CPSR.T on exception

- src/core/hle/service/hid/hid.cpp
We don't need to call a motion update event for all HID types only for Npad. 
At boot events get delayed when loading contents. This causes a positive loop where we start scheduling events with negative time. Since updating input is not critical we can safely schedule the next event without compensating for the delay giving the computer time to recover.
> hid: Only update motion for npad and prevent over scheduling events

- src/yuzu/configuration/configure_profile_manager.cpp
RetranslateUI overwrites the username to the default. Call the function first so the username isn't overwritten.
> Avoid overwriting username

- src/core/hle/service/acc/profile_manager.cpp
When loading the profile manager and opening the selected user it will always load the first user if the user selected exist. This is not intended. This PR corrects such behavior and only resets the selected user if the selected user exist. 
This fixes the crash in SSBU when the second user is selected.
> acc: Fix error when second user is selected

- src/audio_core/command_generator.cpp
As this is causing issues in a few games, it's best to have it disabled until it's completely implemented
> audren: Disable reverb for the time being

- src/yuzu/configuration/configure_input_player.cpp
Handheld wasn't updating if is not selected. Resulting in multiple errors.
> config: Always update handheld config

- src/core/crypto/key_manager.cpp
Removes the need for the user to create the keys directory manually
> key_manager: Create the keys directory if it does not exist

- src/core/hle/kernel/k_affinity_mask.h
This can cause compiler warnings. Instead, we can explicitly add a boolean expression around it to naturally turn the result into a bool.
> k_affinity_mask: Avoid implicit truncation to bool

- src/video_core/host_shaders/CMakeLists.txt
Prevents CMake from calling `glslangValidator` with `--quiet` when it is not available, i.e. on older downstream versions from Ubuntu.
Needs testing on the MSVC toolchain before merge (someone else needs to do that, I can't test it locally.)
> video_core: host_shaders: Don't pass --quiet to glslangValidator if unavailable

- src/core/hle/kernel/k_priority_queue.h
Mainly to remove the usage of a reserved identifier, but some other minor things were able to be tidied up.
> k_priority_queue: Minor cleanup

- src/core/hle/service/am/applets/controller.cpp
- src/core/hle/service/hid/controllers/keyboard.cpp
- src/core/hle/service/hid/controllers/keyboard.h
- src/core/hle/service/hid/controllers/mouse.cpp
- src/core/hle/service/hid/controllers/mouse.h
- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
- src/core/hle/service/hid/controllers/xpad.h
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
- src/yuzu/configuration/configure_input_player.cpp
Updates the HID service to match more closely to switchbrew. Functionality wise nothing should be changed.
- Adds missing controller types and properties.
- Renames properties names to match switchbrew
> HID: Update the HID service to match more closely to switchbrew part 1

- src/common/ring_buffer.h
- src/tests/common/ring_buffer.cpp
There was a bug in `RingBuffer::Push(std::vector<T>&)` when granularity != 1.
Just remove it altogether because we do not have a use for granularity != 1.
> ring_buffer: Remove granularity template argument

- src/core/hle/service/ns/pl_u.cpp
Closes #5291 #5825 
Few things to note:
* Please verify that behaviour is unchanged on windows. On linux the web applet currently doesn't work anyways.
* I removed `transformed_font[1] = Common::swap32(transformed_font[1]) ^ KEY; // "re-encrypt" the size` cause I can only assume it was a wrong copy-paste from above.
* ~~Weirdly enough removing that line (or any transformed_font[x] = y line) makes the compiler warn with~~
>   [1/5] Building CXX object src/core/CMakeFiles/core.dir/hle/service/ns/pl_u.cpp.o
>   ../src/core/hle/service/ns/pl_u.cpp: In function ‘void Service::NS::DecryptSharedFontToTTF(const std::vector&, std::vector&)’:
>   ../src/core/hle/service/ns/pl_u.cpp:73:16: warning: ‘void* memcpy(void*, const void*, size_t)’ specified bound 18446744073709551608 exceeds maximum object …
> pl_u: Fix read out of bounds

- src/core/hle/service/lm/lm.cpp
Fixes assertion on Bloodstained Ritual of the Night.
We would over read sometimes, this is fixed by checking if the top bit is set in the first iteration. We also lock the loop off to be only the max size of the type we can fit. Finally we changed an incorrect print of "DEBUG" to "TRACE" to reflect the proper log severity
> lm: Fix ReadLeb128

- src/video_core/CMakeLists.txt
moron.h & morton.cpp are not used anywhere and are just empty files
> video_core: Delete morton

- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/yuzu/bootmanager.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
This updates the OpenGL backend version requirement from 4.3 to 4.6 for both the Qt and SDL frontends.
With this, we can remove checks for extensions added prior to OpenGL 4.6.
> renderer_opengl: Update OpenGL backend version requirement to 4.6

- src/common/string_util.cpp
This has been fixed as of Visual Studio 2019 Version 16.2
> string_util: Remove MSVC workaround for converting between UTF8/UTF16

- src/audio_core/stream.cpp
- src/core/hle/service/hid/hid.cpp
Similar to #5861 audio stream can schedule events in negative time. This can be noticeable when you pause the game for a long period of time and then unpause it. The game will stutter and lag for quite some time until the audio event get's back to positive time.
This PR also adds a missing UnscheduleEvent for the motion update event.
> Prevent over scheduling audio events and add motion update unschedule event

- .ci/scripts/windows/docker.sh
- .gitmodules
- CMakeLists.txt
- externals/find-modules/FindFFmpeg.cmake
- src/video_core/CMakeLists.txt
- src/video_core/command_classes/codecs/codec.cpp
This adds [FFmpeg](https://ffmpeg.org/) as a submodule and builds/statically links to it on Linux. MSVC is unchanged for the most part. MinGW now uses the same libraries as MSVC, thus fixing the dynamic linking issues with [Martchus](https://github.com/Martchus/PKGBUILDs)'s FFmpeg libraries.
When configuring the submodule on Linux, it disables almost everything from FFmpeg and compiles exactly what yuzu needs. ("Exactly" as far as I know, maybe more can be disabled.) Compile times shouldn't take too much of a hit since yuzu uses only a bit of FFmpeg.
Ports FindFFmpeg.cmake from ctira-emu/citra with minor modifications (see relevant commit). This in turn fixes a couple odd warnings/errors during CMake configuration.
Adds the variable `YUZU_USE_BUNDLED_FFMPEG` to instruct CMake on where to …
> cmake: FFmpeg linking rework

- CMakeLists.txt
- CMakeModules/CopyYuzuFFmpegDeps.cmake
The 4.3.1 externals build seems to not be compatible with yuzu. 
This also fixes an oversight for a renamed CMake variable.
> cmake: Revert FFmpeg 4.3.1 update for Windows builds

- src/yuzu/configuration/configure_input_player_widget.cpp
- src/yuzu/configuration/configure_input_player_widget.h
Makes the Joysticks of the Pro Controller preview have a little depth
Comparison:
> Settings: Add depth to Joysticks on Pro Controller preview

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/texture_cache/util.cpp
Resolves some warnings on Clang 12.
> video_core: Remove unused functions and variables

- src/input_common/udp/client.cpp
- src/input_common/udp/client.h
- src/input_common/udp/udp.cpp
Allows the UDP code to successfully compile on Clang 12
> udp: Silence warnings on Clang 12

- src/yuzu/configuration/configure_input_player_widget.cpp
Prevents Clang 11 from throwing an error since these variables are unused.
> configure_input_player_widget: Silence unused variable warnings

- src/core/CMakeLists.txt
Prevents an operator delete error when compiling with Clang 11.
> core: Add -fsized-dealloction as a Clang flag

- src/common/CMakeLists.txt
Prevents an operator delete error when compiling with Clang 11.
> common: Add -fsized-deallocation as a Clang flag

- src/core/hle/service/am/applets/software_keyboard.cpp
Implements the Finalize request command according to hardware tests. This is fairly trivial to implement as it requests the applet to exit. The attached homebrew is used to verify the behavior on hardware.
Before (failed to process the finalize request):
After (successfully processed the finalize request):
[software-keyboard-finalize.zip](https://github.com/yuzu-emu/yuzu/files/5963316/software-keyboard-finalize.zip)
Further tests will be conducted to verify/fix the rest of the software keyboard implementation
> software_keyboard: Implement Finalize request command

- src/core/settings.h
- src/input_common/mouse/mouse_input.cpp
- src/input_common/mouse/mouse_input.h
- src/input_common/mouse/mouse_poller.cpp
- src/yuzu/bootmanager.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/config.h
- src/yuzu/configuration/configure_input_advanced.cpp
- src/yuzu/configuration/configure_input_advanced.ui
- src/yuzu/main.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Adds mouse panning without clicks for analog joysticks under advanced controller configuration. Since this option hides and fixes the mouse to the center of the window I added the shortcut key F9 to toggle this setting on runtime.
> input_common: Add mouse panning

- src/core/hle/service/am/applets/controller.cpp
- src/core/hle/service/nfp/nfp.cpp
- src/core/hle/service/sockets/bsd.cpp
Allows Clang 12 to successfully build the core library. Also resolves an uninitialized read.
> core: Silence various warnings on Clang 12

- src/core/CMakeLists.txt
- src/core/hle/kernel/k_scoped_resource_reservation.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/memory/page_table.cpp
- src/core/hle/kernel/process.cpp
- src/core/hle/kernel/session.cpp
- src/core/hle/kernel/shared_memory.cpp
- src/core/hle/kernel/svc.cpp
- src/core/hle/kernel/transfer_memory.cpp
This PR aims to more accurately utilize the `resource_limit` to reserve and release resources closer to the way the hardware does.
There is one major inaccuracy which has not been addressed yet, which is the `Process`'s resource limit usage. Currently, each new `Process` creates its own `KResourceLimit`, when it should instead use the system wide resource limit. 
This is critical particularly for `Process::GetTotalPhysicalMemoryAvailable()`, which must return a very specific result, but this requires complete accuracy with the kernel resource reservation, and currently differs in its accuracy from one title to the next. 
This leads me to believe that the size reported as required for each title may be innacurate. For now, Processes continue to create their own resource limit until it can …
>  kernel: More accurately utilize resource_limit

- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
We are already using robustness2 features without requiring it
explicitly, causing potential crashes on drivers without the extension.
Requiring this at boot allows better diagnostics for it and formalizes
our usage on the extension.
> vulkan_device: Require VK_EXT_robustness2

- src/yuzu/main.cpp
Allows screenshots to save in cases where the screenshots path doesn't already exist.
> yuzu: Create screenshot path before capture

- src/video_core/renderer_opengl/gl_stream_buffer.cpp
- src/video_core/renderer_vulkan/vk_master_semaphore.h
- src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
Fix a tragic off-by-one condition that causes Vulkan's stream buffer to
think it's always full, using fallback memory. The OpenGL was also
affected by this bug to a lesser extent.
> gl_stream_buffer/vk_staging_buffer_pool: Fix size check

- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_opengl/gl_texture_cache.h
- src/video_core/renderer_opengl/util_shaders.cpp
As a follow-up to #5288, This lazily creates non-sRGB texture views for sRGB texture formats when being used in compute shaders, particularly for imageLoad and imageStore.
> gl_texture_cache: Lazily create non-sRGB texture views for sRGB formats

- src/core/CMakeLists.txt
- src/core/hle/service/am/am.cpp
- src/core/hle/service/ldn/errors.h
- src/core/hle/service/ldn/ldn.cpp
Two related changes that fix the crash in Pokemon Sword/Shield when pressing 'Y'. Note, you will still get an error, but the game will keep running
* hle: service: ldn: IUserLocalCommunicationService: Indicate that LDN is disabled.
* Fixes crash on Pokemon Sword/Shield when pressing 'Y'.
* hle: service: am: IStorageAccessor: Fix out of bounds error handling.
> Fix LDN Initialization return code & resulting AM overflow

- src/yuzu/debugger/controller.cpp
Adds the access key to the Controller P1 selection at View -> Debugger -> Controller P1. Avoids using the windowTitle as that would add a literal & to the beginning of the window title.
> debugger: controller: Add access key

- src/core/CMakeLists.txt
Looks like I forgot to add this in the web applet PR, oops
> core/CMakeLists: Add web_types.h

- src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
- src/video_core/renderer_vulkan/fixed_pipeline_state.h
- src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.h
- src/video_core/renderer_vulkan/vk_state_tracker.cpp
- src/video_core/renderer_vulkan/vk_state_tracker.h
Use dirty flags to avoid building pipeline key from scratch on each draw call. This saves a bit of unnecessary work on each draw call.
Increases 1 to 2 frames per second on SMO on Lost Kingdom.
> fixed_pipeline_cache: Use dirty flags to lazily update key

- src/input_common/sdl/sdl_impl.cpp
See citra-emu/citra#5123 for more details.
The change of SDL2 from 2.0.8 to 2.0.10 broke compatibility with some controllers that reported as Switch and Xbox One controllers.
Having SDL_HINT_JOYSTICK_HIDAPI set to "0" should get us the same behavior as before the change, as all of the reported problems stem from joysticks that have a hidapi driver implementation.
From some investigation, the current drivers try to write to the controller, for setting rumble, stick calibration, LED behavior and other similar tasks. 
Most or all of the users that had this problem and identified their controllers had non-official versions of the controllers. From the available information some of these controllers don't have some of the features the driver tries to use, and the …
> Port citra-emu/citra#5123: "SDL: Disable hidapi drivers due to compatibility problems with certain controllers"

- src/video_core/renderer_vulkan/vk_rasterizer.cpp
This was recently introduced on a wrongly rebased commit.
> vk_rasterizer: Fix loading shader addresses twice

- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_filesystem.cpp
- src/yuzu/configuration/configure_filesystem.h
- src/yuzu/configuration/configure_filesystem.ui
- src/yuzu_cmd/config.cpp
This tab of the settings is already extremely bloated and the setting itself is quite useless.
With a gamelist of almost 30 games, the cache directory is smaller than 1MB for me and therefore I don't see why it needs to be configurable.
> yuzu/configure_filesystem: Remove "Select Cache Directory" option

- .gitmodules
- CMakeLists.txt
- CMakeModules/CopyYuzuFFmpegDeps.cmake
Download FFmpeg package version 4.3.1. Uses a file defined within the package to determine with DLLs to copy. Also corrects a submodule name.
> cmake: Update FFmpeg to 4.3.1

- src/common/cityhash.cpp
- src/common/cityhash.h
- src/tests/CMakeLists.txt
- src/tests/common/cityhash.cpp
Allow sharing return types with the rest of the code base. For example, we use `u128 = std::array<u64, 2>`, meanwhile Google's code uses `uint128 = std::pair<u64, u64>`. While we are at it, use size_t instead of std::size_t.
I've added tests to make sure this doesn't break backwards compatibility.
> common/cityhash: Use common types

- src/input_common/sdl/sdl_impl.cpp
Reverts yuzu-emu/yuzu#3603 as it causes issues with Xbox One controllers
> Revert "Port citra-emu/citra#5123: "SDL: Disable hidapi drivers due to compatibility problems with certain controllers""

- src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
- src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
- src/video_core/cdma_pusher.cpp
- src/video_core/cdma_pusher.h
- src/video_core/command_classes/codecs/codec.cpp
- src/video_core/command_classes/nvdec.cpp
- src/video_core/command_classes/nvdec.h
- src/video_core/command_classes/vic.cpp
- src/video_core/command_classes/vic.h
- src/video_core/gpu.cpp
- src/video_core/gpu_thread.cpp
This PR aims to clean up some of the nvdec code. Many buffers were being allocated on a per-frame basis (or more frequently) but now are allocated on a per-stream basis. There were also various data structures being improperly used that have been either removed or streamlined.
This also addresses an oversight where the CDMA pusher was alive throughout the lifetime of yuzu, now it is only constructed when a stream begins, and is promptly destroyed on stream end.
> nvdec: Reuse allocated buffers and general cleanup

- src/common/uint128.h
- src/common/wall_clock.cpp
- Previous optimized impl. resulted in an integer overflow, so revert.
- This is our slow/fallback path that should never be really be used, so the optimization in unimportant.
Fixes #5960
> common: wall_clock: Fix integer overflow with StandardWallClock.

- src/core/core.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/service/time/time_manager.cpp
- src/core/hle/service/time/time_manager.h
After rewriting the resource limit, objects releasing reserved resources require a live kernel instance.
This fixes exceptions that occur due to the kernel being destroyed before some objects released their resources, allowing for a graceful exit.
> kernel: Fix resource release exception on exit

- src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
- src/video_core/shader/decode/memory.cpp
- src/video_core/shader/decode/texture.cpp
Also adds offsets for Tlds. OpenGL was hard to do because the only game I have has broken visuals, so I couldn't see if it was actually fixed.
This fixes the graphical corruption and character rendering in Disgaea 6.
Before: 
https://user-images.githubusercontent.com/34639600/107901009-8a0fa700-6f3a-11eb-9715-b8be3498588c.mp4
After:
https://user-images.githubusercontent.com/34639600/107901019-9136b500-6f3a-11eb-8776-6e7b5e536bc1.mp4
> Offsets for TexelFetch and TextureGather in Vulkan

- .ci/scripts/clang/docker.sh
- .ci/scripts/clang/exec.sh
- .ci/scripts/clang/upload.sh
- .ci/templates/build-standard.yml
Adds scripts necessary to compile yuzu using Clang on the yuzu-emu/build-environments:linux-fresh Docker container.
These scripts are mostly a copy of those in .ci/scripts/linux, minus AppImage building since that isn't necessary. Re-uses linux-fresh since that container has Clang 12 installed.
Apparently also adds a trailing newline to the end of a script.
I hope I got the template right, but I'm not familiar with that format. Please do not merge until CI passes with Clang.
> ci: Add clang build scripts

- src/core/hle/service/acc/acc.cpp
This command returns a Nintendo Account ID and writes 2 output buffers. The first output buffer is a NasUserBaseForApplication and the second output buffer is currently empty.
Used by:
- Pokken Tournament DX
- Super Smash Bros. Ultimate
- Super Nintendo Entertainment System - Nintendo Switch Online
- Mario Kart 8 Deluxe
> acc: Stub GetNintendoAccountUserResourceCacheForApplication

- externals/glad/include/glad/glad.h
- externals/glad/src/glad.c
- src/video_core/renderer_opengl/gl_device.cpp
- src/video_core/renderer_opengl/gl_device.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
glDepthRangeIndexeddNV allows depth buffers outside the range [0, 1], which is needed by some games. The current glDepthRangeIndexed clamps the depth to [0, 1] beforehand, which produces incorrect results with [-1, 1] depth buffers.
All credits to Rodrigo for finding this, I did nothing.
> [OpenGL] Implement glDepthRangeIndexeddNV

- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
Implements both SendVibrationGcErmCommand and GetActualVibrationGcErmCommand, and modifies GetVibrationDeviceInfo to account for additional controllers.
This allows vibrations to work when the GameCube Controller is selected in the list of emulated controllers.
> hid: Implement GameCube Controller Vibrations

- src/common/cityhash.h
- src/video_core/shader_notify.cpp
From [error log](https://github.com/yuzu-emu/yuzu/files/6025872/yuzu-qt5-s20210222.log):
```c++
src/./common/cityhash.h:69:47: error: 'size_t' has not been declared
69 | [[nodiscard]] u64 CityHash64(const char* buf, size_t len);
|                                               ^~~~~~
src/./common/cityhash.h:73:55: error: 'size_t' has not been declared
73 | [[nodiscard]] u64 CityHash64WithSeed(const char* buf, size_t len, u64 seed);
|                                                       ^~~~~~
src/./common/cityhash.h:77:56: error: 'size_t' has not been declared
77 | [[nodiscard]] u64 CityHash64WithSeeds(const char* buf, size_t len, u64 seed0, u64 seed1);
|                                                        ^~~~~~
src/./common/cityhash.h:80:47: error: 'size_t' has not been declared
80 | …
```
> common,video-core: unbreak GCC 11 build on FreeBSD 13

- src/core/hle/service/ldn/ldn.cpp
- Since we do not emulate LDN, returning an error here makes more sense.
> core: hle: ldn: Error out on call to Initialization.

- src/video_core/gpu.cpp
- src/video_core/gpu_thread.cpp
- src/video_core/gpu_thread.h
This commit removes early placeholders for an implementation of async nvdec. 
With recent changes to the source code, the placeholders are no longer accurate, and risk a nullptr dereference due to the nature of the cdma_pusher lifetime.
Thanks to @liushuyu and @lat9nq for bringing this to my attention.
> gpu_thread: Remove Async NVDEC placeholders

- src/yuzu/configuration/config.cpp
- src/yuzu_cmd/config.cpp
bcat_backend checks for "none," but is default initialised to "null," leading to incorrectly returning a Connected state without bcat enabled due to the direct string comparisons. Not a huge deal, as opening and closing the settings at any time will fix it back to "none."
> [Service::nifm] Fix bcat_backend's default initialisation

- src/core/core.cpp
- Fixes a shutdown crash due to a race condition with GPU still accessing memory.
> core: Shutdown: Move kernel cleanup to later in shutdown.

- src/common/common_funcs.h
- src/common/misc.cpp
- src/core/network/network.cpp
- src/core/network/network.h
- src/tests/CMakeLists.txt
- src/tests/core/network/network.cpp
`network.cpp` has several error paths which either:
- report "Unhandled host socket error=n" and return `SUCCESS`, or
- switch on a few possible errors, log them, and translate them to
Errno; the same switch statement is copied and pasted in multiple
places in the code
Convert these paths to use a helper function `GetAndLogLastError`, which
is roughly the equivalent of one of the switch statements, but:
- handling more cases (both ones that were already in `Errno`, and a few
more I added), and
- using OS functions to convert the error to a string when logging, so
it'll describe the error even if it's not one of the ones in the
switch statement.
- To handle this, refactor the logic in `GetLastErrorMsg` to expose
new functions `WinErrorToString` and `UnixErrnoToString` which take
the error …
> Network error handling reform

- src/input_common/udp/client.cpp
- src/input_common/udp/client.h
- src/yuzu/configuration/configure_motion_touch.cpp
- src/yuzu/configuration/configure_motion_touch.h
According to https://github.com/v1993/cemuhook-protocol each socket connection should have a unique client id. This should solve problems where test fails or you need to restart the server. Also removes the magic number 24872 that was used as client id for yuzu.
This is a candidate to be ported to citra since it has the same issue.
> InputCommon: Use an unique client id for each udp socket instance

- src/common/fiber.cpp
- src/common/fiber.h
- src/core/cpu_manager.cpp
- src/core/cpu_manager.h
- src/core/hle/kernel/k_scheduler.cpp
- src/core/hle/kernel/k_scheduler.h
- src/core/hle/kernel/k_thread.cpp
- src/core/hle/kernel/k_thread.h
- src/core/hle/kernel/svc.cpp
- src/tests/common/fibers.cpp
- With using unique_ptr instead of shared_ptr, we have more explicit ownership of the context.
- Fixes a memory leak due to circular reference of the shared pointer.
> core: Switch to unique_ptr for usage of Common::Fiber.

- .gitmodules
- src/core/crypto/aes_util.cpp
mbedtls 2.16 is the last version which has licensing for GPL 2.0. This updates mbedtls to our own [fork](https://github.com/yuzu-emu/mbedtls) of mbedtls 2.16
> externals: Update mbedtls to 2.16.9

- src/common/fiber.cpp
- src/common/fiber.h
- src/core/cpu_manager.cpp
- src/core/cpu_manager.h
- src/core/hle/kernel/k_scheduler.cpp
- src/core/hle/kernel/k_scheduler.h
- src/core/hle/kernel/k_thread.cpp
- src/core/hle/kernel/k_thread.h
- src/core/hle/kernel/svc.cpp
- src/tests/common/fibers.cpp
Reverts yuzu-emu/yuzu#6006
This can technically cause a crash by accessing fibers after use. Will address in a followup.
> Revert "core: Switch to unique_ptr for usage of Common::Fiber."

- src/CMakeLists.txt
Ensures that the source and execution character sets are in UTF-8
Also fixes the Move Up / Down arrows
> CMakeLists: Add /utf-8 compile option for MSVC

- src/core/hle/kernel/k_scheduler.cpp
- src/core/hle/kernel/k_thread.cpp
- src/core/hle/kernel/k_thread.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/process.cpp
- src/core/hle/kernel/svc.cpp
- Dummy threads are created on thread local storage for all host threads.
- Fixes a leak by removing creation of fibers, which are not applicable here.
Fixes #5995
> hle: kernel: KThread: Rework dummy threads & fix memory leak.

- src/common/fiber.cpp
- src/common/fiber.h
- src/core/cpu_manager.cpp
- src/core/hle/kernel/k_scheduler.cpp
- src/tests/common/fibers.cpp
- Avoids a memory leak, as taking a strong reference of the fiber here causes a circular reference.
- Supersedes #6006 with a more narrow fix.
> common: fiber: Use weak_ptr when yielding.

- src/input_common/mouse/mouse_input.cpp
- src/input_common/mouse/mouse_input.h
- src/yuzu/bootmanager.cpp
- src/yuzu/bootmanager.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/main.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.h
Fixes a couple of problems that have been present in the mouse implementation.
- Up to 7 different buttons are detected now. (left, right, middle, back, forward, task and another extra button)
- Mapping a mouse button no longer stays pressed after the mapping is done.
- Default hotkey has been changed to Ctrl+F9.
- Mouse will not hide anymore if hide_mouse setting is not enabled
- Mouse panning setting will be reset at reboot and only mouse sensitivity will be stored
> InputCommon: Mouse fixes

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/renderer_opengl/gl_buffer_cache.cpp
Some games benefit from skipping caches (Pokémon Sword), and others don't (Animal Crossing: New Horizons). Add an heuristic to decide this at runtime, an alternative solution would be to have a database of games that benefit from this but that's ugly.
The cache hit ratio has to be ~98% or better to not skip the cache. There are 16 frames of buffer.
I tested the mentioned games as well as Super Mario Odyssey and The Legend of Zelda Breath of the wild. These two games fall under the skip cache category, so they won't be affected by this change. More testing would be appreciated.
- Fixes a performance regression introduced after the initial release of the buffer cache rewrite on Vulkan on AC:NH.
> buffer_cache: Heuristically decide to skip cache on uniform buffers

- src/video_core/compatible_formats.cpp
- src/video_core/compatible_formats.h
- src/video_core/host_shaders/CMakeLists.txt
- src/video_core/host_shaders/opengl_copy_bgra.comp
- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_opengl/gl_texture_cache.h
- src/video_core/renderer_opengl/util_shaders.cpp
- src/video_core/renderer_opengl/util_shaders.h
- src/video_core/renderer_vulkan/vk_texture_cache.h
- src/video_core/texture_cache/image_base.cpp
- src/video_core/texture_cache/image_view_base.cpp
- src/video_core/texture_cache/texture_cache.h
- src/video_core/texture_cache/util.cpp
- src/video_core/texture_cache/util.h
OpenGL does not natively support BGR internal formats, which causes many BGR textures to render incorrectly, with Red and Blue channels swapped.
This PR aims to address this by swizzling the blue and red channels on texture copies when a BGR format is encountered.
Many thanks to @ReinUsesLisp for his guidance and @lat9nq for extensive testing on Linux and AMD hardware.
closes #3581, closes #5783, closes #2184
src="https://user-images.githubusercontent.com/52414509/107165513-31ac3880-6981-11eb-9e5a-99773ef8a386.png" width="720" height="400" />
src="https://user-images.githubusercontent.com/52414509/107165516-3244cf00-6981-11eb-93e8-aafab5a678a2.png" width="720" height="400" />
src="https://user-images.githubusercontent.com/52414509/107165515-3244cf00-6981-11eb-8c14-540ddd1d120b.png" …
> renderer_opengl: Use compute shaders to swizzle BGR textures on copy

- src/input_common/keyboard.cpp
- src/input_common/mouse/mouse_input.cpp
- src/input_common/mouse/mouse_input.h
- src/input_common/mouse/mouse_poller.cpp
- src/yuzu/bootmanager.cpp
- src/yuzu/configuration/configure_input_player.cpp
Since keyboard and mouse has a limit in how many keys can be pressed at the same time. I added the ability to make buttons a toggle button. This way you can free a button from your keyboard by just pressing it once and it will remain pressed until you press it again.
Right click the modifier button then select "toggle button" to enable it or disable it.
> Enable toggle buttons for keyboard and mouse

- src/yuzu/main.cpp
Fixes web browser opening (Help > Open Mods Page, Help > Open Quickstart Guide)
```
$ ./yuzu-20210110-a8cc9db87-x86_64.AppImage 
Error: no DISPLAY environment variable specified
```
Same issue as https://github.com/RPCS3/rpcs3/issues/5959, same fix as https://github.com/RPCS3/rpcs3/pull/7461
> qt: Set DISPLAY env var when not present

- src/video_core/rasterizer_accelerated.cpp
- src/video_core/rasterizer_accelerated.h
- Uses a fixed 64MB for the cache instead of an ever growing map.
- Slightly faster by using atomics instead of a single mutex for access.
- Thanks to Rodrigo for the idea.
> video_core: rasterizer_accelerated: Use a flat array instead of interval_map for cached pages.

- src/core/hle/service/time/time.cpp
CalculateSpanBetween passes in the ClockSnapshots through 2 input buffers and not as raw arguments. Fix this by reading the 2 input buffers instead of popping raw arguments.
Completely fixes Super Smash Bros. Ultimate's Spirit Board with #6054
> time: Fix CalculateSpanBetween implementation

- src/core/hle/service/time/time.cpp
Fixes the timer in Super Smash Bros Ultimate's Spirit Board.
> time: Assign the current time point to the ClockSnapshot

- src/core/hle/service/sockets/bsd.cpp
Silences log spam on empty buffer writes
> bsd: Avoid writing empty buffers

- src/common/fiber.cpp
When we hit limits we bump the limits.
---
? Stack overflow when running 32-bit guest applications. Bump stack size in order to attempt to avoid this.
> [testing] fiber: Double default stack size

- externals/libusb/CMakeLists.txt
Resolves C2001 `newline in constant` errors in libusb's strerror.c
> externals/libusb/CMakeLists: Add /utf-8 compile option for MSVC

- src/yuzu/configuration/configure_filesystem.cpp
Do not change current path if QFileDialog::getExistingDirectory is cancelled. Fixes #4947.
> Fix cancelation of getExistingDirectory dialog

- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_64.cpp
- We re-create the JIT here without preserving any state.
> core: arm_dynarmic: Ensure JIT state is saved/restored on page table changes.

- src/video_core/renderer_opengl/gl_device.cpp
Tested on
```
yuzu Version: yuzu Development Build | master-716285fab
Host CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz | AVX2 | FMA
Host OS: FreeBSD 12.2-RELEASE
Host RAM: 63.68 GB
Host Swap: 0.00 GB
[...]
GL_VERSION: 4.6 (Compatibility Profile) Mesa 21.1.0-devel (git-52e7297f9c7)
GL_VENDOR: Intel
GL_RENDERER: Mesa Intel(R) HD Graphics 530 (SKL GT2)
```
> gl_device: unblock async shaders on other Unix systems

- src/core/hle/kernel/kernel.cpp
- Fixes a startup crash that occurs if CoreTiming tries to preempt before kernel initialization completes.
> hle: kernel: Initialize preemption task after schedulers.

- src/core/hle/service/nvdrv/devices/nvdevice.h
- src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
- src/core/hle/service/nvdrv/devices/nvdisp_disp0.h
- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
- src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
- src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
- src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
- src/core/hle/service/nvdrv/devices/nvhost_gpu.h
- src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
- src/core/hle/service/nvdrv/devices/nvhost_nvdec.h
- src/core/hle/service/nvdrv/devices/nvhost_nvjpg.cpp
- src/core/hle/service/nvdrv/devices/nvhost_nvjpg.h
- src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
- src/core/hle/service/nvdrv/devices/nvhost_vic.h
- src/core/hle/service/nvdrv/devices/nvmap.cpp
- src/core/hle/service/nvdrv/devices/nvmap.h
- src/core/hle/service/nvdrv/nvdrv.cpp
We pass the fd to the ioctl as well as alert the device when it's opened or closed to allow for fd unique actions to take place
> nvdrv: Pass device fd and handle device create methods for device opening and closing

- src/core/hle/service/hid/controllers/gesture.cpp
- src/core/hle/service/hid/controllers/touchscreen.cpp
Gesture only allows up to 4 points. They where initialized at 16. This PR fixes that error and adds a filter to prevent writing to invalid places in the array
> HID: Initialize correctly the gesture finger_id and filter invalid inputs

- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_memory_allocator.cpp
Tested OpenGL/Vulkan renderers on FreeBSD with anv+iris. `VK_KHR_external_memory_fd` is also used by other packages: chromium, libplacebo (used by mpv, vlc), ffmpeg (some filters), wlroots (in future, used by sway), chamferwm..
> vulkan_common: enable OpenGL interop on other Unices

- src/yuzu/main.cpp
Allows to select a specific user at boot. If the selected user is invalid the argument is ignored.
Example:
`yuzu.exe  -u 0`
`yuzu.exe -u 1 -g "path_to_game"`
`yuzu.exe -f -u 2 -g "path_to_game"`
> yuzu/main: Add user command line argument

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
This service call sets an internal flag whether a notification is shown when an image is captured.
Currently we do not support capturing images via the capture button, so this can be stubbed for now.
> ISelfController: Stub SetAlbumImageTakenNotificationEnabled

- src/core/hle/service/hid/controllers/npad.cpp
Left joycon and right joycon map buttons to different memory locations. This PR will fix the SL and SR buttons for the right joycon
> HID: Fix SL and SR buttons for right joycon

- src/input_common/udp/client.cpp
- src/input_common/udp/client.h
- src/yuzu/configuration/configure_motion_touch.cpp
- src/yuzu/configuration/configure_motion_touch.h
In an attempt to improve the reliability of motion servers I decided to use a single connection per server instead of one per controller. This will simplify communications and reduce the chance for errors.  
Connection tests now check if there is data for all controllers and finish early if connection is successful.
With those changes hopefully users will have less problems. Since communication method changed this need to be tested on production to ensure all UDP servers support this mode.
> InputCommon: Improve UDP communications

- src/yuzu/configuration/configure_graphics.cpp
Address Sanitizer reports stack-use-after-scope on line 231 `vulkan_devices.push_back(QString::fromStdString(name));`. Instead of using a pointer, copy the string into a std::string and use that, instead.
Issue was found while opening the Configure menu. Might fix the issue where I sometimes get "rce GTX 980 Ti" instead of "GeForce GTX 980 Ti" in my Vulkan drop down.
> configure_graphics: Prevent stack-use-after-scope

- src/core/hle/kernel/process_capability.cpp
- src/core/hle/kernel/process_capability.h
12.x extended the range of SVC IDs, so we need to expand the range of bits that need to be tested.
The upside of this is that we can eliminate a range check, given the whole range is used.
> process_capability: Handle extended SVC range

- src/common/CMakeLists.txt
- src/common/assert.cpp
- src/common/assert.h
Advantage: Altering the handler does not need a full recompilation.
Disadvantage: noreturn is droped, so the caller is a bit slower.
We quite often run yuzu with a YOLO assertion handler. In fact, only very few
games run at all with asserts. This patch allows developers to patch the handler
without recompiling everything. The overhead of the missing "noreturn" attribute
shoul be negletable.
This will conflict on purpose with #1340.
> common: Move assert failure handling into a cpp file.

- src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
Undefined Behaviour Sanitizer reports a null pointer is being sent to memcpy, thought it's "guaranteed to never be null". Guard it with an if statement, and log when the action has been averted.
Issue was found while booting SSBU. This change may be needed on the rest of the functions in nvhost_ctrl_gpu, but ubsan has not caught anything else there, yet. *Fixing the error, not any potential cause.*
> nvhost_ctrl_gpu: Avoid sending null pointer to memcpy

- src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
Avoid sending null pointer to memcpy as reported by Undefined Behaviour Sanitizer.
> nvhost_nvdec_common: Avoid memcpy with null pointers

- src/core/hle/service/service.cpp
- src/core/settings.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_debug.ui
This adds a toggle in the debugging tab to enable an auto stub fallback for unimplemented HLE service calls.
The toggle is reset when yuzu is relaunched, as this is an experimental feature not meant to remain enabled.
Supersedes #4237
> service: Add a toggle for auto stub fallback

- src/common/threadsafe_queue.h
- src/core/core.cpp
- src/video_core/gpu.cpp
- src/video_core/gpu.h
- src/video_core/gpu_thread.cpp
- src/video_core/gpu_thread.h
This removes the spin loops within gpu_thread for power saving. This should have no large effect on performance.
> video_core: Avoid spin loops.

- src/core/hle/kernel/k_scheduler.h
- src/core/hle/kernel/k_scoped_lock.h
- src/core/hle/kernel/k_scoped_scheduler_lock_and_sleep.h
Prevents logic bugs where
```cpp
KScopedSchedulerLock{kernel};
```
is written instead of:
```cpp
KScopedSchedulerLock lock{kernel};
```
from slipping through silently. Now the compiler is obliged to warn about cases like that.
> kernel: Mark lock helper classes as [[nodiscard]]

- CMakeLists.txt
- externals/CMakeLists.txt
- externals/find-modules/Findopus.cmake
- externals/opus/CMakeLists.txt
- src/core/CMakeLists.txt
We had used conan for opus before, but there was a bug in the AVX detection.
However we still had the Findopus.cmake file within the repository, but not used.
This patch reenables the Findopus helper and prefer the system wide installation of opus.
This will use the opus .so/.dll on linux-fresh and mingw builds (which I think is fine). MSVC builds are not affected.
> externals: Search for shared opus installation.

- src/core/file_sys/control_metadata.cpp
- src/core/file_sys/control_metadata.h
- src/core/hle/service/pctl/module.cpp
- src/core/hle/service/pctl/module.h
- src/core/hle/service/pctl/pctl.cpp
- src/core/hle/service/pctl/pctl.h
Introduces the usage of compatibilities to allow the module to be closer to how it works on hardware.
Closes #6111
> pctl: Rework how pctl works to be more accurate

- src/core/hle/service/time/time.cpp
CalculateStandardUserSystemClockDifferenceByUser passes in the ClockSnapshots through 2 input buffers and not as raw arguments. Fix this by reading the 2 input buffers instead of popping raw arguments.
Fixes #6165
> service: time: Fix CalculateStandardUserSystemClockDifferenceByUser

- src/video_core/renderer_vulkan/renderer_vulkan.cpp
- src/video_core/renderer_vulkan/vk_swapchain.cpp
- src/video_core/renderer_vulkan/vk_swapchain.h
We can get into a really bad state by ignoring this
leading to device loss and using incorrect resources.
> renderer_vulkan: Check return value of AcquireNextImage

- src/core/hle/service/time/clock_types.h
- src/core/hle/service/time/time.cpp
- src/core/hle/service/time/time.h
- src/core/hle/service/time/time_manager.cpp
- src/core/hle/service/time/time_zone_manager.cpp
- src/core/hle/service/time/time_zone_types.h
Setup the network clock with the local clock context instead of a default clock context to prevent a clock source id mismatch when getting the current network time
This fixes Super Smash Bros. Ultimate's Spirit Board resetting its timers on reboot.
**Note that this does NOT fix Pokemon Sword/Shield's time progression when the game is not running**
> service: time: Setup the network clock with the local clock context

- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
The Vulkan spec states:
If an element of pBuffers is VK_NULL_HANDLE, then the corresponding element of pOffsets must be zero.
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBindVertexBuffers2EXT.html#VUID-vkCmdBindVertexBuffers2EXT-pBuffers-04112
> vk_buffer_cache: Fix offset for NULL vertex buffers

- src/video_core/vulkan_common/vulkan_device.cpp
When this was being made mandatory, these enablement of these features was removed, but this is still needed.
Fixes: 757fd1e91716 ("vulkan_device: Require VK_EXT_robustness2")
> vulkan_device: Enable EXT_robustness2 features

- src/core/settings.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_graphics.cpp
- src/yuzu/configuration/configure_graphics.ui
- src/yuzu/main.cpp
The borderless windowed fullscreen mode solves several issues with the presentation of the overlay dialogs and on-screen keyboard in exclusive fullscreen mode, and also has other benefits such as smoother gameplay, lower latency and a significant reduction in screen tearing.
If you encounter issues with this mode, you can swap to the previous exclusive fullscreen mode under Configure > Graphics > Fullscreen Mode
> configure_graphics: Add Borderless Windowed fullscreen mode

- src/core/hle/kernel/k_thread.h
This function has a void return value, so this attribute doesn't apply to it.
> k_thread: Remove [[nodiscard]] attribute from ClearWaitCancelled()

- src/common/nvidia_flags.h
Prevents potential inclusion compilation errors.
> nvidia_flags: Add missing header guard

- src/video_core/query_cache.h
Same behavior, but much more straightforward to read.
> query_cache: Make use of std::erase_if

- src/video_core/texture_cache/util.cpp
- src/video_core/texture_cache/util.h
Amends implicit sign conversions occurring with usages of std::reduce and also relocates it to its own utility function to reduce verbosity a little bit.
> texure_cache/util: Resolve implicit sign conversions with std::reduce

- src/video_core/renderer_vulkan/vk_master_semaphore.h
This member function doesn't modify class state, so it can be marked as const.
> vk_master_semaphore: Add missing const qualifier for IsFree()

- src/video_core/engines/engine_interface.h
- src/video_core/engines/fermi_2d.h
- src/video_core/engines/kepler_memory.h
- src/video_core/engines/maxwell_dma.h
Eliminates a potential bug vector related to inheritance. Plus, we should generally be specifying the destructor as virtual within purely virtual interfaces to begin with.
> engine_interface: Add missing virtual destructor

- src/core/hle/kernel/k_resource_limit.cpp
- src/core/hle/kernel/k_resource_limit.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/svc.cpp
Functionally no change, simply cleans up some of the headers member variables in k_resource_limit
> k_resource_limit: Cleanup of member variables/headers

- src/common/logging/backend.cpp
- src/common/logging/backend.h
- src/common/logging/filter.cpp
- src/common/logging/filter.h
- src/common/logging/log.h
- src/common/logging/text_formatter.cpp
- src/common/logging/text_formatter.h
- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/debugger/console.cpp
- src/yuzu/main.cpp
- src/yuzu_cmd/yuzu.cpp
Forgot to move this over when I moved the rest of the source files with lacking namespaces over.
Thankfully aspects of this namespace outside of the defines aren't touched much, so this is a pretty straightforward change.
> common/log: Move Log namespace into the Common namespace

- src/input_common/sdl/sdl_impl.cpp
- src/input_common/sdl/sdl_impl.h
Xbox 360 and One controllers where listed as `Xinput Controller`. The Pro controller doesn't need the face buttons swapped. 
This PR displays the correct controller name for both  controllers and maps the Pro controller correctly.
> InputCommon: Address mapping and naming issues with SDL2

- .ci/templates/build-msvc.yml
- CMakeLists.txt
- Bintray will be deprecated on May 1st 2021 (https://bintray.com/)
- We were previously using this for Qt (non-Windows) and SDL.
- I've moved to bundled SDL on Windows.
> cmake: Remove use of bintray for externals.

- src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
- src/video_core/gpu.cpp
- src/video_core/gpu.h
Brings us a step closer to unifying all channels to share a common interface.
> nvdrv: Cleanup CDMA Processor on device closure

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/am/applets/applets.cpp
- src/core/hle/service/am/applets/applets.h
- src/core/hle/service/am/applets/controller.cpp
- src/core/hle/service/am/applets/controller.h
- src/core/hle/service/am/applets/error.cpp
- src/core/hle/service/am/applets/error.h
- src/core/hle/service/am/applets/general_backend.cpp
- src/core/hle/service/am/applets/general_backend.h
- src/core/hle/service/am/applets/profile_select.cpp
- src/core/hle/service/am/applets/profile_select.h
- src/core/hle/service/am/applets/software_keyboard.cpp
- src/core/hle/service/am/applets/software_keyboard.h
- src/core/hle/service/am/applets/web_browser.cpp
- src/core/hle/service/am/applets/web_browser.h
Fixes the softlock after the controller applet exits in Mario Kart 8 Deluxe.
Thanks to @EmulationFanatic and @riperiperi for finding this solution to the Mario Kart 8 Deluxe multiplayer softlock
Fixes #6068 
https://user-images.githubusercontent.com/39850852/115115197-0b96ac00-9f61-11eb-8107-6d7e366c1f0f.mp4
> applets: Send focus state change message on applet state change

- .gitmodules
- CMakeLists.txt
- externals/CMakeLists.txt
Since Bintray is (soon to be) no more and has been removed from yuzu, there needs to be a way to acquire updated SDL2. Since Ubuntu 20.04's version is older than our minimum required version (2.0.12), add it as an external.
Fixes #6203
> externals: Add SDL 2.0.12

- src/core/hle/service/glue/arp.cpp
If anything happened to call arp functions in the wrong order and called IRegistrar's Issue function before SetApplicationLaunchProperty, we'd read from an uninitialized ApplicationLaunchProperty instance. Instead, we can always initialize it so if this does happen, then the outcome of doing such a thing is at least consistently reproducible, as opposed to using whatever was in memory at that time. Unlikely to occur, but is a bug vector class that's trivial to eliminate here.
While we're in the area, we can also deduplicate the issuer function type, so that it's in one place and makes the code a little nicer to read.
> arp: Prevent potential uninitialized read of launch member variable

- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
ControllerBase already has a System reference that can be accessed from this class, so we can get rid of this to make the class layout a little more straightforward.
> npad: Remove duplicated class member variable

- src/core/hle/service/set/set.cpp
- src/core/hle/service/time/time_zone_service.cpp
- src/core/hle/service/vi/vi.cpp
For consistency with the rest of the service implementations
> general: Write buffers before pushing raw arguments

- src/video_core/texture_cache/util.cpp
This line can only ever be reached if src is null, so dereferencing it here is a logic bug that slipped through.
Instead, we dereference dst instead which is guaranteed to be valid.
> texture_cache/util: Fix src being used instead of dst within DeduceBlitImages case

- src/common/logging/backend.cpp
- src/common/logging/backend.h
Makes log backend removal less verbose.
While we're at it, we can tidy up the file backend a little bit.
> log/backend: Make use of erase_if

- src/core/hle/service/time/time.cpp
This removes an incorrect alignment usage and corrects the positions of the popped parameters.
- Fixes Super Kirby Clash crashing on boot
- Also fixes Yo-Kai Watch 4 (JP) crashing on boot
Fixes #4045
> time: Fix GetClockSnapshotFromSystemClockContext

- CMakeLists.txt
Sets `find_package(FFmpeg)` to `QUIET` instead of `REQUIRED`. This allows using the FFmpeg external in cases where there is no suitable installed version of FFmpeg.
Also fixes a bug where multiple CMake configures causes `FFmpeg_LIBRARIES` to concatenate on itself, producing cyclical dependencies. Unsets the variable before building it in the `foreach` loop.
Fixes `FFmpeg_INCLUDE_DIR` not including the headers generated at run time.
Additionally, adds `QUIET` to the `find_package` for SDL2, to suppress a somewhat lengthy warning and maybe concerning one to the uninitiated. This was small enough that I though making a full PR for it would be a bit unnecessary.
> cmake: Fix FFmpeg external usage and cleanup 

- CMakeLists.txt
- CMakeModules/DownloadExternals.cmake
Since #6207, building SDL2 from externals on systems with low or no system Boost version is incompatible with Conan's version of libiconv, a requirement of Conan's Boost package. The solution proposed here is to use the same Boost package as the linux-fresh container. This tells CMake to download boost_1_75_0.tar.xz from [yuzu-emu/ext-linux-bin](https://github.com/yuzu-emu/ext-linux-bin) at CMake's configuration step, much the same way Qt and FFmpeg are downloaded for Windows.
This also makes DownloadExternals.cmake cross-platform between Windows and Linux. Although the CMake code is not entirely specific to Linux, only Linux has Boost libraries available at ext-linux-bin, whereas there is no equivalent Boost package for Windows at ext-windows-bin. This also does not work for any of the …
> cmake: Download Boost from ext-linux-bin if inadequate local version

- src/core/hle/service/hid/hid.cpp
This PR simply retrieves the transfer memory for InitializeSevenSixAxisSensor. Further work is needed to read/write from/to the transfer memory.
> service: hid: Get transfer memory for InitializeSevenSixAxisSensor

- src/core/frontend/emu_window.cpp
- src/core/frontend/emu_window.h
- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.h
This is more concise and consistent with the rest of the codebase.
While we're at it, we can convert a function to return a std::pair instead of a std::tuple.
> emu_window: unsigned -> u32

- src/core/crypto/aes_util.cpp
- src/core/crypto/aes_util.h
Allows us to simplify the interface quite a bit as it will handle contiguous sequences for us.
> aes_util: Make use of std::span

- src/core/hle/service/acc/acc.cpp
- src/core/hle/service/lbl/lbl.cpp
These request parsers aren't used at all, so we can remove them.
> acc/lbl: Remove unused variables

- src/core/file_sys/program_metadata.h
The generation of the copy assignment operators are deprecated on being generated when a user-provided destructor is present. We can explicitly specify that we desire this behavior to keep the class forward compatible with future standards.
> program_metadata: Explicitly specify copy/move operators/functions

- src/core/file_sys/program_metadata.cpp
- src/core/file_sys/program_metadata.h
- src/core/loader/kip.cpp
Sets a default size of 0x1FE00000 bytes (510 MiB) for the system_resource_size when a NPDM is not present.
> program_metadata: Set a default resource size when a NPDM is not present

- src/core/CMakeLists.txt
- src/core/hle/service/glue/ectx.cpp
- src/core/hle/service/glue/ectx.h
- src/core/hle/service/glue/glue.cpp
Adds the ectx:aw service used in Pixel Game Maker Series Werewolf Princess Kaguya. Allows the game to be played.
> glue: Add ectx:aw service placeholder

- src/yuzu/configuration/config.cpp
Changes the keyboard bindings to be based on RPCS3's tried and true keyboard bindings.
> config: Add new keyboard bindings

- src/core/hle/service/am/applets/error.cpp
- src/core/hle/service/am/applets/general_backend.cpp
- src/core/hle/service/bcat/backend/boxcat.cpp
- src/core/hle/service/bcat/module.cpp
- src/core/hle/service/filesystem/fsp_srv.cpp
- src/core/hle/service/nvflinger/nvflinger.cpp
- src/core/hle/service/time/standard_user_system_clock_core.cpp
- src/core/hle/service/time/standard_user_system_clock_core.h
- src/core/hle/service/time/system_clock_core.cpp
- src/core/hle/service/time/system_clock_core.h
- src/core/hle/service/time/time_manager.cpp
- src/core/hle/service/time/time_sharedmemory.cpp
- src/core/hle/service/time/time_sharedmemory.h
- src/core/hle/service/vi/display/vi_display.cpp
- src/core/hle/service/vi/display/vi_display.h
Resolves a few localized instances of member variable shadowing. Brings us a little closer to turning shadowing warnings into errors.
> service: Eliminate cases of member variable shadowing

- src/core/loader/deconstructed_rom_directory.cpp
- src/core/loader/deconstructed_rom_directory.h
- src/core/loader/elf.cpp
- src/core/loader/elf.h
- src/core/loader/kip.cpp
- src/core/loader/kip.h
- src/core/loader/loader.h
- src/core/loader/nax.cpp
- src/core/loader/nax.h
- src/core/loader/nca.cpp
- src/core/loader/nca.h
- src/core/loader/nro.cpp
- src/core/loader/nro.h
- src/core/loader/nso.cpp
- src/core/loader/nso.h
- src/core/loader/nsp.cpp
- src/core/loader/nsp.h
- src/core/loader/xci.cpp
- src/core/loader/xci.h
Eliminates variable shadowing cases across all the loaders to bring us closer to enabling variable shadowing as an error in core.
> loader: Resolve instances of variable shadowing

- src/core/CMakeLists.txt
- src/core/frontend/input.h
- src/core/hle/kernel/transfer_memory.cpp
- src/core/hle/kernel/transfer_memory.h
- src/core/hle/service/hid/controllers/console_sixaxis.cpp
- src/core/hle/service/hid/controllers/console_sixaxis.h
- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
- src/core/hle/service/hid/hid.cpp
- src/input_common/motion_input.cpp
Implements SevenSixAxis and ConsoleSixAxisSensor. Allows to move the VR camera with motion.
This PR still needs more research and proper calibration of the motion sensors since they don't necessarily match with the console motion at the moment. But they are working well enough to be used in games that have this feature
> hid: Implement SevenSixAxis and ConsoleSixAxisSensor

- src/core/frontend/applets/web_browser.cpp
- src/core/frontend/applets/web_browser.h
- src/yuzu/applets/web_browser.cpp
- src/yuzu/applets/web_browser.h
- src/yuzu/main.cpp
- src/yuzu/main.h
The URL string was being deleted before being used, leading to a use-after-free occurring when it is used afterwards.
Fix this by taking the string by const ref to extend its lifetime, ensuring it doesn't get deleted before use.
This should fix the random crashes some users were seeing when loading the web applet.
> applets/web: Fix a use-after-free when passing in the URL string

- src/core/file_sys/errors.h
- src/core/hle/service/filesystem/filesystem.cpp
This improves the accuracy of CreateFile by returning the correct error codes on certain conditions (parent directory does not exist, path already exists).
This fixes saving and the loading of existing saves in New Pokemon Snap
> service: filesystem: Return proper error codes for CreateFile

- src/yuzu/game_list.cpp
Currently if you move directories up or down they become expanded or collapsed at what feels like random. I believe the issue comes from how the indexes aren't swapped after the directories are, but with these changes they keep their previous state.
> game_list: Fix dir move up/down expand state

- src/core/hle/service/hid/controllers/gesture.cpp
- src/core/hle/service/hid/controllers/touchscreen.cpp
A regression was introduced in #6264. Removes previous changes and uses another solution that allows touch to be set correctly while ignoring all input devices if disabled.
> hid: Fix touch not initializing properly if disabled

- src/input_common/mouse/mouse_input.cpp
- src/input_common/mouse/mouse_input.h
- src/yuzu/bootmanager.cpp
When the OSK opens mouse input gets pressed permanently until next event. This will release any mouse button if the game loses focus.
> input_common: Release mouse buttons on out of focus

- src/core/arm/dynarmic/arm_dynarmic_cp15.cpp
- src/core/core_timing.cpp
- src/core/core_timing.h
- src/core/cpu_manager.h
- src/core/loader/deconstructed_rom_directory.cpp
- src/core/loader/deconstructed_rom_directory.h
- src/core/memory/cheat_engine.cpp
- src/core/memory/cheat_engine.h
- src/core/tools/freezer.cpp
- src/core/tools/freezer.h
Resolves shadowing warnings that aren't in a particularly large subsection of core. Brings us closer to turning -Wshadow into an error.
All that remains now is for cases in the kernel (left untouched for now since a big change by bunnei is pending), and a few left over in the service code (will be tackled next).
> core: Resolve misc straggler cases of variable shadowing

- src/core/hle/service/am/applets/web_browser.h
- src/core/hle/service/lbl/lbl.cpp
- src/core/hle/service/pctl/module.cpp
Prevents some warnings from occurring.
While in the same area, we can ensure all member variables of am's WebBrowser all have an initializer to make for deterministic initial state.
> service: Remove unused class variables

- src/core/hle/service/nvdrv/interface.cpp
While we're at it, we can fix the is_initialized error code.
This fixes the crashes on Shante
> nvdrv: /dev/nvhost-prof-gpu for production

- src/input_common/main.cpp
- src/input_common/sdl/sdl.h
- src/input_common/sdl/sdl_impl.cpp
- src/input_common/sdl/sdl_impl.h
- src/yuzu/configuration/configure_input_player.cpp
Adds the motion backend for SDL2 since it's now supported. Need testing to find supported controllers.
> input_common: Implement SDL motion

- src/common/tree.h
- src/core/hle/ipc.h
- src/core/hle/ipc_helpers.h
- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/kernel/k_client_port.cpp
- src/core/hle/kernel/k_server_session.cpp
- src/core/hle/kernel/k_session.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/slab_helpers.h
- src/core/hle/kernel/svc.cpp
- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/audio/audren_u.h
- src/core/hle/service/service.cpp
- src/core/hle/service/service.h
- src/core/hle/service/sm/controller.cpp
- src/core/hle/service/sm/sm.cpp
- src/core/hle/service/sm/sm.h
* Adds initial implementation of TIPC, the new IPC protocol introduced with 12.0.0. I've tested the behavior of this with homebrew, although I am not aware of this being used in any retail games yet.
* Updates SM service to support TIPC. This also involved fixing several issues with SM error-checking, such as validating service names being broken.
* Corrects the behavior of svcConnectToNamedPort -- instead of creating static "installed" interfaces of named ports, we now register a factory method with the kernel, and create a new interface each time this is called. This was noticed in testing homebrew with TIPC, where SM is created twice (once for classic IPC, once for TIPC), and these interfaces should have separate state.
* Implements IPC "Close" command. Previously, we never actually …
> Various improvements to IPC and session management

- src/yuzu/main.cpp
Fixes the missing title version number on EA/mainline builds.
Window title bar will now be formatted as `yuzu VersionNumber | Title Name | Title VersionNumber`
> main: Add running title's version to window name on EA/mainline

- .ci/scripts/linux/docker.sh
- .ci/scripts/linux/upload.sh
A regression was introduced on May 13 by linuxdeploy that causes file open dialogs to crash yuzu in the AppImage (likely this commit 1e28ee38fa174279defe70cdaadf2a552c80258c from linuxdeploy/linuxdeploy-desktopfile). Instead of downloading the latest version from each of the repos we use to build the AppImage, just download the ones hosted at yuzu-emu/ext-linux-bin. See yuzu-emu/ext-linux-bin a5bfaae7262630a83d2899e908cc4b6943ba6635 for the specific commits used for each binary.
These are the same binaries we have been using, but verified to be working and won't update on us beyond our control.
This can eventually be moved into the container itself and remove the need to download them at build time.
> ci: linux: Freeze AppImage binaries

- src/yuzu/about_dialog.cpp
- src/yuzu/aboutdialog.ui
- src/yuzu/main.cpp
The nixing of the infamous dot in #6316 caused the yuzu version to disappear from logs and the about dialog.  This PR amends that.
> yuzu/main: Fix version info in logging and about dialog

- src/yuzu/configuration/configure_debug.ui
Duplicate labels were unintentionally introduced due to copy-paste. This silences the compilation warning produced by the presence of these duplicates.
> configure_debug: FIx duplicate labels

- src/core/hle/kernel/k_transfer_memory.h
size is already the size in bytes. We do not need to multiply it by the page size
> KTransferMemory: Return size instead of size * PageSize in GetSize()

- src/input_common/udp/client.cpp
PS3 controllers only have a Z axis for gyro. The rest of the axis contain NAN values which breaks all motion calculations. This PR fixes the problem by filling with zeroes the motion values that are invalid.
> input_common: Sanitize motion data

- src/common/settings.cpp
- src/common/settings.h
- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_64.cpp
- src/core/core.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/config.h
- src/yuzu/configuration/configuration_shared.cpp
- src/yuzu/configuration/configuration_shared.h
- src/yuzu/configuration/configure_audio.cpp
- src/yuzu/configuration/configure_cpu.cpp
- src/yuzu/configuration/configure_cpu.h
- src/yuzu/configuration/configure_cpu.ui
- src/yuzu/configuration/configure_general.cpp
- src/yuzu/configuration/configure_graphics.cpp
- src/yuzu/configuration/configure_graphics_advanced.cpp
- src/yuzu/configuration/configure_per_game.cpp
- src/yuzu/configuration/configure_per_game.ui
- src/yuzu/configuration/configure_system.cpp
- src/yuzu_cmd/config.cpp
Originally I had told myself not to add this bit to per-game settings, as the CPU tab was a place for debug settings. As time went on, settings were add to this tab that apply fixes to specific games, thus the need for this.
This change allows setting CPU accuracy to Accurate or Unsafe per-game, as well as the accuracy options for Unsafe. Debug is not allowed here as a per-game CPU accuracy.
Also took this opportunity to lightly rework the other per-game settings. Code should be a tad easier to maintain in those regards.
This needs testing.
> configuration: Add CPU tab to game properties and slight per-game settings rework

- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
Pops the PID if one is sent in and adds a getter for it.
While we're at it, we can convert the remaining unsigned types to u32 to be more concise and consistent with the rest of the codebase.
> hle_ipc: Add a getter for PID

- src/video_core/renderer_opengl/gl_device.cpp
please let me know if amd users can also be whitelisted on mesa
no device to test atm
> gl_device: Intel: Disable texture view formats workaround on mesa

- src/common/tree.h
- src/core/hle/ipc_helpers.h
- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/kernel/init/init_slab_setup.cpp
- src/core/hle/kernel/k_client_port.cpp
- src/core/hle/kernel/k_client_port.h
- src/core/hle/kernel/k_port.cpp
- src/core/hle/kernel/k_server_port.h
- src/core/hle/kernel/k_server_session.cpp
- src/core/hle/kernel/k_server_session.h
- src/core/hle/kernel/k_session.cpp
- src/core/hle/kernel/k_session.h
- src/core/hle/kernel/k_slab_heap.h
- src/core/hle/kernel/service_thread.cpp
- src/core/hle/kernel/slab_helpers.h
- src/core/hle/service/service.cpp
- src/core/hle/service/sm/controller.cpp
- src/core/hle/service/sm/sm.cpp
- src/core/hle/service/sm/sm.h
- src/core/memory.cpp
- src/core/memory.h
This is a continuation of #6299. With that change, we finally got around to implementing the IPC's mechanisms for moving and closing objects. This was a follow-up to #6266, which migrated kernel objects from std::shared_ptr to KAutoObject, and enforced the real limits for kernel objects.
However, these changes highlighted a longstanding KSession leak, due to limits being enforced and sessions not being properly managed. #6299 temporarily reverted session limits to avoid a crash.
This PR aims to fix these leaks once and for all, and reverts the hacks from #6299. The primary issue was implementing CloneCurrentObject, rather than just trying to fudge reference counts.
This should fix Pokemon Sword/Shield leaks once and for all.
> Various improvements to IPC and session management (Part 2)

- src/input_common/sdl/sdl_impl.cpp
Old code had a flaw where it assigned the controller of the last queued event instead of the controller that triggered the threshold. Use this opportunity to rewrite this code to make it simpler and easier to read.
This PR also fixed a common crashing issue when a controller disconnect event is triggered and It wasn't on the controller list.
> input_common: Rewrite sdl analog mapping and fix controller disconnection crash

- src/common/lz4_compression.cpp
- src/common/lz4_compression.h
- src/common/zstd_compression.cpp
- src/common/zstd_compression.h
Allows the incoming data streams to the APIs to be non-allocating and support more container types.
> common/compression: Make use of std::span

- src/core/hle/kernel/process_capability.cpp
- src/core/hle/kernel/process_capability.h
Since MapRegion isn't supported by the kernel page table, this can be stubbed for now.
- Used by nx-hbloader
> kernel: process_capability: Add MapRegion capability

- src/yuzu/configuration/config.cpp
- src/yuzu/debugger/controller.cpp
- src/yuzu/main.cpp
It's imposible to use docked mode on handheld on real HW. This breaks some games like XC2. This PR fixes this issue by changing the controller type to Pro controller if an user tries to enable docked mode.
> settings: Forbid docked mode on handheld

- CMakeLists.txt
zstd 1.5.0 brings numerous performance improvements to the library, as well as faster decompression speed. Should result in a tiny boost to shader cache compression/decompression.
More info can be seen [here](https://github.com/facebook/zstd/releases/tag/v1.5.0)
> CMakeLists: Update zstd to 1.5.0

- src/yuzu/applets/software_keyboard.cpp
Some users have reported rare crashes when pressing the Enter key on the keyboard to confirm input in the normal software keyboard, particularly in Super Smash Bros. Ultimate while entering the name of a ruleset or controller layout.
It is suspected that the QLineEdit::returnPressed signal is causing a race condition as confirming input through other means does not produce the crash. Since Qt::QueuedConnection posts an event to the event queue of the callee's thread instead of executing it directly on the caller's thread, this eliminates any potential race conditions from occurring in this scenario.
> applets/swkbd: Make use of QueuedConnection in returnPressed signal

- src/core/hle/service/hid/controllers/gesture.cpp
- src/core/hle/service/hid/controllers/gesture.h
We can extend the point struct a little bit to make comparisons and other related operations with points a little less noisy for reading.
> hid/gesture: Simplify point related code

- src/core/arm/arm_interface.h
- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_32.h
- src/core/arm/dynarmic/arm_dynarmic_64.cpp
- src/core/arm/dynarmic/arm_dynarmic_64.h
This code was used to switch the CPU ID on thread switches.
However since "hle: kernel: multicore: Replace n-JITs impl. with 4 JITs.", the CPU ID is not a constant.
This has been dead code since this rewrite, and dropped in dynarmic as well. So there is no need to keep it.
> core/arm: Drop ChangeProcessorID.

- CMakeLists.txt
- CMakeModules/CopyYuzuQt5Deps.cmake
- src/yuzu/CMakeLists.txt
If the local version of Qt is older than the minimum version required by yuzu, download a pre-built binary package of Qt 5.15.2 from yuzu-emu/ext-linux-bin and build yuzu with it. This also links yuzu to and copies over the required libraries when building.
This sets the Qt requirement to 5.12, which is intentionally just behind the versions used by both our MSVC (5.12.8) and GCC/Clang (5.12.6) toolchains. This is meant to serve as a stopgap while those are updated. MinGW has already been using 5.15.2.
Bundled package has requirements GLIBC >= 2.27 and GLIBCXX >= 3.4.28. This means Ubuntu 18.04 and the likes support it, and as far as I know this will not work with Rocky Linux 8 RC1 (GLIBCXX version is too low). This package does not include qtwebengine, as I had trouble getting that …
> cmake: Download Qt binaries on Linux if needed

- src/yuzu/configuration/configure_dialog.cpp
- src/yuzu/configuration/configure_dialog.h
- src/yuzu/configuration/configure_per_game.cpp
- src/yuzu/configuration/configure_per_game.h
- src/yuzu/main.cpp
- src/yuzu/uisettings.h
Most of the code already exists to do this, but the Apply button itself was never added. This adds a button and boolean that tells yuzu to save the configuration after applying settings, even if close/Cancel is pressed on the dialog. Changes after applying will not be saved when Cancel is pressed, though.
The Apply button will only appear on the Configuration and Game Properties dialog if a game is running. This can be changed if people think it's too confusing.
> yuzu qt: Add an Apply button to configuration dialogs

- CMakeLists.txt
CMAKE_DEPENDENT_OPTION takes a value argument, but as a macro function it will read a variable name as the name and not the value. For YUZU_USE_BUNDLED_QT, ensure that we are reading the value of MSVC. For YUZU_ALLOW_SYSTEM_SDL2, CMAKE_DEPENDENT_OPTION is redundant here anyway as we don't use that path on any toolchain by default.
> cmake: Fix usage of CMAKE_DEPENDENT_OPTION

- src/video_core/rasterizer_accelerated.cpp
- src/video_core/rasterizer_accelerated.h
- Greatly reduces the risk of overflow, at the cost of doubling the size of this array.
> video_core: rasterizer_cache: Use u16 for cached page count.

- src/common/fs/file.h
Prevents a potential uninitialized read bug vector in the move constructor in some circumstances (e.g. moving into a default constructed IOFile object)
While we're in the same area, we can make a few minor adjustments.
> common/fs/file: Default initialize IOFile members

- src/core/arm/arm_interface.h
- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_32.h
- src/core/arm/dynarmic/arm_dynarmic_64.cpp
- src/core/arm/dynarmic/arm_dynarmic_64.h
- src/core/hle/kernel/k_scheduler.cpp
So we can modify all of dynarmic states within SVC without ExceptionalExit.
Especially as the ExceptionalExit hack is dropped on upstream dynarmic.
> core/arm_interface: Call SVC after end of dynarmic block.

- src/core/hle/kernel/kernel.cpp
- src/video_core/buffer_cache/buffer_cache.h
std::move created an unneeded copy.
iterating without reference also created copies.
> Fix two GCC 11 warnings: Unneeded copies.

- src/core/hle/kernel/k_slab_heap.h
- src/core/hle/kernel/kernel.cpp
- Use host allocations for kernel memory, as this is not properly emulated yet.
- Use guest allocations for TLS, as this needs to be backed by DeviceMemory.
> hle: kernel: KSlabHeap: Allow host or guest allocations.

- src/core/hle/kernel/k_thread.cpp
Prevents a -Wnonnull warning on GCC.
> k_thread: Move dereference after null check in Initialize()

- src/core/hle/kernel/k_client_port.h
- src/core/hle/kernel/k_client_session.h
- src/core/hle/kernel/k_event.h
- src/core/hle/kernel/k_port.h
- src/core/hle/kernel/k_process.h
- src/core/hle/kernel/k_readable_event.h
- src/core/hle/kernel/k_resource_limit.h
- src/core/hle/kernel/k_server_port.h
- src/core/hle/kernel/k_server_session.h
- src/core/hle/kernel/k_session.h
- src/core/hle/kernel/k_shared_memory.h
- src/core/hle/kernel/k_synchronization_object.h
- src/core/hle/kernel/k_thread.h
- src/core/hle/kernel/k_transfer_memory.h
- src/core/hle/kernel/k_writable_event.h
Over the course of the kernel refactoring a tiny bit of missing overrides slipped through review, so we can add these to prevent compiler warnings from occurring.
While we're at it, we can remove redundant virtual keywords where applicable as well, since override already signifies a virtual function.
> kernel: Add missing override specifiers

- src/core/hle/service/ldn/ldn.cpp
Mario Kart Live: Home Circuit needs lp2p:sys lp2p:app INetworkServiceMonitor INetworkService to be able to progress. 
Note: The game still fails to boot from unimplemented LDN and BSD services.
> ldn: Add and stub lp2p:sys lp2p:app INetworkServiceMonitor INetworkService

- src/core/hle/service/am/applets/software_keyboard.cpp
- src/yuzu/applets/software_keyboard.cpp
Applications may leave this region of memory uninitialized when the text check result is not either Failure or Confirm.
Attempting to read uninitialized memory may cause an exception within the UTF16 to UTF8 string converter.
Fix this by only reading the text check message on Failure or Confirm.
While we're at it, we can make use of std::move where applicable to avoid redundant string copies.
This should fix any remaining crashing issues in games such as Super Smash Bros. Ultimate when entering a name for a ruleset or controller profile.
Special thanks to both @gidoly and @OZtistic for reproducing this issue and sending stack traces which led to the fix.
> applets/swkbd: Only read the text check message on Failure/Confirm

- src/video_core/gpu.cpp
- src/video_core/gpu.h
- Fixes a hang on shutdown when NVFlinger thread is waiting on a syncpoint that will never occur.
- Commonly observed when stopping emulation in Super Mario Odyssey.
> video_core: gpu: WaitFence: Do not block threads during shutdown.

- src/core/hle/kernel/k_class_token.cpp
> k_class_token: Use variable templates where applicable

- src/common/CMakeLists.txt
- src/common/point.h
- src/core/hle/service/hid/controllers/gesture.h
- src/core/hle/service/hid/controllers/touchscreen.cpp
- src/core/hle/service/hid/controllers/touchscreen.h
A point is a fairly basic abstraction that is better put in common (along with Rectangle, and Vec), which can then be reused elsewhere without bringing in any unrelated code.
> common: Extract Point struct into common

- src/common/page_table.cpp
- src/common/page_table.h
- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_64.cpp
- src/core/memory.cpp
This makes it by far harder to crash yuzu.
Also implement the 48bit masking of AARCH64 while touching this code.
> core/memory: Check our memory fallbacks for out-of-bound behavior.

- .ci/scripts/windows/docker.sh
- CMakeLists.txt
- externals/libusb/CMakeLists.txt
After updating to 1.0.24, MinGW fails to build libusb as a result of numerous errors. So we build libusb their way and let them update the nontrivial stuff.
This only applies to MinGW: the old path is still in use for Linux toolchains as well as MSVC.
This will dynamically link libusb, since I hit build errors with the old way we used to resolve the conflict with SDL2.
git diff is going to git diff, but everything after the `else() # MINGW` is identical to the previous version, sans a indentation correction.
> externals: libusb: Use autotools for MinGW

- src/input_common/sdl/sdl_impl.cpp
- src/input_common/sdl/sdl_impl.h
Adds a dual joycon support by merging two individual joycon that share the same port together.
Corrects mapping to use the proper SL/SR buttons of joycons.
> input_common: Add dual joycon support

- externals/CMakeLists.txt
Whatever those settings do breaks controller detection on Windows, at least with the MinGW container. If-guard it against WIN32 and just let SDL2 configure using its defaults, aside from static linking.
> externals: Use defaults for building SDL2 on WIN32

- src/common/fs/fs_util.cpp
- src/common/fs/fs_util.h
- src/common/fs/path_util.cpp
- src/common/fs/path_util.h
These string conversion functions are required for enforcing UTF-8 encoded paths in the future,
> common: fs: fs_util: Add more string conversion functions

- src/common/common_funcs.h
- src/core/hle/result.h
These macros all interact with the result code type, so they should ideally be within this file as well, so all the common_funcs machinery doesn't need to be pulled in just to use them.
Moves an implicit core dependency out of common.
> common_funcs: Move R_ macros to result.h

- src/yuzu/game_list.cpp
There's no need to check the first and last rows since they'll always be the _Favorites_ and _Add Directory_ rows.
I decided to remove the `folder_count` variables because it doesn't just hold the folder count, but also the previous mentioned rows.
Also change the name of the `clear_all` variable for consistency.
> game_list: Minor for loop optimizations

- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/config.h
- src/yuzu/configuration/configure_per_game.cpp
- src/yuzu/configuration/configure_per_game.h
- src/yuzu/game_list.h
- src/yuzu/main.cpp
- src/yuzu/main.h
Fixes a heap-use-after free reported by AddressSanitizer, caused by #6361. This makes use of std::filesystem::path, but due to that we have to use their `string()` function which may not work well with some characters on Windows.
Draft because I need testing.
> yuzu qt: Revert some usages of string_view

- src/yuzu/game_list.cpp
- src/yuzu/game_list_worker.cpp
Rather than deleteing and re-inserting columns and working with modified indexes, just hide the one(s) we don't want to show instead, and keep everything the same. Save the new layout every time it's altered through resize, move or sort.
The column sizes were being reset a lot through startup, after the original load from config. I believe they were mainly coming from the setHeaderData calls in PopulateAsync. By hiding the column instead, they can all be removed. The header is only saved on game boot and yuzu's exit, so any modifications to the layout and then using a menu call which calls PopulateAsync would reset everything, as it calls LoadInterfaceLayout() without a save beforehand. I don't think that's needed, as populate should only be filling the rows and not altering the columns. …
> game_list: Stop the columns resizing on NAND install

- src/yuzu/game_list.cpp
- src/yuzu/game_list.h
The setLayout call in game list instanciation will call resizing signals with default values in light theme, which was then being erroneously saved. setLayout doesn't seem to call resizing for any other theme, so I'm not sure why that happens.
> [game_list] Correct light theme loading

- src/core/frontend/input.h
- src/input_common/analog_from_button.cpp
- src/input_common/keyboard.cpp
Use a different approach for emulating an analog stick from buttons.
- Removes the need for creating a thread for each joystick instance
- Fixes some crash errors on close
This also implements callbacks events on inputs to update data as soon it's available
> input_common: Analog button, use time based position

- src/yuzu/configuration/configure_input_player_widget.cpp
- src/yuzu/configuration/configure_input_player_widget.h
- src/yuzu/debugger/controller.cpp
Currently the controller debugger it's running even if it's on background. This is not ideal since it's only consuming resources.
This also helps detecting wrong configurations since it will not update until the controller it's enabled
> settings: Disable controller preview if controller is not active

- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
Current yuzu-cmd produces a segfault in `TouchFromButtonDevice::TouchFromButtonDevice()`, because touch from button settings are not parsed or initialized for yuzu-cmd. This PR suggests options for setting touch from button feature inside `sdl2-config.ini` and parses those settings. Additionally, it fixes the section name `[Controls]` to `[ControlsGeneral]` in the default config file, which was changed a while ago.
> yuzu-cmd: Add touch_from_button in config file

- src/core/hle/result.h
The result code classes are used quite extensively throughout both the kernel and service HLE code. We can mark these member functions as [[nodiscard]] to prevent a few logic bugs from slipping through.
> result: Add [[nodiscard]] specifiers where applicable

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/engines/maxwell_3d.cpp
- src/video_core/memory_manager.cpp
- src/video_core/rasterizer_interface.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.h
Currently, In order to disable uniform buffers (set them to `NULL_BINDING`), the gpu address and size are set to zero and sent through the same path as the valid buffers that are being bound. This resulted in the GPU to CPU address lookup to fail, indicating that the buffer should be disabled.
This PR aims to make disabling uniform buffers more explicit. Disabling uniforms is now handled by `DisableGraphicsUniformBuffer`, alleviating `BindGraphicsUniformBuffer` from the responsibility to handle both the binding and disabling logic.
> buffer_cache: Simplify uniform disabling logic

- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/kernel/k_auto_object.h
- src/core/hle/kernel/k_auto_object_container.cpp
- src/core/hle/kernel/k_auto_object_container.h
- src/core/hle/kernel/k_client_port.cpp
- src/core/hle/kernel/k_client_port.h
- src/core/hle/kernel/k_client_session.h
- src/core/hle/kernel/k_readable_event.h
- src/core/hle/kernel/k_server_port.cpp
- src/core/hle/kernel/k_server_port.h
- src/core/hle/kernel/k_server_session.cpp
- src/core/hle/kernel/k_server_session.h
- src/core/hle/kernel/k_session.cpp
- src/core/hle/kernel/k_session.h
- src/core/hle/kernel/k_writable_event.cpp
- src/core/hle/service/ns/pl_u.cpp
- src/core/hle/service/service.cpp
- src/core/hle/service/service.h
- src/core/hle/service/sm/controller.cpp
- src/core/hle/service/sm/sm.cpp
- Previously, we would allocate a thread per session, which adds new threads on CloneCurrentObject.
- This results in race conditions with N sessions queuing requests to the same service interface.
- Fixes Pokken Tournament DX crashes/softlocks, which were regressed by #6347.
> hle: kernel: Refactor to allocate a ServiceThread per service handler.

- src/video_core/textures/decoders.cpp
This is not a real fix, so assert here and continue before crashing.
> decoders: Avoid out-of-bounds access

- src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2_gl.h
Commit 7003090187e02c8625f4eb7a024ac97f9b0159aa changed the way rendering is performed, but it was incorrectly modified in yuzu-cmd, resulting in the disappearance of buffer swapping. This PR recovers the rendering for sdl2 GL.
> yuzu-cmd: Fix OpenGL rendering

- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/hle_ipc.h
- src/core/hle/kernel/k_server_session.cpp
- src/core/hle/kernel/kernel.cpp
- We no longer need to queue up service threads to be destroyed.
- Fixes a race condition where a thread could be destroyed too early, which caused a crash in Pokemon Sword/Shield.
> hle: kernel: Remove service thread manager and use weak_ptr.

- src/yuzu/configuration/configure_ui.cpp
Allows for these strings to show up in the translation files.
Also silences some warnings when generating the ts files.
> configure_ui: Add translation context for file-scope strings

- src/common/fs/path_util.h
We can't make use of the return value here, since we don't a return value to work with.
> common/fs/path_util: Remove [[nodiscard]] from function with void return

- src/common/CMakeLists.txt
Fix the variable escaping in `src/common/CMakeLists.txt`.
According to CMake (https://cmake.org/cmake/help/latest/command/add_custom_command.html):
>  All arguments to the commands will be escaped properly for the build tool so that the invoked command receives each argument unchanged. Note that one level of escapes is still used by the CMake language processor before add_custom_command even sees the arguments. Use of VERBATIM is recommended as it enables correct behavior. When VERBATIM is not given the behavior is platform specific because there is no protection of tool-specific special characters.
This should resolve the title bar text issue on Linux.
> src/common/CMakeLists.txt: fix variable escaping

- src/core/hle/kernel/svc.cpp
- Avoids a potential crash if the handle is invalid, and also makes this code accurate to real kernel behavior.
> kernel: svc: Add missing error check to CancelSynchronization.

- .ci/scripts/common/post-upload.sh
- .ci/scripts/windows/upload.sh
Removes the 7z from being package during CI, as only .tar.xz preserves information needed on Linux, and otherwise is just extremely redundant to package in addition to the .tar.xz.  This affects Linux releases and PR-verify artifacts only. MSVC releases do not use this script to my knowledge.
Draft simply so I can verify that CI is correctly not packaging the .7z.
> ci: common: Remove 7z packaging

- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/k_client_port.cpp
- src/core/hle/kernel/k_server_session.h
- src/core/hle/service/service.h
- src/core/hle/service/sm/sm.cpp
- Prevents a cloned session's handler from being overwritten by another disconnected session.
- Fixes session handler nullptr asserts with Pokemon Sword & Shield.
> hle: kernel: KServerSession: Fix client disconnected.

- src/core/hle/service/service.h
- src/core/hle/service/sm/sm.cpp
- We were double-reserving, causing us to run out of sessions in Pokemon Sword & Shield.
> hle: service: sm: Remove redundant session reservation, etc.

- src/core/file_sys/program_metadata.cpp
- src/video_core/buffer_cache/buffer_base.h
- src/video_core/texture_cache/util.cpp
* Wrong alignment in u64 LOG_DEBUG -> memcpy.
* Huge shift exponent in stride calculation for linear buffer, unused result -> skipped.
* Large shift in buffer cache if word = 0, skip checking for set bits.
Non of those were critical, so this should not change any behavior.
At least with the assumption, that the last one used masking behavior, which always yield continuous_bits = 0.
Credit for the texture cache bug @ReinUsesLisp 
Supersedes #6144 and #6147
> Fix GCC undefined behavior sanitizer.

- src/common/CMakeLists.txt
- src/common/host_memory.cpp
- src/common/host_memory.h
- src/common/page_table.h
- src/common/settings.cpp
- src/common/settings.h
- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_64.cpp
- src/core/device_memory.cpp
- src/core/device_memory.h
- src/core/memory.cpp
- src/tests/CMakeLists.txt
- src/tests/common/host_memory.cpp
- src/video_core/gpu_thread.cpp
- src/video_core/rasterizer_accelerated.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_cpu.cpp
- src/yuzu/configuration/configure_cpu.h
- src/yuzu/configuration/configure_cpu.ui
- src/yuzu/configuration/configure_cpu_debug.cpp
- src/yuzu/configuration/configure_cpu_debug.ui
- src/yuzu_cmd/default_ini.h
This Pull Request finally implements a long requested feature from Citra: Fastmem. Fastmem is the name we have given to emulating the MMU by using Host allocation instead of software MMU emulation. In the previous approach, we would emulate Guest virtual memory through a page table where we would store addresses to physical memory for each virtual page the application/game had. Whenever a game accessed memory, we would look into the emulated page table check if we have a valid physical mem address and then read the memory, if the physical address wasn't valid, the game would call an emulator fallback. All this costed around 10-15 instructions.
On fastmem, we use instead about 4 instructions: 3 for checking if the address is within the emulated address space (can be disabled with Unsafe …
> Implement/Port Fastmem from Citra to Yuzu

- src/yuzu/main.cpp
This warns the user if there isn't enough free space to dump the entire RomFS to disk. It requires at least the size of the extracted RomFS + 1 GiB as a buffer of free space.
> yuzu: main: Ensure enough space is available for RomFS dumping

- externals/libusb/CMakeLists.txt
Fixes an issue where libusb.h wouldn't be found when building yuzu on MSVC.
This only affects the "traditional" CMake pathway for linking libusb to yuzu AKA MSVC. For autotools we still want to set these variables before configuring SDL.
> externals: Don't set FOUND or VERSION on LIBUSB

- src/core/hle/service/lm/lm.cpp
Guest logs are intended for use by the game developers during development. 
As such, they provide little meaning to be logged by yuzu and tend to overwhelm the log output at times.
> lm: Demote LM guest logs to LOG_DEBUG

- src/common/fs/file.cpp
std::fflush does not guarantee that file buffers are flushed to the disk.
Use _commit on Windows and fsync on all other OSes to ensure that the file is flushed to the disk.
> common: fs: file: Flush the file to the disk when Flush() is called

- src/common/fs/file.cpp
- src/common/fs/file.h
- src/common/settings.h
- src/core/hle/service/filesystem/fsp_srv.cpp
- src/core/hle/service/filesystem/fsp_srv.h
- src/core/reporter.cpp
- src/core/reporter.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_debug.ui
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
This introduces a new setting Enable FS Access Log which saves the filesystem access log to sdmc:/FsAccessLog.txt
If this setting is not enabled, this will indicate to FS to not call OutputAccessLogToSdCard.
NOTE: This setting is not enabled by default.
NOTE2: This setting **does not need to be enabled** to fix the loading softlock in XC2, it is only **meant for debugging purposes**
Fixes softlocks during loading in Xenoblade Chronicles 2 when certain DLC is enabled.
Supersedes #6458 
Fixes #4712 
Thanks to @gidoly, @OZtistic and @G-Spawn for testing
> fsp_srv: Fix filesystem access logging

- src/common/settings.cpp
- src/common/settings.h
- src/core/telemetry_session.cpp
- src/video_core/CMakeLists.txt
- src/video_core/host_shaders/astc_decoder.comp
- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/texture_cache/util.cpp
- src/video_core/textures/astc.cpp
- src/video_core/textures/astc.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_graphics.cpp
- src/yuzu/configuration/configure_graphics.h
- src/yuzu/configuration/configure_graphics.ui
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
Some drivers may cause hangs/crashes if the GPU is under compute heavy loads for extended periods of time, causing games which make extensive use of ASTC textures, such as Astral Chain, to be unplayable. 
This PR adds a toggle in the graphics settings to fall back to the CPU ASTC decoder. 
This is a temporary work around while a more robust solution for GPU acceleration is developed.
> textures: Add a toggle for GPU Accelerated ASTC decoder 

- src/video_core/texture_cache/util.cpp
Avoids API usage errors on UE4 titles leading to crashes on Vulkan.
> texture_cache/util: Avoid relaxed image views on different bytes per block

- externals/CMakeLists.txt
- src/audio_core/CMakeLists.txt
- src/audio_core/sdl2_sink.cpp
- src/audio_core/sdl2_sink.h
- src/audio_core/sink_details.cpp
- src/yuzu_cmd/default_ini.h
Add SDL2 audio backend. SDL2 has two possible mechanisms for sending audio samples: callback and buffer queue. I chose the later because it's the same as the api I needed to follow.
> Audio: SDL2 audio backend

- src/video_core/vulkan_common/vulkan_debug_callback.cpp
Some validation errors are known to be false positive. We can skip them from being logged to avoid flooding the log stream with errors that are not applicable to yuzu
> vulkan_debug_callback: Skip logging known false-positive validation errors

- .gitmodules
This PR updates the discord-rpc submodule to last upstream commit, before it was deprecated in favour of Discord's new GameSDK. Since the new SDK is closed-source, we can't upgrade to it.  
However, Discord RPC still uses the same underlying code for Rich Presence and hence RPC compatibilty is not broken (*yet!*).
The changes from last-updated commit include few minor bugfixes and readme changes.
> update submodule discord-rpc to latest [now deprecated]

- src/common/host_memory.cpp
Microsoft defines `MEM_RESERVE_PLACEHOLDER` as `0x00040000` [here](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc2), but our manually imported version of it drops the last zero.
This fixes fastmem failing to load on MinGW builds.
> host_memory: Correct MEM_RESERVE_PLACEHOLDER

- src/common/settings.h
- src/core/hle/service/nvflinger/nvflinger.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/config.h
- src/yuzu/configuration/configure_graphics_advanced.cpp
- src/yuzu/configuration/configure_graphics_advanced.h
- src/yuzu/configuration/configure_graphics_advanced.ui
- src/yuzu/main.cpp
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
This adds a toggle which lifts the swap interval waiting on the vsync thread, allowing nvflinger buffers to be pushed for processing by the GPU as soon as they become available.
Display/driver vsync must be disabled for this to setting take effect. The speed at which the title will be running will be increased. There is the potential to cause instabilities in some titles, and the toggle may not work on all titles. 
As such, it remains as a debug setting. The main use case is to allow for potentially easier benchmarking by surpassing the framerate limits of most titles. It can be toggled during runtime via the settings or a hotkey, which is defaulted to `Ctrl+U`
> nvflinger: Add experimental toggle to disable buffer swap interval limits

- src/common/settings.cpp
- src/common/settings.h
- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_cpu.cpp
- src/yuzu/configuration/configure_cpu.h
- src/yuzu/configuration/configure_cpu.ui
This PR updates dynarmic and adds an option to loose the rounding mode on ASIMD instructions (32 bits).
> Update dynarmic and add new unsafe CPU option.

- src/core/core.cpp
Fixes potential data races when shutting down.
> core: Make is_powered_on atomic

- .ci/scripts/windows/docker.sh
Qt can make use of `qwindowsvistastyle.dll` if present, and our MinGW container has the library, but it was not being copied during the packaging process. Thus, yuzu looked like a Windows 98 application when using the MinGW PR-verify artifacts.
This copies over the DLL during packaging, for that sweet-sweet Windows Vista style.
In addition, set the Qt plugins path instead of the plugins/platforms path. This way we can use the directory directly, rather than appending a `..` every time we need something just outside of it.
> ci: windows: Copy the Qt styles directory when packaging

- src/video_core/renderer_vulkan/vk_master_semaphore.cpp
- src/video_core/renderer_vulkan/vk_master_semaphore.h
This minor change is intended to test if we can use `std::jthread`.
> vk_master_semaphore: Use jthread for debug thread

- src/core/CMakeLists.txt
- src/core/file_sys/system_archive/system_version.cpp
- src/core/hle/api_version.h
- src/core/hle/service/spl/csrng.cpp
- src/core/hle/service/spl/module.cpp
- src/core/hle/service/spl/module.h
- src/core/hle/service/spl/spl.cpp
- src/core/hle/service/spl/spl_results.h
- src/core/hle/service/spl/spl_types.h
SPL is used by homebrew to determine the firmware it is running on.
Many homebrew will assume that it is being run on Atmosphere, a custom firmware for the Nintendo Switch. As such, we will mimic its behavior and report that we are Atmosphere, allowing for these homebrew to run properly on yuzu.
> service: spl: Implement general SPL service

- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
Add a lock to avoid data races.
This reduces the number of -fsanitize=thread errors significantly.
> npad: Fix data race when updating devices

- src/input_common/mouse/mouse_input.cpp
- src/input_common/mouse/mouse_input.h
Fix data race using std::jthread and std::stop_token.
> input_common/mouse_input: Fix data race

- src/common/detached_tasks.cpp
If this is not waited on, the synchronization primitives are destroyed
when main exits and the detached task ends up signalling garbage and not
properly finishing.
> common/detached_tasks: Wait for tasks before shutting down

- src/yuzu/configuration/configure_per_game.cpp
- src/yuzu/configuration/configure_per_game.ui
Corrects window sizing of Per-Game configuration window and removes the unused Help hint button from the title bar
> Simple resizing of Per-Game configuration window and removal of useless Help question mark button in the title bar

- src/video_core/rasterizer_interface.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_opengl/gl_shader_cache.h
- src/yuzu/bootmanager.cpp
- src/yuzu/bootmanager.h
- src/yuzu_cmd/yuzu.cpp
Use its std::stop_token to abort shader cache loading.
Using std::stop_token instead of std::atomic_bool allows the usage of
other utilities like std::stop_callback.
> bootmanager: Use std::stop_source for stopping emulation

- src/common/common_sizes.h
- src/common/settings.cpp
- src/common/settings.h
- src/video_core/buffer_cache/buffer_base.h
- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_opengl/gl_texture_cache.h
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
- src/video_core/surface.cpp
- src/video_core/surface.h
- src/video_core/texture_cache/image_base.cpp
- src/video_core/texture_cache/image_base.h
- src/video_core/texture_cache/slot_vector.h
- src/video_core/texture_cache/texture_cache.h
- src/video_core/texture_cache/util.cpp
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
- src/video_core/vulkan_common/vulkan_memory_allocator.cpp
- src/video_core/vulkan_common/vulkan_memory_allocator.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_graphics_advanced.cpp
- src/yuzu/configuration/configure_graphics_advanced.h
- src/yuzu/configuration/configure_graphics_advanced.ui
- src/yuzu_cmd/default_ini.h
This PR instroduces a new GC for GPU Caches, it will try keep memory at between 2.5-4Gb VRAM by removing `Least Used Resources` and Texture Cache leftovers. In general, the GC is pretty safe but it does seem to have some issues in games like SMO when travelling through kingdoms may cause graphics issues (very few to notice though). My current guess is that it's due to GPU VMM Remaps not notifying TCR. This will be fixed in a further PR.
> GPU: Implement a garbage collector for GPU Caches (project Reaper+)

- src/video_core/engines/maxwell_3d.h
We were returning '1' in ComponentCount()'s default case but were neglecting to do the same with SizeInBytes().
Resolves a warning on *nix platforms and makes it a little more consistent in terms of behavior (assuming anything ever actually hits this).
> maxwell3d: Add missing return in default SizeInBytes() case

- CMakeLists.txt
- src/common/hex_util.h
- src/core/crypto/key_manager.cpp
- src/core/file_sys/registered_cache.cpp
- src/core/frontend/input.h
- src/core/hle/service/service.cpp
- src/video_core/renderer_opengl/gl_arb_decompiler.cpp
- src/video_core/renderer_opengl/gl_shader_decompiler.cpp
- src/yuzu/about_dialog.cpp
- src/yuzu/main.cpp
Keeps us up to date with the latest major release.
Also allows compilers that support it to perform compile-time format string checking, allowing format string errors to be caught sooner.
8.0.0 introduces quite a bunch of changes, so the entire changelog can be viewed [here](https://github.com/fmtlib/fmt/releases/tag/8.0.0).
> externals: Update fmt to 8.0.0

- src/video_core/host_shaders/astc_decoder.comp
- src/video_core/renderer_opengl/util_shaders.cpp
- src/video_core/renderer_vulkan/vk_compute_pass.cpp
- src/video_core/textures/astc.cpp
- src/video_core/textures/astc.h
These changes should help in reducing crashes/driver panics that may
occur due to synchronization issues between the shader completion and
later access of the decoded texture.
Tested on an RTX 2080s, GTX 1070, GTX 970, and my very own GT 730,
and there were no ASTC related crashes in some of the most demanding
areas of Astral Chain.
> astc: Various robustness enhancements for the gpu decoder

- src/audio_core/common.h
- src/core/hle/ipc_helpers.h
- src/core/hle/service/aoc/aoc_u.cpp
- src/core/hle/service/aoc/aoc_u.h
- src/core/hle/service/audio/hwopus.cpp
- src/core/hle/service/audio/hwopus.h
This change adds several HLE/service updates for the most recent SDK update. These are all used by Doom Eternal v1.5, which is now booting with these changes.
> services: Misc. minor changes for latest SDK update.

- src/yuzu/main.cpp
Displays whether the currently running title uses 64-bit instructions or only 32-bit instructions.
Useful to know which games would benefit from certain optimizations, since some of the CPU/dynarmic unsafe options apply only to 32-bit titles.
Example screenshot:
> main: Display the instruction set of the running title in the window name

- src/video_core/renderer_base.h
- src/video_core/renderer_opengl/gl_device.cpp
- src/video_core/renderer_opengl/gl_device.h
- src/video_core/renderer_opengl/renderer_opengl.h
- src/video_core/renderer_vulkan/renderer_vulkan.h
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
- src/yuzu/main.cpp
- src/yuzu/main.h
Adds the GPU driver vendor to the title bar of yuzu while running a title, making it easier to confirm which driver is currently being used as the renderer.
Currently the mappings are for the most common drivers and drivers which benefit from being clearly identified (i.e. the OPENSWR software renderer, which misleadingly reports the vendor name as `Intel Corporation`)
Huge thanks to @lat9nq for confirming and populating Linux driver mappings.
Example screenshot:
> main: Add GPU Vendor name to running title bar

- src/core/file_sys/patch_manager.cpp
- src/core/file_sys/patch_manager.h
- src/core/file_sys/sdmc_factory.cpp
- src/core/file_sys/sdmc_factory.h
- src/core/hle/service/filesystem/filesystem.cpp
- src/core/hle/service/filesystem/filesystem.h
- src/yuzu/game_list.cpp
- src/yuzu/game_list.h
- src/yuzu/main.cpp
- src/yuzu/main.h
This was just a literal shower thought about making it easier to use [Ultimate Mod Manager](https://github.com/ultimate-research/UltimateModManager) on yuzu.
Adds to yuzu's Qt frontend a context menu option to dump the RomFS to either the normal directory, or to a subdirectory in the sdmc data directory (`yuzu/sdmc/atmosphere/contents/[title_id]/romfs`). In core, an extra singular mod is added to each game that has contents in this directory.
So now, to use UMM, it should be as easy as right clicking SSBU -> Dump RomFS -> Dump RomFS to SDMC Directory, then opening UMM and installing your mods, then booting SSBU.
> yuzu qt, core: Support LayeredFS mods from SDMC directory

- CMakeLists.txt
- externals/libusb/CMakeLists.txt
- src/video_core/host_shaders/CMakeLists.txt
On a few externals our CMake code will begin to configure or build, but missing programs/libraries/headers will cause crashes later on, often during compilation. This PR does three things to improve that:
1. Our code requires CMake 3.15, but our usages of `find_program` use `REQUIRE`, a 3.18 feature. This removes `REQUIRE` from those and instead checks the success of those functions the old way.
2. Check for required tools needed to configure FFmpeg and libusb before compile time, since we configure those during compilation.
3. Check for dependencies and compatibility with the Qt 5.15.2 bundled package. The ensures that the GLIBCXX version is compatible, all headers are needed for the bundle package, and the xcb/xkb libraries needed during yuzu's runtime are present.
Draft just so I can …
> cmake: Improve Linux dependency checking for externals

- src/audio_core/audio_renderer.cpp
- src/audio_core/audio_renderer.h
- src/audio_core/command_generator.cpp
- src/audio_core/command_generator.h
- src/audio_core/info_updater.cpp
- src/audio_core/voice_context.cpp
- src/audio_core/voice_context.h
- src/core/hle/service/audio/audren_u.cpp
Currently, processing of audio samples is called from AudioRenderer's Update method, using a fixed 4 buffers to process the given samples. Games call Update at variable rates, depending on framerate and/or sample count, which causes inconsistency in audio processing. From what I've seen, 60 FPS games update every ~0.004s, but 30 FPS/160 sample games update somewhere between 0.02 and 0.04, 5-10x slower. Not enough samples get fed to the backend, leading to a lot of audio skipping.
This PR seeks to address this by de-coupling the audio consumption and the audio update. Update remains the same without calling for buffer queuing, and the consume now schedules itself to run based on the sample rate and count.
> [audio_core] Decouple audio update and processing, and process at variable rate

- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/texture_cache/texture_cache.h
This fixes RE:Zero, MHR2 Demo and likely many other games.
> TextureCache: Fix 1D to 2D overlapps.

- src/CMakeLists.txt
This supplements C4101 by detecting initialized but unreferenced local variables
> CMakeLists: Enforce C4189 on MSVC

- src/input_common/analog_from_button.cpp
Whoops I forgot to add this button. Joystick will now update if you press the modifier button
> input_common: Add missing modifier callback to analog from button

- src/video_core/cdma_pusher.cpp
- src/video_core/command_classes/codecs/codec.cpp
- src/video_core/command_classes/codecs/codec.h
- src/video_core/command_classes/codecs/h264.cpp
- src/video_core/command_classes/codecs/h264.h
- src/video_core/command_classes/codecs/vp9.cpp
- src/video_core/command_classes/codecs/vp9_types.h
- src/video_core/command_classes/nvdec.cpp
- src/video_core/command_classes/nvdec.h
- src/video_core/command_classes/nvdec_common.h
Moves NVDEC registers into NVDEC, rather than in Codec, and change the way the methods are called.
Add offsets to the structs and introduce bitfields. H264 especially currently relies on raw bitshifting and AND'ing the flags, this PR makes the code clearer to read what's being used, and less error-prone.
Statically assert struct member offsets for some safety.
Remove a lot of unnecessary initialisation in the structs.
Rename a few members based on official docs, as per ameerj's request.
> Slightly refactor NVDEC and codecs for readability and safety

- src/core/hle/service/mii/manager.cpp
We were including the first 2 default miis which are not meant to be shown in games. With this change, we properly retrieve the 6 default miis shown in games, with 3 of each gender.
> service: mii: Retrieve the correct default miis.

- src/CMakeLists.txt
- src/core/CMakeLists.txt
- src/input_common/CMakeLists.txt
- src/input_common/gcadapter/gc_adapter.cpp
- src/input_common/udp/protocol.h
- src/video_core/CMakeLists.txt
- src/video_core/command_classes/codecs/codec.h
- src/video_core/command_classes/vic.cpp
- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/texture_cache/image_base.cpp
- src/video_core/texture_cache/util.cpp
- src/video_core/textures/astc.cpp
Enforce C4242 in core, video_core, and input_common
Enforce C4018, C4267, C4305, C4389 throughout the entire project
> general: Enforce multiple warnings in MSVC

- src/CMakeLists.txt
- src/audio_core/CMakeLists.txt
- src/core/CMakeLists.txt
- src/input_common/CMakeLists.txt
Treats (un)signed comparison mismatches as errors to be consistent with MSVC
> CMakeLists: Treat -Wsign-compare as an error on GCC/Clang

- src/video_core/memory_manager.cpp
- src/video_core/memory_manager.h
- src/video_core/rasterizer_interface.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.h
- src/video_core/texture_cache/image_base.cpp
- src/video_core/texture_cache/image_base.h
- src/video_core/texture_cache/texture_cache.h
- src/video_core/texture_cache/types.h
- src/video_core/texture_cache/util.cpp
- src/video_core/texture_cache/util.h
This PR takes care of addressing the issues about resources that are partially mapped, uncontinuously mapped or not mapped at all. This should improve the tracking of such resources in the texture cache.
As a consequence: this fixes texture streaming in UE4 games (Oceanhorn 2, Spyro, Bravely Default 2, etc). Have in mind that most UE4 still need the fixes of Hades.
> GPU Memory Manager - Correct handling of non continuous backing memory.

- src/video_core/renderer_opengl/util_shaders.cpp
According to https://gitlab.freedesktop.org/mesa/mesa/-/issues/3820#note_753371 we need to set these to true for use with 3D textures.
Fixes BOTW teleporting on RadeonSI and iris.
> util_shaders: Fix BindImageTexture

- src/core/hle/service/audio/audren_u.cpp
Tales of Vesperia calls this, and caps the number of channels it will output to the result. Only sending back 1 was limiting it to left speaker-only mono audio.
Ideally it should be pulled from the actual active buffer's channel count (?), but I'm not sure how to access it from this service. I don't know why it's calling through audren to get the channels for audout. It doesn't even use audren at all otherwise, just this single function.
Closes https://github.com/yuzu-emu/yuzu/issues/6175.
Edit: Setting the maximum of 6 channels actually caused issues with the audio quality in the game, not sure why. Just reporting 2 instead for now.
> [audren] Report 2 channels active rather than 1

- src/audio_core/audio_renderer.cpp
- src/audio_core/command_generator.cpp
- src/audio_core/command_generator.h
- src/audio_core/sink_context.cpp
- src/audio_core/sink_context.h
Many games report 6 channel output while only providing data for 2. We only output 2-channel audio regardless, and in the downmixing, front left/right are only providing 36% of their volume. This is done assuming all of the other channels also contain valid data, but in a few games they don't. This PR alters the downmixing to preserve front left/right, so volume is not lost.
This improves Link's Awakening, New Super Mario Bros U, Disgaea 6, Super Kirby Clash.
Buffer raw pointers have been replaced with spans as well. This was mainly to aid debugging, as MSVC won't show elements of pointers, but will show the whole span.
> audio_core: Preserve front channel volume after 6 to 2 downmix

- src/audio_core/command_generator.cpp
- src/audio_core/command_generator.h
Adds a few more PCM formats to decode. Only one missing now is PCM24 due to it being awkward. Haven't seen s8 or s32 used in any games so far, but float is used rarely.
Fixes Ys IX audio.
> Support more PCM formats

- src/video_core/engines/fermi_2d.cpp
- src/video_core/texture_cache/texture_cache.h
When I was testing DQ3, I found some strange lines(see before image). Through my debugging, the problem caused by the out-of-bounds blit is not handled properly(#6289). This PR aims to handle this by adding an offset to source texture address to eliminate copy problems caused by out-of-bounds Blit.
**Before**
**After:**
> Out of bound blit

- src/yuzu/configuration/config.cpp
This is a bug fix. Enabling graphics debug mode, then saving a custom
configuration causes graphics debugging to be saved and read from the
custom configuration.
Isolate it the same way we isolate the CPU settings.
> yuzu qt: config: Only save renderer_debug as a global setting

- src/common/settings.cpp
- src/common/settings.h
- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_64.cpp
- src/yuzu/CMakeLists.txt
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure.ui
- src/yuzu/configuration/configure_cpu.cpp
- src/yuzu/configuration/configure_cpu.h
- src/yuzu/configuration/configure_cpu.ui
- src/yuzu/configuration/configure_cpu_debug.ui
- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_debug.ui
- src/yuzu/configuration/configure_debug_tab.cpp
- src/yuzu/configuration/configure_debug_tab.h
- src/yuzu/configuration/configure_debug_tab.ui
- src/yuzu/configuration/configure_dialog.cpp
The current CPU accuracy settings in yuzu are fairly polarized and require more than common knowledge to know what the optimal settings for yuzu would be. This adds a curated option called 'Auto' that applies a few at the moment known-good unsafe optimizations to Dynarmic.
Specifically, sets `Unfuse FMA`, `Faster ASIMD instructions` (32 bits only), `Inaccurate NaN handling`, and `Disable address space checks`.
Also adds migration code, since the old CPU Accuracy setting won't translate well here since we're adding one at the beginning of the list. On first boot with the new setting, just use the default setting.
Now moves the CPU debugging tab and the Debug tab as sub tabs of General -> Debug.
> core,common,yuzu qt: Add CPU accuracy option 'Auto'

- src/tests/video_core/buffer_base.cpp
- src/video_core/buffer_cache/buffer_base.h
- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/dma_pusher.cpp
- src/video_core/fence_manager.h
- src/video_core/gpu.cpp
- src/video_core/rasterizer_interface.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.h
- src/video_core/texture_cache/types.h
This PR aims to fix downloads in the buffer cache and improve further the fence manager to not fully wait after a command buffer.
This PR fixes: Botw's particles (regressed on BCR), ZLA's BowWoW, Pokemon Sword's particles, Vertex explosions on UE4 games: Yoshi's Crafted World and Bravely Default 2 (needs  Hades).
> Buffer Cache: Fix High downloads / Fence manager: Improve fence checking.

- src/common/settings.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_graphics_advanced.cpp
- src/yuzu/configuration/configure_graphics_advanced.h
- src/yuzu/configuration/configure_graphics_advanced.ui
- src/yuzu/main.cpp
Some titles crash if the FPS limit is disabled when launching. This change ensures that titles launch with the limit in-place to avoid issues.
In order to simplify the change, the UI toggle was removed as it would have always been overridden at launch to be disabled.
The setting can still be toggled during gameplay with the hotkey, and indicated by the fps label in the status bar.
> settings: Disable FPS unlimit setting between title launches

- CMakeLists.txt
Allow the usage of git worktrees on yuzu.
> cmake: Only copy pre-commit hook if .git directory exists

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/engines/maxwell_dma.cpp
- src/video_core/engines/maxwell_dma.h
- src/video_core/gpu.cpp
- src/video_core/rasterizer_interface.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.h
This PR introduces DMA accelerations, this means doing a DMA Engine operation on the host GPU instead of the Guest GPU. Currently, the workflow is to Read memory and flush from host if needed, do a LLE DMA operation and then do Write that invalidates Host Caches. This is a very expensive operation on certain scenario.
This PR introduces DMA accelerations for Buffer Copies only. In the future more accelerations will be added for the BlockLinear-Pitch and back copies.
This PR fixes Shin Megami Tensei III Nocturne
> DMAEngine: Introduce Accelerate DMA.

- src/audio_core/command_generator.cpp
As the comment in the code says really, NaNs are causing crazy values in the end, essentially capping every sample in the mix to a maximum or minimum value, flipping the sign as well. I don't see much other way around this. When everything is s32 we can't propogate NaNs all the way to the sink, but even if we did we'd still have to replace them with silence there instead anyways. 
This stops XC2 blowing out the audio in certain places.
> audio_core: Replace NaN mix volume samples with silence

- src/core/file_sys/content_archive.cpp
> content_archive: Remove unnecessary include to <ranges>

- src/yuzu/main.cpp
Currently, whether or not the title is 32-bit or 64-bit was being appended as a suffix to the title, which is fine for left-to-right languages, but may not always fly so smoothly with some right-to-left languages.
We also weren't marking that portion of the string as translatable, which prevents translators from translating part of the title string.
> qt/main: Make title string more i18n-friendly

- src/core/hle/service/hid/controllers/npad.cpp
When checking if the device has rumble we send a vibration signal regardless if the setting is enabled. This completely disables any vibration
> npad: Disable vibration check if disabled

- src/core/hle/service/am/applets/applet_web_browser.cpp
This fixes the hint videos in New Super Mario Bros. U Deluxe
Fixes #6640
> applets/web: Resolve Nintendo CDN URLs

- src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
- src/video_core/command_classes/vic.cpp
This fixes NVDEC related issues in Mario Golf: Super Rush. The Submit Ioctl was meant to read directly from the Object's CPU memory address, rather than the mapped GPU address.
Fixing this unearthed issues in the VIC's computation of the output frame dimensions, which needed to be adjusted to avoid out of bound memory issues.
There are also various refactoring in nvhost_nvdec_common to maintain consistency.
> nvdec: Fix Submit Ioctl data source, vic frame dimension computations

- src/video_core/renderer_vulkan/vk_rasterizer.cpp
> vk_rasterizer: Only clear valid color attachments

- src/common/settings.cpp
- src/common/settings.h
- src/input_common/mouse/mouse_poller.cpp
- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/video_core/renderer_vulkan/vk_blit_screen.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_audio.cpp
- src/yuzu/configuration/configure_graphics.cpp
- src/yuzu/configuration/configure_input_advanced.ui
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
This PR replaces the usage of floating point settings with discrete integer values.
Qt is notorious for its sub-adequate support for floating point values in its configurations, and there are instances of comparing the value of settings with the defaults, which introduces precision issues when the settings are floating point values. The use of integers alleviates these issues.
> settings: Eliminate usage of float-point setting values

- src/yuzu/configuration/configure_audio.cpp
Fixes a regression introduced by #6579
> configure_audio: Fix volume clamping to 0

- src/common/settings.h
- src/input_common/mouse/mouse_poller.cpp
- src/yuzu/bootmanager.cpp
#6579 altered the default values for this setting. This PR corrects them and on top of that fixes an issue with multiple screens where the joystick was always pulled down
> input_common: Fix mouse panning behaivour

- CMakeLists.txt
As-is causes issues with building yuzu using MinGW GCC on Linux-based machines. Only set the variable when needed.
Also, we currently search for Qt on Linux regardless of the YUZU_USE_BUNDLED_QT setting. Disable the initial search if that variable is set to ON.
> cmake: Be more specific with Qt

- src/video_core/renderer_vulkan/vk_compute_pass.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
Fixes validation errors and synchronization issues exposed after updating to the 1.2.182 Vulkan SDK.
Tested on Skyward Sword, sadly no AMD-specific issues are fixed with these changes.
> vulkan: Fix misc validation and synchronization errors

- src/video_core/texture_cache/texture_cache.h
Images used as render targets were not being "prepared" when their dirty flags were not set, causing desynchronizations on the texture cache. Needs #6669 to avoid performance regressions on certain cooking titles.
This was originally included in #6585, but the change does not really belong there. This conflicts with #6585, it should be rebased after this is merged.
- Fixes black shadows on Age of Calamity.
> texture_cache: Always prepare image views on render targets

- src/video_core/renderer_vulkan/vk_texture_cache.cpp
fixes the crash after catching the first Pokemon. it was doing strange stuff with textures coming back outside. ignoring the invalid operation fixes the vulkan crash and doesn't cause any visual glitches
> Fix Pokemon Let's Go on Vulkan

- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
yuzu-cmd's default settings currently has many more-or-less incorrect settings. Some are deprecated settings from Citra (i.e. `use_hw_renderer`), are reported in the default ini but not read during runtime (i.e. `use_caches_gc`), are read during runtime but not reported in the default ini (i.e. `mouse_panning`), report incorrect defaults (i.e. `gpu_accuracy`), or altogether are not acknowledged in yuzu-cmd (i.e. `cpu_debug_mode`). `use_vsync` was listed twice in default_ini.h.
This makes an effort to synchronize yuzu's settings with yuzu-cmd. Some settings such as `fullscreen_mode` were not addressed here as they require implementation in yuzu-cmd (or need dropped from Common and moved to the Qt frontend's UISettings). I also likely did not notice all of the wrong defaults in …
> yuzu-cmd: Update settings

- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
- src/video_core/renderer_vulkan/vk_buffer_cache.h
Vulkan does not support null buffers on transform feedback bindings.
Emulate these using the same null buffer we were using for index
buffers.
Opening as a draft as I haven't tested it yet.
~~Fixes #6572.~~ Needs #6585 to fix #6572.
Removing draft state.
> vk_buffer_cache: Use emulated null buffers for transform feedback

- src/input_common/sdl/sdl_impl.cpp
- fix rumble on DualSense
- Dualsense return 78 value for using rumble, return 0 only if both frequency is 0, and after check function diferent value is normal
value return can be different 0, is not error is normal, error is only -1.
> input/sdl_impl: fix rumble support on DualSense.

- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
Simple fix, this fixes Koei Tecmo games on High Accuracy.
> VkBufferCache: Fix Quad Index array with 0 vertices

- src/common/uuid.h
We can now update this for C++20
Supersedes #4510
> uuid: Directly compare UUID instead of checking per element

- src/video_core/renderer_opengl/gl_texture_cache.h
There's an optimization bug on non-git mesa versions where not
specifying GL_CLIENT_STORAGE_BIT causes very slow reads on the CPU
side.
Add this bit for all vendors.
- Fixes performance issues on radeonsi on Skyward Sword (from ~8 FPS to 60 FPS)
> gl_texture_cache: Workaround slow PBO downloads on radeonsi

- src/yuzu/bootmanager.cpp
This ensures that Qt positions the render window at the correct position on initializing the respective render backends.
Fixes the black bars / offset render window when starting yuzu on a secondary monitor,
> bootmanager: Create a dummy render widget

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/engines/maxwell_dma.cpp
- src/video_core/engines/maxwell_dma.h
- src/video_core/memory_manager.cpp
- src/video_core/renderer_opengl/gl_buffer_cache.cpp
- src/video_core/renderer_opengl/gl_buffer_cache.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
- src/video_core/renderer_vulkan/vk_buffer_cache.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.h
This part adds BufferClears to accelerateDMA for both Vulkan and OGL.
This fixes the black textures on some characters caused by faulty normals (the compute shader messed up as the buffer wasn't clear on time).
> DMAEngine: Accelerate BufferClear [accelerateDMA Part 2]

- src/core/hle/service/am/applets/applet_controller.cpp
- src/core/hle/service/am/applets/applet_controller.h
Version 8 adds support for key remapping introduced in FW 11.0, we will not be implementing this for now.
> applet_controller: Add preliminary support for version 8

- src/input_common/sdl/sdl_impl.cpp
- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/configuration/configure_input_player.ui
Kills two birds with one stone:
- Analog triggers from SDL2 had a range from -1.0 to 1.0 we where setting the trigger to 0.5 which is around 75% of the button pressed. This PR fixes the SDL threshold value to 50%.
- Adds an UI option on right click to set any threshold value for each button
Closes #6644
> input_common: Make button threshold customizable

- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Reverts 48259de0c1a6a1aca77eec31cb8aca5ca2b680dd to the previous hierarchy and fixes the resolution issue with this fullscreen mode. yuzu-cmd will now read the fullscreen_mode setting and use it appropriately.
> yuzu_cmd: Make use of fullscreen_mode setting

- src/core/CMakeLists.txt
- src/core/hle/kernel/hle_ipc.cpp
- src/core/hle/kernel/k_auto_object.cpp
- src/core/hle/kernel/k_auto_object.h
- src/core/hle/kernel/k_process.cpp
- src/core/hle/kernel/k_server_session.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/svc.cpp
- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
- src/core/hle/service/kernel_helpers.cpp
- src/core/hle/service/kernel_helpers.h
- src/core/hle/service/nvdrv/nvdrv.cpp
- src/core/hle/service/nvdrv/nvdrv.h
- src/core/hle/service/service.cpp
- src/core/hle/service/service.h
- src/core/hle/service/sm/sm.cpp
- src/core/hle/service/sm/sm.h
Currently, the emulation session can create tons of kernel objects that are not tracked. This is particularly a problem with HLE services, which are created and torn down between emulation sessions (unlike what would happen on a real Switch), yet often create many kernel objects themselves for things like sessions, events, etc. which are not tracked. This can easily end up with ~1000+ dangling kernel objects after emulation is shutdown.
This change tries to address this by tracking the worst offenders here. These are:
* Adding global tracking of kernel objects, and logging which are dangling after emulation is shutdown.
* Ensuring handle tables are actually shutdown, freeing all of the object references held by the handle table.
* Ensuring events created by HLE services are properly …
> Improve management of kernel objects

- src/common/CMakeLists.txt
Common requires pthreads but does not refer to it when linking to other modules. Fix this by linking to Threads where necessary.
(It's probably not called pthreads for MSVC.)
> common: Publically link to pthreads

- src/yuzu/main.cpp
The screenshot directory path returned does not have a trailing directory separator character. This caused screenshots to be saved in the parent directory of the configured screenshot directory.
This fixes that behavior
> main: Fix screenshot filepath construction

- dist/qt_themes/default/style.qss
- dist/qt_themes/qdarkstyle/style.qss
- dist/qt_themes/qdarkstyle_midnight_blue/style.qss
- src/yuzu/main.cpp
- src/yuzu/main.h
This Pull Request seeks to eliminate the MULTICORE and ASYNC toggles. This toggles were added because on their release they weren't too stable and caused issues in some games. Now-a-days almost none ever uses this toggles anymore, so we are removing them as part of our options simplification.
We are also adding a new toggle: GPU Accuracy. Which allows to switch between Normal and High GPU accuracy. This is meant for users who can't trade the accuracy for the performance. Normal, is pretty safe but breaks effects in many games.
> Settings: Eliminate ASYNC & MULTICORE Toggles and add GPU Accuracy to  status bar

- src/common/settings.h
- src/core/hle/service/nvflinger/nvflinger.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_general.cpp
- src/yuzu/configuration/configure_general.ui
- src/yuzu/main.cpp
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
This setting allows users to manually adjust the FPS limit of titles using a multiple of the target FPS. 
This still requires the use of the hotkey during gameplay to take effect in order to avoid the stability issues that may occur if the FPS is unlocked during title boot.
Thanks to @Morph1984 for bringing to my attention that keeping a fully unlocked FPS can increase the CPU load significantly. 
Upon further investigation, it seems that manually setting a high FPS cap has the potential to outperform a fully unlocked FPS limit. 
Further testing is needed.
> config, nvflinger: Add FPS cap setting

- src/shader_recompiler/frontend/maxwell/control_flow.cpp
This previously duplicated the case of the PBK case above it.
> control_flow: Fix duplicate switch case in OpcodeToken

- src/shader_recompiler/object_pool.h
Prevents cases of undefined behavior from occurring.
> object_pool: Add missing return in Chunk move assignment operator

- src/yuzu/configuration/configure_graphics.cpp
* Change wording to explain that GLASM is actually short for Assembly Shaders
> Config-graphics: reword GLASM option

- src/shader_recompiler/frontend/ir/ir_emitter.h
- src/shader_recompiler/frontend/ir/value.h
[[nodiscard]] doesn't do anything on functions with a void return type and causes superfluous warnings.
> shader_recompiler: Remove unnecessary [[nodiscard]] instances

- src/video_core/renderer_vulkan/vk_compute_pass.cpp
Use an index buffer barrier instead of a vertex input read barrier.
> vk_compute_pass: Fix pipeline barrier for indexed quads

- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
Fixes bad API usages on Vulkan.
> vk_buffer_cache: Add transform feedback usage to null buffer

- src/common/settings.cpp
- src/common/settings.h
- src/core/core.cpp
- src/core/core.h
- src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
- src/core/perf_stats.cpp
- src/core/perf_stats.h
- src/core/telemetry_session.cpp
- src/video_core/renderer_base.cpp
- src/video_core/renderer_base.h
- src/video_core/renderer_opengl/renderer_opengl.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_general.cpp
- src/yuzu/configuration/configure_general.h
- src/yuzu/configuration/configure_general.ui
- src/yuzu/main.cpp
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
This setting is best referred to as a speed limit, as it involves the limits of all timing based aspects of the emulator, not only framerate.
This allows us to differentiate it from the FPS unlocker setting.
This change also uncovered unused renderer settings that are now being removed.
> general: Rename "Frame Limit" references to "Speed Limit"

- src/video_core/vulkan_common/vulkan_wrapper.cpp
We should be using the passed in object type instead.
> vulkan_wrapper: Fix SetObjectName() always indicating objects as images

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_vulkan/vk_compute_pass.cpp
Resolves several compiler warnings, and removes construction overhead of an unused small_vector, which is always nice.
> video_core: Remove some unused variables

- src/shader_recompiler/exception.h
Makes the constructors explicit to match their inheriting `Exception` constructor.
While we're in the area, we can narrow the included header from `<stdexcept>` to `<exception>`, since only `std::exception` is made use of, which avoids a little inclusion churn from indirectly including `<exception>`
> exception: Make constructors explicit

- src/video_core/engines/fermi_2d.h
- src/video_core/engines/maxwell_dma.h
Ensures all of the engines have consistent and deterministic default initialization of the rasterizer pointers.
> video_core/engine: Consistently initialize rasterizer pointers

- src/common/fs/fs_util.cpp
- src/common/fs/fs_util.h
Allows for direct conversion to std::string without having to convert std::u8string to std::string
> common: fs: fs_util: Add BufferToUTF8String

- src/video_core/texture_cache/render_targets.h
Everything else has a default constructor that does the straightforward thing of initializing most members to a default value, except for the `size`, which doesn't initialize any members.
We can explicitly initialize the size (and others, for consistency), to prevent potential uninitialized reads from occurring. Particularly given the largeish surface area that this struct is used in.
> render_target: Add missing initializer for size extent

- src/yuzu/applets/qt_web_browser.cpp
- src/yuzu/applets/qt_web_browser.h
- src/yuzu/applets/qt_web_browser_scripts.h
The QT web applet was having issues with navigation in Super Mario Odyssey's Action Guide.  Neither face button presses nor analog stick movement were being picked up.  By highlighting the first available clickable element and dealing with the button value mysteriously changing before the press can be fully acknowledged, the problem seems to have been resolved in SMO at least.  Could use testing in Windows and other games, though.
> applets/web: Addressing QT Navigation issues in Linux

- src/common/host_memory.cpp
FreeBSD >= 13.0 has [memfd_create(3)](https://man.freebsd.org/memfd_create/3), [implemented](https://reviews.freebsd.org/D21393) via `SHM_ANON`.
> host_memory: enable fastmem on FreeBSD

- src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
Fixes instances where fp16 types are not declared on SPIR-V but they are
used. This shouldn't happen on master, as it's been uncovered by an
additional optimization pass.
> shader: Mark ConvertF16F32 and ConvertF32F16 as fp16 instructions

- src/shader_recompiler/ir_opt/constant_propagation_pass.cpp
Simplifies the code a bit when possible. These instructions should be no-ops codegen wise. #6760 was needed for this.
> shader: Fold UnpackFloat2x16 and PackFloat2x16

- src/core/hle/service/am/applets/applet_software_keyboard.cpp
The buffer size here does not include the initial 8 bytes.
> applet_swkbd: Correct string buffer size calculation

- src/common/settings.h
- src/video_core/CMakeLists.txt
- src/video_core/renderer_vulkan/pipeline_statistics.cpp
- src/video_core/renderer_vulkan/pipeline_statistics.h
- src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
- src/video_core/renderer_vulkan/vk_compute_pipeline.h
- src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
- src/video_core/renderer_vulkan/vk_graphics_pipeline.h
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/renderer_vulkan/vk_pipeline_cache.h
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
- src/video_core/vulkan_common/vulkan_wrapper.cpp
- src/video_core/vulkan_common/vulkan_wrapper.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_debug.ui
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
Use VK_KHR_pipeline_executable_properties when enabled and available to
log statistics about the pipeline cache in a game.
The intention behind this PR is to be able to measure the impact of shader
changes in the compiled binary.
For example, this is on Turing GPUs when generating a pipeline cache
from Super Smash Bros. Ultimate:
```
Average pipeline statistics
==========================================
Code size:       6433.167
Register count:    32.939
```
Example from Intel proprietary (the number of registers is not reported):
```
Average pipeline statistics
==========================================
Code size:        388.719
Basic blocks:      11.141
```
Example from AMD proprietary:
```
Average pipeline statistics
==========================================
SGPRs:             43.217 …
```
> renderer_vulkan: Add setting to log pipeline statistics

- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.h
- src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2_gl.h
- src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2_vk.h
- src/yuzu_cmd/yuzu.cpp
It was just the one in emu_window_sdl2, but since _gl and _vk inherit from it, they all needed adjustments.
Leaves just the one `auto system&` in `main()`.
> emu_window: Remove global system instance

- src/core/hle/service/ns/language.cpp
- src/core/hle/service/set/set.cpp
- src/core/hle/service/set/set.h
- src/yuzu/configuration/configure_system.ui
- src/yuzu_cmd/default_ini.h
Adds Brazilian Portuguese to the list of languages, which was added in NX firmware 10.1.0.
> service: ns, set: Add PT_BR (Brazilian Portuguese)

- src/core/hle/api_version.h
Keeps us up to date with reporting the system version.
> hle: api_version: Update HOS version to 12.1.0

- src/core/hle/service/set/set.cpp
Fixes a regression introduced by #6752 which caused the language in Paper Mario The Origami King to display in Japanese instead of the selected system language.
> service: set: Correct copy amount in GetAvailableLanguageCodes

- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_ui.cpp
- src/yuzu/configuration/configure_ui.ui
- src/yuzu/game_list.cpp
- src/yuzu/game_list_p.h
- src/yuzu/uisettings.h
I don't know if this is intentional, but the icons for the folders in the game list tree view seem really big and are thus also a bit pixelated. In my opinion they would look a lot better if they were about the size of the text.
Before:
After:
> ui: make game list dir icons smaller

- src/video_core/textures/decoders.cpp
This makes UnswizzleTexture two times faster. It is the main bottleneck in video decoding.
| What | Before | After |
|-|-|-|
| Pokemon intro movie | 27 FPS | 30 FPS |
| Kirby intro movies | 29 FPS | 44 FPS |
| Kirby first world | 25 FPS | 30 FPS |
| Kirby first level | 22 FPS | 27 FPS |
| Link's Awakening intro movie | 12 FPS | 21 FPS |
| Animal crossing set-up | 25 FPS | 30 FPS |
| Animal crossing intro movie | 29 FPS | 30 FPS |
| Animal crossing in-game | 18 FPS | 23 FPS |
> decoders: Double the performance

- src/core/network/network.cpp
The ternary operator in core/network/network.cpp is written the wrong way round. The addrlen parameter for sendto should be non-zero if addr isn't a nullptr. Otherwise this call to sendto will generate an EINVAL error.
> network: fix ternary operator in Socket::SendTo

- src/yuzu/configuration/config.cpp
Currently the configuration re-reads current_user when booting a game with a custom configuration. This overwrites the global configuration's current_user value and causes yuzu to use the first profile always.
Read this setting inside the if (global) if statement, instead.
> config: Only read/write current_user on global config

- src/yuzu_cmd/config.cpp
Currently yuzu will read the mapping but does not connect a controller despite adding subsequent configurations for it. Read the `connected` setting for now as a boolean like the Qt frontend.
> config: Read connected setting for controllers

- src/common/hex_util.h
Although this isn't used, this is a potential bug as HexStringToArray will perform an out-of-bounds read.
> hex_util: Fix incorrect array size in AsArray

- src/core/hle/service/am/applets/applet_software_keyboard.cpp
Some games may interpret the read string as a null-terminated string instead of just reading the string up to buffer_size.
Fixes a regression caused by #6770
> applet_swkbd: Include the null terminator in the buffer size calculation

- src/common/uuid.cpp
- src/common/uuid.h
This allows for easily converting a hex string into a Common::UUID, which is backed by a 128 bit unsigned integer.
> common: uuid: Add hex string to UUID constructor

- src/common/assert.h
This fixes the warnings in Clion.
> assert: Avoid empty macros

- src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
- src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
- src/video_core/command_classes/codecs/vp9.cpp
- src/video_core/command_classes/codecs/vp9.h
- src/video_core/command_classes/codecs/vp9_types.h
The main issue with VP9 decoding was the need to guess which frames would be used as a reference as the video stream progressed. This change addresses that limitation.
By stubbing the UnmapBuffer ioctl, the reference frame addresses in the VP9 state remain consistent throughout the video stream, not being remapped to other addresses. This allows for increased confidence in which frames to use as a reference frame when composing the frame header that is sent to FFmpeg.
Stubbing the UnmapIoctl also avoid the flickering issues seen in Link's Awakening, and paves the way for an async nvdec implementation, whose main blocker was data being invalidated by nvdrv before its use by the gpu thread.
Here is a before and after comparison:
https://user-images.githubusercontent.com/52414509/127890988-a3 …
> nvdec: Fix VP9 reference frame refreshes

- dist/qt_themes/default/style.qss
- src/yuzu/configuration/configure_input_player_widget.cpp
- src/yuzu/configuration/configure_input_player_widget.h
Adds a green dot indicating the current position of the joystick since the animated controller doesn't reflect an easy way to see how far the joystick has moved. 
While testing on light theme I noticed the GPU accuracy colors had terrible contrast on my monitor. I changed them to a darker color.
> settings_ui: Add emulated joystick position dot to controller preview

- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.h
- src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp
Exposed `SDL_ShowCursor` to `EmuWindow` as `ShowCursor(bool)`. Both the derived classes (GL and VK) call this function when started with the fullscreen flag.
> yuzu-cmd: hide mouse cursor when started fullscreen

- src/video_core/command_classes/nvdec.cpp
Logs the string name of the codec. rather than the ambiguous numeric ID.
> nvdec: Better logging for unimplemented codecs

- src/common/uuid.h
Used when UUID is a key in an unordered_map. The hash is produced by XORing the high and low 64-bits of the UUID together.
> common: uuid: Add hash function for UUID

- src/input_common/main.cpp
- src/input_common/mouse/mouse_poller.cpp
- src/input_common/sdl/sdl_impl.cpp
- src/yuzu/configuration/configure_input_player.cpp
Some QoL changes:
- Hides the toggle button on all buttons that don't support this setting
- Avoids resetting the SDL controller every time the mappings are edited
- Adds a property to set a desired SDL joystick center
- The auto mapper will set the joystick center automatically
Closes #6555
Closes #6455
> input_common: Improve SDL joystick and hide toggle option

- src/video_core/vulkan_common/vulkan_memory_allocator.cpp
- src/video_core/vulkan_common/vulkan_memory_allocator.h
Closes #6764
The Vulkan spec says:
> bufferImageGranularity is the granularity, in bytes, at which buffer or linear image resources, and optimal image resources can be bound to adjacent offsets in the same VkDeviceMemory object without aliasing.
Yuzu did not respect this.
In the case of Mario Odyssey it caused image copies to write into the index buffer placed right after that image in host GPU memory. 
The value of this is 1024 on Nvidia GPUs. It does not appear to be a problem on AMD GPUs as the value for those is either 1 or 64 depending on the driver.
This probably impacts a bunch of other games on Nvidia GPUs.
> Respect Vulkan bufferImageGranularity

- src/yuzu_cmd/CMakeLists.txt
- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
This function was originally from https://github.com/yuzu-emu/yuzu/pull/5364/commits/55d8d30c7278485df3f137c6c9cee1674331e6e7
sadly on https://github.com/yuzu-emu/yuzu/commit/eae9f2e4404f6bdf8a192bc9c09e53cd87e4359d no correct attribution was given. (the entire commit)
I'de like to correct that. Sadly the commits are divergent and going all the way back to fix authorship is not easy. I've left a few comments though. Hope it's enough.
> yuzu-cmd/CMakeLists: Correct attribution for this function.

- src/video_core/command_classes/codecs/vp9.cpp
- src/video_core/command_classes/codecs/vp9_types.h
Due to the necessity to buffer 1 frame in advance to decode VP9 streams, the first frame was missing its frame data bitstream. 
This change addresses that by making a duplicate copy of the first frame data rather than moving it, silencing a runtime FFmpeg error due to the first frame missing the frame data, and being set to hidden despite being a key-frame.
> vp9: Ensure the first frame is complete

- src/yuzu/configuration/configure_general.ui
A minor change, but one that makes the general config UI look a bit tidier.
Before:
After:
> configure_general: Swap positions of speed limit and frame limit options

- src/core/memory.cpp
- src/core/memory.h
This deduplicates code, fixes all warnings and removes unused code.
This also fixes some logging bugs. I plan to use the new `WalkBlock` function later.
> memory: Clean up code

- src/yuzu/main.cpp
We don't really need to stop emulation unless the "Save as" dialog pop up.
> main: Avoid stopping emulation when taking a screenshot

- src/common/settings.h
Guards against scenarios where a user may manually input invalid settings to the config files then try to run yuzu.
This is achieved by adding two new settings classes, BasicRangedSetting and RangedSetting. They require a minimum and maximum value during initialization. During SetValue or assignment, it clamps the value within the range.
Need to note that RangedSetting is exhibiting diamond inheritance. For now it is handled well with C++ virtual base classes.
Also I don't like how system settings like language_index are handled. Maybe it's time to give all of these an enum class, or find where one is already defined in the source? Would like input on this.
> settings: Implement settings ranges

- src/video_core/command_classes/vic.cpp
Silences a sws_scale runtime warning about unaligned strides.
> vic: Specify sws_scale height stride.

- src/input_common/sdl/sdl_impl.cpp
SDL dies when a web applet opens on yuzu by unknown reasons if JOYSTICK_RAWINPUT is enabled. We don't need this feature.
> input_common: Disable sdl raw input mode

- src/common/threadsafe_queue.h
This fixes a lost wakeup in SPSCQueue. If the reader is in just the right position, the writer's notification will be lost and this will be a problem if the writer then does something to wait on the reader.
This was discovered to affect my upcoming stacktrace PR. I don't think any performance decrease will be noticeable because an uncontended mutex is smart enough to skip the syscall. This PR might also resolve some rare deadlocks but I don't know of any examples.
> threadsafe_queue: Fix deadlock

- src/core/core.cpp
- src/core/core.h
- src/core/cpu_manager.cpp
- src/core/cpu_manager.h
- src/core/hle/kernel/k_address_arbiter.cpp
- src/core/hle/kernel/k_auto_object.h
- src/core/hle/kernel/k_condition_variable.cpp
- src/core/hle/kernel/k_handle_table.cpp
- src/core/hle/kernel/k_handle_table.h
- src/core/hle/kernel/k_process.cpp
- src/core/hle/kernel/k_scheduler.cpp
- src/core/hle/kernel/k_scheduler.h
- src/core/hle/kernel/k_thread.cpp
- src/core/hle/kernel/k_thread.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/svc.cpp
- src/core/hle/service/nvflinger/buffer_queue.cpp
- src/core/hle/service/nvflinger/buffer_queue.h
- src/core/hle/service/nvflinger/nvflinger.cpp
- src/core/hle/service/nvflinger/nvflinger.h
- src/core/hle/service/vi/display/vi_display.cpp
- src/core/hle/service/vi/display/vi_display.h
The primary goal of this PR is to continue to improve the accuracy of our scheduler implementation. There are a few changes here:
* Implement more complete tracking of KThread dispatch count through KScopedDisableDispatch.
* Improved KScheduler EnableScheduling/DisableScheduling routines as a result.
* Overall simplification of a few KScheduler implementations.
* Use std::jthread for CPU threads.
* Improved emulation of host-only HLE threads as simulated "guest threads" on core 3.
* Improved management of some KEvents in services. This is not strictly related to this change, but I noticed some issues with these and this change, so I incorporated this improvement.
With overall better tracking of kernel objects, I have noticed several known shutdown crashes being fixed with these changes.
> kernel: Various improvements to scheduler

- src/core/hle/kernel/svc.cpp
Misplaced break made it only check for the first core. Probably fixes some multicore issues? Found by static analysis (thanks to PVS-Studio!).
~~While we're at it, won't calling `continue` in `if` directly below cause release and re-acquiring of scoped lock on `kernel`? Is this intended?~~ Edit: clarified to be intended on discord, no problem here.
> Fix check is thread current in GetThreadContext

- src/core/hle/service/vi/vi.cpp
It was trying to log value of `layer_id` which is specifically known not to exist, potentially leading to segfault. Log `display_id` instead.
> Fix crash in logging in CreateStrayLayer

- src/yuzu/configuration/configure_input_player_widget.cpp
Previously, floats were implicitly cast to integers. If this turns out to break things, just code them as integers instead.
As advised by @german77, opening as draft first to test.
> Replace QPoint with QPointF where applicable

- externals/CMakeLists.txt
- src/common/x64/xbyak_abi.h
- src/common/x64/xbyak_util.h
- src/video_core/macro/macro_jit_x64.h
We've never hit a dynarmic assert (and these are exercised quite well during fuzzing), so disable them at runtime.
> dynarmic: Update and enable DYNARMIC_IGNORE_ASSERTS

- src/video_core/textures/texture.h
`via_header_index` is already checked above, so it would never be true in this branch. It worked all along and it makes sense, so it's probably fine.
> video_core: eliminate constant ternary

- src/common/settings.h
The maximum is now 17 with the addition of Brazilian Portuguese
Fixes #6903
> settings: Amend language_index maximum setting range

- src/common/logging/backend.cpp
- src/common/logging/backend.h
- src/core/core.cpp
- src/core/core.h
- src/tests/common/param_package.cpp
- src/yuzu/debugger/console.cpp
- src/yuzu/main.cpp
- src/yuzu_cmd/yuzu.cpp
This simplifies the logging system.
This also fixes some lost messages on startup.
The simplification is simple. I removed unused functions and moved most things in the `.h` to the `.cpp`. I replaced the unnecessary linked list with its contents laid out as three member variables. Anything that went through the linked list now directly accesses the backends. Generic functions are replaced with those for each specific use case and there aren't many. This change increases coupling but we gain back more KISS and encapsulation.
With those changes it was easy to make it thread-safe. I just removed the mutex and turned a boolean atomic. I was planning to use this thread-safety in my next PR about stacktraces. It was actually async-signal-safety at first but I ended up using a different …
> logging: Simplify and make thread-safe

- src/yuzu/CMakeLists.txt
If we don't set an explicit source and target language for the base English translation, then Linguist will generate an incorrect number of `<numerusform>` tags (which Transifex doesn't like).
This should allow translators to properly specify pluralization translations on relevant strings that make use of it.
> CMakeLists: Ensure proper numerusform tags are generated for pluralized translations

- src/core/hle/kernel/kernel.cpp
I profiled the *Fire Emblem: Three Houses* loading screen and found that `GetHostThreadID` was taking up a fair chunk of CPU time. It seems like `thread_local` initialization and the optional parameter for ID allocation hurt the chances of inlining and eliminating some checks in each path.
Here's a profile of the old implementation:
And this implementation:
> kernel: Optimize GetHostThreadID

- src/common/logging/backend.cpp
- src/core/core.cpp
- src/core/core.h
- src/yuzu/main.cpp
After #6869, the log filter was being ignored on initialization due to the logging instance being initialized before the config instance, so the log filter was set to its default value.
This fixes that oversight, along with using descriptive exceptions instead of abort() calls.
> logging: Fix log filter during initialization

- src/video_core/command_classes/codecs/vp9.cpp
- src/video_core/command_classes/codecs/vp9_types.h
This change removes unused member variables that hung around from previous iterations of the VP9 decoder. Also tidies up the structs a bit.
Thanks to @v1993 for pointing out some oddities in this part of the code.
> vp9_types: Remove unusued VP9 info struct members

- src/core/hle/service/nifm/nifm.cpp
- src/core/network/network_interface.cpp
General code cleanup and populates the fields in GetCurrentNetworkProfile from the selected network interface.
> nifm/network_interface: Cleanup and populate fields in GetCurrentNetworkProfile

- src/common/logging/backend.cpp
Fix master failing to build due missing common/thread.h
> common/logging: Add missing include

- src/shader_recompiler/frontend/maxwell/structured_control_flow.cpp
- src/shader_recompiler/frontend/maxwell/structured_control_flow.h
- src/shader_recompiler/frontend/maxwell/translate_program.cpp
- src/shader_recompiler/host_translate_info.h
- src/video_core/renderer_opengl/gl_device.h
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
This change adds a new pass to reorder Demote instructions to the end of the program. This change came about after noticing that some drivers don't behave nicely when the following usage pattern was encountered:
```glsl
bool cond = x > y;
float attr_val = in_attr0.x;
if (cond) {
demote;
}
// proceed to use attr_val
```
Querying attribute values near a `demote` / `discard` seemed to cause some drivers to misread the input attributes. 
By deferring demotion to the end of the program, this issue was resolved.
This fixes the "wireframe" bug found in `Pokemon Sword and Shield`.
Before |  After
:-------------------------:|:-------------------------:
closes #6636
> structured_control_flow: Add DemoteCombinationPass

- src/yuzu/game_list.cpp
After Hades, both OpenGL and Vulkan use a pipeline cache instead of single stages of the graphics pipeline. Renamed the Remove and Open location menu entries to match.
> Rename all shader cache strings to pipeline cache

- src/video_core/engines/maxwell_3d.h
Close #6707,
Before：
After：
Finally, I think all the issue about DQ3 should have been solved, so is it possible to consider updating the compatibility list?
> Fix blend equation enum error

- src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
- src/core/hle/service/nvflinger/buffer_queue.h
- src/core/hle/service/nvflinger/nvflinger.cpp
The format member the IGBPBuffer may not always specify the correct desired format. Using the external format member ensures a valid format is provided when creating the framebuffer.
Fixes homebrew using the wrong framebuffer format.
> nvflinger: Use external surface format for framebuffer creation

- src/video_core/renderer_vulkan/renderer_vulkan.cpp
- src/video_core/renderer_vulkan/vk_scheduler.cpp
- src/video_core/renderer_vulkan/vk_scheduler.h
- src/video_core/renderer_vulkan/vk_swapchain.cpp
- src/video_core/renderer_vulkan/vk_swapchain.h
The present semaphore is being signalled by the call to acquire the
swapchain image. This semaphore is meant to be waited on when rendering
to the swapchain image. Currently it is waited on when presenting, which 
happens after rendering, but moving its usage to be waited on in the command
buffer submission allows for proper usage of this semaphore.
Fixes the device lost when launching titles on the Intel Linux Mesa driver.
Supersedes #6687
> renderer_vulkan: Wait on present semaphore at queue submit

- src/video_core/renderer_vulkan/vk_blit_screen.cpp
- src/video_core/renderer_vulkan/vk_swapchain.cpp
- src/video_core/renderer_vulkan/vk_swapchain.h
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
This change fixes an issue of broken sRGB (appearing very dark) when presenting sRGB swaphchains from a secondary GPU by preferring linear swapchain images.
Before |  After
:-------------------------:|:-------------------------:
> vk_swapchain: Prefer linear swapchain format when presenting sRGB images

- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
Silences validation errors for clearing the depth/stencil buffers of framebuffer attachments that were not specified to have depth/stencil usage.
> vk_rasterizer: Only clear depth/stencil buffers when specified in attachment aspect mask

- CMakeLists.txt
- src/common/settings.cpp
- src/common/settings.h
- src/core/telemetry_session.cpp
- src/video_core/CMakeLists.txt
- src/video_core/command_classes/codecs/codec.cpp
- src/video_core/command_classes/codecs/codec.h
- src/video_core/command_classes/codecs/h264.cpp
- src/video_core/video_core.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/config.h
- src/yuzu/configuration/configure_graphics.cpp
- src/yuzu/configuration/configure_graphics.h
- src/yuzu/configuration/configure_graphics.ui
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
As a follow-up to #6713, this change introduces the option to use FFmpeg's GPU video decoding for more GPUs and platforms, with graceful software decoding fallback if the driver/codec combination is not supported. 
The matrix for the implemented GPU decoders is as follows:
| GPU    | Windows       | Linux       |
|--------|---------------|-------------|
| NVIDIA | NVDEC/D3D11VA | NVDEC/VDPAU |
| AMD    | D3D11VA       | VA-API/VDPAU       |
| INTEL  | D3D11VA       | VA-API      |
Note that the GPU selected for decoding will not necessarily be the GPU used by yuzu for rendering. 
On Windows, NVDEC is preferred over D3D11VA for supported hardware, as I experienced lower performance using D3D11VA due to it defaulting to using my integrated Intel graphics.
On Linux, users reported having …
> nvdec: Add GPU video decoding for all capable drivers and platforms

- src/common/CMakeLists.txt
- src/common/common_funcs.h
- src/common/error.cpp
- src/common/error.h
- src/common/thread.cpp
- src/core/file_sys/kernel_executable.h
- src/core/hle/kernel/kernel.h
- src/core/network/network.cpp
- src/video_core/command_classes/codecs/codec.h
- src/video_core/memory_manager.cpp
- src/video_core/renderer_vulkan/vk_descriptor_pool.cpp
- src/video_core/shader_environment.cpp
- src/video_core/texture_cache/slot_vector.h
This avoids implicitly including `<string>` (and by extension `<string_view>`) in all files including common_funcs.h
While we're at it, we can also replace `<algorithm>` with `<iterator>` for `std::size` in common_funcs.h
> common: Move error handling functions out of common_funcs

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/hid/controllers/touchscreen.h
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
Both functions are needed for `Dr Kawashima’s Brain Training for Nintendo Switch` to boot
> hid/am: Stub SetTouchScreenConfiguration and implement GetNotificationStorageChannelEvent

- src/yuzu/main.cpp
Some titles set an exit lock through HLE, which prompts an exit confirmation when stopping emulation if the system is locked.
This change allows bypassing this confirmation if the setting to confirm exits has been disabled by the user.
> main: Apply confirm exit setting in exit locked scenarios

- src/core/hle/service/filesystem/filesystem.cpp
Originally we only created the parent directory, this caused issues for creating directories that also contained subdirectories, eg `/Folder1/Folder2`
This allows the ultimate mod manager homebrew to at least boot
> FS: Recursively create directories for CreateDirectory

- src/video_core/renderer_vulkan/vk_rasterizer.cpp
This function was incorrectly using the stencil_two_side_enable register when dynamically updating the StencilOp.
Fixes missing graphics in `WarioWare: Get It Together!` when using the Vulkan API
Before |  After
:-------------------------:|:-------------------------:
> vk_rasterizer: Fix dynamic StencilOp updating when two faces are enabled

- src/video_core/renderer_vulkan/vk_descriptor_pool.cpp
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
Fixes the random crashes on XC2 during boot with AMD.
> Vulkan/Descriptors: Increase sets per pool on AMD propietary driver.

- src/common/common_funcs.h
This adds bitwise shift operator overloads (<<, >>, <<=, >>=) in the macro DECLARE_ENUM_FLAG_OPERATORS(type)
> common_funcs: Add enum flag bitwise shift operator overloads

- src/video_core/vulkan_common/vulkan_device.cpp
Another broken hardware feature in AMD.
> Vulkan: Disable VK_EXT_SAMPLER_FILTER_MINMAX in GCN AMD

- src/video_core/vulkan_common/vulkan_device.cpp
This variable was going out of scope before its usage in the vulkan device creation, causing a crash on very specific drivers, notably recent proprietary AMD drivers.
> vulkan_device: Reorder Float16Int8 declaration

- src/video_core/vulkan_common/vulkan_debug_callback.cpp
This validation error is spammed on some titles, asserting that VkDescriptorSet 0x0[] was destroyed.
This is likely a validation layer bug when using VK_KHR_push_descriptor, which can avoid using traditional VkDescriptorSet (hence the VkDescriptorSet address is 0x0). It should be safe to ignore for now.
> vulkan_debug_callback: Ignore InvalidCommandBuffer-VkDescriptorSet errors

- src/common/settings.cpp
- src/common/settings.h
- src/input_common/sdl/sdl_impl.cpp
- src/input_common/udp/client.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_input_advanced.cpp
- src/yuzu/configuration/configure_input_advanced.ui
- src/yuzu/main.cpp
I feel like experimenting today.  
Add a setting to enable 8 player support with xinput controllers since this was disabled because input stops working if the web applet opens. This setting will effectively disable the web applets.
Replace SDL config strings with the equivalent.
Log important settings that might affect gameplay
> input_common: Add advanced setting for 8 player support

- src/common/settings.cpp
- src/common/settings.h
- src/core/telemetry_session.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_audio.cpp
- src/yuzu/configuration/configure_audio.h
- src/yuzu/configuration/configure_audio.ui
- src/yuzu_cmd/config.cpp
Removes the "Enable audio stretching" setting, as it is not utilized anymore. Also removes it from the setting read from the logs
> Remove audio stretching

- src/common/threadsafe_queue.h
- src/core/core.cpp
- src/video_core/gpu.cpp
- src/video_core/gpu.h
- src/video_core/gpu_thread.cpp
- src/video_core/gpu_thread.h
- src/video_core/renderer_vulkan/vk_scheduler.cpp
- src/video_core/renderer_vulkan/vk_scheduler.h
The use of `std::jthread` alleviates the need to coordinate and synchronize the joining of threads. The destructor of the jthread owning object can handle cleaning up by signaling a `stop_token`, which the worker threads loop on so long as they are alive. 
This change is expected to lessen the number of crashes when stopping emulation due to race conditions with worker threads upon shutdown, and simplifies the state tracking and coordination of running threads.
> videocore: Use std::jthread for worker threads

- src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
This fixes Shadows in UE4 games on Vulkan.
> Spir-V: Rescale the frag depth to 0,1 mode when -1,1 mode is used in Vulkan.

- src/video_core/renderer_vulkan/renderer_vulkan.cpp
- src/video_core/renderer_vulkan/vk_swapchain.cpp
- src/video_core/renderer_vulkan/vk_swapchain.h
Allows supported drivers that do not support `VK_PRESENT_MODE_MAILBOX_KHR` the ability to present at a framerate higher than the monitor's refresh rate when the FPS is unlocked.
Note that this may cause visible tearing as frames are always presented as they are complete without waiting for a vertical blank.
> vk_swapchain: Use immediate present mode when mailbox is unavailable and FPS is unlocked

- src/yuzu/configuration/configure_tas.ui
Text looked cramped on my pc (Ubuntu 21.04). Re-flowed text as well for nicer read.
Before | After
--------- | --------
> Tas configure ui nits

- src/common/uuid.h
- src/core/frontend/applets/profile_select.cpp
- src/core/hle/service/acc/acc.cpp
- src/core/hle/service/acc/profile_manager.cpp
- src/core/hle/service/am/applets/applet_profile_select.cpp
Given we have a function to invalidate, we should also have ones to query the validity. Also makes the code more straightforward to read.
Also fixes an uninitialized read case in the default profile selection applet that I came across while making this
> common/uuid: Add validity checking functions to interface

- src/core/hle/service/sockets/bsd.cpp
- Used by Diablo II: Resurrected
Note: While an implementation exists in #7082, this will cause the aforementioned game to softlock due to needing other BSD functions to be fully implemented.
> service: bsd: Stub Read

- src/core/core.cpp
- src/video_core/renderer_vulkan/vk_scheduler.h
jthread on some compilers is more picky when it comes to the order in which objects are destroyed.
> video_core: Fix jthread related hangs when stopping emulation

- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
Fixes "rainbow textures" on BOTW and Age of Calamity when using older AMD GPUs on the proprietary drivers.
BOTW was setting this bit on an image which was bound to a shader that was sampling the texture as a 2D array. 
The issue seems to be that when this bit is set on an image, that image will be sampled as a cube map rather than the sampler type. 
From my unit testing, this change doesn't seem to regress proper cube map usage, but further testing is needed.
> vk_texture_cache: Disable cube compatibility flag on non-mesa AMD GCN4 and earlier

- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_input_advanced.cpp
Follow-up to #6950. This option is a no-op on other OSes and only serves to spread confusion there.
> Hide XInput bypass on non-Windows OSes

- src/core/hle/service/audio/audin_u.cpp
- src/core/hle/service/audio/audin_u.h
This also moves IAudioIn's definition to the header.
Required for Splatoon 2 LAN play.
This is the first time I'm stubbing anything, so the possibility that I missed something or don't understand something is likely.
Fixes #7032
> audin_u: stub Start, RegisterBufferEvent, AppendAudioInBufferAuto

- src/common/host_memory.cpp
Since the `it` parameter comes from `placeholders`, using `placeholders.erase` invalidates the iterator. Simply reordering this is the simplest way to fix it. As far as I can see `UntrackPlaceholder` is only used in one place.
> Fixed invalid iterator usage

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/engines/maxwell_dma.cpp
- src/video_core/engines/maxwell_dma.h
- src/video_core/renderer_opengl/gl_buffer_cache.cpp
This change brings some minor refactoring for code clarity, behavior is unchanged save for a few small fixes:
The size calculation for the buffer clear in OpenGL (the size is expected to be in bytes), 
and a minor fix to loop through DMA copy intervals by reference.
> buffer_cache, maxwell_dma: Minor refactoring and code fixes

- src/yuzu/applets/qt_web_browser.cpp
Store QtWebEngine data in `yuzu_directory/qtwebengine`.
Previously, an unrelated directory was used for this. Keep everything together for consistency.
> applets: Use subdirectory of main data directory for QtWebEngine storage

- src/core/core.cpp
- src/core/core.h
- src/core/hle/service/am/am.cpp
- src/yuzu/bootmanager.cpp
- src/yuzu/bootmanager.h
- src/yuzu/main.cpp
- src/yuzu/main.h
This allows applications, typically homebrew, to make use of this service call to exit the currently running application.
Functionally, this is equivalent to the "Stop" button under Emulation -> Stop
> core: Properly shutdown and exit the running application when ISelfController::Exit is called

- src/input_common/sdl/sdl_impl.cpp
Linux have another name for joycons. We simply add a check for the other string
> input_common: Add alternative string for joycons

- src/yuzu/main.cpp
Some titles, such as homebrew, do not have any version string. Because yuzu hard codes the title bar string assuming a version string is preset, booting homebrew causes yuzu to add an extra separator with no content between.
This uses a lambda expression to prevent that from happening.
Before:
After:
> main: Don't add an extra separator when the title version is absent

- src/core/CMakeLists.txt
- src/core/hle/kernel/k_process.cpp
- src/core/hle/kernel/k_process.h
- src/core/hle/kernel/k_shared_memory_info.h
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/svc.cpp
1. Fix KScopedAutoObject leak when SendSyncRequest
**Because the KScopedSchedulerLock triggers a fiber switch. when a suspend been triggered, the current KScopedAutoObject reference count may not be released**
2. Fix SharedMemory leak
Known Issue:
1. svc WaitSynchronization objects may not be released correctly
**KSynchronizationObject::Wait will trigger a fiber switch, causing the object not to be released**
2. svc StartThread thread leak
**It is possible that the shutdown was performed without calling ExitThread**
3. HLE Service's event leak
**The event object is treated as a member parameter, when the class is released, the event object will be destructured and needs to be changed to event pointer object**
I tried to solve the three problems above, but I found that sometimes it would …
> core: Fix memory leak

- src/core/memory.cpp
I encountered this while debugging my reimplementation of the gdb stub. gdb sends `mfffffffc,4#{checksum}` and this is where it occurs. I'm not sure if this is a hotspot or not but if it is and the check causes problems an alternative would be to make `page_table.pointers` large enough for every possible page value. (I don't know how large this would be)
I have not yet had time to test this change so someone may want to manually check it.
> prevent access violation from iob in Memory::IsValidVirtualAddress

- src/core/hle/service/acc/async_context.cpp
- src/core/hle/service/acc/async_context.h
- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/am/applets/applets.cpp
- src/core/hle/service/am/applets/applets.h
- src/core/hle/service/aoc/aoc_u.cpp
- src/core/hle/service/aoc/aoc_u.h
- src/core/hle/service/audio/audin_u.cpp
- src/core/hle/service/audio/audin_u.h
- src/core/hle/service/audio/audout_u.cpp
- src/core/hle/service/audio/audren_u.cpp
- src/core/hle/service/audio/audren_u.h
- src/core/hle/service/bcat/backend/backend.cpp
- src/core/hle/service/bcat/backend/backend.h
- src/core/hle/service/bcat/bcat_module.cpp
- src/core/hle/service/btdrv/btdrv.cpp
- src/core/hle/service/btm/btm.cpp
- src/core/hle/service/friend/friend.cpp
- src/core/hle/service/nfp/nfp.cpp
- src/core/hle/service/nfp/nfp.h
- src/core/hle/service/nifm/nifm.cpp
- src/core/hle/service/nim/nim.cpp
- src/core/hle/service/ptm/psm.cpp
- src/core/hle/service/time/standard_user_system_clock_core.cpp
- src/core/hle/service/time/standard_user_system_clock_core.h
The service context helps to manage all created events and allows us to close them upon destruction.
> service: Replace all service event creation with ServiceContext::CreateEvent

- src/audio_core/command_generator.cpp
- src/audio_core/mix_context.cpp
- src/audio_core/voice_context.cpp
- src/common/CMakeLists.txt
- src/common/logging/backend.cpp
- src/common/logging/log.h
- src/common/logging/log_entry.h
- src/common/logging/text_formatter.cpp
- src/common/logging/types.h
- src/common/param_package.cpp
- src/core/hle/kernel/k_auto_object_container.cpp
- src/core/hle/service/lbl/lbl.cpp
- src/core/hle/service/time/system_clock_context_update_callback.h
- src/core/hle/service/time/system_clock_core.h
- src/video_core/engines/maxwell_3d.h
This PR aims to reduce the compile overhead of including `log.h` by removing the dependency on `chrono`
from `logging/types.h`. It also reduces the scope of the included `fmt` header in log.h, in an effort to 
alleviate the compile overhead further.
> common/logging: Reduce dependent header include overhead

- src/yuzu/configuration/configure_tas.cpp
- src/yuzu/configuration/configure_tas.ui
Before (EA 2083)| After
------------ | -------------
Notice where "OK" and "Cancel" are located after stretching the window down
Instead of it being in the middle of the blank space as can be seen on the left picture, it will be at the bottom of the window at all sizes
Also removes the useless "?" button on the top right
> (Minor Change) Hint (?) Button Removal and Spacing Change to the TAS Window

- src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
- src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
- src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
- src/core/hle/service/nvflinger/nvflinger.cpp
- src/core/hle/service/nvflinger/nvflinger.h
- src/video_core/cdma_pusher.cpp
- src/video_core/cdma_pusher.h
- src/video_core/engines/maxwell_3d.h
- src/video_core/framebuffer_config.h
- src/video_core/gpu.cpp
- src/video_core/gpu.h
- src/video_core/gpu_thread.h
- src/video_core/query_cache.h
- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_opengl/gl_texture_cache.h
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
- src/video_core/shader_environment.cpp
- src/video_core/shader_environment.h
- src/video_core/texture_cache/image_view_info.cpp
- src/video_core/texture_cache/texture_cache.h
- src/video_core/texture_cache/texture_cache_base.h
This PR mainly aims to reduce the amount of dependencies in `video_core/gpu.h`, as it is a very widely included header file, in an effort to reduce compiling overhead. The definition and implementation of `Tegra::GPU` has moved to the cpp file, with the header now serving only as an interface to its public methods. As a result, many unusued headers were trimmed.
Through this migration, two other changes were needed: the `GPU::LockSync` method's single usage was refactored, and the VSync thread was converted to a `std::jthread` to avoid a deadlock on stopping emulation. Further testing is needed to ensure this refactoring did not introduce other anomalies.
> gpu: Migrate implementation to the cpp file

- src/core/hle/result.h
This removes the const qualification for types when MakeResult(arg) is used in a const member function, allowing for automatic deduction and removing the need to manually specify the non-const type as the template argument.
> hle/result: Remove cv-qualifiers from Arg in MakeResult

- src/core/file_sys/control_metadata.cpp
- src/core/file_sys/control_metadata.h
- src/core/hle/service/ns/language.cpp
- src/core/hle/service/ns/language.h
It seems that Nintendo finally filled that last empty spot in ApplicationLanguage for a total of 16 supported languages.
Should fix pt-BR language support in Mario Party Superstars
> file_sys/ns: Add Brazilian Portuguese to the list of ApplicationLanguage

- src/yuzu/CMakeLists.txt
- src/yuzu/main.cpp
This disables the screen saver when yuzu is running a game via SDL2's screen saver functions. Adds an option to allow or disable the screen saver in General options.
I went and finished this, got ready to make the PR, and noticed #6421 already exists. I thought I propose this, anyway, since (a) this implements it in 1/3 of the code, (b) doesn't add any new dependencies, and (c) SDL2's screen saver inhibition is platform-agnostic --- we implement it here for Linux, and it'll work on Android and macOS and anything else that SDL2's screen saver functions are implemented for, too.
Closes #6262
> yuzu_cmd, yuzu qt: Use SDL to disable the screen saver

- src/yuzu/configuration/configure_profile_manager.cpp
Some games seem to be crashing if the profile picture is too big. To avoid this issue we simply resize the image to a smaller size
> profile_manager: Resize any image bigger than 256p

- src/core/core.cpp
- src/core/hle/kernel/k_handle_table.cpp
- src/core/hle/kernel/k_process.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/svc.cpp
1. Fix svc WaitSynchronization objects may not be released correctly.
2. Fix svc StartThread thread leak.
3. Fix dangling kernel objects when exiting.
4. Revert #7009
> Fix memory leak v2

- src/common/CMakeLists.txt
- src/common/expected.h
- src/core/file_sys/romfs_factory.cpp
- src/core/file_sys/savedata_factory.cpp
- src/core/file_sys/sdmc_factory.cpp
- src/core/hle/kernel/k_page_table.cpp
- src/core/hle/result.h
- src/core/hle/service/filesystem/filesystem.cpp
- src/core/hle/service/glue/glue_manager.cpp
- src/core/hle/service/ldr/ldr.cpp
- src/core/hle/service/mii/mii_manager.cpp
- src/core/hle/service/ns/ns.cpp
- src/core/hle/service/sm/sm.cpp
- src/core/hle/service/spl/spl_module.cpp
- src/core/hle/service/vi/vi.cpp
This implementation is based on and is a subset of the proposed implementation of `std::expected`
https://github.com/TartanLlama/expected/blob/master/include/tl/expected.hpp
This is then used to reimplement `ResultVal` as it provides the same functionality, and can be replaced with `std::expected` down the line when it is standardized in the C++ STL.
Special thanks to @lioncash for suggesting this implementation idea.
> common, result: Implement a subset of std::expected and use it in ResultVal

- src/video_core/renderer_opengl/gl_rasterizer.cpp
This removes unused includes, especially the core includes which were causing this file to be recompiled every time files included by those headers are modified.
> gl_rasterizer: Remove unused includes

- src/shader_recompiler/backend/glasm/emit_glasm_not_implemented.cpp
- src/shader_recompiler/backend/glsl/emit_glsl_special.cpp
- src/shader_recompiler/frontend/ir/basic_block.h
- src/shader_recompiler/frontend/ir/microinstruction.cpp
- src/shader_recompiler/frontend/ir/value.h
- src/shader_recompiler/frontend/maxwell/translate_program.cpp
- src/shader_recompiler/ir_opt/ssa_rewrite_pass.cpp
This fixes the post processing in Mario Party SuperStars.
The idea of this is so the tracking algorithm, gets the nearest instances first rather than the oldest instances of a value.
> ShaderCache: Order Phi Arguments from farthest away to nearest.

- src/core/hle/service/acc/acc.cpp
- src/core/hle/service/acc/acc.h
- src/core/hle/service/acc/acc_u0.cpp
- Used by Animal Crossing: New Horizons v2.0.0
Since the name is currently unknown, '160' is used as a placeholder.
> service: acc: Stub acc:u0 '160'

- src/core/hle/service/aoc/aoc_u.cpp
- src/core/hle/service/aoc/aoc_u.h
Stubs NotifyMountAddOnContent, NotifyUnmountAddOnContent and CheckAddOnContentMountStatus
Used by Animal Crossing: New Horizons v2.0.0 DLC
> service: aoc: Stub more 13.x functions used by Animal Crossing

- src/core/core.cpp
Avoids the gpu_core using perf_stats after it's been freed.
> core: Reorder perf_stats destruction order on Shutdown

- src/core/core.cpp
- src/core/core.h
- src/core/file_sys/savedata_factory.cpp
- src/core/hle/kernel/k_process.h
- src/core/hle/kernel/svc.cpp
- src/core/hle/service/acc/acc.cpp
- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/applets/applet_error.cpp
- src/core/hle/service/am/applets/applet_general_backend.cpp
- src/core/hle/service/am/applets/applet_web_browser.cpp
- src/core/hle/service/aoc/aoc_u.cpp
- src/core/hle/service/bcat/bcat_module.cpp
- src/core/hle/service/fatal/fatal.cpp
- src/core/hle/service/filesystem/filesystem.cpp
- src/core/hle/service/filesystem/fsp_srv.cpp
- src/core/hle/service/glue/arp.cpp
- src/core/hle/service/ldr/ldr.cpp
- src/core/hle/service/pctl/pctl_module.cpp
- src/core/hle/service/pm/pm.cpp
- src/core/hle/service/prepo/prepo.cpp
- src/core/memory/cheat_engine.cpp
- src/core/reporter.cpp
- src/yuzu/bootmanager.cpp
- src/yuzu/main.cpp
- src/yuzu_cmd/yuzu.cpp
This allows us to avoid including KProcess' header file in files that only need to get the current process' program id.
> general: Get the current process program id directly from the system

- src/core/frontend/applets/software_keyboard.cpp
- src/core/frontend/applets/software_keyboard.h
- src/core/hle/service/am/applets/applet_software_keyboard.cpp
- src/core/hle/service/am/applets/applet_software_keyboard.h
- src/yuzu/applets/qt_software_keyboard.cpp
- src/yuzu/applets/qt_software_keyboard.h
- src/yuzu/main.cpp
- src/yuzu/main.h
Confirm means that the text has already been checked by the application to be correct, but is asking the user for confirmation.
This also fixes the corrupted text in the confirmation dialog, which is caused by using the incorrect encoding.
Fixes #6712 
Fixes the software keyboard in Famicom Detective Club: The Missing Heir
> applets/swkbd: Skip text checking if the text has been confirmed

- src/core/file_sys/program_metadata.cpp
When running homebrew, `svcCreateThread` will always fail because no cores or thread priorities are allowed in the default metadata. I added the capability for the application to use cores 0\~3 and priorities 1\~63.
> program_metadata: Add default ThreadInfo capability

- src/common/logging/backend.cpp
- src/common/logging/backend.h
- src/common/logging/log_entry.h
- src/yuzu/main.cpp
This addresses a few problems I have had with the logger.
Moving the backend thread out of the constructor gives the queue some time to build some entrys before starting to PopWait them off. I would occasionally crash on booting yuzu due to collision in the queue.
Moving to a stop_source ensures that there is a clean shutdown. I would have to manually kill my gdb session because the logger would be stuck waiting on an entry to pop.
> Logging: Impl refactor

- CMakeLists.txt
- src/video_core/CMakeLists.txt
- src/video_core/command_classes/codecs/codec.cpp
- src/video_core/command_classes/codecs/codec.h
- src/video_core/command_classes/codecs/h264.cpp
- src/video_core/command_classes/codecs/h264.h
- src/video_core/command_classes/codecs/vp8.cpp
- src/video_core/command_classes/codecs/vp8.h
- src/video_core/command_classes/codecs/vp9.cpp
- src/video_core/command_classes/codecs/vp9.h
- src/video_core/command_classes/nvdec.cpp
- src/video_core/command_classes/nvdec_common.h
This change implements support for decoding VP8 video streams.
There are currently only a handful of titles that use VP8 video streams. I'm aware of `Ty the Tasmanian Tiger` and `Diablo II: Resurrected`.
The implementation is based on Nvidia's OpenGPU docs and the official VP8 specification, which can be found [here](https://datatracker.ietf.org/doc/rfc6386/).
Closes #7208
> codecs: Implement VP8 video decoding support

- CMakeLists.txt
Keeps the testing libraries up to date.
Also fixes compilation related to changes with glibc
> CMakeLists: Update catch to 2.13.7

- src/yuzu/hotkeys.cpp
If you hold a hotkey it will start to spam. This is totally undesired
> hotkeys: Don't allow hotkeys to spam
