src/yuzu/main.cpp

Reported on discord by Levlight. Don't try to exit fullscreen if it's already off.

Prevent window flickering when holding Esc

---

src/video_core/renderer_opengl/gl_texture_cache.cpp
src/video_core/renderer_opengl/gl_texture_cache.h
src/video_core/renderer_vulkan/vk_texture_cache.h
src/video_core/texture_cache/texture_cache.h
src/video_core/texture_cache/texture_cache_base.h

Texture copies with "incompatible" formats (i.e. Color <-> Depth) were left unimplemented on OpenGL after TCR. 
This PR aims to implement format conversions by repurposing the existing method used for BGR <-> RGB texture format conversion. 
This is expected to fix a number of issues. For example:
https://user-images.githubusercontent.com/52414509/142131633-fa8aa4e6-5a58-4304-824e-4dc8e1b54aa9.mp4
https://user-images.githubusercontent.com/52414509/142131645-f295dc55-d1a2-4d3b-9f16-19939d19b902.mp4
https://user-images.githubusercontent.com/52414509/142131213-cd13a780-e962-4f9d-9ce8-0abb3139ae18.mp4
https://user-images.githubusercontent.com/52414509/142131230-7eea0eae-d160-4556-99ba-77967da761e7.mp4
closes #6845 closes #4220

gl_texture_cache: Implement pixel format conversions for copies

---

src/yuzu/main.cpp

Original text was not direct enough, hopefully this will reduce support requests regarding dumping keys.
Fight me.

Replace keys error pop up

---

CMakeLists.txt

Move the cmake submodule checkout command to a new line
Presently, if you forget to initialize the git submodules before
running cmake, there'll be a helpful message that reminds you to do so.
However, on narrow terminals (e.g. 80 wide) there's a word wrap that
includes a new line in the middle of the git command, precluding easy
copy-paste.  This moves the entire git command to its own line to avoid
such tragedies.
Before:
```
CMake Error at CMakeLists.txt:59 (message):
Git submodule externals/inih/inih not found.  Please run: git submodule
update --init --recursive
```
After:
```
CMake Error at CMakeLists.txt:59 (message):
Git submodule externals/inih/inih not found.  Please run:
git submodule update --init --recursive
```

Move the cmake submodule checkout command to a new line

---

src/video_core/renderer_opengl/gl_texture_cache.cpp
src/video_core/renderer_opengl/gl_texture_cache.h

Currently, there is a restriction on the level when create an image, but there is no such restriction when update and download, opengl report an error when calling the corresponding method.

Fix image update/download error when width too small

---

src/common/bit_util.h
src/video_core/host_shaders/CMakeLists.txt
src/video_core/host_shaders/convert_abgr8_to_d24s8.frag
src/video_core/host_shaders/convert_b10g11r11_to_d24s8.frag
src/video_core/host_shaders/convert_d24s8_to_abgr8.frag
src/video_core/host_shaders/convert_d24s8_to_b10g11r11.frag
src/video_core/host_shaders/convert_d24s8_to_r16g16.frag
src/video_core/host_shaders/convert_r16g16_to_d24s8.frag
src/video_core/renderer_opengl/gl_texture_cache.cpp
src/video_core/renderer_opengl/gl_texture_cache.h
src/video_core/renderer_vulkan/blit_image.cpp
src/video_core/renderer_vulkan/blit_image.h
src/video_core/renderer_vulkan/vk_texture_cache.cpp
src/video_core/renderer_vulkan/vk_texture_cache.h
src/video_core/texture_cache/texture_cache.h
src/video_core/texture_cache/texture_cache_base.h
src/video_core/texture_cache/types.h
src/video_core/texture_cache/util.cpp

This fixes many issues in Pokemon Brilliant Diamond. Including, Vulkan & OGL crashes.
It's not in a good state to merge though.

Fix ART Blit detection regression and add D24S8 <-> RGBA8 conv to Vulkan

---

src/core/hle/kernel/kernel.cpp

`thread_local` created a static variable which is destroyed on application exit (after `KernelCore` is destroyed), which caused a crash on exit while the emulation was running, because `KThread`s have references to `KernelCore`. This solution causes the dummy `KThread`s to be destroyed earlier, when `KernelCore` gets destroyed.

Fix crash on exit due to static scoped dummy threads

---

src/core/frontend/framebuffer_layout.cpp
src/core/frontend/framebuffer_layout.h
src/video_core/video_core.cpp
src/video_core/video_core.h
src/yuzu/bootmanager.cpp

This was regressed by ART.
Prior to ART, the screenshots were saved at the title's framebuffer resolution. 
A misunderstanding of the existing logic led to screenshot dimensions becoming dependent on the host render window size with changes made in ART.
This PR changes the behavior to match how it was prior to ART at 1x, with screenshots now always being the title's framebuffer dimensions scaled by the resolution scaling factor.
closes #7388

Fix screenshot dimensions when at 1x scale

---

src/core/arm/dynarmic/arm_dynarmic_64.cpp

Used by Skyline modding framework, see #7392 for tracking issue on skyline support.

Add InstructionCacheOperationRaised handler for 'ic ivau' instruction

---

src/yuzu/bootmanager.cpp
src/yuzu/bootmanager.h
src/yuzu/main.cpp
src/yuzu/main.h
src/yuzu/main.ui

This PR improves the discoverability and accessibility of TAS controls by adding them to a TAS submenu under Tools. They were previously only accessible through hotkey configuration.
- The alternatives to the changes in `GRenderWindow` are either to turn `Tas` into a `QObject`, or have `Tas` track a callback function.
- I think there is a bug where you can play and record a TAS at the same time, this PR is not addressing that.
- The hotkeys in the screenshots above are non-default.

Added TAS controls to the menu under Tools

---

src/common/settings.cpp
src/common/settings.h
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_general.cpp
src/yuzu/configuration/configure_general.ui

With my 144Hz monitor I'll be setting global to 3x for 60 fps games and custom configs to 5x for 30 fps games.

configure_general: Allow framerate cap to be used in custom game configs

---

src/yuzu/main.cpp
src/yuzu/main.h
src/yuzu/main.ui

- Removed "Start", since it was always disabled unless it was "Continue" which has now been moved to "Pause".
- Fixes #6043
- Fixes #7429 
- Fixes #7257 
- Fixed #5144 
----
Also question: Does anyone have issue with renaming "Continue" to either "Unpause" or "Resume"?

Refactor menu states and shortcuts in GMainWindow.

---

src/yuzu/main.cpp
src/yuzu/uisettings.cpp

This reflects the current behavior: Light = System default. If your
system is set to dark theme, then Light = Dark, which is a bit confusing
for the end user.
In this PR, I propose to change "Light" with "Default". This way, the
user has "Default" and "Default Colorful", which will apply the system
theme. Now that the Flatpak respects the system theme, I think this
makes much more sense.
I also simplified the theme update. Before the code was branching
between the default theme and the others, but I think we can have
something simpler by forcing the default theme if no theme is defined in
the settings, or if the selected theme doesn't exist. And if there's an
error, tell the theme name in the error message.

Replace "Light" theme by "Default"

---

CMakeLists.txt

Ensures that we're using the latest version of fmt.

CMakeLists: Update fmt to 8.0.1

---

src/common/settings.h
src/common/settings_input.h
src/core/hid/emulated_controller.cpp
src/core/hle/service/hid/controllers/npad.cpp
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_debug.cpp
src/yuzu/configuration/configure_debug.ui
src/yuzu/configuration/configure_input_player.cpp

I often have to hack through my settings to test a new controller. This setting allows to select any Nintendo controller regardless if they work properly or not.

settings: Add debug setting to enable all controllers

---

src/core/CMakeLists.txt
src/core/hle/service/hid/hid.cpp
src/core/hle/service/ns/ns.cpp
src/core/hle/service/ns/ns.h
src/core/hle/service/ns/pdm_qry.cpp
src/core/hle/service/ns/pdm_qry.h

Adds pdm_qry, IReadOnlyApplicationControlDataInterface
Stubs GetUniquePadsFromNpad, QueryPlayStatisticsByApplicationIdAndUserAccountId
Checkpoint needs more implementations to work properly. This PR just reduces the amount of missing services

Core: Stub services and functions needed for checkpoint

---

src/yuzu/applets/qt_controller.cpp

Turns out when the applet is not shown the controllers stay in configuration mode. This PR ensures the controllers are enabled again

qt_controller: Fix input when the controller applet is ignored

---

src/input_common/drivers/sdl_driver.cpp

Another error from kraken. This one adds the correct name to the correct thread....

input_common: Fix erron with thread name

---

src/yuzu/CMakeLists.txt
src/yuzu/applets/qt_controller.h
src/yuzu/applets/qt_profile_select.cpp
src/yuzu/applets/qt_profile_select.h
src/yuzu/game_list.cpp
src/yuzu/game_list.h
src/yuzu/main.cpp
src/yuzu/util/controller_navigation.cpp
src/yuzu/util/controller_navigation.h

This is one of the most requested features. Adds the ability to navigate through the game list, profile selector and controller applet.
The controller applet still needs some work since it's a bit more complex.

yuzu: Implement basic controller UI navigation

---

src/common/x64/native_clock.cpp
src/core/hle/service/audio/hwopus.cpp
src/core/perf_stats.h
src/video_core/shader_notify.cpp
src/video_core/shader_notify.h
src/yuzu/loading_screen.cpp
src/yuzu/loading_screen.h

On some OSes, high_resolution_clock is an alias to system_clock and is not monotonic in nature. Replace this with steady_clock.

general: Replace high_resolution_clock with steady_clock

---

src/video_core/CMakeLists.txt
src/video_core/command_classes/codecs/codec.cpp

This pull request will hopefully solve the FFmpeg hardware decoder selection issue.
The new logic will ask FFmpeg what contexts it supports on the current platform and current hardware, then we will check if the following hardware decoders are supported one-by-one in this order:
- CUDA
- [WIN only] D3D11VA
- [WIN only] DXVA2 (D3D9 on Win7-, Media Foundation on Win7+)
- [Linux only] VDPAU
- VULKAN
Some broader user-testing is required before merging.

video_core/codecs: more robust ffmpeg hwdecoder selection logic

---

src/core/hid/emulated_controller.cpp
src/core/hid/emulated_controller.h
src/core/hid/hid_core.cpp
src/core/hid/hid_core.h
src/core/hid/hid_types.h
src/core/hle/service/hid/controllers/npad.cpp
src/yuzu/configuration/configure_input_player.cpp
src/yuzu/main.cpp

SwapNpadAssignment generated a SVC break when it tried to swap a controller that is invalid.
Fixes #7500

core/hid: Ensure only valid npad are connected

---

src/audio_core/delay_line.cpp
src/audio_core/delay_line.h
src/common/host_memory.cpp
src/core/hle/service/nvdrv/nvdata.h
src/shader_recompiler/environment.h

A few source files didn't have the yuzu copyright notice.

general: Add missing copyright notices

---

src/core/loader/deconstructed_rom_directory.cpp

Skyline uses subsdk9 in order to prevent any possible clashes with games which overwrite lower subsdks. See skyline tracking issue: #7392.

Add support for subsdk8 and subsdk9

---

CMakeLists.txt

SDL 2.0.18 exposes HIDAPI driver needed for a custom driver for joycons. On top of that it seems like it also adds support to new controllers

input_common: Update SDL to 2.0.18

---

src/CMakeLists.txt

This increases the memory heap size for constructing precompiled headers to 2x the default.

CMakeLists: Specify /Zm200 when compiling in MSVC

---

src/yuzu/main.cpp

Fixes a crash where app focus logic relied on UI states rather than emulation states.
#7502

Fixed #7502

---

src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
src/core/hle/service/nvdrv/devices/nvhost_nvdec.h
src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
src/core/hle/service/nvdrv/devices/nvhost_vic.h
src/video_core/gpu.cpp
src/video_core/gpu.h

Currently, when there are multiple videos that need to be played at the same time, there is video flicker. Because only one video decoder is supported internally, when there are other videos that need to be played at the same time, it causes decoder to receive video frames that are sent from different video sources.
The current solution is to generate multiple video decoders to parse different videos according to different fd.
Fixed video confusion when selecting 3d and 2d scenes when starting a new game in Dragon Quest XI.
Before:
After:
Fix #7196 
Before:
After:
There should be other similar scenes fixed.

Support multiple videos playing

---

src/core/hid/hid_core.cpp
src/core/hid/hid_core.h
src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/npad.h
src/core/hle/service/hid/hid.cpp

Implements SetNpadJoyAssignmentModeSingleByDefault, SetNpadJoyAssignmentModeSingle, SetNpadJoyAssignmentModeDual.
Some games where constantly spamming those functions because we din't have them implemented properly. 
This PR also introduces dual joycons with only one side connected. This isn't handled by our UI so only the game can set them properly.

service/hid: Implement SetNpadJoyAssignmentMode

---

src/yuzu/debugger/profiler.cpp

QWheelEvent::pos() is deprecated. Make use of position().toPoint() instead.

profiler: Use QWheelEvent position().toPoint()

---

src/video_core/texture_cache/texture_cache.h

this fixes an issue which could be caused on some very weird cases where the dst had a different format type than the blit. In AMD this was ignored on Vulkan. On NVIDIA this caused a crash on Vulkan.

Texture Cache: Fix mismatching image/views on blits

---

CMakeLists.txt

Cubeb doesn't use result_of anymore, it has been dropped in commit mozilla/cubeb@75d9d125ee655ef80f3bfcd97ae5a805931042b8
Edit: I can't test this right now, I'll rely on the CI

build: update cubeb and remove the result_of comment

---

src/core/hle/kernel/k_thread_queue.cpp

Because cpp files don't need *header* guards.

Remove erroneous #pragma once

---

src/common/input.h
src/input_common/drivers/gc_adapter.cpp
src/input_common/drivers/gc_adapter.h
src/input_common/drivers/keyboard.cpp
src/input_common/drivers/keyboard.h
src/input_common/drivers/mouse.cpp
src/input_common/drivers/mouse.h
src/input_common/drivers/sdl_driver.cpp
src/input_common/drivers/sdl_driver.h
src/input_common/drivers/tas_input.cpp
src/input_common/drivers/tas_input.h
src/input_common/drivers/touch_screen.cpp
src/input_common/drivers/touch_screen.h
src/input_common/drivers/udp_client.cpp
src/input_common/drivers/udp_client.h
src/input_common/input_engine.cpp
src/input_common/input_engine.h
src/input_common/input_poller.cpp

Tidies up some minor aspects of the interface and reduces the amount of object churn that goes on internally (we no longer regularly make copies of 100~200+ byte objects).

input_engine: Minor object churn cleanup

---

src/input_common/input_mapping.h
src/input_common/input_poller.h

Several documentation tags were being used slightly incorrectly, which lead to a few warnings.
We can silence these to get rid of a bit of warning spam.

input_poller/input_mapping: Silence several -Wdocumentation warnings

---

src/input_common/drivers/sdl_driver.cpp

`SDL_HINT_JOYSTICK_HIDAPI_SWITCH_HOME_LED` is no longer needed thanks to new default in SDL 2.0.18.
`SDL_HINT_JOYSTICK_HIDAPI_XBOX` is reported to cause conflicts with native driver Xbox driver on Linux, and Xbox controllers don't benefit from hidapi anyways.

input/SDL: Update SDL hints

---

src/common/input.h
src/core/hid/emulated_console.cpp
src/core/hid/emulated_console.h
src/core/hid/emulated_controller.cpp
src/core/hid/emulated_controller.h
src/core/hid/emulated_devices.cpp
src/core/hid/emulated_devices.h
src/input_common/helpers/stick_from_buttons.cpp
src/input_common/helpers/touch_from_buttons.cpp
src/input_common/input_poller.cpp

CallbackStatus instances aren't the cheapest things to copy around (relative to everything else), given that they're currently 520 bytes in size and are currently copied numerous times when callbacks are invoked.
Instead, we can pass the status by const reference to avoid all the copying.

common/input: Avoid numerous large copies of CallbackStatus

---

src/yuzu/applets/qt_software_keyboard.cpp

We were unconditionally accessing the keyboard_buttons array, even if the bottom_osk_index was for the numberpad, leading to an out of bounds array access. Fix this by accessing the proper array for the current button when the index is for the numberpad.
Fixes #7573

qt_software_keyboard: Fix out of bounds array access

---

src/common/x64/cpu_detect.cpp

We currently do not make use of these fields, remove them for now.

common/cpu_detect: Remove CPU family and model

---

src/yuzu/main.cpp

I have `134850146304` bytes of ram and Yuzu was saying that I had `125.59 GB`
of ram. But `125.59` is actually the amount of gi**bi**bytes I have. In
gi**ga**bytes I would have `134.9`.
Additionally, I changed the `1024 / 1024 / 1024` here into the `_GiB`
user-literals that I added a while ago(#6519).
https://www.wolframalpha.com/input/?i=134850146304+bytes

yuzu/main: Fix host memory byte units. GB to GiB

---

src/video_core/texture_cache/texture_cache.h

This change fixes the incompatibility image/view between compressed and uncompressed textures format when blit image.
This should be a regression introduced by several recent texture cache changes.

Fix blit image/view not compatible

---

src/yuzu/configuration/config.cpp
src/yuzu/game_list.cpp
src/yuzu/uisettings.h

Previously, the favorites row was always expanded on launch. 
This change introduces a persistent setting that allows the favorites row's expanded state to be remembered between launches.

game_list: Add persistent setting for the favorites row expanded state

---

src/video_core/renderer_opengl/gl_texture_cache.h
src/video_core/renderer_opengl/renderer_opengl.cpp
src/video_core/renderer_vulkan/blit_image.cpp
src/video_core/renderer_vulkan/blit_image.h
src/video_core/renderer_vulkan/vk_blit_screen.cpp
src/video_core/renderer_vulkan/vk_texture_cache.cpp
src/video_core/renderer_vulkan/vk_texture_cache.h
src/video_core/texture_cache/texture_cache.h

The refactors a bit of the code that was introduced in #7219 and #7368. Mainly to reduce code duplication and unneeded arguments passed along between functions.
It also fixes an assertion failure that occurs when ConvertImage is called on rescaled textures.

video_core: Refactoring post A.R.T. merge

---

src/input_common/drivers/udp_client.cpp
src/input_common/helpers/udp_protocol.h
src/tests/CMakeLists.txt
src/tests/input_common/calibration_configuration_job.cpp

Partially reverted b01aa72, thread was unable to change status to "Completed".  Calibration is supposed to have multiple request-response exchanges, because of that we cannot store calibration's temporary data inside of callback's local variables.
Added small test for verification.

[input_common] Fixed thread hang

---

externals/CMakeLists.txt

The latest Linux builds do not see my Switch Pro Controller. @v1993 also confirms that joycons are not seen. It shows ` input_common/drivers/sdl_driver.cpp:InitJoystick:287: Failed to open joystick 0`.
Enable `SDL_THREADS` and `SDL_ATOMIC`. They are now required explicitly since 2.0.18  to have HIDAPI and libusb work.
Set `SDL_WAYLAND=OFF` due to [build issue](https://github.com/libsdl-org/SDL/commit/e2ade2bfc46d915cd306c63c830b81d800b2575f) (patch is not available in 2.0.18).
[Related issue](https://github.com/libsdl-org/SDL/issues/5095)

externals/CMakeLists: fix detection/init of Switch controllers in SDL 2.0.18

---

src/core/hid/emulated_controller.cpp
src/core/hid/hid_types.h
src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/npad.h
src/core/hle/service/hid/hid.cpp

Some games test the device rumble all the time. Resulting in an unpleasant continuous rumble. To avoid this we set the amplitude to zero after the test

core/hid: Cancel any vibration after the test

---

src/core/hle/kernel/kernel.cpp

Avoids a memory leak after stopping emulation.
Before:
After:
closes #7562

kernel: Manually destroy the current process during shut down

---

src/core/hid/emulated_console.cpp
src/core/hid/emulated_console.h
src/core/hid/motion_input.cpp
src/core/hid/motion_input.h
src/core/hle/service/hid/controllers/console_sixaxis.cpp
src/core/hle/service/hid/controllers/console_sixaxis.h

Improve accuracy of the VR camera by filling all the data needed. Including gyro data that previously corrupted the camera movement

service/hid: Improve console motion accuracy

---

src/yuzu/main.cpp

Toggling borderless fullscreen on the separate render window (`Single Window Mode` disabled) made it fullscreen on the monitor that the main yuzu window resided in.
This change allows the render window to go fullscreen on the monitor it resides in, independent of the main window location.

main: Make separate render window fullscreen toggle on the monitor it resides in

---

CMakeLists.txt
src/video_core/command_classes/codecs/codec.cpp

VA-API drivers for Intel/AMD GPUs exist on DragonFly, FreeBSD, NetBSD , OpenBSD and probably more. NVIDIA even provides the binary blob for FreeBSD and Solaris. Let's relax the conditionals.
See also [build log](http://www.ipv6proxy.net/go.php?u=http://beefy14.nyi.freebsd.org/data/130amd64-quarterly/300ff0bddeaa/logs/yuzu-qt5-s20211218.log).

build: enable VA-API on FreeBSD

---

src/core/hle/kernel/svc.cpp

- Enforce that the supplied handle is invalid, not valid.
- This gets Witcher 3 booting.
Note, lots of graphical issues, but it will now go in game with OpenGL.

hle: kernel: svc: GetInfo: Fix error checking with IdleTickCount.

---

CMakeLists.txt
src/yuzu/CMakeLists.txt
src/yuzu/main.cpp
src/yuzu/main.h

This pull request implements the wake lock using XDP's Inhibit API.
The SDL 2 implementation does not work in the Flatpak sandbox due to D-Bus message filtering. Although this was written for Flatpak, this also works outside of Flatpak.  
**Known Issues:**
- GNOME on Wayland session may still not respond to this kind of inhibit request, but that remains to be tested.
- KDE may not show yuzu's icon correctly (it will show an empty icon) in its power management panel when inhibit function is activated.

main: Fix wake lock (prevent sleep) in Flatpak

---

src/core/hle/kernel/k_thread.cpp

- This was added with firmware 11.0.0 (https://switchbrew.org/wiki/11.0.0).
- X18 is OR'd by kernel with 1, to make sure it is odd.

  core: hle: kernel: KThread: X18 should be a cryptographically random number.

---

src/shader_recompiler/backend/glasm/emit_glasm_context_get_set.cpp

GetAttribute expects an F32 result type at the IR level.
Similar to  #6928, this fixes the return value of attributes which were not returning an F32 in GLASM.

emit_glasm_context_get_set: Fix GetAttribute return value type.

---

src/video_core/renderer_opengl/gl_texture_cache.cpp
src/video_core/renderer_opengl/gl_texture_cache.h
src/video_core/renderer_vulkan/vk_texture_cache.cpp
src/video_core/renderer_vulkan/vk_texture_cache.h
src/video_core/texture_cache/texture_cache.h

The vulkan ImageView held a reference to its source image for rescale status checking. This pointer is sometimes invalidated when the texture cache slot_images container is resized.
To avoid an invalid pointer dereference, the ImageView now holds a reference to the container itself.
Should fix crashes that occur during Sonic Colors Ultimate gameplay.

vk_texture_cache: Fix invalidated pointer access

---

src/core/frontend/applets/controller.cpp
src/core/hid/emulated_controller.cpp
src/core/hid/emulated_controller.h
src/yuzu/applets/qt_controller.cpp
src/yuzu/configuration/configure_input_player.cpp

IsControllerValid() used the real npad type instead of the temporary type. This made imposible to connect controllers during configuring mode if the previous controller was invalid. Fixes 2 player mode on captain toad.

core/hid: Fix controller type validation

---

src/video_core/texture_cache/util.cpp

This addresses a miscalculation that occurs when resolving overlaps that are relatively distant apart in gpu memory space. 
The signed `diff` variable became negative for large differences, which resulted in the `if (diff > new_size)` check to fail under these circumstances, leading to large textures being allocated and crashes to ensue.
Fixes a VRAM spike+crash which most notably occurred in `Bravely Default 2`

texture_cache/util: Fix s32 overflow when resolving overlaps

---

src/shader_recompiler/backend/glasm/emit_glasm_context_get_set.cpp
src/shader_recompiler/backend/glasm/emit_glasm_instructions.h
src/shader_recompiler/backend/glsl/emit_glsl_bitwise_conversion.cpp
src/shader_recompiler/backend/glsl/emit_glsl_context_get_set.cpp
src/shader_recompiler/backend/glsl/emit_glsl_floating_point.cpp
src/shader_recompiler/backend/glsl/emit_glsl_instructions.h
src/shader_recompiler/backend/glsl/emit_glsl_integer.cpp
src/shader_recompiler/backend/glsl/emit_glsl_special.cpp
src/shader_recompiler/backend/glsl/glsl_emit_context.cpp
src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
src/shader_recompiler/backend/spirv/emit_spirv_instructions.h
src/shader_recompiler/frontend/ir/opcodes.inc
src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
src/shader_recompiler/ir_opt/constant_propagation_pass.cpp
src/shader_recompiler/profile.h
src/video_core/renderer_opengl/gl_device.cpp
src/video_core/renderer_opengl/gl_device.h
src/video_core/renderer_opengl/gl_shader_cache.cpp

After running the new driver through our suite of [unit tests](https://github.com/ReinUsesLisp/nxgpucatch), The two main issues encountered by the newer NVIDIA drivers are negation of floating point values, and bitwise conversions of input attributes. This PR addresses both.
When negating floating point values, prior drivers allowed the following usage:
```glsl
float f1 = 42.0f;
float f2 = -f1;    // f2 equals -42.0f
```
However, the new drivers ignored negation in these cases. The work around is to simply subtract the value from `0.0` to achieve the same result.
The bitwise conversion bug was more subtle. Due to the `GetAttribute` OpCode's return value being an F32, integer attribute values are bitwise converted to F32's, which are then converted back to U32 values when they are being …

shaders: Add fixes for NVIDIA drivers 495+

---

src/video_core/renderer_vulkan/vk_texture_cache.cpp
src/video_core/renderer_vulkan/vk_texture_cache.h
src/video_core/vulkan_common/vulkan_device.cpp
src/video_core/vulkan_common/vulkan_device.h

Fixes a crash when scaling MSAA textures in titles such as Sonic Colors Ultimate.

vk_texture_cache: Use 3D scale helpers for MSAA texture scaling on Intel Windows drivers

---

src/yuzu/applets/qt_controller.cpp
src/yuzu/configuration/configure_input_player.cpp

There is no need to display all controller types if game only allows a few.

controller_applet: Only populate supported controllers

---

src/yuzu/main.cpp

Some UI elements like stop/start or configure current game weren't disabled after a game was stopped. To fix this we update the emulation_running flag just after stopping the emu_thread

yuzu: Fix UI elements not updating correctly

---

src/core/hid/emulated_controller.cpp
src/core/hid/emulated_controller.h

Fullkey controllers fallback to pro controllers in real HW. We currently don't do that. To avoid this issue we reconnect the controller as Pro controller to avoid having to open the config window.

core/hid: Add fallback to fullkey controllers

---

src/core/hle/service/nvflinger/nvflinger.cpp
src/video_core/gpu.cpp
src/video_core/gpu.h

Fixes a hang that may occur when stopping emulation and the VSync thread is blocked on the syncpoint condition variable.

gpu: Use std::stop_token in WaitFence for VSync thread

---

src/common/settings.h
src/shader_recompiler/environment.h
src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
src/video_core/shader_environment.cpp
src/video_core/shader_environment.h
src/yuzu/configuration/configure_debug.cpp
src/yuzu/configuration/configure_debug.ui

We used to have an internal branch for this before Hades. I think this should be added publicly now.
For use:
1. Activate "Dump Game Shaders" in Debug tab.
2. Look for the shaders in yuzu's user folder/dump/shaders.
3. use nvdiasm to disassemble them. Ex. "nvdiasm -b SM52 myshader.ash > my-disassembled_shader.txt"

ShaderDecompiler: Add a debug option to dump the game's shaders.

---

src/core/core.cpp
src/core/hle/service/nvflinger/nvflinger.cpp
src/video_core/gpu.cpp
src/video_core/gpu.h

Alternative approach to #7668. Same goal of avoiding hangs on the vsync thread when stopping emulation.

 gpu: Add shut down method to synchronize threads before destruction 

---

CMakeLists.txt
externals/CMakeLists.txt

Adds support for the following system libs with CMake defines:
* opus - `YUZU_USE_BUNDLED_OPUS=OFF`
~~I have been using this patch since about the beginning of this year with over 99 different builds spanning every yuzu-mainline tag since then. I have not experienced any issues using system libs for these vs the bundled.~~

Add support for linking against system Opus

---

src/yuzu/configuration/configure_per_game.cpp

Tab initialization happens before the game's custom configuration was loaded by the program. The original solution was to use the tab's SetConfiguration function to let the UI correctly, but visual highlighting was done in the UI setup and fixing that directly would just lead to a snowball of 'fixes'.
Changes tab initialization to happen after the configuration is loaded, which means that it no longer happens in member initializers in the `ConfigurePerGame` constructor. Removes the cluster of `??_tab->SetConfiguration`'s that I added earlier to get around this issue initially.
Fixes a regression in #6774

configure_per_game: Initialize tabs after loading custom configuration

---

src/video_core/memory_manager.cpp
src/video_core/memory_manager.h
src/video_core/texture_cache/texture_cache.h

This fixes a few oversights in memory management for sparse (non-contiguous) GPU backed memory. 
The main issue fixed was in `GetSubmappedRange` which did not account for page offsets in the ranges returned in the result.
It also avoids reading/writing to memory whose CPU backed address is 0, as these are the non-resident portions of the sparse memory regions.
This should fix memory related issues that occur in titles that heavily make use of sparse textures, notably UE4 games.

video_core/memory_manager: Fixes for sparse memory management

---

src/core/hid/emulated_controller.cpp
src/input_common/drivers/udp_client.cpp
src/yuzu/configuration/configure_input_player.cpp

Fixes a couple of problems with UDP controllers. Where motion wasn't automapped and manually mapping a button will reset the selected device to the UDP controller 0
Thanks to @v1993 for detecting the issues

input_common: Fix UDP controller mappings

---

src/core/hle/kernel/k_memory_block.h
src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/svc.cpp
src/core/hle/kernel/svc_types.h

This is the first of several changes bringing our memory implementation up to speed with latest HOS, as well as various updates to improve accuracy. Primarily, this updates SetMemoryAttribute, updates our CheckMemoryState impl, and updates several related enums.

Kernel Memory Updates (Part 1): SetMemoryAttribute, and other minor changes.

---

src/core/hid/motion_input.cpp

The initial value was estimated to be safe. But some motion devices are capable to input really fine values. This PR reduces the threshold to allow for those motion devices to work properly.
Closes #7696

core/hid: Reduce gyro threshold even more

---

src/yuzu/main.cpp

This is a temporary solution for now to accommodate for mods containing more than 4096 files.

yuzu: main: Increase the open file limit on Windows to 8192

---

src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/physical_core.cpp
src/core/hle/kernel/svc.cpp
src/core/hle/service/ldr/ldr.cpp

This is the second set of several changes bringing our memory implementation up to speed with latest HOS, as well as various updates to improve accuracy. With these changes, we:
* Rename MapProcessCodeMemory and UnmapProcessCodeMemory functions to MapCodeMemory and UnmapCodeMemory, to be consistent with the official naming.
* Update all usage of KMemoryPermission::ReadAndWrite to UserReadWrite, as this is what should be used for the user-space applications that yuzu aims to emulate.
* Fixes an issue with LDR where we were trying to unmap BSS section of a shared module, even when BSS might be unset.
* Updates our implementation of SetProcessMemoryPermission to be more accurate.

Kernel Memory Updates (Part 2): SetProcessMemoryPermission, update permissions, and other minor changes.

---

src/core/hle/service/hid/hid.cpp

Motion stops working in Mario Tennis in swing mode if the update rate is too fast even when HW updates at the same speed. 10ms it's the minimum period that the game needs to start working again.

service/hid: Decrease motion update rate

---

src/core/hid/emulated_console.cpp

Found by static analysis with PVS-Studio.
It's only a guess, but code looks wrong as is. @german77 should check if this is indeed a correct replacement.

hid: Correct assignment source for rotations

---

src/input_common/input_engine.cpp

You guessed it - found by static analysis with PVS-Studio. It's a very minor thing, but it kinda bothers me now that I know about it.

input_common: nitpick about SetHatButton usage

---

src/core/hle/kernel/k_scheduler.cpp

Found by static analysis with PVS-Studio. Nobody seems to really know what was it doing there.

kernel: remove no-op code

---

src/video_core/host_shaders/astc_decoder.comp

The new Nvidia drivers (Series 511.xx+) have a bug where the `FastReplicateTo6` function produces a lookup into the `REPLICATE_TO_8` table rather than the `REPLICATE_TO_6` table.
This seems to be an optimization gone wrong. Combining the logic of the `FastReplicate` functions into a single function seems to work around the bug.
Closes #7714

astc_decoder: Combine FastReplicate functions to work around new NV driver bug

---

src/common/fiber.cpp
src/core/CMakeLists.txt
src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/k_process.h
src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/k_thread.h
src/core/hle/kernel/k_worker_task.h
src/core/hle/kernel/k_worker_task_manager.cpp
src/core/hle/kernel/k_worker_task_manager.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/kernel.h

Previously, yuzu would close the KThread-owned reference when svcExitThread was called, while it was still scheduled on a core. Subsequently, another game thread calls svcCloseHandle, decrementing the last reference to the thread and destroying it, in a race condition that can happen while we are still scheduling, causing a crash in the emulator.
The accurate solution is to properly implement thread termination. With these changes, we introduce KWorkerTask and KWorkerTaskManager, which is a background task thread used to process tasks from threads and processes. When svcExitThread is called, a task is dispatched to finish the termination on this new kernel thread. Here, we wait for the thread to be unscheduled from all cores before we close the thread-owned reference. This ensures the …

Accurately implement thread exit

---

src/common/input.h
src/input_common/drivers/mouse.cpp
src/input_common/drivers/mouse.h
src/input_common/input_mapping.cpp
src/yuzu/configuration/configure_input_player.cpp

We now have the necessary code to map the mouse as a motion device. This time with the z axis as the wheel input. On top of that use mouse button names since these are well defined.

input_common: Reintroduce motion from mouse and use button names

---

src/input_common/drivers/sdl_driver.cpp

Discord User moon lacer pointed us that official name is 'Xbox' not 'XBox'

Xbox controller default name nit pick

---

src/core/hle/kernel/k_memory_manager.cpp
src/core/hle/kernel/k_memory_manager.h
src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/kernel.cpp

This is the third set of several changes bringing our memory implementation up to speed with latest HOS, as well as various updates to improve accuracy. With these changes, we:
- Zero heap allocated pages from within KMemoryManager.
- Explicitly passed along heap allocation option.

Kernel Memory Updates (Part 3): Clear KMemoryManager pages & other fixes

---

src/core/hle/service/hid/hid.cpp

According to RE SetNpadAnalogStickUseCenterClamp is able to initialize applet_resource if it wasn't initialized before.
Fixes crash at boot on `パワプロクンポケットR`

service/hid: Initialize applet_resource on SetNpadAnalogStickUseCenterClamp

---

src/video_core/command_classes/codecs/codec.h

Regressed by https://github.com/ffmpeg/ffmpeg/commit/626535f6a169. From [error log](https://github.com/yuzu-emu/yuzu/files/7904669/yuzu-s20220119_1.log):
```c++
src/video_core/command_classes/codecs/codec.cpp: In member function 'void Tegra::Codec::Initialize()':
src/video_core/command_classes/codecs/codec.cpp:177:36: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
177 |     av_codec = avcodec_find_decoder(codec);
|                ~~~~~~~~~~~~~~~~~~~~^~~~~~~
|                                    |
|                                    const AVCodec*
```
Runtime tested on [FreeBSD](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261302) via Super Mario Odyssey (sailing destination previews), Bayonetta 2 (some cut scenes), Metroid Dread (intro).

video_core: unbreak build with FFmpeg 5.0

---

src/core/hid/input_converter.cpp

With the current settings 2p mode in pokemon let's go wasn't showing up.  By making the shake more violent we can make it appear without any effort using the keyboard

core/hid: Increment shake force

---

src/shader_recompiler/backend/glsl/glsl_emit_context.cpp
src/shader_recompiler/backend/spirv/spirv_emit_context.cpp

Found by static analysis with PVS-Studio. Original check wasn't actually checking for OOB and would segfault in case of it.

shader_recompiler: fix potential OOB access

---

src/yuzu/configuration/config.cpp
src/yuzu/configuration/config.h

On OSes with system-wide theming this allows yuzu to follow system style, regardless of its exact coloration, working well with both light and dark system themes. Dark /Colorful, on the other hand, forces dark theme regardless of user preferences set in system settings, making for a poor default.
Use Colorful variation to keep in line with icon style of patron-voted Dark Colorful.

Use Default Colorful theme by default outside of Windows

---

src/core/hle/service/apm/apm_interface.cpp

Since we don't currently support CPU overclocking within the emulated system, this can be stubbed for now, like APM IsCpuOverclockEnabled.
Fixes #7748

service: apm: Stub ISession SetCpuOverclockEnabled

---

src/core/hle/kernel/hle_ipc.h
src/core/hle/kernel/k_priority_queue.h
src/core/hle/kernel/k_scheduler.cpp
src/core/hle/kernel/k_server_session.cpp
src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/k_thread.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/service_thread.cpp
src/yuzu/debugger/wait_tree.cpp

This change includes various fixes and improvements for HLE service thread management. Primarily, this was motivated by a KThread leak of dummy threads allocated to back service host threads, which are used for grabbing the kernel locks. Previously, we would not release these dummy threads when the service threads were destroyed. For games that create/destroy service interfaces frequently (e.g. Pokémon Sword and Shield), this would result in a pretty severe leak over long gameplay sessions.
Furthermore, previously, these dummy threads could inadvertently get scheduled on core 3 under certain conditions. These aren't threads that can actually be scheduled by the guest emulation, and this could result in a crash (e.g. in Pokémon Sword and Shield after many hours of gameplay). We add some …

Various fixes to HLE service thread management

---

src/audio_core/stream.cpp
src/yuzu/configuration/config.cpp
src/yuzu/configuration/config.h
src/yuzu/main.cpp

Since the idea is to do everything with the gamepad It was decided to add hotkeys to control the volume. I removed the emulation speed hotkeys mainly since they only work on single core and it's not recommended anymore to use single core.
As an extra I noticed the volume % was a little far from ideal. So I changed the formula to something better.

yuzu: Add volume hotkeys

---

externals/ffmpeg/CMakeLists.txt

* Fix compilation if CUDA_INCLUDE_DIRS is empty/contains multiple paths
* Pass CMAKE_{C,CXX}_COMPILER_LAUNCHER to ffmpeg compiler
There's still a plenty of space for improvement here, but now it at least compiles for me.

Improve FFmpeg cmake file

---

src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/k_process.h
src/core/hle/kernel/k_thread.cpp

- Previously implementation was incorrect, and would occasionally underflow.

hle: kernel: KThread: Improve Increment/Decrement RunningThreadCount.

---

src/core/hle/kernel/k_affinity_mask.h

This is already checked inside `GetCoreBit()`

kernel/k_affinity_mask: Remove duplicated assert

---

src/input_common/drivers/udp_client.cpp
src/input_common/drivers/udp_client.h

These are deprecated and `make_address` variants and `to_uint()` should be used instead.
Just prevents the UDP client from breaking in the event the deprecated functions get removed at some point.

input_common/udp_client: Replace deprecated from_string()/to_ulong() functions

---

src/input_common/input_engine.h
src/input_common/input_mapping.cpp
src/input_common/input_mapping.h
src/input_common/main.cpp
src/input_common/main.h

Avoids creating unnecessary 168 byte copies per callback invocation.
Also does some minor touchups while in the area.

input_common/main: Pass MappingData by const reference in callbacks

---

src/video_core/renderer_vulkan/vk_fsr.cpp

Generally, we should be ending statements with a semicolon not a comma
Resolves a clang diagnostic.

vk_fsr: Replace comma operator with semicolon

---

src/video_core/gpu.h

These were obsoleted in 2c47f8aa1886522898b5b3a73185b5662be3e9f3 but were accidentally overlooked.
While we're in the same area, we can remove some forward declarations that are no longer necessary.

gpu: Remove obsoleted CDmaPusher() accessors

---

src/shader_recompiler/frontend/maxwell/translate_program.h

Since `ConvertLegacyToGeneric` has a void return value, there's nothing that is actually returned by the function.
Should get rid of some warnings when compiling

shader_recompiler: Remove unnecessary [[nodiscard]] specifier

---

externals/FidelityFX-FSR/ffx-fsr/ffx_fsr1.h
src/yuzu/configuration/configure_graphics.ui

Before (EA 2432) | After
------------ | -------------
This PR updates yuzu's FSR implementation to the latest version
This PR does the following:
- [Updates AMD FSR to the latest version (1.0.2)](https://github.com/yuzu-emu/yuzu/compare/master...Moonlacer:fsr-1.0.2?expand=1#diff-9fb2d3a36f6fa275f6eebe246a80fa38cad68870e9c10764089591a3b2a93545).
- [Replaces brackets around the "[Vulkan Only]" to "(Vulkan Only)" to fit with the rest of the UI](https://github.com/yuzu-emu/yuzu/compare/master...Moonlacer:fsr-1.0.2?expand=1#diff-045d8b4da4839e373193af2e68cea6b2d94412f967c7e771890e7b9ad2710ec3).

Update AMD FidelityFX Super Resolution™ to 1.0.2

---

src/common/settings.h
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_input_advanced.cpp
src/yuzu/configuration/configure_input_advanced.ui
src/yuzu/hotkeys.cpp
src/yuzu/util/controller_navigation.cpp

Some users use external programs to translate controller input into keyboard input. This conflicts with controller navigation. Add a setting to fully disable controller navigation.
Closes #7758

yuzu: Add setting to disable controller navigation

---

src/video_core/engines/maxwell_3d.cpp
src/video_core/macro/macro.cpp
src/video_core/macro/macro.h
src/video_core/macro/macro_hle.cpp
src/video_core/macro/macro_hle.h
src/video_core/macro/macro_interpreter.cpp
src/video_core/macro/macro_interpreter.h
src/video_core/macro/macro_jit_x64.cpp
src/video_core/macro/macro_jit_x64.h

Moves the impl classes like `HLEMacroImpl`, `MacroInterpreterImpl`, and `MacroJITx64Impl` into their respective cpp files to keep implementation details hidden and also lessen header dependencies for those implementations in their header files (which is nice, since xbyak is no longer included into files unrelated to the x86-64 implementation).
Now the implementations can be freely modified without needing to rebuild all of the implementations at once.
This is mainly moving code around (save for a few commits)

video_core/macro: Move impl classes into their cpp files

---

src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/svc.cpp

The next part of my long list of changes to bring our memory implementation up to speed with latest HOS. This time around, MapPages and UnmapPages are updated to be more accurate, various KPageTable methods are updated to have more accurate naming, and various other methods are cleaned up. See each commit for details.

Kernel Memory Updates (Part 4): Improve Un/MapPages, and more.

---

src/common/x64/xbyak_abi.h
src/video_core/macro/macro_jit_x64.cpp

This allows us to eliminate any static constructors that would have been
emitted due to the function not being constexpr.

common/xbyak_api: Make BuildRegSet() constexpr

---

src/core/hid/emulated_controller.cpp
src/core/hid/motion_input.cpp
src/input_common/input_poller.cpp
src/yuzu/configuration/configure_input_player.cpp

Depending on the sensitivity and quality of the sensor one might want to change the gyro threshold to provide the best motion experience for everyone. 
90% of the time you will not need to change this. Only if you experience gyro drift or motion is not detected on very slow movements.

input_common: Add option to configure gyro threshold

---

src/shader_recompiler/backend/spirv/emit_spirv.cpp

Fixes Transform Feedback on AMD Vulkan drivers.
Before |  After
:-------------------------:|:-------------------------: 
closes #7790 closes #6612 closes #5004

emit_spirv: Add Xfb execution mode when transform feedback is used

---

src/video_core/buffer_cache/buffer_cache.h

The existing stream buffer optimization accounts for size increases at the end of the allocated buffer.
This adds the same optimization, increasing the size from the beginning of the buffer as well to reduce buffer allocations when expanding the same buffer from the left.
Fixes a crash in Pokemon Legends Arceus

buffer_cache: Reduce stream buffer allocations when expanding from the left

---

src/core/hle/kernel/k_priority_queue.h
src/core/hle/kernel/k_scheduler.cpp

- Previously, it was possible for a thread migration to occur from core A to core B.
- Next, core B waits on a guest lock that must be released by a thread queued for core A.
- Meanwhile, core A is still waiting on the core B's current thread lock - resulting in a deadlock.
- Fix this by try-locking the thread lock.
- Fixes softlocks in FF8 and Pokemon Legends Arceus.
Closes #7795

hle: kernel: KScheduler: Fix deadlock with core waiting for a thread lock that has migrated.

---

src/input_common/drivers/sdl_driver.cpp

Dual sense controllers support HD rumble. So they should use a linear amplitude instead of the exponential for motors. This makes the controller vibrate with less force

input_common: Add DS5 to HD rumble list

---

src/shader_recompiler/backend/spirv/emit_spirv_atomic.cpp
src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp

Some drivers do not support 64-bit atomics, and fallback to atomically modifying U32x2 vectors. This change ensures that U32x2 storage vectors are defined in the spir-v shader when 64-bit atomics are used.
Fixes a hang when booting `Pokemon Legends Arceus` on some devices, notably Intel GPUs,.

spirv_atomic: Define U32x2 storage buffers for 64-bit storage atomics

---

src/common/wall_clock.cpp

If the rtsc frequency is lower than 1,000,000,000hz it will cause udiv128 to overflow. To prevent this issue we fallback to the StandardWallClock.
Fixes issue where yuzu crash at boot with no logs.

wall_clock: Use standard wall clock if rtsc frequency is too low

---

src/video_core/buffer_cache/buffer_cache.h
src/video_core/engines/engine_upload.cpp
src/video_core/engines/engine_upload.h
src/video_core/engines/kepler_compute.cpp
src/video_core/engines/kepler_memory.cpp
src/video_core/engines/kepler_memory.h
src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_3d.h
src/video_core/gpu.cpp
src/video_core/memory_manager.h
src/video_core/rasterizer_interface.h
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_rasterizer.h
src/video_core/renderer_vulkan/vk_rasterizer.cpp
src/video_core/renderer_vulkan/vk_rasterizer.h

This fixes vertex explosions on Pokemon Legends Arceus and likely other BCR regressions. (mostly, there's a bit of random flicker every 2-3 mins or so, but fixes itself)
Credits to epicboy for noticing was writing GPU modified pages.

Inline2Memory: Flush before writing buffer.

---

src/video_core/shader_cache.cpp
src/video_core/shader_cache.h

Same behavior, but without the need to move into the function to avoid an allocation.

video_core/shader_cache: Take std::span in RemoveShadersFromStorage()

---

src/common/fs/file.h

Since this has a void return value, there's nothing that can actually be used when returning

common/file: Remove [[nodiscard]] from Open()

---

src/yuzu/game_list.cpp

The previous overload of split() was deprecated in 5.14. Keeps us a little more forward compatible with Qt 6

yuzu/game_list: Use non-deprecated version of QString's split() function

---

src/yuzu/configuration/configure_input_player.cpp

Just a few trivial changes so that we don't churn ParamPackage reallocations in some cases

configure_input_player: Avoid unnecessary ParamPackage copies

---

src/yuzu/configuration/configure_motion_touch.cpp

Same behavior, but ensures that the functions we're calling exist, since they can be checked at compile-time.

configure_motion_touch: Use functor versions of invokeMethod

---

src/common/wall_clock.cpp
src/common/wall_clock.h
src/common/x64/native_clock.cpp

Additionally, check the precision of the hardware TSC against the emulated CPU and clock counter frequencies. This ensures that the hardware clock is only used when it is more precise than these two frequencies.

common: wall_clock: Utilize constants for ms, us, and ns ratios

---

src/yuzu/configuration/configure_hotkeys.cpp

These strings shouldn't be translated as they would break the controller hotkey detection

hotkeys: Don't translate hotkey buttons

---

src/yuzu/configuration/configure_dialog.cpp
src/yuzu/configuration/configure_filesystem.cpp
src/yuzu/configuration/configure_filesystem.h

This allows the dialog to be retranslated during runtime if the language is changed.
Makes the filesystem widget consistent with all of the other ones.

configure_filesystem: Add missing changeEvent() override

---

src/common/input.h
src/input_common/drivers/udp_client.cpp
src/input_common/drivers/udp_client.h
src/yuzu/configuration/configure_input_player.cpp

V1993 mentioned that buttons where missing on UDP controllers. This PR Enables two buttons that where currently unused.

input_common: Add home and hard touch press buttons to UDP controllers

---

src/yuzu/main.cpp

I did this once for GetHotkey but LinkActionShortcut was introduced afterwards reintroducing the same bug

yuzu: Disable auto repeat on hotkeys again

---

src/common/common_types.h
src/common/telemetry.h
src/core/arm/arm_interface.h
src/core/file_sys/vfs.h
src/core/hid/emulated_console.h
src/core/hid/emulated_controller.h
src/core/hid/hid_core.h
src/core/hle/kernel/k_auto_object.h
src/core/hle/kernel/k_auto_object_container.h
src/core/hle/kernel/k_handle_table.h
src/core/hle/kernel/k_memory_manager.h
src/core/hle/kernel/k_memory_region.h
src/core/hle/kernel/k_page_heap.h
src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/k_slab_heap.h
src/core/hle/service/vi/display/vi_display.h
src/core/loader/loader.h
src/video_core/renderer_base.h
src/video_core/renderer_opengl/gl_resource_manager.h

We have both `YUZU_NON_COPYABLE` and `YUZU_NON_MOVEABLE` defines which already allow a more fine-grained specifying of intent, so we can make use of those and get rid of the `NonCopyable` struct, so that we don't have two things around that do the same thing.

common_types: Remove NonCopyable struct

---

src/video_core/renderer_vulkan/vk_scheduler.cpp
src/video_core/renderer_vulkan/vk_scheduler.h

This fixes some weird freezes in some games on some GPUs, mostly iGPUs. It affected Super Mario 64 Port (Homebrew) and Super Mario All Stars.

Vulkan: Fix Scheduler Chunks when their FuncType is 0.

---

src/core/hid/input_converter.cpp
src/input_common/drivers/sdl_driver.cpp
src/yuzu/configuration/configure_input_player_widget.cpp
src/yuzu/configuration/configure_input_player_widget.h

Battery implementation was never completed. This PR removes the ugly battery symbols with newer ones. It also realigns some elements and fixes SDL battery reporting. Hopefully making everything nicer.
Before
After

yuzu: ui: Improve battery symbols

---

src/yuzu/main.cpp

For unknown reasons, this flag may persist after the application has been closed.
Removing this flag when restoring the UI state ensures that a frameless window will not be shown on startup.

main: Always remove the frameless window flag when restoring UI state

---

src/yuzu_cmd/config.cpp

Motion inputs were not being read in by the config when yuzu-cmd boots up. This adds support for those in the same manner as yuzu-qt's method.
While we're at it, make a reference to the current player controls to improve readability. Also updates the if statements in the Analog and Button loops with curly braces to keep the style consistent.

yuzu-cmd: config: Support motion inputs

---

src/core/hle/kernel/svc.cpp
src/core/hle/service/pm/pm.cpp

(Incomplete) implementation of `pm::dmnt::AtmosphereGetProcessInfo`, which is used by Skyline. See https://github.com/yuzu-emu/yuzu/issues/7392

service: pm: Implement AtmosphereGetProcessInfo

---

src/core/hle/kernel/k_code_memory.cpp

Credits to @xerpi for finding this issue and pointing it out on #7519.

hle: kernel: KCodeMemory: Correct m_page_group number of pages.

---

src/input_common/drivers/sdl_driver.cpp
src/input_common/input_poller.cpp
src/yuzu/configuration/configure_input_player.cpp

Adds the ability to auto center the stick with right click. On top of that seems like Y axis had the offset in the wrong direction. Resulting in even larger drift.

yuzu: Add auto center on right click

---

src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h

Used by Splatoon 2, when opening the inventory from a LAN battle lobby.
Still not really familiar with stubbing functions, and `rb.Push(false);` feels wrong to me. I felt the need to point this out before someone reviews this PR.
Reference: https://switchbrew.org/wiki/HID_services#IsUsbFullKeyControllerEnabled

hid: Stub IsUsbFullKeyControllerEnabled

---

src/yuzu/debugger/console.cpp

This allows the console to display multi-byte encoded characters.
Note that the font used in the console needs to support rendering these characters, otherwise they will be rendered as ?

debugger: console: Set console output codepage to UTF-8

---

src/common/fs/fs_util.cpp
src/common/fs/fs_util.h

These functions allow to construct a string view from an input buffer, avoiding the copy done by the non string view counterparts. However, callers must be cognizant of the viewed buffer's lifetime to avoid a use-after-free.

common: fs_util: Add buffer to string view utility functions

---

src/audio_core/common.h

Update CURRENT_PROCESS_REVISION from REV9 to REVA.
Used by Nintendo Entertainment System - Nintendo Switch Online 6.0.0 and Super Nintendo Entertainment System - Nintendo Switch Online 3.0.0.

audio_core: Update current process revision

---

src/core/file_sys/patch_manager.cpp

Currently we dump the base exeFS, this PR changes it to dump the patched exeFS instead, which I think is more useful. Gives you access to game updates, and you can still get the base by disabling game updates. Thanks @gidoly for testing this for me.

file_sys: Dump patched exefs rather than base

---

src/core/hle/kernel/svc.cpp
src/core/hle/kernel/svc_wrap.h

Very straightforward, they are just wrappers to the 64-bit version of the SVC.

kernel: svc: Add OutputDebugString32, CreateCodeMemory32, ControlCodeMemory32

---

src/common/telemetry.h

Addresses https://github.com/yuzu-emu/yuzu/issues/7881 to fix linux builds.
`YUZU_NON_COPYABLE` deletes the `T(const T&)` constructor which will
cause the implicitly defined default ctor/dtor to no-longer generate.

common: Add NullVisitor default constructor

---

src/yuzu/configuration/configure_input_player.cpp
src/yuzu/configuration/configure_touch_from_button.cpp

Pressing the enter key would restart the mapping process before the key is registered. Resulting on ignoring completely the enter key. By rejecting new inputs until the timer is disabled we can ensure the key will be detected properly.
Only missing key now it's the TAB key since this one is handled by Qt as switching object focus

yuzu: config: Fix mapping issues with the enter key

---

src/core/hle/kernel/k_page_table.cpp

- Fixes a logic bug in KPageTable::UnmapPages.

core: hle: kernel: KPageTable: Fix UnmapPages.

---

src/video_core/renderer_vulkan/vk_texture_cache.cpp
src/video_core/vulkan_common/vulkan_device.cpp
src/video_core/vulkan_common/vulkan_device.h

Currently Mesa's ANV driver [does not support VK_FORMAT_B5G6R5_UNORM_PACK16](https://gitlab.freedesktop.org/mesa/mesa/-/blob/21.3/src/intel/vulkan/anv_formats.c#L152) which results in a crash; implement an alternative for it.
Fixes #6958 and part of #7023

vulkan_device: fix missing format in ANV

---

src/input_common/drivers/sdl_driver.cpp
src/input_common/drivers/udp_client.cpp
src/input_common/drivers/udp_client.h
src/input_common/input_engine.cpp
src/input_common/input_engine.h
src/input_common/input_poller.cpp

Finally figured out why battery values wasn't reported correctly. This PR Should reflect correct battery values for SDL controllers

input_common: Remove battery duplicated struct and update every button press

---

src/yuzu/main.cpp

Currently if you drag and drop an amiibo bin file and the previous one is connected it will fail to connect the new amiibo. Adding a little check and message to disconnect the amiibo ensures the next attempt will be successful

yuzu: Disconnect amiibos on drag and drop

---

src/video_core/renderer_vulkan/vk_blit_screen.cpp

vk_blit_screen: Add missing framebuffer format

---

externals/ffmpeg/CMakeLists.txt

The correct expression should be `endif(NOT WIN32)` (because that's what was in the if statement), but that's confusing, so just remove it.
This resolves the related CMake warning.

ffmpeg: Fix mis-maching argument warning for endif

---

src/video_core/renderer_opengl/gl_fence_manager.cpp

Per the [spec](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetSync.xhtml), bufSize is the number of integers that will be written, in this case, 1.
Also, the length argument is optional if the the number of elements written is not needed.

gl_fence_manager: Minor optimization to signal querying

---

src/common/settings.cpp
src/common/settings.h
src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_64.cpp
src/core/arm/dynarmic/arm_exclusive_monitor.cpp
src/core/arm/dynarmic/arm_exclusive_monitor.h
src/core/arm/exclusive_monitor.h
src/core/hle/kernel/k_address_arbiter.cpp
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_cpu.cpp
src/yuzu/configuration/configure_cpu.h
src/yuzu/configuration/configure_cpu.ui
src/yuzu/configuration/configure_cpu_debug.cpp
src/yuzu/configuration/configure_cpu_debug.ui
src/yuzu_cmd/config.cpp
src/yuzu_cmd/default_ini.h

Do not merge (relies on commit not yet merged to dynarmic master). Please test extensively.
This PR enables experimental support for faster exclusive memory instructions, by inling implementation into JITted code.
The intent of this PR is to improve performance in games extensively using these instructions, such as PLA.
It does this by providing three optimizations:
* Providing a fastmem implementation of exclusive memory instructions (safe optimization).
* Optionally recompiling the above to use callbacks on fastmem failure (safe optimization).
* Allows cross-thread GlobalMonitor related locking to be disabled, relying purely on cmpxchg semantics (unsafe optimization).
See also: https://github.com/merryhime/dynarmic/pull/664
**Please suggest better wording for settings menu text.**
TODO:

dynarmic: Inline exclusive memory accesses

---

src/core/CMakeLists.txt
src/core/hle/kernel/board/nintendo/nx/k_memory_layout.h
src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
src/core/hle/kernel/board/nintendo/nx/k_system_control.h
src/core/hle/kernel/initial_process.h
src/core/hle/kernel/k_memory_layout.h
src/core/hle/kernel/k_memory_manager.cpp
src/core/hle/kernel/k_memory_manager.h
src/core/hle/kernel/k_memory_region_type.h
src/core/hle/kernel/k_page_heap.cpp
src/core/hle/kernel/k_page_heap.h
src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/kernel.h

This is a continuation of my work to bring our kernel memory management up to speed with recent system updates and the latest known updates (see previous PRs #7701, #7698, and #7684 for a history of this effort).
The primary focus of this round of changes is to fully revamp the KMemoryManager implementation. Beyond making this more accurate, this fixes a major issue where we were misreporting memory pool sizes by not taking into consideration the two memory managers used for the application pool. Furthermore, we move the memory layout to the kernel state, allowing this to be accessed elsewhere without deriving it again. Lastly, there are several other misc. fixes in support of and/or related to these changes.

Kernel Memory Updates (Part 4): Revamp KMemoryManager & other fixes

---

src/common/host_memory.cpp

It is possible for virtual_offset to not be 0 when the iterator is at the beginning, and thus, `std::prev(it)` may be evaluated, leading to a crash in debug mode.

host_memory: Fix fastmem crashes in debug builds

---

src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
src/video_core/renderer_opengl/gl_graphics_pipeline.h

This PR aims to alleviate reported issues with async shaders on OpenGL where graphical issues persist during the session.
The challenge with async shaders on OpenGL is that there are two levels of asynchronous execution happening:
- The CPU shader builder thread runs concurrently, and has to coordinate with the main thread to inform it when the thread completed its work
- OGL commands are asynchronous by nature, and run concurrently with the CPU code.
So, even though the shader builder CPU thread completes its CPU work, it doesn't imply that the OGL commands it issued have been completed by the OGL context it shares with with main thread. 
This PR improves on async shaders by making use of `GLsync` fences to better coordinate when the builder thread has completed the OpenGL commands in …

gl_graphics_pipeline: Improve shader builder synchronization using fences

---

src/video_core/engines/maxwell_dma.cpp
src/video_core/engines/maxwell_dma.h

This implements the missing semaphore for MaxwellDMA.
- Used by BOTW & PLA.

MaxwellDMA: Implement semaphore operations

---

src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h

This is a continuation of my work to bring our kernel memory management up to speed with recent system updates and the latest known updates (see previous PRs #7956, https://github.com/yuzu-emu/yuzu/pull/7701, https://github.com/yuzu-emu/yuzu/pull/7698, and https://github.com/yuzu-emu/yuzu/pull/7684 for a history of this effort).
- This makes these functions more accurate to the real HOS implementations.
- Fixes memory access issues in Super Smash Bros. Ultimate that occur when un/mapping NROs.

Kernel Memory Updates (Part 5): Revamp MapCodeMemory and UnmapCodeMemory.

---

src/shader_recompiler/frontend/maxwell/translate/impl/logic_operation_three_input.cpp
src/shader_recompiler/frontend/maxwell/translate/impl/logic_operation_three_input_lut3.py

Thanks to @asLody for optimizing this function within #7985. This raised the focus that this function should be optimized more.
The current table assumes that the host GPU is able to invert for free, so only AND,OR,XOR are accumulated in the performance metrik.
Performance results:
Instructions
0: 8
1: 30
2: 114
3: 80
4: 24
Latency
0: 8
1: 30
2: 194
3: 24

shader_recompiler/LOP3: Use brute force python results within switch/case.

---

src/core/core.cpp
src/core/frontend/emu_window.h
src/video_core/video_core.cpp

This PR aims to fix two crashes when yuzu fails to create the emulated GPU instance (e.g. no Vulkan driver is present). The first is when `CreateGPU` fails yuzu would try and shutdown the GPU instance regardless of whether any instance was actually created. 
Secondly, when `CreateRenderer` fails, the `GraphicsContext` that was `std::move`'d into it is destroyed before the `Scoped` that was created to manage its currency. In that case, the `GraphicsContext::Scoped` will still call its destructor at the ending of the function. And because the `context` is destroyed, the `Scoped` will cause a crash as it attempts to call a destroyed object's `DoneCurrent` function.
~~The first issue if fixed by checking for `nullptr` before calling those methods. The second is fixed by avoiding using any …

core, video_core: Fix two crashes when failing to create the emulated GPU instance

---

src/core/hle/kernel/k_page_table.h
src/core/hle/service/ldr/ldr.cpp

- Instead of randomization, choose in-order addresses for where to map NROs into memory.
- This results in predictable behavior when debugging and consistent behavior when reproducing issues.

hle: service: ldr: Use deterministic addresses when mapping NROs.

---

src/common/bit_util.h
src/common/x64/cpu_detect.cpp
src/common/x64/cpu_detect.h

These are some updates and fixes for `cpu_detect`'s `CPUCaps` structure to make it more robust for later feature-detection additions.

cpu_detect: Refactor detection of processor features

---

src/common/x64/cpu_detect.cpp

Restores compatibility with MSVC's [`__cpuid` intrinsic](https://docs.microsoft.com/en-us/cpp/intrinsics/cpuid-cpuidex?view=msvc-170).

cpu_detect: Revert `__cpuid{ex}` array-type argument

---

src/common/logging/backend.cpp

Ensures that stop_token signals that stop has been requested before destruction of conditional_variable.
Should close #7992.

backend: Ensure backend_thread is destructed before message_queue

---

CMakeLists.txt

This change fixes a cmake error while trying to prepare a build on linux (Linux Mint 20.2) using the bundled Qt5:
```
CMake Error at src/yuzu/CMakeLists.txt:14 (add_executable):
Target "yuzu" links to target "Qt5::DBus" but the target was not found.
Perhaps a find_package() call is missing for an IMPORTED target, or an
ALIAS target is missing?
```

build(cmake): fix missing Qt5::DBus target on linux

---

src/common/telemetry.cpp
src/common/telemetry.h
src/common/x64/cpu_detect.cpp
src/common/x64/cpu_detect.h
src/yuzu/main.cpp

Adds detection of additional CPU flags to cpu_detect and additions to telemetry output.
This is not exhaustive but guided by features that [dynarmic utilizes](https://github.com/merryhime/dynarmic/blob/bcfe377aaa5138af740e90af5be7a7dff7b62a52/src/dynarmic/backend/x64/host_feature.h#L12-L33) as well as features that are currently utilized but not reported to telemetry(invariant_tsc). This is intended to guide future optimizations.
AVX512 in particular is broken up into its individual subsets and some other processor features such as [sha](https://en.wikipedia.org/wiki/Intel_SHA_extensions) and [gfni](https://en.wikipedia.org/wiki/AVX-512#GFNI) are added to have some forward-facing data-points.
What used to be a single `CPU_Extension_x64_AVX512` telemetry field
is also broken up into …

cpu_detect: Add additional x86 flags and telemetry

---

src/shader_recompiler/backend/spirv/emit_spirv.h
src/video_core/renderer_vulkan/vk_compute_pass.cpp

Resolves the following two compilation errors:
```
emit_spirv.h: 'Shader::Backend::SPIRV::RescalingLayout': structure was padded due to alignment specifier
vk_compute_pass.cpp: use of undefined type `std::array`
```

emit_spirv, vk_compute_pass: Resolve VS2022 compiler errors

---

src/shader_recompiler/frontend/maxwell/translate_program.cpp
src/shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp

as requested by xerpi. This fixes an small bug on tracking global mem in deko3d's shaders that use use nouveau's compiler.

Shader decompiler: Fix storage tracking in deko3d.

---

src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_3d.h
src/video_core/renderer_vulkan/vk_texture_cache.cpp

This allows Galaxy and Sunshine to render and not just be completely black.
Unresolved issues:
- Mario's body and many scene elements do not appear yet (see Ryujinx/Ryujinx#1608)
- Both games absolutely chug and seem to be much slower than they really should be

Initial support for Wii Hagi emulator

---

src/yuzu_cmd/default_ini.h

yuzu-cmd already reads the setting from 70482e6b26, this just puts the setting in the default ini.

default_ini: List use_extended_memory_layout in default config file

---

src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_3d.h

This makes constant buffer uploads safer and more accurate by updating the GPU memory as soon as the CB Data method is invoked. The previous implementation was deferring the updates until a different maxwell 3d method was detected, then writing all CB data at once.
This fixes the geometry pop-in in `Kirby and the Forgotten Land`, graphical corruptions in `Monster Hunter Rise` and `Diablo II`, and likely other titles with long-standing graphical issues.

maxwell_3d: Implement a safer CB data upload

---

src/core/CMakeLists.txt
src/core/frontend/applets/mii.cpp
src/core/frontend/applets/mii.h
src/core/hle/service/am/applets/applet_mii.cpp
src/core/hle/service/am/applets/applet_mii.h
src/core/hle/service/am/applets/applets.cpp
src/core/hle/service/am/applets/applets.h
src/yuzu/main.cpp

Pretty simple implementation that allows to create a default mii. Currently this applet has no UI so editing the mii is imposible at this point. I'm only making this PR to make Miitopia playable without a save file while I work on the UI part.

applet: mii: Simple implementation of mii applet

---

src/video_core/host_shaders/CMakeLists.txt
src/video_core/host_shaders/convert_s8d24_to_abgr8.frag
src/video_core/renderer_vulkan/blit_image.cpp
src/video_core/renderer_vulkan/blit_image.h
src/video_core/renderer_vulkan/vk_texture_cache.cpp

Galaxy reads back a combined depth and stencil buffer from the GPU to determine the object underneath the star pointer. Fixes the initial implementation in #8000, which was wrong.
https://user-images.githubusercontent.com/9658600/158484032-f81ea05b-73fa-4552-b24c-a09256dd4c61.mp4
https://user-images.githubusercontent.com/9658600/158484049-2ac9325c-891c-4f8d-b703-02329d3844e2.mp4

Vulkan: convert S8D24 <-> ABGR8

---

src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
src/shader_recompiler/backend/spirv/spirv_emit_context.h
src/shader_recompiler/frontend/maxwell/translate/impl/load_constant.cpp
src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
src/shader_recompiler/shader_info.h

This implements SPIR-V shader support for register-addressed const buffer accesses.
Assumptions:
- LDC can access any const buffer
- LDC can access anywhere in the buffer
The implementation idea is to create a jumptable with each possible const buffer index and use its entries to fill the load destination. In GLSL it would look like something like this:
```glsl
uniform float cb0[0x10000];
uniform float cb1[0x10000];
uniform float cb2[0x10000];
uniform float cb3[0x10000];
// ...
{
float result;
switch (cb_index) {
case 0: result = cb0[cb_offset]; break;
case 1: result = cb1[cb_offset]; break;
case 2: result = cb2[cb_offset]; break;
case 3: result = cb3[cb_offset]; break;
// ...
}
}
```
This is significantly less invasive than other potential approaches like flattening all uniform inputs. …

Add shader support for const buffer indirect addressing

---

src/core/CMakeLists.txt
src/core/hle/kernel/k_page_buffer.cpp
src/core/hle/kernel/k_page_buffer.h
src/core/hle/kernel/k_thread_local_page.cpp
src/video_core/fence_manager.h
src/video_core/query_cache.h
src/video_core/renderer_opengl/gl_state_tracker.h
src/video_core/renderer_vulkan/vk_state_tracker.h

This reduces the dependency on `core.h` in some common header files to reduce some compile time churn.

general: Reduce core.h includes

---

src/core/hle/service/sockets/bsd.cpp

Should fix https://github.com/yuzu-emu/yuzu/issues/7993. Minecraft passes in zero for length, but this should account for all possible cases.
Not hardware-verified, so that would be appreciated.

bsd: Allow inexact match for address length in AcceptImpl

---

src/yuzu_cmd/config.cpp
src/yuzu_cmd/config.h
src/yuzu_cmd/yuzu.cpp

Adds an option `-c` or `--config` with one required argument that allows the user to specify to where the config file is located. Useful for scripts that run specific games with different preferences for settings.

yuzu_cmd: Allow user to specify config file location

---

.ci/templates/build-msvc.yml

#7697 introduced a CMake option to disable building tests for reduced build times.
It should be safe to disable building tests in `build-msvc`, which is only used for the Mainline and EA build bots.

.ci/build-msvc: Disable YUZU_TESTS cmake variable

---

src/core/hle/kernel/k_handle_table.cpp
src/core/hle/kernel/k_handle_table.h

Since the handle type is not being used, we can reduce the amount of space each entry takes up by 4 bytes.

KHandleTable: Optimize table entry layout

---

src/video_core/texture_cache/texture_cache.h

Amends an accidental bitwise OR with a logical OR.
This PR also adds another change where copy extents wouldn't have any scaling applied to them, since they weren't being iterated by reference, effectively making the loop dead-code. Looking into `CopyImage()` however, it seems it would apply the scaling if necessary anyways, making the code unnecessary (though, if my assumption is wrong, feel free to correct me).

texture_cache: Amend unintended bitwise OR in SynchronizeAliases

---

src/video_core/renderer_vulkan/vk_texture_cache.cpp

Fixes star pointer interactions in `Super Mario Galaxy` on some drivers, notably Nvidia.

vk_texture_cache: Do not reinterpret DepthStencil source images

---

src/video_core/buffer_cache/buffer_cache.h

This avoids doubling the buffer but instead increase it only where it's needed.
t should reduce the memory used in PLA.

BufferCache: Find direction of the stream buffer increase.

---

src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_debug.cpp
src/yuzu/configuration/configure_debug.ui
src/yuzu/main.cpp
src/yuzu/main.h
src/yuzu/uisettings.h

The web applet causes issues with the rest of the application. See #5973, #5044, and #5043. Additionally, crashes are reported, but I didn't find any documentation to link here.
Make the option save with the application, disable it by default, and add a debug option to re-enable it until a proper solution can be found.

yuzu qt: Disable the web applet by default

---

src/shader_recompiler/frontend/ir/microinstruction.cpp
src/shader_recompiler/frontend/ir/value.h
src/shader_recompiler/ir_opt/dead_code_elimination_pass.cpp

This adds a pass to eliminate `if(false) {...}` branches within the shader code.
This change is mainly to alleviate dead condition blocks from appearing in shader code during debug inspection. 
But may potentially improve shader code size and/or compilation time.

shader_recompiler/dead_code_elimination: Add DeadBranchElimination pass

---

src/video_core/buffer_cache/buffer_cache.h
src/video_core/renderer_opengl/gl_buffer_cache.cpp
src/video_core/renderer_opengl/gl_buffer_cache.h
src/video_core/renderer_opengl/gl_device.cpp
src/video_core/renderer_opengl/gl_device.h
src/video_core/renderer_opengl/gl_texture_cache.cpp
src/video_core/renderer_opengl/gl_texture_cache.h
src/video_core/renderer_vulkan/vk_buffer_cache.cpp
src/video_core/renderer_vulkan/vk_buffer_cache.h
src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
src/video_core/renderer_vulkan/vk_texture_cache.cpp
src/video_core/renderer_vulkan/vk_texture_cache.h
src/video_core/texture_cache/image_base.h
src/video_core/texture_cache/texture_cache.h
src/video_core/texture_cache/texture_cache_base.h
src/video_core/vulkan_common/vulkan_device.cpp
src/video_core/vulkan_common/vulkan_device.h
src/video_core/vulkan_common/vulkan_memory_allocator.cpp
src/video_core/vulkan_common/vulkan_wrapper.cpp
src/video_core/vulkan_common/vulkan_wrapper.h

This PR adds a few fixes to GC from project YFC as well as a bunch of improvements.
Improvements:
- Rebalance minimum, expected and critical thresholds to be more fair for GPUs with a lot of memory while keeping it great for low memory GPUs.
- Add GPU Memory Usage querying for Vulkan on AMD, NVIDIA & Intel and OGL for NVIDIA. This means that instead of estimating memory usage, we'll use the correct amount to make better decisions on when to clean memory.
- Improved Memory Cleaning & Estimation on iGPUs.
- Made ASTC and converted formats less easier to clean. (Thanks to @sayanns2 for figuring it that out).
- Tuned cleaning aggressiveness accordingly.
This feature used to be part of Project YFC but since it has been brought to my attention that the GC issues are very heavy right now. I have …

First Nugget: Reworked Garbage Collection to be smarter [originally from Project YFC]

---

src/core/memory.cpp
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_vulkan/vk_rasterizer.cpp
src/video_core/texture_cache/image_base.h
src/video_core/texture_cache/texture_cache.h
src/video_core/texture_cache/texture_cache_base.h

Additionally, make sure to not protect read memory on Normal / High accuracy (it was High only before)

Memory GPU <-> CPU: reduce infighting in the texture cache by adding CPU Cached memory.

---

src/core/hle/service/am/applets/applet_software_keyboard.cpp
src/core/hle/service/am/applets/applet_software_keyboard.h
src/core/hle/service/am/applets/applet_software_keyboard_types.h

New firmware versions have an updated version of the inline software keyboard, and the struct used to initialize it has been updated with re-arranged fields. This PR adds support for this updated inline software keyboard and allows for the software keyboard to appear in updated *Monster Hunter* series games (MHGU, MHR, etc)
Apologies for the diff in advance, this was code from close to a year ago that I hadn't had time to properly clean up.
Special thanks to @BSoDGamingYT for making me look at this again 😛 
Fixes #7249

applets/swkbd: Add support for an updated inline software keyboard

---

src/core/memory.cpp
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_vulkan/vk_rasterizer.cpp
src/video_core/texture_cache/image_base.h
src/video_core/texture_cache/texture_cache.h
src/video_core/texture_cache/texture_cache_base.h

Reverts yuzu-emu/yuzu#8080
Causes graphical issues in SMO, and kills performance in Pokemon Sword/Shield with Extreme GPU accuracy. @FernandoS27 to address.

Revert "Memory GPU <-> CPU: reduce infighting in the texture cache by adding CPU Cached memory."

---

src/shader_recompiler/backend/spirv/emit_spirv_atomic.cpp
src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
src/shader_recompiler/backend/spirv/spirv_emit_context.cpp

Needed for compilation with older libc++ releases

shader_recompiler: Include <bit> header when std::count{r,l}_zero is used

---

src/core/arm/dynarmic/arm_dynarmic_64.cpp

Multicore, huh. Closes #8096.
Likely fixes code memory related invalidation issues.

dynarmic: Invalidate CPU cache on all cores

---

src/video_core/renderer_opengl/gl_rasterizer.cpp

When GPU accuracy is set to Extreme, `gpu.TickWork()` will lock the texture_cache and buffer_cache mutexes, which are owned by the thread prior to invoking `TickWork()`.
Defer invoking `gpu.TickWork()` until after the scope ends and the owned mutexes are released.

gl_rasterizer: Avoid scenario locking already owned mutex

---

src/yuzu/main.cpp

Previously the fullscreen setting was always overriden at boot. This PR only overrides the setting if gamepath or argument -f  is provided. This way simple shortcuts will keep the previous configuration.

yuzu: Only override fullscreen setting if gamepath or argument is provided

---

src/core/hle/kernel/k_code_memory.cpp
src/core/hle/kernel/k_page_linked_list.h
src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/svc.cpp

This is a continuation of my work to bring our kernel memory management up to speed with recent system updates and the latest known information (see previous PRs #8013, https://github.com/yuzu-emu/yuzu/pull/7974, https://github.com/yuzu-emu/yuzu/pull/7956, https://github.com/yuzu-emu/yuzu/pull/7701, https://github.com/yuzu-emu/yuzu/pull/7698, and https://github.com/yuzu-emu/yuzu/pull/7684 for a history of this effort).
With this change, we:
* Fix implementations of LockForCodeMemory & UnlockForCodeMemory.
* Fix MapProcessMemory bug where we were mapping onto virtual address space.
* Fix KCodeMemoryBug where we were addressing physical memory with a virtual address.
* Fix a bad alignment check in UnmapProcessCodeMemory.
* Various cleanup & smaller improvements.
The goal with this batch of …

Kernel Memory Updates (Part 7): Various fixes to code memory (Skyline support)

---

src/core/hle/service/hid/hid.cpp

Took me a while to find the cause but I finally discovered the issue. Fixes random controller disconnects on flipwars originally  reported on kraken #7255

service: hid: Signal event on AcquireNpadStyleSetUpdateEventHandle

---

src/video_core/renderer_vulkan/blit_image.cpp
src/video_core/renderer_vulkan/vk_texture_cache.cpp
src/video_core/vulkan_common/vulkan_device.cpp

NVIDIA Vulkan drivers 510+ crash when blitting MSAA images. Fall-back to 3D scale helpers for MSAA image scaling on these drivers.
Fixes crashes when scaling was enabled on titles such as `Monster Hunter Rise`, `Rune Factory 5`, `Sonic Colors Ultimate`, among others.

Vulkan: Use 3D helpers for MSAA scaling on NV drivers 510+

---

src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp

Fixes an svc break in `Kirby and the Forgotten Land` with async GPU enabled.

nvhost_ctrl: Only mark EventState::Busy as BadParameter

---

src/video_core/command_classes/codecs/codec.cpp

It was reported that decoders with the `HW_FRAMES_CTX` config  method causes crashes on certain Linux decoding backends, hence the check to avoid it. This check subsequently caused Windows GPU decoders to never be selected and always fall back to CPU decoding. 
This PR disables `HW_FRAMES_CTX` config check on Windows for now.
This PR also addresses a memory leak relating to the allocation of GPU decoder contexts for the desired decoders which was not being freed.

codec: Fix GPU decoder detection on Windows and a memory leak

---

src/yuzu/configuration/configure_per_game_addons.cpp

This provides more sensible column widths.

configure_per_game_addons: Stretch first column and not last

---

src/yuzu/configuration/configure_hotkeys.cpp

Also configure minimum width of columns to be 150px.
Makes for more sensible column widths.

configure_hotkeys: Make first column stretch and not last column

---

src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/npad.h
src/core/hle/service/hid/hid.cpp

Another game that made my head scratch for a while was bombslinger. This game had no input at all. After playing with homebrew I noticed no controller is really connected until we call `SetSupportedStyleSet`. Doing this simple change makes the game work flawlessly.
Homebrew does call the commands properly so I removed the workarounds as well.
fixes #7475

service: hid: Remove inaccurate behavior on initialization

---

src/core/hle/service/am/applets/applet_web_browser.cpp

This is a hack to keep the foreground (websession) web applet open in games using these such as Super Mario 3D All-Stars.

applets/web: Keep foreground (websession) web applet open

---

src/common/atomic_ops.h
src/common/x64/native_clock.cpp

We implement an atomic 128-bit load using `cmpxchg16b`. (This is the only guaranteed way to have an atomic 128-bit load; `movaps` is not guaranteed to be atomic.)
We use this in `native_clock` to fix an issue with the `time_point` read not being atomic.

native_clock: Use AtomicLoad128

---

src/common/settings.h
src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_64.cpp
src/yuzu/configuration/configure_cpu.ui

Disables most optimizations for the paranoid. Notably this does **not** disable fastmem and memory related opts (because doing so would be absolutely killer). Intended for users to be able to self-diagnose and report issues with CPU optimizations. If this option fixes issues that should be reported as a bug.
While we're here also ensure that when cpu debug mode is enabled, list of opts don't get fiddled with afterwards.
There is probably something around `USE_GLOBAL_OFFSET` I'm not understanding here, pls check.

configuration: Add Paranoid CPU accuracy level

---

src/video_core/texture_cache/util.cpp

This call is reading GPU memory into the dst buffer, which is then overwritten by the SwizzleTexture call on the next line.

texture_cache/util: Remove unneeded ReadBlockUnsafe

---

src/video_core/texture_cache/util.cpp

Reverts yuzu-emu/yuzu#8154
Per @FernandoS27's comment on the other PR, @ameerj as FYI

Revert "texture_cache/util: Remove unneeded ReadBlockUnsafe"

---

src/CMakeLists.txt

It was needed on GCC versions not supporting `-std=c++20`, but GCC 10 and newer (required to compile yuzu) don't need it anymore
Edit: added in https://github.com/yuzu-emu/yuzu/commit/dd2ff236217cb02275cbfa66f50c265a578d1f1e, CC: @lioncash

build: remove -fconcepts

---

src/core/file_sys/registered_cache.cpp

For whatever reason, nca_file/dir can be nullptr in the list of files/dirs. I have not determined the cause of this yet, so add a nullptr check for these prior to dereferencing them.
This prevents a crash on boot on some configurations.

registered_cache: Prevent nullptr dereference when accumulating files

---

src/core/hle/service/hid/hid.cpp

Fixes random input issues introduced in #8123 by adding the hack back. Fixes input issues with DOOM, Dark Souls remastered  and Dragon quest builders 2. 
Closes #8155

service: hid: Partially revert #8123

---

src/core/hle/kernel/hle_ipc.cpp
src/core/hle/kernel/hle_ipc.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/kernel.h
src/core/hle/service/audio/audout_u.cpp
src/core/hle/service/audio/audren_u.cpp
src/core/hle/service/filesystem/fsp_srv.cpp
src/core/hle/service/nvdrv/nvdrv_interface.cpp
src/core/hle/service/service.cpp
src/core/hle/service/service.h
src/core/hle/service/sm/sm.cpp
src/core/hle/service/sockets/bsd.cpp
src/core/hle/service/vi/vi.cpp

Previously, we would allocate a host thread for every HLE service interface. This was necessary because some service routines need to block, and we not support guest rescheduling from HLE host threads. This could result in dozens of host threads being created for services, which may result in weird behavior, especially on systems that have more constrained resources.
With this change, we introduce a single "default service thread" that is used for the 99% of service methods that are non-blocking. For more time-sensitive or blocking services, we still allow a thread to be created (e.g., audio, FS, nvdrv, BSD).
This should reduce service threads from ~25-50 down to ~4. The goal of this change is to improve stability and consistency, especially across systems with lower core counts. Ideally, …

Improve usage of service host threads

---

src/common/logging/filter.cpp
src/common/logging/types.h
src/core/CMakeLists.txt
src/core/hle/service/am/am.cpp
src/core/hle/service/am/am.h
src/core/hle/service/jit/jit.cpp
src/core/hle/service/jit/jit.h
src/core/hle/service/service.cpp

This doesn't do anything interesting yet, this just stubs the relevant functionality.
- `IApplicationFunctions`: `PrepareForJit`
- `jit:u`: `CreateJitEnvironment`
- `IJitEnvironment`: `GenerateCode`, `Control`, `LoadPlugin`, `GetCodeAddress`

service: jit: stub JIT service

---

src/shader_recompiler/backend/glsl/emit_glsl_context_get_set.cpp
src/shader_recompiler/backend/glsl/glsl_emit_context.cpp
src/shader_recompiler/backend/glsl/glsl_emit_context.h
src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
src/shader_recompiler/shader_info.h

This allows Mario's body to render in Sunshine using OpenGL GLSL and SPIR-V (no GLASM support for now). Note that due to current issues with the OpenGL renderer, which polygons are considered front facing is flipped, and so only back faces are rendered.

shader_recompiler: support const buffer indirect addressing on OpenGL

---

src/common/x64/native_clock.cpp

**Why lfence before rdtsc?**
mfence is not guaranteed by Intel to serialize the instruction stream, whereas lfence is, therefore lfence is the correct choice here. It's also more lightweight.
**Why lfence after rdtsc?**
rdtsc is not a serialising instruction, therefore instructions after it may be reordered to execute before it. [The manual actually explicitly mentions all of this](https://www.felixcloutier.com/x86/rdtsc), asking you to execute lfence after rdtsc(p) if correct ordering is required.
**Why is _ReadWriteBarrier required?**
lfence is a CPU-level fence, and does not necessarily disable compiler optimizations that may reorder instructions at compile time. A compiler barrier is required. (_ReadWriteBarrier does not emit any instructions.)
**Why is inline assembly required for …

native_clock: Use lfence with rdtsc

---

src/video_core/renderer_vulkan/vk_blit_screen.cpp

This hides the black bar at the bottom of Sunshine.
|Before|After|
|-|-|
|![010049900f546002_2022-04-04_11-46-38-078](https://user-images.githubusercontent.com/9658600/161582073-07ecf671-dfb7-439b-8bab-19ce7de1f79a.png)|![010049900f546002_2022-04-04_11-45-57-390](https://user-images.githubusercontent.com/9658600/161582103-07600287-5bb9-421a-9564-52692ff076a1.png)|

Vulkan: crop to screen dimensions if crop not explicitly requested

---

src/common/host_memory.cpp
src/common/thread.h
src/common/threadsafe_queue.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/time_manager.cpp
src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/nvflinger/buffer_item_consumer.cpp
src/core/hle/service/nvflinger/buffer_queue_consumer.cpp
src/core/hle/service/nvflinger/buffer_queue_core.cpp
src/core/hle/service/nvflinger/buffer_queue_producer.cpp
src/core/hle/service/nvflinger/consumer_base.cpp
src/core/hle/service/nvflinger/hos_binder_driver_server.cpp
src/core/perf_stats.cpp
src/core/tools/freezer.cpp
src/input_common/drivers/sdl_driver.cpp
src/input_common/input_engine.cpp
src/video_core/gpu.cpp
src/video_core/gpu_thread.cpp
src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_vulkan/pipeline_statistics.cpp
src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
src/video_core/renderer_vulkan/vk_render_pass_cache.cpp
src/video_core/renderer_vulkan/vk_scheduler.cpp
src/video_core/shader_cache.cpp
src/web_service/web_backend.cpp
src/yuzu/util/controller_navigation.cpp

Code cleanup and standardization, no change to emulation.
Standardize on one RAII type; use the more modern one (C++17). Doesn't really make much sense to still use std::lock_guard when we simultaneously have code using std::scoped_lock.
idk

Replace lock_guard with scoped_lock

---

src/video_core/renderer_opengl/gl_rasterizer.cpp

With #8133, this allows Sunshine and Galaxy to render correctly on OpenGL GLSL and SPIR-V backends.
- Sunshine is more or less full speed on OpenGL and playable, aside from some areas like Pinna Park which have slowdowns.
- Galaxy is extremely slow on OpenGL and cannot be progressed due to missing depth buffer translation (see #8030). Users should prefer Vulkan for this title.
|Before|After|
|------|-----|
|![010049900f546002_2022-04-01_18-20-13-192](https://user-images.githubusercontent.com/9658600/161562609-30e6116a-e3b9-4621-9485-9b8291cae373.png)|![010049900f546002_2022-04-04_10-06-38-453](https://user-images.githubusercontent.com/9658600/161562628-5a520ee4-0533-4f70-b00c-b31a8fbb086b.png)|
|![010049900f546003_2022-04-04_10-10-35-436](https://user-images.githubusercontent.com/9658600/1 …

OpenGL: flip front faces if Z scale is inverted

---

src/core/file_sys/patch_manager.cpp
src/core/hle/service/sockets/bsd.cpp
src/core/hle/service/sockets/sfdnsres.cpp
src/core/hle/service/sockets/sfdnsres.h
src/core/hle/service/sockets/sockets.h
src/core/network/network.cpp
src/core/network/sockets.h

- Allows loading LayeredExeFs patches from `sdmc:/atmosphere/contents/titleid/exefs`
- Makes mod distribution easier since users can just copy the `atmosphere` folder to the SD card root like on hardware
- Required for self-updating Skyline plugins that assume that `subsdk9` is writable in this directory
- Adds support for the `SO_KEEPALIVE` socket option
- Used by the Skyline TCP logger (attaching the logger still crashes Yuzu though)
- Implements DNS address resolution in the `sfdnsres` service (`GetAddrInfoRequest` is now functional and `GetAddrInfoRequestWithOptions` was added)
- Required for Skyline plugins that use HTTP requests (but requests still seem to get stuck after the DNS resolution)

Improvements for game modding with Skyline, DNS resolution

---

src/core/hle/service/sockets/sfdnsres.cpp

Regressed by #8171 (82d46a974ad4). See https://github.com/freebsd/freebsd-src/commit/37b3e941672a + https://github.com/freebsd/freebsd-src/commit/27f9f4194284. Affects DragonFly and FreeBSD but not NetBSD and OpenBSD.
```c++
src/core/hle/service/sockets/sfdnsres.cpp: In function 'Service::Sockets::NetDbError Service::Sockets::AddrInfoErrorToNetDbError(s32)':
src/core/hle/service/sockets/sfdnsres.cpp:66:10: error: 'EAI_NODATA' was not declared in this scope; did you mean 'EAI_NONAME'?
66 |     case EAI_NODATA:
|          ^~~~~~~~~~
|          EAI_NONAME
src/core/hle/service/sockets/sfdnsres.cpp: In function 'std::vector<unsigned char> Service::Sockets::SerializeAddrInfo(const addrinfo*, s32, std::string_view)':
src/core/hle/service/sockets/sfdnsres.cpp:127:53: error: 'sockaddr_in' does not …
```

service: sfdnsres: unbreak build on FreeBSD

---

src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
src/core/hle/kernel/k_auto_object.h
src/core/hle/kernel/k_process.h
src/core/hle/kernel/k_scheduler_lock.h
src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/k_thread.h
src/core/hle/kernel/kernel.cpp

Used [ThreadSanitizer](https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual) on yuzu and found a few races. This just fix the ones that yuzu-cmd encounters in `core/hle/kernel` while booting [es2gears](https://github.com/switchbrew/switch-examples/tree/master/graphics/opengl/es2gears), minus a `Kernel::SessionRequestManager` one that I'm not sure how to fix.

kernel: Fix some data races

---

src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/svc.cpp
src/core/hle/service/ldr/ldr.cpp

Thanks to @bunnei for figuring this out!
- Adds icache invalidation to `UnmapProcessMemory`
- Forces invalidation of the entire icache in `UnmapCodeMemory`
- icache invalidation is still constrained to a range when unloading NROs to avoid potential performance regressions in Super Smash Bros. Ultimate
Fixes #8174

hle: kernel: Invalidate entire icache in UnmapProcessMemory and UnmapCodeMemory (fixes #8174)

---

src/core/hle/kernel/hle_ipc.cpp
src/core/hle/kernel/k_auto_object.h
src/core/hle/kernel/k_server_port.cpp
src/core/hle/kernel/k_server_session.cpp
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/kernel.h
src/core/hle/service/sm/sm.cpp
src/core/hle/service/sm/sm.h

Since we do not emulate multi-process, these need to me managed somewhere. This adds a single place where we can register/unregister open ports and sessions, and ensure they are closed when we tear down all services and the kernel. This fixes a regression introduced by #8005, as that removed KServerSession tracking, which resulted in services not getting their dtor called. 
We still had such code in place for KServerPort. But instead of keeping the duplication, we have a single place for all KServer* tracking now.
Supersedes #8136 and #8108.

Kernel: Track open references to KServerPort and KServerSession.

---

src/core/CMakeLists.txt
src/core/hle/kernel/k_code_memory.cpp
src/core/hle/service/jit/jit.cpp
src/core/hle/service/jit/jit_context.cpp
src/core/hle/service/jit/jit_context.h

Allows Super Mario 64 (Super Mario 3D All-Stars) to boot and run. (It does not render yet, due to likely unrelated GPU issues.)
Implementation notes:
- This is HLE. This does not use the firmware service and integrates easily into the existing single-process architecture.
- The loaded plugin is heavily restricted. Per the system security requirements implemented by `ldr:ro` in firmware, it cannot import any ELF symbols. It also is not allowed to make service calls as this would potentially compromise the integrity of the JIT service. This means we can relocate and run it in a completely isolated context.
- Using an isolated context is also helpful for the plugin because making space for it in guest memory would be difficult. The existing helpers to allocate and map memory within existing …

service: jit: Implement the JIT service

---

src/yuzu_cmd/emu_window/emu_window_sdl2.cpp

Since SDL2 does not automatically resize the canvas when entering fullscreen mode, currently we resize the window to whichever native Switch display resolution we are using depending on the docked mode. Instead, resize the window to desktop display dimensions. This allows the different scaling filters as well as resolution scaling effects to appear to work properly in exclusive fullscreen.

emu_window_sdl2: Set window size to display dimensions for exclusive fullscreen

---

src/yuzu/main.cpp
src/yuzu/uisettings.cpp
src/yuzu/uisettings.h

Long story short, QT doesn't allow the link colors to be set via their stylesheets.
There are two ways to work with this, specify the color manually for every link (See the About dialog) The other way is to change the default palette.
IsDarkTheme is copy/pasted from src/yuzu/debugger/wait_tree.cpp
I considered setting the link color to be the same light blue as in the license dialog, but with a bit of testing I found that it wasn't a good fit. I lightened it for the dark theme, and darkened it for the light theme. 
Before
After

ui: Set Link Color when setting theme

---

src/common/fiber.cpp
src/core/core_timing.h
src/core/hle/kernel/global_scheduler_context.h
src/core/hle/kernel/k_scheduler.cpp
src/core/hle/kernel/k_spin_lock.cpp
src/core/hle/kernel/k_spin_lock.h
src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/k_thread.h
src/core/hle/kernel/physical_core.cpp
src/core/hle/kernel/physical_core.h
src/core/hle/service/ldr/ldr.cpp
src/core/hle/service/service.h

This is an experimental change to see if using host mutexes over our own spin-lock implementation improves how the emulator runs, particularly on systems with low core counts. Preliminary testing has shown that this makes emulator much more usable on 4T systems. Marking as do-not-merge for now until we get broader testing.
Credits to @FernandoS27 for the idea.
We still use spinlocks for thread context guards, as for some reason this appears to be very sensitive to timing changes. I'm still investigating the root problem here.

hle: kernel: Use std::mutex instead of spin locks for most kernel locking.

---

src/video_core/buffer_cache/buffer_cache.h
src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_3d.h
src/video_core/renderer_opengl/gl_texture_cache.cpp
src/video_core/renderer_opengl/maxwell_to_gl.h
src/video_core/renderer_vulkan/maxwell_to_vk.cpp
src/video_core/renderer_vulkan/vk_texture_cache.cpp
src/video_core/surface.h
src/video_core/texture_cache/format_lookup_table.cpp
src/video_core/texture_cache/formatter.h
src/video_core/vulkan_common/vulkan_device.cpp

Follow up to #8000 and #8199 
This allows Super Mario 64 (Super Mario 3D All-Stars) to render, albeit at an unplayably slow framerate (due to slow texture swizzles).

Fixes for Mario 64

---

src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_32.h
src/core/arm/dynarmic/arm_dynarmic_64.cpp
src/core/arm/dynarmic/arm_dynarmic_64.h

Addresses #8185.
Zero performance impact. (`std::atomic::load` is free.)
A proper fix would be to make it a core-option but that's awaiting refactor.

dynarmic: Fix race when switching page tables

---

src/common/settings.h
src/common/settings_input.h
src/core/CMakeLists.txt
src/core/hid/emulated_devices.cpp
src/core/hid/emulated_devices.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/kernel.h
src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hidbus.cpp
src/core/hle/service/hid/hidbus.h
src/core/hle/service/hid/hidbus/hidbus_base.cpp
src/core/hle/service/hid/hidbus/hidbus_base.h
src/core/hle/service/hid/hidbus/ringcon.cpp
src/core/hle/service/hid/hidbus/ringcon.h
src/core/hle/service/hid/hidbus/starlink.cpp
src/core/hle/service/hid/hidbus/starlink.h
src/core/hle/service/hid/hidbus/stubbed.cpp
src/core/hle/service/hid/hidbus/stubbed.h
src/yuzu/CMakeLists.txt
src/yuzu/configuration/config.cpp
src/yuzu/configuration/config.h
src/yuzu/configuration/configure_input.cpp
src/yuzu/configuration/configure_input_advanced.cpp
src/yuzu/configuration/configure_input_advanced.h
src/yuzu/configuration/configure_input_advanced.ui
src/yuzu/configuration/configure_input_player.cpp
src/yuzu/configuration/configure_ringcon.cpp
src/yuzu/configuration/configure_ringcon.h
src/yuzu/configuration/configure_ringcon.ui

Implements the minimum necessary to get a Ring Controller working. This was intended to fix Ring Fit Adventure but seems like the game has other issues independent of the ringcon support.
It lacks support for any other hidbus device or any configuration. Implementation will be improved when a game that actually uses this service exist and works.
Note: Starlink: Battle for Atlas is not supported. Thanks to gidoly for helping with HW testing.
Update: Game now boots and detects the ring controller without errors.  It's softlocking when trying to save the calibration config to the ringcon. The issue is know I need to reply correctly to this command.
Update: Game now is fully working with no softlocks related to the controller. SVC breaks at the end of any level possibly gpu related.
Closes …

hidbus: Implement hidbus and ringcon

---

src/yuzu/compatdb.ui
src/yuzu/configuration/configure_dialog.cpp
src/yuzu/game_list_p.h

Reported by GillianMC on Discord.  Translations of the states, such as "Perfect" and "Bad" are done, but not used.
Looks to be a small quirk in the QT API.
Technical detail
setText(QObject::tr(status.text));
bringing up QObject broke the connection to the GameListItemCompat class.
Also related, certain strings are duplicated in translation, which can confuse translators. 
QT_TR_NOOP("Perfect") -> QT_TRANSLATE_NOOP("CompatDB", "Perfect")
If you're wondering about "Not Tested" being left alone, its not possible to submit a compatibility report stating that you didn't test the game.
Also I thought removing the space from `Great` in src/yuzu/compatdb.ui would disconnect the translation but things are still Gut

ui: Fix Game Compatibility list translations

---

src/yuzu/main.cpp
src/yuzu/main.h

If the mouse DPI is high enough or the rendering window size is small enough the mouse cursor can leave the window, which can cause some annoying behavior, just in case a workaround for that issue.

a workaround if the mouse cursor leaves the rendering window in panning mode

---

src/yuzu/configuration/configure_input_player.cpp

988 Yuzu UI set to Russian
Removing QObject:: would move the translation to ConfigureInputPlayer context, but that context is a bit busy, so I'm leaning towards not touching it.
In Russian, the last letter gets cut off for the word right.

ui: translate hat directions

---

src/input_common/helpers/udp_protocol.h

Addresses one of the issues of #8010

input_common: Ignore boost uninitialized local variable

---

src/core/arm/arm_interface.cpp
src/core/arm/arm_interface.h
src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_32.h
src/core/arm/dynarmic/arm_dynarmic_64.cpp
src/core/arm/dynarmic/arm_dynarmic_64.h

A32 and A64 contexts have completely different registers and thus a mechanism for collecting stack traces must necessarily be exclusive to one context or the other.

core/arm: separate backtrace collection

---

src/video_core/renderer_base.cpp
src/video_core/renderer_base.h
src/yuzu/bootmanager.cpp

It's posible to make yuzu crash if on the loading splash screen you spam the screenshot button.  This was due to the callback being destroyed before it was able to reply. To avoid this issue we avoid requesting a screenshot at all if the backend is not ready

bootmanager: Don't create another screenshot request if previous one is not done yet

---

src/core/hid/hid_types.h
src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/npad.h
src/core/hle/service/hid/errors.h
src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h

The following fixes are obtained from unit test on HW and RE from each sixaxis function. This is the first batch of many PR aiming to solve yuzu inaccuracies on the HID side. Hopefully some games will be fixed.
Implements `IsSixAxisSensorFusionEnabled` verified on homebrew.

service: hid: Improve accuracy of sixaxis functions

---

src/input_common/drivers/gc_adapter.cpp
src/input_common/drivers/gc_adapter.h
src/input_common/drivers/sdl_driver.cpp
src/input_common/drivers/sdl_driver.h
src/input_common/drivers/udp_client.cpp
src/input_common/drivers/udp_client.h
src/input_common/input_engine.h
src/input_common/main.cpp
src/input_common/main.h
src/yuzu/configuration/configure_input_player.cpp

Some people like to use single joycons and not turning their xbox controller sideways. Originally trying to manually map a controller in this configuration resulted in inverted axis that had some extra steps to get it working properly.
This PR adds the necessary logic to correct the axis direction to ensure it always goes to where you want it to go.
solves #7412

input_common: Map sticks correctly when mapped sideways

---

src/core/loader/loader.cpp

This change additionally logs the deduced type of a mismatching type/file-extension combination.
For instance loading a ```my_cool.xci``` that is actually a NSP type will log out:
```[   0.148175] Loader <Warning> core/loader/loader.cpp:GetLoader:264: my_cool.xci has a different type (NSP) than its extension.```

loader: log the type of mismatching file-extension

---

CMakeLists.txt

The premise behind ad55faaa3 was due to an issue between Conan's libiconv package and compiling SDL2 from our externals. Since none of our Conan externals require libiconv any longer, though, we can remove downloading our own Boost package and just rely on Conan again.
Additionally, removing CONFIG from the find_package(boost) call fixes issues with finding Boost on Fedora and MSYS2, which was the main motivation for this. (Revert 697a2c001)
Also, remove QUIET since if something goes wrong finding Boost, this makes it harder to tell what went wrong.

CMakeLists: Revert ad55faaa3

---

src/yuzu/main.cpp

Supersedes #7832 by using a queue instead of running the hotkey immediately. This allows the input subsystem to be ready for future keypresses and not be blocked by the UI.

hotkeys: Trigger actions on a separate thread

---

src/core/hle/kernel/svc.cpp

Resolves the C4146 compiler warning on MSVC.
This warning was uncovered when compiling with VS 2022.

kernel: svc: Replace -1ULL with 0xFFFFFFFFFFFFFFFF

---

CMakeLists.txt

Additionally, download an updated conan.cmake file from https://raw.githubusercontent.com/conan-io/cmake-conan/release/0.18/conan.cmake

CMakeLists: Update Conan requirement to 1.45.0

---

src/core/hid/hid_types.h
src/core/hle/service/hid/controllers/console_sixaxis.cpp
src/core/hle/service/hid/controllers/console_sixaxis.h
src/core/hle/service/hid/controllers/controller_base.h
src/core/hle/service/hid/controllers/debug_pad.cpp
src/core/hle/service/hid/controllers/debug_pad.h
src/core/hle/service/hid/controllers/gesture.cpp
src/core/hle/service/hid/controllers/gesture.h
src/core/hle/service/hid/controllers/keyboard.cpp
src/core/hle/service/hid/controllers/keyboard.h
src/core/hle/service/hid/controllers/mouse.cpp
src/core/hle/service/hid/controllers/mouse.h
src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/npad.h
src/core/hle/service/hid/controllers/stubbed.cpp
src/core/hle/service/hid/controllers/stubbed.h
src/core/hle/service/hid/controllers/touchscreen.cpp
src/core/hle/service/hid/controllers/touchscreen.h
src/core/hle/service/hid/controllers/xpad.cpp
src/core/hle/service/hid/controllers/xpad.h
src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h

Currently we have a duplicate of the shared memory. Each single change we do needs to be copied to ensure both locations have the same data. This made the service prone to data mismatches or delays.
On some edge cases a game could be reading wrong data. This PR fixes the issue by casting a pointer to the shared memory and eliminating all data duplication. This fixes the issues on my unit test and has the potential to fix many games. Specially the ones who had wrong state like #8162 or pokemon let's go not detecting controllers properly

service: hid: Access shared memory directly

---

src/video_core/renderer_vulkan/renderer_vulkan.cpp

Fixes a regression introduced in #8150 where homebrew would not render anything to the screen.

renderer_vulkan: Update screen info if the framebuffer size has changed

---

src/common/settings.cpp
src/shader_recompiler/ir_opt/verification_pass.cpp
src/video_core/shader_environment.cpp

These changes are needed for GCC 12, but are not sufficient for yuzu to be compiled with GCC 12 due to [numerous](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105420) [compiler](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105423) [bugs](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105424). Once the bugs are fixed, it should compile.

GCC 12 fixes

---

src/yuzu/configuration/configure_system.ui

The Custom RTC widget is under the influence of the computers System Locale.
The format strings are not necessarily related. As a small example, setting the Windows Language to Dansk, and then trying to use yuzu in English the requested AM/PM indicator is simply not shown
The display format for the Custom RTC field needs to be removed from src/yuzu/configuration/configure_system.ui
modifying the display format needs to be moved to src/yuzu/configuration/configure_system.cpp
^ Wordy git commit message, this PR is related to discussion in #8289

ui: let system locale control format of Custom RTC

---

src/yuzu/configuration/configure_network.cpp
src/yuzu/configuration/configure_network.h

Looks like it was just missed when the tab was added, as currently the Network Tab only has one item
RetranslateUI is used more commonly throughout the project
If you open UI in English and switch to Japanese, Network tab isn't told to re translate
Before example
After example

ui: retranslate the network tab

---

src/input_common/drivers/gc_adapter.cpp

Reverts yuzu-emu/yuzu#8295
According to @lat9nq the aforementioned PR breaks `YUZU_USE_BUNDLED_LIBUSB`

Revert "gc_adapter: fix libusb import on GCC11.2"

---

src/core/hid/input_converter.cpp
src/input_common/input_poller.cpp
src/yuzu/configuration/configure_input_player.cpp
src/yuzu/configuration/configure_input_player.ui

Fixes 4 minor issues with analog sticks.
- Default range is now 95% to give a little guarantee that a game sees the max range posible
- Minimum range is lowered from 50% to 25%
- Center correction now is applied to offsets up to 75%
- You can now delete individual axis if buttons are mapped

yuzu: config: Improve analog stick mapping

---

src/core/hle/result.h

Also marks the implicit conversion operator as constexpr instead of consteval as the constructor is not constant evaluated.

hle/result: Add ResultRange overload in ResultVal

---

src/video_core/engines/maxwell_3d.cpp
src/video_core/macro/macro.cpp
src/video_core/macro/macro.h

Allows NSO N64 to boot, since it reassigned the same macros multiple times with different code. This is more or less a workaround for the fact that we don't implement macro code uploads in a hardware-accurate way.

video_core/macro: clear code on upload address assignment

---

src/video_core/engines/maxwell_dma.cpp

This is supposed to just be 1 when not remapping. There is no relationship between the pitch divided by the line length and the BPP value.
|Before|After|
|-|-|
|![010049900f546003_2022-05-06_18-16-21-493](https://user-images.githubusercontent.com/9658600/167223279-feb51f83-b14f-40c4-8957-a0209aab7f6f.png)|![010049900f546003_2022-05-06_18-08-18-472](https://user-images.githubusercontent.com/9658600/167223254-4186ea0e-4b6c-46d8-9787-7cb6d02d1b5a.png)|

maxwell_dma: fix bytes_per_pixel

---

src/video_core/renderer_opengl/gl_rasterizer.cpp

Better version of #8149. Now you can play Super Mario 64 in OpenGL.
Might still be wrong, but I tested a bunch of games and I didn't have any issues.

OpenGL: interpret face flips according to GL NDC

---

src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/hid.cpp

When motion is disabled it doesn't stop updating. Instead it just returns the starting orientation. This solves issues where pokemon let's go is spamming `StopSixAxisSensor`.
While working on these changes I noticed that I totally missed the delta_time parameter. Setting this value correctly fixes the issues from #7707 and allows us to have the same refresh rate as the switch.

service: hid: Disable correctly motion input

---

src/core/arm/dynarmic/arm_dynarmic_cp15.cpp
src/shader_recompiler/frontend/ir/opcodes.h
src/shader_recompiler/frontend/maxwell/opcodes.h

Ensures that we're using the fmt version of format_to.
These are also the only three outliers. All of the other formatters we have are properly qualified.

general: Avoid ambiguous format_to compilation errors

---

src/common/string_util.cpp
src/common/string_util.h
src/yuzu/applets/qt_software_keyboard.cpp
src/yuzu/main.cpp

This PR aims to fix linking errors when compiling yuzu against Qt 5.15.2 and libstdc++ 12 or later with Clang 13 or 14. Linking something that uses `QString::toStdU16String` throws missing symbol errors. Without investigating it, my guess is that it requires a function that was dropped or changed from previous libstdc++ versions. 
This adds and uses `Common::U16StringFromBuffer` in string_util, which effectively works the same as the Qt function but resolves linker issues.

general: Use Common::U16StringFromBuffer in place of QString::toStdU16String

---

src/video_core/renderer_vulkan/vk_rasterizer.cpp

It should not affect games using NVN api, as it seems that two faces are always enabled.
This may fix some ogl games, but idk exactly what is fixed.

vk_rasterizer: fix stencil test when two faces are disabled

---

src/video_core/vulkan_common/vulkan_device.cpp

A bug occurs in yuzu when VK_KHR_workgroup_memory_explicit_layout is available but 16-bit integers are not supported in the host driver. This occurs notably in AMD proprietary drivers from 22.3.2 and later on Polaris devices.
This disables usage of the extension when this case arises, since I don't have the expertise to come up with a proper fix at the moment.

vulkan_device: Workaround extension bug

---

src/video_core/vulkan_common/vulkan_device.cpp

Recent AMD Vulkan drivers (22.5.2, or 2.0.226 for specifically Vulkan) have a broken initial implementation of VK_KHR_push_descriptor that causes a crash in yuzu. Disable it for the time being.
Specifically RX 6400 and RX 6500XT devices will still crash to an unknown reason. All other cards appear to work with this as far as it's been tested.

vulkan_device: Block AMDVLK's VK_KHR_push_descriptor

---

src/common/fs/path_util.cpp

Clang (rightfully) warns that we are checking for the existence of a pointer to something just allocated on the stack, which is always true.
Instead, check that the string is not empty.

path_util: Resolve `-Wpointer-bool-conversion` warning

---

src/core/hid/emulated_console.cpp
src/core/hid/input_converter.cpp
src/core/hle/service/hid/controllers/touchscreen.cpp
src/input_common/drivers/touch_screen.cpp
src/input_common/drivers/touch_screen.h
src/yuzu/bootmanager.cpp
src/yuzu/bootmanager.h
src/yuzu_cmd/emu_window/emu_window_sdl2.cpp

Arcea had issues with touch. Turns out this game checks the position on release and some input drivers didn't keep it's position on release. On top of that multi-touch wasn't working on touch screens for multiple reasons.
This PR fixes the touch issue. And reimplements the touch screen driver to support multi-touch properly.

input_common: touch: Rewrite touch driver to support multiple touch points

---

src/common/input.h
src/core/hid/emulated_controller.cpp
src/input_common/drivers/sdl_driver.cpp
src/input_common/drivers/sdl_driver.h

Some controllers are too slow to respond when a vibration request was made. This caused the whole emulated thread to be delayed causing some heavy stutters.
This PR pushes SDL vibrations to a queue where they can be executed on a different thread. This avoids locking the main emulation thread

input_common: Make vibration request async

---

src/yuzu/CMakeLists.txt

`-mwindows` doesn't work with Clang. https://github.com/tpoechtrager/wclang resolves this by just using MinGW-GCC to link the executable, however this prevents us from using LLVM-exclusive tools when building yuzu.
Solution is to send the linker argument we need from `-mwindows` directly to the linker.
From https://gcc-help.gcc.gnu.narkive.com/FogklN5J/gcc-wl-subsystem-windows-mwindows-options

yuzu-qt: Call -Wl,--subsystem,windows directly

---

src/audio_core/command_generator.cpp
src/core/hle/service/time/time_zone_manager.cpp
src/video_core/command_classes/codecs/vp9.cpp
src/video_core/surface.h

Using smaller array types allows for a slightly more compact executable.
This PR leads to a total reduction of 36352 bytes in the compiled executable on MSVC.
Note: There are other arrays that use larger-than-necessary types, but they do not reduce the size of the compiled executable, hence why the changes are limited to these 4 files.
Note2: The usage of u8 in BITS_PER_BLOCK_TABLE assumes that 256 bit (32 byte) formats (such as R64G64B64A64) do not exist on the Tegra X1 due to their inefficiency and impracticality.

general: Use smaller array types where applicable

---

CMakeLists.txt

This version of boost brings in a number of bug fixes, especially to the asio library. Details can be seen here: https://www.boost.org/users/history/version_1_79_0.html

CMakeLists: Update boost to 1.79.0

---

src/common/settings.cpp
src/common/settings.h
src/core/CMakeLists.txt
src/core/arm/arm_interface.cpp
src/core/arm/arm_interface.h
src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_32.h
src/core/arm/dynarmic/arm_dynarmic_64.cpp
src/core/arm/dynarmic/arm_dynarmic_64.h
src/core/core.cpp
src/core/core.h
src/core/debugger/debugger.cpp
src/core/debugger/debugger.h
src/core/debugger/debugger_interface.h
src/core/debugger/gdbstub.cpp
src/core/debugger/gdbstub.h
src/core/debugger/gdbstub_arch.cpp
src/core/debugger/gdbstub_arch.h
src/core/hle/kernel/k_process.cpp
src/core/memory.cpp
src/core/memory.h
src/yuzu/bootmanager.cpp
src/yuzu/bootmanager.h
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_debug.cpp
src/yuzu/configuration/configure_debug.ui
src/yuzu/main.cpp

This is a singlecore/multicore thread-based debugger implementation that is primarily intended to interface with GDB (though it theoretically could be adapted to work with other debuggers, like GADP).
The [previously removed](https://github.com/yuzu-emu/yuzu/commit/5bc4eabe36b7ef4dcd5ad8db1e944705655be432) debugger had a number of issues:
- It was only written with singlecore execution in mind.
- It was thread-aware, but executed based on controlling the physical core, as opposed to controlling the threads, which caused issues when syscalls were present in stepped code.
- It slowed execution significantly more over singlecore mode alone, because it would poll the socket for new data on each CPU loop, and when reading data, it would read it one byte at a time.
- It only supported A64 code. …

core/debugger: Implement new GDB stub debugger

---

src/core/debugger/debugger.cpp
src/core/debugger/debugger_interface.h
src/core/debugger/gdbstub.h

Resolves an MSVC warning where a virtual destructor is not defined in the base class with virtual functions.

core/debugger: Define defaulted virtual destructors

---

src/yuzu/main.cpp

Sometimes when yuzu crashes, it restarts with the games list in fullscreen,
which would be fine, except there isn't an easy way to exit this.
It also doesn't occur often enough for qt-config.ini files to be in good supply.
UILayout\geometry value in qt-config.ini is the culprit,
at least for the one provided.
Proposed fix is to simply check isFullScreen when yuzu is starting up,
and take it out of full screen immediately

fix UI opening fullscreen after certain crashes

---

CMakeLists.txt
src/core/CMakeLists.txt
src/core/arm/arm_interface.cpp
src/core/arm/arm_interface.h
src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_32.h
src/core/arm/dynarmic/arm_dynarmic_64.cpp
src/core/arm/dynarmic/arm_dynarmic_64.h
src/core/debugger/debugger.cpp
src/core/debugger/debugger.h
src/core/debugger/debugger_interface.h
src/core/debugger/gdbstub.cpp
src/core/debugger/gdbstub.h
src/core/hle/kernel/k_thread.h
src/video_core/CMakeLists.txt
src/yuzu/CMakeLists.txt

Fixes a bunch of issues found while battle testing the new debugger from #8394 over the past day and adds some new features for debugging.
- Implemented vCont GDB packet, which is required for GDB to issue step commands in servers that report thread support, instead of falling back to setting breakpoints.
- Implemented no-acknowledgement mode for GDB. May give a minor performance boost.
- Implemented detailed thread status reports in thread info XML, which allows GDB to list the state and wait reasons for all threads when stopped in the debugger.
- Fixed behavior of stepping. It sometimes could interact unpredictably with scheduling due to having a single debugger-wide step flag instead of a per-thread step flag, which would confuse and crash GDB. I no longer get any crashes with these …

core/debugger: Improved stepping mechanism and misc fixes

---

src/core/debugger/gdbstub.cpp
src/core/debugger/gdbstub.h
src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/k_thread.h

It was pointed out to me by members of Reswitched that guest threads can indeed have names, even though there is no SVC to set a thread name. Reads the thread name from the `nn::os::ThreadType` struct available in TLS.

gdbstub: Support reading guest thread names

---

src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_3d.h

Counter type 0 actually releases the semaphore payload rather than a constant zero as was previously thought. This is required by Skyrim.

Maxwell3D: Fix 3D semaphore counter type 0 handling

---

src/core/hle/service/hid/irs.cpp
src/core/hle/service/hid/irs.h

This service is stubbed with the bare minimum causing some issues with games that do use this service. This PR improves the implementation by adding logging and creating the IRS enum and structs. Fixes memory errors in `Nintendo Labo Toy-Con 01: Variety Kit`. 
While the service remains stubbed it helps to setup a base while I start implementing this service.

service: hid: Improve stub of IRS

---

src/common/CMakeLists.txt
src/common/elf.h
src/core/arm/symbols.cpp
src/core/hle/service/jit/jit_context.cpp
src/core/loader/elf.cpp

Gets rid of a few of these entries that have been copied and pasted throughout the source. Note that the ELF loader is from Citra and still doesn't work, homebrew loading should still use the NRO.

common: consolidate ELF structure definitions

---

src/core/debugger/debugger.cpp

(change is just adding the capture, masked by clang-fomat)

core/debugger: fix crash due to incorrect lambda capture

---

src/core/debugger/debugger.cpp

`write_some` is only guaranteed to write [at least one byte](https://www.boost.org/doc/libs/1_79_0/doc/html/boost_asio/reference/basic_stream_socket/write_some/overload1.html), but the intended behavior in both of these cases is that the entire buffer should be written in a blocking fashion.

core/debugger: fix asio write usage

---

src/core/hle/service/hid/controllers/gesture.cpp
src/core/hle/service/hid/controllers/gesture.h

I accidentally deleted `UpdateGestureSharedMemory` on #8229 this effectively broke gestures. Thanks to OZ for finding the issue.

service: hid: Fix gesture regression

---

src/yuzu/CMakeLists.txt
src/yuzu/bootmanager.cpp
src/yuzu/bootmanager.h
src/yuzu/configuration/configure_motion_touch.cpp
src/yuzu/configuration/configure_motion_touch.ui
src/yuzu/configuration/configure_system.cpp
src/yuzu/game_list.cpp
src/yuzu/loading_screen.cpp
src/yuzu/loading_screen.h
src/yuzu/main.cpp

Update some files with Qt 5.15.2 best practices in mind
There was some discussion about updating to Qt6 and I figured I would
work on some smaller parts. For Windows platform the WinMain function has moved
from the Qt5::WinMain to a new one called Qt6::EntryPointPrivate
Also Qt5 supports versionless CMake targets
https://www.qt.io/blog/versionless-cmake-targets-qt-5.15
These other changes in this commit are to support Qt6, but in ways that don't mess with Qt5.
src/yuzu/bootmanager.cpp: Qt6 complains about not being able to know to use QPoint or QPointF, picking QPoint
src/yuzu/bootmanager.h: Qt6 prefers that QStringList.h be included rather than an empty class definition
src/yuzu/configuration/configure_system.cpp: toULongLong intends to return unsigned 64 bit integer, but …

Update some files with Qt 5.15.2 best practices in mind

---

dist/qt_themes/default/style.qss
dist/qt_themes/qdarkstyle/style.qss
dist/qt_themes/qdarkstyle_midnight_blue/style.qss
src/yuzu/main.cpp
src/yuzu/main.h

For people not used to the Yuzu UI it's not always clear if the emulated
console is docked or not.  The other items update their text when clicked,
this PR brings the DOCK button in line with this.
DOCK -> DOCK or UNDOCK
Revised to
DOCK -> DOCKED or HANDHELD
---

ui: Status bars dock button becomes DOCKED/HANDHELD button

---

src/common/settings.h
src/video_core/vulkan_common/vulkan_library.cpp
src/yuzu/CMakeLists.txt
src/yuzu/check_vulkan.cpp
src/yuzu/check_vulkan.h
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_graphics.cpp
src/yuzu/configuration/configure_graphics.h
src/yuzu/configuration/configure_graphics.ui
src/yuzu/main.cpp
src/yuzu/uisettings.h
src/yuzu_cmd/default_ini.h

I'm going to skip the premise as to why we want to default to Vulkan. It's more clear to other people, and I didn't get any sleep last night. The people to ask about that would be @goldenx86, or @bunnei who tasked me with this.
The reason this hasn't been done before though is due to crashes when opening the Vulkan loader. From my research today this seems more to do with broken Vulkan layers and not having anything to do with outdated drivers. (It may be possible a __broken driver__ will also reproduce crashes, but I don't really want to try and implement my own Vulkan driver even if it just stubs the necessary functions before forcing a segfault.) 
To make `renderer_backend`'s default to Vulkan, a few things had to be done to make that palatable:
- When yuzu boots, it just opens the …

general: Set renderer_backend's default to Vulkan

---

src/common/bounded_threadsafe_queue.h
src/video_core/gpu_thread.cpp
src/video_core/gpu_thread.h

The main advantage is no new in the hotpath thanks to the slots being allocated at initialization.
Just 1-2 more fps, but much better recovery from load spikes and such.
from: https://github.com/rigtorp/MPMCQueue

gpu_thread: Move to bounded queue

---

src/yuzu/game_list.cpp
src/yuzu/game_list.h

This is the "Double-click to add a new folder to the game list" message
that shows up when users first launch yuzu and is most likely never seen
again. Previously this message was not re-translated.
-----
Bug is triggered by changing language before adding a directory to game list (Start in English, switch to Russian)
With PR

retranslate the game list placeholder

---

src/yuzu/main.cpp

This is related, but not dependent on #8318 I'm PR-ing this separately as the method might be wrong, and this also requires Linux testing. 
------
Idea works as follows, while going fullscreen we compare the current window geometry with
available screens and ask for an intersection rectangle, we go fullscreen where most of
the window is located
GuessCurrentScreen could also potentially be used to see which screen
the window is on for dynamic DPI handling

deprecate usage of QDesktopWidget for going fullscreen

---

src/core/debugger/gdbstub_arch.h

The class is used polymorphically, so it's undefined behavior to delete instances of GDBStubA64 and GDBStubA32 from the base class pointer.

gdbstub_arch: Add missing virtual destructor

---

src/core/hle/kernel/k_code_memory.cpp
src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h

This aligns the entire initialization with latest Atmosphere, and properly resolves the clearing bug that was identified with #8199 by actually collecting the page list from KPageTable instead of assuming a contiguous physical address range will map to a contiguous virtual address range.

kernel: fix KCodeMemory initialization

---

src/core/debugger/debugger.cpp

The previous debugger available in Citra [did this](https://github.com/citra-emu/citra/blob/88a475970240e1dbade1720b02f9e5338647b1b8/src/core/gdbstub/gdbstub.cpp#L1164-L1167). Considering it is not enabled by default, it's probably not that big of an issue.
Fixes #8453

core/debugger: allow remote connections

---

src/core/cpu_manager.cpp
src/core/cpu_manager.h
src/core/hle/kernel/kernel.cpp

This uses host-provided concurrency primitives to implement the condition and barrier needed to do single-core and multi-core guest pauses, instead of spinning on variables.

CpuManager: simplify pausing

---

src/shader_recompiler/frontend/maxwell/structured_control_flow.cpp

This seems to be unsupported in newer libstdc++ versions due to Flow::Block's base class being a non-literal type. It's not clear to me why this was permitted in earlier versions.
Suggested to me by @Morph1984 that I pull this commit from #8455 to give it its own PR. That one and #8439 will need to rebase on this one once merged.

structured_control_flow: Remove constexpr Flow::Block

---

src/video_core/renderer_vulkan/vk_compute_pass.cpp

Silences a warning about using enumerated and non-enumerated types in a conditional expression.

vk_compute_pass: Silence Wextra warning

---

src/input_common/drivers/sdl_driver.cpp
src/input_common/drivers/sdl_driver.h

At some point SDL returned a string with 33 characters which is bigger than the UUID size. This might be a bug on SDL side but s since we don't really need to use the string at all it's just easier to replace all instances with Common::UUID
This PR should have no difference for the user.

input_common: Replace usage of string guid to common uuid

---

src/core/hle/service/glue/notif.cpp
src/core/hle/service/glue/notif.h

Partially Implements RegisterAlarmSetting, UpdateAlarmSetting, LoadApplicationParameter, DeleteAlarmSetting. Needed for `Fitness Boxing 2: Rhythm & Exercise` and `Ring Fit Adventure`.
This allows the game to read and write alarm data without crashing. I have intended to finish implementing this service when vfs changes are in place

service: notifa: Implement most part of this service

---

src/common/bounded_threadsafe_queue.h
src/video_core/gpu_thread.h

While this is the primary change, we also:
- Remove the mpsc namespace and rename Queue to MPSCQueue
- Make Slot a private struct within MPSCQueue
- Remove the AlignedAllocator template argument, as we use std::allocator
- Replace instances of mask + 1 with capacity, and mask + 2 with capacity + 1
Also set the default capacity to 0x400 (1024) instead of 512

bounded_threadsafe_queue: Use constexpr capacity and mask

---

src/core/core.cpp
src/core/core.h
src/core/cpu_manager.cpp
src/core/cpu_manager.h
src/core/debugger/debugger.cpp
src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/k_process.h
src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/kernel.h
src/core/hle/kernel/svc.cpp
src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp

This allows pausing and unpausing the emulated game to go through the kernel mechanism intended for this, which simplifies some CPU code.

kernel: implement KProcess suspension

---

src/core/hle/kernel/svc.cpp

Currently this just stops all the emulation
This works under assumption that only application will try to use
ExitProcess, with services not touching it
If application exits - it quite makes sense to end the emulation

Implement ExitProcess svc

---

src/yuzu_cmd/yuzu.cpp

Because logging infrastructure initializes before the loading of the
config, it reads the default setting for log_filter and ignores the one
set in config. To change log_filter after logging initialization some
additional calls need to be made.

Make yuzu-cmd respect log_filter setting

---

src/common/param_package.cpp

Not all keys are saved in the config file to keep it as clean as posible. Every time input is loaded it will flood the log with these warnings if you are running under debug. Quite annoying for me since they don't provide any useful info and will return the default anyways.

common: param_package: Demote DEBUG to TRACE for getters

---

src/core/cpu_manager.cpp
src/core/cpu_manager.h
src/yuzu/bootmanager.cpp
src/yuzu_cmd/yuzu.cpp

Fixes a race between CPU thread initialization and core GPU initialization that was uncovered in #8388.

core: fix initialization in single core, sync GPU mode

---

src/core/hle/service/am/am.cpp
src/core/hle/service/am/am.h

Used by Ring Fit Adventure when you press ZR or ZL. This fixes a svc crash.

service: am: Stub PerformSystemButtonPressingIfInFocus

---

src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/k_scheduler.cpp
src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/kernel.cpp

Aligns more of this with Atmosphere. Note that we have to specially mark the idle threads because we perform scheduling dispatch from them, which I will address at a later date.

kernel: fix some uses of disable_count

---

src/common/page_table.h
src/core/arm/arm_interface.cpp
src/core/arm/arm_interface.h
src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_32.h
src/core/arm/dynarmic/arm_dynarmic_64.cpp
src/core/arm/dynarmic/arm_dynarmic_64.h
src/core/debugger/debugger.cpp
src/core/debugger/debugger.h
src/core/debugger/debugger_interface.h
src/core/debugger/gdbstub.cpp
src/core/debugger/gdbstub.h
src/core/hardware_properties.h
src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/k_process.h
src/core/hle/kernel/k_scheduler.cpp
src/core/memory.cpp
src/core/memory.h

Implements support for both read and write memory breakpoints into the debugger, which is a highly requested feature.
This operates by removing affected pages from the fastmem page table, and checking accesses to the watched regions in the fallbacks when debugging is enabled. When the debugger is enabled, it has some performance impact, but most games which are able to run above full speed should remain above full speed. There is no effect when debugging is not enabled.

core/debugger: memory breakpoint support

---

.ci/scripts/windows/docker.sh
CMakeModules/MinGWClangCross.cmake

The reason I wanted to do this is twofold: GCC 12 appears to have optimization errors and bogus warnings, and in the future I want to move MinGW to Clang anyway for possibly releasing these builds instead of those from MSVC.
We aren't ready to release any MinGW build though due to stability issues in yuzu's VFS. However, the timing of this part wasn't entirely my choice since Arch Linux has moved their MinGW compiler to GCC 12.
I would still like to see https://github.com/yuzu-emu/yuzu/pull/8439 working before merging this, but if for some reason it doesn't seem worth it, that isn't a hard requirement.
One last thing: I wanted to include [Polly](https://polly.llvm.org/) optimizations in this PR, but I'd rather back that up with evidence showing that we benefit from it at a later time.

ci/windows: Use Clang for MinGW builds

---

src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/k_thread.h
src/core/hle/kernel/kernel.cpp

The previous StallCPU behavior waited for all thread execution to actually stop. Not waiting for it to stop seems to have caused the GPU thread to occasionally race and hang in Fire Emblem: Three Houses if a host GPU stall occurred.

kernel: wait for threads to stop on pause

---

src/core/debugger/gdbstub.cpp

All GDB commands need a reply.

gdbstub: fix register pokes

---

src/core/arm/arm_interface.cpp
src/core/cpu_manager.cpp
src/core/hle/kernel/k_address_arbiter.cpp
src/core/hle/kernel/k_condition_variable.cpp
src/core/hle/kernel/k_interrupt_manager.cpp
src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/k_scheduler.cpp
src/core/hle/kernel/k_scheduler.h
src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/k_thread.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/kernel.h
src/core/hle/kernel/svc.cpp

Another Atmosphere consistency item. When in kernel mode, the platform register stores the current thread pointer, so we emulate this with a thread local that stores the current thread pointer. This is required for reworking the idle mechanism, as on entry, the scheduler will not have set a current thread and so its pointer will be null.

kernel: make current thread pointer thread local

---

src/core/hle/kernel/svc.cpp

I'm not sure whether this patch is desired or not; as the name suggests, this is not stock Switch behavior but something specific to Atmosphere.
My use case for this is to make [exlaunch](https://github.com/shadowninja108/exlaunch), a hooking framework, work in Yuzu.  That said, exlaunch also supports an [alternative method](https://github.com/shadowninja108/exlaunch/blob/b7eb687fba27b2d579aad2944d583c99c30198a8/source/lib/util/sys/cur_proc_handle.cpp#L33) of getting a current-process handle which uses only stock syscalls.  Unfortunately, the syscalls in question include `svcCreateSession` and `svcSendSyncRequest`, which are not implemented by Yuzu.  It seemed to me like implementing them would be much more work than implementing `MesosphereCurrentProcess`, so I didn't try. ¯\\\_(ツ)\_/¯

Support `InfoType_MesosphereCurrentProcess`

---

src/video_core/vulkan_common/vulkan_device.cpp

Reverts yuzu-emu/yuzu#8379
AMD's latest driver fixes the issue worked around in #8379, but retains the same version string in the driver -- 2.0.226.
So since AMD didn't update the version string, solution here is to just revert it and tell people to update their driver if they experience crashes.

Revert "vulkan_device: Block AMDVLK's VK_KHR_push_descriptor"

---

src/core/arm/arm_interface.cpp
src/core/arm/arm_interface.h
src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_64.cpp

Fixes #8488. Might slow down translation a bit, since Dynarmic won't attempt to use the page table during translation.

dynarmic: Stop ReadCode callbacks to unmapped addresses

---

src/core/cpu_manager.cpp
src/core/hle/kernel/k_scheduler.h

Unbreaks single core mode after #8475.

cpu_manager: properly check idle on return from preemption

---

src/core/debugger/gdbstub_arch.cpp

Currently to access the SP register, `RegRead` and `RegWrite` rely on a out-of-bounds array access to reach the next element in a struct. As of writing only git versions of GCC catch this error.
Specify the SP register when we want to access it in these functions.

gdbstub_arch: Directly access SP register

---

src/yuzu/applets/qt_web_browser.cpp

In testing future versions of Qt I forgot to compile with `YUZU_USE_QT_WEB_ENGINE`, so with that flag enabled there are two issues that cropped up.
1. yuzu currently uses setRequestInterceptor, added in Qt 5.6, deprecated in 5.13 with this explaination at https://doc.qt.io/qt-5/qwebengineprofile-obsolete.html
Interceptors installed with this method will call QWebEngineUrlRequestInterceptor::interceptRequest on the I/O thread. Therefore the user has to provide thread-safe interaction with the other user classes. For a duration of this call ui thread is blocked. Use setUrlRequestInterceptor instead.
2. QWebEngineSettings::globalSettings() pointer no longer exists in later versions of Qt
From what I can tell, QtNXWebEngineView doesn't need to set these globally,
when we make changes to …

tweak API usage in qt_web_browser.cpp

---

src/common/fiber.cpp
src/common/fiber.h
src/core/cpu_manager.cpp
src/core/cpu_manager.h
src/core/hle/kernel/k_scheduler.cpp
src/core/hle/kernel/k_scheduler.h
src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/k_thread.h
src/tests/common/fibers.cpp

Changes the `std::function<void(void*)>` + `void*` invocation parameter to a `std::function<void()>`. `std::function` already acts as a closure so there is no point in carrying around the extra `void*`, and having to use extra indirection makes it more annoying to write fibers than it really needs to be.

common/fiber: make fibers easier to use

---

src/common/settings.h
src/yuzu/configuration/config.cpp
src/yuzu/configuration/config.h
src/yuzu/configuration/configuration_shared.cpp
src/yuzu/configuration/configuration_shared.h
src/yuzu/uisettings.h
src/yuzu_cmd/config.cpp
src/yuzu_cmd/config.h

The latest git version of GCC has issues with my diamond inheritance shenanigans. Since that's now two compilers that don't like it I thought it'd be best to just axe all of it and just have the two templates like before.
This rolls the features of BasicRangedSetting into BasicSetting, and likewise RangedSetting into Setting. It also renames them from BasicSetting and Setting to Setting and SwitchableSetting respectively. Now longer name corresponds to more complex thing.

settings: Consolidate RangedSetting's with regular ones

---

src/core/hid/hid_types.h
src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/npad.h
src/core/hle/service/hid/errors.h
src/core/hle/service/hid/hid.cpp

Some functions should always return success even on failure. Fixup behavior of `GetVibrationDeviceInfo` that has been bothering me for a while.
This should fix boot issues on `de Blob`

service: hid: Correct some mistakes and add more validations

---

src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/k_thread.cpp

See [13.0.0 release notes](https://switchbrew.org/wiki/13.0.0), specifically under "A complete re-work/unification was done for the various kinds of thread waiting operations in the kernel." This fixes a few things that were missed.

kernel: clean up waiting implementation

---

src/core/arm/arm_interface.cpp
src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_32.h
src/core/arm/dynarmic/arm_dynarmic_64.cpp
src/core/arm/dynarmic/arm_dynarmic_64.h

- Add the frame at the PC as the top frame in the stacktrace
- 32-bit games are compiled with frame pointer support, report backtraces from this the way the creport sysmodule would
- Demangle names when compiling with libstdc++ or libc++

core/arm: better support for backtrace generation

---

src/audio_core/audio_renderer.cpp
src/audio_core/stream.cpp
src/core/core_timing.cpp
src/core/core_timing.h
src/core/hardware_interrupt_manager.cpp
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/time_manager.cpp
src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hidbus.cpp
src/core/hle/service/nvflinger/nvflinger.cpp
src/core/memory/cheat_engine.cpp
src/core/tools/freezer.cpp
src/tests/core/core_timing.cpp

The main idea here is to make coretiming much more accurate in its callback timing, and add an automatically looping type of event, so that functions don't need to keep re-registering themselves, as almost all events are auto, and not one-shot.
The current problem with coretiming callbacks is the reliance on the callback to re-schedule itself, which necessarily means that some time is lost, between the coretiming timestamp to calculate `ns_late`, and the schedule function doing the same thing some point later. 
If some event was scheduled at time 100, maybe the callback delay is calculated at time 102, passing a ns_late of 2 into the callback. The callback runs and at the end wants to reschedule itself 10 units later. It calls reschedule with 10 - 2, the scheduling function then gets the …

Rework CoreTiming events

---

src/video_core/compatible_formats.cpp
src/video_core/renderer_opengl/maxwell_to_gl.h
src/video_core/renderer_vulkan/maxwell_to_vk.cpp
src/video_core/surface.cpp
src/video_core/surface.h
src/video_core/texture_cache/format_lookup_table.cpp
src/video_core/texture_cache/formatter.h

- Used by Monster Hunter Rise Update 10.0.2
Note: This is **not** enough to fix the broken graphics
@FernandoS27

renderer_(gl/vk): Implement ASTC_10x6_UNORM

---

src/core/hle/kernel/k_thread.cpp

This error is due to incorrect copying from Atmosphere code. This mistake causes a finalizing KThread to cancel the next waiter instead of the current one, which will lead to the first waiter in the list never getting canceled, and a bogus cancel getting called on the finalizing thread itself as the last element.

kernel: fix usage of waiter_list in Finalize

---

src/core/hle/service/hid/controllers/npad.cpp
src/input_common/drivers/sdl_driver.cpp
src/input_common/drivers/sdl_driver.h

When I moved vibrations to the poll thread it created a whole new set of issues. As now controllers would now go unresponsive rather than having stutter on the game. This PR reduces the amount of vibrations send per second as well move them out of the poll thread to avoid locking any controller input.
If issues still persist I might consider disabling vibration devices on the fly if they take too long to respond.

input_common: sdl: lower vibration frequency and use it's own unique thread

---

src/yuzu/applets/qt_web_browser.cpp

Button inputs were broken as `button` was assumed to be the bit position of `NpadButton` prior to the input rewrite. Since this was changed to use `NpadButton` directly, we should count the number of trailing zeros to determine the bit position.

qt_web_browser: Fix button inputs with QtWebEngine

---

.ci/scripts/windows/docker.sh

Prevents overwriting an old libwinpthreads.dll when one should already be present from the first DLL search.

ci/windows: Copy what of FFmpeg not already present

---

src/core/hle/kernel/k_code_memory.h

KCodeMemory: Mark virtual methods as override

---

src/core/hle/service/nvflinger/binder.h

Corrects behaviour: Correctly call the appropriate child destructor on deletion of `IBinder`, when `delete` is performed on pointer to `IBinder`.

nvflinger: Polymorphic destructor requried for abstract class IBinder

---

src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_64.cpp

Watchpoints should only be checked for data, not instructions.

core/arm: skip watchpoint checks when reading instructions

---

src/common/settings.h
src/yuzu/configuration/config.cpp
src/yuzu/configuration/config.h
src/yuzu/configuration/configuration_shared.h
src/yuzu_cmd/config.cpp
src/yuzu_cmd/config.h

- Avoids new GCC 12 warnings when Type is of form std::optional<T>.
- Makes more sense this way, because ranged is not a property which would change over time.

common/setting: Make ranged a property of the type

---

src/common/wall_clock.cpp
src/common/x64/cpu_detect.cpp
src/common/x64/cpu_detect.h

The current method used to estimate the TSC is fairly accurate - within a few kHz - but the exact value can be extracted from CPUID if available.

common/x64: Use TSC clock rate from CPUID when available

---

src/yuzu/configuration/configure_input.ui

For consistency, as it was previously renamed from the status bar.

Rename Undocked to Handheld in input settings

---

.ci/scripts/windows/upload.ps1

vcpkg data takes up a lot of space, and currently the scripts will package all that data with the source archive which is unnecessary.

ci/windows: Cleanup unused data in submodules before packaging

---

.ci/scripts/windows/upload.ps1
.github/workflows/verify.yml

This is related to #8486
Ninja places the exe files into .\build\bin while MSBuild may place them
into .\build\bin\Release
upload.ps1 was originally written for use with Azure Dev Ops to cough up about
5 files and the script appears to be used for both CI and mainline builds
GHA (GitHub Actions) makes available a single zip of the items uploaded by
each Upload action (artifacts directory), so we want to work with that.
I'm doing changes to upload.ps1 to accomplish this.
The changes to the verify.yml are as follows
-DGIT_BRANCH=pr-verify changes the header in yuzu, instead of saying
HEAD-<hash>-dirty it'll say pr-verify-<hash>
-DCLANG_FORMAT_SUFFIX=discordplzdontclang tricks the CMake stuff for
discord-rpc to NOT run clang-format, as this was marking CI builds as
dirty
I'm also making it …

package MSVC CI Builds differently, and include yuzu.exe

---

.ci/scripts/linux/exec.sh

Windows: yuzu 1100
Linux AppImage: yuzu | HEAD-mainline-636-9115-ge567e755d-dirty
This PR just takes a stab at sharing more environment variables into the docker, I don't have Azure Dev Ops to test with, From what I can tell, some of the configuration of environment variables isn't in the repository
Long term I think the AppImage should have a title bar like: yuzu 1100 | mainline-20220720-e567e755d
------------
Variables in question:
AZURECIREPO TITLEBARFORMATIDLE TITLEBARFORMATRUNNING DISPLAYVERSION
CMakeModules/GenerateSCMRev.cmake has some logic that looks at BUILD_REPOSITORY variable inside CMake
src/common/CMakeLists.txt has some logic that takes some items from environment variables and
sets variables inside CMake
This is the whole section at the moment.
if (DEFINED …

ci: pass environment variables to linux docker (AppImage)

---

.ci/scripts/transifex/docker.sh

The slim docker container that runs transifex needs a few packages added
in, curl zip unzip
I've tested everything except actually pushing to transifex, but it's
not November 2022 yet so we're fine for now. Or we're actually using the
newer client and all is well.
-------
I just noticed that I didn't mention that vcpkg wants tar, but we have tar, I'm not editing the commit message for that 😛

ci,transifex: enable vcpkg on transifex step

---

.gitmodules

FFmpeg's own git repo seems to be down, so switch to GitHub like we use for most externals.
The FFmpeg external should still be set to n4.3.1.

externals: Use GitHub for FFmpeg

---

src/video_core/gpu_thread.cpp
src/video_core/gpu_thread.h

The bounded MPSCQueue implementation causes crashes in Fire Emblem Three Houses, use the previous implementation for now.

gpu_thread: Use the previous MPSCQueue implementation

---

.ci/scripts/windows/upload.ps1

With our recent switchover from conan to vcpkg, we're shipping a few
more dll files, these need to be in the full zip.
cp .\build\bin\*.dll .\artifacts\
also tacking on the fix where we're shipping scm_rev.cpp accidentally

build: Ship vcpkg dlls with MSVC pr-verify builds

---

.ci/scripts/linux/docker.sh

This library causes issues in Vulkan driver detection. libQt5Multimedia's dependencies seem to be the issue.
If excluding this library causes larger issues (i.e. the AppImage doesn't work on end-user systems), removing Qt5Multimedia altogether may be necessary.
Please wait for me to verify CI output.

ci/linux: Exclude libwayland-client from AppImage

---

src/audio_core/renderer/command/command_buffer.cpp
src/audio_core/renderer/command/mix/depop_prepare.cpp

The buffer count isn't all of the available mix buffers, and the indexes don't start at 0, so you can have say, 40 mix buffers, but a buffer count of 6, and the inputs of those 6 buffers could be 12/13/14/15/16/17, which is out of bounds for a 6 buffer span that only considered buffers 0-5.
There wasn't any *actual* out of bounds writing here, the underlying buffer is big enough, just the reinterpreted span being too small, so just make it a pointer instead.
Fixes https://github.com/flathub/org.yuzu_emu.yuzu/issues/582#issuecomment-1197358199

[Audio] Avoid an out-of-bounds span write in depop prepare

---

.gitmodules

Our fork includes a commit to disable clang-format, preventing the dirty flag from being set when building yuzu on CI.

externals: Use yuzu-emu/discord-rpc to provide Discord integration

---

.ci/templates/build-msvc.yml
.ci/yuzu-mainline-step2.yml
.ci/yuzu-patreon-step2.yml

Reverts yuzu-emu/yuzu#8256. Temporary to see if this helps with the recent MSVC regression with our ADO build pipelines.

Revert "ci: Enable building with Visual Studio 2022"

---

src/yuzu/main.cpp

An user wanted a way to fine tune the volume on low levels. This PR sets a smaller step the closer you get to 0%

yuzu: Add incremental steps to volume hotkeys

---

.reuse/dep5

Adding comments to these files completely removes the ability to file issues.

ci: use dep5 for GitHub issue template files

---

src/audio_core/renderer/effect/effect_info_base.h

The warnings GCC generates depend on the flags you are compiling with.

audio_core: fix -Wuninitialized when compiling with ASan

---

src/common/threadsafe_queue.h

Fixes a -Wmaybe-uninitialized on gcc 12.1. I don't have the energy to file another upstream bug report at this point given that none of the previously filed issues have been fixed.

common: move forwarded value into SPSCQueue

---

src/video_core/renderer_opengl/gl_shader_util.cpp

Improves memory usage a little bit in XC3 when using OpenGL.
before
after

renderer_opengl: delete shader source after linking

---

src/yuzu/loading_screen.cpp

This prevents yuzu from appearing stalled when booting a program. This would occur if there were no shaders cached for the program, which generally means for the first boot for games, and always for most homebrew.

qt: reset progress bar after shader compilation

---

src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp

This is very annoying while testing fixes for XC3, which compiles thousands of shaders on boot.

video_core: stop waiting for shader compilation on user cancel

---

src/yuzu/applets/qt_profile_select.cpp
src/yuzu/main.cpp
src/yuzu/main.h

2 fixes for using a controller in profile select dialog.
1) Pressing 'B' cancels the launch of the game
2) Using controller to select a profile now correctly sets the index to use for the launch

Controller bugfixes in profile select, closes #8265

---

src/shader_recompiler/backend/spirv/spirv_emit_context.cpp

FSwizzleAdd uses subgroup_local_invocation_id, and ConvertDepthMode uses output_position, but they weren't being set, resulting in some invalid shader opcodes which crashed Vulkan. 
This allows Xenoblade Chronicles 3 to boot with Vulkan. All credits to @liamwhite for this, I was just a guinea pig.

[SPIRV] Add missed shader defines

---

src/video_core/renderer_vulkan/vk_texture_cache.cpp

Prevents Xenoblade Chronicles 3 from crashing during cutscenes.
A separate fix is still needed for the game to be bootable on recent AMD cards with Windows, though it currently works on Linux.

vk_texture_cache: return VK_NULL_HANDLE for views of null images

---

src/yuzu/bootmanager.cpp
src/yuzu/main.cpp
vcpkg.json

Soft-requires #8675 to fix build issues
Also of note is yuzu-emu/build-environments#58
The build environments completed their routine update last night, and vcpkg updated their fmt to 9.0.0. Since we probably want to move to fmt 9.0.0 anyway, this fixes the couple of compile issues we had with that version.
This also specifies the fmt version that we want to use in the vcpkg.json. At the moment there is no later version of fmt, but this helps keep things in our control should we update vcpkg and builtin-baseline later.

vcpkg,yuzu: Update to fmt 9.0.0

---

src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_64.cpp

Partial revert of #8148
Fixes #8211
@merryhime 
This allows Galaxy to be progressed past video playback scenes once again, and fixes stuttery FMV audio playback in this game, as well as normal audio playback in the N64 emulator. It also provides about a 10% speedup in Galaxy with the framerate unlocked.
There seems to be some fundamental timing issue, at the very least regarding cntpct_el0, that needs to be addressed before accurate cycle counting can correctly be disabled. All of these games depend on a relatively precise thread sleep followed by a busy wait for the remaining time to smoothly match timings of the systems they are emulating; in pseudocode they do this
```cpp
u64 tick_start = clock_ns();
u64 tick_end = tick_start + delay_ns;
if (tick_end - tick_start > 1000000) { …
```

core/arm: re-enable cycle counting

---

src/yuzu/main.cpp

When windows is told to display Standard digits as suzhou, it is showing
incorrect information in yuzu, file sizes and the CPU speed limiter are
effected by this. See #8698 for some screenshots.
Setting number format to Chinese (Simplified, Hong Kong SAR) is one
way to see this issue in action.
Fixes #8698
--------

Qt5 work around for suzhou numerals

---

.gitignore
.reuse/dep5
dist/english_plurals/README.md
dist/english_plurals/en.ts
src/yuzu/CMakeLists.txt
src/yuzu/configuration/configure_ui.cpp
src/yuzu/main.cpp

Turns out that for Qt to properly handle plurals in English a
translation needs to be provided, otherwise the user is left with
messages such as "Building: 2 shader(s)"
Plurals for other all other languages are handled on transifex. 
I wrote the README.md to just refer to it as a translation 
collaboration site just in case we ever switch.
These translations being out of date won't pose any technical problems
so I believe it is fine to handle them manually on a "best effort"
basis.
The files are generated into the source directory so that the
relative filenames are correct. The generated file is added to
.gitignore
-------
We might be able to technobabble something decent out of Transifex so I'm submitting this as a draft. Attn: @FearlessTobi 
But in my extensive research on this the best …

Translate english plurals

---

src/core/arm/dynarmic/arm_dynarmic_cp15.cpp
src/core/arm/dynarmic/arm_dynarmic_cp15.h

These were originally no-ops as per Citra previously.
Here we make the barrier instructions actually do something.
Affects 32-bit games only.

 arm_dynarmic_cp15: Implement CP15DMB/CP15DSB/CP15ISB 

---

src/core/hid/emulated_controller.cpp
src/core/hid/emulated_controller.h
src/core/hid/hid_types.h
src/core/hle/service/hid/controllers/npad.cpp

~~The invested time to figure out this issue can't be correlated to the line changed. Qt provided alpha values for the controller color. The switch doesn't have alpha values for the controllers.~~
Properly reports battery and controller colors depending on the controller type.
Fixes Mario Party Superstars displaying the wrong controller icon.

hid: core: Properly emulate controller color and battery level

---

src/core/hid/emulated_controller.cpp

Lately ds4windows will make controllers vibrate indefinitely at the start of every game. Seems like it can't handle two sequent vibrations commands. This PR adds a small delay to ensure it will not ignore the stop command.

hid: core: Delay the stop vibration command when testing

---

src/video_core/renderer_vulkan/vk_swapchain.cpp
src/yuzu/configuration/configure_graphics_advanced.ui

The Vulkan renderer does not support setting vsync.   It currently prefers mailbox (Triple buffering) mode if found. 
Mailbox mode avoids tearing, but it has a downside: it does not keep the emulation in sync with the real display.   If the emulation and display are very close to precise sync, there can be fits of juddering when the newly generated frames don't decisively fall as next in the display's sequence.  
Related to issue #7310.   I experienced the same behavior as [DelghLay](https://github.com/DelghLay).   Yuzu shows a rock solid 60fps, but on my setup, the display judders for ~30 seconds or so every few minutes.   After switching the code to use FIFO mode, the issue goes away completely and scrolling games like Metroid Dread and Link's Awakening become butter smooth.   I'm using …

Make vsync setting work for Vulkan

---

.ci/scripts/common/post-upload.sh
.ci/scripts/windows/upload.ps1

Instead of including yuzu and all the sources it uses directly, include only what specifically belongs to yuzu. Submodules can be downloaded separately later using git since a shallow clone includes minimally all the repository information needed for it.
Shrinks the source archive down from about 32 MB at time of writing to about 8 MB, both numbers after XZ compression.

ci: Graft source when archiving

---

src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/arm/dynarmic/arm_dynarmic_64.cpp

Many thanks to @vladkosi for investigating the underlying issue regarding non-functioning on earlier versions of Windows. See: merryhime/dynarmic#701.
On earlier versions of Windows, because they do not support modern memory allocation APIs, the fastmem pointer would be nullptr. Yuzu attempts to enable fastmem of exclusive accesses without a valid fastmem arena, which is not a valid state to be in. Dynarmic thus asserts internally when this happens.
Verification would be helpful as I am unable to test this.

arm_dynarmic: Fix nullptr fastmem arenas

---

src/yuzu/aboutdialog.ui
src/yuzu/multiplayer/direct_connect.ui

make about dialog a bit taller for full message on more systems
for direct_connect.ui hedging bets here, there is a text field for port
number that possibly shouldn't be translated, marking as such, but also
adding a translation note for the event that it makes sense to translate
the placeholder text to something other than the default multiplayer
direct connect port.
------
It might make sense to look into a unified font between Windows/Linux to reduce the need to tweak the GUI beyond what is done on Windows, but sometimes its fun to embrace chaos
direct_connect.ui in Qt Creator, it's that 24872 that GillianMC and I think shouldn't be translated.

Qt: tweak ui files

---

src/core/file_sys/ips_layer.cpp

Delimits the hex value string on spaces, slashes, carriage returns or newlines, allowing for comments to be added in-line.
Thanks to @theboy181 pestering me to fix this :smile:

ips_layer: Delimit parsed hex value string

---

src/audio_core/sink/cubeb_sink.cpp
src/common/settings.cpp
src/common/settings.h
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_audio.ui
src/yuzu/main.cpp

Requested by a couple people, allows the volume slider to go up to 200%. Also changes the default volume up key from + to =. It was weird that for volume down you just press -, but volume up required shift+=. Changing the key from + to = lets you skip the shift, as was originally intended I think.

Allow audio volume up to 200%

---

src/video_core/textures/decoders.cpp
src/video_core/textures/decoders.h

Interesting exercise in case people were interested.
One could similarly increment swizzled_y to avoid the pdep.

video_core/textures/decoders: Avoid SWIZZLE_TABLE

---

src/common/uint128.h

This header does not seem to be needed, and also removing it may allow some parts of yuzu to compile on non-x86 devices.

common: remove unneeded x86-specific header

---

src/video_core/renderer_vulkan/maxwell_to_vk.cpp

Used by Rocket League
|Before|After|
|---------|------|
|![01005ee0036ec000_2022-08-19_14-52-40-454](https://user-images.githubusercontent.com/9658600/185708627-6bf89e1b-3511-49b0-9741-c51841709072.png)|![01005ee0036ec000_2022-08-19_17-07-36-647](https://user-images.githubusercontent.com/9658600/185708663-64f46cbd-c9ed-49b2-a3ca-07b249af9565.png)|

video_core: implement R16G16B16X16 texture format

---

src/yuzu/game_list.cpp
src/yuzu/game_list.h
src/yuzu/game_list_p.h

Didn't notice this until I was trying to change the default font
to Comic Sans MS when language is set to English in yuzu.
--------------
yuzu started in chinese, switched to english, ignore the size column, that has been fixed. 
Otherwise Illustrates bug being fixed, also shows PMIngLiU font because this is VM set to chinese
Not much to look at when fixed.

Qt: Retranslate GameList header and Filter line

---

src/yuzu/configuration/configure_input_player.cpp

Any longer and it will not fit in the drop down box 
closes #8782

yuzu: Allow longer controller profile names

---

src/core/file_sys/ips_layer.cpp
src/core/file_sys/patch_manager.cpp

Fixes spurious inability to load patches for NSOs with BuildIds less than 32 bytes long

core/file_sys: fix BuildId padding in patch loading

---

src/common/microprofile.h
src/core/arm/dynarmic/arm_dynarmic_32.cpp
src/core/loader/kip.cpp
src/core/loader/nro.cpp
src/core/loader/nso.cpp
src/core/memory.cpp
src/core/memory.h
src/tests/video_core/buffer_base.cpp
src/video_core/buffer_cache/buffer_base.h
src/video_core/buffer_cache/buffer_cache.h
src/video_core/memory_manager.cpp
src/video_core/query_cache.h
src/video_core/rasterizer_accelerated.cpp
src/video_core/shader_cache.cpp
src/video_core/shader_cache.h
src/video_core/texture_cache/texture_cache.h
src/video_core/texture_cache/texture_cache_base.h

Some header files, specifically for OSX and Musl libc define PAGE_SIZE to be a number
This is great except in yuzu we're using PAGE_SIZE as a variable
Specific example
```cpp
static constexpr u64 PAGE_SIZE = u64(1) << PAGE_BITS;
```
PAGE_SIZE PAGE_BITS PAGE_MASK are all similar variables.
Simply deleted the underscores, and then added YUZU_ prefix
Might be worth noting that there are multiple uses in different classes/namespaces
This list may not be exhaustive
Core::Memory   12 bits (4096)
QueryCacheBase 12 bits
ShaderCache    14 bits (16384)
TextureCache   20 bits (1048576, or 1MB)
Fixes #8779
----
~~I had an odd graphical glitch in mario kart earlier, so I'm going to grab the verification build and try a few races just in case, but it seemed to not be related to this PR~~ Was just …

code: dodge PAGE_SIZE #define

---

src/core/file_sys/ips_layer.cpp
src/core/file_sys/patch_manager.cpp

It's aligned to the left, not the right. Oops.

core/file_sys: fix alignment of BuildId

---

src/core/hle/service/filesystem/fsp_srv.cpp

The IDirectory service does not need to calculate the size recursively, which will seriously delay the running speed.

core:filesystem: speed up IDirectory service

---

CMakeLists.txt

For [Flatpak builds](https://github.com/flathub/org.yuzu_emu.yuzu), the compatibility list is located in the source directory, because the Flatpak build system is not allowed access to the internet. In this case, CMake will copy it to `${PROJECT_BINARY_DIR}/dist/compatibility_list/`. This fixes the issue in the Flatpak build where the compatibility of all games is "not tested" as mentioned in  flathub/org.yuzu_emu.yuzu#6.

cmake: Use compatibility list in source directory

---

src/core/hid/emulated_controller.cpp
src/core/hid/emulated_controller.h

Super Mario Galaxy soft locked when dual joycon was selected. This was due the game only enabling pro controller and handheld support at boot. Then later on enabling dual joycon support. 
Original behavior will disconnect the controller since it's not supported at boot.  But after a few HW test with homebrew I found that the controller never stops working it just fallback itself to pro controller then restore the original type once it's supported.
This PR fixes Mario Galaxy with dual joycons.

core: hid: Add fallback for dualjoycon and pro controllers

---

src/video_core/renderer_vulkan/vk_rasterizer.cpp

Thanks to bylaws to make this possible. Viewport swizzle is not supported on AMD. Some games where upside down. This PR should fix those errors.
Should fix the following games. Please confirm:
Fixes #7627
Fixes #8056

video_core: vulkan: rasterizer: Workaround on viewport swizzle on AMD

---

src/shader_recompiler/backend/glasm/emit_glasm_image.cpp
src/shader_recompiler/backend/glsl/emit_glsl_image.cpp
src/shader_recompiler/backend/glsl/glsl_emit_context.cpp
src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
src/shader_recompiler/frontend/ir/ir_emitter.cpp
src/shader_recompiler/frontend/ir/ir_emitter.h
src/shader_recompiler/ir_opt/rescaling_pass.cpp
src/shader_recompiler/ir_opt/texture_pass.cpp
src/shader_recompiler/shader_info.h
src/video_core/renderer_opengl/gl_texture_cache.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
src/video_core/renderer_vulkan/vk_texture_cache.cpp
src/video_core/shader_environment.cpp

This PR is intended to solve the rectangle texture. Considering that the rectangle texture is a legacy texture format, we use texture2d to emulator, and normalize the rectangle texture coordinates when it create fs shader.
Before:
After:

video_code: support rectangle texture

---

src/core/hle/service/am/am.cpp
src/core/hle/service/apm/apm_controller.cpp
src/core/hle/service/hid/hid.cpp
src/core/hle/service/mm/mm_u.cpp
src/core/hle/service/nvdrv/devices/nvmap.cpp

These get spammed very often for many games and can end up taking 90+% of logs. Demote them down to debug instead of warning/info.
Demotes:
* GetCurrentFocusState
* SetClockSpeed
* EnableSixAxisSensorUnalteredPassthrough
* IsSixAxisSensorUnalteredPassthroughEnabled
* Get, GetOld
* SetAndWait, SetAndWaitOld
* IocParam
* IocFree

Demote services from warning/info to debug to reduce log spam

---

src/yuzu/configuration/configure_debug.cpp
src/yuzu/configuration/configure_debug.h
src/yuzu/configuration/configure_debug.ui

Configuration -> General -> Debug is getting a bit crowded.
yzct12345 submit this originally, so I'm tagging them as a co-author.
The original #6714 also modifies the Controls -> Player N sections,
but it looks like more work is needed to make the current area scrollable.
------
Looking at the pictures it seems like the size of the Configuration window is based on the default theme
Before 
After
Before Bright mode
After (default theme)
Before Midnight theme

Qt: Make General->Debug scrollable

---

.ci/templates/build-msvc.yml
.ci/yuzu-mainline-step2.yml
.ci/yuzu-patreon-step2.yml
.github/workflows/verify.yml

Since the following https://developercommunity.visualstudio.com/t/Type-alias-lookup-failure-within-paramet/10039150 compiler bug has been fixed, we can finally build with VS 2022 again.

ci: Enable building with Visual Studio 2022 (again)

---

src/input_common/drivers/sdl_driver.cpp

Currently motion is only detected on object creation. Since objects aren't destroyed motion is never enabled again when the controllers reconnects. This PR fixes the issue by always checking when a controller is connected
closes #8846 
closes #8763 
closes #7915
closes #7381

input_common: sdl: Always check for motion on reconnect

---

src/shader_recompiler/ir_opt/texture_pass.cpp
src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
src/video_core/shader_environment.cpp

Since the following commit: https://github.com/yuzu-emu/yuzu/commit/a83a5d2e4c8932df864dd4cea2b04d87a12c8760 , many games will refuse to boot unless the shader/pipeline cache has been invalidated.
Raises the shader/pipeline cache version to force an invalidation.

(shader/pipeline)_cache: Raise shader/pipeline cache version

---

src/dedicated_room/CMakeLists.txt

Doesn't appear to effect anything regular, but in both Linux and Windows builds it looks like our project has all the libraries available for linking. If this feature is turned off, there is only one thing that quit working, when linking yuzu-room it couldn't find a function called mbedtls_base64_decode
mbedtls is split into three libraries for some reason: 
mbedtls
mbedx509
mbedcrypto
mbedtls_base64_decode is in mbedcrypto
-----
fixes #8866  
ebuild in question https://github.com/gentoo-mirror/guru/blob/master/games-emulation/yuzu/yuzu-9999.ebuild

CMake: explicitly link mbedcrypto for yuzu-room

---

externals/CMakeLists.txt

Relevant Info: 
> CMake Warning (dev) at externals/dynarmic/CMakeLists.txt:16 (option):
>   Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
>   --help-policy CMP0077" for policy details.  Use the cmake_policy command to
>   set the policy and suppress this warning.
> 
>   For compatibility with older versions of CMake, option is clearing the
>   normal variable 'DYNARMIC_TESTS'.
> This warning is for project developers.  Use -Wno-dev to suppress it.
***
Thanks @lioncash for providing the fix.
> Reason for the warning is we're setting a normal cmake variable with the same name as an option before the option itself has been introduced.
> Since dynarmic already disables tests if it's not the main project, we can remove this line.

Fix Cmake warning for CMP0077

---

src/common/settings.cpp
src/common/settings.h
src/video_core/buffer_cache/buffer_base.h
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_graphics_advanced.cpp
src/yuzu/configuration/configure_graphics_advanced.h
src/yuzu/configuration/configure_graphics_advanced.ui
src/yuzu_cmd/config.cpp
src/yuzu_cmd/default_ini.h

This is a hack aimed to work around the issues caused by #8074. When enabled, it forces the buffer cache to continuously flush regions that were used by the GPU, even if they have since been modified by the CPU, which is incorrect. However, until we have a better memory tracking system, this is a stopgap to fix rendering problems in some games.

video_core: add option for pessimistic flushing

---

src/core/hid/emulated_controller.cpp

Since we use the same input for both triggers and buttons. Trigger inputs from GC controllers where overwriting the input of the ZL and ZR buttons. Usually not noticiable until you enable a property like toggle button.
Fixes #8862

core: hid: Fix GC triggers overwriting ZL and ZR buttons

---

src/audio_core/CMakeLists.txt
src/audio_core/audio_core.cpp
src/audio_core/audio_core.h
src/audio_core/device/audio_buffer.h
src/audio_core/device/audio_buffers.h
src/audio_core/device/device_session.cpp
src/audio_core/device/device_session.h
src/audio_core/in/audio_in_system.cpp
src/audio_core/out/audio_out_system.cpp
src/audio_core/renderer/adsp/audio_renderer.cpp
src/audio_core/renderer/behavior/behavior_info.cpp
src/audio_core/renderer/command/sink/device.cpp
src/audio_core/renderer/system_manager.cpp
src/audio_core/sink/cubeb_sink.cpp
src/audio_core/sink/cubeb_sink.h
src/audio_core/sink/null_sink.h
src/audio_core/sink/sdl2_sink.cpp
src/audio_core/sink/sdl2_sink.h
src/audio_core/sink/sink.h
src/audio_core/sink/sink_details.cpp
src/audio_core/sink/sink_stream.cpp
src/audio_core/sink/sink_stream.h
src/core/hle/result.h
src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp

Main purpose is to fix audio desync in games using audio out (notably XC3 cutscenes). Playback is now connected to core timing rather than being based on the realtime backend thread. 
Also removed the audio renderer queue and rely on the same stalling if it gets too large, this may cause an issue with coretiming underrunning though, so I might revert this if it's reported as a problem.
Closes #8857

[audio_core] Rework audio output

---

src/audio_core/renderer/command/effect/compressor.cpp

Same behavior, but also silences a `-Wcast-qual` warning, since the second cast casts away const.
Also two other minor changes that were noticed could be made.

compressor: Remove unneeded casts in ApplyCompressorEffect 

---

src/common/CMakeLists.txt

This pull request will gate the `xbyak` linkage behind an architecture detection for at least one part of yuzu buildable under non-x86_64 architectures (e.g. ARM).
This pull request is needed to build `yuzu-room` for aarch64 targets (see https://github.com/yuzu-emu/yuzu-multiplayer-dedicated/ for more details).

common: do not link to xbyak on non-amd64 architectures

---

src/yuzu/configuration/configure_tas.ui

Tools -> TAS -> Configure TAS
Thanks to Rei on discord for the fix.
Basically: openExternalLinks is a checkbox in Qt Creator

UI: Fix link to TAS help page

---

src/audio_core/audio_core.h
src/audio_core/audio_event.h
src/audio_core/audio_in_manager.h
src/audio_core/audio_manager.h
src/audio_core/audio_render_manager.h
src/audio_core/device/audio_buffers.h
src/audio_core/device/device_session.h
src/audio_core/in/audio_in_system.h
src/audio_core/out/audio_out_system.h
src/audio_core/renderer/adsp/adsp.h
src/audio_core/renderer/adsp/audio_renderer.h
src/audio_core/renderer/adsp/command_list_processor.h
src/audio_core/renderer/command/command_buffer.h
src/audio_core/renderer/command/command_generator.h
src/audio_core/renderer/command/mix/mix_ramp.cpp
src/audio_core/renderer/command/mix/mix_ramp.h
src/audio_core/renderer/command/mix/mix_ramp_grouped.h
src/audio_core/renderer/effect/effect_context.h
src/audio_core/renderer/effect/effect_info_base.h
src/audio_core/renderer/memory/address_info.h
src/audio_core/renderer/nodes/node_states.h
src/audio_core/renderer/performance/performance_manager.h
src/audio_core/renderer/upsampler/upsampler_manager.h
src/audio_core/renderer/voice/voice_info.h
src/audio_core/sink/cubeb_sink.h
src/audio_core/sink/sdl2_sink.h
src/audio_core/sink/sink.h
src/audio_core/sink/sink_stream.h

Resolves a wackload of  `-Wdocumentation` warnings due to mismatching tags and whatnot.
Separated them in case it's desirable to review them separately, but should be squashed when merging.

audio_core: Amend documentation comment tags

---

src/audio_core/audio_in_manager.cpp
src/audio_core/audio_out_manager.cpp
src/audio_core/renderer/audio_device.cpp
src/audio_core/renderer/audio_device.h
src/core/hle/service/audio/audout_u.cpp
src/core/hle/service/audio/audren_u.cpp

Allows the construction of the device name tables at compile-time and moves them to be internal to the audio_device.cpp file.

audio_device: Make AudioDeviceName constructor constexpr

---

.ci/scripts/linux/upload.sh
.ci/yuzu-patreon-step2.yml

Soft-requires yuzu-emu/liftinstall#28
The Early Access AppImage needs to be accessible through liftinstall, so a couple modifications need to made:
The DIR_NAME needs to not include the revision info.
The EA AppImage name cannot contain revision info.
The EA AppImage has to be packaged with the rest of the yuzu package, which means both binaries and the source are bundled with it now in an archive.
In addition, fix the source archive so yuzu can actually be built from it.
This also makes the yuzu mainline releases compatible with liftinstall and its shortcuts.

ci,linux: Support Patreon releases

---

src/common/CMakeLists.txt

Fixes CMake configuration when yuzu is a submodule of another project.

common: Use PROJECT_SOURCE_DIR to find CMakeModules

---

src/core/CMakeLists.txt

These are already present at the [bottom of the file](https://github.com/yuzu-emu/yuzu/blob/master/src/core/CMakeLists.txt#L799-L804) and guarded by the `ARCHITECTURE_x86_64` check.

core/CMakeLists.txt: Remove duplicate files.

---

.gitignore

Helps if you have multiple build folders. There are other, dark ways to hide extra build folders from git, but this is better.
See: https://github.com/citra-emu/citra/pull/6130
-----
I forgot to note it in the commit message, but git snooping in build folders is bad for performance.

GIT: Modify .gitignore to ignore wildcard for build directories

---

src/audio_core/audio_render_manager.cpp
src/audio_core/audio_render_manager.h
src/audio_core/device/audio_buffers.h
src/audio_core/device/device_session.cpp
src/audio_core/device/device_session.h
src/audio_core/in/audio_in.cpp
src/audio_core/in/audio_in.h
src/audio_core/in/audio_in_system.cpp
src/audio_core/in/audio_in_system.h
src/audio_core/out/audio_out.cpp
src/audio_core/out/audio_out.h
src/audio_core/out/audio_out_system.cpp
src/audio_core/out/audio_out_system.h
src/audio_core/renderer/adsp/adsp.cpp
src/audio_core/renderer/adsp/adsp.h
src/audio_core/renderer/adsp/audio_renderer.cpp
src/audio_core/renderer/adsp/audio_renderer.h
src/audio_core/renderer/audio_device.cpp
src/audio_core/renderer/audio_device.h
src/audio_core/renderer/behavior/behavior_info.cpp
src/audio_core/renderer/behavior/behavior_info.h
src/audio_core/renderer/behavior/info_updater.cpp
src/audio_core/renderer/behavior/info_updater.h
src/audio_core/renderer/effect/i3dl2.h
src/audio_core/renderer/effect/reverb.h
src/audio_core/renderer/nodes/node_states.h
src/audio_core/sink/sink_stream.h

Quite a bit of functions that don't modify member state weren't marked as const. This makes the interface a little more explicit about intended modifications.

audio_core: Mark several member functions as const

---

src/common/thread.h
src/core/core_timing.cpp
src/core/hle/service/nvflinger/nvflinger.cpp
src/core/hle/service/nvflinger/nvflinger.h

This re-works the vsync timing a bit for multi-core. After the core timing changes to make it more accurate, we can now use it for vsync flipping as well, which is an improvement over the current sleep method. 
Games in multicore should now be smoother, some quite noticeably (XC2), and can also boost FPS as well (again noticeably XC2), and also eliminates the time drift in Smash. 
Also fixes games that get locked to 58 FPS rather than 60, such as Three Hopes. Images courtesy of Dunastique (the frametime bar at the bottom):
Before: 
After:

[Coretiming/NVNFlinger] Improve multi-core vsync timing, and core timing accuracy

---

src/core/CMakeLists.txt
src/core/hle/service/am/applets/applet_mii_edit_types.h
src/core/hle/service/mii/mii.cpp
src/core/hle/service/mii/mii_manager.cpp
src/core/hle/service/mii/mii_manager.h
src/core/hle/service/mii/types.h
src/core/hle/service/nfp/amiibo_crypto.cpp
src/core/hle/service/nfp/amiibo_crypto.h
src/core/hle/service/nfp/amiibo_types.h
src/core/hle/service/nfp/nfp.cpp
src/core/hle/service/nfp/nfp.h
src/yuzu/main.cpp

After booting SSBU for the 1000th time this PR Implements full amiibo support. You can load and store data from amiibo dumps. A lot of thanks to jonbarrow for providing the data to translate mii data and amiitool that literally made this PR possible. Next implementation will probably implement an interface to manage amiibos. Since this PR only can modify the application area.
To be able to encode or decode amiibos `key_retail.bin` needs to be placed in the keys folder. [LockPick RCM v1.9.8](https://github.com/shchmue/Lockpick_RCM/releases/tag/v1.9.8) added support to dump amiibo keys.
WARNING: Since this feature is experimental it can corrupt your amiibo dumps. Please keep a backup.

core: nfp: Implement amiibo encryption

---

src/core/hle/service/audio/hwopus.cpp
src/core/hle/service/audio/hwopus.h

In order to fix the problem that DQX cannot enter the game.

core: implement HwOpus GetWorkBufferSizeForMultiStreamEx

---

src/audio_core/renderer/adsp/audio_renderer.cpp
src/audio_core/renderer/adsp/audio_renderer.h

This function is only ever called with unsigned types, and all of the other class functions take session_id as a u32, so this makes the class a little more consistent.

audio_renderer: Make GetCommandBuffer() take a u32

---

src/core/internal_network/network.cpp
src/core/internal_network/sockets.h

Other things shouldn't be able to directly mess around with the descriptor

sockets: Make fd member variable protected

---

src/common/settings.h
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_debug.cpp
src/yuzu/configuration/configure_debug.ui
src/yuzu/main.cpp
src/yuzu/startup_checks.cpp
src/yuzu/startup_checks.h

The startup check apparently confuses other programs when yuzu launches 2 processes and then quickly closes one of them. Though this isn't really our issue it's also not a big deal for me to add an option to work around that issue.
Notably Steam on Linux considers yuzu closed when the child process closes.

yuzu qt: Add option to disable startup Vulkan check

---

.ci/scripts/linux/docker.sh

This script still uses the old version of AppImageKit-checkrt (our fork with the `old` branch: https://github.com/yuzu-emu/AppImageKit-checkrt/tree/old), but now we use the shell script version so we can set our own environment variables as the application starts up.
This specific version searches for and sets the correct root CA file to prevent SSL errors in yuzu.
Supersedes #8871

ci/linux: Use AppRun.sh to start AppImage

---

src/yuzu/configuration/input_profiles.cpp

Currently the list order is kind of random. Sort profiles by name so it's easier to search a specific one

yuzu: sort input profiles by name

---

CMakeModules/GenerateSCMRev.cmake
src/common/CMakeLists.txt

> When run in -P script mode, CMake sets the variables [CMAKE_BINARY_DIR](https://cmake.org/cmake/help/latest/variable/CMAKE_BINARY_DIR.html#variable:CMAKE_BINARY_DIR), [CMAKE_SOURCE_DIR](https://cmake.org/cmake/help/latest/variable/CMAKE_SOURCE_DIR.html#variable:CMAKE_SOURCE_DIR), [CMAKE_CURRENT_BINARY_DIR](https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_BINARY_DIR.html?highlight=cmake_current#variable:CMAKE_CURRENT_BINARY_DIR) and [CMAKE_CURRENT_SOURCE_DIR](https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_SOURCE_DIR.html#variable:CMAKE_CURRENT_SOURCE_DIR) to the current working directory.
So if doing an out-of-source build, the `GetGitRevisionDescription` module will search the `.git` directory inside the build/binary directory and will not find it (hence the …

cmake: fix git detection

---

src/core/loader/loader.cpp

Avoids nullptr deref if `file` is invalid.

core/loader: Return nullptr if file is nullptr

---

.ci/scripts/linux/docker.sh

Recent versions of Docker appear to cause the Qt linuxdeploy plugin to throw a boost file copy error in some of our build containers (at the moment, specifically on the Patreon releases, but it's also happened on Mainline at least once? So mostly Azure.)
This switches from linuxdeploy to a [script of mine](https://github.com/lat9nq/deploy/blob/main/linux/deploy-linux.sh) I've been working on for a while.

ci/linux: Drop linuxdeploy usage

---

src/core/CMakeLists.txt
src/core/hle/service/hid/controllers/npad.cpp
src/core/hle/service/hid/controllers/palma.cpp
src/core/hle/service/hid/controllers/palma.h
src/core/hle/service/hid/errors.h
src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h

Originally I was going to fully implement this controller however I found that any meaningful feature was locked behind NSO. Like getting mew or having a Pokémon stored in the pokeball. So I lost all interest with this controller. This PR is just to add my progress in case someone else wants to finish the implementation.
This implementation allows you to select the pokeball controller and use it on Pokémon let's go. The controller works for the most part including motion. Loading and writing data to is not implemented.

service: hid: Partially implement palma controller

---

src/video_core/host_shaders/astc_decoder.comp
src/video_core/textures/astc.cpp

The moon of LIVE A LIVE is a 9-layer astc texture, but the data to be decoded is very strange, only the first two layers are normal, from the third layer onwards all are 0. I have not found the essential cause of this problem so far.
The current solution is to modify the fill value when an error occurs to prevent the wrong texture from being mixed in when sampling.
Before:
After:

video_core: Modify astc texture decode error fill value

---

src/video_core/renderer_opengl/gl_buffer_cache.cpp

Close #7171
Before：
After：
Before：
After：
This should fix more other games, more tests are welcome

Align index buffe size when vertex_buffer_unified_memory enable

---

src/core/hid/emulated_controller.cpp

#8724 fixed controller colours in `controller.colors_state.left` and copy-pasted the changes to `controller.colors_state.right`. However, while copy-pasting it, `controller.colors_state.right` was replaced with `controller.colors_state.left`!  
This pull request fixes that.

Fix "controller.colors_state.right" being "left"

---

src/core/CMakeLists.txt
src/core/hle/service/hid/hid.cpp
src/core/hle/service/ldn/lan_discovery.cpp
src/core/hle/service/ldn/lan_discovery.h
src/core/hle/service/ldn/ldn.cpp
src/core/hle/service/ldn/ldn_types.h
src/core/internal_network/network_interface.cpp
src/core/internal_network/network_interface.h
src/core/internal_network/socket_proxy.cpp
src/dedicated_room/yuzu_room.cpp
src/network/room.cpp
src/network/room.h
src/network/room_member.cpp
src/network/room_member.h
src/yuzu/main.cpp
src/yuzu/main.h
src/yuzu/main.ui
src/yuzu/multiplayer/chat_room.cpp
src/yuzu/multiplayer/client_room.cpp
src/yuzu/multiplayer/direct_connect.cpp
src/yuzu/multiplayer/direct_connect.h
src/yuzu/multiplayer/host_room.cpp
src/yuzu/multiplayer/host_room.h
src/yuzu/multiplayer/lobby.cpp
src/yuzu/multiplayer/lobby.h
src/yuzu/multiplayer/lobby_p.h
src/yuzu/multiplayer/message.cpp
src/yuzu/multiplayer/state.cpp
src/yuzu/multiplayer/state.h
src/yuzu/uisettings.h

This is the last and final part of a series of PRs aiming to bring multiplayer functionality to yuzu.
It fully implements the LDN service, making it possible to use games local wireless features in order to play online with other yuzu users.
For more information on how to use it, please take a look at our blog post.
First, a big thanks to the [ldn_mitm ](https://github.com/spacemeowx2/ldn_mitm) project and all of its contributors. Without it, and the gracious license exemption, all of this wouldn’t have been possible.
And of course, thanks to everyone who helped with this, especially @german77 and all of our testers.
As for the functionality of this feature, the code in lan_discovery is used to find and connect to other players in the yuzu room.
Afterwards data is transferred via the BSD …

ldn: Implement "local wireless" networked multiplayer

---

src/video_core/macro/macro_hle.cpp

Currently MultidrawIndirect Macro is bugged in the MacroJit. This PR **does not** aim to have a high level construct of MultidrawIndirect on the host but to replicate the original macro in C++ and be more useful for debugging purposes.
This shouldn't be merged until macro jit is fixed. As this macro HLE will hide the bug. @ogniK5377 I'de love if you could have a look.
This fixes most rendering issues in Monster Hunter Rise. There are still some medium rendering issues.

MacroHLE: Add MultidrawIndirect HLE Macro.

---

src/core/hle/service/nvflinger/nvflinger.cpp
src/core/hle/service/nvflinger/nvflinger.h
src/core/hle/service/vi/display/vi_display.cpp
src/core/hle/service/vi/display/vi_display.h
src/core/hle/service/vi/vi.cpp
src/core/hle/service/vi/vi_results.h

The display vsync event can only be retrieved once per display. Returns VI::ResultPermissionDenied if we attempt to retrieve the vsync event for the same display.
Prevents games such as .hack GU: Last Recode from consuming all the handles in the handle table by spamming vsync event retrievals and allows it to go in game.
Fixes #8991

service: vi: Retrieve vsync event once per display 

---

src/video_core/macro/macro_jit_x64.cpp

In the following macro, used by deko3d, the `bnz` instruction expects to cancel the exit flag when taken.
```
DrawIndexed::
fetch r6 # Fetch index count
1 to r2 # r2 = 1 (needed for later)
fetch r7 # Fetch instance count
DrawElementsFirst'0 to addr; fetch mem # Fetch first index
fetch r3 # Fetch vertex offset
*bnz r7 .cancelExit # Early exit if instance count is zero
DrawBaseVertex'1 to addr; fetch r4 # Fetch base instance
.cancelExit
r3 to mem # Update DrawBaseVertex
```
This PR fixes the branch emission to avoid exiting after executing a taken branch. Now it will only exit after executing a non-taken branch. The delay slot is still respected for both cases.

macro_jit_x64: cancel exit for taken branch

---

src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
src/video_core/renderer_vulkan/vk_staging_buffer_pool.h

Bumps default staging buffer size to 256MiB (this is well-supported by Vulkan PC games so it should be fine)
Further increases the staging buffer size to 1GiB if the graphics device has enough memory available and supports this usage

vulkan: automatically use larger staging buffer sizes when possible

---

src/web_service/web_backend.cpp

httplib.h has enum class Error, I suspect Connection might be most common
This might help if SSL issues crop up again
------
Intent here is to get more information out into logs without a bother.
Before
`[  10.674559] WebService <Error> web_service\web_backend.cpp:GenericRequest:115: POST to https://api.yuzu-emu.org/jwt/internal returned null`
After
`[  10.674559] WebService <Error> web_service\web_backend.cpp:GenericRequest:115: POST to https://api.yuzu-emu.org/jwt/internal returned null (httplib Error:Connection)`
When verification button is pressed, get three lines, only touching first line. 
```
[  10.674559] WebService <Error> web_service\web_backend.cpp:GenericRequest:115: POST to https://api.yuzu-emu.org/jwt/internal returned null (httplib Error:Connection)
[  10.674642] WebService …
```

Show error from cpp-httplib when we don't have a response to read (report errors while connecting to API)

---

src/audio_core/renderer/adsp/audio_renderer.cpp
src/audio_core/renderer/system_manager.cpp
src/common/logging/backend.cpp
src/core/core_timing.cpp
src/core/cpu_manager.cpp
src/core/debugger/debugger.cpp
src/core/hle/kernel/k_worker_task_manager.cpp
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/service_thread.cpp
src/core/hle/service/nvflinger/nvflinger.cpp
src/input_common/drivers/gc_adapter.cpp
src/input_common/drivers/mouse.cpp
src/input_common/drivers/sdl_driver.cpp
src/video_core/gpu_thread.cpp
src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
src/video_core/renderer_vulkan/vk_scheduler.cpp
src/video_core/textures/astc.cpp
src/yuzu/bootmanager.cpp

Thread names in certain platforms are limited to [15 safe characters](https://man7.org/linux/man-pages/man3/pthread_setname_np.3.html), for unfathomable reasons. This change helps more thread names stay intact when debugging.

common: remove "yuzu:" prefix from thread names

---

src/dedicated_room/CMakeLists.txt

CMake is able to automatically install binaries in the correct location. Also see my older patch, https://github.com/yuzu-emu/yuzu/commit/af94bf4a594b6a3599fae1d78e5d283b9f602032
Cc: @FearlessTobi

build(room): simplify yuzu-room installation

---

src/core/file_sys/program_metadata.cpp
src/core/file_sys/program_metadata.h

Undefined Behaviour Sanitizer identified a reference binding to a misaligned address when logging the acid_file_access permissions. Copy the value into a variable before sending it to fmt.
Issue was found while booting SSBU.

program_metadata: Avoid reference binding to misaligned address

---

src/yuzu/main.cpp

On Windows there are currently two fonts used.
The first, does the Menu, QTreeView and Tooltips
Second is Everything else which is a default font.
From inspecting QApplication::font() at runtime
Windows 10 English: QFont(MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0)
Windows 11 Japanese:        MS UI Gothic,9   ,-1,5,50,0,0,0,0,0
Windows 11 Traditional Chinese: PMingLiU,9   ,-1,5,50,0,0,0,0,0
Windows 11 Simplified Chinese:    SimSun,9   ,-1,5,50,0,0,0,0,0
Windows 11 Korean:                 Gulim,9   ,-1,5,50,0,0,0,0,0
I initially investigated dynamically changing the font when
the UI language is English, but this was getting quite messy
Qt6 makes changes to default font in some situations, so this
PR is being narrowed in scope to only effect Chinese font choices.
This change only effects …

Qt: work around Qt5's font choice for Chinese (in Windows)

---

src/yuzu/configuration/configure_graphics.cpp

The graphics API setting should not be changed when a game is running.
Fixes a regression introduced in #8564

configure_graphics: Fix graphics API selection when a game is running

---

CMakeLists.txt
externals/ffmpeg/CMakeLists.txt
externals/libusb/CMakeLists.txt

The keyword `REQUIRED` is valid for [find_package](https://cmake.org/cmake/help/latest/command/find_package.html), not for [include](https://cmake.org/cmake/help/latest/command/include.html).

cmake: Fix FindPkgConfig

---

src/video_core/buffer_cache/buffer_cache.h
src/video_core/dirty_flags.cpp
src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_3d.h
src/video_core/gpu.h
src/video_core/macro/macro_hle.cpp
src/video_core/query_cache.h
src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
src/video_core/renderer_opengl/gl_graphics_pipeline.h
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_opengl/gl_state_tracker.cpp
src/video_core/renderer_opengl/maxwell_to_gl.h
src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
src/video_core/renderer_vulkan/fixed_pipeline_state.h
src/video_core/renderer_vulkan/maxwell_to_vk.cpp
src/video_core/renderer_vulkan/maxwell_to_vk.h
src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
src/video_core/renderer_vulkan/vk_rasterizer.cpp
src/video_core/renderer_vulkan/vk_state_tracker.cpp
src/video_core/shader_cache.cpp
src/video_core/shader_environment.cpp
src/video_core/shader_environment.h
src/video_core/surface.cpp
src/video_core/texture_cache/image_info.cpp
src/video_core/texture_cache/texture_cache.h
src/video_core/transform_feedback.cpp
src/video_core/transform_feedback.h

Updates the 3D engine registers based on nVidia's recently-released docs. 
The idea of this PR is just to rename, not implement new functionality, and keep execution identical wherever possible. So there's multiple places now which seem a bit silly in code, but I didn't want to alter them. There shouldn't be any regressions introduced here, fingers crossed. A lot of potential bugfixes have opened up though with these new regs, should anyone want to go through them.
There may be some small accidental fixes due to some registers being incorrectly sized, for instance `small_index` (now `index_buffer32_first`) having too large of a count field, so we would read some junk data as vertices. This kind of thing wasn't an intentional fix though.

[video_core] Update 3D registers

---

src/common/input.h
src/core/hid/input_converter.cpp
src/input_common/input_poller.cpp

Gcc 12 and 13 complain that the camera vector is not initialized when it's initialized by default. Since we don't really need two vectors in this struct we simply have one that is shared to all input types and split and join the data as needed.

input_common: have an unique vector in callback status

---

.ci/scripts/windows/docker.sh

Conceptually a revert of #8455
Using MinGW in the future may not be ideal as it does not work very well with crash dumps (#8682).
Switch back to GCC on MinGW. This also gives CI a way to check GCC 12 (as of writing, or whatever version of mingw-gcc Arch happens to be shipping on a given week).

ci/windows: Revert to using GCC for MinGW builds

---

src/video_core/dirty_flags.cpp
src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_3d.h
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_state_tracker.cpp
src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
src/video_core/renderer_vulkan/vk_rasterizer.cpp
src/video_core/renderer_vulkan/vk_state_tracker.cpp

nVidia in their wisdom decided that front and back stencil masks should be a different order. Front uses func_mask/mask, whereas back uses mask/func_mask. This was causing specifically the back stencil masks to be flipped around. Thanks to @bylaws for pointing it out.
Also changed geometry clip to match previous behaviour. Don't know if this affects any games, and I think previous behaviour is certainly wrong, but keeping it there just in case.

[video_core] Fix stencil mask registers

---

src/core/core_timing.cpp

It is not necessary to perform extra spinning on other platforms since Linux has working high-precision sleeps, and hurts performance in lower-end setups. Might fix #9037.

core_timing: use high-precision sleeps on non-Windows targets

---

src/core/hle/result.h

Creates a linker error instead of a runtime assert message.

result: enforce reference check specialization

---

src/core/hle/service/friend/friend.cpp

This was renamed some time after 10.0.0 from IsFriendListCacheAvailable to CheckFriendListAvailability.

IFriendService: stub CheckFriendListAvailability

---

src/audio_core/sink/cubeb_sink.cpp
src/audio_core/sink/cubeb_sink.h
src/audio_core/sink/sdl2_sink.cpp
src/audio_core/sink/sdl2_sink.h
src/audio_core/sink/sink_details.cpp
src/audio_core/sink/sink_details.h
src/yuzu/configuration/configure_audio.cpp

Currently we only select cubeb with the auto option, but some audio devices report really large latencies from cubeb, which causes problems with playback, this PR just tests cubeb before selecting it, switching to SDL if cubeb fails to init or the latency is too large (threshold relatively random).

Auto select the SDL audio backend when Cubeb latency is too high

---

src/video_core/engines/maxwell_3d.h
src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_vulkan/fixed_pipeline_state.cpp

This should be assigned CW only on `Triangles_CW` rather than not `Triangles_CCW`, making CCW the default winding order rather than CW.

renderer_(opengl/vulkan): Fix tessellation clockwise parameter

---

src/audio_core/sink/sink_details.cpp

Originally SDL audio backend is called `sdl2`. #9039 changed the name to just `sdl`. This PR reverts the name to keep compatibility with older versions.

audio_core: Revert sink name to sdl2

---

src/core/arm/dynarmic/arm_dynarmic_64.cpp
src/core/hle/ipc_helpers.h
src/core/hle/kernel/k_client_session.cpp
src/core/hle/kernel/k_client_session.h
src/core/hle/kernel/k_server_session.cpp
src/core/hle/kernel/k_server_session.h
src/core/hle/kernel/svc.cpp
src/core/hle/kernel/svc_wrap.h
src/core/hle/service/ns/ns.cpp
src/core/hle/service/ns/ns.h
src/core/hle/service/ptm/ts.cpp
src/core/hle/service/ptm/ts.h
src/core/hle/service/set/set_sys.cpp
src/core/hle/service/set/set_sys.h
src/core/hle/service/sm/sm.cpp

[nx-hbloader](https://github.com/switchbrew/nx-hbloader/), or hbl.nsp, sets up the launch arguments for all .nro style homebrew and performs the jump to the running application. These changes allow unmodified versions of nx-hbloader and [nx-hbmenu](https://github.com/switchbrew/nx-hbmenu) to work, but launching applications from nx-hbmenu is not yet working (needs extra support from nvnflinger).

Preliminary support for nx-hbloader

---

src/audio_core/sink/sdl2_sink.cpp

Attempting to place a null string into a vector of strings causes an error that closes the application, which SDL_GetAudioDeviceName will return in case of error, so don't do that.
Additionally, ListSDLSinkDevices's prototype appears to care whether we are loading capture devices or not, and SDL_GetAudioDeviceName has a parameter to use that information, but for some reason we just default to loading non-capture devices in both cases. Instead, tell it to distinguish either case.
Addresses a regression by #9039

sdl2_sink: Avoid loading a null string into a vector

---

.ci/scripts/transifex/docker.sh
.github/workflows/ci.yml

Pushing to transifex didn't work in https://github.com/yuzu-emu/yuzu/pull/9058
I did some tests on my own fork, and we're writing to ~/.transifexrc but the client can't seem to read that file. maybe issue with $HOME or something.
Workaround is to set TX_TOKEN environment variable and now the pesky ~/.transifexrc file is not needed.
-----
Took me awhile to figure out, but basically GHA sets HOME to /github/home regardless of how the particular container wants to do things. Most tools read the environment (from the failed log, at least the shell and vcpkg read $HOME), but the transifex tool is going to /etc/passwd and looking up the home directory for the current user, so in our case its looking for /root/.transifexrc instead of /github/home/.transifexrc …

Set TX_TOKEN for transifex client

---

src/core/file_sys/savedata_factory.cpp
src/core/file_sys/savedata_factory.h
src/yuzu/main.cpp

Enable compatibility for new account/device save paths planned on a future implementation.

savedata_factory: Detect future save data paths

---

src/common/concepts.h
src/common/fixed_point.h

We can use concepts to make all of the SFINAE shenanigans significantly less noisy and also collapse the implemented comparison functions in the class down to a single line.
While we're at it, we can make several other functions constexpr, and also make `to_uint()` actually work if it ever gets instantiated.
Also resolves some uninitialized reads that take place in several parts of the audio codebase with the last commit.

common/fixed_point: Minor interface improvements

---

src/yuzu/applets/qt_controller.ui

Remember that time we renamed the Undocked option to Handheld in the status bar, and then later remembered the Controller Configuration?
Scrolling through Transifex I noticed that we still have one instance of "Undocked" in the text.

Controller Applet had instance of Undocked, make Handheld

---

src/core/CMakeLists.txt
src/core/hle/ipc_helpers.h
src/core/hle/kernel/hle_ipc.cpp
src/core/hle/kernel/hle_ipc.h
src/core/hle/kernel/init/init_slab_setup.cpp
src/core/hle/kernel/k_client_session.cpp
src/core/hle/kernel/k_linked_list.h
src/core/hle/kernel/k_page_buffer.h
src/core/hle/kernel/k_server_session.cpp
src/core/hle/kernel/k_server_session.h
src/core/hle/kernel/k_session_request.cpp
src/core/hle/kernel/k_session_request.h
src/core/hle/kernel/k_shared_memory_info.h
src/core/hle/kernel/k_thread_local_page.h
src/core/hle/kernel/kernel.h
src/core/hle/kernel/slab_helpers.h
src/core/hle/service/sm/sm_controller.cpp

Some preliminary IPC handling refactoring for multiprocess.
- Adds KSessionRequest from upstream to track the state of pending requests
- Removes most SessionRequestManager behavior from KServerSession
Next step will likely be to start inverting the way sessions are handled (from a push-based system to a pull system).

kernel: Session request cleanup

---

src/video_core/texture_cache/format_lookup_table.cpp

This format is similar to Z32_FLOAT_X24S8_UINT, which is implemented with D32_FLOAT_S8_UINT.
Used in Persona 5 Royal
Note: This does not resolve the black screen issues

format_lookup_table: Implement R32_B24G8 with D32_FLOAT_S8_UINT

---

src/core/hle/service/hid/controllers/npad.cpp

Previously this was passing the size of the vector into memcpy rather than the size in bytes to copy, which would result in a partial copy.
Thankfully, this function isn't used yet, so this gets rid of a bug before it's able to do anything.

hid/npad: Fix copy size in GetSupportedNpadIdTypes

---

src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/puller.cpp

This fixes up the remaining YFc Part 1 regressions on ACNH and Splatoon 2. Additionally (with nvidia's 3d engine docs) we fixed somethings that were incoherent or made no sense according to official docs.

Maxwell3D/Puller: Fix regressions and syncing issues.

---

src/core/hle/service/nvdrv/nvdrv.cpp
src/core/hle/service/nvdrv/nvdrv.h

If nvdrv got destroyed before guest code closed all open fds to nvdec, then an unavoidable crash would occur with libstdc++, because the nvdec common destructor would attempt to access the NvCore::Container belonging to nvdrv, but it had been destroyed already due to the order of its class members. This fixes that.

nvdrv: fix container destruction order

---

src/core/core.cpp
src/core/hle/kernel/kernel.cpp
src/core/hle/service/nvflinger/nvflinger.cpp
src/core/hle/service/nvflinger/nvflinger.h
src/core/hle/service/service.cpp
src/core/hle/service/service.h

Service threads are managed by a separate thread worker to force serialization. This includes their shutdown. This meant previously that if there was too long of a delay between core shutting down and the service thread shutting down, it could continue to use objects that belonged to the now-destroyed system instance, which would crash.
To prevent this, I added a barrier. However, due to waiting on a host mutex, sometimes an IHOSBinderDriver thread would get stuck. If this was a guest thread, this would not be an issue, since it could just be killed. However, it is a host thread, so I have added some improper hierarchy to ensure that NVNFlinger forces all binder layers to stop waiting before shutdown.

core: barrier service thread shutdown

---

src/common/input.h
src/core/hid/emulated_controller.cpp
src/core/hid/emulated_controller.h
src/core/hle/service/hid/controllers/npad.cpp
src/input_common/drivers/gc_adapter.cpp
src/input_common/drivers/gc_adapter.h
src/input_common/drivers/sdl_driver.cpp
src/input_common/drivers/sdl_driver.h
src/input_common/input_engine.h
src/input_common/input_poller.cpp

Due to controller compatibility reasons vibration test take a bit of time.  For this reason we only test once then return the cached value afterwards. This fixes once more fps drops caused by the game testing vibration all the time.

input_common: cache vibration tests

---

src/core/hid/emulated_controller.cpp
src/core/hle/service/nfp/amiibo_crypto.cpp
src/core/hle/service/nfp/amiibo_crypto.h
src/core/hle/service/nfp/nfp_device.cpp
src/core/hle/service/nfp/nfp_device.h
src/core/hle/service/nfp/nfp_types.h
src/core/hle/service/nfp/nfp_user.cpp
src/core/hle/service/nfp/nfp_user.h

Since many users  started using outdated builds instead of dumping the amiibo keys. I decided to add a little workaround by marking amiibos as read only when keys are missing. This enables basic detection of amiibos.
No fallbacks are given to keep the code accurate. Games that use decrypted data will still need keys.

service: nfp: Allow amiibos without keys

---

src/core/hle/kernel/global_scheduler_context.cpp
src/core/hle/kernel/global_scheduler_context.h
src/core/hle/kernel/k_scheduler.cpp
src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/k_thread.h

This allows host threads to call KSynchronizationObject::Wait without crashing, which is required to implement the HIPC server manager. V2, actually works this time.

kernel: refactor dummy thread wakeups

---

src/audio_core/in/audio_in_system.cpp
src/audio_core/in/audio_in_system.h
src/audio_core/out/audio_out_system.cpp
src/audio_core/out/audio_out_system.h
src/core/hle/service/audio/audin_u.cpp
src/core/hle/service/audio/audout_u.cpp

applet_resource_user_id isn't actually modified and is just assigned to a member variable, so this doesn't need to be a mutable reference.
Similarly, the device name itself isn't modified and is only moved. We pass by value here, since we can still perform the move, but eliminate a sneaky set of calls that can unintentionally destroy the original string. Given how nested the calls are, it's good to get rid of this potential vector for a use-after-move bug.

audio_in/out_system: Pass Initialize members by value where applicable

---

src/shader_recompiler/frontend/ir/microinstruction.cpp
src/shader_recompiler/frontend/ir/value.h
src/shader_recompiler/ir_opt/dead_code_elimination_pass.cpp

Reverts yuzu-emu/yuzu#8068
Close #8788
This PR incorrectly removes the if branch that should not be removed, resulting in partial implementation of ts' compute shader being removed.
Doesn't feel necessary to add so much code to do this，the host compiler is probably going to optimize that.
Before:
After:

Revert "shader_recompiler/dead_code_elimination: Add DeadBranchElimination pass"

---

src/video_core/renderer_vulkan/vk_rasterizer.cpp

This is just a temporary solution,  Auxiliary shader needs to be added to perform specified channel clear.
Fix p5r's battle scenes black.

video_core: Catch vulkan clear op not all channel need clear

---

src/core/hle/kernel/k_server_session.h
src/core/hle/service/sm/sm.cpp

Fixes two issues which arose after #9078:
- KPort is intended to be owned only by the client port and server port. Therefore Close() should never be called on it except by the KClientPort and KServerPort Destroy method. The client port is closed immediately which then closed the parent. This caused the server port to later try to reference invalid memory when closing.
- m_current_request in KServerSession wasn't default-initialized, and caused CleanupRequests to sometimes reference invalid memory.

k_server_session: fix crashes

---

src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_ui.cpp
src/yuzu/configuration/configure_ui.ui
src/yuzu/game_list.cpp
src/yuzu/uisettings.h

Option is added directly below the option for the addons column
Defaulting to hide compatibility list. Changing default works properly.
-----
New option
I made sure to test the default because I don't want to see users needing help turning the compatibility list back on when we're ready to show it again.

UI: Add option to hide the compatibility list

---

src/core/core.cpp

Fixes a crash when changing the dram size introduced by #9071

kernel: reinitialize after dram layout change

---

src/video_core/renderer_vulkan/vk_texture_cache.cpp

Fixes bayonetta 3's white screen on Vulkan.

Vulkan: Fix regression caused by limiting render area to width/height of render targets.

---

src/core/hle/service/sm/sm.cpp
src/core/hle/service/sm/sm_controller.cpp

Follow up to #9148
Since the current code intends for the port to be closed immediately, it should be closed immediately. This prevents the KPort slab heap from running out of space. Furthermore, the port cannot be referenced when cloning the object, since it will have been closed at that point, so the implementation of CreateSession should be used instead.
Fixes crashes in Pokemon: Let's Go (Pikachu/Eevee) and Sword, and probably other games.

kernel: more complete fix for KPort reference counting

---

src/video_core/renderer_vulkan/vk_scheduler.h

`recorded_counts` was never reset to 0 which could lead to the scheduler submitting empty chunks. It's only used to check whether the chunk is empty and we can just use the offset to do that.

vk_scheduler: Remove recorded_counts

---

src/core/hle/service/acc/acc.cpp
src/core/hle/service/acc/acc.h
src/core/hle/service/acc/acc_u0.cpp
src/core/hle/service/acc/profile_manager.cpp
src/core/hle/service/acc/profile_manager.h

- These APIs are used to capture the opened users and allow that state to be persisted across processes.
- They are not intended to just return the system opened users, that is what ListOpenUsers is for.
- Fixes the launch hang with Bayonetta 3.

core: hle: service: acc: Fix ListOpenContextStoredUsers/StoreOpenContext.

---

src/video_core/renderer_vulkan/vk_blit_screen.cpp
src/video_core/renderer_vulkan/vk_blit_screen.h

This allows applications that don't use the RGBA8 buffer format to render correctly when launched from hbmenu, and not flicker incessantly.
|Frame|Before|After|
|-|-|-|
|Odd|![010000000000100d_2022-10-30_15-06-30-738](https://user-images.githubusercontent.com/9658600/198896966-ff5f86c8-28df-4291-bba1-211ac256e621.png)|![010000000000100d_2022-10-30_15-05-11-258](https://user-images.githubusercontent.com/9658600/198896974-3e644738-58da-4db6-9993-0859227ba023.png)|
|Even|![010000000000100d_2022-10-30_15-06-14-010](https://user-images.githubusercontent.com/9658600/198896992-b875292a-1ff9-4524-9bac-e42eb1598064.png)|![010000000000100d_2022-10-30_15-05-11-258](https://user-images.githubusercontent.com/9658600/198896974-3e644738-58da-4db6-9993-0859227ba023.png)|

vk_blit_screen: recreate swapchain images on guest format change

---

src/core/hle/ipc_helpers.h
src/core/hle/kernel/hle_ipc.cpp
src/core/hle/kernel/hle_ipc.h
src/core/hle/kernel/k_client_port.cpp
src/core/hle/kernel/k_client_port.h
src/core/hle/kernel/k_port.cpp
src/core/hle/kernel/k_server_port.cpp
src/core/hle/kernel/k_server_port.h
src/core/hle/kernel/k_server_session.cpp
src/core/hle/kernel/k_server_session.h
src/core/hle/kernel/k_session.cpp
src/core/hle/kernel/k_session.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/kernel.h
src/core/hle/kernel/service_thread.cpp
src/core/hle/kernel/service_thread.h
src/core/hle/kernel/svc.cpp
src/core/hle/service/service.cpp
src/core/hle/service/service.h
src/core/hle/service/sm/sm.cpp
src/core/hle/service/sm/sm.h
src/core/hle/service/sm/sm_controller.cpp

This is a major refactor of how service handling works for multiprocess. This is required as the first step for properly demoting services to userspace processes (where they belong). It removes essentially all of the remaining HLE IPC logic from KServerSession and places it into the session manager.
With this, instead of pushing requests to services, service threads will wait for and pull the requests themselves. There is still much more that is blocked on the kernel and service processes not having their own emulated address spaces, but this is out of scope for these changes.

kernel: invert session request handling flow

---

src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp

This is required for fix from vonchenplus, requires shader cache invalidation.

Update shader cache version.

---

CMakeLists.txt
src/yuzu/CMakeLists.txt
src/yuzu/main.cpp
src/yuzu/main.h

Covers #7614 ([via](https://www.freshports.org/deskutils/xdg-desktop-portal)), #8585 ([via](https://www.freshports.org/sysutils/consolekit2)), #8592, #8647 for systems like FreeBSD or Solaris. macOS is excluded (like before) due to not defining `__unix__`.
Splitting conditionals for granular commits is error-prone, so I didn't bother.

Qt: enable recent Linux features on BSDs

---

src/core/hle/kernel/hle_ipc.cpp
src/core/hle/kernel/hle_ipc.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/kernel.h

Service threads must be deleted by a different thread than the one requesting the thread to be deleted, or a deadlock will occur. The following code raced the queuing of the service thread for removal, and if won, nothing would happen.
```cpp
SessionRequestHandler::~SessionRequestHandler() {
kernel.ReleaseServiceThread(service_thread.lock());
}
```
However, if it lost, then the service thread would be destroyed when the shared_ptr generated from the call to `lock()` went out of scope. This would cause the service thread to try to delete itself and deadlock. This was observed to occur somewhat reliably on Asahi Linux.
To ensure this will never happen anymore, I removed all weak_ptr and shared_ptr ownership of service threads and only return direct references from KernelCore. That way, …

service_thread: fix deletion

---

src/core/hle/kernel/k_scheduler.cpp
src/core/hle/kernel/k_scheduler_lock.h

These fences are absolutely required for correctness on arm64 (yuzu encounters consistency errors and crashes without them). The seq_cst ordering of the adjacent atomic stores do not provide the proper ordering guarantees.

Ensure correctness of atomic store ordering

---

src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/k_thread.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/kernel.h
src/core/hle/kernel/service_thread.cpp

This is the next step in the conversion of services to userspace. After tweaking the SVC code, many SVCs will become callable from service thread context.

kernel: assign KProcess to service threads

---

src/core/hle/ipc_helpers.h
src/core/hle/kernel/init/init_slab_setup.cpp
src/core/hle/kernel/k_client_port.cpp
src/core/hle/kernel/k_event.cpp
src/core/hle/kernel/k_memory_block.h
src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_process.cpp
src/core/hle/kernel/k_resource_limit.cpp
src/core/hle/kernel/k_resource_limit.h
src/core/hle/kernel/k_session.cpp
src/core/hle/kernel/k_shared_memory.cpp
src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/k_transfer_memory.cpp
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/service_thread.cpp
src/core/hle/kernel/svc.cpp
src/core/hle/kernel/svc_types.h
src/core/hle/service/kernel_helpers.cpp
src/core/hle/service/sm/sm_controller.cpp

Updates svc_types.h to provide updated upstream definitions for all SVCs.

kernel/svc_types: refresh

---

src/common/settings.cpp

According to the contributing page (https://github.com/yuzu-emu/yuzu/wiki/Contributing) the default cases should have a break statement
default:
// Yes, even break for the last case
break;

Add break statement in default cases

---

src/yuzu/main.cpp
src/yuzu/main.h

Requested by Italian translator (Fs00 in Discord)
"Remove Installed Game %1?"
"Error Removing %1"
I didn't press for translated strings, so have a taste direct from deepl
Rimuovere il contenuto del gioco installato?
Rimuovere l'aggiornamento del gioco installato?
Rimuovere il DLC del gioco installato?
-------
UI Element in question
Request from our discord 
> Hello everyone! I've found out an issue regarding a particular translatable string in Yuzu: "Remove Installed Game %1?".
Since I wasn't able to understand what the placeholder was for, I dug into the code and discovered that the %1 can get replaced with Contents, Update or DLC (https://github.com/yuzu-emu/yuzu/blob/master/src/yuzu/main.cpp#L1999-L2016).
The problem is that the code is assuming that the part leading to the placeholder …

UI: split up strings relating to content removal

---

src/shader_recompiler/frontend/maxwell/translate_program.cpp
src/shader_recompiler/host_translate_info.h
src/shader_recompiler/ir_opt/passes.h
src/shader_recompiler/ir_opt/texture_pass.cpp
src/video_core/engines/maxwell_3d.h
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_opengl/gl_state_tracker.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
src/video_core/renderer_vulkan/vk_rasterizer.cpp
src/video_core/renderer_vulkan/vk_state_tracker.cpp
src/video_core/shader_environment.cpp

Adds a new entry `support_snorm_render_buffer` to determine whether the host device supports rendering to SNORM render buffers.

ir/texture_pass: Use host_info instead of querying Settings::values

---

src/yuzu/main.cpp

Doesn't differentiate real cores from threads, but it's a safe global way.

Add CPU thread count to log files

---

src/yuzu/compatdb.cpp
src/yuzu/compatdb.h
src/yuzu/compatdb.ui
src/yuzu/game_list_p.h
src/yuzu/main.cpp

This PR brings several improvements to the compatibility submission system, aimed at improving the quality of user reports:
- Only users that match our recommended system requirements are able to submit reports
- The submission form is now multi-page and asks specific questions from which it determines the compatibility status
- The compatibility categories and their descriptions have been renamed to be more clear and the "Okay" category has been removed
Thanks to @german77 for providing an initial implementation of this concept.
Feedback on these changes is highly appreciated.

yuzu/compatdb: Improve compatibility submission system

---

src/common/x64/cpu_detect.cpp
src/common/x64/cpu_detect.h
src/yuzu/main.cpp

[GetLogicalProcessorInformation](http://msdn.microsoft.com/en-us/library/ms683194) is used for Windows, which is a chore and a half.
Linux checks for the existence of SMT, as @liamwhite suggested.

Add CPU core count to log files

---

src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_3d.h
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
src/video_core/renderer_vulkan/fixed_pipeline_state.h
src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp

In my regs PR I removed regs which weren't listed in nVidia's official docs, but that caused regressions in some games due to losing the `invalidate_texture_data_cache` register. I don't know if this reg is correct or not, but we know there are regs which were redacted from the docs, and it seems we do need something to trigger GPU cache invalidation, so I've added it back.
I also added back conservative raster for Vulkan, not sure if the reg is correct or if conservative raster affects any games. Also fixes a mistake with two-sided stencils on OpenGL.
This PR fixes the weird blocky patterns in XC3, and likely helps other games.

[video_core] Fix a couple regs regressions

---

src/yuzu/main.cpp

Turns out, not having an ARM device to test can be a problem.

Ignore ARM for core count

---

src/core/debugger/debugger.cpp
src/core/debugger/gdbstub.cpp
src/core/debugger/gdbstub.h
src/core/hle/kernel/k_page_table.h

Fixes some issues with the debugger:
- yuzu would continue to accept connections after the debugger had already connected, but would never respond to them. This led to confusing gdb behavior if connection had to be re-attempted. Now connections can be re-attempted any number of times, and the previous connection will be closed.
- The `monitor` commands supported by ams dmnt.gen2, which provide printouts of various process information, including memory regions, were not implemented. This implements basic support.

Debugger improvements

---

src/yuzu/configuration/configure_profile_manager.cpp
src/yuzu/configuration/configure_profile_manager.h
src/yuzu/configuration/configure_profile_manager.ui

I was prompted to add this after a user deleted their user profile and found out that it also deleted all the associated save data for that user.
This adds a hopefully more informative dialog that most importantly notifies the user that their saves will be deleted with the user profile. It shows the profile icon, name, and UUID in the dialog.
While I was in this segment of the configuration, I also removed the frame from the profile picture in the manager, since it caused the image to be offset by 1px and cropped by 2px.

configure_profile_manager: Use a custom dialog when deleting a profile

---

externals/microprofile/microprofileui.h

Allows yuzu to be built with Clang 15.

externals: microprofileui: Remove unused variables

---

src/yuzu_cmd/yuzu.cpp

According to the contributing page (https://github.com/yuzu-emu/yuzu/wiki/Contributing) the default cases should have a break statement

Add break statement in default case

---

src/audio_core/renderer/performance/performance_manager.cpp
src/common/atomic_helpers.h
src/core/hle/kernel/init/init_slab_setup.cpp
src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_process.cpp
src/core/hle/service/am/applets/applet_error.cpp
src/core/hle/service/am/applets/applet_general_backend.cpp
src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
src/core/hle/service/service.cpp
src/core/hle/service/time/time_zone_manager.cpp
src/video_core/engines/maxwell_dma.cpp
src/video_core/engines/puller.cpp
src/video_core/macro/macro_interpreter.cpp
src/video_core/macro/macro_jit_x64.cpp
src/video_core/renderer_opengl/gl_texture_cache.cpp
src/video_core/renderer_opengl/renderer_opengl.cpp
src/video_core/renderer_vulkan/vk_scheduler.cpp
src/video_core/renderer_vulkan/vk_texture_cache.cpp
src/video_core/textures/decoders.cpp
src/yuzu/compatdb.cpp
src/yuzu/main.cpp
src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp
src/yuzu_cmd/yuzu.cpp

Visual Studio has an option to search all files in a solution, so I did a search in there for "default:" looking for any missing break statements.
I've left out default statements that `return` something, and that `throw` something, even if via `ThrowInvalidType`
----
UNREACHABLE() also throws
Follow-up to #9217  #9228

Add break for default cases

---

src/common/CMakeLists.txt
src/common/cache_management.cpp
src/common/cache_management.h
src/core/hle/kernel/svc.cpp
src/core/hle/kernel/svc_wrap.h
src/core/memory.cpp
src/core/memory.h

x86 does not need to do anything special to ensure the program data cache behaves as intended, but arm64 does.

kernel: implement data cache management operations

---

src/shader_recompiler/backend/glasm/emit_glasm.cpp
src/shader_recompiler/backend/glasm/emit_glasm_context_get_set.cpp
src/shader_recompiler/backend/glsl/emit_glsl_context_get_set.cpp
src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
src/shader_recompiler/backend/spirv/spirv_emit_context.cpp

Fix Pokemon Scarlet/Violet Black screen.

shader: Implement miss attribute layer

---

src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_3d.h
src/video_core/macro/macro_hle.cpp
src/video_core/rasterizer_interface.h
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_rasterizer.h
src/video_core/renderer_vulkan/vk_rasterizer.cpp
src/video_core/renderer_vulkan/vk_rasterizer.h

Adds a HLE multi-layer clear mechanism, since AMD has been dragging their feet on fixing clears of multiple layers per command queue submission in their driver. This allows Xenoblade Chronicles 3 to become playable on AMD Windows again.
Fixes #9038
TODO: is the layer index not implemented for OpenGL? I couldn't see how it was used.

 maxwell3d: HLE multi-layer clear macro 

---

src/shader_recompiler/backend/spirv/spirv_emit_context.cpp

Places Scarlet in its proper setting of Paldea instead of Mexico
|Before|After|
|-|-|
|![0100a3d008c5c000_2022-11-18_22-10-08-942](https://user-images.githubusercontent.com/9658600/202831425-eaf823f8-ba69-42d3-93bf-3aa6919b7f4c.png)|![0100a3d008c5c000_2022-11-18_22-07-33-286](https://user-images.githubusercontent.com/9658600/202831347-3cd5d943-cffa-4148-a2f4-22a1760b0a02.png)|
Note: AMD users should clear their shader cache for Scarlet/Violet for this to take effect

spirv_emit_context: add missing flat decoration

---

src/core/hid/emulated_console.cpp
src/core/hid/emulated_console.h
src/core/hid/input_converter.cpp
src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h
src/input_common/helpers/touch_from_buttons.cpp
src/input_common/input_poller.cpp

Our previous touch implementation distributed 16 fingers between all touch engines.  This finally completes the implementation by allowing any number of touch inputs.
Additionally touch was running way too fast for games. This often resulted in missing inputs and other bugs. I set the correct update rate by just overclocking npad and leaving everything else at stock refresh rate.
This fixes `Mini Motorways` faulty inputs and lack of multitouch support.

core: hid: Implement true multitouch support

---

src/core/arm/dynarmic/arm_dynarmic_64.cpp

Outsourced testing has shown that disabling this option improves stability in Pokemon Scarlet. I cannot verify it myself yet, so I'll leave it as "experimental".

Dynarmic: Remove inaccurate NaN from Auto CPU settings.

---

src/video_core/buffer_cache/buffer_cache.h
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_rasterizer.h
src/video_core/renderer_vulkan/vk_rasterizer.cpp
src/video_core/renderer_vulkan/vk_rasterizer.h

The previous implementation would cause opengl to crash in non-unified_memory mode, and the generated buffer would not be recycled.
Now we have a unified implementation of vulkan and opengl.

video_core: Reimplement inline index buffer binding

---

src/core/memory/dmnt_cheat_vm.cpp

Fixes crash in speedhack cheat for Scarlet

dmnt:cht: fix copy-paste error

---

src/yuzu/applets/qt_amiibo_settings.cpp

Resolves compilation errors when ENABLE_WEB_SERVICE is disabled in CMake configuration
Fixes #9291

qt_amiibo_settings: Use WebClient only if ENABLE_WEB_SERVICE is enabled

---

src/core/hle/kernel/k_handle_table.cpp
src/core/hle/kernel/k_handle_table.h

This was used to get around the KProcess class being incomplete. We can just move this to the cpp file and eliminate the cast entirely, letting the compiler do its work and still enforce type-safety

k_handle_table: Remove cast to void* in GetObjectForIpc

---

src/video_core/buffer_cache/buffer_cache.h
src/video_core/engines/engine_upload.cpp
src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/puller.cpp

This PR attempts to fix som issues carried over from old implementations and regressions from YFC.
This fixes Pokemon Scarlet & Violet Vertex Explossions (mostly, the popping still needs fixing but  alot obetter) and Pokemon Arceus explosions on Normal Accuracy.
Special thanks to 
- bunnei for bisecting and finding the main issue.
- FengChen for finding out that the offset was wrong in BCR's InlineMemory.
- Maide for continously pointing out inconsistencies in our implementation.

GPU: Fix buffer cache issue, engine upload not inlining memory in multiple lines, etc

---

src/core/hle/kernel/hle_ipc.h
src/core/hle/service/audio/audin_u.cpp
src/core/hle/service/audio/audout_u.cpp
src/core/hle/service/audio/audren_u.cpp
src/core/hle/service/audio/hwopus.cpp
src/core/hle/service/bcat/bcat_module.cpp
src/core/hle/service/es/es.cpp
src/core/hle/service/filesystem/fsp_srv.cpp
src/core/hle/service/ldn/ldn.cpp
src/core/hle/service/nfc/nfc_user.cpp
src/core/hle/service/nfp/nfp_user.cpp
src/core/hle/service/ns/iplatform_service_manager.cpp
src/core/hle/service/set/set.cpp

Just adds a convenience function to get rid of needing to do repetitive things like:
```cpp
const auto num_some_types = GetWriteBufferSize() / sizeof(SomeType);
```
Also adds `[[nodiscard]]` to the HLERequestContext member functions where applicable, to let the compiler catch any easy bugs, given how frequently HLERequestContext is used throughout the codebase.

hle_ipc: Add helper function for determining element counts

---

src/yuzu/main.ui

> Each QAction has a menuRole property which controls the special placement of application menu items; however by default the menuRole is TextHeuristicRole which mean the menu items will be auto-detected by their text.
These items were being detected incorrectly. Used by Qt on Cocoa.

Qt: assign menuRole properties for actions

---

externals/CMakeLists.txt

externals: always use LibreSSL on Windows

---

src/audio_core/renderer/command/command_buffer.cpp

Input channels don't start at index 0. In SSHD there's 6 channels with indexes from 0x8 - 0xD, so when only allocating a 6 channel span size, the range is limited to `sample count * 6`, but when sinking it then tries to access `sample count * 8` for the first channel and beyond. So instead just check for the max input index and add 1.
No functional change here, just fixing an error when building with _FORTIFY_SOURCE since the span access was OoB.

[audio_core] Fix an OoB with sample sinking

---

src/video_core/renderer_vulkan/maxwell_to_vk.cpp

See commit descriptions. Thanks to @liamwhite for verifying these in https://vulkan.gpuinfo.org/

maxwell_to_vk: Fix format usage bits and add R16_SINT

---

src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_3d.h

The order of the drawing commands is sometimes always a surprise and a more conservative strategy is currently used to optimise.
Fix #9275

video_core: Fine tune maxwell drawing trigger mechanism

---

src/common/settings.h

GLASM is not very compatible with the latest games, and too many people have the special superpower to break their Vulkan support.

Replace GLSL as the default OpenGL shader backend

---

src/core/hid/emulated_devices.cpp
src/input_common/main.cpp
src/yuzu_cmd/emu_window/emu_window_sdl2.cpp

Yuzu wasn't releasing properly the input callbacks. This PR solves that issue.

yuzu-cmd: Fix input callback crash on close

---

src/yuzu/main.cpp

This is only used in the non-Windows path.

yuzu/main: Merge variable declaration into ifdef

---

src/common/input.h
src/core/hid/emulated_console.cpp
src/core/hid/emulated_controller.cpp
src/core/hid/emulated_devices.cpp
src/input_common/helpers/stick_from_buttons.cpp
src/input_common/helpers/touch_from_buttons.cpp
src/input_common/main.cpp

Lessens the noise of creating a new device by quite a bit, since no namespaces or types need to be respecified.
Also passes the ParamPackage instance to CreateDevice by const reference, so we're not churning allocations unnecessarily

common/input: Add helper functions for constructing input and output devices

---

src/input_common/helpers/stick_from_buttons.cpp
src/input_common/helpers/touch_from_buttons.cpp

These are const with no dependency on any other data members, so we can make these static constexpr to reduce the overall object size.

input_common/helpers: Mark analog property structs members as static constexpr

---

src/common/cache_management.cpp
src/common/cache_management.h

Narrows the include in the header to `<cstddef>`, since that's what houses size_t's definition, meanwhile the `<cstdint>` include can be moved into the cpp file.
Also nothing from our alignment header is used, so that can be removed

common/cache_management: Amend header includes

---

src/core/hle/service/nvflinger/buffer_item_consumer.cpp
src/core/hle/service/nvflinger/buffer_item_consumer.h
src/core/hle/service/nvflinger/buffer_queue_consumer.cpp
src/core/hle/service/nvflinger/consumer_base.cpp
src/core/hle/service/nvflinger/consumer_base.h
src/core/hle/service/nvflinger/nvflinger.cpp

Avoids churning atomic reference count increments and decrements. Also given they were marked const in the header means that was likely what they were supposed to be.
Also makes a few minor related changes in the surrounding area.

consumer_base: Pass std::shared_ptr by const reference

---

src/core/hle/service/nvflinger/producer_listener.h

Several member variables are shared_ptr's to this base class. Even though producer listeners are still unimplemented, this ensures we always have consistent deletion behavior once this ends up being used polymorphically.

producer_listener: Add virtual destructor to IProducerListener

---

src/video_core/surface.cpp

We can just compare directly and get rid of the verbose casting

video_core/surface: Eliminate casts in GetFormatType()

---

src/core/hle/service/nvdrv/nvdrv.cpp

We can just use auto here. If one of these ever happens to not be derived from nvdevice, then this will cause a compilation error.
We can also move the devices into the collection to get rid of an unnecessary atomic reference count increment and decrement.

nvdrv: Simplify builder declarations

---

src/video_core/host1x/syncpoint_manager.cpp
src/video_core/host1x/syncpoint_manager.h

The handle is only compared against and not modified in any way, so we can pass it by const reference.
This also allows us to mark the respective parameters for `DeregisterGuestAction()` and `DeregisterHostAction()` as const references
as well.
Makes it a little more explicit that the handle isn't intended to be modified from an self-documenting standpoint.

host1x/syncpoint_manager: Pass DeregisterAction() handle as const-ref 

---

src/video_core/engines/engine_upload.cpp
src/video_core/engines/engine_upload.h
src/video_core/engines/fermi_2d.h
src/video_core/engines/kepler_compute.cpp
src/video_core/engines/kepler_compute.h
src/video_core/engines/kepler_memory.cpp
src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_3d.h
src/video_core/engines/maxwell_dma.cpp
src/video_core/engines/puller.cpp

In a few cases we have some casts that can be trivially removed.

engines: Remove unnecessary casts

---

src/input_common/drivers/sdl_driver.cpp
src/input_common/drivers/sdl_driver.h
src/input_common/main.cpp
src/input_common/main.h
src/yuzu/main.cpp
src/yuzu/main.h

Apple doesn't allow pumping events from anything else that is not the main thread.

input_common: Pump SDL events from main thread

---

src/yuzu/startup_checks.cpp
src/yuzu/startup_checks.h

Spawns a child using fork and exec as opposed to fork alone. Workaround for the macos file manager complaining about not supporting fork without exec (iirc).
Control flow for *nix is now roughly the same as for Windows.

startup_checks: Use Windows flow for *nix

---

src/audio_core/sink/sink_stream.cpp
src/audio_core/sink/sink_stream.h
src/core/core.cpp

There is a lock returned by StallProcesses() to prevent callers to Un/StallProcesses from stomping on each other. This fixes assert spam in Pokemon Scarlet/Violet where this code path tends to kick in frequently.
Moves IsPaused() to use an atomic instead of taking the suspend lock, as AudioCore calls this when it may be holding the suspend lock already. This means IsPaused may be slightly stale, but that should be acceptable for how it is used.

AudioCore: Take suspend lock when stalling the running process.

---

src/shader_recompiler/CMakeLists.txt
src/shader_recompiler/frontend/maxwell/translate_program.cpp
src/shader_recompiler/frontend/maxwell/translate_program.h
src/shader_recompiler/host_translate_info.h
src/shader_recompiler/ir_opt/layer_pass.cpp
src/shader_recompiler/ir_opt/passes.h
src/shader_recompiler/shader_info.h
src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp

Should fix rendering of Pokemon Scarlet on Maxwell v1 and older Nvidia cards.
Also experimentally seems to fix it on RadeonSI (well, it displays _something_, whereas before it was just black), but RadeonSI reports support for GL_ARB_shader_viewport_layer_array even though it is broken, and I didn't bother to add another workaround for this particular case, since radv should be much better for this game anyway.

shader_recompiler: add gl_Layer translation GS for older hardware

---

.gitmodules
src/core/frontend/emu_window.h
src/shader_recompiler/backend/spirv/emit_spirv.cpp
src/shader_recompiler/backend/spirv/emit_spirv_control_flow.cpp
src/shader_recompiler/backend/spirv/emit_spirv_warp.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
src/video_core/vulkan_common/vulkan_device.cpp
src/video_core/vulkan_common/vulkan_device.h
src/video_core/vulkan_common/vulkan_instance.cpp
src/video_core/vulkan_common/vulkan_surface.cpp
src/yuzu/bootmanager.cpp
src/yuzu/configuration/configure_graphics.cpp
src/yuzu/startup_checks.cpp
src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp

1. Bumps minimum version of Vulkan to 1.1 (increasing shader cache version), and removes insertion of extensions that are not necessary based on the version:
- VK_EXT_shader_subgroup_ballot - superseded by GroupNonUniformBallot in Vulkan 1.1
- VK_EXT_shader_subgroup_vote - superseded by GroupNonUniformVote in Vulkan 1.1
- VK_EXT_shader_demote_to_helper_invocation - promoted to Vulkan 1.3, unsuffixed as the same operation and capability
2. Adds VK_KHR_portability_enumeration extension to Apple compile
- Needed for MVK
3. Adds support for new platform surface init in Qt and SDL2 frontends
- MVK surface creation tested in both Qt and SDL2

Vulkan: update initialization

---

src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_3d.h

Previously, we would set vertex(index)_count to 0 after each draw, because we needed to determine if it was an index draw based on the value. 
But now it turns out that macro will initiate some draw calls that rely on the previous value of vertex(index)_count, so we have modified the current logic.
Fixed particle in xc3, but some particles were still found to be faulty.

video_core: Fine tuning the index drawing judgment logic

---

CMakeLists.txt
src/CMakeLists.txt
src/audio_core/CMakeLists.txt
src/audio_core/precompiled_headers.h
src/common/CMakeLists.txt
src/common/common_precompiled_headers.h
src/common/precompiled_headers.h
src/common/string_util.cpp
src/core/CMakeLists.txt
src/core/precompiled_headers.h
src/dedicated_room/CMakeLists.txt
src/dedicated_room/precompiled_headers.h
src/input_common/CMakeLists.txt
src/input_common/precompiled_headers.h
src/network/CMakeLists.txt
src/network/precompiled_headers.h
src/shader_recompiler/CMakeLists.txt
src/shader_recompiler/frontend/ir/value.h
src/shader_recompiler/precompiled_headers.h
src/tests/CMakeLists.txt
src/tests/precompiled_headers.h
src/video_core/CMakeLists.txt
src/video_core/precompiled_headers.h
src/web_service/CMakeLists.txt
src/web_service/precompiled_headers.h
src/yuzu/CMakeLists.txt
src/yuzu/precompiled_headers.h
src/yuzu_cmd/CMakeLists.txt
src/yuzu_cmd/precompiled_headers.h

This change introduces Precompiled Headers (PCH) for some of the more commonly included headers which take the longest to compile.
Each project/CMake target defines its own PCH in its `precompiled_headers.h` file. 
This leads to repetitive includes and recompilation of the same headers in multiple projects, but this is needed since many compilers require that PCH are compiled with same compiler flags as the source files including them. 
This also adds the flexibility of adding/removing headers in the PCH as needed for each project.
On MSVC I saw a ~50% build time reduction. Other compilers may fare better or worse.
PCH is disabled on MSVC when using buildcache for now due to compilation errors.

CMake: Use precompiled headers to improve compile times

---

src/common/settings.h
src/core/telemetry_session.cpp
src/video_core/CMakeLists.txt
src/video_core/renderer_null/null_rasterizer.cpp
src/video_core/renderer_null/null_rasterizer.h
src/video_core/renderer_null/renderer_null.cpp
src/video_core/renderer_null/renderer_null.h
src/video_core/video_core.cpp
src/yuzu/bootmanager.cpp
src/yuzu/bootmanager.h
src/yuzu/configuration/configure_graphics.cpp
src/yuzu/configuration/configure_graphics.ui
src/yuzu/main.cpp
src/yuzu/main.h
src/yuzu_cmd/CMakeLists.txt
src/yuzu_cmd/emu_window/emu_window_sdl2.h
src/yuzu_cmd/emu_window/emu_window_sdl2_null.cpp
src/yuzu_cmd/emu_window/emu_window_sdl2_null.h
src/yuzu_cmd/yuzu.cpp

Mostly intended for performance testing.
Note: Qt strings in XML files do not seem to work if you set them to the string literal "Null".

video_core: add null backend

---

CMakeLists.txt
externals/CMakeLists.txt
src/core/hid/emulated_controller.cpp
src/video_core/CMakeLists.txt
src/video_core/engines/sw_blitter/converter.cpp
src/yuzu_cmd/CMakeLists.txt
src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp

Note: you must do a _clean build_ for the SDL2 update. If you have a cached CMake environment it will most likely break.
- Adds support for Dynarmic A64 backend on arm64 (merryhime/dynarmic#719)
- Updates SDL2 to latest for macOS build on Ventura
- Re-fixes macOS build

externals: update dynarmic, SDL2

---

externals/CMakeLists.txt

Regressed by #9198. From [package build log](https://github.com/yuzu-emu/yuzu/files/10147558/yuzu-s20221203.log):
```
====> Running Q/A tests (stage-qa)
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: include/xbyak/xbyak.h
Error: Orphaned: include/xbyak/xbyak_bin2hex.h
Error: Orphaned: include/xbyak/xbyak_mnemonic.h
Error: Orphaned: include/xbyak/xbyak_util.h
Error: Orphaned: lib/cmake/xbyak/xbyak-config-version.cmake
Error: Orphaned: lib/cmake/xbyak/xbyak-config.cmake
Error: Orphaned: lib/cmake/xbyak/xbyak-targets.cmake
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1
```
Obviously, installing those would conflict with [system …

externals: don't install xbyak as part of yuzu install

---

src/video_core/renderer_vulkan/maxwell_to_vk.cpp
src/video_core/renderer_vulkan/pipeline_helper.h
src/video_core/renderer_vulkan/renderer_vulkan.cpp
src/video_core/renderer_vulkan/vk_compute_pass.cpp
src/video_core/renderer_vulkan/vk_compute_pass.h
src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
src/video_core/renderer_vulkan/vk_compute_pipeline.h
src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
src/video_core/renderer_vulkan/vk_graphics_pipeline.h
src/video_core/renderer_vulkan/vk_master_semaphore.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
src/video_core/renderer_vulkan/vk_query_cache.cpp
src/video_core/renderer_vulkan/vk_scheduler.cpp
src/video_core/vulkan_common/vulkan_device.cpp
src/video_core/vulkan_common/vulkan_device.h
src/video_core/vulkan_common/vulkan_wrapper.cpp
src/video_core/vulkan_common/vulkan_wrapper.h

See individual commits for details. We take the KHR/EXT version when the core method is not available. Descriptor update templates are mandatory in 1.1 and we already have 1.1 as a minimum, so the extension method was removed entirely for this case.

vulkan_common: promote extension usages to core when possible

---

src/common/settings_input.h
src/core/hid/emulated_controller.cpp
src/yuzu/CMakeLists.txt
src/yuzu/configuration/config.cpp
src/yuzu/configuration/config.h
src/yuzu/configuration/configure_input_per_game.cpp
src/yuzu/configuration/configure_input_per_game.h
src/yuzu/configuration/configure_input_per_game.ui
src/yuzu/configuration/configure_input_player.cpp
src/yuzu/configuration/configure_input_player.h
src/yuzu/configuration/configure_per_game.cpp
src/yuzu/configuration/configure_per_game.h
src/yuzu/main.cpp

This enables setting custom input profiles per-game. 
Per-game profiles also apply the controller type (i.e. Pro Controller, Handheld, GameCube) that was selected when the profile was saved.
This acts as a temporary compromise until proper Per-Game Input configurations are implemented.

 Configuration: Add per-game input profiles 

---

src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
src/video_core/renderer_vulkan/fixed_pipeline_state.h
src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp

This adds alpha to covergae and alpha to one support to Vulkan.
Fixes trees, grass shading when closed up or far from camera on Pokemon.

Vulkan: Implement Alpha coverage

---

src/core/CMakeLists.txt
src/core/hle/service/nfc/mifare_user.cpp
src/core/hle/service/nfc/mifare_user.h
src/core/hle/service/nfc/nfc.cpp
src/core/hle/service/nfc/nfc_device.cpp
src/core/hle/service/nfc/nfc_device.h
src/core/hle/service/nfc/nfc_result.h
src/core/hle/service/nfc/nfc_user.cpp
src/core/hle/service/nfp/nfp_types.h
src/input_common/drivers/virtual_amiibo.cpp
src/input_common/drivers/virtual_amiibo.h

This PR allows to read/write plain mifare tags. Mostly used by `Skylanders Imaginators`. While encryption is not supported, plain dumps are fully functional. This completes the trilogy of NFC support. 
What's next? Besides adding encryption support I need to combine nfp and nfc as an unique file. Since both do exactly the same. For now I will keep them separated since it makes easier to identify and fix issues.

service: nfc: Implement mifare service

---

CMakeLists.txt

Uses the tagged, versioned release instead.
Followup to #6833

externals: Bump dynarmic to 6.4.0

---

src/core/hle/kernel/k_memory_block.h
src/core/hle/kernel/k_memory_block_manager.h
src/core/hle/kernel/k_shared_memory.h
src/core/hle/kernel/k_thread.h
src/core/hle/kernel/kernel.cpp
src/core/hle/kernel/physical_core.h

Reduces the likelihood of unintentional uninitialized reads occurring especially for members that rely on being set and read through a public interface

kernel: Ensure relevant class members are always initialized on construction

---

src/core/hid/emulated_console.cpp
src/core/hid/emulated_controller.cpp
src/core/hid/emulated_controller.h
src/yuzu/configuration/configure_input_player.cpp

Trivial change that just makes these functions churn a little bit less memory

emulated_console/emulated_controller: std::move ParamPackage instances where applicable

---

src/core/reporter.cpp
src/core/reporter.h

The optionals are unconditionally dereferenced when setting the custom error text, and in a few cases this function is called using the default value of the optionals, meaning dereferencing it is accessing uninitialized storage.
Since they're used unconditionally, we can use `value_or()` to set a default when storage is uninitialized.
While we're in the area, we can also tidy up all the copying going on

reporter: Eliminate undefined behavior in SaveErrorReport

---

src/video_core/vulkan_common/vulkan_debug_callback.cpp
src/video_core/vulkan_common/vulkan_device.cpp

- VUID-VkPipelineShaderStageCreateInfo-pNext-02755: subgroupSizeControl should be enabled when feature-tested
- VUID-vkCmdDraw-None-02699: it's normal for shaders to have image different bindings in different uses
- VUID-vkCmdDrawIndexed-None-06538: the image bound as storage isn't written to

vulkan_common: quiet some validation errors

---

src/video_core/CMakeLists.txt
src/video_core/buffer_cache/buffer_cache.h
src/video_core/engines/draw_manager.cpp
src/video_core/engines/draw_manager.h
src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_3d.h
src/video_core/macro/macro_hle.cpp
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
src/video_core/renderer_vulkan/vk_rasterizer.cpp

The main purpose of this PR is to remove the artificial setting of the maxwell register.
* Split maxwell's drawing logic to draw manager.
* Reorganized the drawing process to more accurately enumerate the drawing behavior.
* Macro HLE draw call makes more sense.
Fix DQB model disappearance,
Fixed dark souls,
Some other games also should be fixed. Welcome to test.

video_core: Implement maxwell3d draw manager and split draw logic

---

src/video_core/engines/draw_manager.cpp

`Maxwell3D::Regs::PrimitiveTopology` is an enum so calling functions on it fails to compile. Likely didn't get caught in CI because `LOG_TRACE` gets expanded away, it might make sense to consider this for the CI in the future.

Fix compilation error

---

src/audio_core/renderer/performance/detail_aspect.h
src/audio_core/renderer/performance/entry_aspect.h

These classes contain a `CommandGenerator&`, which can't be defaulted.

audio_core: remove explicitly defaulted and implicitly deleted constructors

---

src/core/memory.cpp

`pointer` is a structured binding in this context and isn't captured into the function test for asserts that was introduced in #8439. MSVC accepts this, but clang and gcc don't (it is forbidden by the language). Since we never hit this assert, there's not really any need to keep it around, even in debug mode.

memory: remove DEBUG_ASSERT pointer test

---

CMakeLists.txt

ld.bfd is very slow when parsing yuzu's object files. Generally this type of setup would belong in a toolchain file, but selecting one would add friction to the configuring process. A test is made for the availability of the linkers before trying to use them, and the automatic selection can also be disabled if there are issues with it.

cmake: enable faster linkers if available

---

CMakeLists.txt
src/yuzu/CMakeLists.txt

Used for Flatpak arm64, where Qt is compiled with GLES instead of desktop OpenGL.

cmake: make OpenGL loader optional

---

src/video_core/textures/texture.cpp

Fixes #8856 SMO rendering in RADV at 1x with automatic anisotropy (other scaler resolutions are still affected, this seems to be related to differing behaviors of higher anisotropy levels with sRGB textures) 
Fixes SMS water rendering in LVP at automatic anisotropy (still happens with other anisotropy values, see [here](https://wiki.dolphin-emu.org/index.php?title=Super_Mario_Sunshine#Anisotropic_Filtering))
|Before|After|
|-|-|
|![0100000000010000_2022-12-10_19-32-29-022](https://user-images.githubusercontent.com/9658600/206882881-dddb1491-9603-4bca-bd3c-670a2255e3b8.png)|![0100000000010000_2022-12-10_19-33-41-902](https://user-images.githubusercontent.com/9658600/206882882-1789b3b0-9b70-461b-b7f3-9ce4e6abb6ee.png)|
|![010049900f546002_2022-12-10_19-29-25-455](https://user-images.githubus …

video_core: fix off by one in anisotropic filtering amount

---

src/input_common/drivers/sdl_driver.cpp

This is a quick patch to fix latest SDL update with custom GUID for every controller. It shouldn't break current input profiles.
It will take me a bit to rewrite the current SDL driver. So for now this will do with the current issues.

input_common: Filter SDL GUID

---

src/yuzu/configuration/config.cpp
src/yuzu/main.cpp

Unlimited frame rate was made persistent due to user request. But this setting still causes some games to crash at boot. So it was decided to make it non persistent again to favor stability.
Potentially fixes #7356

yuzu: Make unlimited frame rate non persistent between game boots

---

src/video_core/renderer_vulkan/vk_buffer_cache.cpp
src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
src/video_core/vulkan_common/vulkan_device.cpp
src/video_core/vulkan_common/vulkan_device.h

This fixes some log spam when the Vulkan validation layers are enabled on many Intel GPUs. I haven't noticed any changes in game.
Many Intel GPU don't have enough vertex input bindings or attributes. 32 is required but I only have 28. It's a good thing that most games don't use all of them, so we can get away with having just 28 when we don't have 32. By avoiding calling Vulkan when we know it will fail, we see less error messages.

render_vulkan: Fix validation errors on less compatible Intel GPUs

---

src/shader_recompiler/backend/spirv/spirv_emit_context.cpp

Validation error. May interact with #9421

spirv_emit_context: declare GroupNonUniform capability for SubgroupLocalInvocationId

---

src/video_core/vulkan_common/vulkan_device.cpp

Validation error. `vkCreateShaderModule(): storageBuffer8BitAccess is not enabled, but shader contains an 8-bit OpVariable with StorageBuffer Storage Class.`

vulkan_common: declare storageBuffer8BitAccess

---

src/yuzu/game_list.cpp
src/yuzu/game_list.h
src/yuzu/main.cpp
src/yuzu/main.h
src/yuzu/uisettings.h

The goals here were simple: add a context menu option to the game list in yuzu that creates a shortcut, create a [Desktop Entry](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) to that game, and save a PNG icon of the game.
The first goal is just adding a menu option in yuzu's Qt frontend: the user right clicks a game in the game list and selects `Create Shortcut -> Create {Desktop,Applications Menu} Shortcut`. The second is writing a text file, making note of the nuances between different yuzu installs (it could be a Mainline AppImage on someone's desktop, there could be a space in the path to yuzu) and different distros/desktop environments (GNOME doesn't have a desktop to place files on by default).

yuzu qt, common: Add option to create game shortcuts on Linux

---

src/yuzu/bootmanager.cpp
src/yuzu/bootmanager.h
src/yuzu/main.cpp

sends exit event to game when shutdown is requested. if the game exits by itself, everything is good. if not, force terminate.

let games gracefully exit

---

src/core/hle/kernel/hle_ipc.cpp

Avoids std::vector heap memory reallocation churn

hle_ipc: Reserve vectors before populating

---

src/video_core/renderer_vulkan/vk_rasterizer.cpp

Transform feedback is implemented for geometry shaders and seems to work just fine, it's used in multiple games and the outputs are fine. This is mainly for Xenoblade Chronicles 3 though, the logs are unreadable with this message spamming.

Remove unimplemented geometry transform feedback log spam

---

src/audio_core/device/audio_buffers.h
src/audio_core/device/device_session.cpp
src/audio_core/device/device_session.h
src/audio_core/in/audio_in_system.cpp
src/audio_core/out/audio_out_system.cpp

Currently this event is only firing when the system is finalised, and not when it's stopped. When stopping, registered buffers are forcibly cleared, and the event is signalled if any existed.
This fixes a softlock at the start of Pokemon Brilliant Diamond 1.0.0 right after choosing your character.

[audio_core] Signal buffer event on audio in/out system stop

---

src/core/hle/kernel/hle_ipc.cpp

Initializing the vector size during initialization is more efficient than a later call to resize()
Performance comparison:
https://quick-bench.com/q/oVUVQBssJFkZieTrmqsKX81qpO4

hle_ipc: Refactor ReadBuffer to set buffer size upon initialization

---

src/input_common/drivers/camera.cpp
src/input_common/drivers/camera.h
src/yuzu/bootmanager.cpp
src/yuzu/bootmanager.h

Since the size of the payload is known at compile time, we can use a stack allocated array and avoid unneeded heap memory allocations.
Also avoids an unnecessary copy by using std::span when passing the data

camera: Use pre-allocated vector for camera data

---

src/yuzu/bootmanager.cpp

Should fix recording in windowed mode on Windows

qt: avoid setting WA_DontCreateNativeAncestors on all platforms

---

src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
src/shader_recompiler/backend/spirv/emit_spirv_special.cpp
src/shader_recompiler/profile.h
src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
src/video_core/vulkan_common/vulkan_device.cpp
src/video_core/vulkan_common/vulkan_device.h

Currently only NVIDIA Vulkan BETA drivers support it. It does not seem to fix anything.

Vulkan: Add support for VK_EXT_depth_clip_control.

---

src/core/hid/emulated_controller.cpp
src/core/hid/emulated_controller.h
src/input_common/CMakeLists.txt
src/input_common/drivers/virtual_gamepad.cpp
src/input_common/drivers/virtual_gamepad.h
src/input_common/main.cpp
src/input_common/main.h

This PR implements a virtual gamepad that can be accessed from the frontend that is mapped by default

input_common: Add virtual gamepad

---

src/input_common/drivers/camera.h
src/yuzu/bootmanager.cpp
src/yuzu/bootmanager.h
src/yuzu/configuration/config.cpp

Avoids resetting device name with per game config and solves the build error on Qt6. Uses the correct resolution for camera captures to avoid coping more data than necessary.
Fixes #9465
Fixes #9464

yuzu: Fix compile and setting errors

---

src/yuzu/main.cpp

Yuzu will now remember the last install to nand directory that was opened.
Fixes: #9376

yuzu: Remember last selected directory

---

src/yuzu/startup_checks.cpp

When Yuzu is invoked through command line, its `argv[0]` is `yuzu`, not the full path of its executable, so `execl` fails because it's unable to find a file named `yuzu`. `execlp` solve this problem, looking for the executable in `$PATH` if the name is specified instead of its full path.

Use execlp instead of execl to avoid failure

---

src/core/hle/service/nfc/nfc_user.cpp
src/core/hle/service/nfp/nfp_user.cpp

Some games like BoTW have top quality coding and keep spamming this function.

service: nfc: Silence ListDevices

---

src/yuzu/util/overlay_dialog.cpp

This allows for the creation of a non-interactive dialog overlay to display system messages.

overlay_dialog: Hide button dialog box when both buttons are hidden

---

CMakeLists.txt

Fixes compile with older local version of headers after #9480

CMakeLists: bump required Vulkan package version to 1.3.238

---

src/yuzu/bootmanager.cpp
src/yuzu/main.cpp

Allows homebrew demos and such to avoid crashing on exit.

qt: exit properly on guest-initiated close

---

src/yuzu/main.cpp
src/yuzu/main.h
src/yuzu/util/overlay_dialog.cpp
src/yuzu/util/overlay_dialog.h

Fixes #9472 (UI jank from not pumping event loop while waiting for close)
Also puts up an informative overlay while waiting begins

qt: continue event loop during game close

---

src/yuzu/bootmanager.h

GMainWindow checks for EmuThread::IsRunning() immediately after resuming the game when updating the menu. The thread is not likely to have woken up before this happens. IsRunning therefore should return true if the game is intended to resume as well.

qt: fix 'Pause' menu item

---

src/common/CMakeLists.txt
src/common/make_unique_for_overwrite.h
src/common/scratch_buffer.h
src/tests/CMakeLists.txt
src/tests/common/scratch_buffer.cpp
src/video_core/buffer_cache/buffer_cache.h
src/video_core/dma_pusher.cpp
src/video_core/dma_pusher.h
src/video_core/engines/engine_upload.cpp
src/video_core/engines/engine_upload.h
src/video_core/engines/maxwell_dma.cpp
src/video_core/engines/maxwell_dma.h
src/video_core/host1x/vic.cpp
src/video_core/host1x/vic.h

This class acts as a wrapper around a heap allocated buffer using `make_unique_for_overwrite` for cases where value initialization is not needed.
The common use case for this would be in hot code where the buffer is passed into a memcpy, especially when the buffer is reused and will potentially grow during the lifetime of the owning object.
Some benchmarking data:
https://quick-bench.com/q/ZZgvNA7kjr0DYYSduqQ_8bxfUxs

common: Add ScratchBuffer Class

---

src/core/hle/service/time/clock_types.h
src/core/hle/service/time/time_sharedmemory.cpp
src/core/hle/service/time/time_sharedmemory.h

From ams. This cleans up the TODOs in this file. Found while removing special purpose shared memory from the kernel.

time: add LockFreeAtomicType

---

src/core/hle/kernel/k_shared_memory.cpp
src/core/hle/kernel/k_shared_memory.h
src/core/hle/kernel/kernel.cpp

I observed that when looping hbmenu on a 5 second timer, memory blocks used for shared memory regions would sometimes collide with TLS pages, get overwritten with random data, and cause libnx to abort. After tracking down the location of the writes, I found that yuzu wasn't actually allocating those regions, just using them without allocating first.
This is a hack until we get rid of the horrid kernel-managed shared memory objects, but it will probably fix a bunch of randomly-occurring startup crashes in games.

kernel: workaround static shared memory initialization

---

src/yuzu/main.cpp
src/yuzu/main.h

Caused by the perils of programming in event loops.

qt: prevent reentrant shutdown

---

src/core/hid/emulated_controller.cpp

As TAS-scripts provide raw inputs for the system, they should not be sanitized by Yuzu. As the function responsible for doing that (https://github.com/yuzu-emu/yuzu/blob/bbb963a31a141979b27615b9c28bcc72be50468e/src/core/hid/input_converter.cpp#L347) cannot be worked around, the simplest way to fix the current inaccuracies is by just hardcoding the range and deadzone to full and none, meaning the sanitization will not actually perform any changes on the data.

TAS: Increase accuracy of Stick inputs

---

src/tests/common/scratch_buffer.cpp

The header `<cstring>` is needed for `std::memcpy`.

tests: add missing header

---

src/video_core/texture_cache/texture_cache.h
src/video_core/texture_cache/texture_cache_base.h
src/video_core/texture_cache/util.cpp
src/video_core/texture_cache/util.h

Currently, heap memory is allocated and deallocated whenever a texture upload/download occurs. This can have significant overhead that is noticeable as stutters, especially since the texture data can be in the order of a few megabytes.
To alleviate this, a pre-allocated buffer is used to hold the swizzle data. This will reduce dynamic memory allocations, and should lead to less stutter as new textures are loaded, or when the GPU Garbage Collector is evicting images.
This can be further improved by using the ScratchBuffer from #9453

texture_cache: Use pre-allocated heap buffer for texture swizzles

---

src/core/CMakeLists.txt
src/core/hle/kernel/k_code_memory.cpp
src/core/hle/kernel/k_code_memory.h
src/core/hle/kernel/k_memory_manager.cpp
src/core/hle/kernel/k_page_group.cpp
src/core/hle/kernel/k_page_group.h
src/core/hle/kernel/k_page_table.cpp
src/core/hle/kernel/k_page_table.h
src/core/hle/kernel/k_shared_memory.cpp
src/core/hle/kernel/memory_types.h
src/core/hle/kernel/svc.cpp

Sync with ams. We now track page group reference counts and no longer need to use HACK_OpenPages / HACK_ClosePages in KPageTable.

k_page_group: synchronize

---

src/video_core/buffer_cache/buffer_cache.h
src/video_core/host_shaders/vulkan_quad_indexed.comp
src/video_core/renderer_vulkan/maxwell_to_vk.cpp
src/video_core/renderer_vulkan/vk_buffer_cache.cpp
src/video_core/renderer_vulkan/vk_buffer_cache.h
src/video_core/renderer_vulkan/vk_compute_pass.cpp
src/video_core/renderer_vulkan/vk_compute_pass.h
src/video_core/renderer_vulkan/vk_rasterizer.cpp

QuadStrip need to use triangles to simulator it, and also need to simulator indexed and non-indexed modes. 
In non-indexed mode  just create a fixed mapping table (because can reuse it).
In indexed mode need to do a dynamic mapping of the original drawing index, and here use a compute shader to implement it.
LineLoop need to use triangle list to simulator it.
Polygon need to use triangle fan to simulator it.
Fix BOTW Hero's Path.
Fix Pokemon Scarlet Status summary graphic.
Close #9491

video_core: Implement all vulkan topology

---

src/yuzu/configuration/config.cpp

Yuzu saves the remote ip and nickname in the "Direct Connect" dialog by default, which makes it way more convenient to connect to the same host.
But there is an annoying bug, that these saved settings get lost everytime you boot up a game. I don't think that this should be desirable behaviour.
The reason is that the ui settings `multiplayer_nickname`, `multiplayer_ip`, etc. were replaced by the values stored in the per-game config files, whenever a game was loaded and these settings are always default values.
It can simply be fixed by only loading and storing multiplayer settings globally. I might be wrong, but I don't see a reason multiplayer settings should be read from the game specific configs at this point.
`ReadMultiplayerValues` and `SaveMultiplayerValues` were called actually …

config: Save multiplayer settings only globally

---

CMakeLists.txt
externals/CMakeLists.txt
src/CMakeLists.txt
src/audio_core/CMakeLists.txt
src/input_common/CMakeLists.txt
src/input_common/main.cpp

With this, yuzu-room, libusb, sdl2, and cubeb are independently made optional.

CMake: make more features optional

---

src/core/hid/emulated_console.cpp

Avoids a crash if frontend does not configure touch_from_button_maps. Core should gracefully handle this with logging rather than hard crash the emulator.

core: hid: emulated_console: Avoid a crash if frontend does not configure touch_from_button_maps.

---

.ci/scripts/format/script.sh

This branch changes the permissions on the ci clang-format script to be executable and allows the clang-format binary to be set.
This allows me to lint my changes with:
```sh
TRAVIS_EVENT_TYPE=pull_request CLANG_FORMAT=clang-format ./.ci/scripts/format/script.sh
```

ci: Allow setting clang-format binary

---

src/yuzu/configuration/configure_system.cpp
src/yuzu/configuration/configure_system.ui

I was trying to figure out why the temperature indicator in BotW was in Fahrenheit.
Since British English is at index 13 it's easy to overlook.
This branch changes the "English" language option to "American English".
It also adds a warning to the settings window when the selected language isn't valid for the selected region.
This warning doesn't appear when the region is set to China, as that isn't an option on my switch.

settings: warn on invalid regon/language combinations

---

src/common/host_memory.cpp

* `NORESERVE`: Specify that we do not require swap to be reserved for this address range; allow overcommitting (if it's disabled for whatever reason).
* Transparent huge pages (THP): Ensure THP is enabled for the requested region.

host_memory: mmap changes for virtual_base

---

src/core/file_sys/vfs.cpp

Also helpfully side-steps a weird gcc 12.1.0 warning.

vfs: Replace cstr concat with char concat

---

src/core/hle/service/nifm/nifm.cpp

Updates structs and enums to match documentation and more importantly initializes the state of the IRequest.
Fixes #9458

service: nifm: Initialize request state

---

CMakeLists.txt
externals/find-modules/Findhttplib.cmake
externals/find-modules/Findlz4.cmake
externals/find-modules/Findzstd.cmake

Make failure messages less scary as discussed in https://github.com/yuzu-emu/yuzu/pull/9515.
Also don't try to find a library via `pkg-config` when a CMake config file with unsuitable version has already been found. The `pkg-config` will fail too and it makes the message better.

cmake: improve find_package failure messages

---

src/yuzu/debugger/controller.cpp

Co-Authored-By: Narr the Reg <5944268+german77@users.noreply.github.com>
This will make sure that the sanitized (deadzone/range-adjusted) stick input will be written to the file instead of the raw inputs, as the playback will not run the sanitization again. This means that the file will contain all the stick values that are actually received by the game instead of the ones issued by the user, making sure that playback also syncs with different playback methods.

TAS: Record sanitized instead of raw stick inputs

---

CMakeLists.txt
externals/CMakeLists.txt

This policy is only useful for external subprojects and thus belongs to `externals/CMakeLists.txt`.
Also remove the now inexistent `DYNARMIC_NO_BUNDLED_FMT` option.

cmake: allow options shadowing with normal variables

---

src/video_core/renderer_vulkan/vk_buffer_cache.cpp
src/video_core/vulkan_common/vulkan_device.cpp
src/video_core/vulkan_common/vulkan_device.h

This is needed by MVK, which does not support nullDescriptor or robustBufferAccess2. (robustImageAccess2 is supported.)

renderer_vulkan: implement fallback path for null buffer descriptors

---

src/core/memory.cpp
src/tests/video_core/buffer_base.cpp
src/video_core/CMakeLists.txt
src/video_core/buffer_cache/buffer_base.h
src/video_core/engines/engine_upload.cpp
src/video_core/engines/fermi_2d.cpp
src/video_core/engines/fermi_2d.h
src/video_core/engines/maxwell_3d.cpp
src/video_core/engines/maxwell_dma.cpp
src/video_core/invalidation_accumulator.h
src/video_core/memory_manager.cpp
src/video_core/memory_manager.h
src/video_core/rasterizer_interface.h
src/video_core/renderer_vulkan/vk_rasterizer.cpp
src/video_core/renderer_vulkan/vk_rasterizer.h

This PR reduces time spent reading data from CPU to GPU, reduces invalidation overhead, improves performance overall and fixes Pokemon Scarlet / Violet on Normal.

VideoCore: Implement Cached Writes, use fastmem for reading GPU memory and eliminate old stuffs

---

src/common/settings.cpp
src/common/settings.h
src/video_core/CMakeLists.txt
src/video_core/host_shaders/CMakeLists.txt
src/video_core/host_shaders/vulkan_turbo_mode.comp
src/video_core/renderer_vulkan/renderer_vulkan.cpp
src/video_core/renderer_vulkan/renderer_vulkan.h
src/video_core/renderer_vulkan/vk_turbo_mode.cpp
src/video_core/renderer_vulkan/vk_turbo_mode.h
src/video_core/vulkan_common/vulkan_device.cpp
src/yuzu/configuration/config.cpp
src/yuzu/configuration/configure_graphics_advanced.cpp
src/yuzu/configuration/configure_graphics_advanced.h
src/yuzu/configuration/configure_graphics_advanced.ui
src/yuzu_cmd/config.cpp

Dumb workaround for dumb driver issue. Downclocking is bad, and we hit it a lot, especially on AMD, so make a background thread that is always submitting pointless work to prevent the GPU from downclocking.
This provides a significant boost in Scarlet, jumping from roughly 22fps to 35fps on my 6700XT (RADV). Nvidia cards are unlikely to see any significant boost.

vulkan: implement 'turbo mode' clock booster 

---

src/core/internal_network/network.cpp

Some mods adding network connectivity use sockets with a timeout to let the games stay responsive while waiting for a packet to be received (`smo-practice`). Yuzu should just silently deal with that and properly translate the OS timeout errors to error codes for the game instead of spewing out 3 `CRITICAL` and `ERROR` logs.

net: Silently translate ETIMEDOUT network error

---

src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
src/shader_recompiler/backend/spirv/emit_spirv_warp.cpp
src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
src/shader_recompiler/backend/spirv/spirv_emit_context.h
src/shader_recompiler/frontend/maxwell/translate_program.cpp
src/shader_recompiler/host_translate_info.h
src/shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp
src/shader_recompiler/ir_opt/passes.h
src/shader_recompiler/profile.h
src/shader_recompiler/shader_info.h
src/video_core/buffer_cache/buffer_cache.h
src/video_core/renderer_opengl/gl_buffer_cache.h
src/video_core/renderer_opengl/gl_shader_cache.cpp
src/video_core/renderer_vulkan/vk_buffer_cache.cpp
src/video_core/renderer_vulkan/vk_buffer_cache.h
src/video_core/renderer_vulkan/vk_pipeline_cache.cpp

PRing this mainly for geometry passthrough emulation, which should fix nier, MUA3 and #9351 on AMD/Intel GPUs. I've also included an SSBO alignment change which might fix some games using on intel iGPUs and a change that alters the behaviour of `ShuffleUp`  but that needs further HW testing. (NV docs are contradictory)

Port over several shader-compiler fixes from skyline

---

src/video_core/renderer_vulkan/vk_pipeline_cache.cpp

The header size of the Vulkan driver pipeline cache files was incorrect in `PipelineCache::LoadVulkanPipelineCache`, for which reason the pipeline cache wasn't read correctly and got invalidated on each load. I forgot to adjust it when adding the cache version to the file header. Sorry for that guys!

video_core/vulkan: Fixed loading of Vulkan driver pipeline cache

---

src/video_core/renderer_opengl/renderer_opengl.cpp

Yuzu was crashing on opengl due to having a bad config file. Instead of crashing the full emulator for something so trivial just default to no antialiasing.

opengl: Sanitize antialiasing config

---

src/video_core/vulkan_common/vulkan_device.cpp

Fixes the second issue described in #9560

vulkan_device: avoid attempt to access empty optional

---

src/video_core/renderer_vulkan/renderer_vulkan.cpp
src/video_core/vulkan_common/vulkan_device.cpp
src/video_core/vulkan_common/vulkan_device.h

Steam Deck is reported to be broken with this setting, so prevent it from taking effect there.

renderer_vulkan: disable clock boost on unvalidated devices

---

src/shader_recompiler/frontend/maxwell/translate_program.cpp

YFC 1.5 extended the size of the varying mask used to hold passthrough attrs without considering this

Avoid OOB array access reading passthrough attr mask

---

src/common/input.h
src/core/hid/emulated_controller.cpp
src/input_common/helpers/stick_from_buttons.cpp
src/input_common/main.cpp

Initially I decided to use the emulated controller to update the analog from keyboard input regularly. This is now kicking me back.
A much better solution is to create a dummy engine that simply triggers the callback each time. Since we now have a `PumpEvents` function we can simply hook this to the dummy engine and have reliable updates.
Fixes #9562

input_common: Create an update engine

---

src/yuzu/main.cpp

Fixes more crashes in games that are able to close themselves in response to a request for shutdown.

qt: additional fixes for reentrant shutdown

---

src/yuzu/Info.plist

https://developer.apple.com/documentation/bundleresources/information_property_list/lsapplicationcategorytype This makes it show up in the Launchpad Games folder

macOS: Make Yuzu show up in the Launchpad Games folder

---

src/input_common/drivers/tas_input.cpp
src/input_common/drivers/tas_input.h
src/yuzu/main.cpp
src/yuzu/main.h

When multiple scripts are loaded for multiple controllers at the same time, the progress display in the toolbar of Yuzu should reflect the length of all files, if they have individually different lengths. Example: `TAS state: Running 35/100, 20, 0, 40`.
Non-existant files are assumed to be 0 frames long, if none of the following files contain any data, it won't display them. Example: `TAS state: Idle 0/30`, if only the first file contains a script for 30 frames.

TAS: Show all script lengths for multiplayer

---

src/input_common/input_mapping.cpp
src/yuzu/configuration/configure_input_player.cpp
src/yuzu/configuration/configure_input_player.h

Enable listening to the mouse scroll input while we are on the controller configuration. This allows the mouse scroll to be mapped to any button.
Closes: #9603

yuzu: Read mouse scroll

---

src/common/settings.cpp
src/common/settings.h
src/yuzu/configuration/configure_graphics.ui

Seems to hit the sweetspot for current most common GPUS. Also looks great on 1440p displays.
Slapping an [EXPERIMENTAL] warning because Scarlet/Violet doesn't like it too much.

1.5X, 7X, 8X resolution scaler options

---

src/core/hle/service/nvflinger/nvflinger.cpp
src/core/hle/service/nvflinger/nvflinger.h

Swap interval refers to how many vsync events to wait after presenting the queued item, so a value of 3 should wait for 3\*16.67ms (20 fps), but we were waiting for 4\*16.67ms (15 fps) instead, and so forth. Values normally used by games are 1 and 2, which correspond to 60 and 30 fps respectively, so it never broke in that case.
This also adds the ability to use non-positive values as an extension, which are implemented as multiples of 120 fps. This behavior doesn't exist on console, but is useful for framerate mods.

nvnflinger: correct swap interval handling

---

src/audio_core/renderer/command/resample/upsample.cpp

* There was an off-by-one error in convolution operation, where the convolution would only summate 19 values in total instead of the expected 20.
* Make the coefficient arrays a sensible format, they're halves of offsets of a windowed sinc function divvied up as expected for the polyphase interpolator.

audio_core: Corrective fixes to upsampler

---

src/core/core_timing.cpp
src/core/core_timing.h
src/core/hle/kernel/k_hardware_timer.cpp

Removes the duplicated (unused) function RemoveEvent and requires UnregisterEvent to wait for any in-progress callback to complete before returning.
This disallows a dispatched timing callback from executing after UnregisterEvent has returned, which is enough to make unregistration work as expected, and satisfies principle of least surprise. It should fix some semi-rare shutdown crashes.
<details>
<summary>KHardwareTimer info</summary>
KHardwareTimer needs to avoid waiting for the event to complete until it is shut down. It will hold the scheduler lock, and then try to take the advance lock. However, timing callbacks will hold the advance lock, and then try to take the scheduler lock. This will deadlock, given the right timing.
KHardwareTimer callbacks are the only scenario where avoiding …

timing: wait for completion on unregister

---

src/video_core/engines/maxwell_3d.cpp

DeviusDraem doesn't like it, plus we don't really need this logged anyway. Apparently some games spam this excessively.

Demote maxwell3d Firmware4 call log to debug

---

dist/org.yuzu_emu.yuzu.metainfo.xml

The [appstream] spec says that `<screenshot/>` tags must be wrapped in either `<image/>` or `<video/>` tags, so this patch does just that.
[appstream]: https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots
Cc: @liushuyu

fix(dist): wrap screenshots in <image> tags

---

src/core/hid/emulated_controller.cpp

Stick minimum range is -32,766 verified with HW.  As for why it isn't -32768 is unclear to me but there is a particular game where this matters, `EARTH DEFENSE FORCE: WORLD BROTHERS` is unable to read negative values.

core: hid: Fix stick minimum range

---

src/video_core/vulkan_common/nsight_aftermath_tracker.cpp

- GFSDK_Aftermath_EnableGpuCrashDumps was given an extra parameter of type PFN_GFSDK_Aftermath_ResolveMarkerCb which we don't use
- GFSDK_Aftermath_ShaderHash was renamed to GFSDK_Aftermath_ShaderBinaryHash
- A parameter was removed from GFSDK_Aftermath_GpuCrashDump_GenerateJSON

nsight_aftermath_tracker: update for latest Aftermath SDK

---

src/yuzu/configuration/configuration_shared.cpp
src/yuzu/configuration/configuration_shared.h
src/yuzu/configuration/configure_system.cpp
src/yuzu/configuration/configure_system.h

Per game config alters the combobox index. You can't use it directly. This PR fixes that issue and ensures the lookup table is always in bounds to avoid future crashes.
Fixes #9655

yuzu: Fix language comobox crash

---

CMakeLists.txt
externals/CMakeLists.txt
src/tests/CMakeLists.txt
src/tests/common/bit_field.cpp
src/tests/common/cityhash.cpp
src/tests/common/fibers.cpp
src/tests/common/host_memory.cpp
src/tests/common/param_package.cpp
src/tests/common/range_map.cpp
src/tests/common/ring_buffer.cpp
src/tests/common/scratch_buffer.cpp
src/tests/common/unique_function.cpp
src/tests/core/core_timing.cpp
src/tests/core/internal_network/network.cpp
src/tests/input_common/calibration_configuration_job.cpp
src/tests/tests.cpp
src/tests/video_core/buffer_base.cpp
vcpkg.json

Also support the standard `BUILD_TESTING` option (created by the `CTest` module) and force disable tests in externals supporting the same option.

tests: update catch2 to 3.0.1

---

src/input_common/drivers/joycon.cpp

Regressed by #9492. See [error log](https://github.com/yuzu-emu/yuzu/files/10503123/yuzu-s20230124.log).

input_common: unbreak build with libc++ (missing std::ranges::find_if)

---

src/core/hid/emulated_controller.cpp
src/input_common/helpers/stick_from_buttons.cpp

Reverts all the changes from #9617. I made another homebrew to specifically check the weird value. Turns out -32767 is totally possible just unlikely. I confirmed as well by playing the game on the switch. If you put the stick just right you have the same issue as yuzu. So this is a game bug. Not a yuzu one.
Instead I modified the digital stick output to have a maximum range of 99.996% to allow for this game to work properly with keyboard and similar.

Revert #9617 and fix it on input_common

---

src/yuzu_cmd/default_ini.h

We are dangerously close to MSVC's 16384 character limit for string literals. Breaking this string up and concatenating will allow for more settings to be added in the future.

default_ini: Split and concatenate the config string literal

---

src/yuzu/main.cpp

This is fortunately disabled by default on Qt6, so we just have to check whether we are compiling with Qt6 or not.
Fixes #9680

main: Only set AA_DisableWindowContextHelpButton below Qt6

---

src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
src/shader_recompiler/ir_opt/texture_pass.cpp
src/shader_recompiler/shader_info.h

Fixes Vulkan shader compiler crash in Fire Emblem Engage

spirv: fix multisampled image fetch

---

src/core/memory.cpp
src/video_core/memory_manager.cpp
src/video_core/memory_manager.h

This reverts commit af5ecb0b15d4449f58434e70eed835cf71fc5527.
Fixes https://github.com/yuzu-emu/yuzu/issues/9669 as per @piplup55.
Without testing I would assume this would be because of a race between protect and read/write.

Revert "MemoryManager: use fastmem directly."

---

src/input_common/helpers/joycon_driver.cpp
src/input_common/helpers/joycon_protocol/generic_functions.cpp
src/input_common/helpers/joycon_protocol/generic_functions.h
src/input_common/helpers/joycon_protocol/joycon_types.h

Disables low power mode when a joycon is connected and calls TriggersElapsed after the report mode is set. I didn't notice any difference but it might increase the signal strength of the joycons. It also mimics a bit closer to what the switch does.
```
Left Joycon
[ts:  35065ms t: mc::BtdrvMitmThread    p: 17/17] Get Device Info
[ts:  35129ms t: mc::BtdrvMitmThread    p: 17/17] Low Power Mode  [0x00]
[ts:  35193ms t: mc::BtdrvMitmThread    p: 17/17] SPI Read address [0x6000], size [0x10]
[ts:  35246ms t: mc::BtdrvMitmThread    p: 17/17] SPI Read address [0x6050], size [0x0d]
[ts:  35298ms t: mc::BtdrvMitmThread    p: 17/17] Report Mode STANDARD_FULL_60HZ
[ts:  35358ms t: mc::BtdrvMitmThread    p: 17/17] Triggers Elapsed????
[ts:  35429ms t: mc::BtdrvMitmThread    p: 17/17] SPI Read …
```

input_common: Implement SetLowPowerMode and TriggersElapsed

---

src/core/hle/kernel/k_page_table.cpp

Why can't they just make this work correctly

kernel: unbreak min/max template deduction on Apple Clang

---

src/core/hle/kernel/k_condition_variable.cpp
src/core/hle/kernel/k_light_lock.cpp
src/core/hle/kernel/k_memory_layout.h
src/core/hle/kernel/k_thread.cpp
src/core/hle/kernel/k_thread.h
src/core/hle/kernel/kernel.cpp

Calling SetActivity with the scheduler lock held is an error and it isn't needed here anyway
Fixes #9664

kernel: fix incorrect locking order in suspension 

---

src/common/polyfill_thread.h
src/input_common/drivers/gc_adapter.cpp
src/input_common/drivers/joycon.cpp

StoppableTimedWait allows for a timed wait to be stopped immediately after a stop is requested.
This is useful in cases where long duration thread sleeps are needed and allows for immediate joining of waiting threads after a stop is requested.
This allows yuzu to close immediately instead of waiting for the thread sleep to complete to recheck the stop condition.

polyfill_thread: Implement StoppableTimedWait
