yuzu-emu/yuzu

- src/yuzu/configuration/input_profiles.cpp
Found this one while debugging. You can't do a for loop and delete entries of the object at the same time otherwise the index might go out of bounds.
> yuzu: config: Avoid reading deleted object

- src/video_core/texture_cache/image_info.cpp
- src/video_core/texture_cache/samples_helper.h
The texture cache was failing to track image views of MSAA render targets. 
It seems that when an MSAA render target is bound, its dimensions are already scaled by the number of MSAA samples. This was not the case for image views of render targets, which retained the original image dimensions. 
This caused the texture cache to improperly bind the image view as it would not satisfy the subresource check since it had differing dimensions. This was confirmed on a small homebrew test I made. 
Further testing in games with missing/corrupted graphics would be appreciated
Fixes FE: Engage character portraits
|      Before | After        |
|---------|----------|
|  ![before](https://user-images.githubusercontent.com/52414509/215244011-e0645d5d-1c7a-4414-84f9-14f72516d451.png)  | …
> texture_cache: Fix tracking of MSAA image views

- src/input_common/helpers/joycon_protocol/calibration.cpp
- src/input_common/helpers/joycon_protocol/calibration.h
- src/input_common/helpers/joycon_protocol/common_protocol.cpp
- src/input_common/helpers/joycon_protocol/common_protocol.h
- src/input_common/helpers/joycon_protocol/generic_functions.cpp
- src/input_common/helpers/joycon_protocol/joycon_types.h
This PR doesn't introduce anything new. It's just a cleanup of the calibration protocol, it removes magic values and simplifies overall logic making it easier to read.
> input_common: joycon: Remove magic numbers from calibration protocol

- src/shader_recompiler/ir_opt/texture_pass.cpp
ba34cf0a691bc73ae6b2d8db6019b1f10d22dde5 added the `shift_left` and `secondary_shift_left` members to the texture descriptors, but they are not accounted for in the comparison when adding new descriptors. 
I don't think that was intentional, since this could lead to two descriptors that are the same but with different values for the `shift_left` elements to not get correctly tracked.
This also fixes tracking of MSAA texture descriptors.
> texture_pass: Fix texture descriptors comparisons

- .ci/scripts/merge/apply-patches-by-label.py
This raises an exception if the GET request to Github's API returns anything other than 200 OK, ensuring we always have successful merges of tagged PRs. Also, reduces the number of queried pages from 29 to 9 to reduce the number of requests.
> ci: Abort on failure to query Github's API

- src/video_core/host_shaders/CMakeLists.txt
- src/video_core/host_shaders/vulkan_color_clear.frag
- src/video_core/host_shaders/vulkan_color_clear.vert
- src/video_core/renderer_vulkan/blit_image.cpp
- src/video_core/renderer_vulkan/blit_image.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
Vulkan cleaning does not support the mask parameter, so we need to enumerate it by draw. The current solution is to use the blend state to mask specific channels to solve the problem.
For example, clear BGA not R channel.
Before:
After:
This should fix some other games, feel free to test it.
> video_core: Implement vulkan clear specified channel

- src/input_common/drivers/joycon.cpp
- src/input_common/drivers/joycon.h
- src/input_common/helpers/joycon_driver.cpp
- src/input_common/helpers/joycon_protocol/common_protocol.cpp
- src/input_common/helpers/joycon_protocol/common_protocol.h
- src/input_common/helpers/joycon_protocol/generic_functions.cpp
- src/input_common/helpers/joycon_protocol/irs.cpp
- src/input_common/helpers/joycon_protocol/joycon_types.h
- src/input_common/helpers/joycon_protocol/nfc.cpp
- src/input_common/helpers/joycon_protocol/nfc.h
- src/input_common/helpers/joycon_protocol/poller.cpp
- src/input_common/helpers/joycon_protocol/ringcon.cpp
Same deal as previous PR. Removes the usage of vectors and return proper structs. Eliminating all magic numbers in the process.
> input_common: joycon: Remove Magic numbers from common protocol

- src/shader_recompiler/backend/glasm/emit_glasm_image.cpp
- src/shader_recompiler/backend/glsl/emit_glsl_image.cpp
- src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
- src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
- src/shader_recompiler/backend/spirv/spirv_emit_context.h
TXQ can operate on MSAA textures, but has no flag within the instruction indicating if that is the case. The shader backends require knowing if the texture is MSAA as they cannot query LOD related information for MSAA textures.
This implementation relies on an assumption that TLD/`texelFetch` is called on the MSAA texture elsewhere in the shader, which can track if the texture binding is MSAA. 
This assumption will fall apart if there are shaders which query the size of the MSAA texture, but never sample from it. 
Ideally the MSAA mode for the texture is tracked based on its `TICEntry` from the engine environment, as is done here: https://github.com/yuzu-emu/yuzu/blob/3aab57452153c3dfa8591809bc09797da03b44dc/src/shader_recompiler/ir_opt/texture_pass.cpp#L367-L373 
But doing so will …
> shaders: Fix TXQ with MSAA textures

- src/video_core/renderer_opengl/gl_compute_pipeline.cpp
- src/video_core/renderer_opengl/gl_compute_pipeline.h
- src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
- src/video_core/renderer_opengl/gl_graphics_pipeline.h
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_opengl/gl_shader_cache.h
The disk shader cache was building pipelines on async worker threads using a shared GL context, but these built pipelines wouldn't always necessarily be available to the main context.
This was especially an issue for async shader compilation, where there was roundabout logic that made the async worker threads indicate that the pipelines were built despite not calling `glFlush`.
this change forces a context flush when loading disk shader cache, and ensures that the async thread's work is complete before attempting to use the pipeline. This will fix persistent graphical issues especially with async shaders enabled.
The easiest repro I had to test this was DKC:TF title screen, where it was previously graphically messed up/missing elements with async shaders + disk pipeline cache enabled: …
> gl_shader_cache: Force context flush when loading disk shader cache

- src/yuzu/multiplayer/lobby.cpp
- src/yuzu/multiplayer/lobby.h
- src/yuzu/multiplayer/lobby.ui
Same as the full rooms toggle, but hides rooms with no other players, in case you want to jump in where people already are. There are a lot of 0/ rooms at some times of day.
> Added 'Hide empty rooms' toggle to lobby

- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.h
Fixes two issues. First of all implements touch from mouse and secondly SDL controllers where ignoring all config and using default due being already initialized on the yuzu_cmd. Lastly it adds some config params that weren't included.
This allows for yuzu_cmd and yuzu to have the same behavior and config. 
closes: #8852, #9142, #8780, #6954
> yuzu_cmd: Fix touch and controller input

- src/yuzu/applets/qt_software_keyboard.cpp
- src/yuzu/main.cpp
- src/yuzu/util/overlay_dialog.cpp
This uses Qt's new high DPI application attributes for scaling the current window.
However, these aren't perfect as scaling with non integer scales will cause artifacts in UI, icons and other elements.
Therefore, we use a heuristic to select an appropriate integer scale value depending on the current screen resolution and applies this to the application.
Fixes #4904
Fixes #7383
Fixes #8051
> main: Enable High DPI fixes for Qt >= 5.14

- src/tests/video_core/buffer_base.cpp
- src/video_core/buffer_cache/buffer_base.h
This fixes a regression where Yoshi's Crafted World (and potentially other titles) would crash/enter an infinite loop when GPU Accuracy was set to "Normal"
> buffer_base: Partially revert changes from #9559

- src/shader_recompiler/backend/glsl/glsl_emit_context.cpp
These built-ins seem to be available without needing to be declared for fragment shaders, similar i.e. to gl_FragDepth.
> glsl_emit_context: Remove redeclarations of gl_SampleID and gl_SampleMask

- src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
When dynamic state is enabled, the pipeline vertex input state is ignored, and they're set up dynamically on the command buffer instead. For some reason we set "fake" vertex bindings with fixed/incomplete values, which causes Vulkan's validation layers to go crazy spamming unaligned vertex buffer attribute errors, even when these bindings are not used. Seems like a bug with Vulkan validation layers. 
Removing these fake vertex bindings gets rid of the validation console spam with dynamic input.
> Remove fake vertex bindings when dynamic state is enabled

- src/yuzu/main.cpp
For some reason, I had removed this in https://github.com/yuzu-emu/yuzu/pull/4949/commits/ad6cec71ecd61aa2533d9efa89b68837516f8464
This should fix any improperly scaled web applets.
Should fix #9756
> main: Re-add QtWebEngine zoom factor

- src/common/settings.h
- src/input_common/drivers/joycon.cpp
- src/input_common/drivers/joycon.h
- src/input_common/drivers/sdl_driver.cpp
- src/input_common/helpers/joycon_driver.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_input_advanced.cpp
- src/yuzu/configuration/configure_input_advanced.ui
- src/yuzu_cmd/config.cpp
This PR brings back the support for pro controllers on the custom joycon driver. It's disabled by default since it still has issues with 3rd party variants. But users who own an original controller can enable this option.
> input_common: Reintroduce custom pro controller support

- src/video_core/gpu.cpp
- src/video_core/gpu_thread.cpp
- src/video_core/gpu_thread.h
Call rasterizer->ReleaseFences() directly
Tegra::Control::Scheduler::Push calls Tegra::DmaPusher::DispatchCalls which calls Tegra::GPU::OnCommandListEnd
This in turn would make the gpu thread produce to its own command queue.
After this is tested and shows no regressions I will bring back the bounded queue. I believe this is the root cause of the problems the bounded queue encountered.
> gpu_thread: Remove OnCommandListEndCommand

- src/core/hle/kernel/k_process.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
Mistake from #9173.
Fixes #9743.
> core: kernel: k_process: Use application system resource.

- src/core/hle/kernel/svc/svc_info.cpp
The build fails due to `info_id` being used before it's defined.
From #9742
> kernel/svc: Fix undefined info_id

- src/video_core/host_shaders/CMakeLists.txt
- src/video_core/host_shaders/convert_msaa_to_non_msaa.comp
- src/video_core/host_shaders/convert_non_msaa_to_msaa.comp
- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_opengl/gl_texture_cache.h
- src/video_core/renderer_opengl/util_shaders.cpp
- src/video_core/renderer_opengl/util_shaders.h
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
- src/video_core/texture_cache/formatter.cpp
- src/video_core/texture_cache/texture_cache.h
- src/video_core/texture_cache/util.cpp
This is an initial implementation of MSAA image uploads and copies in OpenGL. The main challenge for MSAA support has been replicating the memory layout of MSAA textures, since the APIs forbid calling most typical memory operations on MSAA textures (likely because the memory layout could be device/driver dependent).
Implementing this on Vulkan proved to be a lot more tedious, so for now, it remains unsupported.
This was tested on Sonic Forces, which uses MSAA textures for the background of the map screen:
https://user-images.githubusercontent.com/52414509/217416312-7b7917cf-0a2d-4481-a9a4-7563dc5a9e6e.mp4
https://user-images.githubusercontent.com/52414509/217416319-9d1e4deb-83e4-4cdd-9e8b-04b3200d71f7.mp4
Further testing on other titles known to use MSAA would be appreciated.
> texture_cache: OpenGL: Implement MSAA uploads and copies

- src/core/hid/emulated_controller.cpp
- src/core/hid/emulated_controller.h
- src/core/hid/hid_types.h
- src/core/hid/motion_input.cpp
- src/core/hid/motion_input.h
- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
- src/core/hle/service/hid/hid.cpp
Fixes motion constantly recalibrating on `Metroid Prime`. This PR allows the game to set the desired gyro sensitivity.
> core: hid: Use gyro thresholds modes set by the game

- src/common/settings.cpp
Added missing graphical settings to RestoreGlobalState() to prevent from showing per-game-settings in global settings for these.
> settings: added missing graphical settings to RestoreGlobalState()

- src/audio_core/renderer/command/command_buffer.cpp
Biquad filter commands are generated for each channel, and each command is meant to use a separate state, but I wasn't accounting for this properly and using the same state offset for every biquad command, so each one was trampling over others. This PR fixes the noise generated in games which use biquad commands, like Metroid and Fire Emblem and surely a lot more.
> [audio_core] Use different state offset for each biquad filter channel

- src/yuzu/main.cpp
Reverts yuzu-emu/yuzu#9793
This is apparently causing issues with HDR. I suspect there is no good solution unless you are already using Direct3D to render, which I can't see happening.
> Revert "main: Fix borderless fullscreen for high dpi scaled displays"

- src/audio_core/renderer/command/command_generator.cpp
- src/audio_core/renderer/command/effect/aux_.cpp
Missed a check in the depop prepare command generation which led to an index of -1 being used, grabbing a very random chunk of memory as a mixinfo, and leading to the depop prepare command writing to random parts of memory and crashing audio and Yuzu. This fixes Metroid Prime crashing and the audio exploding randomly.
Biquad filter is still a problem for Metroid Prime, there's noticable noise in some parts of the game. I was trying to fix that too, but Mary confirmed our impl to be apparently equivalent to Switch, but even Mary's PR was unfortunately unable to fix it so I'll keep looking.
> [audio_core] Fix depop prepare

- src/video_core/engines/maxwell_3d.cpp
This register seems to be real, and stops the undefined behaviour flickering on XC3 terrain. We used to have this, but it seems to have been removed by accident.
> Re-add the invalidate_texture_data_cache register

- src/yuzu/configuration/config.cpp
- src/yuzu/game_list.cpp
- src/yuzu/game_list.h
- src/yuzu/main.cpp
Qt isn't always writing changes on save. This causes config to be lost on crash. This PR ensures all changes are always saved on the file.
Additionally restarting a game didn't refresh the per game config since the game wasn't stopped before booting the game again.
> yuzu: Write to config file on important config changes

- src/video_core/host1x/codecs/codec.cpp
Currently we're only CPU decoding videos with 1 thread, we can get a boost by allowing libav to choose the thread count, which should be >1. We might have to limit the threads here if libav is too greedy, but I think this is ok for testing at least.
Also gets rid of the default-set FF_THREAD_FRAME flag. Docs say: 
> Use of FF_THREAD_FRAME will increase decoding delay by one frame per thread,
> so clients which cannot provide future frames should not use it.
We work on a per-frame basis, so this should be disabled. Plus it crashes libav if you use this with >1 thread in Yuzu it seems.
This should help some users with slow video decoding when GPU-decoding isn't supported. For me, it fixes the choppy audio in the SSHD intro video, due to frame decoding taking >16ms. Sped up the SSBU video …
> Allow >1 cpu threads on video decoding, disable multi-frame decoding

- src/core/hid/emulated_console.cpp
- src/core/hid/emulated_devices.cpp
- src/input_common/drivers/mouse.cpp
- src/input_common/drivers/mouse.h
- src/input_common/input_mapping.cpp
- src/yuzu/bootmanager.cpp
- src/yuzu/bootmanager.h
- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/configuration/configure_ringcon.cpp
- src/yuzu/main.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Since #4949 any user that had a window scale different from 100% will have wrong mouse coordinates. This PR fixes the issue by removing the workaround for scaling since now it should be 1:1 at any scale. 
This PR also splits mouse input into 3 different devices. A physical mouse, touch and finally one for controllers. This solves the issue Zeikken85 had where having `emulated mouse` enabled had a weird behavior on stick input. As a final protection against setting invalid configs a warning message will show up if emulated mouse is enabled.
Fixes #7853
> Qt: Fix mouse scalling

- src/shader_recompiler/frontend/maxwell/translate_program.cpp
- src/shader_recompiler/host_translate_info.h
- src/shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp
- src/shader_recompiler/ir_opt/passes.h
- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/renderer_opengl/gl_buffer_cache.h
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
- src/video_core/renderer_vulkan/vk_buffer_cache.h
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Temporary to fix #9579 (MUA3 rendering issues) while the underlying cause is sorted out
> Revert "shader_recompiler: Align SSBO offsets to meet host requirements"

- src/yuzu/bootmanager.cpp
- src/yuzu/bootmanager.h
Partially reverts #9815. Seems like only mouse input doesn't need scaling but touch input does.
> Qt: Reintroduce scaling for touch input

- src/core/hle/service/sockets/sockets.h
- src/core/hle/service/sockets/sockets_translate.cpp
- src/core/internal_network/network.cpp
- src/core/internal_network/network.h
To handle TCP-connections more accurate in the emulator, the `ECONNRESET` error message should be translated to the game properly.
This happens for example when the game opens a TCP server to the "outside world", where a client connects to. After some time, the client disconnects - if the game now tries to read from the closed socket, this error should appear on the first read. However, in Yuzu, this gets caught in the application instead and is not being passed into the game, meaning that the game never recognizes the client disconnect.
> net: translate ECONNRESET network error

- CMakeLists.txt
- src/web_service/web_backend.cpp
- src/yuzu/discord_impl.cpp
`find_package(httplib 0.11 MODULE)` will refuse library with version >= 0.12.
Maybe solve https://github.com/yuzu-emu/yuzu/issues/9840.
In fact this won't solve this particular issue because the library involved uses pkgconfig file instead of cmake config file (so any version greater than 0.11 would be accepted), but the update is welcome anyway :p
> externals: Update cpp-httplib to latest

- src/yuzu/discord_impl.cpp
If yuzu website is not available this request takes up to 30 seconds on windows. Reduce the time to 3 seconds. This feature isn't critical and we shouldn't waste too much time on it.
> yuzu: Set a lower timeout for discord presence

- src/common/settings.cpp
- src/core/hid/emulated_devices.cpp
- src/core/hid/emulated_devices.h
- src/core/hle/service/hid/controllers/gesture.cpp
- src/core/hle/service/hid/controllers/mouse.cpp
- src/core/hle/service/hid/controllers/touchscreen.cpp
Mouse input was completely broken for multiple reasons. The most important one is that we map it as a normal joystick, a joystick has properties like deadzone, range, that aren't by default zero this caused the final output to be completely different from the actual mouse input.
As side fixes. 
Rename some functions to describe better what they do.
Simplifies mouse and keyboard mappings.
Disabling touch actually disables touch. 
Input settings are logged.
> core: hid: Fix native mouse mapping

- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_graphics_advanced.cpp
This setting wasn't saving properly in per game config. Now it should work.
> config: Fix per game Force max clock

- src/core/hid/emulated_controller.cpp
- src/core/hid/motion_input.cpp
- src/core/hid/motion_input.h
- src/input_common/drivers/mouse.cpp
- src/input_common/drivers/mouse.h
- src/input_common/input_mapping.cpp
Yuzu already had motion from mouse. However it was pretty bad. Metroid prime on hybrid mode uses only gyro data. Even better just two axis. This is 1:1 mapping and provides excellent camera control with mouse panning on this game.
The dedicated motion doesn't include any clamping of inputs and has a different sensitivity allowing to be used without changing the config. As for other games they will probably still have bad motion as they use full motion instead of just gyro.
> input_common: Implement dedicated motion from mouse

- src/common/scratch_buffer.h
- src/common/settings.cpp
- src/common/settings.h
- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/texture_cache/image_base.h
- src/video_core/texture_cache/texture_cache.h
- src/video_core/texture_cache/texture_cache_base.h
- src/video_core/textures/astc.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_graphics_advanced.cpp
- src/yuzu/configuration/configure_graphics_advanced.h
- src/yuzu/configuration/configure_graphics_advanced.ui
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
Currently, the GPU thread blocks waiting for ASTC textures to be decoded.
This PR adds another weapon in the war against ASTC: deferring ASTC texture decoding to a separate thread, unblocking the GPU thread. This significantly reduces the notorious stutter caused by ASTC.
The setting can be found under the Advanced Graphics configuration tab.
This uses the CPU decoding implementation, since using the compute shader for this would have been much more complicated for potentially unnoticeable gains.
This does result in some missing graphics while the texture is being decoded, but these are usually quick to clear up unless the system has a low thread count or the title uses many ASTC textures.
An example of missing graphics from async ASTC loading (1 ASTC decode thread): …
> texture_cache: Add asynchronous ASTC texture decoding

- src/core/hle/service/btm/btm.cpp
These functions weren't correctly implemented. They should return a bool if the handle was correctly assigned. This should fix pokemon violet and scarlet on the latest update.
> service: btm: Fix handle functions

- CMakeLists.txt
- src/common/CMakeLists.txt
- src/core/CMakeLists.txt
- src/input_common/CMakeLists.txt
- src/network/CMakeLists.txt
- src/yuzu/CMakeLists.txt
The true imported target name since CMake 3.15 is `Boost::headers` instead of `Boost::boost`. Also remove old hacks not needed anymore (hopefully :p).
> cmake: use correct boost imported targets

- src/video_core/vulkan_common/vulkan_device.cpp
Since we do not request the extension in this case, the feature should be left disabled.
> vulkan_common: disable vertexInputDynamicState on unsupported driver

- src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
- src/core/hle/kernel/init/init_slab_setup.cpp
- src/core/hle/kernel/k_address_arbiter.cpp
- src/core/hle/kernel/k_address_space_info.cpp
- src/core/hle/kernel/k_condition_variable.cpp
- src/core/hle/kernel/k_light_lock.cpp
- src/core/hle/kernel/k_process.cpp
- src/core/hle/kernel/k_scheduler_lock.h
- src/core/hle/kernel/k_thread.cpp
- src/core/hle/kernel/k_thread.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/svc_types.h
Also fixed a subtle deadlock in our kernel code while adding the new LockWithPriorityInheritanceInfo implementation, which would occur if a host and guest address had the same bit value.
> kernel: support for 16.0.0

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/engines/maxwell_dma.cpp
- src/video_core/engines/maxwell_dma.h
- src/video_core/renderer_null/null_rasterizer.h
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.h
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/texture_cache/image_info.cpp
- src/video_core/texture_cache/image_info.h
- src/video_core/texture_cache/texture_cache.h
- src/video_core/texture_cache/texture_cache_base.h
- src/video_core/texture_cache/types.h
- src/video_core/texture_cache/util.cpp
- src/video_core/texture_cache/util.h
This implements host acceleration of the DMA engine. This is used in many games to download textures. Only implemented in Vulkan.
This improves performance in:
- Metroid Prime Remaster.
- Super Mario Sunshine.
- Super Mario Galaxy.
Among others.
> YFC - Engines: Implement Accelerate DMA Texture.

- src/core/hle/kernel/k_scoped_lock.h
[Found](https://github.com/yuzu-emu/yuzu/files/10897537/yuzu-s20230303.log) with libc++ >= 16 (without polyfill_ranges.h) and `-DYUZU_USE_PRECOMPILED_HEADERS=OFF` ([as workaround](https://github.com/freebsd/freebsd-ports/commit/f98c438a0191)).
> kernel: add missing header for libc++

- src/audio_core/renderer/command/effect/reverb.cpp
- src/audio_core/renderer/effect/i3dl2.h
- src/audio_core/renderer/effect/reverb.h
I had the Reverb and I3dl2Reverb delay lines set up the same way, but they're actually not the same. I3dl2 uses separate input and output pointers for reading/writing, whereas Reverb uses just a single one. Since Reverb uses just a single pointer, I've made input/output both begin at index 0, and ensure they always increment together, and that it reads before writing.
The pre delay line in particular was having problems due to never calling Tick on it, which updates the output pointer. It was writing in samples and increasing its input pointer, but it only ever read from output[0]. Instead, that one access should be a TapOut (which reads via input rather than output), with the pre delay time from the state as the index.
This should (hopefully) fix the rare broken audio in any games using …
> Fix a bug with the Reverb command in reading from the pre delay line

- CMakeLists.txt
- dist/yuzu.manifest
- src/common/CMakeLists.txt
- src/common/steady_clock.cpp
- src/common/steady_clock.h
- src/common/wall_clock.cpp
- src/common/wall_clock.h
- src/common/windows/timer_resolution.cpp
- src/common/windows/timer_resolution.h
- src/common/x64/native_clock.cpp
- src/core/core_timing.cpp
- src/core/core_timing.h
- src/core/hardware_properties.h
- src/video_core/gpu.cpp
- src/yuzu/main.cpp
- src/yuzu_cmd/yuzu.cpp
This PR aims to reduce CPU usage on Windows caused by the CoreTiming event loop in 2 ways:
1. Reducing the cost of querying the current time
This was done by implementing a high resolution `SteadyClock`, which is ~2.5x faster compared to querying RDTSC.
While `QueryPerformanceCounter` has a lower precision than RDTSC, it offers sufficient precision (microsecond precision) for our needs.
2. Increasing the timer resolution
Increasing the timer resolution from 1ms to 0.5ms allows us to have 500 microsecond sleeps, which significantly reduces the amount of time needed during the spin-wait.
This was achieved by utilizing the undocumented `ntdll` functions `NtSetTimerResolution` and `NtDelayExecution`.
This results in significantly lower CPU usage in core timing heavy games such as Kirby and …
> core_timing: Reduce CPU usage on Windows

- src/common/bit_cast.h
Uses `__builtin_bit_cast` if it is not supported by the standard library for whatever reason (Apple Clang is the only target where this is the case).
> common: make BitCast constexpr

- src/common/CMakeLists.txt
- src/common/overflow.h
- src/core/hle/kernel/k_resource_limit.cpp
We specify -fwrapv for non-msvc compilers, but msvc has no equivalent to force wrapping for signed integers. This appears to be the only instance in the kernel where wrapping of signed integers is depended on.
> kernel: avoid signed overflow UB on MSVC

- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
Third time's the charm? Thanks to @bylaws for helping out with this one.
Instead of only checking component[0] for red, check all components. Red and green usage here should be exclusive (as per ByLaws), swizzles should only contain either red or green and not both. If no red is found it's assumed green, but if there's no green either and all the components are either zero or one, then that should also be fine, since they'll return constants anyway it doesn't matter if it tries to pull from depth or stencil.
Closes #9805. Hopefully for the last time.
> Check all swizzle components for red, not just [0]

- src/common/settings.h
- src/input_common/drivers/mouse.cpp
- src/input_common/input_mapping.cpp
After talking with some metroid fans we arrived at the conclusion that high dpi mouses move really fast and even 1% still too fast for yuzu. Motion from mouse also felt with a considerable delay and a bit choppy.
I addressed this issue by making the default sensitivity 50% instead of 10%, removing the smoothing filter, lowering the motion threshold, clamping the rotation speed and accumulating all inputs until they are delivered. This improves the feedback and play ability with mouse and keyboard.
> input_common: Increase mouse sensitivity range

- src/shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp
- src/video_core/buffer_cache/buffer_cache.h
TL;DR Fixes some graphical issues and a crash during the initial loading screen in `Doom Eternal` with the latest update, and potentially other titles.
In NVN, global memory ops such as `STG/LDG` generally act on SSBOs whose address and size is stored in a driver reserved constant buffer at index 0. The memory layout for this reserved memory is 16 byte aligned in the format:
```
u32 ssbo_0_addr_lo
u32 ssbo_0_addr_hi
u32 ssbo_0_size
u32 padding
```
Currently, the shader Global To Storage pass uses this information to add an optimization to directly bind the ssbo that the memory op is acting on, rather than go through the indirection of the constant buffer.
Doom Eternal uncovered a flaw in this optimization. This title seems to be using global memory ops on raw SSBO addresses (potentially …
>  buffer_cache: Add logic for non-NVN storage buffer tracking

- src/audio_core/renderer/adsp/audio_renderer.cpp
- src/common/steady_clock.cpp
- src/common/steady_clock.h
- src/common/x64/native_clock.cpp
- src/common/x64/native_clock.h
- src/core/core_timing.cpp
- src/core/cpu_manager.cpp
- src/core/hle/service/hid/controllers/stubbed.cpp
- src/core/hle/service/hid/controllers/touchscreen.cpp
- src/core/perf_stats.cpp
- src/video_core/gpu_thread.cpp
The initial RDTSC frequency, [as determined by CPUID or estimated](https://github.com/yuzu-emu/yuzu/blob/a7792e5ff83523142230951ac7eacbd7685dc40b/src/common/wall_clock.cpp#L58) may not be accurate to its true frequency and may drift relative to the passage of real time.
This PR re-adjusts the RDTSC frequency in accordance to its real-time frequency after a measurement period of 10 seconds, and is done on a separate temporary thread to avoid blocking execution of the main thread.
This was tested to eliminate any remaining time drift on my system¹ in Super Smash Bros. Ultimate², and is also reported to resolve audio drift in Astral Chain, although I am not able to independently verify the latter. Further testing is needed to determine any potential side-effects of this change.
Before: …
> native_clock: Re-adjust the RDTSC frequency to its real frequency

- src/video_core/renderer_opengl/gl_fence_manager.cpp
- src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
- src/video_core/renderer_opengl/gl_resource_manager.cpp
- src/video_core/renderer_opengl/gl_resource_manager.h
- src/video_core/renderer_opengl/gl_texture_cache.cpp
At least on Nvidia, glClientWaitSync with a timeout of 0 (non-blocking) is faster than glGetSynciv of GL_SYNC_STATUS.
> OpenGL: Prefer glClientWaitSync for OGLSync objects

- src/core/hle/kernel/k_address_arbiter.cpp
- src/core/hle/kernel/k_condition_variable.cpp
- src/core/hle/kernel/k_light_condition_variable.cpp
- src/core/hle/kernel/k_scoped_scheduler_lock_and_sleep.h
- src/core/hle/kernel/k_synchronization_object.cpp
- src/core/hle/kernel/k_thread.cpp
- src/core/hle/kernel/k_thread_queue.cpp
- src/core/hle/kernel/k_thread_queue.h
The old behavior was equivalent for one timer, but would not necessarily be equivalent for multiple timers.
> kernel: add timer pointer to KThreadQueue

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_opengl/gl_texture_cache.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.h
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
- src/video_core/texture_cache/texture_cache.h
- src/video_core/texture_cache/texture_cache_base.h
Deduplicates most of the AccelerateDMA Buffer <-> Image copy code added in #9786 and generalizes it within texture_cache.h rather than being rasterizer specific.
Also implements the code on the OpenGL rasterizer.
> AccelerateDMA: Refactor Buffer/Image copy code and implement for OGL

- src/yuzu/configuration/configure_audio.cpp
- src/yuzu/configuration/configure_audio.ui
- src/yuzu/configuration/configure_general.cpp
- src/yuzu/configuration/configure_general.ui
- src/yuzu/configuration/configure_system.cpp
- src/yuzu/configuration/configure_system.h
- src/yuzu/configuration/configure_system.ui
Audio settings should be in the audio section. Also removed vestigial setting called console ID since it actually did nothing.
> yuzu: Move audio settings to audio section

- src/input_common/drivers/sdl_driver.cpp
On the endless quest of vibration issues. Turns out if you have more than one player with the same controller connected or even using dual joycon with a single controller you can get two consecutive vibration commands to the same controller.
My solution this time was to just grab the latest element from the queue rated to a specific controller. Ignoring the rest and ensuring the controller can handle the vibration.
> input_common: sdl: Only send last vibration command

- src/video_core/renderer_vulkan/vk_scheduler.cpp
- src/video_core/renderer_vulkan/vk_scheduler.h
@bylaws pointed out to me that the current Vulkan scheduler implementation waits excessively when a command chunk is split during recording -- this prevents recording from occurring asynchronously. ~~Additionally, when calling Finish, the scheduler waits first for execution to complete, and then waits again on the timeline semaphore for the data to be processed.~~  This was unintentionally regressed by #9016 when I was fixing an issue in WaitWorker.
To work around this, I added a separate method, DrainRequests, which simply waits for the queue to be drained without also waiting for processing to finished, and reworked the locking to accommodate this system.
> vk_scheduler: split work queue waits and execution waits

- src/video_core/vulkan_common/vulkan_device.cpp
This should fix the green and pink colored lens flares appearing in Super Mario 3D World occurring with latest Steam Deck update and mesa main. (Bisected by @piplup55 to mesa f42521f6c3f2eb8546a9290f26d25f05a85f6c85)
> vulkan: disable extendedDynamicState3ColorBlendEquation on radv

- src/yuzu/configuration/configure_input.cpp
Since per-game controller config was added, all controller config that was modified while the game was running was lost when the game closed. This generated annoying issues where you had to configure your controller every time you forgot to do it while the game was closed. 
This PR fixes that issue. Special thanks to epicboy since he did everything. I'm just making the PR.
> config: Fix controller config from resetting

- src/video_core/textures/texture.cpp
Shaders in Xenoblade break with this enabled, as the TSC passes in 8161.0 as the R border colour, but with SRGB conversion enabled we ignore it, and return 1.0 from the SRGB LUT instead. The different between 1.0 and 8161 is very large, and so near edges the values scale up significantly. In the shaders this sampler is used in, the sampled value is used with addition/subtraction on small numbers. In some pixels I was looking at, it's subtracted from a value of ~3.2, and it's then compared > 0.0. Currently this remains positive and passes as needing to be shadowed. With the 8161 border colour value instead, this goes very negative, and fails the check instead, discarding the pixel as a shadow, which seems to be correct behaviour. 
I don't know what the real issue here with SRGB is, because …
> [video_core] Disable SRGB border color conversion in samplers

- src/video_core/renderer_vulkan/vk_scheduler.cpp
Noticed this issue while reviewing #9973. WaitWorker would end up holding the queue mutex until the execution mutex was released, which would cause anything that wanted to push to the queue to wait.
> vulkan: fix more excessive waiting in scheduler

- src/core/hle/service/nfc/nfc_device.cpp
- src/core/hle/service/nfc/nfc_device.h
- src/core/hle/service/nfp/nfp_device.cpp
- src/core/hle/service/nfp/nfp_device.h
Minor bug I found while testing the feature. We need to initialize or finalize the controller when the connection status changes.
> nfc: Initialize device when controller is connected

- src/video_core/texture_cache/texture_cache.h
Investigating issues with game playback for Tsukihime -A Piece of Blue Glass Moon- (01001DC01486A000), a `perf` trace seemed to indicate that a significant chunk of time during stutters was being eaten up by hash table node instantiation inside the texture cache:
On further digging, the issue appears to be a simple missing reference when capturing the gpu page table for a mapper lambda fed into ForEachGPUPage, causing the entire table to be duplicated a few hundred/thousand times per second in certain scenes. Converting the capture to a reference basically eliminates stuttering from this game, and may have an impact on others.
> Pass GPU page table by reference inside TextureCache::ForEachImageInRegionGPU

- src/common/container_hash.h
```
In file included from src/video_core/macro/macro.cpp:9:
src/./common/container_hash.h: In function ‘void Common::HashCombine(std::size_t&, const T&)’:
src/./common/container_hash.h:67:58: error: ‘CHAR_BIT’ was not declared in this scope
67 |     seed = detail::HashCombineImpl<sizeof(std::size_t) * CHAR_BIT>::fn(seed, detail::HashValue(v));
|                                                          ^~~~~~~~
src/./common/container_hash.h:10:1: note: ‘CHAR_BIT’ is defined in header ‘<climits>’; did you forget to ‘#include <climits>’?
9 | #include <vector>
+++ |+#include <climits>
10 | 
src/./common/container_hash.h:67:66: error: template argument 1 is invalid
67 |     seed = detail::HashCombineImpl<sizeof(std::size_t) * CHAR_BIT>::fn(seed, detail::HashValue(v));
| …
```
> container_hash: use climits

- src/core/hle/service/nfp/amiibo_crypto.cpp
- src/core/hle/service/nfp/amiibo_crypto.h
- src/core/hle/service/nfp/nfp_device.cpp
- src/core/hle/service/nfp/nfp_device.h
- src/core/hle/service/nfp/nfp_types.h
It was rather easy to add support now. So why don't have it. This PR allows to load plain amiibo files, since they aren't encrypted there is no need for keys. This still requires a valid amiibo dump.
> service: nfp: Add plain amiibo support

- src/yuzu/main.cpp
Some users where having softlocks at boot. For some reason we don't start logging right away but we do push logs into the queue. If we fill the queue before the log starts yuzu softlocks.
> qt: Fix log softlock

- src/common/CMakeLists.txt
- src/common/telemetry.cpp
- src/common/x64/cpu_detect.cpp
- src/common/x64/cpu_detect.h
- src/common/x64/cpu_wait.cpp
- src/common/x64/cpu_wait.h
- src/common/x64/native_clock.cpp
- src/core/core_timing.cpp
Intel introduced the new waitpkg instructions starting with their 12th Gen Alder Lake CPUs.
Of particular interest is [TPAUSE](https://www.felixcloutier.com/x86/tpause), which enables the processor to go to a lower power state while waiting for the TSC counter deadline to pass.
We have chosen a value of 100,000 cycles as a standard value to wait for, as it provides a balance between power savings and timer precision.
For reference:
At 1 GHz, 100K cycles is 100us
At 2 GHz, 100K cycles is 50us
At 4 GHz, 100K cycles is 25us
This has resulted in measurable power savings (10-20%), building upon the power savings from #9889, but exclusive to CPUs supporting these instructions (Intel 12th gen and newer for now).
> x64: Make use of waitpkg instructions for power efficient sleeps

- CMakeLists.txt
- src/video_core/vulkan_common/vulkan_wrapper.cpp
[VK_EXT_shader_object](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_shader_object.html) extends `VkResult`. Some distros [already updated](https://repology.org/project/vulkan-headers/history).
```c++
src/video_core/vulkan_common/vulkan_wrapper.cpp:285:13: error: enumeration value 'VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT' not handled in switch [-Werror,-Wswitch]
switch (result) {
^~~~~~
```
> externals: update Vulkan-Headers to v1.3.246 to fix -Werror=switch with system package

- src/core/frontend/applets/controller.cpp
- src/core/frontend/applets/controller.h
- src/core/hle/service/am/applets/applet_controller.cpp
- src/core/hle/service/am/applets/applet_controller.h
- src/yuzu/applets/qt_controller.cpp
- src/yuzu/applets/qt_controller.h
- src/yuzu/applets/qt_controller.ui
- src/yuzu/main.cpp
- src/yuzu/main.h
This applet can be canceled. This is used on games like MK8 where it takes you to the previous menu instead of an infinite loop until you meet the conditions. This PR also solves a bug where player count wasn't correct due not saving controller config first.
This PR conflicts with #9505 so don't tag until that one is merged first.
> applet: controller: Implement cancel button

- src/audio_core/device/device_session.cpp
- src/audio_core/renderer/adsp/audio_renderer.cpp
- src/audio_core/renderer/adsp/audio_renderer.h
- src/audio_core/renderer/system_manager.cpp
- src/audio_core/renderer/system_manager.h
- src/audio_core/sink/cubeb_sink.cpp
- src/audio_core/sink/sdl2_sink.cpp
- src/audio_core/sink/sink_stream.cpp
- src/audio_core/sink/sink_stream.h
- Should help to prevent stalls from needing to happen by attempting to tie the guest sample tracking to the host
- I am still unsure about the second patch, needs checking against RE to see if this wait time is included in the execution time accounting. The implementation is also kinda dodgy, ideally you'd keep track of reserved and submitted buffers and ensure they match
> Audio synchronisation improvements

- src/core/arm/dynarmic/arm_dynarmic_32.cpp
* Range invalidation, return stack buffer, and minor bugfixes for arm64 backend.
* AVX-512 implementation for VectorTableLookup64
> externals: Update dynarmic to 6.4.6

- src/core/hle/service/hid/controllers/npad.cpp
As said by the comment I left before. nnsdk doesn't validate this value I walked through the code and found that any value defaults to the unknow sixaxis state. We already do that so we can safely remove the check.
Fixes #10018
> service: hid: Fix handle validation

- src/CMakeLists.txt
- src/common/intrusive_red_black_tree.h
- src/common/typed_address.h
- src/core/internal_network/socket_proxy.h
- src/core/internal_network/sockets.h
- src/web_service/verify_login.cpp
In this round of "why does this break every time", we see that gcc 13 and clang 16 regress implicit conversions in equality comparisons due to a change introduced for C++20 standard compliance (see section 4 "rewritten candidates" here https://en.cppreference.com/w/cpp/language/overload_resolution).
This also sets -Wno-array-bounds, Wno-stringop-overread, -Wno-stringop-overflow for gcc 12+. These would be amazing to have if they worked, but just produce so many bogus diagnostics that there is no point keeping them enabled. Hopefully clang will eventually introduce working versions of the stringop warnings.
> general: fixes for gcc 13

- src/audio_core/sink/sink_stream.cpp
- src/audio_core/sink/sink_stream.h
Some games have very tight scheduling requirements for their audio which can't really be matched on the host, adding a constant to the reported value helps to provide some leeway.
> Add some explicit latency to sample count reporting

- src/input_common/drivers/mouse.cpp
Noticed this while messing with motion. This multiplies `last_motion_change.z` by two each time it's called, which is definitely wrong.
> input_common: minor fix to mouse movement

- src/dedicated_room/yuzu_room.cpp
In some scenarios, it is important to allow for dedicated room servers to specify the bind address.  For example, `fly.io` requires that UDP services bind to a special address aliased by `fly-global-services`, as routing for UDP packets when bound to `0.0.0.0` does not function properly (has to do with how their global routing works).  In scenarios such as that, the dedicated server should allow for the user to set a custom bind address.
*These changes are _backward compatible_, as the execution continues normally without error, and the previous behavior is preserved, if the new argument is not set.*
* Allow for the user to pass `--bind-address` to the dedicated room executable.  Otherwise, default to the existing default, which appears to be `0.0.0.0`.
* Add an info statement to the log …
> Allow passing `--bind-address` to dedicated room.

- src/core/hle/service/am/am.cpp
This function was logged 194k times while playing advance wars for a bit.
> core: am: Demote TryPopFromFriendInvitationStorageChannel Log level

- src/video_core/engines/maxwell_3d.cpp
4 is a possible value for byte_size, which is out of bounds of an array of size 4. This seems to have intended to use the log2 of byte_size to index the array.
> maxwell_3d: fix out of bounds array access in size estimation

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_opengl/gl_texture_cache.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
- src/video_core/texture_cache/texture_cache.h
- src/video_core/texture_cache/texture_cache_base.h
This fixes Pokemon Sword and Hyrule warriors AoC regressions.
> Refactor Accelerate DMA and do downloads through TC.

- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Intel's SPIR-V shader compiler is broken. For now, skip compiling any compute pipelines until they fix this issue.
This is not a perfect workaround, as there are a small subset of non-compute pipelines that still cause it to crash, but this should cover the majority of crashes.
It is unfortunate that even with a test case reported 6 months ago the issue has not been fixed in favor of fixing "[the most popular games and apps](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/159#issuecomment-1527618555)".
Intel, you can do better than this.
> vk_pipeline_cache: Skip compute pipelines on Intel proprietary drivers

- src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
- src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
https://registry.khronos.org/VulkanSC/specs/1.0-extensions/man/html/SampleMask.html
SampleMask must be defined as an array. This gets rid of a validation error.
> Define SampleMask as an array

- src/yuzu/main.cpp
- src/yuzu/main.h
Pops up a warning informing you that your keys can't decrypt the Mii model from your firmware dump (this has already happened to me twice when forgetting to update lockpick after a new major version)
> qt: warn on inoperable keys

- src/CMakeLists.txt
Enables shadow-uncaptured-locals, type-limits and implicit-fallthrough for Clang. implicit-fallthrough is not enabled by default in -Wall or -Wextra, and shadow-uncaptured-local doesn't seem to be enabled by default by -Wshadow, even though GCC has both of these by their respective cases.
Exposed by CI on #10125 
Clang's shadow-all seems to enable checks more than GCC's shadow, and raises more warnings than GCC does as-is. Choosing not to enable that for now.
> CMakeLists: Enable more checks on Clang

- src/common/settings.cpp
- src/common/settings.h
- src/video_core/CMakeLists.txt
- src/video_core/renderer_vulkan/renderer_vulkan.cpp
- src/video_core/renderer_vulkan/renderer_vulkan.h
- src/video_core/renderer_vulkan/vk_blit_screen.cpp
- src/video_core/renderer_vulkan/vk_blit_screen.h
- src/video_core/renderer_vulkan/vk_present_manager.cpp
- src/video_core/renderer_vulkan/vk_present_manager.h
- src/video_core/renderer_vulkan/vk_scheduler.cpp
- src/video_core/renderer_vulkan/vk_scheduler.h
- src/video_core/renderer_vulkan/vk_swapchain.cpp
- src/video_core/renderer_vulkan/vk_swapchain.h
- src/video_core/renderer_vulkan/vk_update_descriptor.cpp
- src/video_core/renderer_vulkan/vk_update_descriptor.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_graphics_advanced.cpp
- src/yuzu/configuration/configure_graphics_advanced.h
- src/yuzu/configuration/configure_graphics_advanced.ui
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
While #9931 fixed a lot of scheduler stalls that occured in DispatchWork, the backend's ability to generate frames in async is still limited due to the fact that WaitWorker must be called at the end of each frame, which may be expensive depending on what the scheduler is [doing](https://github.com/yuzu-emu/yuzu/blob/master/src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp#L496). Thus the main goal of this PR is to offload swapchain operations to a separate thread to avoid such a wait and allow the backend to have multiple frames in flight.
The present manager class handles all swapchain calls. It maintains a separate thread that acquires and presents any frames that are pushed to the present queue. The GPU thread will send render frames and wait for free ones, to prevent …
> Implement asynchronous presentation

- src/common/settings.cpp
- src/common/settings.h
- src/core/core.cpp
- src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_general.cpp
- src/yuzu/configuration/configure_general.h
- src/yuzu/configuration/configure_general.ui
- src/yuzu/configuration/configure_system.cpp
- src/yuzu/configuration/configure_system.h
- src/yuzu/configuration/configure_system.ui
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
People keep enabling this without understanding what it does. It does _not_ make your games perform better, or allocate more VRAM, it just allows loading larger resource files than the Switch natively supports, and pointlessly wastes 4GiB of memory if you aren't using model or texture replacement mods.
Because having this option enabled can break games (spawns falling through the ground in Scarlet/Violet), I have
1. moved it to the bottom of the System tab (so people are less likely to see it in the first place)
2. renamed the setting, so that it will no longer take effect without explicitly enabling it again
3. added the setting to the log file printout so that it can be used for diagnostics.
> settings: rename extended memory layout to unsafe, move from general to system

- vcpkg.json
Fixes compile error with gcc 13
> catch2: update to 3.3.1

- src/core/memory.cpp
- src/video_core/fence_manager.h
- src/video_core/memory_manager.cpp
- src/video_core/memory_manager.h
- src/video_core/query_cache.h
- src/video_core/renderer_opengl/gl_fence_manager.h
- src/video_core/renderer_opengl/gl_query_cache.cpp
- src/video_core/renderer_opengl/gl_query_cache.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_fence_manager.cpp
- src/video_core/renderer_vulkan/vk_fence_manager.h
- src/video_core/renderer_vulkan/vk_query_cache.cpp
- src/video_core/renderer_vulkan/vk_query_cache.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
This pull requests aims to do 3 things:
1st Allow verification of fencing and writing of async downloads in a separate thread.
2nd Restructure the way accuracy is handled. Normal accuracy will now skip host-guest fence syncing and won't download on host conditional rendering.
3rd Rework Query Cache async downloads to be more consistent.
as a result when paired with the buffer cache revamp and Faster DMA:
- Performance greatly improves in many games with Normal accuracy.
- Splatoon 2's ink now works perfectly in AMD. (Splatoon 2 requires High accuracy).
> Y.F.C Implement Asynchronous Fence manager and Rework Query async downloads

- src/video_core/shader_cache.cpp
- src/video_core/shader_environment.cpp
- src/video_core/shader_environment.h
SetCachedSize is returning the size in bytes of the shader code, and using that to resize the u64 code array. Everywhere else I saw currently wants the byte size, but I figured adding a word size function can't hurt, rather than changing the callsite. This fixes the code array being 8 times larger than it should be, and why our shader dumps have always been so huge.
> Fix shader code resize to use word size rather than byte size

- src/audio_core/renderer/system.cpp
Without this, the DSP can still be active with a command list, using memory from a System which is being destroyed. The terminate event here ensures that doesn't happen. I had to remove it before due to relying on CoreTiming to signal it, but CoreTiming stops before services are shut down, which meant it would never signal and deadlock on shutdown.
ByLaws removed the reliance on CoreTiming, so this should be fine now, and remove the use after free.
> Wait for the terminate event before destroying a system instance

- src/core/hid/emulated_controller.cpp
Avoids leaving the buttons active forever
> core: hid: Fix state of capture and home buttons

- src/common/address_space.inc
fixes #10168 
potentially also fixes #10126
OP from the support thread linked in the first issue here. Now I may not exactly be the most qualified person to work on this, but yesterday a Twitch chatter who claims to work at Google took a look at my issue and seems to be "almost certain" that this should fix the issue. Apparently, due to company policy, they are not allowed to contribute to emulators.
Tried out the fix today, and for the first time ever I was able to play through the entire game up to the credits in a single sitting without a crash. Can't really explain much of this myself, but apparently devs of this should be able to "immediately understand" the change.
> Fix read access violation after 2 hours of gameplay in PMD: RTDX

- src/common/input.h
- src/common/vector_math.h
- src/core/hid/emulated_controller.cpp
- src/core/hid/emulated_controller.h
- src/core/hid/input_converter.cpp
- src/core/hid/motion_input.cpp
- src/core/hid/motion_input.h
- src/input_common/input_engine.cpp
- src/input_common/input_poller.cpp
- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/configuration/configure_input_player_widget.cpp
- src/yuzu/configuration/configure_input_player_widget.h
Adds a little 3d cube to the preview that is linked to motion input. This helps to determine if motion has been setup properly.
> yuzu: Add motion preview to controller input

- src/audio_core/sink/sdl2_sink.cpp
- src/yuzu_cmd/config.cpp
Issue was fixed a long time ago, both by SDL2 and in yuzu by including SDL2 as a system library.
Partially reverts f973274 (the other files seemed to have been cleaned up by now).
> yuzu-sdl,audio_core: Remove antiquated warning ignore

- src/common/input.h
- src/core/hid/input_converter.cpp
- src/input_common/input_poller.cpp
- src/yuzu/configuration/configure_input_player.cpp
Some controller manufacturers seem to follow no standard when it comes to triggers. This allows to invert the final state of an axis button.
> input_common: Add property to invert an axis button

- src/core/hid/input_converter.cpp
- src/input_common/input_mapping.cpp
This is a little experiment from an user request. I still need to polish my ideas to allow individual motion axis and most likely motion to stick input.
For now you can map motion to any button and trigger it with a shake.
> input_common: Add experimental motion to button

- src/common/address_space.inc
One more update for this file: https://github.com/skyline-emu/skyline/commit/12c88babd0a8599425007a1c02a74bd4639e4600
Everything else seems identical to Skyline now.
> Fix address space allocator slow path to avoid OOB

- src/yuzu/applets/qt_profile_select.cpp
**In the profile selection window:**
*(enabled if the option "Prompt for user on game boot" is checked)*
Allow the user to start the game by double-clicking a profile to avoid having to additionally click the OK button. This avoids an unnecessary "step" to the start of the game...
Fixes https://github.com/yuzu-emu/yuzu/issues/10185.
> yuzu/applets/qt_profile_select: connect double-click to accept()

- src/video_core/renderer_opengl/gl_device.cpp
- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_opengl/gl_texture_cache.h
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
- src/video_core/texture_cache/formatter.cpp
- src/video_core/texture_cache/formatter.h
- src/video_core/texture_cache/image_view_base.cpp
- src/video_core/texture_cache/image_view_base.h
- src/video_core/vulkan_common/vulkan_device.h
Validation layers have the ability to print object names if they've been assigned. Currently we only set names if RenderDoc or Nsight is being used, but we should enable it for graphics debugging as well.
This also adds the GPU address to image views, which helps for validation layers and OpenGL in RenderDoc. This is something I kept doing locally, but worth PR'ing it.
Before:
> Validation Error: [ VUID-VkWriteDescriptorSet-descriptorType-00336 ] Object 0: handle = 0xbde60e00000000c6, type = VK_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT; | MessageID = 0xc258ecf8 | vkPushDescriptorSetWithTemplateKHR() VkWriteDescriptorSet[1] failed update validation: Write update to Push Descriptors defined with VkDescriptorSetLayout 0xbde60e00000000c6[] binding #1 failed with error message: Attempted write update …
> Log object names with debug renderer, add a GPU address to ImageViews

- src/video_core/texture_cache/texture_cache.h
Currently we're copying overlapping image's data in a random order, it should be sorted from oldest modification -> newest to avoid clobbering a more-updated overlap with an older one.
> Sort overlap_ids by modification tick before copy

- src/yuzu/bootmanager.h
Fixes #10193 (build on, you guessed it, Apple Clang)
> bootmanager: remove stop_token header

- src/core/hle/service/nifm/nifm.cpp
- src/core/internal_network/network.cpp
- src/core/internal_network/network_interface.cpp
I thought we already silenced these before, but the spam from these is horrible in some games. I left the errors to print once if they're necessary to see.
> Silence network spam

- src/yuzu/qt_common.cpp
Regressed by #10125. Found on FreeBSD. Affects both Qt5 and Qt6.
> qt_common: unbreak build on BSDs

- src/input_common/helpers/joycon_protocol/common_protocol.cpp
- src/input_common/helpers/joycon_protocol/common_protocol.h
- src/input_common/helpers/joycon_protocol/joycon_types.h
- src/input_common/helpers/joycon_protocol/nfc.cpp
When I was cleaning up the magic bytes I accidentally added offsets to the command packages. This PR fixes nfc detection by addressing these issues.
> input_common: Fix nfc detection for joycons

- src/core/hid/emulated_controller.cpp
- src/core/hid/emulated_controller.h
- src/core/hid/motion_input.cpp
- src/core/hid/motion_input.h
- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/configuration/configure_input_player_widget.cpp
Allows to calibrate motion to eliminate motion drift. This can be done multiple times until the cube stops spinning. I also moved the cube for dual joycon since it was overlapping with battery symbols and made the cube with a shape of a joycon so it's easier to distinguish the current orientation.
> core: hid: Allow to calibrate gyro sensor

- src/core/file_sys/vfs_layered.cpp
- src/core/file_sys/vfs_vector.cpp
- src/core/file_sys/vfs_vector.h
This optimization reduces the time it takes to apply a single-file romfs mod in Fire Emblem Engage from ~1.5 minutes to ~3 seconds. The performance is still not ideal, because it wastes a lot of time copying and freeing strings, but still worth doing.
> vfs_vector: avoid n^2 lookup in layeredfs building

- src/common/settings.h
- src/core/hle/service/nfc/common/device.cpp
- src/core/hle/service/nfc/common/device.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_input_advanced.cpp
- src/yuzu/configuration/configure_input_advanced.ui
- src/yuzu_cmd/config.cpp
Some games don't allow to load the same amiibo more than once. This generates a random id so the game always thinks it's a new one.
This feature can be enabled in advanced controller settings.
> service: nfp: Allow to load with a different amiibo id

- README.md
With Skyline disbanded, we're removing the blanket license exception to avoid any confusion with unofficial forks relicensing components of yuzu. Future license exceptions will be handled on a case-by-case basis.
> Update README.md to remove Skyline license exception.

- src/video_core/renderer_vulkan/pipeline_helper.h
- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
- src/video_core/renderer_vulkan/vk_buffer_cache.h
- src/video_core/renderer_vulkan/vk_compute_pass.cpp
- src/video_core/renderer_vulkan/vk_compute_pass.h
- src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
- src/video_core/renderer_vulkan/vk_compute_pipeline.h
- src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
- src/video_core/renderer_vulkan/vk_graphics_pipeline.h
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/renderer_vulkan/vk_pipeline_cache.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.h
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
- src/video_core/renderer_vulkan/vk_update_descriptor.h
This PR separates the update descriptor queues for synchronous compute passes and guest pipelines. This way, they each have their own separate spaces for descriptor set data, and will not interfere with each other during descriptor set updates.
Due to an oversight in how the compute passes were designed, we often ended up binding the pipeline for compute-shader data conversion concurrently with the binding for a guest pipeline. In the best case, this broke the guest pipeline state; in the worst case, it crashed the driver due to the update template not matching up with the update data.
This should fix a bunch of random crashes in games which need to do synchronous compute conversion work (Xenoblade, LM3, Astral Chain, Bayonetta 3, etc.). It should also fix many crashes in validation …
> renderer_vulkan: separate guest and host compute descriptor queues

- src/common/scratch_buffer.h
- src/video_core/engines/sw_blitter/blitter.cpp
- src/video_core/texture_cache/texture_cache.h
Currently the accelerated blit path will return nullopt if neither src nor dst exist in the cache already, and then fall back to the software path. This PR changes that to allow it, I also replaced the vectors with scratchbuffers as they were showing up in the perf profiler as well.
Super Fowlst 2 uses Fermi blit a lot (thousands of times), and consistently fails the accelerate path, and is very very slow during menus, which this PR helps to address. It's still slow even with the accelerated path, but noticeably better. @FernandoS27 is there any reason we can't add both images to the cache and do this? Is it slower for some games? Which? We already allow it to work when *either* src or dst is in the cache, just not both.
Needs perf testing either way.
Before: …
> Allow Fermi blit accelerate to work without images in cache

- src/core/hle/service/nvnflinger/buffer_queue_producer.cpp
- src/core/hle/service/nvnflinger/parcel.h
- src/core/hle/service/vi/vi.cpp
We were consistently serializing the Binder responses wrong in ways that games didn't seem to care about until now. This PR aligns the serialization with what Android actually does, where flattened objects and marshalled IBinders are stored in separate regions in the parcel, and the size of the objects array is not always 4.
The producer slot fence being wrong on the first frame was another thing that jumped out at me, since Android requires that the fence object is never null.
Needed for Tears of the Kingdom to boot.
> nvnflinger: fix Parcel serialization

- src/core/file_sys/savedata_factory.cpp
- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/filesystem/fsp_srv.cpp
- src/core/hle/service/filesystem/fsp_srv.h
Somehow, we didn't have any implementation of this, despite it existing and being used in retail games since at least 2019(?). This adds a stub implementation which always returns 0 results for cache storage, and fixes the response alignment for Read on the info reader.
Needed for Tears of the Kingdom to boot. May also fix other games that use it.
> fs: stub cache storage

- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
The framebuffer sequentially adds only valid render targets to `image_ranges`. However, for clears, we look up the image aspect by render target index, and since the framebuffer skips invalid RTs, this can lead to a mis-match between the requested clear RT and the aspect of the RT we look up.
In Tears of the Kingdom, it uses a framebuffer with colour render targets 0/1/2/4, where 3 is invalid. Our framebuffer adds these into `image_ranges` as 0/1/2/3, and then the depth gets index 4. At the start of the renderpass it tries to clear RT index 4 with a colour clear, which looks up `image_ranges[4]` in `framebuffer->HasAspectColorBit()` and returns false as that's now the depth target, and the clear is skipped entirely. This PR just adds a quick mapping between real RT index and the new …
> Correctly track render target index in the framebuffer for image aspects

- src/core/hle/service/time/clock_types.h
- src/core/hle/service/time/time_sharedmemory.cpp
- src/core/hle/service/time/time_sharedmemory.h
This adds a new structure into the time shared memory which has some nice upgrades compared to before:
- Allows computing the current time in ns
- Automatically adjusts for clock skew
- Uses the same clock source as the steady clock
This should fix the save slot timestamps in Tears of the Kingdom. I didn't figure out how exactly the lower/upper distinction worked, or if the time skew adjustment uses the same values every single time (seems to update every 5-10 minutes). However, I did notice when making a test homebrew that everything gets set to the same value on console boot, so we'll go with that.
> time: implement ContinuousAdjustmentTimePoint

- src/video_core/vulkan_common/vulkan_memory_allocator.cpp
Incredibly silly issue.
1. Under memory pressure, the allocator may mask out ~DEVICE_LOCAL from the allocation request:
https://github.com/yuzu-emu/yuzu/blob/9c739f1506dd549df314ccef386218cdf2e5f3a8/src/video_core/vulkan_common/vulkan_memory_allocator.cpp#L278-L281
2. If the request was for DEVICE_LOCAL, this makes property_flags 0
3. This allocation might then be recycled and used for other purposes
4. The compatibility check for a recycled allocation bitwise-ands the flags argument with 0 and checks if it is equal to 0, which it will be if property_flags is 0:
https://github.com/yuzu-emu/yuzu/blob/9c739f1506dd549df314ccef386218cdf2e5f3a8/src/video_core/vulkan_common/vulkan_memory_allocator.cpp#L148-L151
5. vkMapMemory is then called on an allocation which wasn't host visible and the …
> vulkan_common: fix incompatible property flags

- src/video_core/vulkan_common/vulkan_device.cpp
Under memory pressure, the memory allocator will fall back to host memory for new allocations. If host memory is used in the render pipeline, this will cause a massive performance dip during rendering. However, since we have a garbage collector, we want the GC to trigger earlier, since collection is much faster than using host memory, and should be able to reclaim enough space to prevent needing host memory.
Helps performance loss in Tears of the Kingdom
> vulkan_device: reserve extra memory to prevent swaps

- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
- src/core/hle/service/hid/hid.cpp
Prefer span rather than vector references.
> service: hid: Use span instead of vector reference

- src/input_common/helpers/joycon_protocol/joycon_types.h
- src/input_common/helpers/joycon_protocol/nfc.cpp
- src/input_common/helpers/joycon_protocol/nfc.h
Scanning for amiibos is a really demanding task. We don't need to scan every frame so I reduced the scan rate to 5hz and reduced the number of attempts to get valid data to 1 instead of 7.
This makes the right joycon usable while using the amiibo rune on totk. Small stutters will still happen but nothing like current master
> input_common: Make amiibo scanning less demanding

- src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
- src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp
Adding the shader fixes from #10226 which should fix the flickering clouds and the broken geometry in Tears of the Kingdom.
> Fix Tears of the Kingdom flickering clouds and depths geometry.

- src/yuzu/configuration/configure_hotkeys.cpp
- src/yuzu/configuration/configure_hotkeys.h
- src/yuzu/main.cpp
- src/yuzu/main.h
This PR moves away from prefixing `Home+` on all controller hotkey keybinds and instead allows for fully customisable mapping.
Things to note are:
- Work has gone into protecting the TAS functionality from triggering controller hotkeys.
- I moved away from a separate Home/Screenshot button, it looked like the main purpose of this was for protecting against TAS inputs which I have found a method to do without needing to single out these buttons.
- This is my first time working with C++ and I am very open that I have gaps in better ways of doing some of this work.
Unrelated to the work but there is an issue I found where you can record while in playback mode that probably deserves its own issue.
Closes  #10093.
> Allow fully customised controller hotkeys

- src/video_core/vulkan_common/vulkan_device.cpp
This [bug in radv](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/22777) causes an amusing vertex explosion during a critical gameplay moment in Tears of the Kingdom.
|Before|After|
|-|-|
|![0100f2c0115b6000_2023-05-13_00-35-00-993](https://github.com/yuzu-emu/yuzu/assets/9658600/845cac0a-79cd-4243-b032-54cb700233b2)|![0100f2c0115b6000_2023-05-13_00-30-46-691](https://github.com/yuzu-emu/yuzu/assets/9658600/7fd22552-65be-4dbb-ba88-34582b1bf7c3)|
> vulkan_common: disable depth clamp dynamic state for older radv

- src/video_core/vulkan_common/vulkan_device.cpp
Mesa commit [ff91c5ca4](https://gitlab.freedesktop.org/mesa/mesa/-/commit/ff91c5ca42bc80aa411cb3fd8f550aa6fdd16bdc) breaks VK_KHR_push_descriptor usage on ANV drivers 22.3.0 and later, so disable it here and allow games to boot.
This has not been and needs to be reported to Mesa.
> vulkan_device: Disable VK_KHR_push_descriptor on ANV

- src/video_core/renderer_vulkan/vk_swapchain.cpp
This accesses runtime settings, so it isn't constexpr.
> renderer_vulkan: remove wrong constexpr

- src/input_common/drivers/joycon.cpp
- src/input_common/drivers/joycon.h
- src/input_common/helpers/joycon_protocol/common_protocol.cpp
- src/input_common/helpers/joycon_protocol/joycon_types.h
- src/input_common/helpers/joycon_protocol/nfc.cpp
- src/input_common/helpers/joycon_protocol/nfc.h
Turns out the previous implementation worked by a miracle, is not easy to just read hex data and give it a meaning. This fixes the amiibo detection for both joycon and pro controllers.
Special thanks to byte for providing the logs and Alicia for testing.
> input_common: Fix pro controller amiibo support

- src/input_common/input_engine.cpp
This avoid motion mapping accidentally if calibration is off.
> input_common: Map motion with relative values not absolute ones

- src/video_core/vulkan_common/vulkan_device.cpp
Hardly limiting the device access memory to 4 GB for integrated vulkan devices here. Vulkan seems to detect the Steam Deck's APU as integrated device. This limit works for the Steam Deck in order not to go above 4 GB VRAM usage any more (above this value the likelihood to crash when the RAM exceeds 12 GB as well raises).
But there will be perhaps a detection mechanism necessary for detecting the real memory limit for integrated vulkan devices. Those likely might have small limits anyway, but what about integrated GPUs on machines with > 16 GB RAM, aka larger amounts ?
This might fix #10407 and similar issue reports.
Tested on my steam deck and VRAM usage stayed below 4 GB, even when jumping down the gloomy depths. But it can become  a bit slow when swapping starts, tho.
Note, this is just …
> Limit device access memory for integrated devices to 4 GB

- externals/CMakeLists.txt
- externals/stb/stb_dxt.cpp
- externals/stb/stb_dxt.h
- src/common/settings.cpp
- src/common/settings.h
- src/video_core/CMakeLists.txt
- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_vulkan/maxwell_to_vk.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/texture_cache/util.cpp
- src/video_core/textures/astc.cpp
- src/video_core/textures/bcn.cpp
- src/video_core/textures/bcn.h
- src/video_core/textures/workers.cpp
- src/video_core/textures/workers.h
- src/video_core/vulkan_common/vulkan_device.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/config.h
- src/yuzu/configuration/configure_graphics_advanced.cpp
- src/yuzu/configuration/configure_graphics_advanced.ui
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/default_ini.h
This does two things:
1. Add a setting to transcode ASTC textures into uncompressed RGBA (default, matches previous behavior), BC1 (very low quality, causes issues in many games but saves 8x memory) or BC3 (medium quality, saves 4x memory). Currently the BC1 and BC3 compressors are not GPU accelerated due to challenges in getting it wired up. BC7 may be added in the future, it was not added in time for this PR due to issues with encoding performance.
2. ~~Tunes texture cache and buffer cache memory usage and garbage collection to be more accommodating for ASTC transcoding on systems with less VRAM. This also adds a usage cap based on the resolution scale for cards with very large amounts of memory, which should help prevent slowdowns as memory is filled up.~~ Moved to #10422
When combined …
> video_core: add ASTC recompression

- src/core/hle/kernel/k_memory_block_manager.h
These showed up in a profile but are not intended to be used here.
> k_memory_block_manager: remove auditing calls

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/texture_cache/texture_cache.h
This contains the garbage collection changes which were previously included in #10398. These are being split out due to issues reported with device losses with the GC tweaks - the recompression option itself should not be causing any issues.
> video_core: tune garbage collection aggressiveness

- src/video_core/texture_cache/util.cpp
This fixes gloom being broken in Zelda TotK on low VRAM GPUs.
Thanks to @Kelebek1 and @liamwhite for debugging it.
> Texture Cache Util: Fix block depth adjustment on slices.

- src/video_core/texture_cache/texture_cache.h
This fixes the regressions in UE4 games.
> Texture cache: revert wrong acceleration assumption

- src/core/hle/service/nfc/common/amiibo_crypto.cpp
- src/core/hle/service/nfc/common/device.cpp
- src/core/hle/service/nfc/common/device.h
Adds fallbacks for lack of keys. Any game will be able to load a valid amiibo dump it just won't be able to write any data.
> service: nfc: Remove encryption key requirement

- src/yuzu_cmd/yuzu.cpp
The -u short option was documented but not implemented in yuzu_cmd. The same long option --user worked before.
> Add short "-u" option for yuzu_cmd.

- src/core/hid/emulated_controller.cpp
- src/core/hle/service/nfc/common/device.cpp
- src/input_common/drivers/joycon.cpp
- src/input_common/helpers/joycon_driver.cpp
- src/input_common/helpers/joycon_driver.h
- src/input_common/helpers/joycon_protocol/joycon_types.h
- src/input_common/helpers/joycon_protocol/nfc.cpp
- src/input_common/helpers/joycon_protocol/nfc.h
Ladies and gentlemen, I'm happy to present the first implementation of writing to amiibos with a Joy-Con. This pull request enables you to use your amiibo just as you would on the Nintendo Switch. Amiibos are finally fully natively supported.
Keep in mind that this is an experimental attempt, so please use it at your own risk. I will do my best to ensure the process is as safe as possible to avoid any corruption. Additionally, I will likely implement amiibo backup/restore in a subsequent pull request.
> input_common: Implement amiibo writing

- src/audio_core/renderer/adsp/audio_renderer.cpp
- src/audio_core/renderer/system_manager.cpp
- src/audio_core/renderer/system_manager.h
- src/audio_core/sink/sink_stream.cpp
So far I haven't been able to understand how the DSP limits itself and runs with a consistent timing. From my RE, the best thing I could find was a semaphore wait on the DSP itself when it tries to reserve 240 samples in a mix queue before processing. ByLaws used that to implement his changes here, and it's a nice idea and generally works, however it relies on the host audio callback to function, and no one's system will run at 5ms. 10ms callbacks are the standard and most common I've seen, but that means the DSP essentially runs 2 times instantly, every 10ms, rather than a smooth once every 5ms.
The DSP is responsible for updating some state, such as how many samples a wavebuffer has processed, which is sent back to the game on RequestUpdate service calls, which the game then may or may …
> Add a 5ms tiemout to the DSP processing wait

- src/shader_recompiler/frontend/maxwell/translate/impl/integer_funnel_shift.cpp
Fixes cracks between mesh patches in Tears of the Kingdom, particularly in underground areas. (No cache clear required.)
|Before|After|
|-|-|
|![0100f2c0115b6000_2023-05-26_00-35-23-537](https://github.com/yuzu-emu/yuzu/assets/9658600/45036846-4bfa-4dd2-8557-735813fbd202)|![0100f2c0115b6000_2023-05-26_00-33-57-330](https://github.com/yuzu-emu/yuzu/assets/9658600/4e9556fc-21b1-4e4f-b6f4-85c4a38025f8)|
> shader_recompiler: fix copy-paste error

- src/video_core/texture_cache/image_base.cpp
- src/video_core/texture_cache/image_base.h
- src/video_core/texture_cache/texture_cache.h
- src/video_core/texture_cache/texture_cache_base.h
This is a follow up to #10249. This _should_ fix the throw aim and bow aim shadow flickering in Tears of the Kingdom, this time without regressing rendering in SMO.
> texture_cache: process aliases and overlaps in the correct order

- src/audio_core/sink/sink_stream.cpp
This was a change sugegsted by ByLaws to stop some audio desync when the emu core gets frozen, e.g by IO on load screens. He thinks it can help with audio crackling by limiting the queue size. (copium)
> Wait indefinitely when audio buffer queue is too big

- src/video_core/buffer_cache/buffer_cache.cpp
- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/buffer_cache/buffer_cache_base.h
- src/video_core/renderer_opengl/gl_buffer_cache.cpp
Buffer bindings need to be tracked per-channel, and not globally in the buffer cache. 
Dokapon Kingdom Connect boots with a sequence like:
Bind 3d channel 0, bind addr 0x1000 as uniform for vertex shader with cb index 2, draw.
Bind 3d channel 1, bind addr 0x2000 as uniform for vertex shader with cb index 2, draw.
Bind 3d channel 0, send inline const buffer data for addr 0x1000, bind cb index 2 for vertex shader, draw.
Currently, because buffers are tracked globally, the last draw ignores the channel swap, and addr 0x2000 remains the active vertex stage index 2 uniform buffer, and the inline data that was sent inbetween is ignored, leading to bad const buffer values in the uniform, since it's the wrong buffer.
By moving buffer bindings to be channel-specific, addr 0x1000 becomes the active …
> Move buffer bindings to per-channel state

- src/yuzu/game_list.cpp
- src/yuzu/game_list.h
- src/yuzu/main.cpp
- src/yuzu/main.h
Tears of the Kingdom stores weapon icons as PNG files in cache storage. #10418 fixed the issue with generating fused weapon icons (when async shaders are disabled -- it will never work when they are enabled), but this does not do anything to address icons already persisted in cache storage. This adds a button to quickly clear it out so that the icons can be rendered again properly.
Note that because current vfs is a meme the cache storage dir used is always for program id 0 when games open it.
> qt: add menu item to remove cache storage

- src/core/core.cpp
- src/core/file_sys/romfs.cpp
- src/core/file_sys/vfs_concat.cpp
- src/core/file_sys/vfs_concat.h
This fixes the in-game loading times of Animal Crossing: New Horizons, Fire Emblem Engage, Tears of the Kingdom, etc. when using romfs mods.
> vfs_concat: fix time complexity of read

- externals/CMakeLists.txt
- externals/glad/CMakeLists.txt
- externals/libusb/CMakeLists.txt
- externals/opus/CMakeLists.txt
- Implicitly create static library by default for all externals `add_library()`.
- Implicitly skip install rules for all `add_subdirectory()` in the externals directory.
- ~~Remove header files from target sources.~~
- Disable building useless tools/examples in some projects.
> cmake: apply defaults to all externals

- CMakeLists.txt
- externals/ffmpeg/CMakeLists.txt
- src/video_core/host1x/codecs/codec.cpp
- src/video_core/host1x/codecs/codec.h
This is a follow up to #10254 to improve the playback of cut scenes in Layton's Mystery Journey. It uses ffmpeg's yadif filter for deinterlacing.
This means that we now must enable libavfilter in ffmpeg (and update windows binaries).
Alternatively, we may hack some basic deinterlacing ourselves, similarly to how it was done in ryujinx: https://github.com/Ryujinx/Ryujinx/pull/3225, but that seems quite a bit more complicated for what essentially amounts to one and a half games that'd use this feature to my knowledge.
If anyone could tests STAR WARS Episode I Racer before and after this PR, it'd be the most welcome.
> Add support for deinterlaced video playback

- .ci/scripts/windows/upload.ps1
- CMakeModules/CopyYuzuFFmpegDeps.cmake
- CMakeModules/CopyYuzuQt5Deps.cmake
- CMakeModules/CopyYuzuSDLDeps.cmake
- src/yuzu/CMakeLists.txt
Use `$<TARGET_FILE_DIR:...>` where appropriate instead of trying to guess where the binary will end up.
Fixed the issue I had where the dlls weren't copied to the appropriate place on my setup (VS 2022, CMake project).
One thing is that `string(REPLACE "/" "\\\\" SOURCE_DIR ${SOURCE_DIR})` lines in `WindowsCopyFiles.cmake` are now sort of useless since generator expression is expanded after such replacement could be done, on the other hand it seems like `robocopy` doesn't care ;P
> Use TARGET_FILE_DIR generator expression

- src/video_core/renderer_opengl/gl_texture_cache.cpp
gl_format was incorrectly being overwritten when compression was disabled
> gl_texture_cache: Fix ASTC CPU decoding with compression disabled

- externals/microprofile/microprofile.h
Skips iterations where `MP_ASSERT(nStackPos < MICROPROFILE_STACK_MAX)` is triggered, which would cause a crash when microprofile is enabled.
> microprofile: Avoid crashing due to OOB stackPos

- CMakeLists.txt
- src/common/bit_field.h
- vcpkg.json
Implicit conversions are now disallowed in fmt 10. Use format_as to convert to the underlying type.
> externals: Update to fmt 10 and add format_as formatter for BitField

- src/video_core/buffer_cache/buffer_cache.h
Avoids a crash on any apps not using graphics, usually homebrew console apps.
> Skip BufferCache tickframe with no channel state set

- src/yuzu/main.cpp
Qt solution to Qt problem. Turns out the game list is still active in background so you can boot a game while a game is running. The easiest way to go with this is to simply disable the game list so no actions can be triggered. This prevents softlocks at booting games
> yuzu: Disable game list while game is running

- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/config.h
- src/yuzu/main.cpp
Satisfies feature request #10337
Only added context menus for filter and anti-aliasing, other options either only have 2 values or undesirable options ("Extreme" accuracy).
Only thing to note is the `repaint()` at the end of each context menu is to remove the hover CSS on the button which would otherwise be stuck with a border. Looking around this appears to be a quirk of Qt context menus and other solutions I tried were unsuccessful.
> add context menu for status bar settings

- src/core/hle/service/nvdrv/core/syncpoint_manager.cpp
This is a bug copied over from Skyline. I doubt this affects any games, so this is very inconsequential, but a bug I spotted nonetheless.
> Fix incorrect syncpt id bounds check and potential out of bounds lookup

- src/video_core/buffer_cache/buffer_cache.h
When expanding a stream buffer backwards, we set the begin to a big backwards address, but then immediately increment cpu_addr by 1 page, so it ends up that we potentially have 1 page at the start of the new buffer range that is not added to overlap_ids.
The previous cpu_addr assignment shouldn't be necessary either, since the buffers are merging intervals, there cannot be another buffer between half way inside a buffer, and the beginning of that same buffer, so moving cpu_addr backwards just means checking the exact same buffer's pages again up until the point we were previously at.
> Fix buffer overlap checking skipping a page for stream score right expand

- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/GpuDriverHelper.kt
Just return and the app will show an invalid driver error to the user.
> android: Don't crash the app when selecting a zip that causes a SecurityException

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/ImportExportSavesFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/MessageDialogFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
- src/android/app/src/main/res/values/strings.xml
Change "Input Overlay" to "Overlay Options"
Adjust wording around the import/export saves dialog.
Add new warnings for users that fail to install keys due to issues with different directories.
> android: Adjust various warnings

- src/core/CMakeLists.txt
- src/core/file_sys/patch_manager.cpp
- src/core/file_sys/romfs.cpp
- src/core/file_sys/vfs_cached.cpp
- src/core/file_sys/vfs_cached.h
- src/core/file_sys/vfs_vector.cpp
- src/core/file_sys/vfs_vector.h
#10183 fixed an algorithmic complexity issue with loading romfs mods, but did not fix how unbelievably slow it is to make filesystem calls on Windows, and I was not testing on Windows at the time. This wraps the romfs mods directory in a memory cache, which pretty much decisively fixes romfs load time for games with tons of files, including Animal Crossing: New Horizons, Fire Emblem Engage, and Tears of the Kingdom.
> vfs: add vfs_cached for romfs build

- src/core/hle/service/filesystem/fsp_srv.cpp
Caching the built romfs seems to have been intended before but was missed due to a programming oversight. Further decreases load times with romfs mods.
> fsp-srv: avoid patching romfs multiple times

- src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/Settings.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/utils/SettingsFile.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
Before we couldn't rely on these settings for UI functionality. Now these settings are guaranteed to be available as the correct value anywhere in the app.
> android: Load settings at the start of each activity

- src/audio_core/renderer/adsp/audio_renderer.cpp
- src/audio_core/renderer/adsp/audio_renderer.h
- src/audio_core/sink/sink_stream.cpp
- src/audio_core/sink/sink_stream.h
This seemed to happen rarely on my main machine, but was pretty consistently deadlocking for me on Windows.
> audio_renderer: resolve adsp thread deadlock shutdown

- .github/workflows/build.yml
The configuration requires 17, but the default in Actions is an older version
> android: Fix ci builds with Java 17

- src/android/gradle.properties
org.gradle.jvmargs=
-Xms512m  <- Set the IDE to start with 512m allocated. 
-XX:MaxMetaspaceSize=512m <- Convert the MaxPermSize to new option 
-XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 (previous options)
android.useAndroidX=true
kotlin.code.style=official
kotlin.parallel.tasks.in.project=true <- parallel compilation tasks in the same project
android.defaults.buildfeatures.buildconfig=true
> android: Improve Gradle build configuration

- src/core/file_sys/control_metadata.cpp
- src/core/file_sys/control_metadata.h
- src/core/file_sys/patch_manager.cpp
- src/yuzu/main.cpp
Some games provide different icons for different languages but the old behavior has been to pick the first available icon in an arbitrary order. These commits fix that.
I have not changed how the icons are selected by [core/loader/deconstructed_rom_directory.cpp](https://github.com/yuzu-emu/yuzu/blob/58c54aecb6a80e8f8efeae9ae84871fd543dee53/src/core/loader/deconstructed_rom_directory.cpp#L32) but that doesn't affect the UI.
(Re-uses a bit of code from [core/hle/service/ns/ns.cpp:410](https://github.com/yuzu-emu/yuzu/blob/58c54aecb6a80e8f8efeae9ae84871fd543dee53/src/core/hle/service/ns/ns.cpp#L410) by @SciresM)
> Localize game icons

- src/video_core/texture_cache/texture_cache.h
This PR improves performance, which I verified on some homebrew tests I made. 
But, I don't know which titles are likely to be affected by this change.
> `// No need to waste time on an image that's synced with guest`
This comment makes me think the idea for this check was to skip downloading images that haven't been modified on the GPU, but the early return here made it so that the slower unaccelerated path was taken instead, which still downloaded the image.
The logic is also flawed because it makes the **assumption** that the destination for the DMA copy is the same address as the CPU address for the image, which is "synced with guest" and thus needs no updating.
This assumption can't really be made.
> AccelerateDMA: Fix incorrect check in Buffer<->Texture copies

- src/video_core/vulkan_common/vulkan_device.h
For some reason nvidia implemented Vulkan 1.2 supported without support for VK_EXT_robustness2 in tegra X1/X2 .
Fix vulkan work in TX1/TX2  L4T drivers .
> Make VK_EXT_robustness2 optional

- CMakeLists.txt
- src/CMakeLists.txt
The latest version of MSVC STL brings C++23 standard library modules, which conflict with precompiled headers. Disabling with /experimental:module- has no effect, so force C++20 in the meantime while we wait for module support in other compilers.
> CMakeLists: Force C++20 on MSVC due to conflicts with C++23 modules

- src/common/fs/fs_paths.h
- src/common/fs/path_util.cpp
- src/common/fs/path_util.h
- src/core/hle/service/nfc/common/device.cpp
- src/core/hle/service/nfc/common/device.h
- src/core/hle/service/nfc/common/device_manager.cpp
- src/core/hle/service/nfc/nfc_interface.cpp
- src/core/hle/service/nfc/nfc_result.h
- src/core/hle/service/nfp/nfp_interface.cpp
- src/core/hle/service/nfp/nfp_result.h
Since writing to amiibos with Joy-Con is now supported, all we need is backup support for amiibo data, just like on the Switch. This pull request will create a backup every time a valid amiibo is loaded or saved. The game will be able to detect the backup and restore it accordingly, fixing any corrupted amiibo tags.
As amiibo data is stored, you can use Yuzu to dump your amiibo bin from a Joy-Con or Pro Controller. You can find all the amiibo files in `%appdata%/amiibo/backup`.
> service: nfc: Add backup support

- src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/SearchFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/Game.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/GamesViewModel.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/GameHelper.kt
- src/android/app/src/main/jni/native.cpp
- src/core/loader/nro.cpp
- src/core/loader/nro.h
Instead of just using the .nro extension to guess whether a game is homebrew or not, check for "HOMEBREW" in the header of the file.
> android: Add proper homebrew check

- .codespellrc
https://github.com/yuzu-emu/yuzu/pull/10691 broke your verification because codespell thinks OptIn is a typo for option. That's why it was marked as failed, despite being perfectly fine.
> Add a codespell exception for kotlin OptIn

- src/video_core/renderer_vulkan/vk_blit_screen.cpp
Fixes annoying color banding when using FXAA
|Before|After|
|-|-|
|![01007ef00011e000_2023-06-08_11-32-27-066](https://github.com/yuzu-emu/yuzu/assets/9658600/1944db0c-15cc-45ad-a595-811044b3e3cb)|![01007ef00011e000_2023-06-08_11-29-47-002](https://github.com/yuzu-emu/yuzu/assets/9658600/e67da3c7-5134-4c3e-9bf4-42f7d5d5fb84)|
> vk_blit_screen: use higher bit depth for fxaa

- src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/FileUtil.kt
- src/android/app/src/main/res/values/strings.xml
Fixes an issue where we try to resolve file extension from URIs. Sometimes the URI will not contain the file name at all and instead a string of numbers. Here we query the content resolver and guarantee that we get a file name every time.
> android: Use ContentResolver to get file extension

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/buffer_cache/buffer_cache_base.h
- src/video_core/renderer_opengl/gl_buffer_cache.cpp
- src/video_core/renderer_opengl/gl_buffer_cache.h
- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
- src/video_core/renderer_vulkan/vk_buffer_cache.h
Currently we bind every vertex and transform feedback buffer individually, which can lead to over a thousand extra API calls per frame. This PR combines them into a temp data structure and binds them at once instead. On buffer deletion, index and vertex buffers are also made conditional and specific, rather than invalidating the index and all vertex buffers every time any buffer is deleted.
> Combine vertex/transform feedback buffer binding into a single call

- src/yuzu/main.cpp
This embarrassingly simple change more than triples the installation speed of updates.
> qt: use larger buffer for update install

- src/shader_recompiler/CMakeLists.txt
- src/shader_recompiler/frontend/maxwell/translate_program.cpp
- src/shader_recompiler/host_translate_info.h
- src/shader_recompiler/ir_opt/lower_fp64_to_fp32.cpp
- src/shader_recompiler/ir_opt/passes.h
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/vulkan_common/vulkan_device.h
Needed for newer Intel GPUs as they no longer support double operations in shaders.
```cpp
constexpr s32 F64ToF32Exp = + 1023 - 127;
constexpr s32 F32ToF64Exp = + 127 - 1023;
f32 PackedF64ToF32(u32 lo, u32 hi) {
u32 sign = BitfieldExtract(hi, 31, 1);
u32 exp = BitfieldExtract(hi, 20, 11);
u32 mantissa_hi = BitfieldExtract(hi, 0, 20);
u32 mantissa_lo = BitfieldExtract(lo, 29, 3);
u32 mantissa = (mantissa_hi << 3) | mantissa_lo;
u32 exp_if_subnorm = exp == 0    ? 0   : (exp + F64ToF32Exp);
u32 exp_if_infnan  = exp == 2047 ? 255 : exp_if_subnorm;
return bit_cast<f32>((sign << 31) | (exp_if_infnan << 23) | mantissa);
}
void F32ToPackedF64(u32* out_lo, u32* out_hi, f32 raw) {
u32 value = std::bit_cast<u32>(raw);
u32 sign = BitfieldExtract(value, 31, 1);
u32 exp = BitfieldExtract(value, 23, 8); …
```
> shader_recompiler: translate f64 to f32 when unsupported on host

- src/shader_recompiler/CMakeLists.txt
- src/shader_recompiler/frontend/maxwell/translate_program.cpp
- src/shader_recompiler/host_translate_info.h
- src/shader_recompiler/ir_opt/conditional_barrier_pass.cpp
- src/shader_recompiler/ir_opt/passes.h
- src/video_core/renderer_opengl/gl_device.cpp
- src/video_core/renderer_opengl/gl_device.h
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
The PTX ISA documentation for barrier advises:
> As threads exit, barriers waiting on all threads are checked to see if the exiting threads are the only threads that have not yet made it to a barrier{.cta} for all threads in the CTA. If the exiting threads are holding up the barrier, the barrier is released. 
However, SPIR-V says of `OpControlBarrier`:
> When Execution is Workgroup or larger, behavior is undefined unless all invocations within Execution execute the same dynamic instance of this instruction.
Which precludes a simple implementation of the barrier instruction. It's not clear that we can accurately implement the semantics of how barriers work for Nvidia hardware on GPUs which don't check exiting threads, so just remove it in this case.
This fixes the primary source of device …
> shader_recompiler: remove barriers in conditional control flow when device lacks support

- src/android/app/build.gradle.kts
Instead of fiddling with detecting gradle build types or environment variables, you can set an `autoVersioned` property to "true" in your `local.properties` file and get the appropriate `autoVersion` versionCode. Otherwise the versionCode will be 1 just like before.
> android: Use autoVersion when gradle property is set

- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/IntSetting.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsFragmentPresenter.kt
- src/android/app/src/main/jni/config.cpp
- src/android/app/src/main/jni/default_ini.h
- src/android/app/src/main/res/values-de/strings.xml
- src/android/app/src/main/res/values-es/strings.xml
- src/android/app/src/main/res/values-fr/strings.xml
- src/android/app/src/main/res/values-it/strings.xml
- src/android/app/src/main/res/values-ja/strings.xml
- src/android/app/src/main/res/values-ko/strings.xml
- src/android/app/src/main/res/values-nb/strings.xml
- src/android/app/src/main/res/values-pl/strings.xml
- src/android/app/src/main/res/values-pt-rBR/strings.xml
- src/android/app/src/main/res/values-pt-rPT/strings.xml
- src/android/app/src/main/res/values-ru/strings.xml
- src/android/app/src/main/res/values-uk/strings.xml
- src/android/app/src/main/res/values-zh-rCN/strings.xml
- src/android/app/src/main/res/values-zh-rTW/strings.xml
- src/android/app/src/main/res/values/strings.xml
* Disables force_max_clocks by default due to thermal throttling on most devices.
* Adds use_reactive_flushing as a setting and disables it by default to improve performance.
* Removes deleted translations that were causing a build break.
> android: Update settings, remove unused translations

- src/android/app/src/main/AndroidManifest.xml
- src/android/app/src/main/res/xml/locales_config.xml
This is required to make per-app language swithcing possible on Android 13.
> android: Declare languages in locales_config.xml

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/buffer_cache/buffer_cache_base.h
- src/video_core/renderer_opengl/gl_buffer_cache.cpp
- src/video_core/renderer_opengl/gl_buffer_cache.h
- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
- src/video_core/renderer_vulkan/vk_buffer_cache.h
Avoid reinterpret-casting from void pointer since the type is already known at compile time.
> buffer_cache_base: Specify buffer type in HostBindings

- vcpkg.json
`Forgot to update the manifest to reflect the submodule in the previous commit.`
My bad... I caused the failures not updating this.
> externals: Fix update vcpkg to 2023.06.14

- src/core/file_sys/vfs_real.cpp
- src/core/file_sys/vfs_real.h
This allows making romfs mods with as many files as you want. I tested it with 300k+ files and it worked.
Closes #10722 , probably others opened about this issue
Fixes https://github.com/yuzu-emu/yuzu/issues/5918.
Fixes https://github.com/yuzu-emu/yuzu/issues/7308.
Fixes https://github.com/yuzu-emu/yuzu/issues/4870.
>  vfs_real: add file LRU cache for open file limits 

- src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/DocumentsTree.kt
- src/common/fs/fs.cpp
- src/common/fs/fs_android.h
Loading ROMs via SAF was regressed by #10729. This is a band aid until we have a better Android backend (probably as part of G).
> android: fs: Fix Exists / IsFile for SAF.

- src/input_common/drivers/virtual_amiibo.cpp
- src/input_common/drivers/virtual_amiibo.h
Foomiibo is a plain amiibo that has been autogenerated. The only difference is that they contain an extra header at the end compared to a regular amiibo dump. Add this file size to supported amiibo formats.
> input_common: Add foomiibo support

- externals/CMakeLists.txt
TLDR: Disabling `CPUinfo` triggers a very nasty SDL audio subsystem bug, which **utterly** breaks SDL's JACK output on Linux, so no audio when one wanted to do `SDL_AUDIODRIVER=jack bin/yuzu`. This is a workaround for that.
Below is the offending SDL code in question, if anyone is curious. Without `CPUinfo`, it thinks there is no SIMD support (so it doesn't use SIMD granule type conversion), while also thinking there is no lack of SIMD support, because for example on x86 `SDL_SSE2_INTRINSICS` is still defined (so `NEED_SCALAR_CONVERTER_FALLBACKS` isn't set, so it doesn't use the fallback granule type conversion functions either), thus all the `SDL_Convert_x_to_y` functions are null and there is no way for other parts of SDL's audio subsystem to work properly: …
> Re-enable SDL's `CPUinfo` subsystem

- src/android/app/src/main/AndroidManifest.xml
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
The "locked" aspect ratio is based on landscape, so allowing the activity to start in portrait means landscape will use the width and height of portrait to dictate the landscape aspect ratio. The end result is an emulation surface that is short and wide. By launching in landscape, this sets the proper aspect ratio at the cost of a quick transition.
> android: Fix aspect ratio when rotating screen

- src/core/hle/service/nfc/common/amiibo_crypto.cpp
- src/core/hle/service/nfc/common/amiibo_crypto.h
- src/core/hle/service/nfc/common/device.cpp
- src/core/hle/service/nfc/common/device.h
- src/core/hle/service/nfc/common/device_manager.cpp
- src/core/hle/service/nfc/mifare_result.h
- src/core/hle/service/nfc/nfc_interface.cpp
- src/core/hle/service/nfc/nfc_result.h
- src/core/hle/service/nfc/nfc_types.h
- src/core/hle/service/nfp/nfp_types.h
Adds proper checks to ReadMifare and fixes GetTagInfo output to match switch. Might fix the skylander bug where each time the file was loaded it was detected as a different toy.
> service: nfc: Accuracy fixes

- src/android/app/build.gradle.kts
Bumping ktlint to 0.47.1 fixes an issue where it tries to check nonexistent files and removing the `import-ordering` check fixes conflicts with android studio formatting.
> android: Ktlint fixes

- src/video_core/renderer_opengl/gl_shader_context.h
- src/video_core/renderer_vulkan/vk_pipeline_cache.h
IR::Block is a 4192-byte structure. The default number of pooled blocks to allocate is 8192, which leads to 34MB of IR::Blocks allocated twice per thread. This seems excessive.
> video_core: preallocate fewer IR blocks

- src/core/hle/kernel/k_thread.cpp
- src/core/hle/kernel/k_thread.h
std::atomic\<bool\> is broken on MinGW and causes deadlocks there. Use a normal cond var in its stead.
Fixes #10232
> k_thread: Use a mutex and cond_var to sync bool

- src/video_core/renderer_vulkan/vk_master_semaphore.cpp
Fixes build on Apple Clang (please update to llvm 16 soon, thanks)
> renderer_vulkan: add missing include

- src/yuzu/CMakeLists.txt
- src/yuzu/configuration/configure_dialog.cpp
- src/yuzu/configuration/configure_dialog.h
- src/yuzu/configuration/configure_graphics.cpp
- src/yuzu/configuration/configure_graphics.h
- src/yuzu/configuration/configure_per_game.cpp
- src/yuzu/configuration/configure_per_game.h
- src/yuzu/main.cpp
- src/yuzu/main.h
- src/yuzu/vk_device_info.cpp
- src/yuzu/vk_device_info.h
Loading it when the configuration opens now incurs a noticeable delay (as a result of #10125). We also don't need to rediscover the same data repeatedly each time the configuration opens.
Moves Vulkan device info discovery to yuzu's startup as opposed to the configure_graphics constructor.
> yuzu-qt: Load Vulkan device info at startup

- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
- src/yuzu/configuration/configure_graphics.cpp
- src/yuzu/vk_device_info.cpp
- src/yuzu/vk_device_info.h
Followup to #10181
Intel finally fixed the compute issue, so we can disable it here where needed. Currently the only fixed driver is a beta version, so this just checks for affected drivers. As a side effect, this also re-enables compute on older unsupported Intel graphics devices where they never had the compute issue in the first place.
> vulkan_device: Restrict compute disable only to affected Intel drivers

- src/core/hle/service/time/time_zone_manager.cpp
This is a deviation from the reference time zone implementation. The actual code will set a pointer to the time zone name here, but for us we have a limited number of characters to work with, and the name of the time zone here could be larger than 8 characters. This causes an oob array access (#10817).
We can make the assumption that time zone names greater than five characters in length include a comma that denotes more data. Nintendo just truncates that data for the name, so we can do the same. And just to be doubly sure that we never break past the array length, directly compare against the length.
Closes #10817
> time_zone_manager: Stop on comma

- src/core/file_sys/vfs_concat.cpp
> vfs_concat: fix offset calculation when not aligned to file boundary

- src/common/settings.h
- src/video_core/texture_cache/texture_cache.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_graphics_advanced.cpp
- src/yuzu/configuration/configure_graphics_advanced.h
- src/yuzu/configuration/configure_graphics_advanced.ui
Allows undoing the effect of #10402.
Interacts with #10600 
Interacts with #10425
Games are not inserting their own barriers when rendering here, and seems to depend rasterization order attachment access. However, since we don't have that capability on desktop, we need a way to allow access to just-rasterized fragments, which we can do by inserting a barrier.
For some reason, inserting these pipeline barriers makes certain Nvidia GPUs completely break and device loss without any clear reason as to why. I was never able to reproduce this myself, but seeing as these GPUs also do not seem to need the barriers most of the time, I'm fine with making it optional.
> video_core: optionally skip barriers on feedback loops

- src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/MemoryUtil.kt
- src/android/app/src/main/res/values/strings.xml
Separated this from the multi-install PR by switching to a Toast. In all honesty, most users with insufficient RAM should at least have some idea what they are getting into. No need to pause the entire load just to remind them.
Completes the request at https://github.com/yuzu-emu/yuzu/issues/10789
> android: Add a notice when RAM inadequate

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/InstallDialogFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/LongMessageDialogFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
- src/android/app/src/main/res/values/strings.xml
Very simple way of replicating the desktop installation process for multiple files.
Outputs a success if all installs work or a fail if at least one fails. Lists the number of files that succeed, overwrite, or fail and any failure causes.
Resolves the request in https://github.com/yuzu-emu/yuzu/issues/10757
> android: Add support for multiple installs

- src/common/input.h
- src/core/hid/emulated_controller.cpp
- src/core/hid/emulated_controller.h
- src/core/hid/input_converter.cpp
- src/core/hle/service/am/applets/applet_cabinet.cpp
- src/core/hle/service/nfc/common/device.cpp
- src/core/hle/service/nfc/common/device.h
- src/core/hle/service/nfc/common/device_manager.cpp
- src/core/hle/service/nfc/common/device_manager.h
- src/core/hle/service/nfc/mifare_types.h
- src/core/hle/service/nfc/nfc_interface.cpp
- src/input_common/drivers/joycon.cpp
- src/input_common/drivers/joycon.h
- src/input_common/drivers/virtual_amiibo.cpp
- src/input_common/drivers/virtual_amiibo.h
- src/input_common/helpers/joycon_driver.cpp
- src/input_common/helpers/joycon_driver.h
- src/input_common/helpers/joycon_protocol/joycon_types.h
- src/input_common/helpers/joycon_protocol/nfc.cpp
- src/input_common/helpers/joycon_protocol/nfc.h
- src/input_common/helpers/joycon_protocol/poller.cpp
- src/input_common/helpers/joycon_protocol/poller.h
- src/input_common/input_engine.h
- src/input_common/input_poller.cpp
- src/yuzu/main.cpp
Implements native Skylander toys with Joy-Cons or a Pro Controller. You should be able to load them just as you would on the Switch. No additional setup is required; simply connecting and mapping the controller is sufficient.
This pull request removes certain hacks. Consequently, a significant portion of the tag detection process had to be rewritten to accommodate different types of tag support. As Joy-Cons handle all the encryption, there is no need for any keys to read or write data, allowing them to be used directly.
> input_common: Implement native mifare/skylander support for joycons/pro controller

- src/android/app/src/main/jni/native.cpp
Android Studio marked these parameters as errors because it is an instance, not a class, that is being passed from Java.
After the pip mute fixes were pushed, Android Studio was able to index the file a little better.
> android: (native) Parameter types from Android Studio

- src/input_common/drivers/sdl_driver.cpp
With new SDL version joycons stopped working correctly. Address this by updating the flags. Battery level is also a proper event now. So update it like any other input as well.
There's one bug remaining. Player leds are always off on switch controllers. This needs to be fixed upstream so I will address that issue in another PR.
> input_common: Make use of new SDL features

- src/core/hid/emulated_controller.cpp
- src/input_common/helpers/joycon_driver.cpp
- src/input_common/helpers/joycon_driver.h
- src/input_common/helpers/joycon_protocol/common_protocol.cpp
Some 3rd party controllers don't accept commands. I have reduced the number of attempts to obtain valid data and disabled most commands to minimize the stutter caused by attempting to configure the controller.
SetPollingMode also forwards the failure so that EmulatedController can properly restore the previous state. This fixes missing input when the controller fails to use NFC.
If the game stops polling for amiibos while an amiibo was in range, the amiibo is lost but never signaled.
Finally, if your controller supports NFC but you try to use a bin dump, it will now detect it properly instead of displaying an error."
Fixes #10877
> input_common: Improve nfc state handling and 3rd party support

- src/yuzu/configuration/configure_ringcon.ui
It is not obvious how the left Joy-Con should be set up.
Clarify message and mention that it should be left physical, but dual emulated according to [this comment](https://github.com/yuzu-emu/yuzu/issues/8489#issuecomment-1546490439).
Without this clarification one might think to set up left controller as dual both physical and emulated, and this won't work. In fact, this confusion has already happened as we can see from comment history on the same issue #8489.
> Clarify Ring-Con configuration message in UI

- src/common/fs/fs.cpp
Games on android will fail to load game data and metadata without this change.
I'm not familiar with the vfs here but switching back to this way of getting size works. I'd definitely want @liamwhite to check this out to make sure I didn't break anything else.
> android: Fix size check for content uris

- src/shader_recompiler/backend/glasm/emit_glasm.cpp
- src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
- src/shader_recompiler/shader_info.h
- src/video_core/host_shaders/CMakeLists.txt
- src/video_core/host_shaders/opengl_lmem_warmup.comp
- src/video_core/renderer_opengl/gl_compute_pipeline.cpp
- src/video_core/renderer_opengl/gl_compute_pipeline.h
- src/video_core/renderer_opengl/gl_device.cpp
- src/video_core/renderer_opengl/gl_device.h
- src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
- src/video_core/renderer_opengl/gl_graphics_pipeline.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_shader_manager.cpp
- src/video_core/renderer_opengl/gl_shader_manager.h
Here's a fun one.
Nvidia's OpenGL drivers see a significant performance uplift in shaders using local memory if the previous shader that was executed uses more local memory (sort of..)
To take advantage of this discovery, this change introduces a dummy shader that allocates the maximum allowed local memory, but returns immediately without executing. This tricks the driver into boosting the performance of the later executing shaders which use local memory.
Here's a local memory torture test homebrew used to test this: 
[textured_cube_compute.zip](https://github.com/yuzu-emu/yuzu/files/11861207/textured_cube_compute.zip)
In this homebrew, my performance went from 7 to 8 FPS, up to 40 to 42 FPS, matching Vulkan's performance.
>  OpenGL: Add Local Memory warmup shader for Nvidia

- src/input_common/drivers/sdl_driver.cpp
- src/yuzu/main.cpp
- src/yuzu/main.h
Closes #10674.
SDL has internally fixed shenanigans related to wakelocking through DBus from inside sandboxes from around August 2022, so we can now remove the workaround we used since 2021.
> Only use SDL wakelock on Linux

- src/common/settings.h
- src/input_common/drivers/mouse.cpp
- src/input_common/drivers/mouse.h
- src/yuzu/CMakeLists.txt
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/config.h
- src/yuzu/configuration/configure_input_advanced.cpp
- src/yuzu/configuration/configure_input_advanced.ui
- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/configuration/configure_input_player.ui
- src/yuzu/configuration/configure_mouse_panning.cpp
- src/yuzu/configuration/configure_mouse_panning.h
- src/yuzu/configuration/configure_mouse_panning.ui
- src/yuzu_cmd/default_ini.h
I wanted to give a try at fixing the issues raised by #10420 (whose author is away for some months and can't update the PR), and I ended up with a somewhat more conservative solution.
Attempts to fix the following issues:
1. Sensitivity setting affecting the stick's range, making either the max value unreachable or min value too high if not set to 50%.
Fixed by applying the sensitivity on the mouse input alone, before any clamping.
2. Very small movements being impossible to perform.
Fixed by removing the line that sets the mouse event's length to a minimum of 3. Testing shows that it is rarely higher than 1 even with a low mouse polling rate, so setting it to 3 meant some details were lost.
3. Stick "resistance" feeling inconsistent.
This is more subjective. The buffer decay is applied …
> input_common: Redesign mouse panning

- src/video_core/engines/maxwell_dma.cpp
Some OpenGL games use blits and then DMA to do the readback. Currently with unsafe reads we're not synchronising the memory and ending with undefined memory in the read. Needs a bit of testing to detemine any perf hits from this, but hopefully won't be noticable.
Closes #10654.
> Use safe reads in DMA engine

- src/common/settings.cpp
Windows lets you select time zones that fail in their own C++ implementation library. Evidently from the stack trace, we get a runtime error to work with, so catch it and use the fallback.
> settings: Catch runtime_error, fallback time zone

- .gitmodules
- Use tab everywhere because `git submodule add ...` always inserts tab.
- Some usernames in repo url have changed.
- Add the `.git` suffix in all url.
> gitmodules: normalize indentation and url

- src/android/app/build.gradle.kts
- src/android/app/src/main/AndroidManifest.xml
Specifies the permissions needed for the changes to foreground services in Android 14.
> android: Android 14 support

- src/common/input.h
- src/input_common/drivers/joycon.cpp
- src/input_common/drivers/joycon.h
- src/input_common/helpers/joycon_driver.cpp
- src/input_common/helpers/joycon_driver.h
- src/input_common/helpers/joycon_protocol/calibration.cpp
- src/input_common/helpers/joycon_protocol/calibration.h
- src/input_common/helpers/joycon_protocol/common_protocol.cpp
- src/input_common/helpers/joycon_protocol/common_protocol.h
- src/input_common/helpers/joycon_protocol/generic_functions.cpp
- src/input_common/helpers/joycon_protocol/generic_functions.h
- src/input_common/helpers/joycon_protocol/irs.cpp
- src/input_common/helpers/joycon_protocol/irs.h
- src/input_common/helpers/joycon_protocol/joycon_types.h
- src/input_common/helpers/joycon_protocol/nfc.cpp
- src/input_common/helpers/joycon_protocol/nfc.h
- src/input_common/helpers/joycon_protocol/ringcon.cpp
- src/input_common/helpers/joycon_protocol/ringcon.h
- src/input_common/helpers/joycon_protocol/rumble.cpp
- src/input_common/helpers/joycon_protocol/rumble.h
- src/yuzu/configuration/configure_ringcon.cpp
Turns out the errors reported by the driver where mismatched. Fixed this by removing the enum. 
When scanning for the ring it's possible to get no response. This was being treated as an error. This fixes the ring detection by allowing timeout errors and letting the code try again. I also added a description to DriverResult::InvalidHandle
> input_common: Remove duplicated enum and fix ring detection

- src/common/telemetry.cpp
- src/common/x64/cpu_detect.cpp
- src/common/x64/cpu_detect.h
- src/common/x64/cpu_wait.cpp
It turns out that AMD had the equivalent of Intel's waitpkg instructions since 2015, starting with the AMD Carrizo CPUs.
In light of this, we are using these instructions to emulate the behavior of the TPAUSE instruction in #9982 to bring in significant power savings for AMD CPUs, which should benefit handhelds such as the Steam Deck (running Windows), and the recently released ROG Ally and other power/thermally limited systems.
Thanks to @goldenx86 and @gidoly for testing this,
and @goldenx86 providing the following numbers on his Ryzen 5 5600X:
- Master: 69-71W
- This PR: 61-63W
- Master: 11-15 FPS
- This PR: 15-18 FPS
> x64: Make use of monitorx instructions for power efficient sleeps (AMD)

- src/android/gradle.properties
> Android Gradle plugin 8.0.2 is designed for API 33, but a newer plugin hasn't been released yet. The warning message is rather extravagant, but also suggests adding this property if you are aware of the risks.
```
You are strongly encouraged to update your project to use a newer
Android Gradle plugin that has been tested with compileSdk = 34.
If you are already using the latest version of the Android Gradle plugin,
you may need to wait until a newer version with support for compileSdk = 34 is available.
To suppress this warning, add/update
android.suppressUnsupportedCompileSdk=34
to this project's gradle.properties.
```
Note: This property should be removed when the Android Gradle plugin is updated.
> android: Suppress a known incompatibility

- src/video_core/texture_cache/texture_cache.h
This fixes the crash in Pikmin 4 Demo.
It will now use the LLE slow path. Unless a game really requires the acceleration, I don't see it necessary to accelerate.
> AccelerateDMA: Don't accelerate 3D texture DMA operations

- src/video_core/texture_cache/texture_cache.h
This fixes a regression with NVN virtual images not being correctly remapped when sparse memory changes to mapped.
It should fix regressions in UE4 games like bravely default, SMT V and Pikmin 4 demo.
> Texture cache: Fix YFC regression due to code testing

- src/common/settings.h
- src/input_common/drivers/mouse.cpp
- src/input_common/drivers/mouse.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_input_player.ui
- src/yuzu/configuration/configure_mouse_panning.cpp
- src/yuzu/configuration/configure_mouse_panning.ui
Minor teaks to mouse input calibration. Removes all magic numbers from the code. Allows to return to center when using a deadzone. Motion input is now in the correct sensitivity.
> input_common: Tune mouse controls

- src/audio_core/sink/sink_stream.cpp
- src/audio_core/sink/sink_stream.h
Also, remove the use of ScratchBuffer when upmixing, as other channels may not be initialized with zeroed out data.
Note: This may resolve several unexplainable crashes and memory corruption unrelated to audio.
Fixes #10897
Fixes #10900
Fixes #10960
Fixes #10965
> sink_stream: Resolve heap buffer corruption due to out of bounds write

- src/video_core/vulkan_common/vulkan_instance.cpp
- src/video_core/vulkan_common/vulkan_surface.cpp
- src/video_core/vulkan_common/vulkan_wrapper.h
- src/yuzu/qt_common.cpp
- src/yuzu/vk_device_info.cpp
* Migrates from the legacy VK_MVK_macos_surface to the recommended VK_EXT_metal_surface. We can fetch the required CAMetalLayer from the window using a simple objc_msgSend trick, same as in Citra.
* Fixes a preferences crash on macOS following the addition of present mode detection.
* The code for this passes in a GMainWindow for surface creation, which is not configured to have a Vulkan surface. On other platforms this seems to work, but on macOS this fails due to the window not having a CAMetalLayer.
* Instead, create a dummy invisible window with surface type VulkanSurface to perform this test.
> vulkan: Improvements to macOS surface creation

- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
As far as I can tell, there is no reason to OR this bit in separately.
> Minor cleanup in BufferCacheRuntime::ReserveNullBuffer

- src/core/core.cpp
- src/core/core.h
- src/core/gpu_dirty_memory_manager.h
- src/core/memory.cpp
- src/core/memory.h
- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/buffer_cache/buffer_cache_base.h
- src/video_core/fence_manager.h
- src/video_core/gpu.cpp
- src/video_core/gpu.h
- src/video_core/gpu_thread.cpp
- src/video_core/rasterizer_interface.h
- src/video_core/renderer_null/null_rasterizer.cpp
- src/video_core/renderer_null/null_rasterizer.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.h
- src/video_core/shader_cache.cpp
- src/video_core/shader_cache.h
This PR adds a mechanism to store small CPU writes when a GPU page is being written by the GPU. It assumes coherency happens at a cache line level (64 bytes). If the page is not contested it will be fully invalidated.
This fixes:
* Pokemon Violet and scarlet Vertex explosions (keep it at High accuracy for god's sake).
* Rain/Snow in Zelda BotW and TotK.
* Weird particle movement in SMO.
* Particle corruption in Zelda TotK.
* Corrupting Thumbnail in Xenoblade DE.
* Eyebrow animation in Xenoblade 3.
EDIT: After reading the TRM, the coherency depends if the page bypasses the cache (CPU writes/reads directly to that page in RAM) or if it uses the CPU cache. We assume the second so the accuracy remains 64 bytes. In the future we may increase the accuracy for cases where the CPU writes directly …
> Memory Tracking: Add mechanism to register small writes when gpu page is contested by GPU

- src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/Settings.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/MemoryUtil.kt
- src/android/app/src/main/res/values/strings.xml
~~The API for accessing the total amount of system memory has not allowed apps to see memory hidden from the kernel until API 34 (Android 14). As a result the memory warning would appear inaccurate and inconsistent between devices. (Reports 7/8GBs on my Pixel 7 and 6/8GBs on @goldenx86 's S23)~~
~~If there is a way to get the full system memory amount on lower API levels (there has to be since apps like CPU-Z have been around for ages and I think you could do this via JNI), I'll just add it later on.~~
I reworked this PR so we don't have to worry as much about API level (and avoid JNI entirely).
> android: Rework MemoryUtil

- src/video_core/compatible_formats.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
- src/video_core/texture_cache/types.h
- src/video_core/texture_cache/util.cpp
- src/video_core/vulkan_common/vulkan_device.h
Attempts to limit the impact of setting the mutable flag for every image. Depth/stencil images no longer require the mutable flag as vulkan doesn't seem to support mutable views for these formats. If supported, the image format list extension is also used to limit the compatible formats. I've also removed the FormatBpp relaxed flag, cause I could not find a place where it was being set
> Add support for VK_KHR_image_format_list

- src/core/core_timing.cpp
- src/core/core_timing.h
- src/yuzu/main.cpp
- src/yuzu_cmd/yuzu.cpp
Other programs may change this value, but if thousands of syscalls in this loop is undesirable, then we can just set this once.
> core_timing: Remove GetCurrentTimerResolution in CoreTiming loop

- src/yuzu/main.cpp
Fixes #11003.
DBus expects UTF-8 no matter the locale: https://dbus.freedesktop.org/doc/dbus-specification.html#:~:text=The%20value%20of%20any%20string%2Dlike%20type%20is%20conceptually%200%20or%20more%20Unicode%20codepoints%20encoded%20in%20UTF%2D8%2C%20none%20of%20which%20may%20be%20U%2B0000
> Use `toUtf8()` for string passed to DBus

- .github/workflows/android-build.yml
- .github/workflows/android-merge.js
- .github/workflows/android-publish.yml
- .github/workflows/verify.yml
This pull request adds a new GitHub Actions which will merge pull requests with a specific label (currently `android-merge`) into yuzu-emu/yuzu-android (this repository does not exist, as of writing).
It will trigger every day at 00:37 UTC (to avoid the 0 o'clock rush) and make a release in the (proposed) yuzu-emu/yuzu-android repository.
A manual trigger is also provided in case a new release is needed urgently.
> CI: auto-publish Android releases

- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/Settings.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/overlay/InputOverlay.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/overlay/InputOverlayDrawableButton.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/overlay/InputOverlayDrawableJoystick.kt
- src/android/app/src/main/res/drawable/button_l3.xml
- src/android/app/src/main/res/drawable/button_l3_depressed.xml
- src/android/app/src/main/res/drawable/button_r3.xml
- src/android/app/src/main/res/drawable/button_r3_depressed.xml
- src/android/app/src/main/res/values/arrays.xml
- src/android/app/src/main/res/values/integers.xml
Now within the Input Overlay file, there is an `OVERLAY_VERSION` code that will determine when the overlay will be reset. This is intended for breaking changes like the ones we had with the additions of percentage based layouts or the addition of foldable/portrait layouts.
This also includes L3/R3 buttons with icons provided by @Schplee
> android: Input overlay updates

- src/video_core/vulkan_common/vulkan_device.cpp
Take 2 -- These are needed on S8Gen2, but not older.
> video_core: vulkan_device: Fix S8Gen2 dynamic state checks.

- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
- Fixes Turnip driver usage on certain handsets (e.g. ZTE Snapdragon 870 devices)
- Fixes version check for broken Qualcomm 7xx drivers.
> video_core: vulkan_device: Disable timeline semaphore on Turnip, fix qcom version check.

- src/video_core/texture_cache/texture_cache.h
It seems that pr https://github.com/yuzu-emu/yuzu/pull/10953 regressed Metroid Prime Remastered rendering.
This pr bring back code that removed by https://github.com/yuzu-emu/yuzu/pull/10953 pr. Reason why mentioned pr fixed smt v and other ue4 game rendering seems it enable the code that marked as comment rather than cause by code that this pr trying to bring back.
I have tested ue4 games and metroid prime to see if it regress any game but couldn't found one. since i am not dev this will need to get approve from other devs like @FernandoS27 .
before
after
reopen cuz it auto closed original pr while switch branch name and less commit for bonus
> Fix regression by unreal engine fix pr #11009

- src/android/app/src/main/AndroidManifest.xml
- src/core/hid/emulated_controller.cpp
- src/core/hid/emulated_controller.h
- src/core/hle/service/nfc/common/device.cpp
This is a bug due missing HID services. This ensures nfc mode is active when the nfc service is being used.
> service: nfc: Ensure controller is in the correct mode

- src/video_core/vulkan_common/vulkan_memory_allocator.cpp
Reported to improve stability on UE4 games.
> vulkan_common: use device local preferred for image memory

- src/input_common/drivers/mouse.cpp
Some users reported that mouse stops working about x time. I believe the cause is by an accidental division by zero. Avoid this from happening at all.
> input_common: Avoid potential division by zero

- src/common/settings.cpp
Even though it compiles and runs fine on the latest Windows versions, older LTSC builds will crash due to lacking support somewhere in the OS.
For now just disable it for MSVC until either Microsoft fixes this or we no longer support 1809 LTSC.
Needs testing by someone using an old build of Windows 10.
> settings: Disable C++20 time zone path on MSVC

- src/common/settings.cpp
This function throws a runtime error we can catch on old Windows 10
installs, so we can catch it here rather than disable this path for
everybody.
> settings: Catch runtime error from STL

- .ci/scripts/windows/docker.sh
This is unnecessary here: pefile is already installed on the container.
This step also causes issues in coming changes to the container.
> ci/mingw: Remove pefile installation step

- src/android/app/src/main/AndroidManifest.xml
While this can be convenient in some scenarios, this will be a big problem for users trying to sideload different APK versions. If they forget the last one they had installed, they could have problems installing a new copy.
> android: Don't prompt to save user data on uninstall

- src/input_common/drivers/sdl_driver.cpp
- src/input_common/drivers/sdl_driver.h
This allows to share the mappings between Nintendo and non-Nintendo controllers.
([Documentation of the hint, which is set to 1 by default](https://github.com/libsdl-org/SDL/blob/92b3c53c92971e685254fd89f89ce6bde8cea60e/include/SDL_hints.h#L512-L532))
Compiled locally to test. (On a Pro Controller and an Xbox controller)
(I have mainly done it because I have this hint set to 0 globally on my system via environment variable, and Yuzu's default mapping was assuming it was set to 1)
⚠ WARNING: Breaks the controller configuration for existing users who are using a Nintendo controller and are not using the direct driver.
> input_common: set `SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS` to 0

- src/audio_core/device/device_session.cpp
- src/audio_core/renderer/command/data_source/decode.cpp
- src/audio_core/renderer/command/effect/aux_.cpp
- src/common/page_table.cpp
- src/common/page_table.h
- src/common/scratch_buffer.h
- src/core/core_timing.cpp
- src/core/core_timing.h
- src/core/hle/service/hle_ipc.cpp
- src/core/memory.cpp
- src/core/memory.h
- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/dma_pusher.cpp
- src/video_core/engines/engine_upload.cpp
- src/video_core/engines/kepler_compute.cpp
- src/video_core/engines/maxwell_3d.cpp
- src/video_core/engines/maxwell_dma.cpp
- src/video_core/engines/sw_blitter/blitter.cpp
- src/video_core/memory_manager.cpp
- src/video_core/memory_manager.h
- src/video_core/texture_cache/texture_cache.h
- src/video_core/texture_cache/util.cpp
- src/video_core/texture_cache/util.h
#10457 aimed to reduce memory allocations when copying from guest memory, this PR goes another step and aims to eliminate the data copy entirely.
The minimum guarantee we can have of data contiguity is 1 page (4Kb), but in reality, almost all guest memory is allocated contiguously in host memory. We can exploit that and use spans directly over guest memory, rather than requiring separate reads and writes every time we interact with it. From testing various games, this is able to eliminate a non-trivial amount of copying, and can give a noticable perf boost to a bunch of games, I get ~10% on SMO's metro scene for example. XCDE seems to get similar results.
Still could use some more testing that it doesn't break any games, and if anyone has any ideas for making a cleaner interface/making it …
> Use spans over guest memory where possible instead of copying data

- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/HomeSettingAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/HomeSetting.kt
- src/android/app/src/main/res/values/strings.xml
Allow for displaying options in the home options that are disabled with messages that explain why they are disabled.
This includes reasoning for the GPU driver installation button.
> android: Visualize disabled home options

- src/core/CMakeLists.txt
- src/core/hle/kernel/k_server_session.cpp
- src/core/hle/kernel/message_buffer.h
This allows nx-hbloader to properly retrieve non-pseudo handles. (This still needs to be fixed to do full parsing of the message buffer.)
> k_server_session: translate special header for non-HLE requests

- src/core/file_sys/content_archive.cpp
- src/core/loader/loader.h
Instead of failing silently when reading compressed NCAs, print an Error in the log and abort the parsing.
> file_sys/content_archive: Detect compressed NCAs

- src/common/settings.cpp
- src/common/time_zone.cpp
MinGW's strftime implementation does not work and cannot be used to determine the time zone. Besides that, the string operations are actually unnecessary since we can get the offset from std::localtime.
Compare localtime to gmtime to find the zone offset on all platforms.
In addition, disable the C++20 tzdb path on MinGW. This always results in Etc/UTC on MinGW, which often is not close to the local time zone.
> common: Use arithmetic instead of string ops to get time zone

- src/android/app/src/main/jni/native.cpp
- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_32.h
- src/core/arm/dynarmic/arm_dynarmic_64.cpp
- src/core/arm/dynarmic/arm_dynarmic_64.h
- src/core/arm/dynarmic/dynarmic_exclusive_monitor.h
- src/core/core.cpp
- src/core/core.h
- src/core/hle/kernel/physical_core.cpp
- src/yuzu/game_list_worker.cpp
Each of these instances happened to be one where we know the underlying type in one way or another and there is no need for an RTTI-based cast.
> general: remove uses of dynamic_cast

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/buffer_cache/buffer_cache_base.h
Should fix crashes when defeating the first boss in Master Detective Archives: Rain Code (#10987)
The game configures a compute pipeline with 18 texture buffers which overflows compute_texture_buffers and causes garbage data to be written in compute_uniform_buffer_sizes.
According to the vulkan spec the limit for texture buffers is `maxPerStageDescriptorSampledImages`. Looking at the switch vulkan driver in [vulkaninfo](https://vulkan.gpuinfo.org/displayreport.php?id=15757#properties) the limit appears much higher than the current 16, so I am not exactly sure on what the correct value is. Bumped it to 32 to match the number of bits in `enabled_compute_texture_buffers` in the buffer cache.
> buffer_cache: Increase number of texture buffers

- src/core/debugger/gdbstub.cpp
- src/core/hle/kernel/k_code_memory.cpp
- src/core/hle/kernel/k_page_table.h
- src/core/hle/kernel/k_process.cpp
- src/core/hle/kernel/k_process.h
- src/core/hle/kernel/k_shared_memory.cpp
- src/core/hle/kernel/k_thread_local_page.cpp
- src/core/hle/kernel/svc/svc_cache.cpp
- src/core/hle/kernel/svc/svc_code_memory.cpp
- src/core/hle/kernel/svc/svc_device_address_space.cpp
- src/core/hle/kernel/svc/svc_info.cpp
- src/core/hle/kernel/svc/svc_memory.cpp
- src/core/hle/kernel/svc/svc_physical_memory.cpp
- src/core/hle/kernel/svc/svc_process.cpp
- src/core/hle/kernel/svc/svc_process_memory.cpp
- src/core/hle/kernel/svc/svc_query_memory.cpp
- src/core/hle/kernel/svc/svc_shared_memory.cpp
- src/core/hle/kernel/svc/svc_thread.cpp
- src/core/hle/kernel/svc/svc_transfer_memory.cpp
- src/core/hle/service/ldr/ldr.cpp
- src/core/hle/service/nvdrv/devices/nvmap.cpp
- src/core/loader/deconstructed_rom_directory.cpp
- src/core/loader/kip.cpp
- src/core/loader/nro.cpp
- src/core/loader/nso.cpp
- src/core/memory.cpp
- src/core/memory/cheat_engine.cpp
- src/core/reporter.cpp
1. Change KProcess::PageTable to KProcess::GetPageTable
2. Reduce excessive checking on memory svcs and use new function names
> kernel: misc cleanup of page table accessors

- .ci/scripts/linux/docker.sh
I was asked recently if we could enable Wayland on our official releases. Does it work very well? Errr if you only like Vulkan on Intel or AMD then sure. But the point of this PR is to enable the feature even if it's not fully functional.
The new script includes AppImage changes so that the needed Qt Wayland libraries are included. The path was changed due to it previously existing in the GCC path for some odd reason. This also gives us an opportunity to make sure it's work on our CI before merging. Testing locally can be only half the battle sometimes.
> ci/linux: Target deploy script from appimage path

- src/shader_recompiler/ir_opt/ssa_rewrite_pass.cpp
This significantly improves the performance of the slowest shader compilation in Splatoon 3, from 30 seconds down to about 4 seconds. This is still too slow, but substantially better now.
I originally only used map, but found that the extra space overhead of unordered_map was worth it for this case when benchmarking.
> ssa_rewrite_pass: use proper maps

- src/core/debugger/gdbstub.cpp
- src/core/hle/kernel/svc/svc_ipc.cpp
- src/core/hle/kernel/svc/svc_synchronization.cpp
- src/core/memory.cpp
- src/core/memory.h
- Mostly eliminates the dependency on process, but a lot of code still calls into memory during initialization which needs to be fixed, and that felt out of scope for this.
- Removes some TOCTTOU mapping issues with IsValidVirtualAddress[Range] by having WalkBlock return whether all pages were user-accessible during traversal.
> memory: cleanup

- CMakeLists.txt
This package download has intermittent failures due to host Internet
issues (presumably), so download it ourselves from our own hosting.
> cmake: Download nasm from our external repo

- src/yuzu/game_list_worker.cpp
If you load yuzu without keys and already have a cache entry the game list will crash as soon as it tries to get the localized title id. Return early when the loader fails.
> yuzu: Avoid reading broken games

- src/common/page_table.h
- src/core/arm/arm_interface.cpp
- src/core/arm/arm_interface.h
- src/core/hle/kernel/k_auto_object.cpp
- src/core/hle/kernel/k_auto_object.h
- src/core/hle/kernel/k_scheduler.cpp
- src/core/hle/kernel/k_thread.cpp
- src/core/memory.cpp
- src/video_core/query_cache.h
- src/video_core/rasterizer_accelerated.cpp
- src/video_core/rasterizer_accelerated.h
There are still some other issues not addressed here, but it's a start.
Workarounds for false-positive reports:
- `RasterizerAccelerated`: Put a gigantic array behind a `unique_ptr`, because UBSan has a [hardcoded limit](https://stackoverflow.com/questions/64531383/c-runtime-error-using-fsanitize-undefined-object-has-a-possibly-invalid-vp) of how big it thinks objects can be, specifically when dealing with offset-to-top values used with multiple inheritance.  Hopefully this doesn't have a performance impact.
- `QueryCacheBase::QueryCacheBase`: Avoid an operation that UBSan thinks is UB even though it at least arguably isn't.  See the link in the comment for more information.
Fixes for correct reports:
- `PageTable`, `Memory`: Use `uintptr_t` values instead of pointers to avoid UB from …
> Fixes and workarounds to make UBSan happier on macOS

- src/yuzu/discord_impl.cpp
- src/yuzu/discord_impl.h
Seems like there's a memory leak within httplib. For now we can replace this code with QtNetworkRequest. This bring us multiple benefits. The first one is that no longer stalls until the image is ready. Second it saves 2GB of ram.
> yuzu: Replace httplib with QtNetworkRequest

- src/video_core/vulkan_common/vulkan_device.cpp
AMD has fixed this issue with public driver 23.7.2, so the blacklist is no longer needed
> Revert "Blacklist EDS3 blending from new AMD drivers"

- src/android/app/src/main/res/values-de/strings.xml
- src/android/app/src/main/res/values-es/strings.xml
- src/android/app/src/main/res/values-fr/strings.xml
- src/android/app/src/main/res/values-it/strings.xml
- src/android/app/src/main/res/values-ja/strings.xml
- src/android/app/src/main/res/values-ko/strings.xml
- src/android/app/src/main/res/values-nb/strings.xml
- src/android/app/src/main/res/values-pl/strings.xml
- src/android/app/src/main/res/values-pt-rBR/strings.xml
- src/android/app/src/main/res/values-pt-rPT/strings.xml
- src/android/app/src/main/res/values-ru/strings.xml
- src/android/app/src/main/res/values-uk/strings.xml
- src/android/app/src/main/res/values-zh-rCN/strings.xml
- src/android/app/src/main/res/values-zh-rTW/strings.xml
- src/android/app/src/main/res/values/strings.xml
If you are fluent in French and want to change an app to French, are you looking for French or Française?
If you accidentally change the language to Spanish, but only speak English, are you looking for Inglés or English?
Honestly, there is no real use for having the language name translated beyond curiosity, but it also avoids the entire discussion of what translations might be considered sensitive.
> android: Only label language with language

- src/video_core/vulkan_common/vulkan_device.cpp
Reverts #11163 
*Sighs*, turns out AMD hasn't fixed EDS3 blending for Polaris, they only fixed it for RDNA2 in 23.5.2
Thanks to [Blakbin](https://github.com/yuzu-emu/yuzu/issues/10285#issuecomment-1656729216) for bringing this to my attention so quickly
Further testing will be done before we implement a proper workaround/fix
> Revert the Revert! Reverts the Revert of "Blacklist EDS3 blending from new AMD drivers"

- src/core/hle/service/time/time_zone_content_manager.cpp
- src/core/hle/service/time/time_zone_content_manager.h
Some games such as Pokemon Legends: Arceus will rapidly ask for a single time zone rule many times in certain scenarios. In case of no dumped firmware, yuzu would generate the time zone binary from our own data. We were not storing this data for more than a moment, so the shared ptrs would accumulate, resulting in a memory leak.
This sets up TimeZoneContentManager to keep track of the time zone binary after it first generates it, thereby plugging the memory leak.
Closes #11174
> tz_content_man: Generate the time zone binary once

- src/video_core/renderer_vulkan/vk_blit_screen.cpp
- src/video_core/renderer_vulkan/vk_descriptor_pool.cpp
- src/video_core/renderer_vulkan/vk_fsr.cpp
- src/video_core/renderer_vulkan/vk_turbo_mode.cpp
Allows the descriptor set allocator to use a simpler linear allocator. Yuzu does not seem to free individual descriptor sets which makes this flag unnecessary.
> vk_descriptor_pool: Disallow descriptor set free

- src/audio_core/common/audio_renderer_parameter.h
I am become cringe, bringer of bad code. 
I'm not quite sure how I messed up the size of this as it doesn't match what I have in my docs, likely due to some confusion with the non-internal version. Thanks to byte for noticing.
> Fix AudioRendererParameterInternal's size

- src/video_core/CMakeLists.txt
- src/video_core/vulkan_common/vma.cpp
- src/video_core/vulkan_common/vma.h
- src/video_core/vulkan_common/vulkan.h
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_memory_allocator.cpp
- src/video_core/vulkan_common/vulkan_wrapper.cpp
- src/video_core/vulkan_common/vulkan_wrapper.h
The `VMA_*` options need to be defined before every inclusion of `vk_mem_alloc.h`, not just in the implementation. So regroup them in a header file with `vk_mem_alloc.h` and include this one everywhere instead.
> vma: enable options everywhere

- src/core/hle/service/audio/audren_u.cpp
The reduction in size from 0x38 to 0x34 caused the parameter to be misaligned. Skipping 1 word fixes this.
> audren_u: Fix parameter alignment

- src/video_core/vulkan_common/vulkan_device.cpp
I originally approved a commit to disable this on all AMD drivers, because AMD failed to increment the version number in their driver after fixing this bug. This was changed to blacklist Polaris despite it being demonstrably broken on other hardware, so this undoes that change and blocks it globally.
Fixes #11203
> vulkan_device: disable EDS3 blending on all AMD drivers

- src/video_core/renderer_vulkan/blit_image.cpp
- src/video_core/renderer_vulkan/renderer_vulkan.h
- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
- src/video_core/renderer_vulkan/vk_compute_pass.cpp
- src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.h
- src/video_core/renderer_vulkan/vk_scheduler.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
- src/video_core/vulkan_common/vulkan.h
- src/video_core/vulkan_common/vulkan_instance.cpp
- src/video_core/vulkan_common/vulkan_surface.cpp
- src/video_core/vulkan_common/vulkan_wrapper.h
- src/yuzu/vk_device_info.cpp
Continuation of https://github.com/yuzu-emu/yuzu/pull/11188.
Sadly the system headers included by `<vulkan/vulkan.h>`, like `<X11/Xlib.h>` and `<X11/X.h>`, create many stupid defines like `#define True 1` and `#define None 0L`, and global variables like `Time` and `GC`, which mess up with the rest of the code. So some headers need to be included before the inclusion of `"video_core/vulkan_common/vulkan.h"` by other headers.
It should probably be better to change yuzu code to not use names conflicting with these global variables in fact :$
> vulkan: centralize config

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/am/applet_ae.cpp
OpenLibraryAppletSelfAccessor was wrongly implemented. This PR might introduce some unimplemented errors but I'm not aware of any game that makes use of this interface.
> service: am: Fix wrong interface ILibraryAppletSelfAccessor

- src/core/hle/service/am/am.h
- src/core/hle/service/set/set.cpp
- src/core/hle/service/set/set.h
- src/core/hle/service/set/set_sys.cpp
- src/core/hle/service/set/set_sys.h
Implements all setting functions required to launch Qlaunch and MiiEdit. The default values are verified through homebrew.
> service: set: Implement system settings for Qlaunch

- src/shader_recompiler/environment.h
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/shader_cache.cpp
- src/video_core/shader_cache.h
- src/video_core/shader_environment.cpp
- src/video_core/shader_environment.h
This PR does a few minor things:
1. Fix shader dumps to work properly with nvdisasm. Currently they're 50/50 on whether nvdisasm will complain or not, this is now fixed from my testing, a good ~3K shaders all decompiled without issue. Also changed their names to \<key hash>\_\<stage>\_\<shader hash>, including the graphics key hash, since that's what we print in the console and how we store all the pipelines, making it easier to find them.
2. Skip fragment shaders when rasisation is disabled. In Xenoblade Chronicles 3, when using transform feedback pipelines with rasterisation disabled, the fragment shader is still enabled in the regs, but it's a leftover from whatever was drawn previously, and potentially invalid for the current draw. 
In XC3, the fragment shaders often contain texture …
> Fix various misc pipeline/shader things

- src/core/hle/service/audio/audctl.cpp
- src/core/hle/service/audio/audctl.h
Continuing the endless number of stubs Qlaunch needs. This time with audio.
> service: audctl: Stub functions needed by Qlaunch

- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
This has been a minor sore spot since the refactor in #9530 -- you would need to disable both the feature and extension in separate ways. This allows us to cleanly disable all the features when we disable an extension, preventing crashes in debugging tools.
> vulkan_device: disable features associated with unloaded extensions

- src/core/hle/service/nvnflinger/buffer_queue_producer.cpp
- src/core/hle/service/nvnflinger/window.h
Fixes graphics on Gunvolt Chronicles Luminous Avenger iX 1.0.0.
> nvnflinger: add missing scale mode

- src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
`assembly_programs` is not yet initialized at this point of the pipeline creation, so the `assembly_shaders` check always returned false.
> gl_graphics_pipeline: Fix GLASM storage buffer detection

- src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
- src/video_core/renderer_opengl/gl_graphics_pipeline.h
Fixes character shading in Pokemon Legends Arceus, and likely other titles that use Transform Feedback.
| Before | After |
| -------|------|
Multiple streams is not currently supported:
https://github.com/yuzu-emu/yuzu/blob/26ff2147197352b571c394404de2be1a65d0cf9b/src/video_core/transform_feedback.cpp#L88
The correct usage here is to use multiple transform feedback buffers, not streams. So the buffer mode must be `GL_SEPARATE_ATTRIBS` and the stream used should always be Stream 0 (implicit in `glTransformFeedbackAttribs`)
> gl_graphics_pipeline: GLASM: Fix transform feedback with multiple buffers

- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/LicenseAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/viewholder/DateTimeViewHolder.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/viewholder/RunnableViewHolder.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/viewholder/SettingViewHolder.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/viewholder/SingleChoiceViewHolder.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/viewholder/SliderViewHolder.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/viewholder/SubmenuViewHolder.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/viewholder/SwitchSettingViewHolder.kt
- src/android/app/src/main/res/layout/dialog_slider.xml
- src/android/app/src/main/res/layout/list_item_setting.xml
- src/android/app/src/main/res/values/strings.xml
+ Fixed a bug where a switch setting could apply the value of the recycled view
+ Display settings value in list view
+ Use string resource for slider value/units
+ Reduce opacity of non-editable settings
+ Remove redundant "Default" button in slider dialog
> android: Settings tweaks

- src/core/internal_network/network.cpp
- src/core/internal_network/network_interface.cpp
This made it impossible to diagnose some LDN issues since the error messages were not printed anymore.
> Partially Revert "Silence nifm spam"

- src/CMakeLists.txt
Fix https://github.com/yuzu-emu/yuzu/issues/11300.
> cmake: mark warning disable for gcc 11

- src/core/hle/kernel/k_hardware_timer.h
- src/core/hle/kernel/k_resource_limit.cpp
- src/core/hle/kernel/k_resource_limit.h
- src/core/hle/kernel/k_scoped_scheduler_lock_and_sleep.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/svc/svc_address_arbiter.cpp
- src/core/hle/kernel/svc/svc_condition_variable.cpp
- src/core/hle/kernel/svc/svc_ipc.cpp
- src/core/hle/kernel/svc/svc_resource_limit.cpp
- src/core/hle/kernel/svc/svc_synchronization.cpp
- src/core/hle/kernel/svc/svc_thread.cpp
This resulted in svcs waiting for longer than they needed to, in general, as well as KResourceLimit and Svc::CreateThread specifically never waiting for the correct amount of time when a timeout was passed.
> kernel: remove relative task registration

- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/texture_cache/texture_cache_base.h
The accelerated engine functions in 2d/dma/upload do GPU <-> GPU copies where possible, skipping a write to the CPU-side destination address, but we're currently not marking the destination buffer/image as being modified in DMA, which they should be, otherwise any future reads will not trigger a download and read the wrong data.
The non-accelerated paths in all engines are likely also causing some issues, due to the fact that they don't mark the relevant image/buffer as CPU-modified. I'm not sure how to correctly find them from the various engines, and if this is really even an issue, so I'll leave that to @FernandoS27 to check.
We also now fallback to a software blit when encountering an address which isn't valid for the given image's format. That case needs some more research.
Closes …
> Mark accelerated DMA destination buffers and images as GPU-modified

- src/video_core/host_shaders/CMakeLists.txt
- src/video_core/host_shaders/vulkan_depthstencil_clear.frag
- src/video_core/renderer_vulkan/blit_image.cpp
- src/video_core/renderer_vulkan/blit_image.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
Vulkan doesn't support masked clears, so we need to implement them another way. This PR implements the clear via drawing a full-screen tri, and allowing the regular stencil hardware to handle the masking and writing. The stencil test values are set up as normal, except we pass the clear value for the reference rather than the usual ref register, and the same for depth.
Closes #11313 and #11314
> Support masked depthstencil clears

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
Previously when switching between landscape modes when in orientation lock, you would have to press the button that appears when you reorient the screen. Now the app will switch between landscape and reverse-landscape automatically.
Closes #11335
> android: Use sensor landscape for landscape mode

- src/core/file_sys/card_image.cpp
- src/core/file_sys/card_image.h
Fixes #9902 (probably)
Fixes #9141
Fixes #4410
> file_sys/card_image: support dumps with prepended key area

- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/HomeSettingAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/HomeSetting.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/HomeViewModel.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
- src/android/app/src/main/res/layout/card_home_option.xml
You can now attach live data to a home setting item to display relevant information about that option.
> android: Show associated value in home settings

- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
Likely fixes #11373
Ports this fix which was made well after the YFC changes added the file:
skyline-emu/skyline@94ac457
> nvhost_as_gpu: ensure mappings are aligned to big page size when deallocated

- src/core/hle/kernel/k_process.cpp
- src/core/hle/kernel/k_process.h
- src/core/loader/deconstructed_rom_directory.cpp
- src/core/loader/kip.cpp
- src/core/loader/nro.cpp
- src/core/loader/nso.cpp
- src/core/reporter.cpp
Prevents [this bug](https://github.com/skyline-dev/skyline/issues/79) from occurring by allowing space in the ASLR region to exist before the code load address.
> kernel: offset code entry point for 39-bit address space type

- src/core/hle/service/ssl/ssl.cpp
- src/core/hle/service/ssl/ssl_backend_openssl.cpp
- src/core/hle/service/ssl/ssl_backend_schannel.cpp
Needs Windows testing. Also fixes a double-free in the OpenSSL backend destructor (SSL_free frees the BIO handles for you).
> ssl: tolerate handshake without hostname set

- src/yuzu/main.cpp
- src/yuzu/main.h
Fixes updates and DLC not being loaded when launching yuzu from the command line.
Similar to https://github.com/yuzu-emu/yuzu/pull/11357. 
Fixes https://github.com/yuzu-emu/yuzu/issues/8352,
> yuzu/main: Ensure NCAs are registered in content provider when launching from CLI

- src/android/app/src/main/AndroidManifest.xml
This still doesn't make builds appear as a game to the Samsung game launcher but this could help for the version of the app that is delivered from that play store. `isGame` was deprecated in Android Oreo and `appCategory` is supposed to be the replacement. But I'll be keeping both just in case there are game launchers that only check for `isGame`.
> android: Use appCategory to specify the app is a game

- externals/CMakeLists.txt
- src/CMakeLists.txt
- src/common/swap.h
- src/input_common/input_poller.cpp
- src/web_service/verify_user_jwt.cpp
Note: For GCC there are still a huge number of `-Warray-bounds` warnings coming from `externals/dynarmic`.  I could have added a workaround in `externals/CMakeLists.txt` similar to what this PR does for other externals, but given Dynarmic's close affiliation with Yuzu, it would be better to fix it upstream.
Besides that, on my machine, this makes the build warning-free except for some warnings from glslangValidator and AutoMoc.
Details:
- Disable some warnings in externals.
- Disable `-Wnullability-completeness`, which is a Clang warning triggered by the Vulkan SDK where if any pointers in the header are marked _Nullable, it wants all pointers to be marked _Nullable or _Nonnull. Most of them are, but some aren't.  Who knows why.
- `src/web_service/verify_user_jwt.cpp`: Disable another …
> Warnings cleanup for GCC 13 and Clang 16

- src/video_core/macro/macro.cpp
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Currently we have no real way to tell which macros we've already decompiled and which we haven't, besides manual checking of hashes. This PR just changes their name to `decompiled_` when they've already been decompiled to make it easy to see what's new.
Also dumps shaders after they're been translated, rather than before, which makes it possible to conditionally dump some shaders based on instructions they use. I wanted this for only dumping shaders that use the SAM/RAM instructions in Bayonetta 3 for example.
> Mark decompiled macros on dump, dump shaders after translation

- src/audio_core/sink/cubeb_sink.cpp
- src/audio_core/sink/cubeb_sink.h
- src/audio_core/sink/sdl2_sink.cpp
- src/audio_core/sink/sdl2_sink.h
- src/audio_core/sink/sink_details.cpp
Avoids the problem of badly configured audio devices that fail to init, and then softlocking games on boot. Tests each of the preferential backends in turn to see if they're valid, and falls back to null when they aren't, which avoids games softlocking.
> Pre-test for valid audio backends

- src/android/app/src/main/jni/config.cpp
- src/android/app/src/main/jni/native.cpp
- src/common/settings.cpp
- src/common/settings.h
- src/common/settings_common.h
- src/common/settings_enums.h
- src/core/frontend/applets/controller.cpp
- src/core/frontend/framebuffer_layout.cpp
- src/core/hle/service/am/am.cpp
- src/core/hle/service/apm/apm_controller.cpp
- src/core/hle/service/hid/controllers/gesture.cpp
- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/vi/vi.cpp
- src/core/telemetry_session.cpp
- src/yuzu/applets/qt_controller.cpp
- src/yuzu/bootmanager.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/config.h
- src/yuzu/configuration/configure_input.cpp
- src/yuzu/configuration/configure_per_game.cpp
- src/yuzu/configuration/configure_system.cpp
- src/yuzu/configuration/shared_translation.cpp
- src/yuzu/configuration/shared_widget.cpp
- src/yuzu/configuration/shared_widget.h
- src/yuzu/main.cpp
See linked issue for premise.
This does a couple things to complete that goal. shared_widget now supports radio groups for enumerations. use_docked_mode is now an enumeration to take advantage of that. configure_per_game will check the console mode setting against the first player's controller type to sanitize against handheld/docked issues.
The new console mode radio group is removed in the global configuration dialog, for simplicity sake and to avoid duplicating settings. I was somewhat miffed that it used to be just a GetValue call to check the docked state, and this changed it to a enum comparison. I added a helper function `Settings::IsDockedMode` which addressed that concern.
Would have closed #11325
> general,config-qt: Present Console Mode as an enum with separate options in game properties

- src/core/hle/service/audio/hwopus.cpp
- src/core/hle/service/audio/hwopus.h
Allows MLB The Show 22 to boot.
Fixes https://github.com/yuzu-emu/yuzu/issues/7911.
> hwopus: Implement OpenHardwareOpusDecoderForMultiStreamEx and DecodeInterleavedForMultiStream

- src/android/app/src/main/AndroidManifest.xml
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsActivity.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/views/FixedRatioSurfaceView.kt
- Fixes a bug where the emulation surface would appear stretched when changing from the orientation where emulation started
- Fixes a bug where the emulation activity would start in landscape and then switch to portrait when using the portrait/auto settings for orientation
> android: Emulation activity fixes

- externals/ffmpeg/CMakeLists.txt
- src/video_core/host1x/codecs/codec.cpp
If final frame was transferred from GPU, it won't carry the props.
Fixes #11089
This also needs an update to ffmpeg windows binaries to include `scale` filter which I suppose is required for pix formats conversions.
> Use initial_frame to check interlaced flag

- CMakeLists.txt
This version allows to disable WGI however I had to disable it with cmake flags since we can't use that feature yet on some systems until they update to 2.28.2. This mainly solves crashes when opening yuzu with specific controllers. Depends on https://github.com/yuzu-emu/ext-windows-bin/pull/47
- Fixed Xbox controller trigger motion events on Windows
- Fixed Xbox controller rumble in the background on Windows
- Fixed 8BitDo gamepad mapping when in XInput mode on Linux
- Fixed controller lockup initializing some unofficial PS4 replica controllers
closes #11296
> externals: Update SDL to 2.28.2

- src/android/app/src/main/AndroidManifest.xml
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/GameHelper.kt
- src/android/app/src/main/res/navigation/emulation_navigation.xml
- src/android/app/src/main/res/navigation/home_navigation.xml
Added a view action to the emulation activity so that you can launch games in yuzu from other apps like Daijishō
Demo -
> android: Support intents to emulation activity

- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/GameAdapter.kt
After launching any game, an associated app shortcut is added to the launcher. You can long press the app icon and add any of these generated shortcuts to your home screen.
> android: Support dynamic app shortcuts

- src/core/core.cpp
- src/core/core.h
- src/core/hle/service/am/am.cpp
- src/yuzu/main.cpp
This should make the "Closing software" dialog less of an agonizing wait and more in-line with hardware behavior.
> am: shorten shutdown timeout when lock is not held

- src/shader_recompiler/frontend/maxwell/translate/impl/move_special_register.cpp
- src/video_core/dma_pusher.cpp
- src/video_core/dma_pusher.h
- src/video_core/engines/engine_interface.h
- src/video_core/engines/engine_upload.h
- src/video_core/engines/kepler_compute.cpp
- src/video_core/engines/kepler_compute.h
- src/video_core/engines/puller.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/vulkan_common/vulkan_wrapper.cpp
- src/video_core/vulkan_common/vulkan_wrapper.h
Big credits to Maide @Kelebek1 who investigated this issue.
This fixes Mario + Rabbids Kingdom Battle. I have not tested Sparks of hope:
and Sea of Solitude:
> Fix regressions that damaged compute indirect & use reinterpret for copies with different byteblocksizes

- src/yuzu/main.cpp
- src/yuzu/main.h
Fixes #11071
This addresses a bunch of janky code in the RomFS dumping menu. It now iterates all available program NCAs for the given application as well as data NCAs from DLC, and it now returns the content record type so that RomFS patching when a DLC update is present will work correctly.
> qt: fix romfs dumping for multiprogram applications

- src/core/crypto/key_manager.cpp
- src/core/crypto/key_manager.h
- src/core/file_sys/submission_package.cpp
- src/core/file_sys/submission_package.h
- src/core/hle/service/es/es.cpp
Adds support for loading personalized (encrypted title key) tickets from NSP files. Previously the relevant code would assume a common key and load in the first 16 bytes of the key area. Now, the code properly reads the ticket and loads it in as personalized or common depending on the type.
This also adds support for eticket_rsa_keypair key material, which was added to the Lockpick_RCM output sometime late last year and can be used instead of needing to derive the key material from other system files. The key pair is also now derived ahead of time and stored in KeyManager instead of re-deriving it every time it is needed.
> core: Add support for loading NSPs with personalized tickets.

- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
https://github.com/yuzu-emu/yuzu/pull/10668 added a new path for binding vertex buffers, but without the fix of https://github.com/yuzu-emu/yuzu/pull/6688 which causes crashing in all games with older Bifrost Mali GPUs as these do not expose 32 vertex bindings (only 16). Applying this fix here as well allows games to boot as they did before.
> vk_buffer_cache: Respect max vertex bindings in BindVertexBuffers

- CMakeLists.txt
- src/video_core/renderer_vulkan/renderer_vulkan.cpp
- src/video_core/renderer_vulkan/renderer_vulkan.h
- src/video_core/vulkan_common/vulkan_debug_callback.cpp
- src/video_core/vulkan_common/vulkan_debug_callback.h
- src/video_core/vulkan_common/vulkan_instance.cpp
The graphics debugging option on android is currently not very useful as validation layers are not available to the android app. So this PR adds a cmake option to automatically download the validation layers android binary from the vvl github and copy it to jniLibs directory.
In addition I've removed support for VK_EXT_debug_report as newer versions of vvl implement VK_EXT_debug_utils. I have tested it on my Samsung Note 9 and validation works as expected.
> android: Add option to bundle validation layer

- src/audio_core/renderer/command/data_source/adpcm.cpp
- src/audio_core/renderer/command/data_source/decode.cpp
- src/audio_core/renderer/command/data_source/pcm_float.cpp
- src/audio_core/renderer/command/data_source/pcm_int16.cpp
After a small change I made in #11428 to decode, audio was cutting out in XC2, and causing some issues in other games as well. 
After a bunch of investigation, I found an issue with version 1 of data source commands trying to loop. Version 2 of the data source commands added more looping control, and the decode function was updated to use them. Instead of splitting the decode function into an old and new for both version, instead they just passed the v2 struct, and the v1 commands initialise v2 wavebuffers using the v1 data.
I was not considering this properly, and wasn't correctly considering the new members when creating the v2 struct. This PR properly initialises those members which fixes v1 commands looping.
Closes #11462.
> [audio] Fix data source version 1 command looping

- src/audio_core/adsp/apps/audio_renderer/audio_renderer.cpp
- src/audio_core/adsp/apps/audio_renderer/audio_renderer.h
- src/audio_core/adsp/apps/audio_renderer/command_list_processor.cpp
- src/audio_core/adsp/apps/audio_renderer/command_list_processor.h
- src/audio_core/renderer/system.cpp
Currently we set the command buffer to a new struct every time. A couple fields in the struct are only meant to be set by the DSP and not the host, but using a new struct for this each time is implicitly setting the command count to 0.
If a command list takes too long to process on the DSP, it returns early before finishing completely, and in the next run it continues where it left off in the previous command buffer, instead of generating a new one. The DSP relies on the remaining command count being > 0 to continue properly, if it's 0 then the DSP re-initialises the list processor, which sets the command pointer back to the beginning, instead of letting it carry on from where it stopped in the previous run.
This should fix some issues when the DSP runs too slowly.
> [Audio] Do not reset the remaining command count each time

- src/core/loader/loader.cpp
- src/core/loader/loader.h
- src/core/loader/nca.cpp
- src/core/loader/nca.h
- src/core/loader/nsp.cpp
- src/core/loader/nsp.h
- src/core/loader/xci.cpp
- src/core/loader/xci.h
- src/yuzu/game_list.cpp
- src/yuzu/game_list.h
- src/yuzu/main.cpp
- src/yuzu/main.h
Instead of validating NCAs on the fly (by using the signature and root hashes), we can use the names of the NCAs to perform some lighter validation. Skipping integrity verification during game operation is slightly faster and avoids requiring a buffer cache implementation for the NCA storages.
> core: implement basic integrity verification

- src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
This fixes a NIR validation error that is not yet added as a Vulkan validation error. [The spec says:](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap15.html#interfaces-resources-descset)
> The `Image Format` of an `OpTypeImage` declaration **must not** be **Unknown**, for variables which are used for `OpAtomic*` operations.
Since the image's sampled type is set to u32x1, the result on most(?) drivers with the previous is that the atomic will be performed as a 32-bit operation. This makes that behavior explicit.
> shader_recompiler: always declare image format for image buffers

- src/yuzu/configuration/configure_graphics.cpp
- src/yuzu/main.cpp
The VSync combobox wouldn't populate if there was no Vulkan device, which caused issues with trying to set VSync on other backends.
This also adds another layer to GetCurrentGraphicsBackend to check for broken Vulkan and return OpenGL instead of Vulkan.
Closes #11445
> configure_graphics: Fix handling of broken Vulkan

- CMakeLists.txt
- src/common/CMakeLists.txt
- src/common/fs/path_util.cpp
yuzu checks for a `user` folder in the current working directory on non-windows and non-android platforms. At least on linux, the CWD will default to `~` if ran through an application launcher, and a folder at `~/user` will enable portable mode.
As installations with a package manager will not make use of portable mode, we should expose a compile time option to allow package maintainers disable this undesirable behavior.
closes #11441
> common: add a compile time option to allow disabling portable mode

- src/core/core.cpp
- src/core/internal_network/network.cpp
- src/core/internal_network/network.h
The [TCP logger](https://github.com/skyline-dev/skyline/blob/master/source/skyline/logger/TcpLogger.cpp#L41) here has a blocking accept call that gets converted to a host accept call. This ends up blocking forever until a host is actually accepted. However, when terminating the application, we want this to get shut down right away, and not require forcibly killing the emulator.
> internal_network: cancel pending socket operations on application process termination

- src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
- src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
- src/shader_recompiler/backend/spirv/spirv_emit_context.h
Fixes Pikmin 4 crashing on recent versions of Mesa (probably, debug builds have a NIR validation failure in the same shader that I couldn't get past, even on versions predating when they added the check for this SPIR-V validation issue).
Khronos removed (!) the ability to declare an OpTypeSampledImage for images with the Buffer dim declaration in SPIR-V 1.6. There appear to be no public notes for why they removed it completely instead of just marking it as a deprecation, and this removal makes it more inconvenient to work with buffer textures in a uniform way when stored alongside other samplers.
They also forgot to remove the SampledBuffer capability, which is now useless.
> shader_recompiler: skip sampler for buffer textures

- src/android/app/src/main/jni/native.cpp
Config is already initialized on application start
> android: Don't reinitialize settings on emulation start

- src/android/app/src/main/jni/native.cpp
When trying to avoid closing the emulation activity if there was a message that needed to be displayed (Ex. Invalid ROM), I accidentally prevented the emulation activity from getting the right message by running the OnEmulationStopped callback after the `m_load_result` state was reset. This behavior is corrected now.
> android: Return the correct status code on emulation stop

- src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/BooleanSetting.kt
- src/android/app/src/main/jni/native.cpp
Now just use the new settings interface provided by NativeConfig
> android: Remove settings interface specifically for audio mute

- externals/CMakeLists.txt
- externals/renderdoc/renderdoc_app.h
- src/common/settings.h
- src/core/CMakeLists.txt
- src/core/core.cpp
- src/core/core.h
- src/core/tools/renderdoc.cpp
- src/core/tools/renderdoc.h
- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_debug.ui
- src/yuzu/hotkeys.h
- src/yuzu/main.cpp
Debugging the texture or buffer cache is often difficult because certain resources are uploaded at specific points and then used in many subsequent frames. Capturing these specific frames in renderdoc is possible but cumbersome. This is my attempt at a solution to this problem.
The PR uses the renderdoc C API and adds a hotkey to start/stop frame captures. This way multiple frames can be recorded and written into the same large capture. Then using the resource inspector the desired frame can be found and analyzed. I've only enabled this if graphics debugging is used as it's a strictly debugging feature.
> debug: Add renderdoc capture hotkey

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/sockets/bsd.cpp
Allows Minecraft Legends to boot.
Fixes https://github.com/yuzu-emu/yuzu/issues/10067.
> am: Stub GetSaveDataSizeMax 

- src/android/app/src/main/jni/config.cpp
- src/common/settings_common.h
- src/common/settings_setting.h
- src/core/crypto/key_manager.cpp
- src/core/file_sys/ips_layer.cpp
- src/core/memory/cheat_engine.cpp
- src/yuzu/configuration/configure_ui.cpp
- src/yuzu/configuration/shared_widget.cpp
- src/yuzu/configuration/shared_widget.h
- src/yuzu_cmd/config.cpp
- src/yuzu_cmd/yuzu.cpp
Closes #11490 
This began as the title states, but I also took time to forward-port any Settings improvements I've done in my quest to backport the Settings rework to Citra. Fixes occasional issues with the application crashing due to a type of an exception not being caught. Adds some float support to Settings and shared_widget.
> general: Remove uncaught usages of C++ string number conversions

- src/common/fs/fs.cpp
Resolves a case on Windows where an unmounted bitlocker protected volume containing an assigned game directory would crash Yuzu at start.
May also resolve cases where a disconnected SMB volume causes similar crashes (needs testing)
closes #10597
> add std::error_code for std::filesystem exceptions

- src/core/file_sys/patch_manager.cpp
- src/core/file_sys/patch_manager.h
- src/core/hle/kernel/k_process.cpp
- src/core/hle/kernel/k_process.h
- src/core/hle/kernel/svc/svc_debug_string.cpp
- src/core/hle/kernel/svc/svc_exception.cpp
- src/core/loader/deconstructed_rom_directory.cpp
- src/core/loader/deconstructed_rom_directory.h
- src/core/loader/kip.cpp
- src/core/loader/nro.cpp
- src/core/loader/nso.cpp
- src/core/loader/nsp.cpp
1. When looking for patches, we now print the filename of the module, so you don't have to guess.
2. Debug output is upgraded to info log, since it's useful when making patches.
3. Debugger is changed to not stop on notification-type exceptions unless the program is HBL, to match behavior of dmnt.gen2 as best as possible (we don't have override/takeover, so we could never know exactly, but this should be close enough).
> core: improve debug workflow

- src/core/hle/service/nfc/common/device.cpp
This function was bound to crash every time.  Fix the behavior so it actually sucedes when formatting the tag.
> service: nfc: Fix amiibo formatting

- src/core/hid/hid_core.cpp
- src/core/hid/hid_core.h
- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
- src/core/hle/service/hid/hid.cpp
Implement get last active Npad since the stub was causing issues with controllers not being detected. Removes deprecated field from the Npad struct since this will never be used anymore. And lastly we had a nasty bug where the controller could be connected but not supported. So double check both the emulated and the service are connected if not try to fix it.
> service: hid: Implement last active Npad and fix some errors.

- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid.h
AppletResource should be actually shared between hid services. Someone put `// We already do this for homebrew so we can just stub it out` well this is a lie so in this PR we actually implement this function.
> service: hid: Implement ApplyNpadSystemCommonPolicy

- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Users have pointed out that during shader compilation in game (on devices that aren't using Adreno), games can crash unless they go through that game segment at a slower speed. This indicated a problem with using different amounts of workers between each device type.
Fix provided by @liamwhite
> android: Use 1 worker for shader compilation for all devices

- src/audio_core/CMakeLists.txt
- src/audio_core/adsp/adsp.cpp
- src/audio_core/adsp/adsp.h
- src/audio_core/adsp/apps/audio_renderer/audio_renderer.cpp
- src/audio_core/adsp/apps/audio_renderer/audio_renderer.h
- src/audio_core/adsp/apps/opus/opus_decode_object.cpp
- src/audio_core/adsp/apps/opus/opus_decode_object.h
- src/audio_core/adsp/apps/opus/opus_decoder.cpp
- src/audio_core/adsp/apps/opus/opus_decoder.h
- src/audio_core/adsp/apps/opus/opus_multistream_decode_object.cpp
- src/audio_core/adsp/apps/opus/opus_multistream_decode_object.h
- src/audio_core/adsp/apps/opus/shared_memory.h
- src/audio_core/adsp/mailbox.h
- src/audio_core/opus/decoder.cpp
- src/audio_core/opus/decoder.h
- src/audio_core/opus/decoder_manager.cpp
- src/audio_core/opus/decoder_manager.h
- src/audio_core/opus/hardware_opus.cpp
- src/audio_core/opus/hardware_opus.h
- src/audio_core/opus/parameters.h
- src/common/CMakeLists.txt
- src/common/bounded_threadsafe_queue.h
- src/core/CMakeLists.txt
- src/core/hle/result.h
- src/core/hle/service/audio/errors.h
- src/core/hle/service/audio/hwopus.cpp
- src/core/hle/service/audio/hwopus.h
Since we recently had problems with some unimplemented hwopus functions, I decided to RE it and do a reimplementation. This PR moves the main Opus processing over to the ADSP, and also implements all the remaining functions that we don't currently have.
Please test with any games using Opus. Ones I know of include MLB The Show 22/23, Touhou, Pokemon Quest, Pokemon Let's Go Eevee! and Sea of Stars.
> Reimplement HardwareOpus

- src/core/hle/service/mii/mii_types.h
This is an OoB array access, causing a crash on at least the Linux Flatpak releases.
> mii_types: Remove null terminator check

- src/audio_core/renderer/command/command_processing_time_estimator.cpp
- src/audio_core/renderer/system.cpp
Fixes a bug with time estimation and the dropping of voices. In New Super Marios Bros U's final level, the music can randomly cut out, which happens due to the music getting dropped when the command buffer goes over its time estimate with too many commands. NSMBU has a specific case where it runs into situations needing to drop *some* voices, but not drop so many that it gets to the music track.
The starting point for time estimation is meant to begin after voice generation rather than before, so all voice commands aren't counted, which results in a smaller estimation, and fewer commands need to be dropped to fit into the time limit. Also a small fix to the ADPCM estimate from a bad copy/paste. That file is a nightmare.
> Do not consider voice commands in time estimation, fix adpcm estimate

- src/core/file_sys/partition_filesystem.cpp
Can't say it applies to many games but in my case `Luigi's Mansion 3` couldn't load and instead caused Yuzu to segfault randomly. The log says:
```
[   0.446392] Service.FS <Warning> core/file_sys/submission_package.cpp:ReadNCAs:245: NCA with ID 0fe8c30f50fa8d12c9b9b85045fe6473.nca is listed in content metadata, but cannot be found in PFS. NSP appears to be corrupted.
[   0.446601] Loader <Debug> core/loader/loader.cpp:GetLoader:265: Loading file Luigis Mansion 3 [0100DCA0064A6000][v0] (6.35 GB).nsp as NSP...
[   0.446647] Crypto <Debug> core/crypto/key_manager.cpp:AddTicket:1366: Skipping parsing title key from ticket for known rights ID 080000000000000000604A06A0DC0001.
[   0.446811] Service.FS <Warning> core/file_sys/submission_package.cpp:ReadNCAs:245: NCA with ID …
```
> pfs: Fix reading filenames past the buffer end

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/ImportExportSavesFragment.kt
- src/android/app/src/main/res/values-de/strings.xml
- src/android/app/src/main/res/values-es/strings.xml
- src/android/app/src/main/res/values-fr/strings.xml
- src/android/app/src/main/res/values-it/strings.xml
- src/android/app/src/main/res/values-ja/strings.xml
- src/android/app/src/main/res/values-ko/strings.xml
- src/android/app/src/main/res/values-nb/strings.xml
- src/android/app/src/main/res/values-pl/strings.xml
- src/android/app/src/main/res/values-pt-rBR/strings.xml
- src/android/app/src/main/res/values-pt-rPT/strings.xml
- src/android/app/src/main/res/values-ru/strings.xml
- src/android/app/src/main/res/values-uk/strings.xml
- src/android/app/src/main/res/values-zh-rCN/strings.xml
- src/android/app/src/main/res/values-zh-rTW/strings.xml
- src/android/app/src/main/res/values/strings.xml
Reverts yuzu-emu/yuzu#11551 due to an oversight in the user profile folder generation. Will be reintroduced later with a proper solution.
> Revert "android: Allow save imports always"

- src/video_core/engines/maxwell_dma.cpp
- src/video_core/engines/maxwell_dma.h
Remap register offsets are wrong, which is leading to ClearBuffer filling buffers with the wrong values.
This completely breaks lighting in Pikmin 4, but it's already half-broken and is only working by accident.
> Fix DMA engine register offsets

- src/video_core/renderer_vulkan/maxwell_to_vk.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
Some games use this format for text rendering but because the component order was not correct it would show up all wrong. So instead we use VK_FORMAT_A4B4G4R4_UNORM_PACK16_EXT which has the order we want. If that format is not available then it is emulated using a swizzle.
yuzu (master) | yuzu (PR)
-|-
Fixes https://github.com/yuzu-emu/yuzu/issues/11550
> renderer_vulkan: Correct component order for A4B4G4R4_UNORM

- src/core/hle/service/am/applets/applet_mii_edit.cpp
- src/core/hle/service/am/applets/applet_mii_edit.h
- src/core/hle/service/mii/mii.cpp
- src/core/hle/service/mii/mii.h
- src/core/hle/service/mii/mii_manager.cpp
- src/core/hle/service/mii/types/char_info.cpp
- src/core/hle/service/mii/types/core_data.cpp
- src/core/hle/service/mii/types/raw_data.cpp
Allows our HLE implementation of mii edit to create mii. This PR also fixes random mii generation, makes the mii manager shared across sessions as well implements GetIndex which somehow wasn't implemented by previous PR.
With this change creating a mii from any game won't result in any crash. Instead it will automatically generate a random mii.
Fixes: #3587
> am: mii_edit: Implement DB operations

- src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
If you wanted to manually back up your user data from an older version and then import it into a newer version, sometimes it would fail because of how your compression tool would create the zip file.
> android: Adjust valid user data check

- src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
The File.readBytes() extension attempts to load an entire file into a byte array. This would cause crashes when loading huge files into memory.
> android: Use smaller read buffer size for exporting user data

- src/shader_recompiler/backend/spirv/emit_spirv_image_atomic.cpp
- src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
Fixes #11559
The root cause of the problem in #11436 was performing atomic operations on a typeless image. However, given the constraints of how atomic operations are compiled, it is literally impossible for a typeless atomic to be emitted, and I did not pay close enough attention to that.
After debugging _why_ that happened, I found that this is just a bug where the SPIR-V code for atomics uses the _array layer of the image_ instead of the numeric value of the correct descriptor...
I fixed it and removed the previous workaround that sets typeless image buffers to R32UI (which is actually wrong because they may occur without atomics -- so they are supposed to be typeless in that case).
Fixes lighting in Pikmin 4.
Fixes #11487
Fixes https://github.com/yuzu-emu/yuzu/issues/11125.
Fixes …
> emit_spirv: fix incorrect use of descriptor index in image atomics

- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
On devices that don't support D24S8 but supports D32S8, this should still return true if D32S8 supports src and dst blit
> vulkan_device: Return true if either depth/stencil format supports blit

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/am/applet_ae.cpp
- src/core/hle/service/filesystem/fsp_srv.cpp
- src/core/hle/service/filesystem/fsp_srv.h
- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/mii/mii_types.h
- src/core/hle/service/ns/iplatform_service_manager.cpp
- src/yuzu/main.cpp
- src/yuzu/main.h
- src/yuzu/main.ui
After more than 6 months of research, 15 PR, a few thousand lines of code and the holy illumination from byte. I'm happy to announce that yuzu can now boot LLE applets. This PR allows to boot the mii editor from firmware via `tools->mii editor`. 
You can create, edit or even load your mii from an amiibo using your joycon. Using them in games or anything related. All features are fully supported with exception of send/receive from other consoles.
Closes: #11280
Finally thank you to all yuzu team for making this PR possible. (Forgive me if I forgot someone)
> service: am: Add support for LLE Mii Edit Applet

- src/android/app/src/main/java/org/yuzu/yuzu_emu/overlay/InputOverlay.kt
Even after updating the androidx window library, this did not fix the issue for all devices. This ensures that the measured size of the overlay will be used instead of a potentially larger one seen by androidx.
> android: Use measured size of view for input overlay bounds

- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsActivity.kt
- src/android/app/src/main/res/layout/activity_settings.xml
Fixes an issue where the settings activity could appear dim while using 3 button navigation and landscape.
> android: Prevent nav bar shade from laying out across screen

- src/common/settings_setting.h
This was mysteriously missing, likely from when I ported Citra fixes semi-recently.
> settings_setting: Read audio engine

- src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
- src/android/app/src/main/jni/native.cpp
- src/android/app/src/main/res/values/strings.xml
The C++ side never made the filename lowercase when checking the extension. This just passes the pre-prepared extension to have it checked.
> android: Content install lowercase fix

- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsActivity.kt
Previously the config file wasn't being recreated when resetting all settings. Now just call into native code to recreate the settings file and reload all defaults.
> android: Correctly reload settings file during reset

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/SetupFragment.kt
- src/android/app/src/main/res/values/strings.xml
Was looking at play store stats and noticed a few crashes that I could fix quickly.
Fixes an issue where the app would crash if the emulation activity doesn't have a game.
Fixes an issue where we tried to update invalid views in the emulation fragment.
Fixes a couple issues where we tried to update invalid views in the setup fragment.
Additionally don't wait for post callback to update input overlay visibility.
> android: Various play store fixes

- src/video_core/host_shaders/convert_msaa_to_non_msaa.comp
- src/video_core/host_shaders/convert_non_msaa_to_msaa.comp
- src/video_core/renderer_vulkan/vk_compute_pass.cpp
- src/video_core/renderer_vulkan/vk_compute_pass.h
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
- src/video_core/vulkan_common/vulkan_device.h
Implementation of https://github.com/yuzu-emu/yuzu/pull/9746 for vulkan for the image copy part. I didn't implement uploads because I couldn't find much information about the layout of MSAA images and games I tested do not upload anything meaningful anyway. Fixes graphics in Sonic Forces as mentioned in the PR and also in Mortal Kombat 1
yuzu (master) | yuzu (PR)
-|-
> renderer_vulkan: Implement MSAA image copies

- src/android/app/src/main/jni/native.cpp
- src/yuzu/main.cpp
- src/yuzu/main.h
Just talked with @liamwhite about how you can still install these. Figured we should remove the ability to since XCIs are usually application containers and will fail on installation.
> Frontend: Remove ability to install xci files

- src/common/settings.h
- src/core/core.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
- src/video_core/vulkan_common/vulkan_wrapper.cpp
- src/video_core/vulkan_common/vulkan_wrapper.h
This should fix the z fighting in some games in AMD cards. So far only RADV supports the extension, hopefully, AMD's proprietary driver will in the future.
I'm leaving it as  a Draft as it needs testing.
> Vulkan: Implement Depth Bias Control

- src/core/hle/service/am/am.cpp
Regression from #11569, FocusStateChanged is pushed twice, once in LoopProcess when setting up the services, and then it's set again when ICommonStateGetter is created as added by #11569. Removing the one in LoopProcess fixes a hang on boot.
Closes #11624
> Don't send a double focus change message

- src/core/hid/emulated_controller.cpp
- src/core/hid/emulated_controller.h
- src/core/hle/kernel/k_hardware_timer.cpp
This gives a small reduction in the mutex contention around core timing callbacks.
> Reduce core timing mutex contention

- src/core/CMakeLists.txt
- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/am/applets/applet_cabinet.h
- src/core/hle/service/am/applets/applet_general_backend.cpp
- src/core/hle/service/am/applets/applets.cpp
- src/core/hle/service/am/applets/applets.h
- src/core/hle/service/ldn/ldn.cpp
- src/core/hle/service/nfc/common/device.cpp
- src/core/hle/service/nvdrv/devices/nvmap.h
- src/core/hle/service/nvnflinger/buffer_item.h
- src/core/hle/service/nvnflinger/buffer_slot.h
- src/core/hle/service/nvnflinger/fb_share_buffer_manager.cpp
- src/core/hle/service/nvnflinger/fb_share_buffer_manager.h
- src/core/hle/service/nvnflinger/graphic_buffer_producer.h
- src/core/hle/service/nvnflinger/nvnflinger.cpp
- src/core/hle/service/nvnflinger/nvnflinger.h
- src/core/hle/service/nvnflinger/ui/fence.h
- src/core/hle/service/nvnflinger/ui/graphic_buffer.h
- src/core/hle/service/vi/vi.cpp
- src/yuzu/main.cpp
- src/yuzu/main.h
- src/yuzu/main.ui
Why stop with mii edit applet. We also have an accurate emulation of amiibos already. This PR allows to use all the functionality of the amiibo manager. You can now register, rename, delete, restore the data of your amiibo via `tools->Amiibo`.
Special thanks to byte for implementing the hard vi, nvnflinger stuff.
> service: am: Add support for LLE Cabinet Applet

- src/core/hle/service/filesystem/fsp_srv.cpp
The MiiEdit applet disables automatic save data creation, which is persisted global state(!)
This caused games that need automatic save data creation to crash when booting, so reset the state every time fsp-srv is re-inited.
> fsp-srv: enable auto save data creation on init

- src/core/core.cpp
- src/yuzu/configuration/configure_audio.cpp
- src/yuzu/configuration/shared_translation.cpp
- src/yuzu/main.cpp
- src/yuzu/uisettings.h
Mute audio when in background and changing custom rtc while the game is open will now work properly.
Fixes https://github.com/yuzu-emu/yuzu/issues/11663.
Fixes https://github.com/yuzu-emu/yuzu/issues/10127.
> yuzu: Fix custom rtc and mute audio settings

- src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
- src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
- src/video_core/vulkan_common/vulkan_memory_allocator.cpp
- src/video_core/vulkan_common/vulkan_memory_allocator.h
As in the comments, GPUs without rebar support have a very limited host/device heap size, which gets very full in a frame. This prevents RenderDoc from being able to open 2 captures at the same time, since if 200/256MB of the heap is full in a capture, opening a second then fails as the region is out of memory. RenderDoc cannot migrate or move allocations to other heaps, they have to be where they were originally. This PR removes non-stream allocations from the shared heap, and also limits the size of the stream buffer to 40% of max, so 2 can be opened.
Also removes HOST_ACCESS flags from our DeviceLocal allocations, as we always call copy functions on device local memory, so there's no need to try and allocate them into host visible regions. May give a performance increase.
> Allow GPUs without rebar to open multiple RenderDoc captures

- src/video_core/renderer_vulkan/blit_image.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
Depth test must be enabled to allow depth writing.
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPipelineDepthStencilStateCreateInfo.html#_members
> depthWriteEnable controls whether depth writes are enabled when depthTestEnable is VK_TRUE. Depth writes are always disabled when depthTestEnable is VK_FALSE.
Fixes #11438
> Enable depth test on depthstencil clear path

- src/video_core/host_shaders/CMakeLists.txt
- src/video_core/host_shaders/convert_d32f_to_abgr8.frag
- src/video_core/renderer_vulkan/blit_image.cpp
- src/video_core/renderer_vulkan/blit_image.h
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
Corrects some visual issues in games such as Disney SpeedStorm
Closes #11671
Fixes #9798
When combined with #11534 also partially addresses #11666 (Map issue remains)
Used without 11534 causes this
> Implements D32_Float to A8B8G8R8_UNORM format copy

- src/common/fs/fs_paths.h
- src/common/fs/path_util.cpp
- src/common/fs/path_util.h
- src/yuzu/game_list.cpp
- src/yuzu/main.cpp
- src/yuzu/util/util.cpp
- src/yuzu/util/util.h
Allows creating desktop shortcuts with icons for yuzu games.
This is a continuation of https://github.com/yuzu-emu/yuzu/pull/11344 with some minor changes and its review comments addressed.
> yuzu: Add desktop shortcut support for Windows (continuation of #11344)

- src/video_core/texture_cache/util.cpp
Alternative to #11528 
The If block in this change was causing some 2D textures to be treated as if their mip 0 was a 3D Slice, this could be ascertained as the same texture viewed from different distances would render fine, but then close up would look like a decoding failure.
It also resulted in some 3D ASTC textures not being scaled appropriate leading to broken graphical effects such as the jagged TOTK recall animation being a circle, as the If block was only accepting the image based on its original info without any adjustments applied.
Fixes #11252  and #10493
Doesn't reintroduce #10255
> Partial revert of #10433 (Texture Cache Util: Fix block depth adjustment on slices)

- src/video_core/texture_cache/util.cpp
Fixed an error on my part, in the last change I had mistakenly passed unadjusted block info into FullUploadSwizzles and UnswizzleImage
This reverts (my mistaken changing of) the construction of SwizzleParameters in UnswizzleImage and FullUploadSwizzles to use level_info.block instead of info.block. This ensures that the block information used in the swizzling process is correctly adjusted for each mip level.
This should close #11738 and negate the need for #11739
> Fix mistaken usage of info.block instead of level_info.block

- dist/qt_themes/default/style.qss
- dist/qt_themes/qdarkstyle/style.qss
- dist/qt_themes/qdarkstyle_midnight_blue/style.qss
- src/yuzu/applets/qt_controller.cpp
- src/yuzu/applets/qt_controller.h
- src/yuzu/applets/qt_controller.ui
Allows to add controllers and validate current configuration when the Controller Applet is opened.
Add a controller if possible (less than maximum) by using "Right" and remove by using "Left" (more than minimum).
Use "A" to validate and "B" to cancel. If less controllers than minimum are selected and the user tries to validate, an error message is shown. It disappears when the number of controllers is increaed.
> Enable controller interaction in Controller Applet

- src/video_core/renderer_opengl/gl_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
If resolution scaling is disabled, we shouldn't set the Rescaled flag as if it was active. This leads to weird issues/different paths taken where some images can be marked as rescaled and get compared with other images which are not rescaled. I've seen it throw this assert for instance: https://github.com/yuzu-emu/yuzu/blob/master/src/video_core/texture_cache/texture_cache.h#L2326
> Do not set rescaled flag when rescaling is disabled

- .ci/scripts/common/pre-upload.sh
- .ci/scripts/linux/docker.sh
- .ci/scripts/linux/upload.sh
Creates a new archive with a debug suffix that contains the debug symbols from compiling yuzu for mainline. The yuzu executable also gets a GNU debug link to the symbols file. ci/linux: Compile with debug symbols and upload separately
Currently only uploads for yuzu but yuzu-cmd or other future executables can be added to the for-loop's parameters.
> ci/linux: Upload separated debug symbols

- src/video_core/renderer_opengl/gl_texture_cache.h
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
- src/video_core/texture_cache/texture_cache.h
We have an implicit dependance on RefreshContents uploading an image's memory on creation, and the barrier for it transitioning the image to a general layout. For MSAA iamges we don't support uploading its data and return early, which ends up leaving the iamge in its default undefined layout. This then causes render passes using these as render targets to fail to draw. 
This PR just adds an explicit transition for multisampled images to get them into a general layout. Gets rid of a validation error, and is needed to fix some games rendering, though some still have issues to due memory tracking.
> Transition MSAA images to general layout without uploading data

- src/core/hle/service/caps/caps.cpp
- src/core/hle/service/caps/caps_manager.cpp
- src/core/hle/service/caps/caps_manager.h
- src/core/hle/service/caps/caps_types.h
- src/core/hle/service/caps/caps_u.cpp
I made too many mistakes here. First of all in parameters where wrong. Secondly `GetAlbumFileList3AaeAruid` returns a  `ApplicationAlbumEntry` list. Finally these should auto mount.
I also fully implemented GetAlbumFileList0AafeAruidDeprecated so it will now use the correct date range.
Fixes SSBU replays menu.
> service: caps: Fix GetAlbumFileList3AaeAruid and GetAlbumFileList0AafeAruidDeprecated

- src/common/common_funcs.h
- src/core/hle/kernel/kernel.cpp
Resolves runtime assertion failures due to overly-aggressive behavior of gold/lld regarding thread-local variables, which interact poorly with fibers.
See https://bugs.llvm.org/show_bug.cgi?id=19177
> kernel: mark TLS accessors as noinline for non-MSVC LTO

- src/yuzu/game_list.cpp
- src/yuzu/game_list_worker.cpp
- src/yuzu/game_list_worker.h
The item model in GameList takes ownership of GameListDir objects while they are being processed. However, the list can be cleared while the worker may still have live references to GameListDir objects. This prevents use-after-free in GameListWorker, by forcing processing to complete before clearing the list.
> qt: ensure worker cancellation is complete before clearing

- src/yuzu/main.cpp
This pull request updates how the directory path for shortcuts is determined. The main changes are:
1. Replaced the use of environment variables to determine the path of the desktop and applications menu with `QStandardPaths::writableLocation`. This change addresses an issue where the desktop path was not correctly identified when its location was customized, as shown in the attached screenshot.
2. Added conversion from `QString` to `std::string` using `toUtf8()`, which correctly handles non-ASCII characters in directory paths. This change ensures that directory paths containing Portuguese words like "área de trabalho" are supported.
3. Replaced directory checking using `Common::FS::IsDir()` with `QDir::exists()`.
These changes should improve cross-platform compatibility and code …
> Improvement in Directory Path Detection for Shortcuts

- src/audio_core/sink/sink_stream.cpp
When in the process of shutting down, the sink callback signals release_cv to wake up the producer, but the producer is waiting for the number of queued buffers to be less than the maximum queue size. This sets the number of queued buffers to 0 every time the sink callback is invoked when shutting down, so that the producer can stop waiting.
> audio: fix shutdown deadlock in audio renderer

- src/yuzu/configuration/configure_input.cpp
- src/yuzu/configuration/configure_input.h
When reducing the number of Connecter Controllers, keep the one clicked if it was not the last one of the list.
I find it more intuitive to click on the number of players we want, being for increasing or reducing. With the current behavior, if 4 controllers are set and we want to reduce it to 2, we need to click on "3", or to click on "2" two times.
> yuzu: Improve behavior when clicking on controller box in Control configuration

- src/input_common/drivers/udp_client.cpp
CemuHook can take a while to connect. So it's very likely you can start trying to map motion before the client is ready. To avoid mapping to undefined axis we need to preset the motion input beforehand.
> input_common: udp: Avoid crash when trying to map motion before client is ready

- src/video_core/host1x/codecs/codec.cpp
The code in question disabled use of CUDA/NVDEC hardware decoder on all Linux machines, including those where it works just fine. The only known setup where this caused problems and led to inclusion of this code is having two NVIDIA+AMD GPUs installed, which is a fairly uncommon case that with this change only requires user to select "CPU Video Decoding" for NVDEC emulation.
I've confirmed that this allows GPU decoding to work on my Linux+Nvidia setup.
> host1x/codecs: enable CUDA on Linux

- src/video_core/texture_cache/util.cpp
This resolves the out of bounds read/writes in the linear swizzler without tearing apart several hotpath optimizations performed, 
It brings back the scaled TOTK Recall bug however, pending further work in the block size calculation.
_Recall is not glitched in the Dynamic FPS resolution mod to the degree that it is in the native yuzu scaler, this can be a workaround for the time being._
The recall effect is constructed from multiple 320x180 texture slices, it breaking may have a similar origin to https://github.com/Ryujinx/Ryujinx/pull/5640
but it may also be connected to the other deficiencies identified in the Yuzu size calculations, such as no apparent implementation of slice size testing for end of slice depth as opposed to full aligned size as implemented in …
> [crash fix]brings back the removed if  statement in util.cpp and adds the  num_level test to it like previous discontinued PR

- src/video_core/buffer_cache/buffer_cache_base.h
- src/video_core/host_shaders/convert_d24s8_to_abgr8.frag
- src/video_core/host_shaders/convert_s8d24_to_abgr8.frag
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
1. Set vertex buffer num to 16, because mvk have when using more than 16.
2. Add missing scissor update when viewport scale offset disable.
3. Fix d24r8/s8d24 convert shader build error in moltenvk
> video_core: Fix moltenvk crash on macos 

- src/video_core/renderer_vulkan/vk_query_cache.cpp
- src/video_core/renderer_vulkan/vk_render_pass_cache.cpp
- src/video_core/texture_cache/formatter.cpp
- src/video_core/texture_cache/samples_helper.h
- Get out of render pass before attempting to barrier, fixes query cache rewrite spamming validation errors due to putting a barrier inside a render pass pre-syncing values (which still needs to be deleted @FernandoS27 , the spam in all games is pointless and huge).
- Remove image alias bit for all attachments. Why is this even here, host images don't alias? It's almost certainly preventing memory optimisations from happening.
- Fix image debug names with samples > 1
> Small things

- src/core/core.cpp
- src/core/file_sys/fsmitm_romfsbuild.cpp
- src/core/file_sys/patch_manager.cpp
- src/core/file_sys/registered_cache.cpp
- src/core/file_sys/romfs.cpp
- src/core/file_sys/vfs_cached.cpp
- src/core/file_sys/vfs_cached.h
- src/core/file_sys/vfs_concat.cpp
- src/core/file_sys/vfs_concat.h
- src/core/file_sys/vfs_layered.cpp
Somewhat improves romfs build performance due to code refactoring that gets rid of unnecessary string copying. Also fixes #11724 (circular reference formed in RomFSBuildContext).
> fsmitm_romfsbuild: avoid unnecessary copies of vfs pointers

- src/core/hle/service/acc/acc.cpp
- src/core/hle/service/hle_ipc.cpp
- src/core/hle/service/hle_ipc.h
- src/core/hle/service/prepo/prepo.cpp
In some rare cases both buffer descriptors A and X are available under the same index. This was the case with `StoreWithImage` and `SaveReportWithUser`.
This PR addresses this issue by letting them be accessed directly. I also added a warning log to help identify this issue on the rest of the codebase as it's probably an error.
> service: hle: Allow to access read buffer A and X directly

- src/core/hle/kernel/k_process.cpp
Fixes boot crash on Super Mario Bros Wonder
> kernel: fix incorrect calculation of used non system memory value

- src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
- src/shader_recompiler/backend/spirv/spirv_emit_context.h
- src/shader_recompiler/profile.h
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
Unfortunately it seems like Maxwell and Pascal cards have broken robust support, or something else strange is happening in Yuzu preventing it from working correctly. Crash Team Racing Nitro Fueled uses wildly invalid buffer indexes (values like 0x3D00001C), and they should just return 0 with robust enabled on the device, but Maxwell seems to instead just % the index with the buffer size, or & it with at least 0x10000 or something, and is returning "valid" results even with large indexes. 0x3D00001C returns the same value as 0x1C. No bits above bit 16 affect the returned result, so 0x20000 and above.
This PR also changes the arithmetic shifts to logical, since we don't want negative indexes, which also affects CTR.
I feel like there's something else strange going on in our shaders or their …
> Manually robust on Maxwell and earlier

- src/common/thread.cpp
Available in Windows 10 1607+, and our minimum requirement is already 1809+
> common: use SetThreadDescription API for thread names

- src/shader_recompiler/backend/glsl/emit_glsl.cpp
- src/shader_recompiler/backend/glsl/emit_glsl_warp.cpp
`readInvocationARB` needs all participating lanes to be active to return valid results if that lane's index is to be read from. The previous `shfl_in_bounds` condition could mask some lanes from participating, causing the data read from their invocation to be undefined.
Instead, the `shfl_in_bounds` check should happen after all lanes participate in `readInvocationARB` to avoid undefined behavior.
Verified to fix previously failing nxgpucatch tests. Likely fixes graphical corruption in some titles.
> emit_glsl_warp: Fix shfl_in_bounds conditional

- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/config.h
- src/yuzu/configuration/configure_hotkeys.cpp
Toggle Renderdoc Capture was missing. I also patched the code so it won't crash in case this error happens as well.
> yuzu: fix restore shortcuts button

- src/core/hle/service/hle_ipc.cpp
Needed for IScreenShotService::SaveEditedScreenShotEx1. This function seems to be the first one to have three buffer index. I'm not sure if this change is correct or not but works perfectly fine.
```
const auto application_data_buffer = ctx.ReadBuffer(0);
const auto image_data_buffer = ctx.ReadBuffer(1);
const auto thumbnail_image_data_buffer = ctx.ReadBuffer(2);
```
> service: ipc: Add third read buffer index

- src/video_core/vulkan_common/vulkan_wrapper.cpp
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkApplicationInfo.html
> Vulkan 1.0 implementations were required to return `VK_ERROR_INCOMPATIBLE_DRIVER` if `apiVersion` was larger than 1.0. Implementations that support Vulkan 1.1 or later **must** not return `VK_ERROR_INCOMPATIBLE_DRIVER` for any value of `apiVersion`.
...
> The Khronos validation layers will treat `apiVersion` as the highest API version the application targets, and will validate API usage against the minimum of that version and the implementation version (instance or device, depending on context). If an application tries to use functionality from a greater version than this, a validation error will be triggered.
We support features from Vulkan 1.3, and attempt to use them with the logical device, but …
> vulkan_common: use highest API version

- src/yuzu/applets/qt_controller.cpp
- src/yuzu/applets/qt_controller.h
- src/yuzu/configuration/configure_input.cpp
- src/yuzu/configuration/configure_input.h
- src/yuzu/configuration/configure_input_player.h
- Apply changes on Controller configuration of commit 9524d70 to Controller applet
- Fix regression of this previous commit: Enabling a controller in its tab did not activate previous controllers
- Refactor to use same names in both classes
>  yuzu: Improve behavior when clicking on controller box in Controller applet

- src/core/hle/service/nvnflinger/buffer_queue_core.cpp
- src/core/hle/service/nvnflinger/buffer_queue_producer.cpp
Super Mario Bros Wonder switches between double and triple buffered presentation modes in-game and in the world map.
Decreasing the buffer count would almost always freeze, because we would end up freeing a preallocated buffer slot beyond the new max buffer count. This caused the game to continuously retry to dequeue that slot and fail.
This ensures we don't free preallocated slots, and fixes buffer count tracking, preventing the game from freezing when transitioning.
> nvnflinger: fix reporting and freeing of preallocated buffers

- src/input_common/helpers/joycon_driver.cpp
- src/input_common/helpers/joycon_driver.h
Currently switch controllers need to wait for the reply of the controller. This takes time. Games like Mario Wonder love vibration. So you start feeling those little stutters from vibration. We can avoid this by using a queue and just returning a delayed vibration result.
> input_common: joycon: Move vibrations to a queue

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
FindBuffer calls are required to be wrapped in a do/while loop due to the fact that existing buffers can be deleted on resize to accommodate a new overlapping range, which then invalidates the existing buffer ids in that range. When that happens, we need to loop and try to grab new buffer ids for all resources again. This is already done for graphics resources, but is missing for compute.
Also adds a cache lock in DrawTexture which seems to be missing.
> Add missing loop around compute FindBuffer calls

- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Theoretically fixes #11853 by applying the robust workaround to Pascal as well
cc @bowlofspiders
> Manually robust on Pascal and earlier

- src/yuzu/game_list.cpp
- src/yuzu/game_list.h
- src/yuzu/game_list_worker.cpp
- src/yuzu/game_list_worker.h
I experienced seemingly random shutdown crashes about 10% of the time and seemingly duplicated objects in the game list when shutting down games more than 50% of the time. This is another result of the play time PR, which fully reloads the game list on shutdown.
It turns out there is a really annoying behavior of Qt: when an object is disconnected or destroyed, any messages from that object which are still queued in slots (but not yet delivered) will still get delivered. This led to messages from the game list worker, which had just been canceled and destroyed, sending invalid data references to the game list, which would then try to process them and crash.
Unfortunately it is not possible to ensure the signal queue for any given object is empty in Qt, so we change the strategy by …
> qt: fix game list shutdown crash

- src/video_core/renderer_vulkan/vk_state_tracker.cpp
When swizzle is invalidated we need to update the whole viewport state, but we were clobbering the viewport dirty state in this case. Moving these to the second table ensures we track the invalidation correctly.
Fixes #9368
Fixes #8839
> renderer_vulkan: fix viewport swizzle dirty state tracking

- src/common/nvidia_flags.cpp
Force enables the Nvidia OpenGL threaded optimizations using the environment variable flag
> nvidia_flags: Enable GL Threaded optimizations

- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/applets/applet_cabinet.cpp
- src/core/hle/service/hid/controllers/palma.cpp
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hidbus/hidbus_base.cpp
- src/core/hle/service/pctl/pctl_module.cpp
While testing applets I noticed we run out of handles. Make sure to close all KEvents on all services.
> core: Close all KEvents

- src/video_core/renderer_vulkan/vk_swapchain.cpp
This is needed for Android so that the present manager can detect the surface loss condition and retry without getting stuck in an infinite loop.
> renderer_vulkan: ensure exception on surface loss

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
Previously buttons could get stuck when pulling the drawer open
> android: Release touch on input overlay when opening in-game menu

- src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/GameAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/Game.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/GamesViewModel.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/DocumentsTree.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/FileUtil.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/GameHelper.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/GameIconUtils.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/GameMetadata.kt
- src/android/app/src/main/jni/CMakeLists.txt
- src/android/app/src/main/jni/game_metadata.cpp
- src/android/app/src/main/jni/native.cpp
- src/android/app/src/main/jni/native.h
- src/common/fs/fs_android.cpp
- src/common/fs/fs_android.h
- src/common/fs/path_util.cpp
- src/common/string_util.cpp
We were getting logcat spam from incorrect assumptions about how android uri's worked. Here I add the hooks into Kotlin code that let us check for parent paths correctly and prevent the log spam we saw when loading the games list.
This does fix our previous assumption, but in the future I should create an all-encompassing solution where we keep track of each tree uri for the directories that we're allowed to search. We actually can't get the parent of a uri only with a single file's uri. For now if we want the parent of a uri, I just return the uri without changes.
This additionally has some fixes for game metadata parsing that get us all the information we need for a properties page.
> android: Fix URI parsing in native code

- src/yuzu/main.cpp
- src/yuzu/main.h
This simply adds a way of changing the volume by scrolling when hovering over the volume button in the UI without having to click it.
Volume changes faster with longer scroll duration up to a cap.
First time ever contributing to open source so any feedback welcome.
> Implemented wheel event for volume control in VolumeButton

- src/android/app/src/main/res/layout/card_game.xml
Using a material card view to shape the image was just a waste of a layout pass. A shapeable image view does what we want and does it faster.
Also removes the drop shadow underneath the card.
Before - 
After -
> android: Simplify game card layout

- src/core/hle/service/am/am.cpp
- src/core/hle/service/caps/caps_manager.cpp
- src/core/hle/service/caps/caps_manager.h
- src/core/hle/service/caps/caps_ss.cpp
- src/core/hle/service/caps/caps_su.cpp
- src/core/hle/service/caps/caps_su.h
Fixes the regression caused by #11880 and implements `SaveCurrentScreenshot`. This function is a bit more complicated from the others since the game doesn't provide the image data. This allows to take screenshots on `Pokémon Scarlet` on the latest game update.
> service: am: Implement ISelfController::SaveCurrentScreenshot

- src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/Log.kt
- src/android/app/src/main/jni/CMakeLists.txt
- src/android/app/src/main/jni/native.cpp
- src/android/app/src/main/jni/native_log.cpp
Begin logging when the frontend starts like qt and forward all calls to the Log object in the android frontend to the yuzu logging system so we can get information in the yuzu_log.txt file.
This also ensures that the user shares the correct log based on context. If a user has booted a game, closed it, and went to share the log, the most recent log will be shared. If a user had a game crash and goes to share the log, the old log will be shared.
> android: Adjust log lifecycle

- src/core/file_sys/romfs.cpp
- src/core/file_sys/romfs.h
- src/core/hle/service/am/applets/applet_web_browser.cpp
- src/yuzu/main.cpp
Fixes #8905. I've also gone ahead and removed the RomFSExtractionType enum as it would have only ever been used in error...
> romfs: fix extraction of single-directory root

- src/video_core/renderer_vulkan/vk_rasterizer.cpp
This makes logs basically unreadable on games that actually use them.
> renderer_vulkan: minimize transform feedback support log

- src/core/hid/emulated_controller.cpp
- src/core/hid/hid_types.h
- src/core/hle/service/hid/controllers/npad.cpp
While implementing applets a function called `nn::hid::detail::GetNpadPowerInfo` this will throw `nn::detail::UnexpectedDefaultImpl` on any battery value higher than 4. Fix this property by using the apropiarte range.
> core: hid: Fix wrong battery values

- src/core/hle/service/hid/ring_lifo.h
Some how there's a slight chance that GetNextEntryIndex() is called but total_buffer_count is zero. Prevent this from happening at compile time instead.
> service: hid: Ensure GetNextEntryIndex can't fail

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
This adds a quick update that notifies the render surface if there was a change between surface creation and emulation starting.
> android: Update surface parameters on emulation start

- src/core/hle/service/sockets/bsd.cpp
- src/core/hle/service/sockets/bsd.h
Adds helpers that cap the access size to avoid reading and writing off the end of the buffer bounds. Also removes some unconditional UB in SetSockOpt (??) where we tried to read 16 bytes from an 8 byte buffer.
> sockets: use safe access helpers

- src/core/hid/emulated_controller.cpp
- src/core/hid/emulated_controller.h
- src/yuzu/configuration/configure_input.cpp
- src/yuzu/configuration/configure_input_advanced.cpp
- src/yuzu/configuration/configure_input_advanced.h
Previously changing colors didn't take into effect until the configuration window was reopened. This allows to update colors when config is saved.
> core: hid: Signal color updates

- src/core/hle/service/acc/acc.cpp
- src/yuzu/configuration/configure_profile_manager.cpp
Turns out system applets only allow 256x256 images any other size will result in a corrupted image. Resize all image profiles on frontend side as well on core side. Ensuring that the image will be always displayed properly even when the stored image is wrong.
closes #11968
> service: acc: Ensure proper profile size

- src/video_core/renderer_vulkan/vk_rasterizer.cpp
Many OpenGL games allocate and render into a 1080p backbuffer regardless of whether the console state is docked or handheld, and simply adjust the size and location of the region they are rendering to. The final pass flips the image and renders to the bottom of the RT instead of the top, but we were always rendering to the top because we calculated flips based on the viewport height instead of the surface clip height.
> renderer_vulkan: render on bottom of surface clip when flipped

- .github/workflows/android-build.yml
When I was setting up the scripts that Citra used for their android CI, I missed this step in the yml to declare the secrets at the right time.
> ci: android: Declare secrets during build step

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
- src/android/app/src/main/jni/native.cpp
- src/android/app/src/main/jni/native.h
- src/android/app/src/main/res/layout/fragment_emulation.xml
Just a few adjustments that @liamwhite and I wanted for the counter
- Always update the FPS counter regardless of pause state
- Recolor the text to white
- Simplify padding to just use its framelayout's `fitsSystemWindows` attribute and use the padding option directly in the xml view
> android: FPS counter adjustments

- src/yuzu/vk_device_info.cpp
Allocate resources for `test_window` to avoid setting `wsi.render_surface` as nullptr, which causes a crash in Wayland as per [#11941](https://github.com/yuzu-emu/yuzu/issues/11941#issuecomment-1795920846)
Fixes #11941.
> Allocate resources for test window before getting system info

- src/core/hle/service/hid/irs.cpp
- src/core/hle/service/hid/irsensor/clustering_processor.cpp
- src/core/hle/service/hid/irsensor/clustering_processor.h
- src/core/hle/service/hid/irsensor/image_transfer_processor.cpp
- src/core/hle/service/hid/irsensor/moment_processor.cpp
- src/core/hle/service/hid/irsensor/moment_processor.h
Implements the moment image processor. This allows `Trombone Champ` and `WarioWare: Put a lid on it` to be played with the joycon IR sensor.
Note: Other Wario mini games that use IR still require the tera image processor to be functional.
> service: irs: Implement moment image processor

- src/android/app/src/main/res/values/arrays.xml
This doesn't exist and if you clicked it, your region would be set to Taiwan.
> android: Remove "auto" region option

- src/common/settings.cpp
- src/common/settings.h
- src/common/settings_common.h
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_audio.cpp
- src/yuzu/main.cpp
- src/yuzu/uisettings.h
I didn't made an UI category when I fixed the audio setting. Now the setting should be persistent.
> yuzu: Save mute when in background setting

- src/audio_core/sink/cubeb_sink.cpp
- src/audio_core/sink/sdl2_sink.cpp
- src/audio_core/sink/sink_stream.cpp
- src/audio_core/sink/sink_stream.h
On finalization, sink callbacks can get paused with a bunch of stream data still queued. Once the sink callbacks are stopped and will not be called anymore, the renderer might then block forever and prevent shutdown. This fixes a persistent shutdown deadlock on Android.
> audio_core: ignore renderer wait when stream is paused

- src/core/arm/arm_interface.cpp
The process for shutting down a process involves the following, for each thread:
- Mark it as termination requested and apply the DPC flags, and if it is runnable, send an interrupt to all cores with the thread's affinity
- Wait for the thread to exit, if needed
Threads which are runnable and marked as termination-requested are not removed from the scheduling PQ, so they can get scheduled again during termination, despite the core having already cleared the interrupt when a previous thread was terminated. This implies a subtle but important rule that the DPC flags must be checked _before_ returning to user code, or a thread might not get terminated, and cause a deadlock on shutdown.
> core: check for thread dpc before eret

- src/core/core_timing.cpp
- src/core/core_timing.h
This fixes another shutdown crash. System calls ClearPendingEvents on shutdown, even though the timing thread may still be concurrently popping items from the event queue.
> core_timing: lock event queue access

- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/GameAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/GameIconUtils.kt
If the coil loader ever got stuck when creating a dynamic shortcut icon, the app would freeze. This would happen most notably when booting nca format games. This pushes that process to a separate coroutine that can be cancelled by the main activity's lifecycle.
> android: Use suspend function for creating dynamic shortcuts

- src/android/app/src/main/jni/uisettings.h
After getting several complaints from devs and users alike, this is being disabled by default on new configs
> android: Disable PiP by default

- src/common/settings_input.cpp
- src/common/settings_input.h
- src/core/hid/emulated_controller.cpp
- src/core/hle/service/hid/controllers/npad.cpp
- src/input_common/drivers/gc_adapter.cpp
- src/input_common/drivers/joycon.cpp
- src/input_common/drivers/sdl_driver.cpp
- src/input_common/drivers/sdl_driver.h
- src/input_common/drivers/udp_client.cpp
- src/yuzu/configuration/config.cpp
- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/configuration/configure_input_player.ui
- src/yuzu/configuration/configure_input_player_widget.cpp
Plug your leaks! Now you can map SL and SR buttons on dual joycon. Allowing this wario minigame to be playable.
> core: hid: Split SL and SR buttons

- src/core/CMakeLists.txt
- src/core/hle/service/hid/controllers/controller_base.cpp
- src/core/hle/service/hid/controllers/controller_base.h
- src/core/hle/service/hid/controllers/npad.h
- src/core/hle/service/hid/controllers/palma.cpp
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid_firmware_settings.cpp
- src/core/hle/service/hid/hid_firmware_settings.h
- src/core/hle/service/hid/hid_server.cpp
- src/core/hle/service/hid/hid_server.h
- src/core/hle/service/hid/resource_manager.cpp
- src/core/hle/service/hid/resource_manager.h
Next one on the list. Introduce hid firmware settings. To make use of the class I updated the activate calls to 16.0.0 for all hid types.  Right now there's no difference between managed and unmanaged config. But that will change as I keep updating the service.
> service: hid: Introduce firmware settings and update activate controller calls

- src/core/hle/service/nvnflinger/buffer_queue_consumer.cpp
- src/core/hle/service/nvnflinger/buffer_queue_consumer.h
- src/core/hle/service/nvnflinger/buffer_queue_core.cpp
- src/core/hle/service/nvnflinger/buffer_queue_core.h
- src/core/hle/service/nvnflinger/consumer_base.cpp
- src/core/hle/service/nvnflinger/consumer_base.h
- src/core/hle/service/nvnflinger/nvnflinger.cpp
- src/core/hle/service/nvnflinger/nvnflinger.h
Companion PR to #11912. Graphic buffers get leaked on exit because of a reference cycle, and the way Android breaks this cycle is requiring the consumer to explicitly disconnect itself when the system is ready to shut down.
> nvnflinger: implement consumer abandonment

- src/core/CMakeLists.txt
- src/core/hle/service/nvnflinger/buffer_item.h
- src/core/hle/service/nvnflinger/buffer_queue_consumer.cpp
- src/core/hle/service/nvnflinger/buffer_queue_consumer.h
- src/core/hle/service/nvnflinger/buffer_queue_producer.cpp
- src/core/hle/service/nvnflinger/buffer_queue_producer.h
- src/core/hle/service/nvnflinger/buffer_slot.h
- src/core/hle/service/nvnflinger/fb_share_buffer_manager.cpp
- src/core/hle/service/nvnflinger/status.h
- src/core/hle/service/nvnflinger/ui/graphic_buffer.cpp
- src/core/hle/service/nvnflinger/ui/graphic_buffer.h
- src/core/hle/service/vi/display/vi_display.cpp
While investigating #11900, I found that the map handles are actually opened when preallocated buffer slots are allocated and held until they are cleared. This matches that behavior and adds a wrapper with better aesthetics.
> nvnflinger: use graphic buffer lifetime for map handle

- src/audio_core/adsp/apps/opus/opus_multistream_decode_object.cpp
- src/audio_core/opus/decoder.cpp
This was regressed by #11460 and was _almost_ fixed by #11952, except the code was also duplicated in this location for some reason. At some point these blocks need to be deduplicated so that there is one place for validation.
Fixes Super Mario RPG background audio.
> opus: fix stereo stream count check in multistream decoder object

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/engines/maxwell_3d.cpp
Fixes some regressions in Pokemon Scarlet.
thanks to @ameerj for figuring it out!
> Buffer Cache: Eliminate clears on Indirect buffers

- src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
- src/video_core/renderer_opengl/gl_graphics_pipeline.h
GL_SEPARATE_ATTRIBS only applies when multiple buffers are being used, else GL_INTERLEAVED_ATTRIBS handles the cases for a single buffer with potentially more than one attribute
closes #11680
closes  #11888
> gl_graphics_pipeline: GLASM: Fix transform feedback attribs buffer mode

- src/shader_recompiler/CMakeLists.txt
- src/shader_recompiler/frontend/maxwell/translate_program.cpp
- src/shader_recompiler/ir_opt/passes.h
- src/shader_recompiler/ir_opt/vendor_workaround_pass.cpp
Workaround to an odd Nvidia bug that should be harmless to apply everywhere.
Basically, in the following pattern:
```glsl
uint low = uint(bitfieldExtract(some_number, 0, 16));
low <<= 16U;
uint high = uint(bitfieldExtract(some_number, 16, 16));
uint swapped = low + high;
```
Replace the addition with a bitwise or:
```glsl
uint swapped = low | high;
```
Closes #12063
> shader_recompiler: add byteswap pattern workaround for Nvidia

- src/video_core/renderer_vulkan/vk_query_cache.cpp
This should fix the crashes on Turnip on games that need query summing like Red Dead Redemption and LM3
> Query Cache: Disable write syncing on Android

- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/vulkan_common/vulkan_device.cpp
- src/video_core/vulkan_common/vulkan_device.h
Currently, we have only 1 pipeline worker in Android. Thus we have way too much stutter when making shaders. Since NCE, we can be a bit more generous. This also adds a check for drivers that have broken parallel shader compiling.
> Vulkan: Be more generous with pipeline workers for Android

- src/shader_recompiler/backend/spirv/emit_spirv.cpp
- src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
- src/shader_recompiler/profile.h
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/vulkan_common/vulkan_device.h
Fixes a bunch of shader compiler crashes on Mali
> renderer_vulkan: ignore viewport stores on non-supporting drivers

- src/core/hle/service/hid/hid_server.cpp
Ensures the proper initialization of the IActiveVibrationDeviceList. By using GetResourceManager() instead of resource_manager, we make sure that the IActiveVibrationDeviceListis initialized before it's used, preventing potential null issues.
Fixes #12088
Change suggested by @german77
> service: hid: Ensure resource manager is initialized

- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/Game.kt
- src/android/app/src/main/res/layout/fragment_search.xml
Additionally fixes an issue where all homebrew apps would appear in the recently played list even though you only played one
> android: Select recently played games by default in search tab

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/InstallableFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
- src/android/app/src/main/res/values/strings.xml
The share sheet was causing problems for people who just wanted to back up their saves and didn't have a file manager to copy the zip with. Just saving to a selected location makes things easier for everyone.
> android: Use file picker intent for save exporter

- src/core/hid/hid_types.h
- src/core/hle/service/am/am.cpp
- src/core/hle/service/am/am.h
- src/core/hle/service/am/applets/applet_controller.h
- src/core/hle/service/btm/btm.cpp
- src/core/hle/service/hid/controllers/npad.cpp
- src/core/hle/service/hid/controllers/npad.h
- src/core/hle/service/hid/hid_server.cpp
- src/core/hle/service/hid/hid_system_server.cpp
- src/core/hle/service/hid/hid_system_server.h
- src/core/hle/service/ldn/ldn.cpp
- src/core/hle/service/set/set_sys.cpp
- src/core/hle/service/set/set_sys.h
- src/yuzu/main.cpp
- src/yuzu/main.h
- src/yuzu/main.ui
With a lot of help from @german77 I managed to implement the qlaunch version of the controller applet. 
It's not super useful for now but it's a good start to get this running in games.
> Implemented qlaunch version of the controller applet

- src/yuzu/CMakeLists.txt
- src/yuzu/configuration/shared_translation.cpp
Qt can't parse tr called within a macro, so we must call it on each string. Qt still seems unhappy with the way I called tr, but it's getting the strings now nevertheless.
To figure this out, I had to create a workaround so that lupdate would run on my system. The path I created results in a number of warnings across the Qt frontend. I have no ability to tell if these were existing already or not, or if this is an issue with the way I'm calling lupdate.
> shared_translation: Call tr more directly

- dist/languages/.tx/config
This should allow android strings to be automatically transferred between transifex and the app just like Qt
> translations: Add android translations to transifex config

- src/yuzu/configuration/shared_widget.cpp
- src/yuzu/game_list_worker.cpp
Implicit `this` is deprecated in C++20.
> Explicit this

- src/video_core/query_cache/query_cache.h
This gets hits a lot on Turnip drivers, which causes a hard crash.
> query_cache: demote report synced unreachable to assert

- src/core/hid/emulated_controller.cpp
- src/core/hid/emulated_controller.h
Lately hid isn't destroyed in the correct order. Sometimes before other services like nfc. To prevent hard crashes I simply check if input is initialized before attempting to send any command to the controllers.
> core: hid: Ensure output devices are initialized

- src/video_core/vulkan_common/vulkan_device.cpp
A gentle reminder that if you are on a power or thermally limited device, do not enable the option to force maximum clocks.
> renderer_vulkan: exclude steam deck oled from force max clock setting

- src/core/hle/service/set/set_sys.cpp
- src/core/hle/service/set/set_sys.h
- src/yuzu/main.cpp
- src/yuzu/main.h
Since FW version make a difference in system applets. It's actually useful now to display the current firmware version.
> yuzu: Display firmware version

- src/core/hle/service/am/applets/applet_cabinet.cpp
When I made the service accurate for the system cabinet applet I removed all hard coded values. This broke our hle implementation because the service now expects to have a mii on the request. Fix this by creating said mii.
> service: am: Create random mii for cabinet applet

- src/common/settings.h
- src/video_core/CMakeLists.txt
- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/buffer_cache/buffer_cache_base.h
- src/video_core/buffer_cache/usage_tracker.h
- src/video_core/renderer_opengl/gl_buffer_cache.cpp
- src/video_core/renderer_opengl/gl_buffer_cache.h
- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
- src/video_core/renderer_vulkan/vk_buffer_cache.h
- src/video_core/renderer_vulkan/vk_master_semaphore.cpp
- src/video_core/renderer_vulkan/vk_master_semaphore.h
- src/video_core/renderer_vulkan/vk_scheduler.cpp
- src/video_core/renderer_vulkan/vk_scheduler.h
- src/video_core/renderer_vulkan/vk_smaa.cpp
- src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
- src/video_core/texture_cache/slot_vector.h
- src/video_core/vulkan_common/vulkan_wrapper.h
- src/yuzu/configuration/configure_debug.cpp
- src/yuzu/configuration/configure_debug.ui
It can be often observed in renderdoc that certain copies from the stream buffer will be performed while rendering, breaking the renderpass. This is expensive on mobile GPUs, especially on yuzu where renderpass break incurs a full pipeline barrier. So this PR adds a mechanism to track buffer usage throught the frame and if the buffer has not been used before the copy can be reordered into an upload command buffer that is executed before any rendering commands.
Usage is any operation that reads or writes to the buffer. Initially I used an interval map for tracking the ranges but this reduced performance quite a bit especially in hot paths like vertex buffer binding. So instead the buffer is tracked using a bit tracker with 64 byte granularity. The intention is to hopefully improve the …
> renderer_vulkan: Introduce separate cmd buffer for uploads

- src/core/hle/service/am/applets/applet_cabinet.cpp
- src/core/hle/service/mii/types/ver3_store_data.cpp
- src/core/hle/service/nfc/common/device.cpp
- src/core/hle/service/nfc/common/device.h
Games like SSBU crash if you load an amiibo with invalid mii data. Since mii service is implemented now we can actually check the integrity of the mii. This change returns a corrupted error if mii is invalid. If a backup exist you can use the applet to restore it to be functional again.
I also deleted a duplicated function. Probably a leftover from a rebase. 
Big **WARNING** I made a huge mistake. All mii amiibo registered on yuzu in the last few months are considered corrupted. Should be fixable by using the restore function on the amiibo applet.
> service: nfc: Validate mii data

- .github/workflows/verify.yml
It's not optimal that this is not arm64 (there is no arm64 runner yet), but this should prevent it from regressing in the future.
> Add mac workflow

- externals/CMakeLists.txt
- src/common/CMakeLists.txt
Regressed by #12223. gamemode itself is Linux-only but yuzu doesn't bundle gamemode. Avoid extra conditionals by keeping the support even if it will never be used.
> cmake: unbreak build on FreeBSD by re-enabling gamemode

- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/vulkan_common/vulkan_device.cpp
vkCmdSetVertexInputEXT does not work on every Qualcomm driver that supports it: the vertex input state is not persisted in the command buffer, so when you move to the next draw in the same command buffer and don't issue another command to update the state, it behaves as if there are no vertex bindings available. I'm pretty sure this behavior would not pass dEQP, and breaks basically everything except rendering demos.
Fixes #12215
> renderer_vulkan: exclude more qcom drivers from extensions

- src/video_core/renderer_vulkan/vk_blit_screen.cpp
PR https://github.com/yuzu-emu/yuzu/pull/10670 changed the format of the AA image_views but the renderpass format wasn't updated accordingly. This caused qcom proprietary drivers to break.
| Before | After |
|---|---|
Fixes https://github.com/yuzu-emu/yuzu/issues/10730
Fixes #12247
> vk_blit_screen: Use correct format for fxaa renderpass

- src/android/app/src/main/jni/native.cpp
Should fix the issue where games wouldn't boot if they were loaded after installing an update (requiring an app restart).
> android: Don't reload filesystem on update install

- src/yuzu/configuration/qt_config.cpp
Fixes a bug where language selection wouldn't save properly
> frontend_common: Use optional for language default

- src/core/arm/nce/patcher.cpp
When a single module has a pre-text patch, the kernel will assign the pc to be the first instruction of the patch section. Make this instruction be a jump to the module body.
> nce: fix pre-text patch for single modules

- src/common/settings.h
Fixes a bug where we weren't setting the default value for CPU backend correctly
> settings: Enable NCE by default on capable systems

- src/core/CMakeLists.txt
- src/core/hle/service/hid/controllers/applet_resource.cpp
- src/core/hle/service/hid/controllers/applet_resource.h
- src/core/hle/service/hid/errors.h
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid_server.cpp
- src/core/hle/service/hid/hid_system_server.cpp
- src/core/hle/service/hid/hid_system_server.h
- src/core/hle/service/hid/resource_manager.cpp
- src/core/hle/service/hid/resource_manager.h
This is the first actual accuracy change of project leviathan. Here we start to actually emulate `AppletResource`. Now we should care about the actual `AppletResourceUserId`(aruid) sent by games. While this change is pretty barebones I will be completing this implementation as I start migrating controllers features to use aruid values.
These changes are necessary to handle multiprocess properly in the future.
> service: hid: Introduce proper AppletResource emulation

- src/common/settings.cpp
Clarify when NCE is being auto-disabled due to disabled fastmem
> settings: Clearer NCE error messages

- src/core/hle/service/nvnflinger/fb_share_buffer_manager.cpp
Fixes assertion failures in programs using shared layers
> fbshare: set external format correctly

- src/core/file_sys/savedata_factory.cpp
- src/core/file_sys/savedata_factory.h
- src/core/hle/service/filesystem/fsp_srv.cpp
Fixes another startup crash in Portal 2.
> fs: don't enumerate hidden savedata size file

- src/core/hle/service/hid/controllers/applet_resource.cpp
- src/core/hle/service/hid/controllers/applet_resource.h
- src/core/hle/service/hid/errors.h
- src/core/hle/service/hid/hid_server.cpp
- src/core/hle/service/hid/resource_manager.cpp
- src/core/hle/service/hid/resource_manager.h
Any application run through hbl will fail at the moment. This PR fixes the issue by improving CreateAppletResource and more importantly releasing the applet resource.
This allow running multiple programs under the same program id.
> service: hid: Improve CreateAppletResource implementation and free resources

- src/android/app/src/main/jni/native.cpp
- src/android/app/src/main/jni/native.h
- src/core/core.cpp
- src/core/core.h
- src/yuzu/applets/qt_profile_select.cpp
- src/yuzu/applets/qt_profile_select.h
- src/yuzu/configuration/configure_profile_manager.cpp
- src/yuzu/configuration/configure_profile_manager.h
- src/yuzu/main.cpp
- src/yuzu/multiplayer/lobby.cpp
- src/yuzu/multiplayer/lobby.h
- src/yuzu/play_time_manager.cpp
- src/yuzu/play_time_manager.h
I counted around 13 different instances of the profile manager. This probably fixes all weirdness we have with this service specially randomly loosing your user file.
> core: Use single instance of profile manager

- vcpkg.json
Should fix compiling on the latest version of MSVC.
Fixes https://github.com/yuzu-emu/yuzu/issues/12270.
> vcpkg: Update fmt to 10.1.1

- .github/workflows/verify.yml
This got broken at some point today, so that when you run `brew install python` it now returns an error. Homebrew [explicitly rejected](https://github.com/Homebrew/brew/issues/1742) an option to force link during install so I guess this is the approach we'll be using.
> ci: fix homebrew installation issue in actions runner images

- src/common/host_memory.cpp
- src/common/host_memory.h
- src/core/hle/kernel/k_memory_manager.cpp
- src/core/hle/kernel/k_page_table_base.cpp
On Linux (and by extension Android) we can take advantage of the MADV_REMOVE extension to madvise, which deletes the backing memory and makes future reads return zero. This decreases boot time by more than a full second on all Linux-based platforms and also prevents us from needing to have 3GB available immediately on boot - the needed memory can be allocated on demand.
I could not find a way to implement this on Windows. There is simply no way to decommit a portion of a page-file backed mapping, which we use in order to support memory aliasing. This is documented in the API:
> After a page from the reserved range is committed, it cannot be freed or decommitted by calling VirtualFree.
> common: use memory holepunching when clearing memory

- src/tests/video_core/memory_tracker.cpp
- src/video_core/buffer_cache/word_manager.h
- src/video_core/rasterizer_accelerated.cpp
- src/video_core/rasterizer_accelerated.h
- src/video_core/rasterizer_interface.h
- src/video_core/shader_cache.cpp
- src/video_core/texture_cache/texture_cache.h
This saves about 256MB of prefaulted memory in every single guest program, and makes startup a bit faster. The atomic semantics are not needed because this function is ~~only ever called from a locked context (and since it can modify the page table, it wouldn't have worked if it was unlocked anyway).~~ this is not true when NCE is enabled, so I have added a lock.
Should be tested to ensure the performance and accuracy is the same as before.
> video_core: use interval map for page count tracking

- src/common/fs/path_util.cpp
- src/common/fs/path_util.h
- src/core/file_sys/vfs.cpp
- src/core/file_sys/vfs_real.cpp
- src/core/hle/service/filesystem/filesystem.cpp
Authored by BreadFish64. Reimplemented #10692 with permission, and creates a vector of string_views instead of using range-v3.
> Improve path splitting speed

- src/common/common_funcs.h
- src/core/CMakeLists.txt
- src/core/hle/service/set/appln_settings.cpp
- src/core/hle/service/set/appln_settings.h
- src/core/hle/service/set/device_settings.cpp
- src/core/hle/service/set/device_settings.h
- src/core/hle/service/set/private_settings.cpp
- src/core/hle/service/set/private_settings.h
- src/core/hle/service/set/set.h
- src/core/hle/service/set/set_sys.cpp
- src/core/hle/service/set/set_sys.h
- src/core/hle/service/set/system_settings.cpp
- src/core/hle/service/set/system_settings.h
This saves the system setting titles and re-loads them across game boots, so we can save out these settings and have their changes persist rather than resetting to a default every time. Includes a version in each file so we can force settings back to default if we change the struct sizes or want to initialise them with new defaults.
> Make system settings persistent across boots

- src/core/hle/service/nvnflinger/fb_share_buffer_manager.cpp
- src/core/hle/service/nvnflinger/nvnflinger.cpp
- src/core/hle/service/nvnflinger/nvnflinger.h
- src/core/hle/service/vi/display/vi_display.cpp
- src/core/hle/service/vi/display/vi_display.h
- src/core/hle/service/vi/layer/vi_layer.cpp
- src/core/hle/service/vi/layer/vi_layer.h
- src/core/hle/service/vi/vi.cpp
When combined with the previous two fixes, Portal 2 can now go in game. The vi service implementation could use an overhaul.
> vi: fix confusion between closing and destroying layers

- src/video_core/renderer_vulkan/vk_present_manager.cpp
- src/video_core/renderer_vulkan/vk_present_manager.h
For various reasons we can only allow up to 6 frames to be processed at any given time. However, with async presentation enabled (especially on Android), slow rendering can cause the present queue to grow up to the maximum number of presentation images, which might result in the descriptor queue data getting clobbered and subsequent driver crashes.
Some users have previously worked around this by changing the speed limit setting, which slows down the presentation rate and can prevent these crashes. This should remove the need to do that.
Here, we force presentation to wait before the maximum number of frames which can be enqueued is reached. This should also help with input lag a bit.
> renderer_vulkan: cap async presentation frame count

- src/core/hle/service/set/appln_settings.h
- src/core/hle/service/set/device_settings.h
CI passed because it uses 12, but this isn't indirectly included in libstdc++ 13 anymore, which gave me a build failure
> set: add cstddef for offsetof macro

- src/common/fs/path_util.cpp
- src/common/fs/path_util.h
This resolves a lifetime issue where a reference to a temporary would be returned. After checking the Android ifdefs, this seems to be the only case where this happened.
> path_util: copy output for GetParentPath

- src/audio_core/sink/cubeb_sink.cpp
- src/audio_core/sink/sdl2_sink.cpp
- src/audio_core/sink/sink.h
- src/audio_core/sink/sink_stream.cpp
- src/core/hle/service/audio/audren_u.cpp
Games usually create their audio output using the max number of channels (6), and then afterwards query the active output device for how many channels it's actually outputting, and then they send data to match that. So a game may open audio out with 6 channels, query the device and find it only supports 2 channels, and then send 6 channels of data, but with only 2 of the channels filled, and leaving the other 4 as 0, silence.
In the case that your host output only supports 2 channels, GetActiveChannelCount will return 2, and Tales of Vesperia seems to struggle with this. It opens 6 channel output which we can't control as far as I know, but then we return 2 channels from GetActiveChannelCount back to it, and Tales of Vesperia seems to mis-calculate its audio data rate due to the 6-2 …
> Have GetActiveChannelCount return the system channels instead of host device channels

- src/yuzu/configuration/configure_ui.cpp
- src/yuzu/configuration/qt_config.cpp
- src/yuzu/main.cpp
- src/yuzu/uisettings.h
Symbols path seems unused. Language wasn't saved with default value but it was read with one. This made yuzu to load the default value every time. This change ensures it will be saved/read properly.
> yuzu: Make language persistent and remove symbols_path

- src/core/hle/service/nvnflinger/buffer_queue_consumer.cpp
- src/core/hle/service/nvnflinger/buffer_queue_core.cpp
- src/core/hle/service/nvnflinger/buffer_slot.h
Previously, buffers would instantly transition from queued to free after being flipped. Somehow, this didn't break anything.
> nvnflinger: mark buffer as acquired when acquired

- src/video_core/renderer_opengl/gl_buffer_cache.cpp
- src/video_core/renderer_opengl/gl_buffer_cache.h
- src/video_core/renderer_opengl/gl_device.cpp
- src/video_core/renderer_opengl/gl_device.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/renderer_opengl.cpp
Partial revert of #12094 
Nvidia's driver fails to performs tfb in cases where the same buffer is bound as a vertex buffer and tfb buffer in the same draw call.
I only repro'd on homebrew tests, but using the `NV_vertex_buffer_unified_memory` works around this and fixes the issue.
> gl_buffer_cache: Reintroduce NV_vertex_buffer_unified_memory 

- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
- src/video_core/vulkan_common/vulkan_device.cpp
PR #11471 changed yuzu to be able to respect the maximum vertex binding count of the driver. There was a minor issue in how this was implemented, which is now fixed.
Bizarrely, respecting the maximum binding count and binding all 16 buffers causes Turnip on a610 to device loss on any guest program, when using either vkCmdBindVertexBuffers2EXT or vkCmdBindVertexBuffers - it seems that you _have_ to use the API incorrectly and bind too many buffers to avoid this. I didn't try binding the inputs one at a time, but suspect it might also work.
This needs to be reported to mesa.
> renderer_vulkan: work around turnip binding bug in a610

- src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
- src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
- src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
- src/shader_recompiler/profile.h
- src/shader_recompiler/shader_info.h
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/vulkan_common/vulkan_device.h
Values of the gl_ClipDistance array which are not written to are considered undefined. Most drivers seem to treat unwritten values as zero, but radv does not. This fixes rendering with radv in Portal.
>  shader_recompiler: use minimal clip distance array 

- src/core/arm/nce/interpreter_visitor.cpp
- src/core/arm/nce/visitor_base.h
> nce: hide shadowing warnings from dynarmic headers

- src/video_core/renderer_vulkan/vk_query_cache.cpp
There's an assumption that ResetCounter() would be called before reporting the counter value, but that's not always the case. 
When ResetCounter() is not called, `last_accumulation_checkpoint` would not be updated, passing in 0 as the `max_accumulation_base` to the prefix sum shader...
https://github.com/yuzu-emu/yuzu/blob/b8c50276869aa98bc3cf2622a18c08cf1fb66315/src/video_core/host_shaders/queries_prefix_scan_sum.comp#L107
This happens in Luigi's Mansion 3
> vk_query_cache: Fix prefix sum max_accumulation_limit logic

- CMakeLists.txt
- src/video_core/vulkan_common/vulkan_wrapper.cpp
Similar #10017. Video encoding is [out of beta](https://www.khronos.org/blog/khronos-finalizes-vulkan-video-extensions-for-accelerated-h.264-and-h.265-encode).
> externals: update Vulkan-Headers to v1.3.274

- src/core/hle/service/hid/hid_server.cpp
Our object creation is a bit messed up while I'm rewriting hid. Npad is really big, it will take me a few weeks to get something together. Patch this function to avoid breaking games like rocket league.
> service: hid: Fix crash on InitializeVibrationDevice

- src/yuzu/configuration/configure_graphics.cpp
- src/yuzu/configuration/configure_graphics.h
Properly integrates the per-game vsync combobox into the qt gui after I had accidentally enabled it during #12335
> qt: settings: Fix per-game vsync combobox

- src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
- src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
- src/shader_recompiler/backend/spirv/spirv_emit_context.h
- src/shader_recompiler/environment.h
- src/shader_recompiler/ir_opt/texture_pass.cpp
- src/shader_recompiler/shader_info.h
- src/video_core/renderer_opengl/gl_shader_cache.cpp
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/shader_environment.cpp
- src/video_core/shader_environment.h
This is a redo of #12407
It turns out that binding any float image type with a mismatched sampler type is actually not spec compliant (thanks to DadSchoorse🐸 on the mesa issue tracker for pointing this out:
> If a VkImageView is accessed as a result of this command, then the numeric type of the image view’s format and the Sampled Type operand of the OpTypeImage must match
This means we should make the sampled type be float for all pixel formats which are not explicitly integer. I now add the pixel format to the shader cache (and have increased the cache version, so this causes an invalidation) and test the pixel format when compiling image ops. I have also pushed required conversion into the backend to make the IR cleaner--we only want to get U32x4 on the output.
Fixes rendering on mobile …
> shader_recompiler: use float image operations on load/store when required

- src/video_core/renderer_vulkan/vk_buffer_cache.cpp
- src/video_core/renderer_vulkan/vk_buffer_cache.h
Works around yet another crash due to the lack of support for nullDescriptor.
> renderer_vulkan: don't pass null view when nullDescriptor is not supported

- src/video_core/engines/maxwell_3d.cpp
- src/video_core/query_cache.h
- src/video_core/renderer_opengl/gl_query_cache.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
Brings the counter query accuracy close to what the Vulkan side has.
Fixes shadows in Metroid Prime:
> OpenGL: Add GL_PRIMITIVES_GENERATED and GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN queries

- src/video_core/macro/macro_hle.cpp
- src/video_core/rasterizer_interface.h
- src/video_core/renderer_opengl/gl_buffer_cache.cpp
- src/video_core/renderer_opengl/gl_buffer_cache.h
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_opengl/gl_rasterizer.h
- src/video_core/renderer_opengl/gl_resource_manager.cpp
- src/video_core/renderer_opengl/gl_resource_manager.h
Should be functionally equivalent to Vulkan's `DrawIndirectByteCount`. 
The macro execution takes a slightly different path for OpenGL since the TFB byte count is not readily available.
Fixes particles in XC3
https://github.com/yuzu-emu/yuzu/assets/52414509/db4e96bc-221f-4947-bd38-f4954f7880ff
> gl_rasterizer: Implement DrawTransformFeedback macro

- src/video_core/vulkan_common/vulkan_device.cpp
This loop https://github.com/yuzu-emu/yuzu/blob/91290b9be4e99a9890c6545e327f600484e39914/src/video_core/renderer_vulkan/vk_texture_cache.cpp#L858-L871 enumerates all of the Maxwell-supported formats on the device to see which ones are view-compatible. Doing this will generally cause assertion failures on non-Nvidia devices because they don't support all the same formats. This should just be logged as an error instead.
> renderer_vulkan: demote format assert to error log

- src/video_core/vulkan_common/vulkan_wrapper.cpp
This isn't supported on the a6xx proprietary driver natively and is emulated by the validation layer. When not using the validation layer, this causes a crash with a debugging tool attached. (Not relevant for normal use)
> renderer_vulkan: skip SetObjectNameEXT on unsupported driver

- src/common/assert.cpp
- src/common/logging/backend.cpp
- src/common/logging/backend.h
See citra-emu/citra#7146 for more details.
Most of the time when an assert fails, Citra crashes without flushing the contents of the log file, leaving us with an incomplete log without the reason for assert.
>  Port citra-emu/citra#7146: "assert/logging: Stop the logging thread and flush the backends before crashing"

- src/core/hle/kernel/k_auto_object_container.cpp
- src/core/hle/kernel/k_auto_object_container.h
- src/core/hle/kernel/k_transfer_memory.h
Until we have the framework in place to have deferred object destruction, this needs to use an OS mutex instead. Should fix an extremely rare shutdown crash in EndWait.
> kernel: use simple mutex for object list container

- src/video_core/texture_cache/decode_bc.cpp
- src/video_core/texture_cache/decode_bc.h
- src/video_core/texture_cache/util.cpp
For compressed textures info.pitch is the amount of bytes between one row of compressed blocks to another. Previously it was always divided by the block size, which results in the number of blocks per row, which works okay for uncompressed formats that have 1x1 blocks but breaks for compressed ones. To achieve the result Vulkan expects, which is the number of texels per row (with possible padding) we multiply with block_width first before dividing because:
buffer_row_length = pitch / (block_height * bpp) = pitch * block_width / (block_width * block_height * bpp) = pitch * block_width / block_size;
While at it, I've also adjusted the software BCn decoder to take the pitch into account so it can work with non tightly packed images.
| Before | After |
|---|---|
Fixes …
> video_core: Fix buffer_row_length for linear compressed textures

- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/IntSetting.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/view/SettingsItem.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsFragmentPresenter.kt
- src/android/app/src/main/res/layout/list_item_setting_switch.xml
- src/android/app/src/main/res/values/arrays.xml
- src/android/app/src/main/res/values/strings.xml
Had a couple requests for these tweaks
- Hide fastmem toggle when CPU Debugging is disabled
- Expose anisotropic filtering setting
- Center switch setting title when no description is present
> android: Small settings tweaks

- src/yuzu/main.cpp
On compliant Wayland compositors windows are matched to their .desktop files by comparing the appId window property to the name of the .desktop file without the .deskop extension.
Qt5/6 by default set this property to the basename of the binary (IE `yuzu`) which does not match the expected value `org.yuzu_emu.yuzu`. We can fix this and fix window associations on compliant compositors (like Plasma) by using the `setDesktopFileName()` function which will set the appId window property. This is a no-op on X11 so is safe to be ran without guards.
> Fix Wayland appId

- src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
- src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp
This PR prints the errors reported by SDL's `SDL_GetError` in yuzu-cmd in some places where it previously didn't.
> Report more SDL errors

- .ci/scripts/android/build.sh
- .ci/scripts/android/upload.sh
Makes it so that the yuzu-emu/yuzu repo will generate RelWithDebInfo builds and yuzu-emu/yuzu-android will generate Release builds.
Allows you to install builds from PRs alongside release builds.
> actions: android: Build relWithDebInfo on main repo

- src/core/CMakeLists.txt
- src/core/hle/service/jit/jit.cpp
- src/core/hle/service/jit/jit_code_memory.cpp
- src/core/hle/service/jit/jit_code_memory.h
This allows the N64 games to work with NCE
> jit: use code memory handles correctly

- src/core/file_sys/ips_layer.cpp
Fixes #12500 (based on crash stack - can't repro issue with unicode in cheat)
> ips_layer: prevent out of bounds access with offset exceeding module size

- src/common/CMakeLists.txt
- src/common/heap_tracker.cpp
- src/common/heap_tracker.h
- src/common/host_memory.cpp
- src/common/host_memory.h
- src/core/CMakeLists.txt
- src/core/arm/dynarmic/arm_dynarmic.cpp
- src/core/arm/dynarmic/arm_dynarmic.h
- src/core/arm/dynarmic/arm_dynarmic_32.cpp
- src/core/arm/dynarmic/arm_dynarmic_64.cpp
- src/core/hle/kernel/k_page_table_base.cpp
- src/core/hle/kernel/k_page_table_base.h
- src/core/hle/kernel/k_process.cpp
- src/core/memory.cpp
- src/core/memory.h
- src/tests/common/host_memory.cpp
Fixes #7397
Unlike basically every other operating system, Linux has a limit on how many distinct page table mappings you can create with mmap(). This doesn't appear to correspond to any real resource limiting need and the default value is set to 65530 on most systems. 
Typically, Switch games will query the amount of heap they have available, reserve all of it, and then suballocate from their OS-level reservation as they use up memory. This is already well-supported when using host-mapped memory on Linux-based operating systems as it only creates a small number of virtual-to-physical mappings for the physical memory blocks which comprise the heap.
Games based on Unreal Engine 4 do something different: instead of reserving all of their available heap immediately, they reserve and …
>  core: track separate heap allocation for linux 

- src/audio_core/device/device_session.cpp
- src/core/core_timing.cpp
- src/core/core_timing.h
- src/core/hle/kernel/k_hardware_timer.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/service/hid/hidbus.cpp
- src/core/hle/service/hid/hidbus.h
- src/core/hle/service/hid/resource_manager.cpp
- src/core/hle/service/hid/resource_manager.h
- src/core/hle/service/nvnflinger/nvnflinger.cpp
- src/core/memory/cheat_engine.cpp
- src/core/memory/cheat_engine.h
- src/core/tools/freezer.cpp
- src/core/tools/freezer.h
- src/tests/core/core_timing.cpp
This simplifies and increases the robustness of client code, and solves another shutdown crash related to timing.
>  core_timing: minor refactors

- src/core/memory.h
- src/video_core/engines/maxwell_dma.cpp
- src/video_core/renderer_vulkan/vk_present_manager.cpp
This set of fixes, fix the performance slowdowns in Super Mario Odessy in Android while videos are playing.
> VideoCore: A few fixes to DMA and swapchain

- src/yuzu/multiplayer/direct_connect.cpp
We load the port from settings. But when connecting to the room we used the default port if it wasn't modified. This resulted in a mismatch on what is displayed on the UI and what is actually doing.
closes #12550
> yuzu: Use displayed port on direct connect

- src/core/hle/kernel/k_thread.cpp
KThread::RequestTerminate may run from a thread which is not the CurrentCore, or a core thread.
As masking out only makes sense to avoid an interrupt to the "currently executing" core if this were a real machine, remove this masking.
> KThread: Send termination interrupt to all cores a thread has affinity to

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GamePropertiesFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/FileUtil.kt
Disables compression for user data and save exports
Testing with firmware and an update installed saw user data export time decrease from 3 minutes to 1
> android: Disable compression for zip exports

- .github/workflows/android-merge.js
- .github/workflows/android-publish.yml
Shifts automation responsibility from yuzu-emu/yuzu to yuzu-emu/yuzu-android and allows for triggering builds from the yuzu-emu/yuzu-android repo.
Additionally links to the merged PR in the related commit
And prevents linking to an unrelated PR in the tag commit (Ex. "Android #180" linking to PR 180)
> actions: android: Allow for manually triggering Android builds

- src/frontend_common/config.cpp
- src/frontend_common/config.h
Fixes a compiler error where the compiler could not see the definition of the method in qt_config and others.
> frontend_common: config: Move WriteIntegerSetting definition to header

- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/Settings.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
- src/android/app/src/main/res/values/arrays.xml
- src/android/app/src/main/res/values/strings.xml
You can now use the following orientation options during emulation
- Auto
- Sensor Landscape
- Landscape
- Reverse Landscape
- Sensor Portrait
- Portrait
- Reverse Portrait
yuzu in reverse portrait - the way it was meant to be played...
Additionally, fixed a bug where we would apply custom orientation only once emulation had started
> android: Expose more orientation options

- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/GamesViewModel.kt
- src/android/app/src/main/jni/android_config.cpp
- src/android/app/src/main/jni/android_config.h
- src/frontend_common/config.cpp
Fixes a couple issues with config saving on android (and potentially PC but I haven't seen reports there)
- Fixes an issue where global settings could be overwritten by previously loaded per-game settings
- Fixes an issue where multiple global config saves could happen at once when leaving the games folder fragment repeatedly
> frontend_common: config: Only write setting related to opened config file

- src/shader_recompiler/backend/glsl/emit_glsl_image.cpp
- src/shader_recompiler/backend/glsl/emit_glsl_instructions.h
- src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
- src/video_core/renderer_opengl/gl_device.cpp
- src/yuzu/configuration/shared_translation.cpp
AMD's new OGLP driver is no longer a complete insufferable joke, but still has its issues, so it's not always viable.
This removes some of the AMD specific OpenGL workarounds that are no longer applicable, and has a few fixes.
> OpenGL: Fixes and workaround updates for AMD

- src/hid_core/resource_manager.cpp
- src/hid_core/resources/applet_resource.cpp
- src/hid_core/resources/npad/npad_resource.cpp
We need to handle pending delete entries. I don't have the RE for this part. So currently I'm just going to assume at the moment that not assigned and pending delete are the same.
This fixes a crash that happened when registering multiple aruid handles while deleting old ones. Besides this I did some minor cleanup of the code.
> service: hid: Handle pending delete

- src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/InstallableFragment.kt
- src/android/app/src/main/jni/native.cpp
- src/android/app/src/main/res/values/strings.xml
- src/core/file_sys/savedata_factory.cpp
- src/core/file_sys/savedata_factory.h
Reworked to correctly collect and import/export saves that could exist in either /nand/user/save/000...000/<user id> or /nand/user/save/account/<user id raw string>
Compatible with all previous save data backups, regardless of whether they were exported per-game or globally.
> android: Re-add global save manager

- src/hid_core/resources/npad/npad.cpp
We still have issues with Rocket league. Now that npad is initialized properly at boot the game still tries to register a vibration device before creating the applet resource. Creating again the same crash but in a different spot.
Here I prevent this from happening.
> service: hid: Make sure there's an active aruid handle

- src/android/app/src/main/AndroidManifest.xml
- src/android/app/src/main/res/xml/game_mode_config.xml
This adds support for the Performance and Battery Saver modes in the Game Dashboard mostly found on Google Pixel devices.
This does not yet define the specifics for the performance modes but does provide the initial basic support
> android: add basic support for google game dashboard

- src/shader_recompiler/environment.h
- src/shader_recompiler/ir_opt/constant_propagation_pass.cpp
- src/video_core/buffer_cache/memory_tracker_base.h
- src/video_core/control/channel_state_cache.h
- src/video_core/control/channel_state_cache.inc
- src/video_core/engines/maxwell_3d.h
- src/video_core/engines/sw_blitter/blitter.cpp
- src/video_core/host1x/codecs/vp8.h
- src/video_core/host_shaders/astc_decoder.comp
- src/video_core/query_cache/query_cache.h
- src/video_core/query_cache/query_stream.h
- src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
- src/video_core/renderer_vulkan/fixed_pipeline_state.h
- src/video_core/renderer_vulkan/vk_blit_screen.h
- src/video_core/renderer_vulkan/vk_query_cache.cpp
- src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/shader_environment.cpp
- src/video_core/vulkan_common/vulkan_device.h
- src/video_core/vulkan_common/vulkan_memory_allocator.cpp
Found few hundred misspellings.
This PR only touches `src/video_core/`.
> Fix typos in video_core

- .ci/scripts/format/script.sh
- .ci/scripts/linux/exec.sh
- LICENSES/BSD-2-Clause.txt
- LICENSES/BSD-3-Clause.txt
- LICENSES/MPL-2.0.txt
- externals/ffmpeg/CMakeLists.txt
Currently there are some problems with this workflow:
- The grep command that is intended to find trailing whitespace doesn't actually work, because it doesn't use recursive globs.
- TRAVIS_EVENT_TYPE isn't supported by GitHub, and even if we check for GITHUB_EVENT_TYPE instead, we would need to do a non-shallow clone to verify format over the file range, which we don't really care about. So we should always check every source file.
- The format output doesn't lend itself easy use with `git apply`, requiring manually fixing up the generated diffs in order to apply.
This fixes all of these issues.
>  ci: make verify format workflow output more helpful 

- src/core/hle/service/nvnflinger/nvnflinger.cpp
- src/core/hle/service/vi/display/vi_display.cpp
- src/core/hle/service/vi/display/vi_display.h
- src/core/hle/service/vi/vi.cpp
- src/core/hle/service/vi/vi.h
1. Fix the name of nvnflinger
2. The ability to fetch the vsync event is tied to the lifetime of the application display service interface, not the display itself
> vi: minor cleanups

- .ci/scripts/format/script.sh
Mainline stage 1 job sets the bash files in .ci/scripts to executable on demand, so ignore those file mode changes. Might be better to just make them executable in the repo.
> ci: fix file mode check in format script

- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/AbstractDiffAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/AbstractListAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/AbstractSingleSelectionList.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/AddonAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/AppletAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/CabinetLauncherDialogAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/DriverAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/FolderAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/GameAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/GamePropertiesAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/HomeSettingAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/InstallableAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/LicenseAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/SetupAdapter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/DriverManagerFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/Driver.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/DriverViewModel.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/SelectableItem.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/GpuDriverHelper.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/viewholder/AbstractViewHolder.kt
- src/android/app/src/main/res/menu/menu_driver_manager.xml
Created a few generic list adapters and a generic view holder to simplify interactions with list updates.
Additionally, this has some updates to the driver fragment as a result of the simplifications
- Fixes an issue where per-game driver settings could be written into global settings
- Adds a button to use the global driver setting
- Fixes an issue where incorrect drivers could appear upon importing user data
> android: Refactor list adapters

- .ci/scripts/format/script.sh
- .github/workflows/verify.yml
- src/android/app/build.gradle.kts
Running the ktlint check every time you built the android project was pretty frustrating. This moves it to run in the `verify` step for PRs like clang-format.
This also adds a hint to run `gradlew ktlintFormat` to automatically format your code if the verification steps fail.
> android: Move ktlintCheck to yuzu-verify

- src/android/app/build.gradle.kts
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AboutFragment.kt
- src/android/app/src/main/res/layout-w600dp/fragment_about.xml
- src/android/app/src/main/res/layout/fragment_about.xml
Allows you to see the git tag (Ex. "android-190") used for our android mainline builds and the build hash plus the release variant (Ex. "15d8a4052-relWithDebInfo") for all other builds under "Build" in the about page.
> android: Show version name instead of build hash in about fragment

- src/core/hle/service/server_manager.cpp
When a client handle gets closed without passing through the normal service termination route, it breaks the server manager. Ensure we handle this correctly.
> server_manager: respond to session close correctly

- src/common/page_table.cpp
- src/core/debugger/debugger.cpp
- src/core/debugger/gdbstub.cpp
- src/core/debugger/gdbstub.h
- src/core/hle/kernel/k_memory_block_manager.cpp
- src/core/hle/kernel/k_memory_block_manager.h
- src/core/hle/kernel/k_page_table_base.cpp
- src/core/hle/kernel/k_page_table_base.h
- src/core/hle/kernel/k_process.cpp
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
- src/core/hle/kernel/svc/svc_process.cpp
- src/core/hle/service/glue/arp.cpp
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/pm/pm.cpp
Blinkhawk informed me that KProcess was leaking some memory on shutdown, so I had a quick look. Slab heap objects don't have their destructors called, so the destruction of the unique_ptrs was not occurring and leaking the ARM interface pointers and exclusive monitor, as well as leaking all of the allocated heap pages (though these would normally have been reset after the slab heap was cleared, so it wasn't a huge deal).
Additionally, I found and fixed a bunch of lifetime management surrounding holding references to the process object. It's unlikely that these would have ever resulted in a crash, but better to refactor to handle this correctly.
> kernel: fix resource management issues

- src/android/app/src/main/jni/native.cpp
- src/core/CMakeLists.txt
- src/core/core.cpp
- src/core/file_sys/savedata_factory.cpp
- src/core/file_sys/savedata_factory.h
- src/core/hle/service/am/am.cpp
- src/core/hle/service/filesystem/filesystem.cpp
- src/core/hle/service/filesystem/filesystem.h
- src/core/hle/service/filesystem/fsp_srv.cpp
- src/core/hle/service/filesystem/fsp_srv.h
- src/core/hle/service/filesystem/romfs_controller.cpp
- src/core/hle/service/filesystem/romfs_controller.h
- src/core/hle/service/filesystem/save_data_controller.cpp
- src/core/hle/service/filesystem/save_data_controller.h
- src/core/loader/deconstructed_rom_directory.cpp
- src/core/loader/nca.cpp
- src/core/loader/nro.cpp
- src/core/loader/nsp.cpp
- src/core/loader/xci.cpp
- src/yuzu/main.cpp
This refactoring allows fs to be informed about filesystem metadata for the running program directly from the loader, instead of having to fetch it from globals every time.
> fsp-srv: use program registry for SetCurrentProcess

- src/shader_recompiler/backend/spirv/emit_spirv_memory.cpp
- src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
- src/shader_recompiler/backend/spirv/spirv_emit_context.h
Fixes one of the issues in #12643, there is still at least one more shader compiler crash regarding missing support for StorageImageExtendedFormats
Probably fixes a bunch of shader compiler crashes in other games. The emitted shader was basically not parseable at all before this fix, and I had to view it in a hex editor to figure out the issue.
> shader_recompiler: emulate 8-bit and 16-bit storage writes with cas loop

- src/audio_core/device/device_session.cpp
- src/audio_core/device/device_session.h
- src/audio_core/in/audio_in_system.cpp
- src/audio_core/in/audio_in_system.h
- src/audio_core/out/audio_out_system.cpp
- src/audio_core/out/audio_out_system.h
- src/core/hle/service/audio/audin_u.cpp
- src/core/hle/service/audio/audout_u.cpp
The information is provided by the sync request that sets up audio in/out sessions, and is used to device map the memory. Therefore it doesn't need to be fetched from globals.
> audio: fetch process object from handle table

- src/core/hle/service/acc/profile_manager.cpp
- src/core/hle/service/acc/profile_manager.h
- src/yuzu/configuration/configure_profile_manager.cpp
I finally got an instance where the profile data corrupted. The issue here is that we save when the profile manager is destroyed, normally this works fine but on a crash it might not flush the contents on time. Leaving you with a 0 byte file. Next session will detect the file is empty and create a new user. 
To fix that I removed the save on destruction, we don't need that. Instead I save only when the contents change. This should permanently fix this long standing bug.
> service: acc: Only save profiles when profiles have changed

- src/core/arm/nce/patcher.cpp
- src/core/arm/nce/patcher.h
- src/core/hle/kernel/k_process.cpp
- src/core/loader/deconstructed_rom_directory.cpp
- src/core/loader/nso.cpp
- src/core/loader/nso.h
Small batch of changes to module patching requested by @liamwhite 
Instead of each module strictly having a dedicated patch section, the loader will try to use the same patch section for as many sequential in memory modules as possible. When the target jump becomes too large, only then the patch section is broken off. Pre-text patches retain the same behavior as before, they have a dedicated patch section
Should fix mods that make assumptions about the module layout and hardcode jump offsets
Fixes #12224
> core: Support multiple modules per patcher

- .ci/yuzu-mainline-step2.yml
Broke after moving the ktlint checks to CI but this should only be happening for PRs anyways.
> ci: Remove format step from mainline builds

- src/android/app/src/main/res/values/arrays.xml
Fixes an issue where the L3/R3 and Left Stick/Right Stick buttons in the toggle buttons menu would be swapped
> android: Fix overlay toggle ordering

- src/android/app/src/main/jni/android_config.cpp
- src/frontend_common/config.cpp
- src/frontend_common/config.h
- src/yuzu/configuration/configure_input_player.cpp
- src/yuzu/configuration/input_profiles.cpp
- src/yuzu/configuration/qt_config.cpp
- src/yuzu_cmd/sdl_config.cpp
For each player, the controller configuration profile name is saved in the qt-config.ini file. The one selected is restored when opening the configuration window, even after closing yuzu
> Save configuration profile name used by players

- src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
This should have been fully embraced before but the items within the popup menu and the adjust controls dialog fell through. This ensures that everything related to the overlay is saved during emulation and can't be lost during a crash.
> android: Save overlay data while using emulation fragment

- src/input_common/CMakeLists.txt
- src/input_common/drivers/android.cpp
- src/input_common/drivers/android.h
- src/input_common/input_mapping.cpp
- src/input_common/main.cpp
- src/input_common/main.h
Works exactly the same as Virtual gamepad but this engine is a hardcoded engine. If we want custom mappings we must use another engine dedicated just for android.
> input_common: Add android input engine

- src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
- src/shader_recompiler/backend/spirv/emit_spirv_instructions.h
This is not invalid in SPIR-V, but is invalid in Vulkan (VUID-StandaloneSpirv-Offset-04663).
> shader_recompiler: fix Offset operand usage for non-OpImage*Gather

- src/core/hle/service/nfc/common/device.cpp
An user tried to dump their amiibos. But yuzu did not generate any because the amiibo was mounted as read only. This PR makes this process easier as it now allows to dump the amiibos if no previous dump is available and was marked as read only.
> service: nfc: Create backup when none exist

- src/hid_core/resources/npad/npad.cpp
This part is not technically accurate. But we need to clear the controller state when the aruid is no longer in use to keep the state clean next time.
> service: hid: Clear controller status when aruid is no longer used

- src/core/hle/service/acc/profile_manager.cpp
- src/core/hle/service/acc/profile_manager.h
- src/yuzu/main.cpp
- src/yuzu/main.h
Allow -u to accept a username string in addition to index, and suppress the User selector even if settings requires it to be shown for one instance only.
> Allow -u to accept a username string in addition to index

- src/hid_core/frontend/emulated_controller.cpp
Disconnecting the controller while special features are still active will cause a double lock. To prevent this disable anything before disconnecting. This fixes a crash when using nfc and trying to open the config menu.
> core: hid: Disable special features before disconnecting the controllers

- src/yuzu/CMakeLists.txt
Bumps MVK from 1.2.5 to 1.2.7  (Vulkan SDK 1.3.275)
I have tested with a few games and didn't notice any regressions. 
Here is the [changelog for 1.2.7](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.7): 
<details>
<summary>Changelog 1.2.7</summary>
- Add support for extensions:
- `VK_KHR_calibrated_timestamp`
- `VK_KHR_format_feature_flags2`
- `VK_KHR_vertex_attribute_divisor`
- `VK_EXT_extended_dynamic_state3` (Metal does not support `VK_POLYGON_MODE_POINT`)
- `VK_EXT_headless_surface`
- `VK_EXT_layer_settings`
- Add support for format `VK_FORMAT_B4G4R4A4_UNORM_PACK16`.
- Add support for vertex formats `VK_FORMAT_B10G11R11_UFLOAT_PACK32` & `VK_FORMAT_E5B9G9R9_UFLOAT_PACK32`.
- Fix regression that broke `VK_POLYGON_MODE_LINE`.
- Fix regression in marking rendering state dirty …
> macOS: Bump MoltenVK to v1.2.7

- src/android/app/src/main/res/layout/card_home_option.xml
Works better with the Material You theme in dark mode, black backgrounds, and just generally looks nice
> android: Use elevated card style for home setting card

- src/common/fs/file.h
Closes #12723.
std::fstream::open takes a std::filesystem::path as a first argument. [MSVC correctly accepts this, but libc++/libstdc++ does not](https://twitter.com/__phantomderp/status/1748763826479091742). Explicitly convert for better compiler compatibility.
> fs/file: Explicitly convert std::u8string to std::filesystem::path

- src/video_core/renderer_vulkan/vk_present_manager.cpp
Fixes #12684
Mutter has an issue where if you present a surface larger than the dimensions of your swapchain it just draws over random crap on the screen so that's lovely. Possibly should check if this is an issue in kwin or wlroots.
This reverts the change from #12543. Arguably it didn't make any sense there because the frame dimensions are always supposed to be based on the swapchain, not on the guest.
> renderer_vulkan: recreate swapchain when frame size changes

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/DriverManagerFragment.kt
- src/android/app/src/main/res/layout/list_item_setting.xml
- src/android/app/src/main/res/layout/list_item_setting_switch.xml
- src/android/app/src/main/res/menu/menu_driver_manager.xml
- src/android/app/src/main/res/values/strings.xml
Changed the wording for returning to the global setting to make things a little clearer
> android: Change "Clear" to "Use global setting" for per-game settings

- src/core/hle/service/set/system_settings_server.cpp
Mii edit is broken because some settings config have invalid UUID. This should fix these issues
> service: set: Don't allow invalid mii author id

- src/hid_core/frontend/emulated_controller.cpp
Minor issue I forgot to add back. We had a frontend setting that was removed from core on the rewrite. Use this setting on the correct place instead.
> core: hid: Allow to disable vibration

- src/core/hle/service/nvdrv/nvdrv_interface.cpp
- src/core/hle/service/set/system_settings_server.cpp
- src/core/hle/service/vi/vi.cpp
Found this issue while debugging the setting service. We can't convert from buffer to string directly with begin()...end() since that will include trailing zeroes on the string and any comparison with another string will fail. It also causes issues with logging as the parser doesn't handle this well either.
> service: properly convert buffers to strings

- src/video_core/vulkan_common/vulkan_wrapper.cpp
Recently, Windows started shipping an OpenCL/OpenGL/Vulkan compatibility pack, which includes dozen, Mesa's D3D12 to Vulkan compatibility layer.
Those new Vulkan devices are called "Microsoft Direct3D (device name)", making them take priority over AMD and Intel devices in yuzu's Vulkan device list due to how the list is ordered (inverse alphabetical order takes priority).
This change checks for the Microsoft string and pushes those devices to the bottom of the list, following the other rules in the ordering process.
> Demote dozen to the bottom of the device list

- src/core/CMakeLists.txt
- src/core/hle/service/cmif_serialization.h
- src/core/hle/service/cmif_types.h
- src/core/hle/service/hle_ipc.cpp
- src/core/hle/service/hle_ipc.h
- src/core/hle/service/jit/jit.cpp
- src/core/hle/service/ro/ro.cpp
- src/core/hle/service/service.h
We are spending a significant amount of time writing manual serialization and deserialization for service interfaces, and frequently get it wrong because of the argument sorting rules and different handling between buffer types.
As we move deeper into more and more involved service implementations, the maintenance burden of doing this is already past unsustainable, and it's clear we need a new solution. Several recent PRs have even started separating out the `Result`-returning versions of interface methods from specially named IPC wrappers.
This is not the overarching solution I have wished for, but it allows us to incrementally migrate services as we need to the "wrapped" format.
The syntax for binding interface methods is almost the same, except you must now specify whether the server …
> service: add template serializer for method calls

- src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AboutFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/EmulationViewModel.kt
- src/android/app/src/main/res/layout-w600dp/fragment_about.xml
- src/android/app/src/main/res/layout-w600dp/fragment_game_info.xml
- src/android/app/src/main/res/layout-w600dp/fragment_game_properties.xml
- src/android/app/src/main/res/layout/card_driver_option.xml
- src/android/app/src/main/res/layout/card_folder.xml
- src/android/app/src/main/res/layout/fragment_about.xml
- src/android/app/src/main/res/layout/fragment_addons.xml
- src/android/app/src/main/res/layout/fragment_applet_launcher.xml
- src/android/app/src/main/res/layout/fragment_driver_manager.xml
- src/android/app/src/main/res/layout/fragment_early_access.xml
- src/android/app/src/main/res/layout/fragment_emulation.xml
- src/android/app/src/main/res/layout/fragment_folders.xml
- src/android/app/src/main/res/layout/fragment_game_info.xml
- src/android/app/src/main/res/layout/fragment_game_properties.xml
- src/android/app/src/main/res/layout/fragment_games.xml
- src/android/app/src/main/res/layout/fragment_home_settings.xml
- src/android/app/src/main/res/layout/fragment_installables.xml
- src/android/app/src/main/res/layout/fragment_licenses.xml
- src/android/app/src/main/res/layout/fragment_settings.xml
- src/android/app/src/main/res/layout/list_item_addon.xml
- src/android/app/src/main/res/layout/list_item_settings_header.xml
This does a few things related to the controller's focus meaning the highlight you see over buttons to indicate that you can click it
- Fixes an issue where you couldn't focus toolbar menu items
- Fixes an issue where the in game menu wouldn't be focused when opened
- Fixes an issue where container views would appear focused even though they aren't clickable
- Fixes an issue where the emulation surface would appear focused and gray
- Adds a landscape layout for the game info page
> android: Controller focus optimizations

- src/hid_core/resource_manager.cpp
- src/hid_core/resources/vibration/vibration_base.cpp
- src/hid_core/resources/vibration/vibration_base.h
Some games enable vibration before npad is initialized. Others like `Taiko no Tatsujin Rhythm Festival` send vibrations before vibration is initialized. I reviewed the code a couple of times but there's no mistake from my RE. The only explanation I found is that vibration is probably already initialized from system side. To fix this issue I simply avoid any vibration while the handle is inactive.
Fixes #12797
> service: hid: Don't try to vibrate if device isn't initialized

- src/core/hle/service/btm/btm.cpp
- src/core/hle/service/hid/hid.cpp
- src/core/hle/service/hid/hid_server.cpp
- src/core/hle/service/hid/hid_system_server.cpp
- src/core/hle/service/hid/hid_system_server.h
- src/core/hle/service/set/setting_formats/system_settings.cpp
- src/core/hle/service/set/settings_types.h
- src/core/hle/service/set/system_settings_server.cpp
- src/core/hle/service/set/system_settings_server.h
- src/hid_core/resource_manager.cpp
- src/hid_core/resources/hid_firmware_settings.cpp
- src/hid_core/resources/hid_firmware_settings.h
- src/hid_core/resources/npad/npad.cpp
- src/hid_core/resources/npad/npad.h
- src/hid_core/resources/npad/npad_vibration.cpp
- src/hid_core/resources/npad/npad_vibration.h
Mostly used by Qlaunch. Implements a few more settings needed mostly on HID. There are still more to implement but reduces the need for auto stub.
> service: set: Implement more settings functions for Qlaunch

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
Adds another case to the installed content check so that if you press cancel, it won't say "Integrity verification succeeded!" and instead say "Integrity verification couldn't be performed"
Closes #12804
> android: Add cancel condition to installed content check

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
UI like the driver manager expects the global settings to be loaded when in the MainActivity so we reload global config to properly reset state on exit.
> android: Reload global settings on closing emulation

- src/android/app/src/main/res/layout/fragment_emulation.xml
Fixes a regresssion in #12796 where the card could appear focused
> android: Disable focus on loading card

- src/yuzu/configuration/configure_graphics.cpp
Steps to reproduce crash:
1. Setup graphics backend to be Null.
2. Open the settings window.
3. Close the settings window.
4. Crash occurs.
Crash occurs because `vsync_mode_combobox->currentIndex() == -1` with the above.
> configure_graphics: Avoid crash when vsync_mode_combobox is empty

- src/audio_core/adsp/apps/audio_renderer/audio_renderer.cpp
- src/audio_core/adsp/apps/audio_renderer/audio_renderer.h
- src/audio_core/adsp/apps/audio_renderer/command_buffer.h
- src/audio_core/adsp/apps/audio_renderer/command_list_processor.cpp
- src/audio_core/adsp/apps/audio_renderer/command_list_processor.h
- src/audio_core/renderer/audio_renderer.cpp
- src/audio_core/renderer/audio_renderer.h
- src/audio_core/renderer/system.cpp
- src/audio_core/renderer/system.h
- src/core/hle/service/audio/audren_u.cpp
Allows audren to work over multiple processes.
> Use the input process handle to get the correct application's memory

- src/common/atomic_ops.h
- src/core/memory.cpp
Also fixes builds on unusual toolchains where:
- u32 is unsigned int
- u64 is unsigned long long
- uintptr_t is unsigned long
Which results in a build error when one `AtomicCompareAndSwap`s with a uintptr_t.
> atomic_ops: Reduce code duplication with templates

- src/frontend_common/config.cpp
- src/frontend_common/config.h
- src/yuzu/CMakeLists.txt
- src/yuzu/configuration/configure_audio.h
- src/yuzu/configuration/configure_cpu.h
- src/yuzu/configuration/configure_general.h
- src/yuzu/configuration/configure_graphics.h
- src/yuzu/configuration/configure_graphics_advanced.h
- src/yuzu/configuration/configure_linux_tab.cpp
- src/yuzu/configuration/configure_linux_tab.h
- src/yuzu/configuration/configure_linux_tab.ui
- src/yuzu/configuration/configure_motion_touch.h
- src/yuzu/configuration/configure_mouse_panning.h
- src/yuzu/configuration/configure_per_game.cpp
- src/yuzu/configuration/configure_per_game.h
- src/yuzu/configuration/configure_system.h
- Linux settings were not saved or loaded in config file. Fix for https://github.com/yuzu-emu/yuzu/issues/12444
- Add per-game gamemode option :
- Create a new Linux configuration tab, because General tab is not present per-game
- Add settings of Linux category in the tab
- Show the tab in per-game configuration, on Linux only
I added Q_OBJECT macro on other tab classes, for consistency, even if it is mostly needed only when declaring signal and slots. Some already had it, others not, with no reason.
> Save gamemode configuration and add per-game config

- src/core/hle/service/set/setting_formats/system_settings.cpp
Build in ubuntu jammy arm64 gcc 11 with cmake cmd `VCPKG_FORCE_SYSTEM_BINARIES=1 cmake .. -GNinja -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 -DYUZU_USE_QT_WEB_ENGINE=ON -DLINUX=1 -DYUZU_USE_BUNDLED_VCPKG=ON`
This commit fixes build error:
```
/build/deb_build/yuzu-0-1696/src/core/hle/service/set/setting_formats/system_settings.cpp:47:53: error: no match for ‘operator=’ (operand types are ‘Service::PSC::Time::LocationName’ and ‘<brace-enclosed initializer list>’)
47 |     settings.device_time_zone_location_name = {"UTC"};
|                                                     ^
In file included from /build/deb_build/yuzu-0-1696/src/./core/hle/service/set/settings_types.h:12,
from /build/deb_build/yuzu-0-1696/src/./core/hle/service/set/setting_formats/private_settings.h:10,
from …
```
> fix build for gcc 11

- src/core/hle/service/mii/mii.cpp
This is now possible. So I prefer to use it on any reference that shouldn't be modified.
> service: mii: Set arguments as const

- src/common/settings.h
- src/yuzu/configuration/configure_audio.cpp
- src/yuzu/configuration/configure_audio.h
Since the audio output/input are set based on the audio sink, there's some custom logic around the reset to global button to ensure that you can't reset the audio device to something that only the global sink has access to.
> settings: Allow audio sink, input, and output to be set per game

- src/core/hle/service/glue/time/time_zone.cpp
- src/core/hle/service/glue/time/time_zone.h
- src/core/hle/service/psc/time/common.h
- src/core/hle/service/psc/time/service_manager.cpp
- src/core/hle/service/psc/time/time_zone.cpp
- src/core/hle/service/psc/time/time_zone.h
- src/core/hle/service/psc/time/time_zone_service.cpp
- src/core/hle/service/psc/time/time_zone_service.h
- src/core/hle/service/set/system_settings_server.cpp
Remove a few hacks for clock setups, which seem to no longer be needed. 
Fix network clock to local clock on every boot, instead of just once on setup, which fixes Pokemon Quest advancing time as it relies on the network clock updating between loads.
Also fix some logging strings.
> Small time fixes

- src/common/CMakeLists.txt
- src/common/range_mutex.h
- src/core/device_memory_manager.h
- src/core/device_memory_manager.inc
- src/core/hle/service/nvdrv/core/container.cpp
- src/video_core/texture_cache/texture_cache.h
- src/video_core/texture_cache/texture_cache_base.h
This adds a set of fixes for some SMMU problems:
* Games with fragmented heaps (Ex: Fire Emblem Three Houses) will now correctly use the full heap optimization. This is to avoid running out of memory due to repeated aliases.
* SMMU will no longer protect non-device memory from the game. This fixes the NCE FPS 0 of death in most cases in Android.
* Sparse Images Page Table is now per channel, this avoids conflicts between Applet GPU address space and other applications.
Still pending are the issues with primitive succeeded queries on Splatoon 2. These will need to be redone, sadly.
> SMMU: A set of different fixes.

- .github/workflows/verify.yml
This changes the build architecture to arm64, which reflects the environment most people will be compiling it with.
> ci: bump mac to macos-14

- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/vulkan_common/vulkan_device.cpp
For RDNA-based Samsung Xclipse GPUs, this fixes wireframes in Pokémon games such as Sword/Shield, Scarlet/Violet and possibly others.
Based on the original #6900 @ameerj made, this just adds the new `VK_DRIVER_ID_SAMSUNG_PROPRIETARY` driver ID to the reorder pass
Thanks to @no.kola on Discord for testing the fix and @liamwhite for the driver ID
> structured_control_flow: Add Samsung Proprietary Driver ID to Reorder Pass

- CMakeLists.txt
The `FindVulkan.cmake` module provided by CMake is deprecated and will be [removed](https://gitlab.kitware.com/cmake/cmake/-/issues/25617) in the future, so use upstream `VulkanHeadersConfig.cmake` file instead.
> cmake: use vulkan-headers config file

- src/yuzu/main.cpp
- src/yuzu/uisettings.h
Default shortcuts were chosen as to be intuitive (use the first letter of the action, or the second word's first letter) and work on all types of keyboards. The hotkeys can be used while playing a game too, as they are application-wide.
- This closes https://github.com/yuzu-emu/yuzu/issues/10169.
> Add hotkeys for multiplayer actions

- src/yuzu/multiplayer/lobby.cpp
- src/yuzu/uisettings.h
- Follow-up to https://github.com/yuzu-emu/yuzu/pull/12850.
After connecting to a room, the chosen filter text, "Games I Own", "Hide Empty Rooms" and "Hide Full Rooms" values are persisted to configuration so they are preserved across restarts.
This makes it easier to rejoin a room if you regularly play the same game, or after a crash.
> Persist filters in multiplayer public lobby list

- src/yuzu/multiplayer/lobby_p.h
- Full lobbies have their player count displayed in red.
- Lobbies with one slot left have their player count displayed in orange.
- Empty lobbies have their player count grayed out.
This makes the lobby list easier to visually parse.
-|-
-|
> Color player counts in the multiplayer public lobby list

- src/hid_core/resource_manager.cpp
- src/hid_core/resource_manager.h
- src/hid_core/resources/digitizer/digitizer.cpp
- src/hid_core/resources/digitizer/digitizer.h
- src/hid_core/resources/npad/npad.cpp
- src/hid_core/resources/npad/npad.h
- src/hid_core/resources/unique_pad/unique_pad.cpp
- src/hid_core/resources/unique_pad/unique_pad.h
Currently we have a weird input issue on multiple applets chained together. While this PR doesn't fix that issue we found a couple of mistakes that might cause issues in some games.
- Fixes polling when multiple aruid are registered.
- Controllers registering as connected before styleset is defined.
- Fixes color corruption.
- Fixes external pad state.
- Fixes unique pad and digitizer missing header.
> service: hid: Multiple fixes

- src/common/hex_util.h
- src/core/hle/service/filesystem/fsp/fsp_srv.cpp
I sometimes create backups in the same folder where saves are. This avoids an out of bounds memory read when some folders aren't the correct size.
> service: fs: Skip non user id folders

- src/core/hle/service/glue/time/time_zone_binary.cpp
IsTimeZoneBinaryValid checks the mount result, and it's not set until the end of the function we're calling it from, so just set it as success before attempting the check. If the check fails, it'll be reset to Unknown.
> Fix firmware timezone boot load check.

- src/core/memory/cheat_engine.cpp
- src/core/memory/cheat_engine.h
- src/core/memory/dmnt_cheat_types.h
- src/core/memory/dmnt_cheat_vm.cpp
- src/core/memory/dmnt_cheat_vm.h
Updates cheat codes to support if-else statements. Along this fixes a few mistakes like: Static registers loosing their value, missing `alias` and `aslr` memory spaces, pause/resume opcodes returning as invalid opcodes.
Note: Pause and Resume aren't implemented yet. I need to research a bit before implementing them.
> dmnt: cheats: Update cheat vm to latest version

- src/yuzu/configuration/configure_per_game.cpp
Eliminates the element from appearing on windows. On the top left.
> yuzu: Fully hide linux tab

- src/core/hle/service/nvnflinger/hardware_composer.cpp
- src/core/hle/service/nvnflinger/hardware_composer.h
- src/core/hle/service/nvnflinger/nvnflinger.cpp
Currently the composer sleeps and then releases any acquired buffers after it wakes up again on the next vsync signal. This seems incorrect - it should release them as soon as possible after they are presented to avoid starving the guest present queue.
I believe this should address #12902, but needs testing.
> nvnflinger: release buffers before presentation sleep

- src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
- src/video_core/host1x/host1x.cpp
- src/video_core/memory_manager.cpp
- src/video_core/memory_manager.h
This is the start of a reform of the GPU memory manager, to improve speed and reduce memory usage.
This simply reduces the memory usage of the big page table from 64Mbs to 8Mbs.
> MemoryManager: Reduce the page table size based on last big page address.

- src/yuzu/configuration/configure_hotkeys.cpp
- src/yuzu/configuration/configure_hotkeys.h
- src/yuzu/hotkeys.cpp
One of the most common complains is how difficult is to use custom controller hotkeys. Right now users need to press home/screenshot button + another button at the same time to save the button presses. This makes it almost impossible to do a 3+ key press.
This simplifies the method in these ways:
- One key presses are allowed. It will be user responsibility to avoid issues from accidentally pressing the hotkey while playing.
- You will see a preview of the button presses followed with "..."
- Finally the box will save the output after 2.5 seconds.
> yuzu: Make controller keys easier to assign

- src/core/memory/cheat_engine.cpp
Users keep mentioning that cheats that used buttons didn't work. I found that the game was running on cache so any memory writes to game code won't affect it until we invalidate the region. This should fully fix cheats for Mario Wonder and many more games.
> dmnt: cheat: Invalidate cache on memory writes

- src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
- src/shader_recompiler/backend/spirv/emit_spirv_instructions.h
Fixes Astral Chain on qcom drivers
> shader_recompiler: use only ConstOffset for OpImageFetch

- src/android/app/build.gradle.kts
Fixes an issue where github builds would appear as `android` instead of `android-236`
> android: Fix regex for git version

- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/BooleanSetting.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AboutFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AddonsFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AppletLauncherFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/DriverManagerFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EarlyAccessFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GameFoldersFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GameInfoFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GamePropertiesFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/InstallableFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/LicensesFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/SettingsSearchFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/GamesFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/ViewUtils.kt
- src/android/app/src/main/jni/android_settings.h
- src/android/app/src/main/res/layout/fragment_emulation.xml
- src/android/app/src/main/res/menu/menu_overlay_options.xml
- src/android/app/src/main/res/values/strings.xml
Adds an additional overlay option to show if your device is thermally throttling
Android has a system service that allows you to check if the system is reducing performance to improve throttling so we expose that via an emoji indicator. Each of these emojis will indicate the following thermal statuses. (Learn more about each status [here](https://source.android.com/docs/core/power/thermal-mitigation#codes))
🙂 - No throttling
😥 - Light throttling
🥵 - Moderate throttling
🔥 - Severe throttling
☢️ - Platform has done everything to reduce power
Thanks to @liamwhite for the idea to represent throttling this way
These definitions can vary between each vendor, but they are useful to see why one session is performing better than another.
(My Galaxy S21 quickly reaching severe throttling after just …
> android: Thermal throttling indicator

- src/android/app/src/main/jni/CMakeLists.txt
- src/android/app/src/main/jni/emu_window/emu_window.cpp
- src/android/app/src/main/jni/game_metadata.cpp
- src/android/app/src/main/jni/native.cpp
- src/android/app/src/main/jni/native.h
- src/android/app/src/main/jni/native_config.cpp
- src/android/app/src/main/jni/native_log.cpp
- src/common/CMakeLists.txt
- src/common/android/android_common.cpp
- src/common/android/android_common.h
- src/common/android/applets/software_keyboard.cpp
- src/common/android/applets/software_keyboard.h
- src/common/android/id_cache.cpp
- src/common/android/id_cache.h
- src/common/fs/fs_android.cpp
- src/common/fs/fs_android.h
Makes it easier to call JNI from other parts of the project.
Additionally provides a fix for #12873 for running the OnEmulationStarted callback where the app would crash when trying to call JNI on a fiber. This provides a workaround by starting a new thread and waiting for the result.
> android: Move JNI setup and helpers to common

- src/yuzu/multiplayer/lobby_p.h
This fixes #12852 to the intended color in dark and midnight themes.
<h2>Preview</h2>
Before             |  After
:-------------------------:|:-------------------------:
> Fix multiplayer player count color in dark themes | Temp fix until #12744: Add green color for counts > 0 and < max_players - 1

- src/video_core/host_shaders/vulkan_present.vert
Older Adreno drivers crash when comparing exact values of gl_VertexIndex. How does a bug like this even exist????
> host_shaders: add vendor workaround for adreno drivers

- src/frontend_common/config.cpp
This fixes a bug from #11889 where per-game input config would not be cleared upon selecting "Use global input configuration"
I mistakenly interpreted "If key is an empty string, all keys in the current group() are removed." where I thought that only settings with no value should be removed. This was obviously in reference to how you pass in an empty `QString` to `QSettings::remove` in order to delete an entire section. 🤦
> config: Always delete control settings in ClearControlPlayerValues

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GamePropertiesFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/MessageDialogFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/model/MessageDialogViewModel.kt
I've received a couple reports for this so clearly some people are speeding through the UI quickly enough to accidently delete their save data.
I swapped the "OK" and "Cancel" buttons to hopefully alleviate this.
> android: Swap confirmation buttons for delete save data dialog

- src/yuzu/hotkeys.cpp
Allows to use basic hotkeys that don't require a npad button. Fixes #12988
> yuzu: Allow non npad hotkeys and disable controller navigation requirement

- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/IntSetting.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/Settings.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/view/SettingsItem.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsFragmentPresenter.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
- src/android/app/src/main/jni/android_settings.h
- src/android/app/src/main/res/values/arrays.xml
- src/android/app/src/main/res/values/strings.xml
Had a couple requests for settings that I expose/add
- FSR sharpness slider: Changes how sharp the image will look when using FSR
- Vertical alignment: Allows you to move the emulation surface to the top/bottom/center of your display
> android: Expose FSR slider and add vertical alignment setting

- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AddonsFragment.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/MessageDialogFragment.kt
- Fixes an issue where "Close" appeared where "OK" should in message dialogs
- Show a cancel option for the delete addons dialog
- Prevent the user from dismissing the mod/cheats notice (Can only be dismissed via "OK" or "Close")
> android: Message dialog tweaks

- src/core/core.cpp
- src/core/hle/kernel/k_thread.h
- src/core/hle/kernel/kernel.cpp
- src/core/hle/kernel/kernel.h
Currently suspension does not put processes other than the main process to sleep. With applets running, it is now possible for this to have noticeable side effects. This fixes the problem by moving away from SetActivity and adding a new suspend type for the system level suspends we want to enforce.
> kernel: add and enable system suspend type

- src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
- src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/CoreErrorDialogFragment.kt
Cleaning up the clutter in NativeLibrary
> android: Move CoreErrorDialogFragment to its own file

- src/android/app/src/main/jni/emu_window/emu_window.cpp
- src/android/app/src/main/jni/emu_window/emu_window.h
- src/android/app/src/main/jni/native_input.cpp
I neglected to map touches to the touchscreen when refactoring in the input mapping PR. This fixes that regression.
Closes #13058
> android: Map touches to touchscreen

- src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
Fixes an issue where player 1 could be mapped silently with the controller on port 0 even if you wanted to use touch controls for P1 and a controller for P2
> android: Only do first startup automapping if nothing has been mapped

- src/core/hle/service/acc/profile_manager.cpp
- src/core/hle/service/am/applet_manager.cpp
- src/core/hle/service/am/service/library_applet_self_accessor.cpp
- src/core/hle/service/am/service/library_applet_self_accessor.h
- src/core/hle/service/caps/caps_a.cpp
- src/core/hle/service/caps/caps_a.h
- src/core/hle/service/erpt/erpt.cpp
Implements the launcher for Qlaunch. Fixes the user creation applet. Implements caps_a::GetAlbumFIleList and erpt::SubmitContext.
No user facing changes are done on this PR.
> service: Implement functions needed by Qlaunch

- src/hid_core/frontend/emulated_controller.cpp
Some engines are hardcoded into emulated controller to overload our input capabilities. These two aren't always compiled so it will trigger an error on input_common. Fix this by clearing out the parameters when they aren't compiled.
> core: hid: Remove driver errors from log

- src/core/hle/service/am/library_applet_storage.cpp
Fixes #13033 and all other cases where the applet keyboard was not displaying the input string correctly
Fixes #13039
> am: account for offset in transfer memory storage

- src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
- src/shader_recompiler/backend/spirv/emit_spirv_instructions.h
Fixes #13025
Can't use ConstOffset with the scaler because resolution info is dynamic, so...
>  shader_recompiler: fix non-const offset for arrayed image types 

- src/video_core/buffer_cache/buffer_cache.h
The limit register for vertex buffers is purely advisory. Since I'm pretty sure we don't support sparse buffers at all, this will ensure we don't expand to fill all available memory with buffers if the guest driver passes something like 4GB and has something mapped on the high end.
Fixes #12185
> buffer_cache: use mapped range with large vertex buffer size

- src/android/app/src/main/java/org/yuzu/yuzu_emu/features/input/model/PlayerInput.kt
- src/android/app/src/main/jni/native.cpp
- src/android/app/src/main/jni/native_input.cpp
- Re-enable all controller styles on emulation shutdown
- Add additional check for startup auto-mapping when you have no mapped controllers
- Change controller style to a supported one on connection if the configured style isn't allowed for a running game
> android: Misc controller fixes

- src/shader_recompiler/backend/spirv/emit_spirv.cpp
- src/shader_recompiler/backend/spirv/emit_spirv_special.cpp
- src/shader_recompiler/profile.h
- src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
- src/video_core/vulkan_common/vulkan_device.h
Really fixes #13074. (Mali specific issue)
I tried not using geometry streams and it passes validation but crashes in the driver shader compiler so this is as good as it's going to get
> shader_recompiler: throw on missing geometry streams in geometry shaders

- src/common/settings.h
- src/common/settings_enums.h
- src/video_core/vulkan_common/vulkan_device.cpp
- src/yuzu/configuration/shared_translation.cpp
This was intended to keep vram usage from expanding to fill the entire gpu on dedicated cards. I am not convinced this limit is really necessary and it is causing issues with native resolution mods.
> vulkan_device: don't use fixed cap for memory limits

- src/common/ring_buffer.h
Rather unimportant IWYU patch, but I use the RingBuffer class as a small library in another project and the missing <limits> header makes the build fail when trying to instantiate std::numeric_limits<std::size_t> in line 29
> common/ring_buffer: Include <limits> header

- src/core/hle/service/set/setting_formats/system_settings.cpp
- src/core/hle/service/set/system_settings_server.cpp
I keep forgetting to enable settings when implementing the services. This fixes amiibo detection regressed by #13140
> service: set: Enable nfc and others by default and bump version

- src/core/hle/service/glue/time/manager.cpp
Fixes startup error from #13155
> glue: load initial year setting as s32

- src/hid_core/frontend/emulated_controller.cpp
- src/hid_core/frontend/emulated_controller.h
- src/hid_core/hid_types.h
- src/hid_core/resources/npad/npad.cpp
Modern controllers clearly can't handle this. Add the vibration filter back to remove controller lag issues.
> core: hid: Reintroduce vibration filter

- src/hid_core/frontend/emulated_controller.cpp
One step forward and two back. LIBUSB is only available on input_common. So the ring param never got compiled on systems that support it. This fixes the ring with joycons.
> core: hid: hid_core doesn't have access to LIBUSB

- src/common/settings.h
- src/core/CMakeLists.txt
- src/core/hle/service/acc/acc.cpp
- src/core/hle/service/acc/acc_u1.cpp
- src/core/hle/service/am/am_types.h
- src/core/hle/service/am/service/common_state_getter.cpp
- src/core/hle/service/am/service/common_state_getter.h
- src/core/hle/service/erpt/erpt.cpp
- src/core/hle/service/filesystem/fsp/fsp_srv.cpp
- src/core/hle/service/filesystem/fsp/fsp_srv.h
- src/core/hle/service/ldn/monitor_service.cpp
- src/core/hle/service/ldn/monitor_service.h
- src/core/hle/service/set/settings_types.h
- src/core/hle/service/set/system_settings_server.cpp
- src/core/hle/service/set/system_settings_server.h
- src/core/hle/service/ssl/cert_store.cpp
- src/core/hle/service/ssl/cert_store.h
- src/core/hle/service/ssl/ssl.cpp
- src/core/hle/service/ssl/ssl_types.h
- src/yuzu/configuration/configure_applets.cpp
This adds support for and enables the error applet by default, and adds preliminary support for the online web applet.
|Error|Web|
|-|-|
|![0100152000022000_2024-02-24_22-30-32-915](https://github.com/yuzu-emu/yuzu/assets/9658600/9826aa3a-b93d-41a0-ba45-8562f65c5e40)|![0100ea80032ea000_2024-02-24_22-36-40-756](https://github.com/yuzu-emu/yuzu/assets/9658600/a6089bcc-7de5-4bcf-8353-5370aac53593)|
> core: enable error applet, add stubs for web applet

- src/video_core/buffer_cache/usage_tracker.h
Found from a user crash dump when closing the keyboard applet.
> buffer_cache: avoid overflow in usage tracker

- src/video_core/engines/draw_manager.cpp
- src/video_core/renderer_opengl/gl_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_rasterizer.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.cpp
- src/video_core/renderer_vulkan/vk_texture_cache.h
Fixes cut off rendering in handheld mode on Tomb Raider I-III Remastered. Oversight of #12235
> vk_rasterizer: flip scissor y on lower left origin mode

- src/video_core/buffer_cache/buffer_cache.h
- src/video_core/renderer_vulkan/vk_query_cache.cpp
Drafting as these are workarounds for a general pattern of behavior where a resource is unmapped from the SMMU before the GPU has released it, which will take more time to fix.
1. ~~Counters can still trigger reprotection when they are not supposed to due to incomplete locking and wrong use of atomics. Protect the entire range before performing any mapping operation.~~
2. ~~Some resources can get stuck in a state where they are still marked as protected but are no longer device mapped. I investigated this for a while but couldn't find the cause.~~
3. Fix crashes resulting from unmapped usages. Fixes #12741
Hacky workarounds removed, can now be merged.
> general: workarounds for SMMU syncing issues

- src/video_core/texture_cache/texture_cache.h
The texture cache intentionally generates invalid device addresses for gpu mappings it cannot resolve:
https://github.com/yuzu-emu/yuzu/blob/f9bfdb15559c7ce447151162af61cc69efcbec01/src/video_core/texture_cache/texture_cache.h#L1355-L1357
Tracking these will lead to a crash, so don't do that. "Fixes" #13169
> texture_cache: do not track invalid addresses

- src/core/file_sys/fssystem/fssystem_aes_xts_storage.cpp
- src/core/hle/service/server_manager.cpp
(Harmless) buffer overflow in xts storage and use-after-free in server manager (oops)
Rest is surprisingly clean but requires use of detect_stack_use_after_return=false or it inserts poison bytes into kernel data structures which live on the stack.
> general: fix asan errors
